### ISSUE TITLE
[execution-environments] Imports in inventory scripts do not appear to work

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#10012]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Scenario is that someone would like to use old of the old inventory scripts like this:

https://github.com/ansible-collections/community.aws/blob/main/scripts/inventory/ec2.py

(note: use https://github.com/ansible-collections/community.aws/compare/main...AlanCoding:executable due to a bug with executable bit)

All non-trivial legacy scripts require importing from the Ansible code base. This appears to not be working within execution environments. Inventory update output:

```
ansible-inventory [core 2.11.0b4] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
host_list declined parsing /runner/project/scripts/inventory/ec2.py as it did not pass its verify_file() method
auto declined parsing /runner/project/scripts/inventory/ec2.py as it did not pass its verify_file() method
yaml declined parsing /runner/project/scripts/inventory/ec2.py as it did not pass its verify_file() method
toml declined parsing /runner/project/scripts/inventory/ec2.py as it did not pass its verify_file() method
[WARNING]:  * Failed to parse /runner/project/scripts/inventory/ec2.py with
script plugin: Inventory script (/runner/project/scripts/inventory/ec2.py) had
an execution error: Traceback (most recent call last):   File
"/runner/project/scripts/inventory/ec2.py", line 158, in <module>     from
ansible_collections.amazon.aws.plugins.module_utils import ec2 as ec2_utils
ModuleNotFoundError: No module named 'ansible_collections'
  File "/usr/local/lib/python3.8/site-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/inventory/script.py", line 169, in parse
```

The `amazon.aws` collection is available in the EE being used.

https://github.com/ansible/awx-ee/blob/devel/_build/requirements.yml#L5

but it is not importable. It stands to reason that collections should be set up as importable for doing inventory imports.

**Comment by AlanCoding** [comment]
@Zokormazo you can close this issue if you agree it's not supported.

**Comment by kdelee** [comment]
@wenottingham says if the script is not compatible with the version of ansible in the EE, you must port it or use a different ansible version
