### ISSUE TITLE
AWX EE 0.2.0 doesn't work fine

### ISSUE THREAD

**Issue by Uzzi** [ansible/awx#10061]
##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: k3s, docker
* Operating System: Debian 10
* Web Browser: Firefox

I've two EE:
   AWX EE 0.1.1
   quay.io/ansible/awx-ee:0.1.1
   AWX EE 0.2.0
    quay.io/ansible/awx-ee:0.2.0

Launching job with AWX EE 0.2.0:
`Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1397, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2957, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3008, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Pod Running`

Same job with AWX EE 0.1.1:
`ERROR! couldn't resolve module/action 'win_shell'. This often indicates a misspelling, missing collection, or incorrect module path.`

**Comment by shanemcd** [comment]
The version of AWX that uses 0.2.0 hasn't been released yet. Expect that later today or Monday.
