### ISSUE TITLE
Container Registry credentials don't work with Container Groups

### ISSUE THREAD

**Issue by phemmer** [ansible/awx#10114]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
This is a reopen of #9928. #9928 was closed stating #9623 addresses the issue and would be resolved in the next release. However #9623 was included in release 19.1.0 and the issue still persists.

Execution environments can't be pulled from private registries as the authentication credentials are not being passed to the pod spec.

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: minikube
* Ansible version:  ?
* Operating System: Debian
* Web Browser: Chrome

##### STEPS TO REPRODUCE

![image](https://user-images.githubusercontent.com/1826947/117161065-a11ea200-ad8f-11eb-8b4f-a4e465224873.png)

![image](https://user-images.githubusercontent.com/1826947/117161122-a976dd00-ad8f-11eb-9aa3-6bbddf4c5c5c.png)

![image](https://user-images.githubusercontent.com/1826947/117161147-b0055480-ad8f-11eb-9a97-15d0a9b1af0c.png)

```

# kubectl describe pod awx-job-53-cvh88
Name:         awx-job-53-cvh88
Namespace:    default
Priority:     0
Node:         minikube/192.168.49.2
Start Time:   Wed, 05 May 2021 14:06:06 +0000
Labels:       ansible-awx=f34e7217-6215-41db-b716-970e1b09be7d
              ansible-awx-job-id=53
Annotations:  <none>
Status:       Pending
IP:           172.17.0.6
IPs:
  IP:  172.17.0.6
Containers:
  worker:
    Container ID:  
    Image:         gitlab.example.com:5443/myproject/ansible-runner
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      ansible-runner
      worker
      --private-data-dir=/runner
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-qfwv8 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-qfwv8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-qfwv8
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  44m                    default-scheduler  Successfully assigned default/awx-job-53-cvh88 to minikube
  Normal   Pulling    43m (x4 over 44m)      kubelet            Pulling image "gitlab.example.com:5443/myproject/ansible-runner"
  Warning  Failed     43m (x4 over 44m)      kubelet            Failed to pull image "gitlab.example.com:5443/myproject/ansible-runner": rpc error: code = Unknown desc = Error response from daemon: Head https://gitlab.example.com:5443/v2/myproject/ansible-runner/manifests/latest: denied: access forbidden
  Warning  Failed     43m (x4 over 44m)      kubelet            Error: ErrImagePull
  Normal   BackOff    9m25s (x155 over 44m)  kubelet            Back-off pulling image "gitlab.example.com:5443/myproject/ansible-runner"
  Warning  Failed     4m25s (x177 over 44m)  kubelet            Error: ImagePullBackOff
```

##### EXPECTED RESULTS

Image to download & run successfully

##### ACTUAL RESULTS

Image download responds with `access forbidden` because of lack of credentials.

**Comment by shanemcd** [comment]
I apologize for the confusion here. There are several problems here. The container registry credential type is only used when we are running jobs directly on a control plane node via podman (this isn't something you can do upstream atm).

For jobs running as Kubernetes pods, you will need to attach an imagePullSecret to the service account your pods are running under, wherever they are running. We should look at documenting this better.

**Comment by phemmer** [comment]
Ah, should this be re-opened then?

I originally had closed it because I noticed the issue template had `minishift` as the available install method, not `minikube`, so I was thinking that minikube wasn't a supported method and that minishift was required. So I closed it to go back and review. But upon reading the documentation, I see that minikube is the documented method, and minishift isn't even mentioned. So that's also confusing.

**Comment by Zokormazo** [comment]
@rooftopcellist 

Following here since the PR is merged.

I'm not using the operator. I'm registering a container group using different permisson level service accounts
All the service accounts I used have enough pod permissions to run jobs using the default public ee.

1. service account with no `secrets` roles

    After running a job I got this:
```json
{
    "id": 102,
    "type": "job",
    "url": "/api/v2/jobs/102/",
    "related": {
        "created_by": "/api/v2/users/1/",
        "labels": "/api/v2/jobs/102/labels/",
        "inventory": "/api/v2/inventories/39/",
        "project": "/api/v2/projects/76/",
        "organization": "/api/v2/organizations/71/",
        "credentials": "/api/v2/jobs/102/credentials/",
        "unified_job_template": "/api/v2/job_templates/77/",
        "stdout": "/api/v2/jobs/102/stdout/",
        "execution_environment": "/api/v2/execution_environments/5/",
        "job_events": "/api/v2/jobs/102/job_events/",
        "job_host_summaries": "/api/v2/jobs/102/job_host_summaries/",
        "activity_stream": "/api/v2/jobs/102/activity_stream/",
        "notifications": "/api/v2/jobs/102/notifications/",
        "create_schedule": "/api/v2/jobs/102/create_schedule/",
        "job_template": "/api/v2/job_templates/77/",
        "cancel": "/api/v2/jobs/102/cancel/",
        "relaunch": "/api/v2/jobs/102/relaunch/"
    },
    "summary_fields": {
        "organization": {
            "id": 71,
            "name": "Organization - HeatImpact\ufffd",
            "description": "FoldHourFaceProcessDressDrawerChanceSignatureHealthFlight\ufffd"
        },
        "inventory": {
            "id": 39,
            "name": "Inventory - TrainerPlayer\ufffd",
            "description": "TrainerParkWhileFriendshipFeedbackRevolutionChestIllegalInternationalTechnology\ufffd",
            "has_active_failures": false,
            "total_hosts": 1,
            "hosts_with_active_failures": 0,
            "total_groups": 0,
            "has_inventory_sources": false,
            "total_inventory_sources": 0,
            "inventory_sources_with_failures": 0,
            "organization_id": 71,
            "kind": ""
        },
        "execution_environment": {
            "id": 5,
            "name": "EE - BuildingRoyal\u3fb2",
            "description": "",
            "image": "private.registry/awx-ee"
        },
        "project": {
            "id": 76,
            "name": "Project - GuidanceRound\ufffd",
            "description": "MeetHighlightStageTwistParticularSituationTwistWholeLectureCry\u1631",
            "status": "successful",
            "scm_type": "git",
            "allow_override": false
        },
        "job_template": {
            "id": 77,
            "name": "JobTemplate - FinalPrompt\ufffd",
            "description": "MaintenanceBoardFaultContributionHeatRoleTimeRefrigeratorGeneBack\ufffd"
        },
        "unified_job_template": {
            "id": 77,
            "name": "JobTemplate - FinalPrompt\ufffd",
            "description": "MaintenanceBoardFaultContributionHeatRoleTimeRefrigeratorGeneBack\ufffd",
            "unified_job_type": "job"
        },
        "instance_group": {
            "id": 23,
            "name": "ContainerGroup - dytyujeaea",
            "is_container_group": true
        },
        "created_by": {
            "id": 1,
            "username": "admin",
            "first_name": "",
            "last_name": ""
        },
        "user_capabilities": {
            "delete": true,
            "start": true
        },
        "labels": {
            "count": 0,
            "results": []
        },
        "credentials": [
            {
                "id": 66,
                "name": "Credential - SadDare\ufffd",
                "description": "PackageLightCoverPropertyPieceInternalTrafficDrawLeaderSentence\u48a2",
                "kind": "ssh",
                "cloud": false
            }
        ]
    },
    "created": "2021-05-26T07:25:06.561452Z",
    "modified": "2021-05-26T07:25:06.814565Z",
    "name": "JobTemplate - FinalPrompt\ufffd",
    "description": "MaintenanceBoardFaultContributionHeatRoleTimeRefrigeratorGeneBack\ufffd",
    "job_type": "run",
    "inventory": 39,
    "project": 76,
    "playbook": "ping.yml",
    "scm_branch": "",
    "forks": 0,
    "limit": "",
    "verbosity": 0,
    "extra_vars": "{}",
    "job_tags": "",
    "force_handlers": false,
    "skip_tags": "",
    "start_at_task": "",
    "timeout": 0,
    "use_fact_cache": false,
    "organization": 71,
    "unified_job_template": 77,
    "launch_type": "manual",
    "status": "error",
    "execution_environment": 5,
    "failed": true,
    "started": "2021-05-26T07:25:06.875363Z",
    "finished": "2021-05-26T07:25:07.302776Z",
    "canceled_on": null,
    "elapsed": 0.427,
    "job_args": "",
    "job_cwd": "",
    "job_env": {},
    "job_explanation": "",
    "execution_node": "",
    "controller_node": "localhost",
    "result_traceback": "Traceback (most recent call last):\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/scheduler/kubernetes.py\", line 88, in create_secret\n    existing_secret = self.kube_api.read_namespaced_secret(namespace=self.namespace, name=secret_name)\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api/core_v1_api.py\", line 20110, in read_namespaced_secret\n    (data) = self.read_namespaced_secret_with_http_info(name, namespace, **kwargs)  # noqa: E501\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api/core_v1_api.py\", line 20187, in read_namespaced_secret_with_http_info\n    return self.api_client.call_api(\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api_client.py\", line 340, in call_api\n    return self.__call_api(resource_path, method,\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api_client.py\", line 172, in __call_api\n    response_data = self.request(\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api_client.py\", line 362, in request\n    return self.rest_client.GET(url,\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/rest.py\", line 237, in GET\n    return self.request(\"GET\", url,\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/rest.py\", line 231, in request\n    raise ApiException(http_resp=r)\nkubernetes.client.rest.ApiException: (403)\nReason: Forbidden\nHTTP response headers: HTTPHeaderDict({'Audit-Id': '39bb7429-ef0a-4dc7-abfc-8d2fa8ab21b2', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 26 May 2021 07:25:07 GMT', 'Content-Length': '403'})\nHTTP response body: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"secrets \\\"automation-c7bfc-image-pull-secret-65\\\" is forbidden: User \\\"system:serviceaccount:dytyujeaea:serviceaccount-dytyujeaea\\\" cannot get resource \\\"secrets\\\" in API group \\\"\\\" in the namespace \\\"dytyujeaea\\\"\",\"reason\":\"Forbidden\",\"details\":{\"name\":\"automation-c7bfc-image-pull-secret-65\",\"kind\":\"secrets\"},\"code\":403}\n\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py\", line 1382, in run\n    res = receptor_job.run()\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py\", line 2921, in run\n    return self._run_internal(receptor_ctl)\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py\", line 2938, in _run_internal\n    result = receptor_ctl.submit_work(worktype=self.work_type, payload=sockout.makefile('rb'), params=self.receptor_params)\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py\", line 3016, in receptor_params\n    spec_yaml = yaml.dump(self.pod_definition, explicit_start=True)\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py\", line 3090, in pod_definition\n    secret_name = pm.create_secret(job=self.task.instance)\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/scheduler/kubernetes.py\", line 105, in create_secret\n    raise PermissionError(full_error_msg)\nPermissionError: Failed to create secret for container group ContainerGroup - dytyujeaea because the needed service account roles are needed.  Add get, list, create and delete roles for secret resources for your cluster credential.: (403)\nReason: Forbidden\nHTTP response headers: HTTPHeaderDict({'Audit-Id': '39bb7429-ef0a-4dc7-abfc-8d2fa8ab21b2', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 26 May 2021 07:25:07 GMT', 'Content-Length': '403'})\nHTTP response body: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"secrets \\\"automation-c7bfc-image-pull-secret-65\\\" is forbidden: User \\\"system:serviceaccount:dytyujeaea:serviceaccount-dytyujeaea\\\" cannot get resource \\\"secrets\\\" in API group \\\"\\\" in the namespace \\\"dytyujeaea\\\"\",\"reason\":\"Forbidden\",\"details\":{\"name\":\"automation-c7bfc-image-pull-secret-65\",\"kind\":\"secrets\"},\"code\":403}\n\n\n",
    "event_processing_finished": true,
    "launched_by": {
        "id": 1,
        "name": "admin",
        "type": "user",
        "url": "/api/v2/users/1/"
    },
    "job_template": 77,
    "passwords_needed_to_start": [],
    "allow_simultaneous": false,
    "artifacts": {},
    "scm_revision": "f4754c24e094e9ed24a24ba9d1d90b69190e45f4",
    "instance_group": 23,
    "diff_mode": false,
    "job_slice_number": 0,
    "job_slice_count": 1,
    "webhook_service": "",
    "webhook_credential": null,
    "webhook_guid": "",
    "host_status_counts": {},
    "playbook_counts": {
        "play_count": 0,
        "task_count": 0
    },
    "custom_virtualenv": "/var/lib/awx/venv/ansible"
}
```
Now status is `error` instead of canceled. Much better, but the job explanation now is `''`. Would be great to add something there.

```
2021-05-26 07:41:17,353 ERROR    [f814c0aaa0ea464fb35906a7c741ec03] awx.main.scheduler Failed to create secret for container group ContainerGroup - 8u1gtffven because the needed service account roles are needed.  Add get, list, create and delete roles for secret resources for your cluster credential.: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'ef519542-a67c-4f7a-8735-260edc6f325b', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 26 May 2021 07:41:17 GMT', 'Content-Length': '403'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets \"automation-c7bfc-image-pull-secret-74\" is forbidden: User \"system:serviceaccount:8u1gtffven:serviceaccount-8u1gtffven\" cannot get resource \"secrets\" in API group \"\" in the namespace \"8u1gtffven\"","reason":"Forbidden","details":{"name":"automation-c7bfc-image-pull-secret-74","kind":"secrets"},"code":403}

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/scheduler/kubernetes.py", line 88, in create_secret
    existing_secret = self.kube_api.read_namespaced_secret(namespace=self.namespace, name=secret_name)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 20110, in read_namespaced_secret
    (data) = self.read_namespaced_secret_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 20187, in read_namespaced_secret_with_http_info
    return self.api_client.call_api(
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api_client.py", line 340, in call_api
    return self.__call_api(resource_path, method,
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api_client.py", line 172, in __call_api
    response_data = self.request(
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api_client.py", line 362, in request
    return self.rest_client.GET(url,
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/rest.py", line 237, in GET
    return self.request("GET", url,
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'ef519542-a67c-4f7a-8735-260edc6f325b', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 26 May 2021 07:41:17 GMT', 'Content-Length': '403'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets \"automation-c7bfc-image-pull-secret-74\" is forbidden: User \"system:serviceaccount:8u1gtffven:serviceaccount-8u1gtffven\" cannot get resource \"secrets\" in API group \"\" in the namespace \"8u1gtffven\"","reason":"Forbidden","details":{"name":"automation-c7bfc-image-pull-secret-74","kind":"secrets"},"code":403}


2021-05-26 07:41:17,359 ERROR    [f814c0aaa0ea464fb35906a7c741ec03] awx.main.tasks job 107 (running) Exception occurred while running task
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/scheduler/kubernetes.py", line 88, in create_secret
    existing_secret = self.kube_api.read_namespaced_secret(namespace=self.namespace, name=secret_name)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 20110, in read_namespaced_secret
    (data) = self.read_namespaced_secret_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 20187, in read_namespaced_secret_with_http_info
    return self.api_client.call_api(
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api_client.py", line 340, in call_api
    return self.__call_api(resource_path, method,
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api_client.py", line 172, in __call_api
    response_data = self.request(
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api_client.py", line 362, in request
    return self.rest_client.GET(url,
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/rest.py", line 237, in GET
    return self.request("GET", url,
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'ef519542-a67c-4f7a-8735-260edc6f325b', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 26 May 2021 07:41:17 GMT', 'Content-Length': '403'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets \"automation-c7bfc-image-pull-secret-74\" is forbidden: User \"system:serviceaccount:8u1gtffven:serviceaccount-8u1gtffven\" cannot get resource \"secrets\" in API group \"\" in the namespace \"8u1gtffven\"","reason":"Forbidden","details":{"name":"automation-c7bfc-image-pull-secret-74","kind":"secrets"},"code":403}



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1382, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2921, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2938, in _run_internal
    result = receptor_ctl.submit_work(worktype=self.work_type, payload=sockout.makefile('rb'), params=self.receptor_params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3016, in receptor_params
    spec_yaml = yaml.dump(self.pod_definition, explicit_start=True)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3090, in pod_definition
    secret_name = pm.create_secret(job=self.task.instance)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/scheduler/kubernetes.py", line 105, in create_secret
    raise PermissionError(full_error_msg)
PermissionError: Failed to create secret for container group ContainerGroup - 8u1gtffven because the needed service account roles are needed.  Add get, list, create and delete roles for secret resources for your cluster credential.: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'ef519542-a67c-4f7a-8735-260edc6f325b', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 26 May 2021 07:41:17 GMT', 'Content-Length': '403'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets \"automation-c7bfc-image-pull-secret-74\" is forbidden: User \"system:serviceaccount:8u1gtffven:serviceaccount-8u1gtffven\" cannot get resource \"secrets\" in API group \"\" in the namespace \"8u1gtffven\"","reason":"Forbidden","details":{"name":"automation-c7bfc-image-pull-secret-74","kind":"secrets"},"code":403}
```

I like the error message here, but we should inject the PermissionError on job_explanation

2. serviceaccount with all `secrets` verbs:

```
{
    "id": 104,
    "type": "job",
    "url": "/api/v2/jobs/104/",
    "related": {
        "created_by": "/api/v2/users/1/",
        "labels": "/api/v2/jobs/104/labels/",
        "inventory": "/api/v2/inventories/40/",
        "project": "/api/v2/projects/78/",
        "organization": "/api/v2/organizations/75/",
        "credentials": "/api/v2/jobs/104/credentials/",
        "unified_job_template": "/api/v2/job_templates/79/",
        "stdout": "/api/v2/jobs/104/stdout/",
        "execution_environment": "/api/v2/execution_environments/6/",
        "job_events": "/api/v2/jobs/104/job_events/",
        "job_host_summaries": "/api/v2/jobs/104/job_host_summaries/",
        "activity_stream": "/api/v2/jobs/104/activity_stream/",
        "notifications": "/api/v2/jobs/104/notifications/",
        "create_schedule": "/api/v2/jobs/104/create_schedule/",
        "job_template": "/api/v2/job_templates/79/",
        "cancel": "/api/v2/jobs/104/cancel/",
        "relaunch": "/api/v2/jobs/104/relaunch/"
    },
    "summary_fields": {
        "organization": {
            "id": 75,
            "name": "Organization - ChampionshipFinance\u3dda",
            "description": "PromptBetSupermarketFoodExaminationInterviewZoneProposalShopDamage\u64f2"
        },
        "inventory": {
            "id": 40,
            "name": "Inventory - StateDebt\u2709",
            "description": "PotatoOppositeAirportRecoverIndependenceProfileWeightRollNightPull\u7f93",
            "has_active_failures": false,
            "total_hosts": 1,
            "hosts_with_active_failures": 0,
            "total_groups": 0,
            "has_inventory_sources": false,
            "total_inventory_sources": 0,
            "inventory_sources_with_failures": 0,
            "organization_id": 75,
            "kind": ""
        },
        "execution_environment": {
            "id": 6,
            "name": "EE - BoringOpening\u4188",
            "description": "",
            "image": "private.registry/awx-ee"
        },
        "project": {
            "id": 78,
            "name": "Project - ShockOutcome\ufffd",
            "description": "UnionExpertToolClothesLocalPresidentBirdMorningReserveExtent\ufffd",
            "status": "successful",
            "scm_type": "git",
            "allow_override": false
        },
        "job_template": {
            "id": 79,
            "name": "JobTemplate - TransitionSuccess\ufffd",
            "description": "ConsistChestPrimaryTemporaryCoverCollectionEffectTopProfileUnderstanding\u2269"
        },
        "unified_job_template": {
            "id": 79,
            "name": "JobTemplate - TransitionSuccess\ufffd",
            "description": "ConsistChestPrimaryTemporaryCoverCollectionEffectTopProfileUnderstanding\u2269",
            "unified_job_type": "job"
        },
        "instance_group": {
            "id": 24,
            "name": "ContainerGroup - fscope-bdzipqj9z3",
            "is_container_group": true
        },
        "created_by": {
            "id": 1,
            "username": "admin",
            "first_name": "",
            "last_name": ""
        },
        "user_capabilities": {
            "delete": true,
            "start": true
        },
        "labels": {
            "count": 0,
            "results": []
        },
        "credentials": [
            {
                "id": 69,
                "name": "Credential - GodExplanation\ufffd",
                "description": "IndependenceLadderPutFearPrizeProductPresidentIndicationSizeBlack\ufffd",
                "kind": "ssh",
                "cloud": false
            }
        ]
    },
    "created": "2021-05-26T07:33:02.176967Z",
    "modified": "2021-05-26T07:33:02.430049Z",
    "name": "JobTemplate - TransitionSuccess\ufffd",
    "description": "ConsistChestPrimaryTemporaryCoverCollectionEffectTopProfileUnderstanding\u2269",
    "job_type": "run",
    "inventory": 40,
    "project": 78,
    "playbook": "ping.yml",
    "scm_branch": "",
    "forks": 0,
    "limit": "",
    "verbosity": 0,
    "extra_vars": "{}",
    "job_tags": "",
    "force_handlers": false,
    "skip_tags": "",
    "start_at_task": "",
    "timeout": 0,
    "use_fact_cache": false,
    "organization": 75,
    "unified_job_template": 79,
    "launch_type": "manual",
    "status": "error",
    "execution_environment": 6,
    "failed": true,
    "started": "2021-05-26T07:33:02.488814Z",
    "finished": "2021-05-26T07:33:06.159826Z",
    "canceled_on": null,
    "elapsed": 3.671,
    "job_args": "",
    "job_cwd": "",
    "job_env": {
        "RECEPTOR_UNIT_ID": "06WDd4Nv"
    },
    "job_explanation": "",
    "execution_node": "",
    "controller_node": "localhost",
    "result_traceback": "Traceback (most recent call last):\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py\", line 1382, in run\n    res = receptor_job.run()\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py\", line 2921, in run\n    return self._run_internal(receptor_ctl)\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py\", line 2984, in _run_internal\n    raise RuntimeError(detail)\nRuntimeError: Pod Running\n",
    "event_processing_finished": true,
    "launched_by": {
        "id": 1,
        "name": "admin",
        "type": "user",
        "url": "/api/v2/users/1/"
    },
    "job_template": 79,
    "passwords_needed_to_start": [],
    "allow_simultaneous": false,
    "artifacts": {},
    "scm_revision": "f4754c24e094e9ed24a24ba9d1d90b69190e45f4",
    "instance_group": 24,
    "diff_mode": false,
    "job_slice_number": 0,
    "job_slice_count": 1,
    "webhook_service": "",
    "webhook_credential": null,
    "webhook_guid": "",
    "host_status_counts": {},
    "playbook_counts": {
        "play_count": 0,
        "task_count": 0
    },
    "custom_virtualenv": "/var/lib/awx/venv/ansible"
}
```

task_system.log
```
2021-05-26 07:33:06,151 ERROR    [b78e2e0917c849279bfe21faf01fecac] awx.main.tasks job 104 (running) Exception occurred while running task
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1382, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2921, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2984, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Pod Running
```

The secret was created properly and it works. I can use it to deploy this manually:
```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: private-reg-container
    image: private.registry/awx-ee
  imagePullSecrets:
  - name: automation-e5c74-image-pull-secret-133
```

This pulls the container image properly

3. with kubeadmin as serviceaccount aka full permissions
    Same result as 2.

I would like to test another scenario: serviceaccount with just `get` verb on `secrets` and precreated `secrets` for credentials. But since I can't run jobs as `kubeadmin` I didn't test that yet

**Comment by Zokormazo** [comment]
this continues failing. the embedded container group on the operator works, but Instance Group -> Container Group can't spawn jobs if using private ees with credentials, even with kubeadmin token. The secret is created and then https://github.com/ansible/awx/issues/10114#issuecomment-848557784

**Comment by rooftopcellist** [comment]
@Zokormazo 
1. I agree, including the error in the job_explanation would be great, unfortunately, because of how the [TaskError class](https://github.com/ansible/awx/blob/devel/awx/main/exceptions.py#L22) works, the job_explanation gets overwritten to be `Error` no matter what I do (more info in this [comment](https://github.com/ansible/awx/pull/10204#issuecomment-848244192)).  I am still unclear on where exactly it gets unset, I will see if I can figure that out.  
2. I just tested this with a service account with the following Role rules and the job ran to completion without error.  

```
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - pods/log
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - pods/attach
  - verbs:
      - get
      - create
      - delete
    apiGroups:
      - ''
    resources:
      - secrets
```

If I remove the `get` verb for the secret resource rule, I get the error you described.  

3. I am seeing the job run to completion when using an OCP Cred made from the kubeadmin token.  
![image](https://user-images.githubusercontent.com/11698892/120667005-121eab80-c45b-11eb-8b97-8bef1a90b893.png)

**Comment by shanemcd** [comment]
We should make sure the example service account in the official docs gets updated.

**Comment by shanemcd** [comment]
@rooftopcellist Can you open a separate issue for improving the error handling / surfacing here?

**Comment by rooftopcellist** [comment]
@shanemcd here is the issue for better error handling - https://github.com/ansible/awx/issues/10364

**Comment by shanemcd** [comment]
I believe this has now been addressed.
