### ISSUE TITLE
19.1: project refreshing fails

### ISSUE THREAD

**Issue by daenney** [ansible/awx#10207]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After upgrading to 19.1.0 I'm no longer able to refresh projects.

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: Kubernetes with AWX operator 0.9.0
* Ansible version:  Whatever is in the EE 0.2.0 execution environment
* Operating System: Amazon Linux 2
* Web Browser: Firefox 86

##### STEPS TO REPRODUCE

* I upgraded my 19.0.0 installation to 19.1.0
* I clicked on the refresh button next to one of my projects

##### EXPECTED RESULTS

No errors

##### ACTUAL RESULTS

I get an error, with rather unhelpful output:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/streaming.py", line 108, in run
    utils.unstream_dir(zip_data, self.private_data_dir)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/utils.py", line 104, in unstream_dir
    data = base64.b85decode(data)
  File "/usr/lib64/python3.8/base64.py", line 463, in b85decode
    raise ValueError('bad base85 character at position %d'
ValueError: bad base85 character at position 84
```

I initially thought this might be due to me having forgotten to rebuild my EE on top of 0.2.0, but even after doing that and launching the job on an EE derived from 0.2.0 I still get this.

Unfortunately this is all the log I get, which makes debugging this difficult without further pointers.

**Comment by shanemcd** [comment]
It seems like you're using an old version of Runner. Make sure you are on 2.0.0a2.

**Comment by daenney** [comment]
If I'm building on EE 0.2.0 shouldn't that be the case by itself?
