### ISSUE TITLE
Not sure what this AWX error means?

### ISSUE THREAD

**Issue by jjasghar** [ansible/awx#10219]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
We got this error in our environment:

```python
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1397, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2957, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3008, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Stream error running pod: unexpected EOF
```

##### ENVIRONMENT
* AWX version: 
```
 ______________ 
<  AWX 19.0.0  >
 -------------- 
          \
          \   ^__^
              (oo)\_______
              (__)      A )\
                  ||----w |
                  ||     ||
```
* AWX install method: operator on kubernetes

##### STEPS TO REPRODUCE

Attempting to run a job and this is the error we get "sometimes"

/cc @moficodes @odrodrig

**Comment by shanemcd** [comment]
We improved error handling a lot in 19.1.0... any chance you can upgrade and see if the message changes?

**Comment by jjasghar** [comment]
Honestly, I'm not 100% sure how to update the Operator install of awx, can you point me to the docs?

**Comment by popicool** [comment]
Still here:

`Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1377, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2904, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2962, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Stream error running pod: unexpected EOF`

`
 ______________ 
<  AWX 19.1.0  >
 -------------- 
          \
          \   ^__^
              (oo)\_______
              (__)      A )\
                  ||----w |
                  ||     ||
`

**Comment by grommir** [comment]
We have a version 19.3.0

It fails with this error almost always on large runs (~1000 hosts).

```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1406, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2935, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3000, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Stream error running pod: unexpected EOF
```

**Comment by vzovko** [comment]
> We have a version 19.3.0
> 
> It fails with this error almost always on large runs (~1000 hosts).
> 
> ```
> Traceback (most recent call last):
>   File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1406, in run
>     res = receptor_job.run()
>   File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2935, in run
>     return self._run_internal(receptor_ctl)
>   File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3000, in _run_internal
>     raise RuntimeError(detail)
> RuntimeError: Stream error running pod: unexpected EOF
> ```

I'm having the exact same error which occures at different stages during playbook execution.  Most of the times it fails at wait_for tasks.

**Comment by sdktr** [comment]
We experience the same issue during an inventory plugin run. This plugin runs for >45 minutes (it is a BIG inventory with lot of slow backend calls) and fails with the same error as above.
Any hints on how to troubleshoot this? The automation-pod that's spun of on the k8s cluster, should we start there or are detailed loggins available within the awx-ee pod for example?

**Comment by sdktr** [comment]
Maybe we hit an error on the stdout? Our plugin by-design only spilts out data after the plugin succeeds, which can take quite a while of no-traffic to the console/stdout. I noticed @vzovko mentions things go southways when hanging on a long 'wait_for' task..

**Comment by vzovko** [comment]
Our issue has been resolved. It turned out that there was a cronjob restarting the whole Kubernetes clusters periodically for whatever reason.

During the investigation of this issue two parallel running job pods were killed at the same time. This lead us in the right direction into finding the cause.

There was nothing of interest logged in the stdout of the running pods when they got killed, just the task infos of the last task, no traceback or anything. So the focus shifted to Kubernetes itself and not AWX.

In case of similar problems like above I would suggest looking into resource management of the pods too. Maybe the get killed because either they are eating up to much resources or are looking to be stale when waiting for too long.
