### ISSUE TITLE
19.1.0 Cant run Playbooks after setup

### ISSUE THREAD

**Issue by gruselglatz** [ansible/awx#10227]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Starting a Ping job to some host or even localhost ending in this:
Idk where the connection gets refused.
AWX-Task can reach every host and the socket files from receptor are all there.

```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1377, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2904, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2920, in _run_internal
    result = receptor_ctl.submit_work(worktype=self.work_type, payload=sockout.makefile('rb'), params=self.receptor_params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/receptorctl/socket_interface.py", line 144, in submit_work
    self.connect()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/receptorctl/socket_interface.py", line 88, in connect
    self._socket.connect(path)
ConnectionRefusedError: [Errno 111] Connection refused

```

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: operator
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by shanemcd** [comment]
What version and flavor of Kubernetes?

**Comment by gruselglatz** [comment]
minikube 1.18.1
awx 19.1.0
ee 0.2.0
operator 0.9.0

**Comment by shanemcd** [comment]
Can you get the logs from the awx-ee container inside of the main awx pod?

**Comment by gruselglatz** [comment]
I didn't find any logs on it. But I am honest, i gave up on 19.1.0 and gone back to 17. So I don't have this installation anymore, sry.
