### ISSUE TITLE
awxkit workflow_job monitor errors out against Ansibe Tower

### ISSUE THREAD

**Issue by isuftin** [ansible/awx#10242]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I am able to launch a job against Ansible Tower via awxkit. However, attempting to monitor the workflow job via `awx  workflow_job monitor` fails.

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: pip via python 3.6.8
* Ansible version: Python 2 & Ansible 2.10.9 on client,  Python 2 & Ansible 2.10.7 on clieTowernt
* Operating System: CentOS 7
* Web Browser: Chrome, curl
* Ansible Tower: 3.8.3

##### STEPS TO REPRODUCE

Create workflow job template which calls on regular job template

Create user with read + execute permissions in Tower that has ability to execute workflow job template

Launch workflow job template via awxkit

Monitor workflow job

`awx workflow_job_templates launch --limit my-ec2-hostname 20`

Results in:

```json
{
     "workflow_job": 572,
     "ignored_fields": {},
     "id": 572,
     "type": "workflow_job",
     "url": "/api/v2/workflow_jobs/572/",
     "summary_fields": {
          "organization": {
               "id": 3,
               "name": "My Organization - Development",
               "description": "Development deployment account for myorg in AWS"
          },
          "inventory": {
               "id": 5,
               "name": "EC2 Development",
               "description": "",
               "has_active_failures": false,
               "total_hosts": 1,
               "hosts_with_active_failures": 0,
               "total_groups": 4,
               "has_inventory_sources": true,
               "total_inventory_sources": 1,
               "inventory_sources_with_failures": 0,
               "organization_id": 3,
               "kind": ""
          },
          "workflow_job_template": {
               "id": 20,
               "name": "base_centos_7",
               "description": "A base CentOS 7 workflow template"
          },
          "unified_job_template": {
               "id": 20,
               "name": "base_centos_7",
               "description": "A base CentOS 7 workflow template",
               "unified_job_type": "workflow_job"
          },
          "created_by": {
               "id": 2,
               "username": "isuftin",
               "first_name": "Ivan",
               "last_name": "Suftin"
          },
          "modified_by": {
               "id": 2,
               "username": "isuftin",
               "first_name": "Ivan",
               "last_name": "Suftin"
          },
          "user_capabilities": {
               "delete": true,
               "start": true
          },
          "labels": {
               "count": 0,
               "results": []
          }
     },
     "created": "2021-05-20T20:57:33.981409Z",
     "modified": "2021-05-20T20:57:34.040583Z",
     "name": "base_centos_7",
     "description": "A base CentOS 7 workflow template",
     "unified_job_template": 20,
     "launch_type": "manual",
     "status": "pending",
     "failed": false,
     "started": null,
     "finished": null,
     "canceled_on": null,
     "elapsed": 0.0,
     "job_args": "",
     "job_cwd": "",
     "job_env": {},
     "job_explanation": "",
     "result_traceback": "",
     "workflow_job_template": 20,
     "extra_vars": "{\"remove_packages\": [\"rsh\", \"talk\", \"telnet-server\", \"rsh-server\", \"ypserv\", \"tftp-server\", \"xinetd\", \"ypbind\", \"openldap-clients\", \"xorg-x11*\"]}",
     "allow_simultaneous": true,
     "job_template": null,
     "is_sliced_job": false,
     "inventory": 5,
     "limit": "my-ec2-hostname",
     "scm_branch": "development",
     "webhook_service": "",
     "webhook_credential": null,
     "webhook_guid": ""
}
```

Using the workflow_job id, I then issue `awx -v workflow_job monitor 572`

```json
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): my.internal.tower.hostname:443
DEBUG:urllib3.connectionpool:https://my.internal.tower.hostname:443 "GET /api/ HTTP/1.1" 200 307
DEBUG:awxkit.api.client:"GET https://my.internal.tower.hostname:443/api/" elapsed: 0:00:00.135593
DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.api.ApiV2'> by url: /api/v2/
DEBUG:urllib3.connectionpool:https://my.internal.tower.hostname:443 "GET /api/v2/ HTTP/1.1" 200 1688
DEBUG:awxkit.api.client:"GET https://my.internal.tower.hostname:443/api/v2/" elapsed: 0:00:00.167629
DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.workflow_jobs.WorkflowJobs'> by url: /api/v2/workflow_jobs/
DEBUG:urllib3.connectionpool:https://my.internal.tower.hostname:443 "OPTIONS /api/v2/workflow_jobs/ HTTP/1.1" 200 12107
DEBUG:awxkit.api.client:"OPTIONS https://my.internal.tower.hostname:443/api/v2/workflow_jobs/" elapsed: 0:00:00.295014
DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.workflow_jobs.WorkflowJobs'> by url: /api/v2/workflow_jobs/
DEBUG:urllib3.connectionpool:https://my.internal.tower.hostname:443 "OPTIONS /api/v2/workflow_jobs/1/ HTTP/1.1" 200 7037
DEBUG:awxkit.api.client:"OPTIONS https://my.internal.tower.hostname:443/api/v2/workflow_jobs/1/" elapsed: 0:00:00.242236
DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.workflow_jobs.WorkflowJob'> by url: /api/v2/workflow_jobs/572/
DEBUG:urllib3.connectionpool:https://my.internal.tower.hostname:443 "GET /api/v2/workflow_jobs/572/ HTTP/1.1" 200 2362
DEBUG:awxkit.api.client:"GET https://my.internal.tower.hostname:443/api/v2/workflow_jobs/572/" elapsed: 0:00:00.238253
------Starting Standard Out Stream------
DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.workflow_jobs.WorkflowJob'> by url: /api/v2/workflow_jobs/572/
DEBUG:urllib3.connectionpool:https://my.internal.tower.hostname:443 "GET /api/v2/workflow_jobs/572/ HTTP/1.1" 200 2362
DEBUG:awxkit.api.client:"GET https://my.internal.tower.hostname:443/api/v2/workflow_jobs/572/" elapsed: 0:00:00.347116
Launching base_centos_7...
DEBUG:urllib3.connectionpool:https://my.internal.tower.hostname:443 "GET /api/v2/unified_jobs?order_by=finished&unified_job_node__workflow_job=572 HTTP/1.1" 301 162
DEBUG:awxkit.api.client:"GET https://my.internal.tower.hostname:443/api/v2/unified_jobs?order_by=finished&unified_job_node__workflow_job=572" elapsed: 0:00:00.002451
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): my.internal.tower.hostname:80
DEBUG:urllib3.connectionpool:http://my.internal.tower.hostname:80 "GET /api/v2/unified_jobs/?order_by=finished&unified_job_node__workflow_job=572 HTTP/1.1" 301 134
DEBUG:awxkit.api.client:"GET http://my.internal.tower.hostname/api/v2/unified_jobs/?order_by=finished&unified_job_node__workflow_job=572" elapsed: 0:00:00.005123
DEBUG:urllib3.connectionpool:https://my.internal.tower.hostname:443 "GET /api/v2/unified_jobs/?order_by=finished&unified_job_node__workflow_job=572 HTTP/1.1" 401 107
DEBUG:awxkit.api.client:"GET https://my.internal.tower.hostname:443/api/v2/unified_jobs/?order_by=finished&unified_job_node__workflow_job=572" elapsed: 0:00:00.065960
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/awxkit/cli/__init__.py", line 25, in run
    cli.parse_resource()
  File "/usr/local/lib/python3.6/site-packages/awxkit/cli/client.py", line 168, in parse_resource
    response = self.parse_action(resource)
  File "/usr/local/lib/python3.6/site-packages/awxkit/cli/client.py", line 316, in parse_action
    return getattr(page, self.method)(**parsed)
  File "/usr/local/lib/python3.6/site-packages/awxkit/cli/custom.py", line 580, in perform
    self.page.connection.session,
  File "/usr/local/lib/python3.6/site-packages/awxkit/cli/stdout.py", line 62, in monitor_workflow
    fetch(seen)
  File "/usr/local/lib/python3.6/site-packages/awxkit/cli/stdout.py", line 23, in fetch
    ).json()['results']
KeyError: 'results'

```

Also, this is a thing:

```sh
# awx workflow_job_templates launch --limit my-ec2-hostname --monitor 20

------Starting Standard Out Stream------
Launching base_centos_7...
'results'

#
```

In both of the above launch attempts, the workflow job continues working and actually succeeds :/

Also note that in the json output, the `related` field is missing. This seems to be an issue with awxkit since when I perform a regular curl to the same URL wit the same bearer token as awkxit is using, the related fields do come up. Through those fields I am able to track down the workflow nodes.

*Also* note that awxkit leaves out a slash at first in the call to `/api/v2/unified_jobs/` which then Tower will try to 301 redirect to the proper URL but @ http/80 for some reason. My load balancer will catch that and redirect back to https/443 with the proper URL but it looks like by that point the authentication token is gone since we're seeing a 401

##### EXPECTED RESULTS

awxkit hangs out and monitors the workflow job until it's done. 

##### ACTUAL RESULTS

Errors pasted above

**Comment by isuftin** [comment]
It actually looks like that same weird redirect is happening when launching as well...

```
# awx -v workflow_job_templates launch --limit my-ec2-hostname --monitor 20
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): my.internal.tower.hostname:443
DEBUG:urllib3.connectionpool:https://my.internal.tower.hostname:443 "GET /api/ HTTP/1.1" 200 307
DEBUG:awxkit.api.client:"GET https://my.internal.tower.hostname:443/api/" elapsed: 0:00:00.083265
DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.api.ApiV2'> by url: /api/v2/
DEBUG:urllib3.connectionpool:https://my.internal.tower.hostname:443 "GET /api/v2/ HTTP/1.1" 200 1688
DEBUG:awxkit.api.client:"GET https://my.internal.tower.hostname:443/api/v2/" elapsed: 0:00:00.060863
DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.workflow_job_templates.WorkflowJobTemplates'> by url: /api/v2/workflow_job_templates/
DEBUG:urllib3.connectionpool:https://my.internal.tower.hostname:443 "OPTIONS /api/v2/workflow_job_templates/ HTTP/1.1" 200 14767
DEBUG:awxkit.api.client:"OPTIONS https://my.internal.tower.hostname:443/api/v2/workflow_job_templates/" elapsed: 0:00:00.147170
DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.workflow_job_templates.WorkflowJobTemplates'> by url: /api/v2/workflow_job_templates/
DEBUG:urllib3.connectionpool:https://my.internal.tower.hostname:443 "OPTIONS /api/v2/workflow_job_templates/1/ HTTP/1.1" 200 7160
DEBUG:awxkit.api.client:"OPTIONS https://my.internal.tower.hostname:443/api/v2/workflow_job_templates/1/" elapsed: 0:00:00.138520
DEBUG:urllib3.connectionpool:https://my.internal.tower.hostname:443 "OPTIONS /api/v2/workflow_job_templates/1/launch/ HTTP/1.1" 200 3886
DEBUG:awxkit.api.client:"OPTIONS https://my.internal.tower.hostname:443/api/v2/workflow_job_templates/1/launch/" elapsed: 0:00:00.107607
DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.workflow_job_templates.WorkflowJobTemplate'> by url: /api/v2/workflow_job_templates/20/
DEBUG:urllib3.connectionpool:https://my.internal.tower.hostname:443 "GET /api/v2/workflow_job_templates/20/ HTTP/1.1" 200 4824
DEBUG:awxkit.api.client:"GET https://my.internal.tower.hostname:443/api/v2/workflow_job_templates/20/" elapsed: 0:00:00.133247
DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.workflow_job_templates.WorkflowJobTemplateLaunch'> by url: /api/v2/workflow_job_templates/20/launch/
DEBUG:urllib3.connectionpool:https://my.internal.tower.hostname:443 "POST /api/v2/workflow_job_templates/20/launch/ HTTP/1.1" 201 2370
DEBUG:awxkit.api.client:"POST https://my.internal.tower.hostname:443/api/v2/workflow_job_templates/20/launch/" elapsed: 0:00:01.085151
DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.workflow_job_templates.WorkflowJobTemplateLaunch'> by url: /api/v2/workflow_job_templates/20/launch/
------Starting Standard Out Stream------
DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.workflow_jobs.WorkflowJob'> by url: /api/v2/workflow_jobs/576/
DEBUG:urllib3.connectionpool:https://my.internal.tower.hostname:443 "GET /api/v2/workflow_jobs/576/ HTTP/1.1" 200 2331
DEBUG:awxkit.api.client:"GET https://my.internal.tower.hostname:443/api/v2/workflow_jobs/576/" elapsed: 0:00:00.166304
Launching base_centos_7...
DEBUG:urllib3.connectionpool:https://my.internal.tower.hostname:443 "GET /api/v2/unified_jobs?order_by=finished&unified_job_node__workflow_job=576 HTTP/1.1" 301 162
DEBUG:awxkit.api.client:"GET https://my.internal.tower.hostname:443/api/v2/unified_jobs?order_by=finished&unified_job_node__workflow_job=576" elapsed: 0:00:00.002507
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): my.internal.tower.hostname:80
DEBUG:urllib3.connectionpool:http://my.internal.tower.hostname:80 "GET /api/v2/unified_jobs/?order_by=finished&unified_job_node__workflow_job=576 HTTP/1.1" 301 134
DEBUG:awxkit.api.client:"GET http://my.internal.tower.hostname/api/v2/unified_jobs/?order_by=finished&unified_job_node__workflow_job=576" elapsed: 0:00:00.004558
DEBUG:urllib3.connectionpool:https://my.internal.tower.hostname:443 "GET /api/v2/unified_jobs/?order_by=finished&unified_job_node__workflow_job=576 HTTP/1.1" 401 107
DEBUG:awxkit.api.client:"GET https://my.internal.tower.hostname:443/api/v2/unified_jobs/?order_by=finished&unified_job_node__workflow_job=576" elapsed: 0:00:00.087749
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/awxkit/cli/__init__.py", line 25, in run
    cli.parse_resource()
  File "/usr/local/lib/python3.6/site-packages/awxkit/cli/client.py", line 168, in parse_resource
    response = self.parse_action(resource)
  File "/usr/local/lib/python3.6/site-packages/awxkit/cli/client.py", line 316, in parse_action
    return getattr(page, self.method)(**parsed)
  File "/usr/local/lib/python3.6/site-packages/awxkit/cli/custom.py", line 102, in perform
    self.monitor(response, **monitor_kwargs)
  File "/usr/local/lib/python3.6/site-packages/awxkit/cli/custom.py", line 87, in monitor
    timeout=kwargs.get('timeout'),
  File "/usr/local/lib/python3.6/site-packages/awxkit/cli/stdout.py", line 62, in monitor_workflow
    fetch(seen)
  File "/usr/local/lib/python3.6/site-packages/awxkit/cli/stdout.py", line 23, in fetch
    ).json()['results']
KeyError: 'results'
```

**Comment by isuftin** [comment]
I live updated the nginx.conf on tower to always use https when rewriting...

before:

...

```
        location / {
            # Redirect if there is no forward-slash
            rewrite ^(.*[^/])$ $1/ permanent;

            if ($http_x_forwarded_proto = "http") {
            rewrite ^ https://$host$request_uri? permanent;
            }
        }
...

```

after:

...

```
        location / {
            # Redirect if there is no forward-slash
            rewrite ^(.*[^/])$ $http_x_forwarded_proto://$host$1/ permanent;

            if ($http_x_forwarded_proto = "http") {
            rewrite ^ https://$host$request_uri? permanent;
            }
        }
...

```

I have to do this because it doesn't seem like I'm able to get NGINX to pick up x-forwarded-proto from the AWS application load balancer which terminates SSL.

This actually seems to have fixed things as NGINX does now redirect to https properly so the load balancer no longer needs to handle a second redirect.

```
awx  workflow_job_templates launch --limit my-ec2-hostname --monitor 20
------Starting Standard Out Stream------
Launching base_centos_7...
 ↳ 585 - base_operating_system running
```

(keeps going until done)

So a few things...

First, awxkit is not including the forward slash before the first `?` in the rest API which is what causes Tower to perform the redirect in the first place. But also, it seems as though after Tower redirects to the balancer @ HTTP and the balancer  redirects back to Tower @ HTTPS, the authentication headers are not passed in, so they get lost somewhere in the mix.
