### ISSUE TITLE
AWX 19.1.0 Inventory sync from source fails with ValueError in traceback

### ISSUE THREAD

**Issue by sdomi4** [ansible/awx#10309]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Syncing inventory from project source in GitLab fails with status "Error occured [sic] while saving inventory data, see traceback or server logs".
Project syncs successfully, inventory file is parsed successfully, traceback reports "ValueError: A string literal cannot contain NUL (0x00) characters."

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: Operator on Minikube
* Ansible version:  ansible [core 2.11.0rc2]
* Operating System: Ubuntu 20.04
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Add GitLab project source to fresh install, try to add Inventory from GitLab source

##### EXPECTED RESULTS
Inventory syncs successfully.

##### ACTUAL RESULTS
Inventory sync fails despite inventory file being parsed fine.

##### ADDITIONAL INFORMATION
Sync output (non-inventory files failing to be parsed and hostnames omitted):
```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2597, in post_run_hook
    cmd.perform_update(options, data, inventory_update)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/inventory_import.py", line 1002, in perform_update
    self.load_into_database()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/inventory_import.py", line 747, in load_into_database
    self._delete_hosts()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/inventory_import.py", line 346, in _delete_hosts
    for host_pk in hosts_qs.filter(name__in=host_names).values_list('pk', flat=True):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 182, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/sql/compiler.py", line 1094, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
ValueError: A string literal cannot contain NUL (0x00) characters.
ansible-inventory [core 2.11.0rc2] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
setting up inventory plugins
[...]
host_list declined parsing /runner/project/images/test.yml as it did not pass its verify_file() method
script declined parsing /runner/project/images/test.yml as it did not pass its verify_file() method
Parsed /runner/project/images/test.yml inventory source with ini plugin
setting up inventory plugins
host_list declined parsing /runner/project/inventory/IOS_inventory.yml as it did not pass its verify_file() method
script declined parsing /runner/project/inventory/IOS_inventory.yml as it did not pass its verify_file() method
Skipping empty key (hosts) in group (core_OTHER)
Parsed /runner/project/inventory/IOS_inventory.yml inventory source with yaml plugin
setting up inventory plugins
host_list declined parsing /runner/project/inventory/inventory.yml as it did not pass its verify_file() method
script declined parsing /runner/project/inventory/inventory.yml as it did not pass its verify_file() method
Skipping empty key (hosts) in group (CentOS8)
Parsed /runner/project/inventory/inventory.yml inventory source with yaml plugin
    6.553 INFO     Processing JSON output...
    6.563 DEBUG    Loaded group: all
[...]
    6.934 DEBUG    Loaded host: 
    6.934 DEBUG    Adding host  to group all
    6.936 INFO     Loaded 46 groups, 199 hosts
```

**Comment by wenottingham** [comment]
Do you have an example inventory file (redacted, if needed) that produces this?

**Comment by sdomi4** [comment]
With further testing, it seems unrelated to the inventory files.
- Copying the inventory files to an empty repo and syncing works
- Specifying inventory files/the folder with the inventory files in the inventory source works

I was able to isolate the issue to a .png file contained in the repo. To reproduce, set inventory source to project root or a directory containing a .png and an inventory file (or any file that gets parsed as an inventory, e.g. an empty .yml works as well).
If any file is successfully parsed combined with the image file failing to be parsed, the sync fails with the above ValueError.

Full output for an example repo containing just an image and an empty .yml file:
```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2597, in post_run_hook
    cmd.perform_update(options, data, inventory_update)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/inventory_import.py", line 1002, in perform_update
    self.load_into_database()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/inventory_import.py", line 747, in load_into_database
    self._delete_hosts()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/inventory_import.py", line 346, in _delete_hosts
    for host_pk in hosts_qs.filter(name__in=host_names).values_list('pk', flat=True):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 182, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/sql/compiler.py", line 1094, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
ValueError: A string literal cannot contain NUL (0x00) characters.
ansible-inventory [core 2.11.0rc2] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
host_list declined parsing /runner/project/ansible.png as it did not pass its verify_file() method
script declined parsing /runner/project/ansible.png as it did not pass its verify_file() method
auto declined parsing /runner/project/ansible.png as it did not pass its verify_file() method
yaml declined parsing /runner/project/ansible.png as it did not pass its verify_file() method
toml declined parsing /runner/project/ansible.png as it did not pass its verify_file() method
[WARNING]:  * Failed to parse /runner/project/ansible.png with ini plugin:
/runner/project/ansible.png:4: Expected key=value host variable assignment,
  File "/usr/local/lib/python3.8/site-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/inventory/ini.py", line 136, in parse
    raise AnsibleParserError(e)
[WARNING]: Unable to parse /runner/project/ansible.png as an inventory source
host_list declined parsing /runner/project/empty.yml as it did not pass its verify_file() method
script declined parsing /runner/project/empty.yml as it did not pass its verify_file() method
Parsed /runner/project/empty.yml inventory source with ini plugin
    7.700 INFO     Processing JSON output...
    7.701 INFO     Loaded 0 groups, 3 hosts
```

If the image is removed from the repo, the empty .yml is parsed successfully and the expected 0 groups / 0 hosts are added (same behaviour with a populated inventory):
```
ansible-inventory [core 2.11.0rc2] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
host_list declined parsing /runner/project/empty.yml as it did not pass its verify_file() method
script declined parsing /runner/project/empty.yml as it did not pass its verify_file() method
Parsed /runner/project/empty.yml inventory source with ini plugin
    8.650 INFO     Processing JSON output...
    8.651 INFO     Loaded 0 groups, 0 hosts
   10.361 INFO     Inventory import completed for Inventory from GitIT in 1.7s
```

**Comment by wenottingham** [comment]
This is due to the current behavior of the ansible inventory plugins - in this example, ini_file is reading some strings from the PNG and deciding 'yes, they're hosts'. 

To fix this would require changes in ansible itself. You can file an issue at https://github.com/ansible/ansible requesting (as an example) better file type detection in the ini_file plugin.

**Comment by samdoran** [comment]
You could add `.png` to the `INVENTORY_IGNORE_EXTS` as a workaround.
