### ISSUE TITLE
Failed to read /api. GET status: 502

### ISSUE THREAD

**Issue by spac3-monkey** [ansible/awx#1038]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI
 
##### SUMMARY

After the default Docker install when accessing login page an [error](https://www.awesomescreenshot.com/image/3119432/32c83ae8bf78cd232633599654fde098) is thrown.

##### ENVIRONMENT
* AWX version: latest
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: Ubuntu
* Web Browser: Chrome

##### STEPS TO REPRODUCE

After running `ansible-playbook -i inventory install.yml` and a couple of [this](https://github.com/ansible/awx/issues/689) errors in the taks logs:
```python
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer
```
I try to login and get the following message in the UI:
```
Failed to read /api. GET status: 502
```
The Web server logs show:
```python
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 53, in response_for_exception
    response = get_exception_response(request, get_resolver(get_urlconf()), 404, exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 119, in get_exception_response
    response = handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 143, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/usr/lib/python2.7/site-packages/awx/main/views.py", line 88, in handle_500
    return handle_error(request, 500, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/views.py", line 56, in handle_error
    return render(request, 'error.html', kwargs, status=status)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/defaulttags.py", line 40, in render
    output = self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/defaulttags.py", line 166, in render
    values = self.sequence.resolve(context, True)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 736, in resolve
    new_obj = func(obj, *arg_vals)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/templatetags/rest_framework.py", line 244, in items
    return value.items()
```

**Comment by jakemcdermott** [comment]
I've seen this from time to time as well, although I have not identified a reliable reproducer.

**Comment by jakemcdermott** [comment]
Thanks for the bug report, spac3-monkey. I've seen this from time to time as well, although I have not identified a reliable, deterministic reproducer.

One thing I've noticed is that the `502` seems to occur once and is always the very first request if you're making several from an automation script or other tooling.

If you end up finding a reliable / repeatable sequence of steps to reproduce this error please let us know.

**Comment by spac3-monkey** [comment]
@jakemcdermott I'm getting the `502` every time I get to Login page. After closing the popup I try to get in using the default credentials but it just says `working...`
I've tried the installation a couple of times in an __aws EC2__ running __Ubuntu 16.04.3 LTS__ and same results.

**Comment by maccdoog** [comment]
I've been getting the same error when trying to authenticate from the logon screen in GUI.

Think it may be related to supervisord failing, and a restart of the service resolved temporarily.

**Comment by ryanpetrello** [comment]
This _might_ be a bug in the version of Django Rest Framework we're using.  This issue in particular looks very similar: https://github.com/encode/django-rest-framework/issues/3260  Searching the issue list for snippets of the traceback that @spac3-monkey provided points to a few other clues.

**Comment by seffyroff** [comment]
Seeing the same things here.  Lots of logspam related to connection reset by peer (as per other issues filed here) between awx_task and rabbitmq.  The 502 issue also happens as described out of the box, with a fresh install following the docker (or docker-compose) instructions.  No special configs.  Attempted on bare metal and cloud VMs of between 4-8GB ram, Ubuntu Xenial host, Docker 17.12 or 18.02..

EDIT: Not sure if this is helpful, but if I do a docker-compose deploy using geerlinguy/awx_task and geerlinguy/awx_web instead of the stock images, the web UI works properly.  Interestingly, I still see lots of logspam regarding connections being reset, but it doesn't appear to be affecting functionality of AWX, so that may be a red herring.

**Comment by seffyroff** [comment]
Additionally, the @geerlingguy container images aren't working flawlessly either.  After an uptime of 8 hours or so the API stops responding to the frontend, and the 502 error message starts happening as described in this thread.

I'm going to start working back through container images to find the last stable version - right now it seems like there isn't a stable version, given the system requirements being satisfied.

**Comment by Cryptophobia** [comment]
I am getting the same errors on AWS deploying to K8s. Using version `dockerhub_version=1.0.3`

**Comment by Cryptophobia** [comment]
What container actually works? I tried 1.0.2 and same thing....

**Comment by AlanCoding** [comment]
Probably related to #1418

**Comment by wenottingham** [comment]
Please test 1.0.6 and reopen if this is still an issue. (See #1418 above)
