### ISSUE TITLE
Endpoint `/api/v2/ad_hoc_command_events/` errors

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#10392]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Global endpoint 500s

##### STEPS TO REPRODUCE

Visit https://localhost:8043/api/v2/ad_hoc_command_events/

##### EXPECTED RESULTS

A response

##### ACTUAL RESULTS

a 500 error

##### ADDITIONAL INFORMATION

```
2021-06-08 14:49:39,685 ERROR    [b8e5c47c] django.request Internal Server Error: /api/v2/ad_hoc_command_events/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "./awx/api/generics.py", line 324, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "./awx/api/views/__init__.py", line 4002, in get_queryset
    adhoc = self.get_parent_object()
AttributeError: 'AdHocCommandEventList' object has no attribute 'get_parent_object'

2021-06-08 14:49:39,685 ERROR    [b8e5c47c] django.request Internal Server Error: /api/v2/ad_hoc_command_events/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "./awx/api/generics.py", line 324, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "./awx/api/views/__init__.py", line 4002, in get_queryset
    adhoc = self.get_parent_object()
AttributeError: 'AdHocCommandEventList' object has no attribute 'get_parent_object'
```

I didn't expect this to _be_ an endpoint, so I need to get someone to clarify intent.

**Comment by chrismeyersfsu** [comment]
Look like it's the parallel to `api/v2/job_events` which we have gotten rid of recently. We should get rid of this endpoint too. We _may_ have to deprecate it first then delete it. @wenottingham can we delete or do we need to deprecate first?

**Comment by wenottingham** [comment]
Just delete it.

**Comment by wenottingham** [comment]
@chrismeyersfsu did someone send a PR for this?

**Comment by chrismeyersfsu** [comment]
![image](https://user-images.githubusercontent.com/722880/122581339-f1428280-d024-11eb-8dbb-72f05b163fce.png)
I'm not seeing any global event endpoints. Trying to find the code change to link to this issue.

Edit: Ok, the endpoint isn't shown in the list of endpoints but is accessible. So no, PR not submitted yet.
Edit: I'm seeing the wanted behavior now. `ad_hoc_command_events/` should remain "hidden". The intent is to not allow listing. going to `api/v2/ad_hoc_command_events/` should result in a 404. Going to `api/v2/ad_hoc_command_events/1/` SHOULD load event 1 (if it exists).  

Currently:
* https://localhost:8043/api/v2/ad_hoc_command_events/12/ works
* https://localhost:8043/api/v2/ad_hoc_command_events/ results in a 500

TODO:
- [ ] return 404 at https://localhost:8043/api/v2/ad_hoc_command_events/

**Comment by CFSNM** [comment]
Validated manually from QE side. The endpoind /api/v2/adhoc_command_events cannot be found
