### ISSUE TITLE
Inventory source from a project failing

### ISSUE THREAD

**Issue by marekvesely-direct** [ansible/awx#10401]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
If I create Source from a Project in Inventories it finished with status Error. It is connected to Project which is status successful.

##### ENVIRONMENT
* AWX version: 19.2.0
* AWX install method: kubernetes

##### STEPS TO REPRODUCE

1. Create Git project with inventory file envs/analytics/hosts:
```
[postgres_master]
dwh-prod-01

[postgres_slave]

[postgres:children]
postgres_master
postgres_slave

[apache_airflow]
app-an-01

[grafana]
app-an-01

[web]
app-an-01

[applications:children]
apache_airflow
grafana
web

[jupyterhub]
jupyterhub-an
```

2. Create inventory with some name.
3. Go to sources and create source with source as Sourced from a Project. Project which is connected to some git repo, inventory file: envs/analytics/hosts and enabled Update on launch.
4. Start sync proccess.

##### EXPECTED RESULTS
Status as succesfful

##### ACTUAL RESULTS

```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1384, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2900, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2924, in _run_internal
    raise transmitter_thread.exc[1].with_traceback(transmitter_thread.exc[2])
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2880, in run
    super().run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/utils/common.py", line 1036, in wrapper_cleanup_new_process
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2975, in transmit
    ansible_runner.interface.run(streamer='transmit', _output=_socket.makefile('wb'), **self.runner_params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/ansible_runner/interface.py", line 249, in run
    r.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/ansible_runner/streaming.py", line 53, in run
    stream_dir(self.private_data_dir, self._output)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/ansible_runner/utils/streaming.py", line 20, in stream_dir
    archive.write(os.path.join(dirpath, fname), arcname=os.path.join(relpath, fname))
  File "/usr/lib64/python3.8/zipfile.py", line 1740, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/usr/lib64/python3.8/zipfile.py", line 522, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pdd_wrapper_45_ewjlgpme/awx_45_hxv_76p1/project/envs/fin-vag-vaults/mongo.yml'
```

**Comment by marekvesely-direct** [comment]
My mistake, I had broken simlink in one inventory file
