### ISSUE TITLE
Unicode error in ansi job stdout

### ISSUE THREAD

**Issue by saez0pub** [ansible/awx#1042]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
API call on job stdout results on error 500 when there is an unicode caracter

##### ENVIRONMENT
* AWX version: 1.0.2.372
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: Centos 7
* Web Browser: any

##### STEPS TO REPRODUCE

Create a playbook : 
```
---
- hosts: all
  gather_facts: false
  tasks:
    - name: unicode ☠☠☠☠☠☠☠☠☠☠☠☠☠
      debug: msg="☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠"
```
launch it from awx

Get the output from the api : 
$AWX_HOST/api/v2/jobs/$JOB_ID/stdout/?content_format=ansi&start_line=0&content_encoding=base64&format=json

##### EXPECTED RESULTS

`"<div class=\"nocode ansi_fore ansi_back\"><style type=\"text/css\">\n.ansi_fore { color: #000000; }\n.ansi_back { background-color: #F5F5F5; }\n.ansi_fore.ansi_dark { color: #AAAAAA; }\n.ansi_back.ansi_dark { background-color: #000000; }\n.ansi1 { font-weight: bold; }\n.ansi3 { font-weight: italic; }\n.ansi4 { text-decoration: underline; }\n.ansi9 { text-decoration: line-through; }\n.ansi30 { color: #161b1f; }\n.ansi31 { color: #d9534f; }\n.ansi32 { color: #5cb85c; }\n.ansi33 { color: #f0ad4e; }\n.ansi34 { color: #337ab7; }\n.ansi35 { color: #e1539e; }\n.ansi36 { color: #2dbaba; }\n.ansi37 { color: #ffffff; }\n.ansi40 { background-color: #161b1f; }\n.ansi41 { background-color: #d9534f; }\n.ansi42 { background-color: #5cb85c; }\n.ansi43 { background-color: #f0ad4e; }\n.ansi44 { background-color: #337ab7; }\n.ansi45 { background-color: #e1539e; }\n.ansi46 { background-color: #2dbaba; }\n.ansi47 { background-color: #ffffff; }\nbody.ansi_back pre {\n  font-family: Monaco, Menlo, Consolas, \"Courier New\", monospace;\n  font-size: 12px;\n}\ndiv.ansi_back.ansi_dark {\n  padding: 0 8px;\n  -webkit-border-radius: 3px;\n  -moz-border-radius: 3px;\n  border-radius: 3px;\n}\n</style><span class=\"ansi34\">ansible-playbook 2.4.2.0</span>\n<span class=\"ansi34\">  config file = /etc/ansible/ansible.cfg</span>\n<span class=\"ansi34\">  configured module search path = [u'/usr/lib/python2.7/site-packages/awx/plugins/library']</span>\n<span class=\"ansi34\">  ansible python module location = /usr/lib/python2.7/site-packages/ansible</span>\n<span class=\"ansi34\">  executable location = /usr/bin/ansible-playbook</span>\n<span class=\"ansi34\">  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]</span>\n<span class=\"ansi34\">Using /etc/ansible/ansible.cfg as config file</span>\nSSH password: \n\nPLAYBOOK: test_unicode.yml *****************************************************\n<span class=\"ansi34\">1 plays in test_unicode.yml</span>\n\nPLAY [all] *********************************************************************\n<span class=\"ansi34\">META: ran handlers</span>\n\nTASK [unicode ☠☠☠☠☠☠☠☠☠☠☠☠☠] ***************************************************\n<span class=\"ansi1 ansi30\">task path: /var/lib/awx/projects/_10__itg_tlf/test_unicode.yml:5</span>\n<span class=\"ansi32\">ok: [itgtlf-batch01n.prppai27.cvf] =&gt; {</span>\n<span class=\"ansi32\">    \"msg\": \"☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠☠\"</span>\n<span class=\"ansi32\">}</span>\n<span class=\"ansi31\">ERROR! Attempting to decrypt but no vault secrets found</span>\n\n</div>"`

##### ACTUAL RESULTS

`{"detail":"A server error has occurred."}`

##### ADDITIONAL INFORMATION

here is the trace in awx_web : 

```
 X.X.X.X - - [23/Jan/2018:16:39:57 +0000] "GET /api/v2/jobs/639/stdout/?content_format=ansi&start_line=0&content_encoding=base64&format=json HTTP/1.1" 500 41 "-" "curl/7.57.0" "-"
 2018-01-23 16:39:57,268 ERROR    django.request Internal Server Error: /api/v2/jobs/639/stdout/
 Traceback (most recent call last):
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
     response = get_response(request)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
     response = self._get_response(request)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
     response = self.process_exception_by_middleware(e, request)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
     return func(*args, **kwargs)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
     return view_func(*args, **kwargs)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
     return self.dispatch(request, *args, **kwargs)
   File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 253, in dispatch
     return super(APIView, self).dispatch(request, *args, **kwargs)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
     response = self.handle_exception(exc)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
     self.raise_uncaught_exception(exc)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
     response = handler(request, *args, **kwargs)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 210, in get
     return self.retrieve(request, *args, **kwargs)
   File "/usr/lib/python2.7/site-packages/awx/api/views.py", line 4603, in retrieve
     return Response({'range': {'start': start, 'end': end, 'absolute_end': absolute_end}, 'content': b64encode(content)})
   File "/usr/lib64/python2.7/base64.py", line 53, in b64encode
     encoded = binascii.b2a_base64(s)[:-1]
 UnicodeEncodeError: 'ascii' codec can't encode characters in position 768-780: ordinal not in range(128)
 2018-01-23 16:39:57,268 ERROR    django.request Internal Server Error: /api/v2/jobs/639/stdout/
 Traceback (most recent call last):
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
     response = get_response(request)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
     response = self._get_response(request)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
     response = self.process_exception_by_middleware(e, request)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
     return func(*args, **kwargs)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
     return view_func(*args, **kwargs)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
     return self.dispatch(request, *args, **kwargs)
   File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 253, in dispatch
     return super(APIView, self).dispatch(request, *args, **kwargs)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
     response = self.handle_exception(exc)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
     self.raise_uncaught_exception(exc)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
     response = handler(request, *args, **kwargs)
   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 210, in get
     return self.retrieve(request, *args, **kwargs)
   File "/usr/lib/python2.7/site-packages/awx/api/views.py", line 4603, in retrieve
     return Response({'range': {'start': start, 'end': end, 'absolute_end': absolute_end}, 'content': b64encode(content)})
   File "/usr/lib64/python2.7/base64.py", line 53, in b64encode
     encoded = binascii.b2a_base64(s)[:-1]
 UnicodeEncodeError: 'ascii' codec can't encode characters in position 768-780: ordinal not in range(128)
 [pid: 415|app: 0|req: 506/12435] X.X.X.X () {34 vars in 605 bytes} [Tue Jan 23 16:39:57 2018] GET /api/v2/jobs/639/stdout/?content_format=ansi&start_line=0&content_encoding=base64&format=json => generated 41 bytes in 71 msecs (HTTP/1.1 500) 5 headers in 177 bytes (1 switches on core 0)

```

**Comment by ryanpetrello** [comment]
@saez0pub this should be resolved in `devel` of awx via https://github.com/ansible/awx/pull/1061
