### ISSUE TITLE
AWX upgrade failed

### ISSUE THREAD

**Issue by AlekseiSaff** [ansible/awx#10472]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX upgrade from 17 to 19 failed on 0137_custom_inventory_scripts_removal_data step

##### ENVIRONMENT
* AWX version: 17.0 to 19.x 
* AWX install method: awx-operator
* Ansible version:  19.x
* Operating System: Linux
* Web Browser:

##### STEPS TO REPRODUCE

Upgrade from 17.x to 19.x failed on step 0137_custom_inventory_scripts_removal_data

##### EXPECTED RESULTS

full upgrade passed

##### ACTUAL RESULTS

Upgrade failed

##### ADDITIONAL INFORMATION

sh-4.4$ awx-manage migrate --noinput
Operations to perform:
  Apply all migrations: auth, conf, contenttypes, main, oauth2_provider, sessions, sites, social_django, sso, taggit
Running migrations:
2021-06-18 03:24:30,435 INFO     [-] awx.main.migrations deleted (10757, {'main.ActivityStream_unified_job': 0, 'main.UnifiedJob_dependent_jobs': 0, 'main.UnifiedJob_notifications': 2, 'main.UnifiedJob_labels': 0, 'main.UnifiedJob_credentials': 0, 'main.JobLaunchConfig_credentials': 0, 'main.ActivityStream_inventory_update': 2, 'main.InventoryUpdateEvent': 8818, 'main.InventoryUpdate': 645, 'main.JobLaunchConfig': 645, 'main.UnifiedJob': 645})
2021-06-18 03:24:30,436 INFO     [-] awx.main.migrations Deleted 645 custom inventory script sources.
  Applying main.0137_custom_inventory_scripts_removal_data...Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/__init__.py", line 171, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/commands/migrate.py", line 232, in handle
    post_migrate_state = executor.migrate(
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/migrations/_inventory_source.py", line 105, in delete_custom_inv_source
    ct, deletions = InventorySource.objects.filter(source='custom').delete()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 710, in delete
    collector.collect(del_query)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/deletion.py", line 224, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/deletion.py", line 15, in CASCADE
    collector.collect(sub_objs, source=field.remote_field.model,
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/deletion.py", line 224, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/utils/polymorphic.py", line 18, in SET_NULL
    return models.SET_NULL(collector, field, sub_objs.non_polymorphic(), using)
AttributeError: 'QuerySet' object has no attribute 'non_polymorphic'
sh-4.4$

**Comment by colixxx** [comment]
@AlekseiSaff Hi, I have the same problem. When I am upgrading from 19.0.0 to 19.1.0 through a version change in the AWX object. I am trying to run migrations manually via awx-tasks container and get this error. 
Did you manage to defeat her?

**Comment by jbradberry** [comment]
The fix for this landed in 19.3.0, from PR #10633.
