### ISSUE TITLE
Unable to customize args or image directly from the container group configuration

### ISSUE THREAD

**Issue by AlexisDuf** [ansible/awx#10568]
On 19.0.0 we were able to customize the image and the args.

And now(on 19.2.2) it's kind of hard coded 
```python
        pod_spec['spec']['containers'][0]['image'] = ee.image
        pod_spec['spec']['containers'][0]['args'] = ['ansible-runner', 'worker', '--private-data-dir=/runner']
```
https://github.com/ansible/awx/blob/2afa406b7f16971ea83150c326f8e04717b5c14d/awx/main/tasks.py#L3075

Could we add a `if` condition if image is already set ? 

About `args` the default command in the image is `ansible-runner worker --private-data-dir=/runner` (cf https://github.com/ansible/awx-ee/blob/devel/run.sh) so we can't overload this part

**Comment by shanemcd** [comment]
Curious - what do you need to change the command to? Anything else will likely cause AWX not to work properly. I did this to stop people from shooting themselves in the foot.

**Comment by AlexisDuf** [comment]
Hi @shanemcd, 

Yes, I customized awx-ee by executing some script before running the command `ansible-runner worker --private-data-dir=/runner`.  And yes I noticed that AWX can't start a job properly 

As workaround I tried to use an `initContainers` in the pod spec but it's not working too. 

And I don't have any output to see what's going wrong

**Comment by shanemcd** [comment]
I think `initContainers` is probably the more elegant solution here. We'll look into why that isn't working.

**Comment by nmaupu** [comment]
Same here, I would like to be able to customize the image args to configure stuff before job is ran.
I could do all the stuff using ansible itself but it's not very a nice solution because this ansible task would need to be included in all playbooks...
I need some line of bash to generate a vault access token prior to run all the jobs. `initContainers` is not the best way imho because it makes the custom pod spec complicated for nothing (initContainers specs + volumes mounting for file sharing between containers vs. a path to a custom entrypoint).

As a workaround, I tried to make a script named `ansible-runner` with `chmod +x` containing:

```
#!/bin/bash

## My stuff here

/usr/local/bin/ansible-runner $@
```

This can be executed instead of the default args if you put it in the `PATH` before `ansible-runner` binary.

But the job does not start and no logs are output in `awx-task` container. As of now, I can't figure out why...

It would be much better to let user choose what they want to do... I mean we are all adults here ;)

**Comment by nmaupu** [comment]
Ok, the job was not running when I added `initContainers` (without any output logs nor relevant awx-task logs - even in debug) because `name: worker` **has to be specified** in the instance group's custom pod spec...

I don't know if this is documented somewhere but this surely should be. Or at least give somewhere an error that is explicit.

Nevertheless, now that initContainers are working, this is far from an ideal solution. The pod spec is now much longer and overhead for init container to launch and run is not negligible. Once more, it would be much better to be able to specify my own args.

**Comment by nmaupu** [comment]
ok, in the current code, container's `args` is replaced but not `command`... So it's possible to specify whatever command I need instead of the default forced value but the job stops 10 secs or so after starting for no reason. This is maybe what you (@shanemcd) were refering to when saying _Anything else will likely cause AWX not to work properly_.

@shanemcd Do you have any clue as to why it's not working with a script like the following ?

```
#! /bin/bash
set -xe

echo foobar
ansible-runner worker --private-data-dir=/runner
```

**Comment by nmaupu** [comment]
After more digging, I manage to extract the logs before pod is deleted from the cluster (for reference, output log is a zip file base64 encoded)

The error is the following:

```
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/usr/local/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 532, in _execute
    self._connection = self._get_connection(cvars, templar)
  File "/usr/local/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 869, in _get_connection
    connection, plugin_load_context = self._shared_loader_obj.connection_loader.get_with_context(
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/loader.py", line 837, in get_with_context
    obj.__init__(instance, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/connection/local.py", line 50, in __init__
    self.default_user = getpass.getuser()
  File "/usr/lib64/python3.8/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1000'
fatal: [ans]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

This user id is actually existing in the image. I don't get why this crashes when `ansible-runner` is executed from a shell script instead of directly from pod's arguments 🤔

**Comment by nmaupu** [comment]
I answer to myself: it's because of the entrypoint of ansible-runner image which create a dummy /etc/passwd and /etc/group file...

The last line executes `exec /usr/local/bin/dumb-init -- "${@}"`
https://github.com/ansible/ansible-runner/blob/devel/utils/entrypoint.sh#L48 

So if I create a script which do what I want and finishes by the following, this should work:
```
exec /usr/bin/entrypoint "$@"
```

I see that the job starts ok and ansible playbook starts also ok but as soon as the container starts, it's automatically killed making it impossible to finish...
Do you have any idea why ? @shanemcd

**Comment by kdelee** [comment]
@nmaupu you might consider setting `RECEPTOR_RELEASE_WORK`=`False` to be able to (from the task container) query the receptor work status for the `work_unit_id` associated with the job to find out if the receptor work unit is failing what what the detail is for the failure.

On a lower level, you could also experiment in receptor itself with what you are trying to do
https://github.com/ansible/awx/blob/4f1c6626913f2a9794a5f94724bbeb1b90231db1/awx/settings/defaults.py#L937-L938

FWIW in that doc is where it is called out that receptor requires the container to be named `worker`

**Comment by shanemcd** [comment]
No activity here for a while, going to assume it was resolved.
