### ISSUE TITLE
GUI settings component broken in 19.2.2

### ISSUE THREAD

**Issue by lo78cn** [ansible/awx#10565]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
/#/settings shows:
Something went wrong...
There was an error loading this content. Please reload the page. Back to Dashboard.
Error details are empty.

Note: Everything else is working fine.

Browser development tools response reports: SyntaxError: JSON.parse: unterminated string at line 1 column 64792 of the JSON data

##### ENVIRONMENT
* AWX version: 19.2.2
* AWX install method: developer environment
* AWX deployment target: Docker compose
* Operating System: MacOS 11.3.1
* Web Browser: tested latest Safari, Firefox and Brave

##### STEPS TO REPRODUCE

Clean install as described in README.md files.

##### EXPECTED RESULTS

Working settings GUI 

##### ADDITIONAL INFORMATION

/api/v2/settings/all/ -> no output in GUI REST api explorer

I do get output on all other setting details in GUI REST api exporer like /api/v2/settings/system/ and /api/v2/settings/ldap/.

**Comment by nixocio** [comment]
@lo78cn, can you provide more details? What are the HTTP requests being made? Responses.

**Comment by lo78cn** [comment]
Hi @nixocio,

JSON payload ends on SOCIAL_AUTH

OPTIONS
	/api/v2/settings/all/

Status: 200 OK

Response header: X-API-Total-Time | 0.645s

response error: SyntaxError: JSON.parse: unterminated string at line 1 column 64792 of the JSON data

payload:
{"name":"Setting Detail","description":"# Retrieve a Setting:\n\nMake GET request to this resource to retrieve a single setting\nrecord containing the following fields:\n\n* `ACTIVITY_STREAM_ENABLED`: Enable capturing activity for the activity stream. (boolean)\n* `ACTIVITY_STREAM_ENABLED_FOR_INVENTORY_SYNC`: Enable capturing activity for the activity stream when running inventory sync. (boolean)\n* `ORG_ADMINS_CAN_SEE_ALL_USERS`: Controls whether any Organization Admin can view all users and teams, even those not associated with their Organization. (boolean)\n* `MANAGE_ORGANIZATION_AUTH`: Controls whether any Organization Admin has the privileges to create and manage users and teams. You may want to disable this ability if you are using an LDAP or SAML integration. (boolean)\n* ...
`LOGIN_REDIRECT_OVERRIDE`: URL to which unauthorized users will be redirected to log in.  If blank, users will be sent to the login page. (string, default=`\"\"`)\n\n* `CUSTOM_LOGIN_INFO`: If needed, you can add specific information (such as a legal notice or a disclaimer) to a text box in the login modal using this setting. Any content added must be in plain text or an HTML fragment, as other markup languages are not supported. (string, default=`\"\"`)\n* `CUSTOM_LOGO`: To set up a custom logo, provide a file that you create. For the custom logo to look its best, use a .png file with a transparent background. GIF, PNG and JPEG formats are supported. (string, default=`\"\"`)\n* `MAX_UI_JOB_EVENTS`: Maximum number of job events for the UI to retrieve within a single request. (integer, required)\n* `UI_LIVE_UPDATES_ENABLED`: If disabled, the page will not refresh when events are received. Reloading the page will be required to get the latest details. (boolean, required)\n\n* `SOCIAL_AUTH

**Comment by arodriguezd** [comment]
Hi, 
I have the same problem. 

```typeError: Cannot read properties of undefined (reading 'default')
    at j5 (https://awx-test.domain.com/static/js/main.fb70a15e.js:2:2684580)
    at oo (https://awx-test.domain.com//static/js/main.fb70a15e.js:2:913504)
    at Ks (https://awx-test.domain.com//static/js/main.fb70a15e.js:2:965804)
    at Al (https://awx-test.domain.com//static/js/main.fb70a15e.js:2:953045)
    at Tl (https://awx-test.domain.com//static/js/main.fb70a15e.js:2:952973)
    at El (https://awx-test.domain.com//static/js/main.fb70a15e.js:2:952836)
    at yl (https://awx-test.domain.com//static/js/main.fb70a15e.js:2:949802)
    at https://awx-test.domain.com//static/js/main.fb70a15e.js:2:899296
    at t.unstable_runWithPriority (https://awx-test.domain.com//static/js/main.fb70a15e.js:2:995558)
    at Vi (https://awx-test.domain.com//static/js/main.fb70a15e.js:2:899073)
```
I have changed my domain that showed by domain.com.

**Environment**

    AWX version: 21.3.0
    AWX install method: k3s with awx-operator (0.25.0 )
    Operating System: Ubuntu 20
    Web Browser: tested latest Firefox and Chrome

Why do I want to edit here, why do I need to change this parameter:

```
Base URL of the service
https://towerhost
```

By my domain to be able to authenticate with Azure AD.
