### ISSUE TITLE
AWX 19.2.2 PermissionError: /runner/env/

### ISSUE THREAD

**Issue by CWollinger** [ansible/awx#10616]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Running AWX 19.2.2 with awx-operator 0.12.0 on kubernetes. AWX EE 0.5.0
Images are pushed (not modified) to a local private registry.
When I try to execute a job template, I receive the following error after a few seconds:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/streaming.py", line 107, in run
    unstream_dir(self._input, data['zipfile'], self.private_data_dir)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/utils/streaming.py", line 59, in unstream_dir
    os.chmod(out_path, perm)
PermissionError: [Errno 1] Operation not permitted: '/runner/env/'`

There was no such problem with AWX 19.2.0 and operator 0.10.0.

### AWX version

19.2.2

### Installation method

kubernetes

### Modifications

yes

### Steps to reproduce

- Push images to private registry
- Launch AWX operator and AWX
- Create a new project and template
- Execute template

### Expected results

Job runs without error like in version 19.2.0

### Actual results

Job error:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/streaming.py", line 107, in run
    unstream_dir(self._input, data['zipfile'], self.private_data_dir)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/utils/streaming.py", line 59, in unstream_dir
    os.chmod(out_path, perm)
PermissionError: [Errno 1] Operation not permitted: '/runner/env/'`

**Comment by fourstepper** [comment]
I am getting a very similar error, for one of my templates:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/streaming.py", line 107, in run
    unstream_dir(self._input, data['zipfile'], self.private_data_dir)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/utils/streaming.py", line 68, in unstream_dir
    os.chmod(out_path, perm)
PermissionError: [Errno 1] Operation not permitted: '/runner/project/'
```

**Comment by shanemcd** [comment]
This should be fixed by the next release of awx-ee that contains https://github.com/ansible/ansible-runner/pull/740

In the meantime you can build your own EE to pull in the patch.

**Comment by kladiv** [comment]
Same error on 19.2.2 with EE awx-ee:0.5.0 on Inventory Sync job (flag Update on project update) automatically invoked by Source Control Update job

@shanemcd are you able to create an EE 0.5.1 image with that patch?

**Comment by vishnubraj** [comment]
how to fix this? I just upgraded and it's broken.
