### ISSUE TITLE
Can't clone git project - InvalidSignature: Signature did not match digest

### ISSUE THREAD

**Issue by flisak-robert** [ansible/awx#10799]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

After setup, I've created credentials for gitlab repo authentication and the initial clone worked. However, I've restarted my host running AWX and after that I am unable to clone a repository, jobs fail with "InvalidSignature: Signature did not match digest" error.

### AWX version

19.2.2

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

- Create new git credential source
- Sync repository
- Restart awx host
- Try to sync the project

### Expected results

Git projects syncs without any errors.

### Actual results

Syncing jobs fail and 'InvalidSignature: Signature did not match digest' error is present in the logs.

### Additional information

```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/cryptography/fernet.py", line 104, in _verify_signature
    h.verify(data[-32:])
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/cryptography/hazmat/primitives/hmac.py", line 66, in verify
    ctx.verify(signature)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1344, in run
    private_data_files = self.build_private_data_files(self.instance, private_data_dir)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 898, in build_private_data_files
    private_data = self.build_private_data(instance, private_data_dir)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1901, in build_private_data
    private_data['credentials'][credential] = credential.get_input('ssh_key_data', default='')
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/models/credential/__init__.py", line 278, in get_input
    return decrypt_field(self, field_name)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/utils/encryption.py", line 159, in decrypt_field
    return smart_str(decrypt_value(key, value))
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/utils/encryption.py", line 136, in decrypt_value
    value = f.decrypt(encrypted)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/cryptography/fernet.py", line 75, in decrypt
    return self._decrypt_data(data, timestamp, ttl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/cryptography/fernet.py", line 117, in _decrypt_data
    self._verify_signature(data)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/cryptography/fernet.py", line 106, in _verify_signature
    raise InvalidToken
cryptography.fernet.InvalidToken
```

**Comment by flisak-robert** [comment]
My bad, did not configure postgres_configuration_secret properly.

**Comment by cloneluke** [comment]
we had this problem, make sure to go in an update all credentials, we restored our database from a different one and needed to update all of our credentials within AWX

**Comment by ololdach** [comment]
@cloneluke: Thanks for the hint. Adding more details that might help: in my case only the Access Token for pulling the custom AWX-Execution Environment from the repository failed. Hence the execution environment could not be started and produced the above error.  Generating a new token for the repository solved it.
