### ISSUE TITLE
"Something went wrong" after AKS rebuild and AWX upgrade

### ISSUE THREAD

**Issue by tp199314** [ansible/awx#10914]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Hi all,

we had to rebuild our aks cluster (version was to old) and had to create AWX from scratch.

(Please see below information. Thank you in advance)

### AWX version

AWX 19.3.0

### Installation method

kubernetes

### Modifications

yes

### Web browser

Chrome

### Steps to reproduce

After installing AWX with awx-operator, we restored a database backup into the postgresql pod.
Then we run an awx-manage makemigrations and awx-manage migrate. No errors so far.

### Expected results

We thought, that after this AWX will came back online. Which is partly working.

### Actual results

But, there are some pages which "went wrong". This pages are Jobs, Templates, Projects and Instance Groups.

2021-08-19 15:23:19,219 ERROR    [86ba151dbd8349a6a570db9794960718] django.request Internal Server Error: /api/v2/projects/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/api/generics.py", line 322, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/api/pagination.py", line 64, in paginate_queryset
    return super(Pagination, self).paginate_queryset(queryset, request, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/pagination.py", line 218, in paginate_queryset
    return list(self.page)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/paginator.py", line 150, in __len__
    return len(self.object_list)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/polymorphic/query.py", line 66, in _polymorphic_iterator
    real_results = self.queryset._get_real_instances(base_result_objects)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/polymorphic/query.py", line 377, in _get_real_instances
    real_concrete_class = base_object.get_real_instance_class()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/polymorphic/models.py", line 135, in get_real_instance_class
    raise PolymorphicTypeInvalid(
polymorphic.models.PolymorphicTypeInvalid: ContentType 40 for <class 'awx.main.models.organization.Team'> #10 does not point to a subclass!

### Additional information

![image](https://user-images.githubusercontent.com/2600276/130096286-b1a37b9e-7f09-4783-9f0c-7e7bfed827e1.png)

**Comment by tp199314** [comment]
Somehow the issue is solved. Looks like, the error was not part of AWX, more a misconfiguration on our site.
