### ISSUE TITLE
External Postgres DB fail to migrate ( AWX migration 17.0.1 - > latest)

### ISSUE THREAD

**Issue by olokolo250** [ansible/awx#10955]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

Installation with external Postgres DB previously running with docker based version 17.0.1 
With minikube setup fails on DB migration step 

# minikube kubectl logs awx-768d58d7bf-s5mmd awx-task
[wait-for-migrations] Waiting for database migrations...
[wait-for-migrations] Attempt 1 of 10
[wait-for-migrations] Waiting 0.5 seconds before next attempt
[wait-for-migrations] Attempt 2 of 10
[wait-for-migrations] Waiting 1 seconds before next attempt
[wait-for-migrations] Attempt 3 of 10
[wait-for-migrations] Waiting 2 seconds before next attempt
[wait-for-migrations] Attempt 4 of 10
[wait-for-migrations] Waiting 4 seconds before next attempt
[wait-for-migrations] Attempt 5 of 10
[wait-for-migrations] Waiting 8 seconds before next attempt
[wait-for-migrations] Attempt 6 of 10
[wait-for-migrations] Waiting 16 seconds before next attempt
[wait-for-migrations] Attempt 7 of 10
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 8 of 10
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 9 of 10
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 10 of 10
[wait-for-migrations] ERROR: Database migrations not applied

##### ENVIRONMENT
* AWX version: 19.3.0
* AWX install method: operator
* AWX deployment target:  minikube
* Operating System: RH 7.9
* Web Browser: Chrome 

##### STEPS TO REPRODUCE

Postgres DB v12 installed externally , unable to migrate in minikube/operator type of setup 

##### EXPECTED RESULTS

operator should quickly migrate external postgres DB that its structure is adequate for new AWX version

##### ACTUAL RESULTS

 minikube kubectl logs awx-768d58d7bf-s5mmd awx-task
[wait-for-migrations] Waiting for database migrations...
[wait-for-migrations] Attempt 1 of 10
[wait-for-migrations] Waiting 0.5 seconds before next attempt
...
[wait-for-migrations] Attempt 10 of 10
[wait-for-migrations] ERROR: Database migrations not applied

**Comment by shanemcd** [comment]
Did you follow these steps? https://github.com/ansible/awx-operator/blob/devel/docs/migration.md

**Comment by shanemcd** [comment]
Please confirm that you followed the steps pertaining to the secret key.

**Comment by olokolo250** [comment]
yes, the awx-postgres-configuration and awx-secret-key secret is configured

**Comment by colixxx** [comment]
I faced a similar problem. I talked about it [here](https://github.com/ansible/awx-operator/issues/402)

**Comment by olokolo250** [comment]
yes, thats exactly the same issue,  getting the same output for "awx-manage migrate" command 

...
  Applying main.0136_scm_track_submodules... OK
2021-08-30 10:26:20,731 INFO     [-] awx.main.migrations deleted (32892, {'main.ActivityStream_unified_job': 0, 'main.UnifiedJob_dependent_jobs': 258, 'main.UnifiedJob_notifications': 0, 'main.UnifiedJob_labels': 0, 'main.UnifiedJob_credentials': 0, 'main.JobLaunchConfig_credentials': 0, 'main.ActivityStream_inventory_update': 0, 'main.InventoryUpdateEvent': 31344, 'main.InventoryUpdate': 430, 'main.JobLaunchConfig': 430, 'main.UnifiedJob': 430})
2021-08-30 10:26:20,732 INFO     [-] awx.main.migrations Deleted 430 custom inventory script sources.
  Applying main.0137_custom_inventory_scripts_removal_data...Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/__init__.py", line 164, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/commands/migrate.py", line 232, in handle
    post_migrate_state = executor.migrate(
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/migrations/_inventory_source.py", line 105, in delete_custom_inv_source
    ct, deletions = InventorySource.objects.filter(source='custom').delete()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 710, in delete
    collector.collect(del_query)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/deletion.py", line 224, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/deletion.py", line 15, in CASCADE
    collector.collect(sub_objs, source=field.remote_field.model,
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/deletion.py", line 224, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/utils/polymorphic.py", line 18, in SET_NULL
    return models.SET_NULL(collector, field, sub_objs.non_polymorphic(), using)
AttributeError: 'QuerySet' object has no attribute 'non_polymorphic'

**Comment by olokolo250** [comment]
Hi, I managed to complete migration by disabling /var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/migrations/0137_custom_inventory_scripts_removal_data.py in awx-task pod 

I simply commented one line in that file  "# migrations.RunPython(delete_custom_inv_source)," 

could someone take a closer look and code proper fix for that please. 


_bash-4.4# cat 0137_custom_inventory_scripts_removal_data.py
# Generated by Django 2.2.16 on 2021-04-13 19:51

from django.db import migrations

# AWX migration utils
from awx.main.migrations._inventory_source import delete_custom_inv_source


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0136_scm_track_submodules'),
    ]

    operations = [
      #  migrations.RunPython(delete_custom_inv_source),
    ]_

**Comment by chrismeyersfsu** [comment]
@olokolo250 Instead of commenting that migration line. Can you try applying this code change and migrate? https://github.com/ansible/awx/commit/b0c511a7a25a8219b09d4953b8bb40ca293a8edd

**Comment by colixxx** [comment]
@olokolo250 Hi, how you can change file in container? Exec in container via awx user only. But file have root perm.
i could rebuild the image but can't find the dockerfile

**Comment by adandanielteamint** [comment]
Im having this same problem but doing a fresh install... I dont know why...

**Comment by santosh-sagam** [comment]
I have similar problem with below version

AWX version: 22.1.0
AWX install method: operator
AWX deployment target: k3s
Operating System: RH 7.9 or rhel8.7
Web Browser: Chrome
