### ISSUE TITLE
issue with ansible fortimanager modules 

### ISSUE THREAD

**Issue by sanjay-chahar** [ansible/awx#10962]
##### ISSUE TYPE
Ansible fortimanager miodules issue
  File "/tmp/ansible_fortios_system_global_payload_axggyhx6/ansible_fortios_system_global_payload.zip/ansible/module_utils/connection.py", line 1                                                       85, in __rpc__
ansible.module_utils.connection.ConnectionError: Method not found
fatal: [192.168.252.131]: FAILED! => {

##### COMPONENT NAME
 ansible_httpapi 

##### SUMMARY
Playbook execution failoed with below error

The full traceback is:
Traceback (most recent call last):
  File "/home/sanjay/.ansible/tmp/ansible-local-35476kmds0_w/ansible-tmp-1630162401.703714-276545883982005/AnsiballZ_fortios_system_global.py", l                                                       ine 247, in <module>
    _ansiballz_main()
  File "/home/sanjay/.ansible/tmp/ansible-local-35476kmds0_w/ansible-tmp-1630162401.703714-276545883982005/AnsiballZ_fortios_system_global.py", l                                                       ine 237, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/sanjay/.ansible/tmp/ansible-local-35476kmds0_w/ansible-tmp-1630162401.703714-276545883982005/AnsiballZ_fortios_system_global.py", l                                                       ine 108, in invoke_module
    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_global', init_globals=None, run_name='__main__                                                       ', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_fortios_system_global_payload_axggyhx6/ansible_fortios_system_global_payload.zip/ansible_collections/fortinet/fortios/plugin                                                       s/modules/fortios_system_global.py", line 11045, in <module>
  File "/tmp/ansible_fortios_system_global_payload_axggyhx6/ansible_fortios_system_global_payload.zip/ansible_collections/fortinet/fortios/plugin                                                       s/modules/fortios_system_global.py", line 11022, in main
  File "/tmp/ansible_fortios_system_global_payload_axggyhx6/ansible_fortios_system_global_payload.zip/ansible_collections/fortinet/fortios/plugin                                                       s/module_utils/fortios/fortios.py", line 248, in check_schema_versioning
  File "/tmp/ansible_fortios_system_global_payload_axggyhx6/ansible_fortios_system_global_payload.zip/ansible/module_utils/connection.py", line 1                                                       85, in __rpc__
ansible.module_utils.connection.ConnectionError: Method not found
fatal: [192.168.252.131]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/sanjay/.ansible/tmp/ansible-local-35476kmds0_w/ansible-tmp-1630162401.70                                                       3714-276545883982005/AnsiballZ_fortios_system_global.py\", line 247, in <module>\n    _ansiballz_main()\n  File \"/home/sanjay/.ansible/tmp/ansib                                                       le-local-35476kmds0_w/ansible-tmp-1630162401.703714-276545883982005/AnsiballZ_fortios_system_global.py\", line 237, in _ansiballz_main\n    invok                                                       e_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/sanjay/.ansible/tmp/ansible-local-35476kmds0_w/ansible-tmp-1630162401.703714-27                                                       6545883982005/AnsiballZ_fortios_system_global.py\", line 108, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.fortinet.forti                                                       os.plugins.modules.fortios_system_global', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line                                                        207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run                                                       _module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_g                                                       lobals)\n  File \"/tmp/ansible_fortios_system_global_payload_axggyhx6/ansible_fortios_system_global_payload.zip/ansible_collections/fortinet/fort                                                       ios/plugins/modules/fortios_system_global.py\", line 11045, in <module>\n  File \"/tmp/ansible_fortios_system_global_payload_axggyhx6/ansible_for                                                       tios_system_global_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_global.py\", line 11022, in main\n  File \"/tm                                                       p/ansible_fortios_system_global_payload_axggyhx6/ansible_fortios_system_global_payload.zip/ansible_collections/fortinet/fortios/plugins/module_ut                                                       ils/fortios/fortios.py\", line 248, in check_schema_versioning\n  File \"/tmp/ansible_fortios_system_global_payload_axggyhx6/ansible_fortios_syst                                                       em_global_payload.zip/ansible/module_utils/connection.py\", line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: Method not fou                                                       nd\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

##### ENVIRONMENT
*sanjay@ub-ansible:~$ ansible --version
ansible 2.9.6
  config file = /home/sanjay/ansible.cfg
  configured module search path = ['/home/sanjay/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]

Inventory file 

sanjay@ub-ansible:~$ more hosts
[fortimanagers]
192.168.252.131 ansible_host=192.168.252.137 #ansible_user="admin" ansible_password="sanjay123"
#fortimanager02 ansible_host=192.168.190.131 ansible_user="admin" ansible_password="password"

[fortigates]
192.168.252.135 ansible_host=192.168.252.137 #ansible_user="admin" ansible_password="sanjay123"

[fortigates:vars]
ansible_network_os=fortinet.fortios.fortios

[fortimanagers:vars]
ansible_network_os=fortinet.fortimanager.fortimanager
#ansible_network_os=fortimanager
#ansible_network_os=fortinet.fortimanager.fmgr_generic
ansible_user=root
ansible_password=sanjay123
ansible_become=no
ansible_become_method=disable
ansible_httpapi_use_ssl=true
ansible_httpapi_validate_certs=false
ansible_httpapi_timeout=300

[fortigates:vars]
ansible_network_os=fortinet.fortios.fortios

Playbook

---
- hosts: fortimanagers
  collections:
   - fortinet.fortios
  connection: httpapi

  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443

  tasks:
  - name: Configure global attributes.
    fortios_system_global:
      vdom:  "{{ vdom }}"
      system_global:
        admintimeout: "60"
        hostname: "fortigate6-ansibe-fortigate6"

##### STEPS TO REPRODUCE

<
sanjay@ub-ansible:~$ ansible-playbook fortimanager.yml -vvvvv
ansible-playbook 2.9.6
  config file = /home/sanjay/ansible.cfg
  configured module search path = ['/home/sanjay/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
Using /home/sanjay/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/sanjay/hosts as it did not pass its verify_file() method
script declined parsing /home/sanjay/hosts as it did not pass its verify_file() method
auto declined parsing /home/sanjay/hosts as it did not pass its verify_file() method
Parsed /home/sanjay/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python3/dist-packages/ansible/plugins/callback/default.py

PLAYBOOK: fortimanager.yml *****************************************************************************************************************************************************************************
Positional arguments: fortimanager.yml
verbosity: 5
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/home/sanjay/hosts',)
forks: 5
1 plays in fortimanager.yml

PLAY [fortimanagers] ***********************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************
task path: /home/sanjay/fortimanager.yml:2
<192.168.252.137> attempting to start connection
<192.168.252.137> using connection plugin httpapi
<192.168.252.137> local domain socket does not exist, starting it
<192.168.252.137> control socket path is /home/sanjay/.ansible/pc/f70db4dc1c
<192.168.252.137> local domain socket listeners started successfully
<192.168.252.137> loaded API plugin ansible_collections.fortinet.fortimanager.plugins.httpapi.fortimanager from path /home/sanjay/.ansible/collections/ansible_collections/fortinet/fortimanager/plugins/httpapi/fortimanager.py for network_os fortinet.fortimanager.fortimanager
<192.168.252.137>
<192.168.252.137> local domain socket path is /home/sanjay/.ansible/pc/f70db4dc1c
<192.168.252.137> ESTABLISH LOCAL CONNECTION FOR USER: sanjay
<192.168.252.137> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/ansible-tmp-1630163290.003947-4413922361289 `" && echo ansible-tmp-1630163290.003947-4413922361289="` echo /home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/ansible-tmp-1630163290.003947-4413922361289 `" ) && sleep 0'
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/default_collectors.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/basic.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/ansible_collector.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/namespace.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/system/service_mgr.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/system/ssh_pub_keys.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/network/linux.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/virtual/netbsd.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/system/date_time.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/system/platform.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/system/user.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/virtual/freebsd.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/hardware/aix.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/system/local.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/hardware/dragonfly.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/network/aix.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/system/pkg_mgr.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/virtual/base.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/hardware/netbsd.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/virtual/openbsd.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/network/dragonfly.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/system/python.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/network/fc_wwn.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/virtual/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/network/netbsd.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/system/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/virtual/sunos.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/network/iscsi.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/virtual/hpux.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/hardware/freebsd.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/other/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/other/ohai.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/system/chroot.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/hardware/base.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/network/nvme.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/network/freebsd.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/hardware/openbsd.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/system/distribution.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/hardware/hurd.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/virtual/linux.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/system/env.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/system/apparmor.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/network/hurd.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/network/base.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/other/facter.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/network/openbsd.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/hardware/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/hardware/hpux.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/hardware/sunos.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/network/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/hardware/darwin.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/network/sunos.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/system/cmdline.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/network/hpux.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/system/fips.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/system/lsb.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/system/selinux.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/system/dns.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/hardware/linux.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/network/darwin.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/system/caps.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/virtual/dragonfly.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/collector.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/_text.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/utils.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/timeout.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/six/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/virtual/sysctl.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/network/generic_bsd.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/sysctl.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/process.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/file.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/sys_info.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/distro/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/_utils.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/distro/_distro.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/text/formatters.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/text/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/_collections_compat.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/validation.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/parameters.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/text/converters.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/pycompat24.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/_json_compat.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/collections.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/facts/compat.py
<192.168.252.131> Attempting python interpreter discovery
<192.168.252.137> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<192.168.252.137> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
Using module file /usr/lib/python3/dist-packages/ansible/modules/system/setup.py
<192.168.252.137> PUT /home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/tmp2ce5ai33 TO /home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/ansible-tmp-1630163290.003947-4413922361289/AnsiballZ_setup.py
<192.168.252.137> EXEC /bin/sh -c 'chmod u+x /home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/ansible-tmp-1630163290.003947-4413922361289/ /home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/ansible-tmp-1630163290.003947-4413922361289/AnsiballZ_setup.py && sleep 0'
<192.168.252.137> EXEC /bin/sh -c '/usr/bin/python3 /home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/ansible-tmp-1630163290.003947-4413922361289/AnsiballZ_setup.py && sleep 0'
ok: [192.168.252.131]
META: ran handlers

TASK [Configure global attributes.] ********************************************************************************************************************************************************************
task path: /home/sanjay/fortimanager.yml:15
<192.168.252.137> attempting to start connection
<192.168.252.137> using connection plugin httpapi
<192.168.252.137> found existing local domain socket, using it!
<192.168.252.137> updating play_context for connection
<192.168.252.137>
<192.168.252.137> local domain socket path is /home/sanjay/.ansible/pc/f70db4dc1c
<192.168.252.137> ESTABLISH LOCAL CONNECTION FOR USER: sanjay
<192.168.252.137> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/ansible-tmp-1630163290.9590342-251428619457870 `" && echo ansible-tmp-1630163290.9590342-251428619457870="` echo /home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/ansible-tmp-1630163290.9590342-251428619457870 `" ) && sleep 0'
Using module_utils file ansible_collections/fortinet/fortios/plugins/module_utils/fortios
Using module_utils file ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios
Using module_utils file ansible_collections
Using module_utils file ansible_collections/fortinet/fortios/plugins
Using module_utils file ansible_collections/fortinet/fortios
Using module_utils file ansible_collections/fortinet/fortios/plugins/module_utils/fortimanager/common
Using module_utils file ansible_collections/fortinet
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/basic.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/connection.py
Using module_utils file ansible_collections/fortinet/fortios/plugins/module_utils
Using module_utils file ansible_collections/fortinet/fortios/plugins/module_utils/fortios/comparison
Using module_utils file ansible_collections/fortinet/fortios/plugins/module_utils/fortimanager
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/_text.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/six/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/text/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/_utils.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/file.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/_collections_compat.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/validation.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/parameters.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/text/converters.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/text/formatters.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/process.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/sys_info.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/pycompat24.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/_json_compat.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/collections.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/distro/__init__.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/distro/_distro.py
Using module_utils file /usr/lib/python3/dist-packages/ansible/module_utils/common/json.py
Using module file /home/sanjay/.ansible/collections/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_global.py
<192.168.252.137> PUT /home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/tmpg_ylznol TO /home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/ansible-tmp-1630163290.9590342-251428619457870/AnsiballZ_fortios_system_global.py
<192.168.252.137> EXEC /bin/sh -c 'chmod u+x /home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/ansible-tmp-1630163290.9590342-251428619457870/ /home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/ansible-tmp-1630163290.9590342-251428619457870/AnsiballZ_fortios_system_global.py && sleep 0'
<192.168.252.137> EXEC /bin/sh -c '/usr/bin/python3 /home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/ansible-tmp-1630163290.9590342-251428619457870/AnsiballZ_fortios_system_global.py && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/ansible-tmp-1630163290.9590342-251428619457870/AnsiballZ_fortios_system_global.py", line 247, in <module>
    _ansiballz_main()
  File "/home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/ansible-tmp-1630163290.9590342-251428619457870/AnsiballZ_fortios_system_global.py", line 237, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/ansible-tmp-1630163290.9590342-251428619457870/AnsiballZ_fortios_system_global.py", line 108, in invoke_module
    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_global', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_fortios_system_global_payload_kvce1ty4/ansible_fortios_system_global_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_global.py", line 11045, in <module>
  File "/tmp/ansible_fortios_system_global_payload_kvce1ty4/ansible_fortios_system_global_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_global.py", line 11022, in main
  File "/tmp/ansible_fortios_system_global_payload_kvce1ty4/ansible_fortios_system_global_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py", line 248, in check_schema_versioning
  File "/tmp/ansible_fortios_system_global_payload_kvce1ty4/ansible_fortios_system_global_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
ansible.module_utils.connection.ConnectionError: Method not found
fatal: [192.168.252.131]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/ansible-tmp-1630163290.9590342-251428619457870/AnsiballZ_fortios_system_global.py\", line 247, in <module>\n    _ansiballz_main()\n  File \"/home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/ansible-tmp-1630163290.9590342-251428619457870/AnsiballZ_fortios_system_global.py\", line 237, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/sanjay/.ansible/tmp/ansible-local-4022508jtsja/ansible-tmp-1630163290.9590342-251428619457870/AnsiballZ_fortios_system_global.py\", line 108, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_global', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_fortios_system_global_payload_kvce1ty4/ansible_fortios_system_global_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_global.py\", line 11045, in <module>\n  File \"/tmp/ansible_fortios_system_global_payload_kvce1ty4/ansible_fortios_system_global_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_global.py\", line 11022, in main\n  File \"/tmp/ansible_fortios_system_global_payload_kvce1ty4/ansible_fortios_system_global_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py\", line 248, in check_schema_versioning\n  File \"/tmp/ansible_fortios_system_global_payload_kvce1ty4/ansible_fortios_system_global_payload.zip/ansible/module_utils/connection.py\", line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: Method not found\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *********************************************************************************************************************************************************************************************
192.168.252.131            : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

sanjay@ub-ansible:~$
##### EXPECTED RESULTS

Its showuld change the name of fortigate device

**Comment by sanjay-chahar** [comment]
HI Raise another one
