### ISSUE TITLE
The job is not transmitted to the container group on remote openshift cluster

### ISSUE THREAD

**Issue by Lee-Kwang** [ansible/awx#11136]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

The job is not transmitted to the container group on the remote openshift cluster.
The pod was created and running on the remote cluster but nothing was found in the pod's log.
The job always ends up with fail after waiting for about 5 mins and get this message:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1406, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2935, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3000, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Error opening pod stream: Get "https://openshift.......container=worker&follow=true": unexpected EOF

### AWX version

19.3.0

### Installation method

openshift

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

create a credential as Openshfit or Kubernetes Bearer Token with Openshfit API url and access token of remote cluster
create a container group with above credential

edit a test job template to run on the above container group.
launch the job.

### Expected results

Normal Job result

### Actual results

Job always fails.

**Comment by Lee-Kwang** [comment]
issue is found to be specific to us. network problem between Azure and Openstack
