### ISSUE TITLE
Jobs failed - Error creating pod - connection refused

### ISSUE THREAD

**Issue by stefanpinter** [ansible/awx#11152]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Hi!
over night around jobs are triggered via API. It worked fine so far but last night some jobs failed! oh no!
what went wrong?

### AWX version

19.3.0

### Installation method

minikube

### Modifications

no

### Operating system

Ubuntu 20.04

### Steps to reproduce

start job via API but I am unsure if it has to be via API... i guess not

### Expected results

Job being started

### Actual results

4 jobs failed
the last one has no text in "output" but this information:
_failed
Task was marked as running but was not present in the job queue, so it has been marked as failed._

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1406, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2935, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3000, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Error creating pod: pods "automation-job-6494-" is forbidden: etcdserver: request timed out

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1406, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2935, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3000, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Error creating pod: Post "https://10.96.0.1:443/api/v1/namespaces/default/pods": dial tcp 10.96.0.1:443: connect: connection refused

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1406, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2935, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3000, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Error creating pod: Post "https://10.96.0.1:443/api/v1/namespaces/default/pods": dial tcp 10.96.0.1:443: connect: connection refused

**Comment by stefanpinter** [comment]
another Job failed with ERROR:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1406, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2935, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3000, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Error creating pod: timed out waiting for the condition, ImagePullBackOff

I am not a fan of this added kubernetes complexity.

**Comment by Lee-Kwang** [comment]
It seems to fail to pull the image. It can happen when image path ( of EE)  is wrong or docker registry secret is wrong.

**Comment by stefanpinter** [comment]
why doesnt it just use the existing one? nothing has changed... it worked multiple times before and after that, just minutes apart.
the template is using quay.io/ansible/awx-ee:latest
in the configuration of the EE "Pull" is set to "--------" whatever that means. i suppose it means "only when missing" because it says "missing" in the EE settings prior to click "edit".

ah.. quay.io download are on AWS as well... i don't understand why we cant download files from AWS anymore.

anyways - it is set to "only when missing" so why does it want to download a new one all of a sudden?

**Comment by olegsidokhmetov** [comment]
I have similar issue :(

```
  Warning  Failed     42s                kubelet            Failed to pull image "quay.io/ansible/awx-ee:latest": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/ansible/awx-ee:latest": failed to copy: httpReaderSeeker: failed open: failed to do request: Get "https://quay.io/v2/ansible/awx-ee/blobs/sha256:988815eef7888246bebc4b1f3f581ccc039000f573c8756d6927473d3d7e1676": dial tcp: lookup quay.io: Try again
  Normal   Pulling    27s (x2 over 57s)  kubelet            Pulling image "quay.io/ansible/awx-ee:latest"
  Warning  Failed     15s                kubelet            Failed to pull image "quay.io/ansible/awx-ee:latest": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/ansible/awx-ee:latest": failed to copy: httpReaderSeeker: failed open: failed to do request: Get "https://quay.io/v2/ansible/awx-ee/blobs/sha256:d89b22c495e691d00db78990bc7e6c5c5f6bcd1e1c758ac8fac9c1a4f1e2c319": dial tcp: lookup quay.io: Try again
  Warning  Failed     15s (x2 over 42s)  kubelet            Error: ErrImagePull
  Normal   BackOff    2s (x2 over 41s)   kubelet            Back-off pulling image "quay.io/ansible/awx-ee:latest"
  Warning  Failed     2s (x2 over 41s)   kubelet            Error: ImagePullBackOff

```

**Comment by Raptus1** [comment]
Got the same issue here using awx 18 ee:0.1.1 and operator 0.14.0 :
in the awx.spec I have the following details:

`  ee_images:
    - name: AWX EE {{ awx_ee_version }}
      image: {{ custom_image_repo }}{{ awx_ee_image }}:{{ awx_ee_version }}
  control_plane_ee_image: {{ custom_image_repo }}{{ awx_ee_image }}:{{ awx_control_plane_ee_version }}
  task_privileged: true
  extra_settings:
    - setting: CONTROL_PLANE_EXECUTION_ENVIRONMENT
      value: >-
        "{{ custom_image_repo }}{{ awx_ee_image }}"`

Yet still it is set as quay.io/ansible/awx-ee in awx-gui when I deploy awx, and even though I add a new default EE in the settings, I still get the ImagePull issue where it wants to use quay.io registry.

**Comment by rmarzo** [comment]
Any updates about this?
I have the same problem... I ran a job in awx ui , it worked with success; after 1 hour, I ran the SAME job with this failure: 
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  6m9s                 default-scheduler  Successfully assigned awx/automation-job-11-th6h7 to minikube
  Warning  Failed     107s (x2 over 4m1s)  kubelet            Failed to pull image "quay.io/ansible/awx-ee:latest": rpc error: code = Unknown desc = context deadline exceeded
  Warning  Failed     107s (x2 over 4m1s)  kubelet            Error: ErrImagePull
  Normal   BackOff    92s (x2 over 4m1s)   kubelet            Back-off pulling image "quay.io/ansible/awx-ee:latest"
  Warning  Failed     92s (x2 over 4m1s)   kubelet            Error: ImagePullBackOff
  Normal   Pulling    81s (x3 over 6m)     kubelet            Pulling image "quay.io/ansible/awx-ee:latest"
