### ISSUE TITLE
Failing Job produces no output (how to debug this?)

### ISSUE THREAD

**Issue by twhiston** [ansible/awx#1118]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
When running some playbooks they fail with no output

##### ENVIRONMENT
* AWX version:  1.0.2.75
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: RHEL

##### STEPS TO REPRODUCE

In this specific case I am trying to run the openshift byo config.yml playbook, but i'm not sure that this is the root cause.
I set up the job and trigger it, it fails, and no output at all is written. Note that perhaps the job is failing for a valid reason, but how can I tell what that is?

Trying to get the output from the tower-cli also produces no helpful output 

```
☿ tower-cli job stdout 37
OK. (changed: false)`
```

Other ad-hoc commands directly on the host work correctly and write to stdout as expected

##### EXPECTED RESULTS

Something is output that explains why the job fails

##### ACTUAL RESULTS

Output is blank

##### ADDITIONAL INFORMATION

In the task worked logs some data is output, but it directs you to stdout, which is of course blank
```
2018-02-02 12:08:21,895 DEBUG    awx.main.scheduler Starting job 38 (pending) in group tower (remaining_capacity=275)
2018-02-02 12:08:21,895 DEBUG    awx.main.scheduler Starting job 38 (pending) in group tower (remaining_capacity=275)
[2018-02-02 12:08:21,895: DEBUG/ForkPoolWorker-324] Starting job 38 (pending) in group tower (remaining_capacity=275)
2018-02-02 12:08:21,977 INFO     awx.main.scheduler Submitting job 38 (waiting) to instance group 1.
2018-02-02 12:08:21,977 INFO     awx.main.scheduler Submitting job 38 (waiting) to instance group 1.
[2018-02-02 12:08:21,977: INFO/ForkPoolWorker-324] Submitting job 38 (waiting) to instance group 1.
2018-02-02 12:08:22,058 DEBUG    awx.main.scheduler job 38 (waiting) consumed 20 capacity units from tower with prior total of 0
2018-02-02 12:08:22,058 DEBUG    awx.main.scheduler job 38 (waiting) consumed 20 capacity units from tower with prior total of 0
[2018-02-02 12:08:22,058: DEBUG/ForkPoolWorker-324] job 38 (waiting) consumed 20 capacity units from tower with prior total of 0
[2018-02-02 12:08:22,089: DEBUG/ForkPoolWorker-324] Start from server, version: 0.9, properties: {'information': 'Licensed under the MPL.  See http://www.rabbitmq.com/', 'product': 'RabbitMQ', 'copyright': 'Copyright (C) 2007-2015 Pivotal Software, Inc.', 'capabilities': {'exchange_exchange_bindings': True, 'connection.blocked': True, 'authentication_failure_close': True, 'basic.nack': True, 'per_consumer_qos': True, 'consumer_priorities': True, 'consumer_cancel_notify': True, 'publisher_confirms': True}, 'cluster_name': 'rabbit@XXXXXXXX', 'platform': 'Erlang/OTP', 'version': '3.5.7'}, mechanisms: ['AMQPLAIN', 'PLAIN'], locales: [u'en_US']
[2018-02-02 12:08:22,090: DEBUG/ForkPoolWorker-324] using channel_id: 1
[2018-02-02 12:08:22,091: DEBUG/ForkPoolWorker-324] Channel open
[2018-02-02 12:08:22,110: INFO/MainProcess] Received task: awx.main.tasks.run_job[35a87a6f-2cc4-428d-9cd7-11370ddb70ab]
[2018-02-02 12:08:22,111: INFO/MainProcess] Scaling up 1 processes.
[2018-02-02 12:08:22,115: INFO/ForkPoolWorker-324] Task awx.main.scheduler.tasks.run_job_launch[158c411f-6068-457c-96ab-135c3f844ffe] succeeded in 1.44872143492s: None
[2018-02-02 12:08:22,234: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x1e93c80> (args:('awx.main.tasks.run_job', '35a87a6f-2cc4-428d-9cd7-11370ddb70ab', {'origin': 'gen579@awx', 'lang': 'py', 'task': 'awx.main.tasks.run_job', 'group': None, 'root_id': '158c411f-6068-457c-96ab-135c3f844ffe', u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'tower', u'exchange': u''}, 'expires': None, u'correlation_id': '35a87a6f-2cc4-428d-9cd7-11370ddb70ab', 'retries': 0, 'timelimit': [None, None], 'argsrepr': '[38]', 'eta': None, 'parent_id': '158c411f-6068-457c-96ab-135c3f844ffe', u'reply_to': 'a42c8b04-b3e5-382a-bd65-a5762728a982', 'id': '35a87a6f-2cc4-428d-9cd7-11370ddb70ab', 'kwargsrepr': '{}'}, u'[[38], {}, {"chord": null, "callbacks": [{"chord_size": null, "task": "awx.main.tasks.handle_work_success", "subtask_type": null, "kwargs": {"task_actual": {"type": "job", "id": 38}}, "args": [], "options": {}, "immutable": false}], "errbacks": [{"chord_size": null, "task": "awx.main.tasks.handle_work_error", "subtask_type": null, "kwargs": {"subtasks": [{"type": "job", "id": 38}]},... kwargs:{})
[2018-02-02 12:08:22,236: DEBUG/MainProcess] basic.qos: prefetch_count->1288
[2018-02-02 12:08:22,238: DEBUG/ForkPoolWorker-326] Closed channel #1
[2018-02-02 12:08:22,240: DEBUG/MainProcess] Task accepted: awx.main.tasks.run_job[35a87a6f-2cc4-428d-9cd7-11370ddb70ab] pid:579
[2018-02-02 12:08:23,708: INFO/MainProcess] Received task: awx.main.tasks.update_inventory_computed_fields[ecba1b6a-5e98-4b82-a60a-9b28ba98c279]
[2018-02-02 12:08:23,708: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x1e93c80> (args:('awx.main.tasks.update_inventory_computed_fields', 'ecba1b6a-5e98-4b82-a60a-9b28ba98c279', {'origin': 'gen579@awx', 'lang': 'py', 'task': 'awx.main.tasks.update_inventory_computed_fields', 'group': None, 'root_id': '158c411f-6068-457c-96ab-135c3f844ffe', u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'tower', u'exchange': u''}, 'expires': None, u'correlation_id': 'ecba1b6a-5e98-4b82-a60a-9b28ba98c279', 'retries': 0, 'timelimit': [None, None], 'argsrepr': '(2, True)', 'eta': None, 'parent_id': '35a87a6f-2cc4-428d-9cd7-11370ddb70ab', u'reply_to': '6ac4aa64-0b39-39d4-a106-91a4a7c7780b', 'id': 'ecba1b6a-5e98-4b82-a60a-9b28ba98c279', 'kwargsrepr': '{}'}, u'[[2, true], {}, {"chord": null, "callbacks": null, "errbacks": null, "chain": null}]', 'application/json', 'utf-8') kwargs:{})
[2018-02-02 12:08:23,716: DEBUG/MainProcess] Task accepted: awx.main.tasks.update_inventory_computed_fields[ecba1b6a-5e98-4b82-a60a-9b28ba98c279] pid:581
2018-02-02 12:08:23,734 DEBUG    awx.main.tasks Executing error task id <Context: {'origin': 'gen579@awx', u'args': [38], u'chain': None, 'root_id': '158c411f-6068-457c-96ab-135c3f844ffe', 'expires': None, u'is_eager': False, u'correlation_id': '35a87a6f-2cc4-428d-9cd7-11370ddb70ab', u'chord': None, u'reply_to': 'a42c8b04-b3e5-382a-bd65-a5762728a982', '_children': [<AsyncResult: ecba1b6a-5e98-4b82-a60a-9b28ba98c279>], 'id': '35a87a6f-2cc4-428d-9cd7-11370ddb70ab', 'kwargsrepr': '{}', 'lang': 'py', 'retries': 0, 'task': 'awx.main.tasks.run_job', 'group': None, 'timelimit': [None, None], u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'tower', u'exchange': u''}, u'hostname': u'celery@localhost', 'called_directly': False, 'parent_id': '158c411f-6068-457c-96ab-135c3f844ffe', 'argsrepr': '[38]', u'errbacks': [{u'chord_size': None, u'task': u'awx.main.tasks.handle_work_error', u'args': [], u'immutable': False, u'subtask_type': None, u'kwargs': {u'subtasks': [{u'type': u'job', u'id': 38}]}, u'options': {}}], u'callbacks': [{u'chord_size': None, u'task': u'awx.main.tasks.handle_work_success', u'args': [], u'immutable': False, u'subtask_type': None, u'kwargs': {u'task_actual': {u'type': u'job', u'id': 38}}, u'options': {}}], u'kwargs': {}, 'eta': None, '_protected': 1}>, subtasks: [{u'type': u'job', u'id': 38}]
2018-02-02 12:08:23,734 DEBUG    awx.main.tasks Executing error task id <Context: {'origin': 'gen579@awx', u'args': [38], u'chain': None, 'root_id': '158c411f-6068-457c-96ab-135c3f844ffe', 'expires': None, u'is_eager': False, u'correlation_id': '35a87a6f-2cc4-428d-9cd7-11370ddb70ab', u'chord': None, u'reply_to': 'a42c8b04-b3e5-382a-bd65-a5762728a982', '_children': [<AsyncResult: ecba1b6a-5e98-4b82-a60a-9b28ba98c279>], 'id': '35a87a6f-2cc4-428d-9cd7-11370ddb70ab', 'kwargsrepr': '{}', 'lang': 'py', 'retries': 0, 'task': 'awx.main.tasks.run_job', 'group': None, 'timelimit': [None, None], u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'tower', u'exchange': u''}, u'hostname': u'celery@localhost', 'called_directly': False, 'parent_id': '158c411f-6068-457c-96ab-135c3f844ffe', 'argsrepr': '[38]', u'errbacks': [{u'chord_size': None, u'task': u'awx.main.tasks.handle_work_error', u'args': [], u'immutable': False, u'subtask_type': None, u'kwargs': {u'subtasks': [{u'type': u'job', u'id': 38}]}, u'options': {}}], u'callbacks': [{u'chord_size': None, u'task': u'awx.main.tasks.handle_work_success', u'args': [], u'immutable': False, u'subtask_type': None, u'kwargs': {u'task_actual': {u'type': u'job', u'id': 38}}, u'options': {}}], u'kwargs': {}, 'eta': None, '_protected': 1}>, subtasks: [{u'type': u'job', u'id': 38}]
[2018-02-02 12:08:23,734: DEBUG/ForkPoolWorker-324] Executing error task id <Context: {'origin': 'gen579@awx', u'args': [38], u'chain': None, 'root_id': '158c411f-6068-457c-96ab-135c3f844ffe', 'expires': None, u'is_eager': False, u'correlation_id': '35a87a6f-2cc4-428d-9cd7-11370ddb70ab', u'chord': None, u'reply_to': 'a42c8b04-b3e5-382a-bd65-a5762728a982', '_children': [<AsyncResult: ecba1b6a-5e98-4b82-a60a-9b28ba98c279>], 'id': '35a87a6f-2cc4-428d-9cd7-11370ddb70ab', 'kwargsrepr': '{}', 'lang': 'py', 'retries': 0, 'task': 'awx.main.tasks.run_job', 'group': None, 'timelimit': [None, None], u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'tower', u'exchange': u''}, u'hostname': u'celery@localhost', 'called_directly': False, 'parent_id': '158c411f-6068-457c-96ab-135c3f844ffe', 'argsrepr': '[38]', u'errbacks': [{u'chord_size': None, u'task': u'awx.main.tasks.handle_work_error', u'args': [], u'immutable': False, u'subtask_type': None, u'kwargs': {u'subtasks': [{u'type': u'job', u'id': 38}]}, u'options': {}}], u'callbacks': [{u'chord_size': None, u'task': u'awx.main.tasks.handle_work_success', u'args': [], u'immutable': False, u'subtask_type': None, u'kwargs': {u'task_actual': {u'type': u'job', u'id': 38}}, u'options': {}}], u'kwargs': {}, 'eta': None, '_protected': 1}>, subtasks: [{u'type': u'job', u'id': 38}]
2018-02-02 12:08:23,760 DEBUG    awx.main.models.inventory Going to update inventory computed fields
[2018-02-02 12:08:23,760: DEBUG/ForkPoolWorker-326] Going to update inventory computed fields
2018-02-02 12:08:23,837 DEBUG    awx.main.models.inventory Finished updating inventory computed fields
[2018-02-02 12:08:23,837: DEBUG/ForkPoolWorker-326] Finished updating inventory computed fields
[2018-02-02 12:08:23,844: INFO/ForkPoolWorker-326] Task awx.main.tasks.update_inventory_computed_fields[ecba1b6a-5e98-4b82-a60a-9b28ba98c279] succeeded in 0.132328880019s: None
2018-02-02 12:08:23,961 WARNING  awx.main.tasks job 38 (error) encountered an error (rc=None), please see task stdout for details.
2018-02-02 12:08:23,961 WARNING  awx.main.tasks job 38 (error) encountered an error (rc=None), please see task stdout for details.
[2018-02-02 12:08:23,961: WARNING/ForkPoolWorker-324] job 38 (error) encountered an error (rc=None), please see task stdout for details.
[2018-02-02 12:08:23,962: ERROR/ForkPoolWorker-324] Task awx.main.tasks.run_job[35a87a6f-2cc4-428d-9cd7-11370ddb70ab] raised unexpected: Exception('job 38 (error) encountered an error (rc=None), please see task stdout for details.',)
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 483, in _wrapped
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 924, in run
    raise AwxTaskError.TaskError(instance, rc)
Exception: job 38 (error) encountered an error (rc=None), please see task stdout for details.
[2018-02-02 12:08:23,963: INFO/MainProcess] Received task: awx.main.scheduler.tasks.run_job_complete[66beed69-6e2f-401a-adca-dfdc95da6a7f]
[2018-02-02 12:08:23,963: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x1e93c80> (args:('awx.main.scheduler.tasks.run_job_complete', '66beed69-6e2f-401a-adca-dfdc95da6a7f', {'origin': 'gen579@awx', 'lang': 'py', 'task': 'awx.main.scheduler.tasks.run_job_complete', 'group': None, 'root_id': '158c411f-6068-457c-96ab-135c3f844ffe', u'delivery_info': {u'priority': 0, u'redelivered': False, u'routing_key': u'tower_scheduler.job.complete', u'exchange': u'scheduler'}, 'expires': None, u'correlation_id': '66beed69-6e2f-401a-adca-dfdc95da6a7f', 'retries': 0, 'timelimit': [None, None], 'argsrepr': '(38,)', 'eta': None, 'parent_id': '35a87a6f-2cc4-428d-9cd7-11370ddb70ab', u'reply_to': '6ac4aa64-0b39-39d4-a106-91a4a7c7780b', 'id': '66beed69-6e2f-401a-adca-dfdc95da6a7f', 'kwargsrepr': '{}'}, u'[[38], {}, {"chord": null, "callbacks": null, "errbacks": null, "chain": null}]', 'application/json', 'utf-8') kwargs:{})
[2018-02-02 12:08:23,965: DEBUG/MainProcess] Task accepted: awx.main.scheduler.tasks.run_job_complete[66beed69-6e2f-401a-adca-dfdc95da6a7f] pid:581
```

**Comment by Kaskouilles** [comment]
hello i have same issue, the playbook works in command line but launched from awx it's failed with no output.

**Comment by wenottingham** [comment]
What is job 38 in your case? Usually the error you see implies a Tower service errored before the playbook ran.

**Comment by itamarshpak** [comment]
hey, i am experiencing same issue, in my case the job is just the hello world one from the tower docs [http://docs.ansible.com/ansible-tower/2.4.1/html/quickstart/create_job.html](url) ,the job failed with no output and the log from the task container is same as:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 584, in _wrapped
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 1014, in run
    raise AwxTaskError.TaskError(instance, rc)
Exception: job 48 (error) encountered an error (rc=None), please see task stdout for details.

*****I am using awx with docker containers and docker compose*****

**Comment by itamarshpak** [comment]
Solved it, apperantly the playbooks need to be in awx_task container and in awx_web container both @twhiston

**Comment by wenottingham** [comment]
Yes, if you're using a manual project it needs to be in both places.
