### ISSUE TITLE
Job Templates API endpoint produces error

### ISSUE THREAD

**Issue by twhiston** [ansible/awx#1119]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Visiting the API endpoint /api/v2/job_templates/ results in a server error

##### ENVIRONMENT
AWX version: 1.0.2.75
AWX install method: docker on linux
Ansible version: 2.4.2.0
Operating System: RHEL

##### STEPS TO REPRODUCE

Create a workflow and do not edit it, delete it, in my case it is not removed from the UI, then visit the api page

##### EXPECTED RESULTS

Workflows/job templates are shown as expected

##### ACTUAL RESULTS

```
Server Error
GET /api/v2/job_templates/
HTTP 500 Internal Server Error
Content-Type: application/json
Vary: Accept
{
    "detail": "A server error has occurred."
}
```

##### ADDITIONAL INFORMATION

Web Logs
```
2018-02-02 12:59:17,022 ERROR    django.request Internal Server Error: /api/v2/job_templates/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 253, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/mixins.py", line 45, in list
    return self.get_paginated_response(serializer.data)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/serializers.py", line 738, in data
    ret = super(ListSerializer, self).data
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/serializers.py", line 656, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/usr/lib/python2.7/site-packages/awx/api/serializers.py", line 611, in to_representation
    return super(UnifiedJobTemplateSerializer, self).to_representation(obj)
  File "/usr/lib/python2.7/site-packages/awx/api/serializers.py", line 2407, in to_representation
    ret = super(JobOptionsSerializer, self).to_representation(obj)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/serializers.py", line 500, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/fields.py", line 1816, in to_representation
    return method(value)
  File "/usr/lib/python2.7/site-packages/awx/api/serializers.py", line 300, in _get_related
    return {} if obj is None else self.get_related(obj)
  File "/usr/lib/python2.7/site-packages/awx/api/serializers.py", line 2536, in get_related
    res = super(JobTemplateSerializer, self).get_related(obj)
  File "/usr/lib/python2.7/site-packages/awx/api/serializers.py", line 580, in get_related
    if obj.current_job:
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 184, in __get__
    rel_obj = self.get_object(instance)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 159, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: UnifiedJob matching query does not exist.
2018-02-02 12:59:17,022 ERROR    django.request Internal Server Error: /api/v2/job_templates/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 253, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/mixins.py", line 45, in list
    return self.get_paginated_response(serializer.data)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/serializers.py", line 738, in data
    ret = super(ListSerializer, self).data
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/serializers.py", line 656, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/usr/lib/python2.7/site-packages/awx/api/serializers.py", line 611, in to_representation
    return super(UnifiedJobTemplateSerializer, self).to_representation(obj)
  File "/usr/lib/python2.7/site-packages/awx/api/serializers.py", line 2407, in to_representation
    ret = super(JobOptionsSerializer, self).to_representation(obj)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/serializers.py", line 500, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/fields.py", line 1816, in to_representation
    return method(value)
  File "/usr/lib/python2.7/site-packages/awx/api/serializers.py", line 300, in _get_related
    return {} if obj is None else self.get_related(obj)
  File "/usr/lib/python2.7/site-packages/awx/api/serializers.py", line 2536, in get_related
    res = super(JobTemplateSerializer, self).get_related(obj)
  File "/usr/lib/python2.7/site-packages/awx/api/serializers.py", line 580, in get_related
    if obj.current_job:
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 184, in __get__
    rel_obj = self.get_object(instance)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 159, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: UnifiedJob matching query does not exist.
```

**Comment by twhiston** [comment]
In the end the only way I could solve this was by deleting the db and starting again, which was a bit of a painful fix! Seems directly related to #1100

**Comment by AlanCoding** [comment]
I'm not able to reproduce this.

 - Create a new WFJT with no organization
 - Navigate down in the list, click the delete button

That does produce some strange UI behavior, for example:

![screen shot 2018-02-07 at 11 16 47 am](https://user-images.githubusercontent.com/1385596/35927414-a7229fee-0bf8-11e8-9e21-308fc8de0f6f.png)

But this is because I deleted the workflow while the edit page for the workflow was still open. That's a minor UI bug which could use fixing.

However, none of the obvious endpoints result in a server error after trying this myself.

**Comment by wenottingham** [comment]
Please reopen if you're able to reproduce this error on 1.0.6 or later; we believe this issue is fixed.
