### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#11207]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary
Potentially introduced by https://github.com/ansible/awx/pull/11133

I created my local environment from scratch today using latest devel and I'm not able to run jobs, this error is poping up on console:

```
tools_awx_1     | awx-dispatcher stdout | Traceback (most recent call last):
tools_awx_1     | awx-dispatcher stdout |   File "manage.py", line 8, in <module>
tools_awx_1     | awx-dispatcher stdout |     manage()
tools_awx_1     | awx-dispatcher stdout |   File "/awx_devel/awx/__init__.py", line 171, in manage
tools_awx_1     | awx-dispatcher stdout |     execute_from_command_line(sys.argv)
tools_awx_1     | awx-dispatcher stdout |   File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
tools_awx_1     | awx-dispatcher stdout |     utility.execute()
tools_awx_1     | awx-dispatcher stdout |   File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
tools_awx_1     | awx-dispatcher stdout |     self.fetch_command(subcommand).run_from_argv(self.argv)
tools_awx_1     | awx-dispatcher stdout |   File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
tools_awx_1     | awx-dispatcher stdout |     self.execute(*args, **cmd_options)
tools_awx_1     | awx-dispatcher stdout |   File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 364, in execute
tools_awx_1     | awx-dispatcher stdout |     output = self.handle(*args, **options)
tools_awx_1     | awx-dispatcher stdout |   File "/awx_devel/awx/main/management/commands/run_dispatcher.py", line 62, in handle
tools_awx_1     | awx-dispatcher stdout |     consumer.run()
tools_awx_1     | awx-dispatcher stdout |   File "/awx_devel/awx/main/dispatch/worker/base.py", line 149, in run
tools_awx_1     | awx-dispatcher stdout |     self.worker.on_start()
tools_awx_1     | awx-dispatcher stdout |   File "/awx_devel/awx/main/dispatch/worker/task.py", line 128, in on_start
tools_awx_1     | awx-dispatcher stdout |     dispatch_startup()
tools_awx_1     | awx-dispatcher stdout |   File "/awx_devel/awx/main/tasks.py", line 170, in dispatch_startup
tools_awx_1     | awx-dispatcher stdout |     cluster_node_heartbeat()
tools_awx_1     | awx-dispatcher stdout |   File "/awx_devel/awx/main/tasks.py", line 539, in cluster_node_heartbeat
tools_awx_1     | awx-dispatcher stdout |     inspect_execution_nodes(instance_list)
tools_awx_1     | awx-dispatcher stdout |   File "/awx_devel/awx/main/tasks.py", line 483, in inspect_execution_nodes
tools_awx_1     | awx-dispatcher stdout |     worktypes.append(c["WorkType"])
tools_awx_1     | awx-dispatcher stdout | TypeError: string indices must be integers

```

### AWX version

devel

### Installation method

docker on linux

### Modifications

no

### Operating system

Ubuntu LTS

### Web browser

Chrome

### Steps to reproduce

1. make docker-clean-volumes
2. docker system prune -a -f
3. COMPOSE_TAG=devel CLUSTER_NODE_COUNT=1 make docker-compose

### Expected results

awx up and running able to run jobs

### Actual results

Jobs stuck in pending state

**Comment by tiagodread** [comment]
This is now fixed!
