### ISSUE TITLE
vanilla 19.4.0 awx.main.dispatch.periodic periodic beat crash

### ISSUE THREAD

**Issue by mrwiora** [ansible/awx#11211]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

running the latest awx version on my **on-premise** kubernetes cluster I get the following repeating (~1s) error in logs of the corresponding task pod:

````
Instance Group already registered controlplane
Instance Group already registered default
(changed: True)
2021-10-06 03:19:44,672 WARNING  [-] awx.main.dispatch scaling up worker pid:297
2021-10-06 03:19:44,679 WARNING  [-] awx.main.dispatch scaling up worker pid:298
2021-10-06 03:19:44,686 WARNING  [-] awx.main.dispatch scaling up worker pid:299
2021-10-06 03:19:44,693 WARNING  [-] awx.main.dispatch scaling up worker pid:300
2021-10-06 03:19:44,696 WARNING  [-] awx.main.dispatch Running worker dispatcher listening to queues ['tower_broadcast_all', 'awx-demo-74b7c95c54-8265x']
2021-10-06 03:19:44,708 DEBUG    [-] awx.main.tasks Syncing Schedules
2021-10-06 03:19:44,727 DEBUG    [-] awx.main.tasks Waited 0.0006389617919921875 seconds to obtain lock name: cluster_policy_lock
2021-10-06 03:19:44,737 DEBUG    [-] awx.main.tasks Total instances: 1, available for policy: 1
2021-10-06 03:19:44,738 DEBUG    [-] awx.main.tasks Policy percentage, adding Instances [1] to Group controlplane
2021-10-06 03:19:44,739 DEBUG    [-] awx.main.tasks Cluster policy no-op finished in 0.010987520217895508 seconds
2021-10-06 03:19:44,740 DEBUG    [-] awx.main.tasks Cluster node heartbeat task.
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/__init__.py", line 171, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/run_dispatcher.py", line 62, in handle
    consumer.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/dispatch/worker/base.py", line 149, in run
    self.worker.on_start()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/dispatch/worker/task.py", line 128, in on_start
    dispatch_startup()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 170, in dispatch_startup
    cluster_node_heartbeat()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 536, in cluster_node_heartbeat
    inspect_execution_nodes(instance_list)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 475, in inspect_execution_nodes
    ctl = get_receptor_ctl()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/utils/receptor.py", line 50, in get_receptor_ctl
    receptor_sockfile = get_receptor_sockfile()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/utils/receptor.py", line 22, in get_receptor_sockfile
    with open(__RECEPTOR_CONF, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/receptor/receptor.conf'
2021-10-06 03:19:45,147 INFO exited: dispatcher (exit status 1; not expected)
2021-10-06 03:19:45,147 INFO exited: dispatcher (exit status 1; not expected)
2021-10-06 03:19:46,150 INFO spawned: 'dispatcher' with pid 301
2021-10-06 03:19:46,150 INFO spawned: 'dispatcher' with pid 301
2021-10-06 03:19:47,151 INFO success: dispatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-10-06 03:19:47,151 INFO success: dispatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-10-06 03:19:48,465 WARNING  [-] awx.main.dispatch.periodic periodic beat started
```` 

### AWX version

19.4.0

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

awxstorage.yml
```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-demo-postgres-0
  labels:
    app: awx-demo-postgres-0
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-awx-demo-postgres-0
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: awx-demo-postgres-0
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: "awx-demo-postgres-0"
```

awxservice.yml
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: LoadBalancer
  ingress_type: none
  hostname: awx-demo.example.com
  image_version: 19.4.0
```

### Expected results

an up and running container, that produces no further error logs

### Actual results

docker logs is producing errors

### Additional information

on-premise setup with metall-lb and weave network

**Comment by CWollinger** [comment]
Same here. Unable to sync projects

**Comment by fust** [comment]
+1
The EE containers aren't even created

**Comment by CWollinger** [comment]
I think this is because of some changes regarding the receptor.conf and socket:

AWX Operator: https://github.com/ansible/awx-operator/commit/fc9cd6bdb12d2afe4e3918128c48f2a13a1c62a0#diff-ffa438a6fcaf00ccb436a124570d42f6d84ad72078f9a7fd3d9e594f01780b4e & https://github.com/ansible/awx-operator/commit/eb4b5b9b908e3c8582c36d9e1a395bf9d9e45ded#diff-ffa438a6fcaf00ccb436a124570d42f6d84ad72078f9a7fd3d9e594f01780b4e

AWX: https://github.com/ansible/awx/commit/42484cf98ddd2e9ffb8d9c0cf8eb35abb2eb3a93#diff-177c3041e06856968094bcca4def757abbf9ce49a16c62845b538fb8a67ef325

So either we edit the deployments.apps afterwards or we are using the new awx-operator 0.14

**Comment by fust** [comment]
I agree it looks that way. Good find!
That complicates things a bit as the upgrade path to awx-operator 0.14 isn't as straigh-forward but I can live with that.
I hoped to postpone that for a couple of days and do a quick update to AWX 19.4.0 as it contains a fix for LDAP we desperately need.

**Comment by mrwiora** [comment]
@fust: try this: https://github.com/ansible/awx-operator/pull/592 - already created a PR, as I was struggling with this too.
I will check in a moment version 0.14 and report back, if we're fine with that version regarding the beat crash topic

**Comment by fust** [comment]
If I understand correctly the only difference is specifying the NAMESPACE in the env?
That isn't an issue for us as we use a custom Kustomize build for our Gitlab CI/CD pipelines.

I'll have to admit I haven't really looked into why upgrading to 0.14 didn't "just work" for me, will take a look at upgrading the operator first and then updating AWX tomorrow morning.

**Comment by fust** [comment]
Updating the operator to 0.14 and then updating AWX to 19.4.0 works like a charm.
Additional steps to update the operator are required, multiple PRs have been opened for this.

I followed the steps in this PR: https://github.com/ansible/awx-operator/pull/593/files
Then updated our custom Kustomize deployment pipeline to deploy the new operator and then updated AWX.
Downtime for AWX was around a minute or so.

**Comment by mrwiora** [comment]
works as expected - closing case :) thanks to all
