### ISSUE TITLE
Set AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT with setting module of awx collection

### ISSUE THREAD

**Issue by mick1627** [ansible/awx#11222]
##### ISSUE TYPE
 - Feature Idea
 
Trying to set  AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT with settings module of awx collection 

```yaml
- name: Set the value of AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT
  settings:
    name: "AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT"
    value: "10m"
```

Raised this error :

```yaml
TASK [Set the value of AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT] ****************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT'
fatal: [localhost]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-tmp-1633693454.1335557-74-197260893426883/AnsiballZ_settings.py", line 100, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-tmp-1633693454.1335557-74-197260893426883/AnsiballZ_settings.py", line 92, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-tmp-1633693454.1335557-74-197260893426883/AnsiballZ_settings.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.awx.awx.plugins.modules.settings', init_globals=dict(_module_fqn='ansible_collections.awx.awx.plugins.modules.settings', _modlib_path=modlib_path),
      File "/usr/lib64/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_settings_payload_5v1dphqk/ansible_settings_payload.zip/ansible_collections/awx/awx/plugins/modules/settings.py", line 180, in <module>
      File "/tmp/ansible_settings_payload_5v1dphqk/ansible_settings_payload.zip/ansible_collections/awx/awx/plugins/modules/settings.py", line 140, in main
    KeyError: 'AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

```
##### SUMMARY
In some case, we observed that 5 minutes for AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT is not enough when pods are waiting the cluster to add new node using autoscaling.
It seems not possible to set this setting using  awx collection

**Comment by chrismeyersfsu** [comment]
`AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT` isn't something that can be set via the API.

Can you try the below `awx-operator` feature instead and report back if it worked for you?
https://github.com/ansible/awx-operator#extra-settings

**Comment by chrismeyersfsu** [comment]
This card is to track the addition of `AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT` to the api settings.

**Comment by mick1627** [comment]
> `AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT` isn't something that can be set via the API.
> 
> Can you try the below `awx-operator` feature instead and report back if it worked for you? https://github.com/ansible/awx-operator#extra-settings

Thanks, It works using extra-settings :

```yaml
spec:
  extra_settings:
    - setting: AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT
      value: '"10m"'
```

I had to use simple quote in the value to be sure to have the double quote in the settings.py.
