### ISSUE TITLE
Postgres issue with using dynamic inventory, { ERROR:  value too long for type character varying(512) }

### ISSUE THREAD

**Issue by easmithdev** [ansible/awx#11232]
##### ISSUE TYPE
 - Bug Report
 

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
When trying to use a dynamic inventory, I received the error message from Postgres
**ERROR:  value too long for type character varying(512)**
I saw the same error when using AWX version 19.2.1, and decided to do a clean install of AWX version 19.4.0. 
I'm still experiencing the same exact error.

I did verify the dynamic inventory works with ansible-core by using ansible-inventory -i <inventory-script.py> --list, and also with ansible-inventory -i <inventory-script.py> --host <hostname>. The inventory script works correctly. The problem comes when data output from the inventory script attempts to be inserted into the Postgres database.

##### ENVIRONMENT
* AWX version: 19.4.0
* AWX install method: operator
* AWX deployment target: kubernetes
* Operating System: Ubuntu
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Dynamic Inventory script is written in python3, and stored in SCM project. 
2. In AWX have inventory source be script located in SCM project.
3. Attempt Inventory Sync

##### EXPECTED RESULTS

All hosts and groups show up in AWX inventory

##### ACTUAL RESULTS

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 554, in update_or_create
    obj = self.select_for_update().get(**kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 406, in get
    raise self.model.DoesNotExist(
awx.main.models.inventory.Group.DoesNotExist: Group matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(512)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2717, in post_run_hook
    cmd.perform_update(options, data, inventory_update)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/inventory_import.py", line 986, in perform_update
    self.load_into_database()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/inventory_import.py", line 743, in load_into_database
    self._create_update_groups()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/inventory_import.py", line 498, in _create_update_groups
    group = self.inventory.groups.update_or_create(name=group_name, defaults={'variables': json.dumps(mem_group.variables), 'description': group_desc})[
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 680, in update_or_create
    return super(RelatedManager, self.db_manager(db)).update_or_create(**kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 559, in update_or_create
    obj, created = self._create_object_from_params(kwargs, params, lock=True)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 575, in _create_object_from_params
    obj = self.create(**params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/models/base.py", line 329, in save
    super(PrimordialModel, self).save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/models/base.py", line 176, in save
    super(CreatedModifiedModel, self).save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/base.py", line 743, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/base.py", line 780, in save_base
    updated = self._save_table(
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/base.py", line 873, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/base.py", line 910, in _do_insert
    return manager._insert([self], fields=fields, return_id=update_pk,
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/sql/compiler.py", line 1377, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(512)

**Comment by easmithdev** [comment]
This will now be closed. 

The reason for the error I was seeing was the related to the children of a group. The children is supposed to be a list of group names. What was happening is I used the actual group dictionary as the reference as a child. As a result, the dictionary was being expanded into the children list instead of just listing the dictionary name. It was thereby creating an entry that was indeed far too large. So, the issue was my dynamic inventory script, and NOT Postgres.
