### ISSUE TITLE
task Get OS info for sdb failing due to "docker info | grep 'Operating System" is missing 

### ISSUE THREAD

**Issue by praetorianguards** [ansible/awx#11438]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Almalinux docker info
docker Version:      3.3.1 
API Version:  3.3.1 
Go Version:   go1.16.7 
Built:        Tue Nov  9 13:25:58 2021 
OS/Arch:      linux/amd64

docker info ist missing the  'Operating System output
i tried to fix the taks by modifying 
/docker-compose/ansible/roles/sources/tasks/main.yml
to hostnamectl | grep 'Operating System'

task is now sucksessful
but build is failing 

### AWX version

19.5.0

### Installation method

docker on linux

### Modifications

no

### Ansible version

[core 2.12.1]

### Operating system

AlmaLinux 8.5 (Arctic Sphynx)

### Steps to reproduce

fresh install
pip3 install ansible docker-compose

git clone -b 19.5.0 https://github.com/ansible/awx.git

make docker-compose-build

vi tools/docker-compose/ansible/roles/sources/tasks/main.yml
change 
hostnamectl | grep 'Operating System'

### Expected results

docker running

### Actual results

> docker-compose -f tools/docker-compose/_sources/docker-compose.yml  up  --remove-orphans Traceback (most recent call last):   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen     httplib_response = self._make_request(   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request     conn.request(method, url, **httplib_request_kw)   File "/usr/lib64/python3.8/http/client.py", line 1255, in request     self._send_request(method, url, body, headers, encode_chunked)   File "/usr/lib64/python3.8/http/client.py", line 1301, in _send_request     self.endheaders(body, encode_chunked=encode_chunked)   File "/usr/lib64/python3.8/http/client.py", line 1250, in endheaders     self._send_output(message_body, encode_chunked=encode_chunked)   File "/usr/lib64/python3.8/http/client.py", line 1010, in _send_output     self.send(msg)   File "/usr/lib64/python3.8/http/client.py", line 950, in send     self.connect()   File "/usr/local/lib/python3.8/site-packages/docker/transport/unixconn.py", line 30, in connect     sock.connect(self.unix_socket) FileNotFoundError: [Errno 2] No such file or directory  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send     resp = conn.urlopen(   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen     retries = retries.increment(   File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment     raise six.reraise(type(error), error, _stacktrace)   File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise     raise value.with_traceback(tb)   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen     httplib_response = self._make_request(   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request     conn.request(method, url, **httplib_request_kw)   File "/usr/lib64/python3.8/http/client.py", line 1255, in request     self._send_request(method, url, body, headers, encode_chunked)   File "/usr/lib64/python3.8/http/client.py", line 1301, in _send_request     self.endheaders(body, encode_chunked=encode_chunked)   File "/usr/lib64/python3.8/http/client.py", line 1250, in endheaders     self._send_output(message_body, encode_chunked=encode_chunked)   File "/usr/lib64/python3.8/http/client.py", line 1010, in _send_output     self.send(msg)   File "/usr/lib64/python3.8/http/client.py", line 950, in send     self.connect()   File "/usr/local/lib/python3.8/site-packages/docker/transport/unixconn.py", line 30, in connect     sock.connect(self.unix_socket) urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 214, in _retrieve_server_version     return self.version(api_version=False)["ApiVersion"]   File "/usr/local/lib/python3.8/site-packages/docker/api/daemon.py", line 181, in version     return self._result(self._get(url), json=True)   File "/usr/local/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner     return f(self, *args, **kwargs)   File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 237, in _get     return self.get(url, **self._set_request_timeout(kwargs))   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get     return self.request('GET', url, **kwargs)   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request     resp = self.send(prep, **send_kwargs)   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send     r = adapter.send(request, **kwargs)   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send     raise ConnectionError(err, request=request) requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/usr/local/bin/docker-compose", line 8, in <module>     sys.exit(main())   File "/usr/local/lib/python3.8/site-packages/compose/cli/main.py", line 81, in main     command_func()   File "/usr/local/lib/python3.8/site-packages/compose/cli/main.py", line 200, in perform_command     project = project_from_options('.', options)   File "/usr/local/lib/python3.8/site-packages/compose/cli/command.py", line 60, in project_from_options     return get_project(   File "/usr/local/lib/python3.8/site-packages/compose/cli/command.py", line 152, in get_project     client = get_client(   File "/usr/local/lib/python3.8/site-packages/compose/cli/docker_client.py", line 41, in get_client     client = docker_client(   File "/usr/local/lib/python3.8/site-packages/compose/cli/docker_client.py", line 170, in docker_client     client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)   File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 197, in __init__     self._version = self._retrieve_server_version()   File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 221, in _retrieve_server_version     raise DockerException( docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory')) make: *** [Makefile:472: docker-compose] Error 1

**Comment by praetorianguards** [comment]
i was able to start after 
yum install docker-ce docker-ce-cli containerd.io
