### ISSUE TITLE
500 error from /api/v2/inventories/N/update_inventory_sources/

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#11574]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

The UPDATE ALL button to update multiple inventory sources can give a 500 error

### AWX version

19.5.0

### Installation method

docker on linux

### Modifications

no

### Ansible version

devel

### Operating system

N/A

### Web browser

Chrome

### Steps to reproduce

Create an inventory with inventory sources which are expected to fail updates. Click the "UPDATE ALL" button, same as the API update_inventory_sources sub-endpoint

### Expected results

not an error code

### Actual results

Internal server error, with this in logs.

```
2022-01-20 20:46:23,833 ERROR    [6cbbadbd89ef4712b274b7cc1bef992f] django.request Internal Server Error: /api/v2/inventories/1939/update_inventory_sources/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/api/generics.py", line 332, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/api/generics.py", line 217, in finalize_response
    'error': response.data.get('error', response.status_text),
AttributeError: 'list' object has no attribute 'get'
```

**Comment by akus062381** [comment]
@kialam @AlexSCorey could this be related to the bug both of you saw?

**Comment by kialam** [comment]
No, however this is the actual bug: https://github.com/ansible/awx/issues/11575

**Comment by CFSNM** [comment]
Validated manually from QE side. Closing the issue

**Comment by tvo318** [comment]
@AlanCoding - should this go in the release notes to read:
> The UPDATE ALL button to update multiple inventory sources no longer produces a 500 error message

?

**Comment by AlanCoding** [comment]
A 500 is a server error, so these are universally understood to be bug fixes. I'm also not sure if the bug was ever in a released version of the product, so I would probably opt to take no docs action.
