### ISSUE TITLE
Server error doing a GET to /api/v2/instances/N/

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#11575]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Detail view of an instance gives a 500 doing a GET request as an organization admin

### AWX version

19.5.0

### Installation method

docker on linux

### Modifications

no

### Ansible version

devel

### Operating system

N/A

### Web browser

Chrome

### Steps to reproduce

 - create a new user
 - make user admin of an organization
 - create an instance group and add an instance
 - add the instance group to the org's instance groups
 - try to view the instance in that IG as the org admin

I might have missed some details, this is from `tests/api/rbac/test_instance_group_rbac.py::TestInstanceGroupRBAC::test_org_admin` test.

### Expected results

works

### Actual results

500 server error

### Additional information

logs

```
2022-01-20 20:51:08,268 ERROR    [c25d4a7f57904ceabe3945e152cdb51a] django.request Internal Server Error: /api/v2/instances/1/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/api/generics.py", line 332, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/generics.py", line 208, in get
    return self.retrieve(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/rest_framework/views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/api/permissions.py", line 136, in has_object_permission
    return self.has_permission(request, view, obj)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/api/permissions.py", line 127, in has_permission
    response = self.check_permissions(request, view, obj)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/api/permissions.py", line 118, in check_permissions
    result = check_method and check_method(request, view, obj)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/api/permissions.py", line 53, in check_get_permissions
    return check_user_access(request.user, view.model, 'read', obj)
AttributeError: 'InstanceDetail' object has no attribute 'model'
```

**Comment by kialam** [comment]
This is also happening if you are signed in as a system auditor.

**Comment by jbradberry** [comment]
This is 1) my fault I think, and 2) highly relevant for the final bits of the mesh visualizer work.  :frowning_face:

**Comment by jbradberry** [comment]
The PR, #11591, has merged.

**Comment by CFSNM** [comment]
Hop nodes are accesible from the "/api/v2/instances/ endpoint, but they are not part of the "default" group. Is that correct or they should be part of it?

**Comment by AlanCoding** [comment]
^ That is correct.

 - hybrid and execution nodes can run jobs, inventory updates, and ad hoc commands (user content)
   - instances are valid candidates for `default` IG and all user-created IGs
 - control and hybrid nodes can run project updates and system jobs
   - all of these instances (and no other instances) should be in the `controlplane` IG

So hop nodes should never be in any instance group.

**Comment by CFSNM** [comment]
Merged PR from QE side with new automated tests that validate this issue. Closing
