### ISSUE TITLE
awx.awx.group fails to create a group if preserve_existing_hosts or preserve_existing_children is true

### ISSUE THREAD

**Issue by RussTech** [ansible/awx#11687]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

awx.awx.group will not create a new group if preseve_existing flags are set to true.  

### AWX version

Automation Platform 2.1

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

no

### Ansible version

core 2.12.1

### Operating system

Redhat 8.5

### Steps to reproduce

This code will create a **new** group named group_1 in inventory_1.  It will add hostname1 to the group as a member. 
```yml
- name: tower_host_inv | Add host to inventory group
    awx.awx.group: 
      state: present
      name: "group_1" 
      inventory: "inventory_1"
      hosts:
        - "hostname1"
```
This code will add hostname2, to the **existing** group, leaving hostname1 in the group
```yml
- name: tower_host_inv | Add host to inventory group
    awx.awx.group: 
      state: present
      name: "group_1" 
      inventory: "inventory_1"
      preserve_existing_hosts: true
      hosts:
        - "hostname2"
```
This code will fail if the group **does not exist** 
```yml
- name: tower_host_inv | Add host to inventory group
    awx.awx.group: 
      state: present
      name: "group_1" 
      inventory: "inventory_1"
      preserve_existing_hosts: true
      hosts:
        - "hostname1"
```

### Expected results

Running this code should create the group if it does not exist and add the host to it. 
This code should also add the host to the existing group leaving existing hosts in the group.  
```yml
- name: tower_host_inv | Add host to inventory group
    awx.awx.group: 
      state: present
      name: "group_1" 
      inventory: "inventory_1"
      preserve_existing_hosts: true
      hosts:
        - "hostname1"
```

### Actual results

An exception occurred during task execution. To see the full traceback, use -vvv.  The error was: "TypeError: 'NoneType' object is not subscriptable

### Additional information

awx.awx collection version: 19.4.0

as a workaround, I can run these two tasks to get the desired result. 
```yml
  - name: Creates group if missing, makes no changes if group already exists 
    awx.awx.group: 
      state: present
      name: "group_1"
      inventory: "inventory_1"
    register: group_result

  - name: Adds host to existing group, leaves other hosts in group
    ansible.builtin.uri:
      url: "https://awxserver/api/v2/groups/{{ group_result['id'] }}/hosts/"
      method: POST
      headers:
        Content-Type: "application/json"
        Authorization: "Bearer {{ pat }}"
      body_format: json
      body: 
        name: "hostname1"
      use_proxy: false
      validate_certs: false
      status_code: [200, 204]
    no_log: true
```

**Comment by antony-with-no-h** [comment]
Issue also occuring for me [edit: also on awx.awx 19.4.0]

```yaml
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not subscriptable
fatal: [localhost]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/tmp/user/.ansible/ansible-tmp-1645446402.4450126-7808-255643934480798/AnsiballZ_group.py", line 100, in <module>
        _ansiballz_main()
      File "/tmp/user/.ansible/ansible-tmp-1645446402.4450126-7808-255643934480798/AnsiballZ_group.py", line 92, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/tmp/user/.ansible/ansible-tmp-1645446402.4450126-7808-255643934480798/AnsiballZ_group.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.awx.awx.plugins.modules.group', init_globals=dict(_module_fqn='ansible_collections.awx.awx.plugins.modules.group', _modlib_path=modlib_path),
      File "/usr/lib64/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_awx.awx.group_payload_vfhksw7_/ansible_awx.awx.group_payload.zip/ansible_collections/awx/awx/plugins/modules/group.py", line 184, in <module>
      File "/tmp/ansible_awx.awx.group_payload_vfhksw7_/ansible_awx.awx.group_payload.zip/ansible_collections/awx/awx/plugins/modules/group.py", line 173, in main
    TypeError: 'NoneType' object is not subscriptable
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

My workaround is to run `awx.awx.group` twice

**Comment by AlanCoding** [comment]
Working fine for me now, here the "group_2" does not exit and it works as expected.

```yaml
- name: create host
  awx.awx.host:
    name: hostname2
    inventory: "Demo Inventory"

- name: tower_host_inv | Add host to inventory group
  awx.awx.group:
    state: present
    name: "group_2"
    inventory: "Demo Inventory"
    preserve_existing_hosts: true
    hosts:
      - "hostname2"
```
