### ISSUE TITLE
[tech debt] Overly-aggressive unified job save method errors when another process changes model

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#11698]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This traceback paints a very complete picture of an error case that we should address.

```
2022-02-08 07:55:56,634 ERROR    [dc755b9d534d46fe80d2413561ce1af4] awx.main.tasks.jobs job 3758 (running) Exception occurred while running task
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks/receptor.py", line 401, in _run_internal
    self.task.instance.save(update_fields=['result_traceback'])
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/models/unified_jobs.py", line 879, in save
    self._update_parent_instance()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/models/unified_jobs.py", line 801, in _update_parent_instance
    parent_instance.save(update_fields=update_fields)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/models/jobs.py", line 330, in save
    return super(JobTemplate, self).save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/models/unified_jobs.py", line 280, in save
    super(UnifiedJobTemplate, self).save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/polymorphic/models.py", line 93, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/models/base.py", line 329, in save
    super(PrimordialModel, self).save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/models/base.py", line 176, in save
    super(CreatedModifiedModel, self).save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/models/mixins.py", line 566, in save
    super().save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/base.py", line 743, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/base.py", line 779, in save_base
    parent_inserted = self._save_parents(cls, using, update_fields)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/base.py", line 808, in _save_parents
    updated = self._save_table(
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/base.py", line 858, in _save_table
    raise DatabaseError("Save with update_fields did not affect any rows.")
django.db.utils.DatabaseError: Save with update_fields did not affect any rows.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks/jobs.py", line 764, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks/receptor.py", line 282, in run
    res = self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks/receptor.py", line 405, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Error creating pod: timed out waiting for the condition, ImagePullBackOff
```

At issue here is that `self.task.instance.save(update_fields=['result_traceback'])` should never trigger a call to `_update_parent_instance`, and this causes errors in error processing code... which will result in errors not being reported correctly.

If you peer into the `UnifiedJob.save` method, you can see that it tracks `status_before` and the status after, and compares them, doing an additional `.get` (which it shouldn't do). Then, if the statuses differ, then it incorrectly concludes that it is dealing with a status transition event. This is never true when `update_fields` is given and "status" is not included in the list. Passing `update_fields` is specifically done to isolate actions and keep domains of responsibility separate, to prevent problems like this.

**Comment by AlanCoding** [comment]
I really want to bump priority of this issue because it's such a clear problem with badly written save methods.
