### ISSUE TITLE
Missing partition creation for some project update scenarios

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#11715]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Sometimes the necessary partition for project update events (hourly) does not get created like it needs.

```
2022-02-09 23:52:35,121 ERROR    [-] awx.main.commands.run_callback_receiver Database Error Saving Job Event
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.CheckViolation: no partition of relation "main_projectupdateevent" found for row
DETAIL:  Partition key of the failing row contains (job_created) = (2022-02-09 23:52:27.076482+00).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/dispatch/worker/callback.py", line 130, in flush
    cls.objects.bulk_create(events)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 474, in bulk_create
    ids = self._batched_insert(objs_without_pk, fields, batch_size, ignore_conflicts=ignore_conflicts)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 1202, in _batched_insert
    inserted_id = self._insert(
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/sql/compiler.py", line 1377, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: no partition of relation "main_projectupdateevent" found for row
DETAIL:  Partition key of the failing row contains (job_created) = (2022-02-09 23:52:27.076482+00).
```

I do not have much information beyond that at this moment.

**Comment by AlanCoding** [comment]
We should inspect logs from test runs, and if not seeing this, close this issue.

**Comment by anxstj** [comment]
I experience similar errors on my AWX node:

```
psycopg2.errors.CheckViolation: no partition of relation "main_jobevent" found for row
DETAIL:  Partition key of the failing row contains (job_created) = (2022-06-01 08:00:06.737403+00).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/callback.py", line 140, in flush
    e.save()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/models/base.py", line 176, in save
    super(CreatedModifiedModel, self).save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: no partition of relation "main_jobevent" found for row
DETAIL:  Partition key of the failing row contains (job_created) = (2022-06-01 08:00:06.737403+00)
```
And the corresponding PostgreSQL logs (might not the exact corresponding message, but it's similar):
```
2022-06-01 08:11:23.065 UTC [22031] sql_awx@awx ERROR:  no partition of relation "main_jobevent" found for row
2022-06-01 08:11:23.065 UTC [22031] sql_awx@awx DETAIL:  Partition key of the failing row contains (job_created) = (2022-06-01 08:00:06.737403+00).
2022-06-01 08:11:23.065 UTC [22031] sql_awx@awx STATEMENT:  INSERT INTO "main_jobevent" ("event", "event_data", "failed", "changed", "uuid", "playbook", "play", "role", "task", "counter", "stdout", "verbosity", "start_line", "end_line", "created", "modified", "job_id", "host_id", "host_name", "parent_uuid", "job_created") VALUES ('runner_on_skipped', '{"playbook": "resolver.yml", "playbook_uuid": "7b14beb3-d565-48e7-8362-9a212c5ef4b3", "play": "Deploy resolver", "play_uuid": "7e9b7b58-d9e9-2ddd-43f9-000000000021", "play_pattern": "all", "task": "authorized_key | {{ __calling_task }} | ensure permissons on key", "task_uuid": "7e9b7b58-d9e9-2ddd-43f9-000000005d93", "task_action": "file", "resolved_action": "file", "task_args": "", "task_path": "/runner/requirements_roles/users/tasks/authorized_key.yml:76", "role": "users", "host": "resolver0801", "remote_addr": "resolver0801", "start": "2022-06-01T08:11:22.550782", "end": "2022-06-01T08:11:22.839589", "duration": 0.288807, "event_loop": null, "uuid": "d6c7c071-6fcf-439a-b63f-16bd93460eff"}', false, false, 'd6c7c071-6fcf-439a-b63f-16bd93460eff', 'resolver.yml', 'Deploy resolver', 'users', 'authorized_key | {{ __calling_task }} | ensure permissons on key', 6646, 'ESC[0;36mskipping: [resolver0801]ESC[0m', 0, 4044, 4045, '2022-06-01T08:11:22.839740+00:00'::timestamptz, '2022-06-01T08:11:23.064734+00:00'::timestamptz, 897661, 75, 'resolver0801', '7e9b7b58-d9e9-2ddd-43f9-000000005d93', '2022-06-01T08:00:06.737403+00:00'::timestamptz) RETURNING "main_jobevent"."id"
```

I'm running AWX 20.1.0 with local docker and an external database.

I see the error `ERROR:  no partition of relation "main_projectupdateevent" found for row` every hour to the full hour and the error `ERROR:  no partition of relation "main_jobevent" found for row` also on a recurring pattern. That might be caused by a specific schedule/job. 

The output for the specific job is lost:
```
api/v2/jobs/897661/stdout/?format=json
{"range":{"start":0,"end":0,"absolute_end":0},"content":""}
```

And I can't reproduce the error by just relaunching the job. But at least the last three jobs launched by schedule have no output, so I guess the error is only triggered if a job is started via schedule.

**Comment by anxstj** [comment]
I just recognized that an insert statement might contain events from multiple jobs. In my case, a sliced job is affected, too, that started one hour before the "broken" scheduled job started. But as soon as the "broken" scheduled job started, the sliced job has missing events, too.

I'm wondering if this is related to https://github.com/ansible/awx/issues/12194.

**Comment by AlanCoding** [comment]
The version 20.1.0 is old, and the latest fix landed on April 5. I suspect you don't have that, and upgrading should affect what you're seeing.

**Comment by anxstj** [comment]
I updated to 21.1.0 and the error is gone. Thanks.
