### ISSUE TITLE
Permission denied error when using awx-ee

### ISSUE THREAD

**Issue by yw5vruox7dr** [ansible/awx#11854]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

I got following error while using an custom execution environment as `control_plane_ee_image`:
```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 449, in run
    self.pre_run_hook(self.instance, private_data_dir)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 979, in pre_run_hook
    RunProjectUpdate.make_local_copy(job.project, private_data_dir, scm_revision=job_revision)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 1380, in make_local_copy
    source_branch = git_repo.create_head(tmp_branch_name, p.scm_revision)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/git/repo/base.py", line 386, in create_head
    return Head.create(self, path, commit, force, logmsg)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/git/refs/symbolic.py", line 543, in create
    return cls._create(repo, path, cls._resolve_ref_on_create, reference, force, logmsg)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/git/refs/symbolic.py", line 510, in _create
    ref.set_reference(target, logmsg)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/git/refs/symbolic.py", line 326, in set_reference
    assure_directory_exists(fpath, is_file=True)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/git/util.py", line 177, in assure_directory_exists
    os.makedirs(path, exist_ok=True)
  File "/usr/lib64/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/lib/awx/projects/_8__xxx/.git/refs/heads/awx_internal'
```

### AWX version

20.0.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

yes

### Ansible version

ansible-core: 2.11.3

### Steps to reproduce

AWX Instance:
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-test
  namespace: awx-test
spec:
  service_type: NodePort

  image_pull_secret: awx-test-cp-pull-credentials
  ee_images:
    - name: bsp
      image: xxx/bsp/container/awx-ee:latest
  control_plane_ee_image: xxx/bsp/container/awx-ee:latest
  ```
Some values replaced with `xxx`.

Dockerfile used to build the execution environment:
```docker
FROM quay.io/ansible/awx-ee:latest
RUN python3 -m pip install --no-cache-dir dnspython netaddr python-hpilo
```

### Expected results

Custom EE is working like the original but with three more pip packages.

### Actual results

Got a permission error

### Additional information

Manual creating a directory is possible:

```bash
podman run -it xxx/bsp/container/awx-ee:latest bash

bash-4.4# mkdir -p /var/lib/awx/projects/_8__xxx/.git/refs/heads/awx_internal
bash-4.4# ls /var/lib/awx/projects/_8__xxx/.git/refs/heads/awx_internal

bash-4.4# ls -alZ /var/lib | fgrep ' .'
drwxr-xr-x. 16 root root system_u:object_r:fusefs_t:s0 4096 Mar  7 12:37 .
drwxr-xr-x. 20 root root system_u:object_r:fusefs_t:s0 4096 Mar  7 12:37 ..

bash-4.4# sestatus
bash: sestatus: command not found

bash-4.4# cat /etc/selinux/config
cat: /etc/selinux/config: No such file or directory
```

**Comment by yw5vruox7dr** [comment]
Seems that adding `USER 1000`fixed the problem.

```Docker
FROM quay.io/ansible/awx-ee:latest
USER 1000
RUN python3 -m pip install --no-cache-dir dnspython netaddr python-hpilo
```

But the plugin is still not found:
```
fatal: [localhost]: FAILED! => {"msg": "lookup plugin (dig) not found"}
```
Created new issue: https://github.com/ansible/ansible-runner/issues/1017
