### ISSUE TITLE
Inventory pending delete

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#11892]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Deleted inventories are stuck in pending delete status for weeks. No templates are associated with the inventories. How do I force delete the inventories? 

Azure cli output: `Inventory is already pending deletion.`

### AWX version

19.4

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs

### Installation method

minikube

### Modifications

no

### Ansible version

quay.io/ansible/awx-ee:0.6.0

### Operating system

Centos

### Steps to reproduce

Delete inventory

### Expected results

Inventory should be removed

### Actual results

Status is always pending delete

**Comment by amolgautam25** [comment]
There are two steps here: 
--- Is there a way we can get those inventory updates out of the stuck state?
--- Figure out the Root cause for that and fix it

**Comment by mabashian** [comment]
Just out of curiosity - do these inventories have hosts with a large number of host facts?  We've seen behavior like this before where there are a large number of host facts and deleting the inventory hangs.

**Comment by AlanCoding** [comment]
We really want to look for tracebacks from the delete_inventory task in the server logs for this type of issue.

**Comment by nicolaibaralmueller** [comment]
> Just out of curiosity - do these inventories have hosts with a large number of host facts? We've seen behavior like this before where there are a large number of host facts and deleting the inventory hangs.

No, not large. Maybe 10-20 lines. Did you delete the facts manually? Problem also is that the delete button is frozen. Can't click it again.

**Comment by nicolaibaralmueller** [comment]
> We really want to look for tracebacks from the delete_inventory task in the server logs for this type of issue.

How do I get those logs for the inv delete? @AlanCoding

**Comment by AlanCoding** [comment]
you can grep the logs for "delete_inventory"

https://github.com/ansible/awx/blob/73e02e745aa3d76a43c75b25176bd9972cd82a26/awx/main/tasks/system.py#L796

It might have failed to run the task, or failed while in it. That will only happen once when the delete button was originally clicked. After that, the UI will be very annoying, not allowing you to try again.

**Comment by nicolaibaralmueller** [comment]
Thx @AlanCoding. How do I grep the logs for "delete_inventory"?

**Comment by keithjgrant** [comment]
This question seems like a good one to ask on our mailing list at https://groups.google.com/g/awx-project. You can also join #ansible-awx on https://libera.chat/ and ask your question there.

**Comment by MrBones757** [comment]
Hi All,

I have run into this error trying to delete a dynamic VMWARE Inventory:
Version: 19.5.0

As noted above, the inventories are in the pending delete stage.
These would have had a large number of facts per host as they were dynamically discovered by the VMware inventory plugin.

Stack Trace:
2022-09-20 06:18:24,392 ERROR    [2c422f3c33174c81953037e371ab8fb2] awx.main.tasks Database error deleting inventory 9, but will retry.
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: SSL SYSCALL error: EOF detected


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 884, in delete_inventory
    host.job_events_as_primary_host.update(host=None)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 741, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/sql/compiler.py", line 1471, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: SSL SYSCALL error: EOF detected

Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/__init__.py", line 171, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/run_dispatcher.py", line 62, in handle
    consumer.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/dispatch/worker/base.py", line 151, in run
    for e in conn.events():
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/dispatch/__init__.py", line 39, in events
    self.conn.poll()
psycopg2.OperationalError: SSL SYSCALL error: EOF detected

**Comment by MrBones757** [comment]
Using this:
https://github.com/ansible/awx/issues/3945#issuecomment-496582370

i was able to recover the inventory, and i will try to manually reduce the number of facts and then delete again

**Comment by AlanCoding** [comment]
> SSL SYSCALL error: EOF detected

Was anyone reporting this issue using a managed postgres database? Like the Azure offering.

**Comment by MrBones757** [comment]
Thanks for replying here.
Yes, the awx instance that I received this error on is using AWS RDS (HA active-passive) as it's backend db.

**Comment by AlanCoding** [comment]
We've had multiple similar reports of this type, and actually, https://github.com/ansible/awx/issues/709 was really good reading on the topic for me.

In your case, is it possible that the process which hit this was idle for a long time before hitting the error (not running much jobs before the error)? Some of the settings changes suggested there look really interesting, and maybe it could help your case, but this is speculative, I don't really know.

When we run jobs or system tasks (like the one that deletes inventory), the task is sent to a worker in a worker pool which is semi-persistent. These tend to keep their connections open after running a job or other task. That behavior has started to bother me lately.

**Comment by MrBones757** [comment]
Thanks for your reply here, i'll review the notes in #709 and get back to you - our awx instance is usually fairly busy, with a number of jobs running in parallel most of the time throughout the day, so its unlikely to be due to inactivity, though if system jobs like this use a different worker set, or pg connection it could be related.

I'm fairly sure that we arent using the keepalive settings so i'll look to implement those and report back.

**Comment by MrBones757** [comment]
Hi @AlanCoding

I have had a look at our current configuration and can report the following:
Similar delete tasks are working in one of our other instances / clusters that is running the latest version, but this database is significantly smaller (30,000 jobs vs 150,000) and only a few hundred hosts vs 1500 active, and probably 10,000+ deleted hosts (autoscaling, etc). 

The SSL Mode is set to prefer, but the operator doesn't seem to expose the ability to be able to use the keepalive settings.
We are using certificate auth for both of the above instances, so both of these items don't seem to make a difference.

Its leading me to believe there is possibly an integrity issue in the database of our main awx cluster, or some other inefficiency somewhere...
I'm planning on running an upgrade to the latest version as that has been pretty solid in our other instance.

**Comment by 2and3makes23** [comment]
We are experiencing long (several minutes) waiting times during which inventories we delete stay in "pending delete" state.
At least since one of the last updates (I believe 21.7), inventory deletions usually succeed (which they used to do not some times).
But it still seems awkward waiting minutes for such an operation. Out equivalent but smaller testing instance of AWX (less hosts, less jobs etc.) has no noticable pending deletion times.
Is there any update on this issue?

**Comment by 2and3makes23** [comment]
We are experiencing long (several minutes) waiting times during which inventories we delete stay in "pending delete" state.
At least since one of the last updates (I believe 21.7), inventory deletions usually succeed (which they used to do not some times).
But it still seems awkward waiting minutes for such an operation. Our equivalent but smaller testing instance of AWX (less hosts, less jobs etc.) has no noticable pending deletion times.
Is there any update on this issue?

**Comment by alice-rc** [comment]
We are experiencing this often. Any update on the root cause and or mitigation or an actual fix?

**Comment by 2and3makes23** [comment]
What we ended up doing is always deleting the inventory´s hosts first, which seemed to resolve the issue of pending deletion inventories. Empty inventories always get deleted instantly.

Maybe this workaround is something like a hint to a solution for the root cause of this problem? :)

**Comment by briancline** [comment]
Here's the task system log entry for a recent case of this we're hitting on AAP 2.4:

```
2025-10-31 19:35:27,134 ERROR    [87f8529c3ee64439bb49f922ed0eef46] awx.main.tasks.system Database error deleting inventory 26, but will retry.
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
psycopg.errors.OutOfMemory: out of shared memory
HINT:  You might need to increase max_locks_per_transaction.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/system.py", line 875, in delete_inventory
    host.job_events_as_primary_host.update(host=None)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/query.py", line 1206, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/sql/compiler.py", line 1984, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
django.db.utils.OperationalError: out of shared memory
HINT:  You might need to increase max_locks_per_transaction.
```

It repeats the same entry a few times attempting to retry, but same result each time. This controller has 32GB RAM with about 8GiB in use (plus roughly 8GiB buffer/cache in use), so looks like a DB-imposed limit. The DB runs on the same system - we have about 22,000 jobs in our history and about 36,000 entries in the activity stream.

We're not seeing any slowness or issues running jobs (and none of these inventories have templates attached to them). Just happened to notice it while looking at inventories.

While this is our most recent case, we're seeing 3 affected inventories currently. The other 2 were deleted further back than we have logs for:
 * Inv A (26): kind=smart, 70 hosts, 0 groups, 0 sources, no fact data for them. No running/pending jobs.
 * Inv B (22): kind=normal, 1 host, 1 group, 0 sources, no fact data, no running/pending jobs.
 * Inv C (19): kind=normal, 5 hosts, 3 groups, 0 sources, no fact data, no running/pending jobs.

I verified I can create an empty inventory and delete it without issue just as @2and3makes23 reports.

I attempted to reset the status on all 3 inventories (see [7024486](https://access.redhat.com/solutions/7024486) and [7004592](https://access.redhat.com/solutions/7004592)) so I could re-delete them:
```
$ sudo awx-manage shell_plus
...
>>> Inventory.objects.filter(pending_deletion=True)
<QuerySet [<Inventory: redacted-22>, <Inventory: redacted-19>, <Inventory: redacted-26>]>
>>> Inventory.objects.filter(pending_deletion=True).update(pending_deletion=False)
3
```
Re-deleting via the UI predictably yielded same issue, so at least reproducible.

I updated `/var/lib/pgsql/data/postgresql.conf` to increase `max_locks_per_transaction` from its default value of 64 to 128. After restarting postgres, resetting the status on the 3 inventories again, and retrying the delete, the deletions worked (C took a while, but based on debug logs there were other unrelated tasks going on).

While this fixed our issue, hopefully someone with deeper knowledge about the overall awx schema might know why this increase was needed.

Should we scale `max_locks_per_transaction` with larger job history sizes? We keep a much larger-than-default history backlog for annual compliance/auditing needs -- something that gave us very similar DB pain way back in the AAP 1.2 days on a different system -- but not sure if the size of that table could be the issue here.

Hope this helps.
