### ISSUE TITLE
SAML Login fails with invalid endpoint

### ISSUE THREAD

**Issue by balpert89** [ansible/awx#119]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT
 - Installer

##### SUMMARY
I configured awx to utilize our SSO with the SAML protocol. The login works in principle, but awx receives the response at the wrong port.

Message received:
```
Authentication failed: SAML login failed: ['invalid_response'] (The response was received at https://awx.appagile.io:8052/sso/complete/saml/ instead of https://awx.appagile.io/sso/complete/saml/).
```

I deployed AWX on an OpenShift 3.4 cluster.

##### STEPS TO REPRODUCE

Configure AWX with a SAML Identity Provider. We are using Redhat SSO. No matter what port I configure as a valid redirect uri or which port I configure for my service I get the same error message.

##### EXPECTED RESULTS

I expect AWX to utilize SAML as an Identity Provider.

##### ACTUAL RESULTS

After providing credentials on the SSO login page:
```
Authentication failed: SAML login failed: ['invalid_response'] (The response was received at https://awx.appagile.io:8052/sso/complete/saml/ instead of https://awx.appagile.io/sso/complete/saml/).
```

##### ADDITIONAL INFORMATION

Logfile from inside the awx-web container:
```
[pid: 31\|app: 0\|req: 374/639] 10.1.0.1 () {52 vars in 1015 bytes} [Mon Sep 11 18:55:17 2017] GET /sso/login/saml/?idp=AppAgile => generated 0 bytes in 62 msecs (HTTP/1.1 302) 8 headers in 1167 bytes (1 switches on core 0)
--
  | 10.1.0.1 - - [11/Sep/2017:18:55:17 +0000] "GET /sso/login/saml/?idp=AppAgile HTTP/1.1" 302 5 "https://awx.appagile.io/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" "100.125.192.46"
  | The response was received at https://awx.appagile.io:8052/sso/complete/saml/ instead of https://awx.appagile.io/sso/complete/saml/
  | 2017-09-11 18:55:18,576 ERROR    social Authentication failed: SAML login failed: ['invalid_response'] (The response was received at https://awx.appagile.io:8052/sso/complete/saml/ instead of https://awx.appagile.io/sso/complete/saml/).
  | 10.1.0.1 - - [11/Sep/2017:18:55:18 +0000] "POST /sso/complete/saml/ HTTP/1.1" 302 5 "https://sso-appaoc.tsi-af.de/auth/realms/appagile/protocol/saml?SAMLRequest=fVNNj9owEL3vr0C5J06gKMGCSCn0A4lCBGkPvVReZ7JrKbFTj7PQf7%2BOAyytuvjgSG9m3rx5nsyRNXVLs848yz387gDNw8ieU1NLpC648DotqWIokErWAFLD6SH7tqHjIKStVkZxVXv%2FlN2vYoigjVByKFuvFt5u%2B2mz%2B7Le%2FgKIx8ljyMJwClE8SWYfoimbTGI%2BjZNZmYSTMVRhOEuG0h%2Bg0fIsPEs7ILlWL6IEvbVdF17WttmTqOHcCLGDtUTDpLElYRT74cyPoiJK6HRKo%2FjnkLeyPgjJjGN%2BNqZFSgii8lnbMsUDg8JnVVACYdY5ooHVDZI%2B2PciF1NI78RVlYM%2BClkK%2BXTfnschCenXosj9fHcoBpLsYttSSewa0AfQL4LD9%2F3mTSY7noKLkkCoXjbhqmlrMOAEkYEsdfe8R6jzRafvUMzJbdJbWUt7j9erXNWC%2F3F4fz4r3TDz%2FoRREDlElH7lUmknsQUuKgGld6XJ6lodl9ZaY5%2FR6A68Efmr%2BXlfoXTbay0xcDKjpR2VaYH9y8GJceOlV8ph2Nv0ZW1XcQ9VendbOeV9noVz%2BzkqXfbPCdz2LjSz4pU2Z5P%2BSz6oJndkpw%2BX8O2vmL4C&RelayState=AppAgile" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" "100.125.192.46"
```

Service config: 
```
apiVersion: v1
kind: Service
metadata:
  name: awx-web-svc
  namespace: awx
  selfLink: /api/v1/namespaces/awx/services/awx-web-svc
  uid: ab92885a-94c1-11e7-b586-fa163e77dbc4
  resourceVersion: '17922926'
  creationTimestamp: '2017-09-08T18:15:18Z'
  labels:
    name: awx-web-svc
spec:
  ports:
    - name: https
      protocol: TCP
      port: 8052
      targetPort: 8052
      nodePort: 30083
  selector:
    name: awx-web-deploy
  clusterIP: 172.30.162.123
  type: NodePort
  sessionAffinity: None
status:
  loadBalancer: {}
```

Route config:
```
apiVersion: v1
kind: Route
metadata:
  name: awx-secure
  namespace: awx
  selfLink: /oapi/v1/namespaces/awx/routes/awx-secure
  uid: b3dedd56-970d-11e7-aa04-fa163e1766cf
  resourceVersion: '17921415'
  creationTimestamp: '2017-09-11T16:24:36Z'
  labels:
    name: awx-web-svc
spec:
  host: awx.appagile.io
  to:
    kind: Service
    name: awx-web-svc
    weight: 100
  port:
    targetPort: https
  tls:
    termination: edge
    certificate: "<omitted>"
    key: "<omitted>"
    caCertificate: "<omitted>"
  wildcardPolicy: None
status:
  ingress:
    - host: awx.appagile.io
      routerName: router
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2017-09-11T16:24:36Z'
      wildcardPolicy: None
```

**Comment by balpert89** [comment]
Just a question, does somebody got SAML authentication working with AWX?

**Comment by matburt** [comment]
There are quite a few folks running this in production on Tower. I have not had a chance to investigate why this is not working.

**Comment by matburt** [comment]
alrighty, looks like we are handing the wrong port over for SSO redirect. I'll see if I can get a fix in for this.

**Comment by matburt** [comment]
Could I get you to try #160 

After some spelunking it looks like social-auth isn't getting the right value necessary for python-saml to realize the correct incoming port.

At the moment I don't have a SAML service to test this against with openshift. It might take me until next week until I can fully verify this, so if you can do it that would be super helpful!

**Comment by matburt** [comment]
#161 is better, lets go with that.

**Comment by balpert89** [comment]
I finally got back to this one, but now it seems I cannot bring AWX to generate the needed metadata, browsing to the metadata endpoint provides the following: `Invalid dict settings: sp_acs_url_invalid`

Log from the awx-web container: 
```
2017-09-15 20:42:51,465 ERROR    awx.sso.views unable to generate SAML metadata
--
  | Traceback (most recent call last):
  | File "/usr/lib/python2.7/site-packages/awx/sso/views.py", line 90, in get
  | metadata, errors = saml_backend.generate_metadata_xml()
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social/backends/saml.py", line 238, in generate_metadata_xml
  | saml_settings = OneLogin_Saml2_Settings(config)
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/onelogin/saml2/settings.py", line 104, in __init__
  | ','.join(self.__errors)
  | OneLogin_Saml2_Error: Invalid dict settings: sp_acs_url_invalid

2017-09-15 20:47:01,511 ERROR    awx.sso.views unable to generate SAML metadata
--
  | Traceback (most recent call last):
  | File "/usr/lib/python2.7/site-packages/awx/sso/views.py", line 90, in get
  | metadata, errors = saml_backend.generate_metadata_xml()
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social/backends/saml.py", line 238, in generate_metadata_xml
  | saml_settings = OneLogin_Saml2_Settings(config)
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/onelogin/saml2/settings.py", line 104, in __init__
  | ','.join(self.__errors)
  | OneLogin_Saml2_Error: Invalid dict settings: sp_acs_url_invalid
```
This error is risen because of this (/var/lib/awx/venv/awx/lib/python2.7/site-packages/social/backends/saml.py): 

```
    def generate_metadata_xml(self):
        """
        Helper method that can be used from your web app to generate the XML
        metadata required to link your web app as a Service Provider with
        each IdP you wish to use.

        Returns (metadata XML string, list of errors)

        Example usage (Django):
            from social.apps.django_app.utils import load_strategy, \
                                                     load_backend
            def saml_metadata_view(request):
                complete_url = reverse('social:complete', args=("saml", ))
                saml_backend = load_backend(load_strategy(request), "saml",
                                            complete_url)
                metadata, errors = saml_backend.generate_metadata_xml()
                if not errors:
                    return HttpResponse(content=metadata,
                                        content_type='text/xml')
                return HttpResponseServerError(content=', '.join(errors))
        """
        # python-saml requires us to specify something here even
        # though it's not used
        idp = DummySAMLIdentityProvider()
        config = self.generate_saml_config(idp)
        saml_settings = OneLogin_Saml2_Settings(config) << This one throws an exception
        metadata = saml_settings.get_sp_metadata()
        errors = saml_settings.validate_metadata(metadata)
        return metadata, errors
```

The dummy class (/var/lib/awx/venv/awx/lib/python2.7/site-packages/social/backends/saml.py):
```
class DummySAMLIdentityProvider(SAMLIdentityProvider):
    """
    A placeholder IdP used when we must specify something, e.g. when
    generating SP metadata.

    If OneLogin_Saml2_Auth is modified to not always require IdP
    config, this can be removed.
    """
    def __init__(self):
        super(DummySAMLIdentityProvider, self).__init__(
            'dummy',
            entity_id='https://dummy.none/saml2',
            url='https://dummy.none/SSO',
            x509cert=''
        )
```

Maybe the Dummy class settings are messed up. I am not sure if this error occurs because I messed up the configuration, though (I am not proficient in python). Please take a look at it:

![image](https://user-images.githubusercontent.com/28100685/30502839-3a6285ec-9a68-11e7-990f-4cef2987e8b3.png)

Best regards and have a nice evening (from germany)

**Comment by falencastro** [comment]
The source of this issue, which appears to be the redirection to port 8052, is also preventing access to /api. When I go to http://towerurl/api it redirects me to http://towerurl:8052/api and this port isn't exposed.

**Comment by matburt** [comment]
@falencastro Add a trailing slash:   `http://towerurl/api/` until I get the rewrite rules down.

**Comment by matburt** [comment]
it seems like we are good here? I'm going to close this ... comment if there are still issues.

**Comment by balpert89** [comment]
still got this issue: https://github.com/ansible/awx/issues/119#issuecomment-329902765

**Comment by matburt** [comment]
can you open that one as a new one?

**Comment by oscartcy** [comment]
Still got this issue in AWX 1.0.2.301 docker deployment

awx_web log:
```
x.x.x.x - - [19/Dec/2017:07:12:13 +0000] "GET /sso/login/saml/?idp=okta HTTP/1.1" 302 0 "http://y.y.y.y/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36" "-"
2017/12/19 07:12:14 [warn] 30#0: *129 a client request body is buffered to a temporary file /var/lib/nginx/tmp/client_body/0000000004, client: x.x.x.x, server: _, request: "POST /sso/complete/saml/ HTTP/1.1", host: "y.y.y.y"
The response was received at http://y.y.y.y:8052/sso/complete/saml/ instead of http://y.y.y.y/sso/complete/saml/
2017-12-19 07:12:14,697 ERROR    social Authentication failed: SAML login failed: ['invalid_response'] (The response was received at http://y.y.y.y:8052/sso/complete/saml/ instead of http://y.y.y.y/sso/complete/saml/).
[pid: 27|app: 0|req: 27/86] x.x.x.x () {48 vars in 872 bytes} [Tue Dec 19 07:12:14 2017] POST /sso/complete/saml/ => generated 0 bytes in 74 msecs (HTTP/1.1 302) 7 headers in 322 bytes (1 switches on core 0)
x.x.x.x - - [19/Dec/2017:07:12:14 +0000] "POST /sso/complete/saml/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36" "-"
[pid: 28|app: 0|req: 33/87] x.x.x.x () {42 vars in 716 bytes} [Tue Dec 19 07:12:14 2017] GET /sso/error/ => generated 0 bytes in 19 msecs (HTTP/1.1 301) 6 headers in 185 bytes (1 switches on core 0)
x.x.x.x - - [19/Dec/2017:07:12:14 +0000] "GET /sso/error/ HTTP/1.1" 301 0 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36" "-"

```

Also tested with 1.0.1.316 docker deployment, same issue.

**Comment by batemanst** [comment]
@matburt Can we open this back up?

Also running into the same issue on 1.0.2.289.

```
The response was received at http://aaaaa.aaaaa.com:8052/sso/complete/saml/ instead of https://aaaaa.aaaaa.com/sso/complete/saml/
2017-12-29 16:08:03,685 ERROR    social Authentication failed: SAML login failed: ['invalid_response'] (The response was received at http://aaaa.aaaa.com:8052/sso/complete/saml/ instead of https://aaaa.aaaaa.com/sso/complete/saml/).
```

**Comment by batemanst** [comment]
@matburt @wwitzel3 Any update? I'd be glad to submit a new bug report if that is warranted.

**Comment by newlandk** [comment]
@balpert89 If you're still having issues, take a look at my issue #1016. The SAML process is using [django's built-in method](https://docs.djangoproject.com/en/2.0/ref/request-response/#django.http.HttpRequest.get_port) to get port 8052 from the container. As you can see in the documentation that can be manipulated using a x-forwarded-port header with a proxy.

Arguably, there should always be SSL in front of AWX due to the amount of sensitive information you pass to and from it. This could be done with SSL offload with a proxy like haproxy or nginx today.

**Comment by sudomateo** [comment]
I commented on #1016 with details on how to configure AWX for use with SAML auth.
