### ISSUE TITLE
Cannot view some notification templates in UI

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#11982]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

I can view the list of notification templates but get an error trying to navigate to the page for a notification template.

### AWX version

20.1.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

no

### Ansible version

devel

### Operating system

N/A

### Web browser

Chrome

### Steps to reproduce

I have a notification template that has this data:

```json
{
    "id": 60,
    "type": "notification_template",
    "url": "[/api/v2/notification_templates/60/](https://localhost:8043/api/v2/notification_templates/60/)",
    "related": {
        "named_url": "[/api/v2/notification_templates/NotificationTemplate (email) - AnswerBeautiful淇++Organization - GuitarGene�/](https://localhost:8043/api/v2/notification_templates/NotificationTemplate%20(email)%20-%20AnswerBeautiful%E6%B7%87++Organization%20-%20GuitarGene%EF%BF%BD/)",
        "created_by": "[/api/v2/users/2/](https://localhost:8043/api/v2/users/2/)",
        "modified_by": "[/api/v2/users/2/](https://localhost:8043/api/v2/users/2/)",
        "test": "[/api/v2/notification_templates/60/test/](https://localhost:8043/api/v2/notification_templates/60/test/)",
        "notifications": "[/api/v2/notification_templates/60/notifications/](https://localhost:8043/api/v2/notification_templates/60/notifications/)",
        "copy": "[/api/v2/notification_templates/60/copy/](https://localhost:8043/api/v2/notification_templates/60/copy/)",
        "organization": "[/api/v2/organizations/211/](https://localhost:8043/api/v2/organizations/211/)"
    },
    "summary_fields": {
        "organization": {
            "id": 211,
            "name": "Organization - GuitarGene�",
            "description": "YouDrawerFortuneWeaknessUniversityTitleCityDealImplementConversation秊"
        },
        "created_by": {
            "id": 2,
            "username": "alan",
            "first_name": "",
            "last_name": ""
        },
        "modified_by": {
            "id": 2,
            "username": "alan",
            "first_name": "",
            "last_name": ""
        },
        "user_capabilities": {
            "edit": true,
            "delete": true,
            "copy": true
        },
        "recent_notifications": []
    },
    "created": "2022-03-30T18:51:54.916234Z",
    "modified": "2022-03-30T18:51:55.041358Z",
    "name": "NotificationTemplate (email) - AnswerBeautiful淇",
    "description": "WomanRoutineSectionEventProtectionDateTitleTeaPrincipleFuneral�",
    "organization": 211,
    "notification_type": "email",
    "notification_configuration": {
        "host": "<redacted>",
        "port": 587,
        "sender": "<redacted>",
        "timeout": 30,
        "use_ssl": false,
        "use_tls": false,
        "password": "$encrypted$",
        "username": "<redacted>",
        "recipients": [
            "<redacted>"
        ]
    },
    "messages": {
        "error": {
            "body": "body_error\n",
            "message": "message_error"
        },
        "started": null,
        "success": null,
        "workflow_approval": null
    }
}
```

### Expected results

Able to load page

### Actual results

![Screenshot from 2022-03-30 16-05-33](https://user-images.githubusercontent.com/1385596/160921609-17f4336c-367b-4ec3-a5b6-707ff8c966d9.png)

### Additional information

Chrome logs

```
index.js:9 I18nProvider did not render. A call to i18n.activate still needs to happen or forceRenderOnLocaleChange must be set to false.
react-dom.production.min.js:216 TypeError: Cannot read properties of null (reading 'message')
    at RZ (NotificationTemplateDetail.js:450:35)
    at oo (react-dom.production.min.js:157:137)
    at Ks (react-dom.production.min.js:267:460)
    at Ol (react-dom.production.min.js:250:347)
    at Tl (react-dom.production.min.js:250:278)
    at El (react-dom.production.min.js:250:138)
    at yl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Gi (react-dom.production.min.js:122:325)
us @ react-dom.production.min.js:216
react-dom.production.min.js:216 TypeError: Cannot read properties of null (reading 'message')
    at RZ (NotificationTemplateDetail.js:450:35)
    at oo (react-dom.production.min.js:157:137)
    at Ks (react-dom.production.min.js:267:460)
    at Ol (react-dom.production.min.js:250:347)
    at Tl (react-dom.production.min.js:250:278)
    at El (react-dom.production.min.js:250:138)
    at yl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Gi (react-dom.production.min.js:122:325)
us @ react-dom.production.min.js:216
n.payload @ react-dom.production.min.js:217
fa @ react-dom.production.min.js:130
Vo @ react-dom.production.min.js:184
Ks @ react-dom.production.min.js:269
Ol @ react-dom.production.min.js:250
Tl @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
yl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
pl @ react-dom.production.min.js:237
Io @ react-dom.production.min.js:170
(anonymous) @ useRequest.js:44
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
i @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
i @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ NotificationTemplate.js:48
Fl @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Nl @ react-dom.production.min.js:261
yl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
Jt @ react-dom.production.min.js:73
```

**Comment by AlanCoding** [comment]
Same behavior if there is just 1 notification template in the system.

**Comment by nixocio** [comment]
yeah, I was also able to recreate this one.

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/9053044/161072870-63c1ca79-bc1e-4c16-b3df-272c2d21f3df.png">

**Comment by akus062381** [comment]
resolved
