### ISSUE TITLE
`awx-cli receive --all` results in "KeyError: 'extra_credentials'"

### ISSUE THREAD

**Issue by avalou** [ansible/awx#12034]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY
In order to migrate projects, templates and inventories from Tower to AWX I tried to get every text assets from Tower with the `receive --all` command. Instead of the output I expected, I got the following error stack.

##### ENVIRONMENT
* tower-cli version: 3.3.6
* ansible 2.9.25
* Operating System: rhel 7.9
* host : 127.0.01

##### STEPS TO REPRODUCE
`awx-cli login admin`  

`awx-cli receive --all > ~/received`

##### EXPECTED RESULTS
Getting every possible assets from a Tower instance, in order to migrate to AWX.

##### ACTUAL RESULTS
After a `receive --all` command I get the follow error stack : 
```
Traceback (most recent call last):
  File "/usr/bin/awx-cli", line 9, in <module>
    load_entry_point('ansible-tower-cli==3.3.6', 'console_scripts', 'awx-cli')()
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/conf.py", line 373, in method_with_context_managed
    method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/misc.py", line 332, in receive
    receiver.receive(all=all, asset_input=assets_to_export)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/transfer/receive.py", line 12, in receive
    exported_objects = self.export_assets(all, asset_input)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/transfer/receive.py", line 102, in export_assets
    common.extract_extra_credentials(asset)['items']
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/transfer/common.py", line 426, in extract_extra_credentials
    extra_credentials = load_all_assets(asset['related']['extra_credentials'])
KeyError: 'extra_credentials'
```

As you noticed, this issue kind of concerns Tower. But as I get the same result either with `tower-cli` or `awx-cli`, and that the tower-cli repo is deprecated, I choosed to publish the issue here. If this is not okay, I understand that you would have to close the issue.

**Comment by 12csw1** [comment]
Should this issue be labeled as priority:high?

We are doing research about “Issue Priority Prediction". We have developed a tool to automatically label the priority of an issue. The basic idea is to employ Bert model to encode the textual and code descriptions of the issue, and incorporate the issue’s attributes in the model, then apply multi-task learning to facilitate other information boosting the prediction performance. 
 We have conducted experiments on four GitHub projects with 21700 issues, and results show that 79 accuracy can be achieved.

Our tool shows that this issue has a very large possibility to be labeled as priority:high 
Could you please tell us whether it should be labeled as priority:high?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by jbradberry** [comment]
@avalou as you have already noted, tower-cli is deprecated.  The new awx-cli (https://github.com/ansible/awx/tree/devel/awxkit) does not have a codebase in common with the old tool, so is unlikely to have this same bug.  Closing.
