### ISSUE TITLE
Getting errors during Project sync after upgrade to AWX 21.0.0

### ISSUE THREAD

**Issue by thedatabaseme** [ansible/awx#12111]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Hello,

today I've updated to AWX 21.0.0. The update itself went fine but now, when trying to run a sync on my projects, I always get the error below. I checked the EE and the controlplane EE is set to `latest`. Can anyone support me on this issue. I had to downgrade back to AWX 20.1.0 in order to get this fixed again.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/__main__.py", line 901, in main
    res = run(**run_options)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/interface.py", line 216, in run
    r.run()
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/streaming.py", line 130, in run
    r = ansible_runner.interface.run(**self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/interface.py", line 215, in run
    r = init_runner(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/interface.py", line 123, in init_runner
    rc = RunnerConfig(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/config/runner.py", line 79, in __init__
    super(RunnerConfig, self).__init__(private_data_dir, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'suppress_env_files'


  This can be caused if the version of ansible-runner in your execution environment is out of date.
```

### AWX version

21.0.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Web browser

Firefox

### Steps to reproduce

- Go to Projects page
- Sync an existing project

### Expected results

- Sync should work without an error

### Actual results

- See error above

**Comment by thedatabaseme** [comment]
Ok, found it out by myself. I've messed up to set the ImagePullPolicy correctly in my AWX custom resource. After setting it to `Always`, he pulled the most recent image of the `latest` tag and project sync now works.
