### ISSUE TITLE
Cannot edit a WFJT node from JT to WF approval

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#12228]
When a WFJT has a JT node and the JT was deleted, if the user tries to edit that node and make it a workflow approval node instead, they get this error:
```
TypeError: Cannot read properties of undefined (reading 'unified_job_type')
    at https://ec2-18-206-158-25.compute-1.amazonaws.com/static/js/main.5676adf4.js:2:3307248
    at Array.forEach (<anonymous>)
    at https://ec2-18-206-158-25.compute-1.amazonaws.com/static/js/main.5676adf4.js:2:3306704
    at u (https://ec2-18-206-158-25.compute-1.amazonaws.com/static/js/main.5676adf4.js:2:1280004)
    at Generator._invoke (https://ec2-18-206-158-25.compute-1.amazonaws.com/static/js/main.5676adf4.js:2:1279792)
    at Generator.next (https://ec2-18-206-158-25.compute-1.amazonaws.com/static/js/main.5676adf4.js:2:1280433)
    at An (https://ec2-18-206-158-25.compute-1.amazonaws.com/static/js/main.5676adf4.js:2:1528512)
    at o (https://ec2-18-206-158-25.compute-1.amazonaws.com/static/js/main.5676adf4.js:2:1528716)
    at https://ec2-18-206-158-25.compute-1.amazonaws.com/static/js/main.5676adf4.js:2:1528777
    at new Promise (<anonymous>)
```

Steps to reproduce:
1. Create a job template.
2. Create a workflow job template and assign the job template as the first and only node on the visualizer.
3. Run the job.
4. Delete the job template.
5. Go to the visualizer of the WFJT and edit the deleted node to be a workflow approval. Try to save- you'll see the error.

**Comment by akus062381** [comment]
resolved
