### ISSUE TITLE
RuntimeError: The project could not sync because there is no Execution Environment.

### ISSUE THREAD

**Issue by aishwaryakulkarni31** [ansible/awx#12221]
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 456, in run
    env = self.build_env(self.instance, private_data_dir, private_data_files=private_data_files)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 1031, in build_env
    env = super(RunProjectUpdate, self).build_env(project_update, private_data_dir, private_data_files=private_data_files)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 310, in build_env
    raise RuntimeError('The project could not sync because there is no Execution Environment.')
RuntimeError: The project could not sync because there is no Execution Environment.

I was able to create a custom image and add the execution environment to AWX tower. I selected the built image as execution environment while creating the project.. The error still pops up. 

Suggest a way out please.

**Comment by fosterseth** [comment]
Can you please provide more information about your setup (awx-operator version and awx version)?

does it eventually work if you retry, or does it fail every time?

**Comment by ThomasCappe** [comment]
UP ! I have the same problem .. I use Ansible Automation platform 2.2.1-1.

**Comment by bbaassssiiee** [comment]
The automation hub only works as a registry when deployed to a host using a FQDN. Verify that the execution environment (a container image) is present in the hub, try to pull it to validate your credentials setup.

**Comment by ktomaszx** [comment]
have the same problem, does anyone know what is the reason?

**Comment by bbaassssiiee** [comment]
I ran EEs with a change in global job settings:

AWX_ISOLATION_BASE_PATH: /var/tmp

And a higher user.max_user_namespaces

**Comment by zmanhogmail** [comment]
i am using Ansible Automation platform 2.3 with automation-controller/4.3.8.
I have the same problem randomly... Either project sync job or launch a playbook template job...

May i know how to set "global job settings"?

**Comment by bbaassssiiee** [comment]
> i am using Ansible Automation platform 2.3 with automation-controller/4.3.8. I have the same problem randomly... Either project sync job or launch a playbook template job...
> 
> May i know how to set "global job settings"?

[https://github.com/playingfield/provisioning/blob/main/group_vars/controller/settings.yml](https://github.com/playingfield/provisioning/blob/main/group_vars/controller/settings.yml)
