### ISSUE TITLE
new Organization member can't access SCHEDULES page

### ISSUE THREAD

**Issue by gueux** [ansible/awx#1244]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
I've created new unprivileged member of organization and trying to get list of scheduled jobs via his interface. Every time I get this error:

```
2018-02-14 07:15:32,441 ERROR    django.request Internal Server Error: /api/v2/schedules/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 248, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/mixins.py", line 42, in list
    page = self.paginate_queryset(queryset)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 319, in paginate_queryset
    page = super(ListAPIView, self).paginate_queryset(queryset)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 173, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/pagination.py", line 214, in paginate_queryset
    self.page = paginator.page(page_number)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/paginator.py", line 57, in page
    number = self.validate_number(number)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/paginator.py", line 46, in validate_number
    if number > self.num_pages:
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/paginator.py", line 91, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/paginator.py", line 79, in count
    return self.object_list.count()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 364, in count
    return self.query.get_count(using=self.db)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/query.py", line 499, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/query.py", line 480, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception
ProgrammingError: more than one row returned by a subquery used as an expression
```

##### ENVIRONMENT
* AWX version: 1.0.2.302
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: OSX High Sierra
* Web Browser: 

##### STEPS TO REPRODUCE

- create new user
- assign it as a member organization
- login to new user
- go to "SCHEDULES" page

##### EXPECTED RESULTS

List of scheduled jobs

##### ACTUAL RESULTS

Error with message: "Invalid search term entered. GET returned: 500 A server error has occurred." appears.

##### ADDITIONAL INFORMATION

System Administrator user can access "SCHEDULES" page without any problems.

**Comment by AlanCoding** [comment]
#1214 was intended to fix this bug occurring for org admins. The most simple explanation is that you're still seeing that same bug. With updated code, I can't reproduce with a simple org member right now.

The fix landed in 1.0.2-620, so since you're below that, this is probably it.
