### ISSUE TITLE
tower-cli workflow schema not supporting approval node

### ISSUE THREAD

**Issue by aldobongio** [ansible/awx#12476]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When a workflow schema includes an approval node the tower-cli workflow schema command fails.

### AWX version

21.0.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

5.1.0

### Operating system

Ubuntu WSL on Windows 10

### Web browser

Chrome

### Steps to reproduce

1. Open AWX
2. Create an empty Workflow named _Test_
3. Open a terminal with tower-cli installed and connect to the AWX instance
4. `tower-cli workflow list`
```
== ============================== ============
id              name              organization
== ============================== ============
82 Test                           None
== ============================== ============
```
5. `tower-cli workflow schema 82`
```
[]
```
6. Go back to AWX, select the workflow, open the _Visualizer_, click the _Start_ button, select _Approval_ as _Node Type_, type _Test_ as name, save and leave the Visualizer
7. Go back to the terminal
8. `tower-cli workflow schema 82`

### Expected results

The tower-cli workflow schema command must recognize approval nodes and display them in the result.

### Actual results

```
Traceback (most recent call last):
  File "/usr/local/bin/tower-cli", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tower_cli/conf.py", line 373, in method_with_context_managed
    method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tower_cli/cli/resource.py", line 107, in func
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tower_cli/resources/workflow.py", line 289, in schema
    existing_network = self._get_schema(wfjt)
  File "/usr/local/lib/python3.8/dist-packages/tower_cli/resources/workflow.py", line 264, in _get_schema
    return self._workflow_node_structure(node_results)
  File "/usr/local/lib/python3.8/dist-packages/tower_cli/resources/workflow.py", line 253, in _workflow_node_structure
    schema_dict.append(branch_schema(root_node_id))
  File "/usr/local/lib/python3.8/dist-packages/tower_cli/resources/workflow.py", line 236, in branch_schema
    ujt_key = JOB_TYPES[job_type]
KeyError: 'workflow_approval'
```

**Comment by sarabrajsingh** [comment]
hello @aldobongio - `tower-cli` is deprecated and is no longer supported. please refer to the `awxkit` docs - https://docs.ansible.com/automation-controller/4.1.0/html/controllercli/index.html. this tool is the successor to `tower-cli` and will house the functionality that you're seeking.

please note that importing/exporting Workflow Approval Nodes is a feature that is currently in progress. please keep track of the PR here - https://github.com/ansible/awx/pull/12513.
