### ISSUE TITLE
`make jupyter` broken for docker-compose development environment

### ISSUE THREAD

**Issue by TheRealHaoLiu** [ansible/awx#12673]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

`make jupyter` broken for docker-compose development environment

we should evaluate if this make target is useful/needed and if we should fix or remove it

### AWX version

awx: 21.4.1.dev61+gd2217bc61d.d20220817

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

docker development environment

### Modifications

no

### Operating system

MacOS

### Web browser

Firefox, Chrome

### Steps to reproduce

- standup docker-compose development environment using `make docker-compose`
- validate that development environment come up cleanly by visiting `https://localhost:8043/api/v2` and login
- exec into docker container `docker exec -it tools_awx_1 bash`
- run make target `make jupyter` in `/awx_devel` directory
- encounter the following error
```
bash-5.1$ make jupyter
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/traitlets/traitlets.py", line 645, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/awx-manage", line 9, in <module>
    load_entry_point('awx', 'console_scripts', 'awx-manage')()
  File "/awx_devel/awx/__init__.py", line 201, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django_extensions/management/commands/shell_plus.py", line 125, in run_from_argv
    return super(Command, self).run_from_argv(argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django_extensions/management/commands/shell_plus.py", line 517, in handle
    shell()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django_extensions/management/commands/shell_plus.py", line 253, in run_notebook
    app.initialize(notebook_arguments)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/traitlets/config/application.py", line 110, in inner
    return method(app, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/notebook/notebookapp.py", line 2146, in initialize
    self.init_configurables()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/notebook/notebookapp.py", line 1648, in init_configurables
    connection_dir=self.runtime_dir,
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/traitlets/traitlets.py", line 686, in __get__
    return self.get(obj, cls)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/traitlets/traitlets.py", line 648, in get
    default = obj.trait_defaults(self.name)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/traitlets/traitlets.py", line 1752, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/jupyter_core/application.py", line 106, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/jupyter_core/utils/__init__.py", line 12, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/usr/lib64/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib64/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/lib/awx/.local/share/jupyter'
```

### Expected results

jupyter notebook service start

### Actual results

```
PermissionError: [Errno 13] Permission denied: '/var/lib/awx/.local/share/jupyter'
```

**Comment by philipsd6** [comment]
FWIW, with my rootless podman customization documented in #13337 it works fine for me: :dancers: 

```sh
$ podman exec awx-tools_awx_1 make jupyter
[I 19:30:20.873 NotebookApp] Writing notebook server cookie secret to /var/lib/awx/.local/share/jupyter/runtime/notebook_cookie_secret
[I 19:30:20.874 NotebookApp] Authentication of /metrics is OFF, since other authentication is disabled.
[W 19:30:20.885 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 19:30:20.957 NotebookApp] Serving notebooks from local directory: /awx_devel
[I 19:30:20.957 NotebookApp] Jupyter Notebook 6.5.2 is running at:
[I 19:30:20.957 NotebookApp] http://awx:8888/
[I 19:30:20.957 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 19:34:02.554 NotebookApp] Writing notebook-signing key to /var/lib/awx/.local/share/jupyter/notebook_secret
[W 19:34:02.554 NotebookApp] Notebook Untitled.ipynb is not trusted
[I 19:34:02.832 NotebookApp] Kernel started: 42b42886-b663-42b1-a619-5cbb59a57f54, name: django_extensions
```
