### ISSUE TITLE
Grafana Notification => ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by manuel-held** [ansible/awx#12682]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Administration => Notification - Type Grafana.

Test failed when "ID of the dashboard (optional)" or/and "ID of the panel (optional)" is empty. 

`2022-08-18 10:11:57,916 ERROR    [9170e756] awx.main.tasks.system Send Notification Failed invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/awx_devel/awx/main/tasks/system.py", line 290, in send_notifications
    sent = notification.notification_template.send(notification.subject, notification.body)
  File "/awx_devel/awx/main/models/notifications.py", line 182, in send
    backend_obj = self.notification_class(**notification_configuration)
  File "/awx_devel/awx/main/notifications/grafana_backend.py", line 58, in __init__
    self.panelId = int(panelId) if panelId is not None else None
ValueError: invalid literal for int() with base 10: ''`

and

`2022-08-18 10:09:46,302 ERROR    [c7de9089] awx.main.tasks.system Send Notification Failed invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/awx_devel/awx/main/tasks/system.py", line 290, in send_notifications
    sent = notification.notification_template.send(notification.subject, notification.body)
  File "/awx_devel/awx/main/models/notifications.py", line 182, in send
    backend_obj = self.notification_class(**notification_configuration)
  File "/awx_devel/awx/main/notifications/grafana_backend.py", line 57, in __init__
    self.dashboardId = int(dashboardId) if dashboardId is not None else None
ValueError: invalid literal for int() with base 10: ''`

The reason i think is that '' is not None so '' is passed to int() and triggers the Error

AWX Version: Ansible AWX 21.4.0
Grafana Version: v9.0.7

### AWX version

21.4.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.10.8

### Operating system

Ubuntu 22.04.1 LTS

### Web browser

Firefox, Chrome

### Steps to reproduce

Under Notification, add a Grafana Notification and leave the Fields ID of (dashboard, panel) empty. Hit the Test Button. 

### Expected results

Notification in Grafana

### Actual results

The State changed to Failed. The log contains the Error above.

**Comment by dmzoneill** [comment]
I've opened a primary pull request that needs refinement, but the errors described here will be fixed in that PR.

refer: https://github.com/ansible/awx/pull/14802
refer: https://github.com/ansible/awx/issues/14675

**Comment by mihai-satmarean** [comment]
I am trying to set grafana notifications, but since documentation here https://docs.ansible.com/ansible-tower/latest/html/userguide/notifications.html#grafana does not specify a type of object the tower sends, trace, log, metric whatever, and we have no example dashboard, I let the fields empty, thus hitting this bug. any hint is apreciated

**Comment by noesberger** [comment]
I also tried today the notification to grafana from ansible and have the same error. When I need to create a dashboard and panel before, do you have any example or documentation how they need to be configured in grafana.

**Comment by mateuszdrab** [comment]
Still not working for me, despite one of the fixes by @dmzoneill being merged.

Seems like the check for empty value is not working correctly as the value seems an empty string rather than null, and in second case, the value is expected to be an int, but dashboard ids can have alphanumeric characters and dashes I think.

```
awx-task ValueError: invalid literal for int() with base 10: ''
awx-task 2025-08-15 08:13:14,961 ERROR    [369b43254555452fbb5251df55910d90] awx.main.tasks.system Send Notification Failed invalid literal for int() with base 10: ''
awx-task Traceback (most recent call last):
awx-task   File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/tasks/system.py", line 350, in send_notifications
awx-task     sent = notification.notification_template.send(notification.subject, notification.body)
awx-task            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
awx-task   File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/models/notifications.py", line 185, in send
awx-task     backend_obj = self.notification_class(**notification_configuration)
awx-task                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
awx-task   File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/notifications/grafana_backend.py", line 56, in __init__
awx-task     self.dashboardId = int(dashboardId) if dashboardId is not None else None
awx-task                        ^^^^^^^^^^^^^^^^
awx-task ValueError: invalid literal for int() with base 10: ''
awx-task Task was destroyed but it is pending!
awx-task task: <Task pending name='Task-1070690' coro=<RedisConnection._read_data() done, defined at /var/lib/awx/venv/awx/lib64/python3.11/site-packages/aioredis/connection.py:180> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[RedisConnection.__init__.<locals>.<lambda>() at /var/lib/awx/venv/awx/lib64/python3.11/site-packages/aioredis/connection.py:168]>
awx-task 2025-08-15 08:14:22,208 ERROR    [351121d3e191459281b7c02802486ac7] awx.main.tasks.system Send Notification Failed invalid literal for int() with base 10: 'dTC0e9wZk'
awx-task Traceback (most recent call last):
awx-task   File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/tasks/system.py", line 350, in send_notifications
awx-task     sent = notification.notification_template.send(notification.subject, notification.body)
awx-task            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
awx-task   File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/models/notifications.py", line 185, in send
awx-task     backend_obj = self.notification_class(**notification_configuration)
awx-task                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
awx-task   File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/notifications/grafana_backend.py", line 56, in __init__
awx-task     self.dashboardId = int(dashboardId) if dashboardId is not None else None
awx-task                        ^^^^^^^^^^^^^^^^
awx-task ValueError: invalid literal for int() with base 10: 'dTC0e9wZk'
```

**Comment by dmzoneill** [comment]
Fixed in `awx/main/notifications/grafana_backend.py`.

**Root cause:** The `__init__` method stored `dashboardId` and `panelId` by wrapping them in `int()`, guarded only by a `!= ''` check. This left two bugs:

1. Passing `None` (the default) also passed the `!= ''` guard, causing `int(None)` → `TypeError`.
2. Grafana now issues string UIDs for dashboards (e.g. `'dTC0e9wZk'`), so any non-numeric dashboard ID triggered `int('dTC0e9wZk')` → `ValueError: invalid literal for int() with base 10: ''`.

**Fix:**

```python
# Before (buggy)
self.dashboardId = int(dashboardId) if dashboardId != '' else None
self.panelId = int(panelId) if panelId != '' else None

# After (fixed)
self.dashboardId = dashboardId if dashboardId else None   # stored as string; supports both legacy numeric IDs and new UID strings
self.panelId = int(panelId) if panelId else None          # still numeric per Grafana API; empty string and None both map to None
```

Both `None` and `''` now safely map to `None` for both fields. `dashboardId` is kept as a string (matching Grafana's current API which accepts both numeric IDs and UID strings). `panelId` is still converted to `int` since Grafana's annotation API expects a numeric panel ID.
