### ISSUE TITLE
Survey fields can't be updated on UI if created via the API

### ISSUE THREAD

**Issue by PB1899** [ansible/awx#12696]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Survey fields can't be updated on UI if created via the API
If a survey was created programmatically, the multiplechoice fields can't be edited (textarea fields can).

### AWX version

Ansible Automation Platform Controller 4.2.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Ansible version

2.12.1

### Operating system

RHEL 8

### Web browser

Firefox, Chrome

### Steps to reproduce

1. Create a survey for a workflow using the `awx.awx.tower_workflow_job_template` module.
2. Open the workflow job template on the UI, choose survey and edit any of the multiplechoice fields.

### Expected results

I am able to edit the survey field (in a similar fashion as it was possible in Ansible Tower).

### Actual results

Something went wrong...
There was an error loading this content. Please reload the page. [Back to Dashboard.](https://aap.corp.redhat.com/#/home)

Details:
```
TypeError: n.choices.split is not a function
    at E4 (https://aap.corp.redhat.com/static/js/main.b0175964.js:2:3176991)
    at oo (https://aap.corp.redhat.com/static/js/main.b0175964.js:2:1206935)
    at Ks (https://aap.corp.redhat.com/static/js/main.b0175964.js:2:1259235)
    at Ol (https://aap.corp.redhat.com/static/js/main.b0175964.js:2:1246476)
    at Tl (https://aap.corp.redhat.com/static/js/main.b0175964.js:2:1246404)
    at El (https://aap.corp.redhat.com/static/js/main.b0175964.js:2:1246267)
    at bl (https://aap.corp.redhat.com/static/js/main.b0175964.js:2:1243233)
    at https://aap.corp.redhat.com/static/js/main.b0175964.js:2:1192727
    at t.unstable_runWithPriority (https://aap.corp.redhat.com/static/js/main.b0175964.js:2:1418952)
    at Gi (https://aap.corp.redhat.com/static/js/main.b0175964.js:2:1192504)
```

**Comment by mabashian** [comment]
@PB1899  thanks for reporting this. I see you mentioned Controller/AAP. This bug tracker is for reporting issues in the open source AWX project, not Red Hat Ansible Controller/AAP. If you need help troubleshooting Controller/AAP, you should reach out to Red Hat support.

That being said - https://github.com/ansible/awx/pull/12038 should address this issue.
