### ISSUE TITLE
Worker failed to run task awx.main.scheduler.tasks.workflow_manager

### ISSUE THREAD

**Issue by Zokormazo** [ansible/awx#12710]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

workflow/slicing fails to run.

Job status is failed, with `Task was marked as running but was not present in the job queue, so it has been marked as failed.`

### AWX version

devel

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Steps to reproduce

Run a workflow or an sliced job

### Expected results

Workflow or sliced job ends succesfully

### Actual results

Workflow or sliced job fails

### Additional information

dispatcher.log:
```
2022-08-22 10:27:55,878 ERROR    [ae094ece0b4041bc8153c7ceb5c27753] awx.main.dispatch PID:49573 Worker failed to run task awx.main.scheduler.tasks.workflow_manager(*[], **{}
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/task.py", line 102, in perform_work
    result = self.run_callable(body)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/task.py", line 77, in run_callable
    return _call(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/tasks.py", line 35, in workflow_manager
    run_manager(WorkflowManager, "workflow")
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/tasks.py", line 20, in run_manager
    manager().schedule()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/task_manager.py", line 133, in schedule
    commit_start = time.time()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/transaction.py", line 290, in __exit__
    connection.set_autocommit(True)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py", line 420, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py", line 653, in run_and_clear_commit_hooks
    func()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/models/unified_jobs.py", line 1299, in <lambda>
    connection.on_commit(lambda: self._websocket_emit_status(status))
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/models/unified_jobs.py", line 1292, in _websocket_emit_status
    if self.workflow_job:
AttributeError: 'Job' object has no attribute 'workflow_job'
```

**Comment by AlanCoding** [comment]
this should be resolved by https://github.com/ansible/awx/pull/12706
