### ISSUE TITLE
Openstack inventory using custom CACERT

### ISSUE THREAD

**Issue by jobcespedes** [ansible/awx#1273]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
Error syncing inventory with openstack

##### ENVIRONMENT
* AWX version: 1.0.3.55
* AWX install method: docker-compose on linux
* Ansible version:  2.4.3.0 
* Operating System: Ubuntu 16.04.3
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Use an SSL endpoint

##### EXPECTED RESULTS

Import instances to inventory

##### ACTUAL RESULTS
```

2018-02-16 05:02:06,680 INFO     awx.main.commands.inventory_import Updating inventory 2: devstack
2018-02-16 05:02:06,692 INFO     awx.main.commands.inventory_import Reading Ansible inventory source: /usr/lib/python2.7/site-packages/awx/plugins/inventory/openstack.py
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==1.0.3.55', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 991, in handle
    self.is_custom)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 242, in load_inventory_source
    is_custom=is_custom).load()
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 177, in load
    data = self.command_to_json(base_args + ['--list'])
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 160, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=4) with stdout:

stderr:
ERROR! Could not parse inventory source /usr/lib/python2.7/site-packages/awx/plugins/inventory/openstack.py with available plugins:
Plugin script failed: Inventory script (/usr/lib/python2.7/site-packages/awx/plugins/inventory/openstack.py) had an execution error: Error fetching server list on devstack::

 
Plugin ini failed: /usr/lib/python2.7/site-packages/awx/plugins/inventory/openstack.py:48: Expected key=value host variable assignment, got: argparse
```

##### ADDITIONAL INFORMATION

I also tried to use "Source variables":
```
---
clouds:
  devstack:
    cacert: /etc/pki/ca-trust/source/anchors/overcloud-cacert-mo.crt
    verify: false
    auth:
      auth_url: https://172.16.128.10:13000/v2.0
      username: user
      password: mi_pass
      project_name: project
```

**Comment by matburt** [comment]
Would be helpful to know what the config file we generated at sync-time looked like. Otherwise we'll have to circle back to this when we get to it.

**Comment by jobcespedes** [comment]
Hello,
Using the following in "Source variables":
```
---
use_hostnames: True
clouds:
  devstack:
    cacert: /etc/pki/ca-trust/source/anchors/overcloud-cacert-mo.crt
    verify: false
    auth:
      auth_url: https://172.16.128.10:13000/v2.0
      username: user
      password: 'mi_pass'
      project_name: project
```
The generated config file in /tmp looks like:
```
ansible:
  expand_hostvars: false
  fail_on_errors: true
  use_hostnames: true
cache:
  path: /tmp/awx_47_bEDift/openstack_cachewgoBvJ
clouds:
  devstack:
    auth:
      auth_url: https://172.16.128.10:13000/v2.0
      password: 'mi_pass'
      project_name: project
      username: user
    private: true

```

**Comment by chrismeyersfsu** [comment]
@jobcespedes can you try to recreate with ansible on the command-line?

**Comment by jobcespedes** [comment]
@chrismeyersfsu I'm not sure how to recreate it on cli, sorry.

**Comment by chrismeyersfsu** [comment]
https://github.com/ansible/ansible/blob/devel/contrib/inventory/openstack.py

create an `openstack.yml` and fill it with the content that you pasted above. Put that file in the same directory as `openstack.py`

Run:
`ansible-inventory -i openstack.py`

**Comment by jobcespedes** [comment]
Files in place and `ansible-inventory -i openstack.py --list`:
```
[WARNING]:  * Failed to parse /usr/lib/python2.7/site-packages/awx/plugins/inventory/openstack.py with script plugin: Inventory script
(/usr/lib/python2.7/site-packages/awx/plugins/inventory/openstack.py) had an execution error: Traceback (most recent call last):   File
"/usr/lib/python2.7/site-packages/awx/plugins/inventory/openstack.py", line 246, in <module>     main()   File "/usr/lib/python2.7/site-
packages/awx/plugins/inventory/openstack.py", line 232, in main     inventory = shade.inventory.OpenStackInventory(**inventory_args)   File
"/usr/lib/python2.7/site-packages/shade/inventory.py", line 42, in __init__     for cloud_config in config.get_all_clouds()   File
"/usr/lib/python2.7/site-packages/os_client_config/config.py", line 815, in get_all_clouds     cloud, region_name=region['name']))   File
"/usr/lib/python2.7/site-packages/os_client_config/config.py", line 1088, in get_one_cloud     auth_plugin =
loader.load_from_options(**config['auth'])   File "/usr/lib/python2.7/site-packages/keystoneauth1/loading/base.py", line 162, in
load_from_options     raise exceptions.MissingRequiredOptions(missing_required)
keystoneauth1.exceptions.auth_plugins.MissingRequiredOptions: Auth plugin requires parameters which were not given: auth_url

 [WARNING]:  * Failed to parse /usr/lib/python2.7/site-packages/awx/plugins/inventory/openstack.py with ini plugin: /usr/lib/python2.7
/site-packages/awx/plugins/inventory/openstack.py:48: Expected key=value host variable assignment, got: argparse

 [WARNING]: Unable to parse /usr/lib/python2.7/site-packages/awx/plugins/inventory/openstack.py as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

{
    "_meta": {
        "hostvars": {}
    }, 
    "all": {
        "children": [
            "ungrouped"
        ]
    }, 
    "ungrouped": {}
}
```

**Comment by chrismeyersfsu** [comment]
Let's remove `ansible-inventory` from the picture for now.

Also, I told you wrong. Openstack no longer looks for `openstack.yml` in the current directory. Instead, we have to tell openstack where the yml file is exactly (this is how tower works too).

`OS_CLIENT_CONFIG_FILE=openstack.yml openstack.py --list`

I noticed a long hang on this command when the remote host specified via `auth_url` isn't accessible. You can ctrl+c if you see this long hang and the traceback will indicate it trying to connect to the server.

My guess is that you will see this long hang and that your openstack server isn't accessible from the tower server. You can verify by using `nc` or `telnet` to try and connect to the openstack API server from the tower instance.

**Comment by jobcespedes** [comment]
This is the output for `OS_CLIENT_CONFIG_FILE=openstack.yml ./openstack.py --list`

```
Traceback (most recent call last):
  File "./openstack.py", line 246, in <module>
    main()
  File "./openstack.py", line 235, in main
    output = get_host_groups(inventory, refresh=args.refresh)
  File "./openstack.py", line 114, in get_host_groups
    groups = to_json(get_host_groups_from_cloud(inventory))
  File "./openstack.py", line 143, in get_host_groups_from_cloud
    for server in inventory.list_hosts(**list_args):
  File "/usr/lib/python2.7/site-packages/shade/inventory.py", line 68, in list_hosts
    for server in cloud.list_servers(detailed=expand):
  File "/usr/lib/python2.7/site-packages/shade/openstackcloud.py", line 2180, in list_servers
    filters=filters)
  File "/usr/lib/python2.7/site-packages/shade/openstackcloud.py", line 2196, in _list_servers
    '/servers/detail', params=params, error_message=error_msg)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 304, in get
    return self.request(url, 'GET', **kwargs)
  File "/usr/lib/python2.7/site-packages/shade/_adapter.py", line 154, in request
    response = self.manager.submit_task(RequestTask(**kwargs))
  File "/usr/lib/python2.7/site-packages/shade/task_manager.py", line 259, in submit_task
    return self.run_task(task=task, raw=raw)
  File "/usr/lib/python2.7/site-packages/shade/task_manager.py", line 270, in run_task
    return self._run_task(task, raw=raw)
  File "/usr/lib/python2.7/site-packages/shade/task_manager.py", line 284, in _run_task
    return task.wait(raw)
  File "/usr/lib/python2.7/site-packages/shade/task_manager.py", line 98, in wait
    self._traceback)
  File "/usr/lib/python2.7/site-packages/shade/task_manager.py", line 109, in run
    self.done(self.main(client))
  File "/usr/lib/python2.7/site-packages/shade/_adapter.py", line 152, in main
    return request_method(**self.args)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 189, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 573, in request
    auth_headers = self.get_auth_headers(auth)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 900, in get_auth_headers
    return auth.get_headers(self, **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/plugin.py", line 95, in get_headers
    token = self.get_token(session)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 88, in get_token
    return self.get_access(session).auth_token
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 134, in get_access
    self.auth_ref = self.get_auth_ref(session)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/generic/base.py", line 201, in get_auth_ref
    return self._plugin.get_auth_ref(session, **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/v2.py", line 63, in get_auth_ref
    authenticated=False, log=False)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 848, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 698, in request
    resp = send(**kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 760, in _send_request
    raise exceptions.SSLError(msg)
keystoneauth1.exceptions.connection.SSLError: SSL exception connecting to https://172.16.128.10:13000/v2.0/tokens: HTTPSConnectionPool(host='172.16.128.10', port=13000): Max retries exceeded with url: /v2.0/tokens (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),))
```

**Comment by jobcespedes** [comment]
If I add cacert: 'path/to/cacert' to the openstack.yml and run the same command, it runs without problems. The issue could be why isn't the varible 'cacert' pass from gui to the tmp file

**Comment by chrismeyersfsu** [comment]
@jobcespedes the problem may be that the file referenced isn't accessible in the runtime environment because bubblewrap is "blocking" it. Try exposing that ssl directory or disable bubblewrap/proot https://docs.ansible.com/ansible-tower/3.1.3/html/administration/proot_func_variables.html

Let me know if it works!

**Comment by jobcespedes** [comment]
@chrismeyersfsu Do you think bubblewrap is the reason cacert variable is not written to the temporary openstack.yml? 
Please look again at my "Source variables" and then to the respective temporal openstack.yml file ansible used. Even tough I set a cacert variable in "Source Variable", there is no cacert variable in the respective temporal openstack.yml file

### "Source variables"
```
---
clouds:
  devstack:
    cacert: /etc/pki/ca-trust/source/anchors/overcloud-cacert-mo.crt     # <------ CACERT is present
    verify: false
    auth:
      auth_url: https://172.16.128.10:13000/v2.0
      username: user
      password: mi_pass
      project_name: project
```
### openstack.yml
```
ansible:
  expand_hostvars: false
  fail_on_errors: true
  use_hostnames: true
cache:
  path: /tmp/awx_47_bEDift/openstack_cachewgoBvJ
clouds:
  devstack:   #################################### <------ CACERT is not present
    auth:
      auth_url: https://172.16.128.10:13000/v2.0
      password: 'mi_pass'
      project_name: project
      username: user
    private: true
```

**Comment by wenottingham** [comment]
I think you should be able to use https://github.com/ansible/awx/pull/1552 to solve this instead. Let us know if that doesn't work for you.

**Comment by xdfil** [comment]
Is there any solution recommended for an OpenShift deployment?

To fix the issue manually will require updating the CA Trust inside the container, and also iirc set an environment variable for python CA path.

Can you folks provide a play in the installer that will add these things to the images?
