### ISSUE TITLE
Browser console error when navigating to schedule for some management jobs

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#12811]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Some management jobs have a schedule that I can edit in the UI. For example "Cleanup Activity Stream" has the schedule "Cleanup Activity Schedule", and based on my preferences, I can change its frequency in the UI.

This is not working for the schedules for some management jobs, instead getting a console error in the UI.

### AWX version

devel

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

N/A

### Operating system

N/A

### Web browser

Chrome

### Steps to reproduce

Go to the management jobs

![Screenshot from 2022-09-01 09-43-08](https://user-images.githubusercontent.com/1385596/187929828-f64887c7-c769-4ca9-aea1-44cc9fec91da.png)

Now navigate to the "Cleanup Expired OAuth 2 Tokens" job

![Screenshot from 2022-09-01 09-43-15](https://user-images.githubusercontent.com/1385596/187930158-516ab028-faa7-454b-8a60-0d56e27d75a0.png)

Now click on the schedule.

![Screenshot from 2022-09-01 09-43-28](https://user-images.githubusercontent.com/1385596/187929935-2391b2bb-f47a-4a11-8c4f-c36222e70cc1.png)

### Expected results

I expect to be able to modify this the same as the cleanup activity stream schedule.

### Actual results

Cannot do this in the UI.

### Additional information

This also affects "Cleanup Expired Sessions"

Console error:

```
index.js:9 I18nProvider did not render. A call to i18n.activate still needs to happen or forceRenderOnLocaleChange must be set to false.
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'sort')
    at W6 (FrequencyDetails.js:89:16)
    at oo (react-dom.production.min.js:157:137)
    at Ks (react-dom.production.min.js:267:460)
    at Al (react-dom.production.min.js:250:347)
    at Tl (react-dom.production.min.js:250:278)
    at El (react-dom.production.min.js:250:138)
    at yl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Vi (react-dom.production.min.js:122:325)
us @ react-dom.production.min.js:216
n.payload @ react-dom.production.min.js:217
pa @ react-dom.production.min.js:130
Go @ react-dom.production.min.js:184
Ks @ react-dom.production.min.js:269
Al @ react-dom.production.min.js:250
Tl @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
yl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vi @ react-dom.production.min.js:122
Yi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
fl @ react-dom.production.min.js:237
Io @ react-dom.production.min.js:170
(anonymous) @ useRequest.js:44
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
An @ asyncToGenerator.js:3
o @ asyncToGenerator.js:25
Promise.then (async)
An @ asyncToGenerator.js:13
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Schedule.js:50
Fl @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vi @ react-dom.production.min.js:122
Dl @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
M @ scheduler.production.min.js:16
_.port1.onmessage @ scheduler.production.min.js:12
```

**Comment by AlanCoding** [comment]
This is the issue I mentioned when reviewing @matburt patch https://github.com/ansible/awx/pull/12803

It seems unlikely that users mucked with those schedules, since it's not really possible to do so in the UI.

**Comment by bschaeffer** [comment]
@AlanCoding It is possible with the API though possibly https://docs.ansible.com/ansible/latest/collections/awx/awx/schedule_module.html

**Comment by anbi-x5** [comment]
Any news on a solution to this problem?
I'm getting the same errors
```
TypeError: Cannot read properties of undefined (reading 'sort')
    at E9 (http://127.0.0.1:81/static/js/main.f71c4091.js:2:2488165)
    at oo (http://127.0.0.1:81/static/js/main.f71c4091.js:2:850659)
    at Ks (http://127.0.0.1:81/static/js/main.f71c4091.js:2:902959)
    at Al (http://127.0.0.1:81/static/js/main.f71c4091.js:2:890200)
    at Tl (http://127.0.0.1:81/static/js/main.f71c4091.js:2:890128)
    at El (http://127.0.0.1:81/static/js/main.f71c4091.js:2:889991)
    at yl (http://127.0.0.1:81/static/js/main.f71c4091.js:2:886957)
    at http://127.0.0.1:81/static/js/main.f71c4091.js:2:836451
    at t.unstable_runWithPriority (http://127.0.0.1:81/static/js/main.f71c4091.js:2:932713)
    at Vi (http://127.0.0.1:81/static/js/main.f71c4091.js:2:836228)
```
 in the UI in the schedulers:
- Cleanup Expired OAuth 2 Tokens;
- Cleanup Expired Sessions.

On a fresh installation of AWX 21.10.2

**Comment by anbi-x5** [comment]
On a fresh installation of AWX 21.10.2 installation, the following schedulers:
- Clean up Expired Sessions;
- Cleanup Expired OAuth 2 Tokens,

in the _"main_shedule"_ table in the _"rrule"_ column have values:
DTSTART:YYYYMMDDTHHMMSSZ RRULE:FREQ=WEEKLY;INTERVAL=1
DTSTART:YYYYMMDDTHHMMSSZ RRULE:FREQ=WEEKLY;INTERVAL=1

I fixed it like this:
DTSTART:YYYYMMDDTHHMMSSZ RRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=SU
DTSTART:YYYYMMDDTHHMMSSZ RRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=SU

the problem goes away and the schedulers are available in the UI to view/edit and save changes.

**Comment by AlanCoding** [comment]
Thanks for the info. @mabashian it would be good to see if we can get this fixed, because in a major release or two I do have ideas to add more management jobs.

**Comment by laiminhtrung1997** [comment]
Dear @AlanCoding , I have implemented it like this comment.

> On a fresh installation of AWX 21.10.2 installation, the following schedulers:
> 
> * Clean up Expired Sessions;
> * Cleanup Expired OAuth 2 Tokens,
> 
> in the _"main_shedule"_ table in the _"rrule"_ column have values: DTSTART:YYYYMMDDTHHMMSSZ RRULE:FREQ=WEEKLY;INTERVAL=1 DTSTART:YYYYMMDDTHHMMSSZ RRULE:FREQ=WEEKLY;INTERVAL=1
> 
> I fixed it like this: DTSTART:YYYYMMDDTHHMMSSZ RRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=SU DTSTART:YYYYMMDDTHHMMSSZ RRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=SU
> 
> the problem goes away and the schedulers are available in the UI to view/edit and save changes.

It still gives error though, but with different message in console. And this error occur after and before this fix.
Version I used is 22.3.0.
![image](https://github.com/ansible/awx/assets/68812829/1e400d44-d3c0-452e-9b54-0b3fe1f67d7a)
