### ISSUE TITLE
EE runner's inventory sync failed to parse because module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

### ISSUE THREAD

**Issue by Uquout7o** [ansible/awx#12843]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Exact same problem as in issues #12124 and #12117
- occurs since todays changes to the default awx-ee, see https://quay.io/repository/ansible/awx-ee?tab=history

### AWX version

20.1.0

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [x] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

core 2.12.5.post0

### Operating system

20.04.4 LTS

### Steps to reproduce

Running any task with inventory sync results in this error.

### Expected results

Until today, this was the result:
```
ansible-inventory [core 2.12.5.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.11.3
  libyaml = True
No config file found; using defaults
redirecting (type: inventory) ansible.builtin.vmware_vm_inventory to community.vmware.vmware_vm_inventory
Parsed /runner/inventory/vmware_vm_inventory.yml inventory source with auto plugin
   22.355 INFO     Processing JSON output...
   22.639 INFO     Loaded 27 groups, 257 hosts
   23.656 INFO     Inventory import completed for vc-emea in 1.3s
```

### Actual results

Since todays changes to the awx-ee image, I get the following error:
```
[WARNING]:  * Failed to parse /runner/inventory/vmware_vm_inventory.yml with
auto plugin: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
  File "/usr/local/lib/python3.8/site-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/inventory/auto.py", line 50, in parse
    plugin = inventory_loader.get(plugin_name)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/loader.py", line 807, in get
    return self.get_with_context(name, *args, **kwargs).object
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/loader.py", line 827, in get_with_context
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/loader.py", line 791, in _load_module_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/ansible/collections/ansible_collections/community/vmware/plugins/inventory/vmware_vm_inventory.py", line 368, in <module>
    from ansible_collections.community.vmware.plugins.plugin_utils.inventory import (
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/usr/local/lib/python3.8/site-packages/ansible/utils/collection_loader/_collection_finder.py", line 402, in load_module
    exec(code_obj, module.__dict__)
  File "/usr/share/ansible/collections/ansible_collections/community/vmware/plugins/plugin_utils/inventory.py", line 35, in <module>
    from vmware.vapi.vsphere.client import create_vsphere_client
  File "/usr/local/lib/python3.8/site-packages/vmware/vapi/vsphere/client.py", line 13, in <module>
    from vmware.vapi.lib.connect import get_requests_connector
  File "/usr/local/lib/python3.8/site-packages/vmware/vapi/lib/connect.py", line 11, in <module>
    from vmware.vapi.lib.ssl import UnverifiedClientContextFactory
  File "/usr/local/lib/python3.8/site-packages/vmware/vapi/lib/ssl.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 1517, in <module>
    class X509StoreFlags(object):
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 1537, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
[WARNING]: Unable to parse /runner/inventory/vmware_vm_inventory.yml as an
inventory source
ERROR! No inventory was parsed, please check your configuration and options.
```

### Additional information

Are there any other tags than _latest_ to use when using the awx-ee image? I couldn't find a _stable_ tag, for example.

**Comment by thedatabaseme** [comment]
Same issue starting as of today for me. It's probably an EE issue that is tracked here: https://github.com/ansible/awx-ee/issues/134

**Comment by Miggel75** [comment]
I have been able to solve this issue by downgrading the **cryptography** package in awx-ee to **37.0.2**.
I am using the docker-compose base installed awx and have performed the following as a workaround until the awx-ee image is fixed.
I really hope that the awx-ee images on quay will be tagged soon.

### In the tools_awx_1 container
```
bash-5.1# podman images
REPOSITORY              TAG         IMAGE ID      CREATED       SIZE
quay.io/ansible/awx-ee  latest      3bb951b4e1db  11 hours ago  1.9 GB
bash-5.1# podman run -it --user=0 3bb951b4e1db bash
bash-4.4# ansible-galaxy collection install community.general
ERROR! Unexpected Exception, this is probably a bug: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 97, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/local/lib/python3.8/site-packages/ansible/cli/galaxy.py", line 24, in <module>
    from ansible.galaxy.api import GalaxyAPI
  File "/usr/local/lib/python3.8/site-packages/ansible/galaxy/api.py", line 28, in <module>
    from ansible.module_utils.urls import open_url, prepare_multipart
  File "/usr/local/lib/python3.8/site-packages/ansible/module_utils/urls.py", line 115, in <module>
    from urllib3.contrib.pyopenssl import PyOpenSSLContext
  File "/usr/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 1517, in <module>
    class X509StoreFlags(object):
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 1537, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
bash-4.4# pip install cryptography==37.0.2
Collecting cryptography==37.0.2
  Downloading cryptography-37.0.2-cp36-abi3-manylinux_2_24_x86_64.whl (4.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 36.5 MB/s eta 0:00:00
Requirement already satisfied: cffi>=1.12 in /usr/lib64/python3.8/site-packages (from cryptography==37.0.2) (1.13.2)
Requirement already satisfied: pycparser in /usr/lib/python3.8/site-packages (from cffi>=1.12->cryptography==37.0.2) (2.19)
Installing collected packages: cryptography
  Attempting uninstall: cryptography
    Found existing installation: cryptography 38.0.0
    Uninstalling cryptography-38.0.0:
      Successfully uninstalled cryptography-38.0.0
Successfully installed cryptography-37.0.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 22.0.4; however, version 22.2.2 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
bash-4.4# ansible-galaxy collection install community.general
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/download/community-general-5.5.0.tar.gz to /home/runner/.ansible/tmp/ansible-local-21iokjdcw0/tmp_xsebmme/community-general-5.5.0-os0u203x
Installing 'community.general:5.5.0' to '/home/runner/.ansible/collections/ansible_collections/community/general'
community.general:5.5.0 was installed successfully
bash-4.4#
```
### Then in another session to the tools_awx_1 container
```
bash-5.1# podman images
REPOSITORY              TAG         IMAGE ID      CREATED       SIZE
quay.io/ansible/awx-ee  latest      3bb951b4e1db  12 hours ago  1.9 GB
bash-5.1# podman ps
CONTAINER ID  IMAGE                          COMMAND     CREATED        STATUS            PORTS       NAMES
30cb9494a600  quay.io/ansible/awx-ee:latest  bash        3 minutes ago  Up 3 minutes ago              romantic_jang
bash-5.1# podman commit 30cb9494a600 quay.io/ansible/awx-ee
Getting image source signatures
Copying blob 101e6c349551 skipped: already exists
Copying blob aadc47c09f66 skipped: already exists
Copying blob e0808177f5c4 skipped: already exists
Copying blob 5fa5c1c78a8e skipped: already exists
Copying blob 6da2fb060681 skipped: already exists
Copying blob 699491b2659e skipped: already exists
Copying blob f8fd3a54d485 skipped: already exists
Copying blob d4df4b7e8eaf skipped: already exists
Copying blob 32ad5db2dab5 skipped: already exists
Copying blob 7dfd83b5170b skipped: already exists
Copying blob aa621dba5e87 skipped: already exists
Copying blob d32c18715b98 skipped: already exists
Copying blob a39c6baf08b1 skipped: already exists
Copying blob 1d211ae75d27 skipped: already exists
Copying blob 22e51cce938f skipped: already exists
Copying blob 869dbc4797e2 skipped: already exists
Copying blob 2d4417eff75b skipped: already exists
Copying blob 5fc9189ff6da skipped: already exists
Copying blob 607274fb27bb skipped: already exists
Copying blob b36bd1c866e9 skipped: already exists
Copying blob 41c3c29b2fd4 skipped: already exists
Copying blob 17f106b998da skipped: already exists
Copying blob 4de68c6ba76d skipped: already exists
Copying blob 1febd754181d skipped: already exists
Copying blob 9890bf214489 skipped: already exists
Copying blob ab6704b460d1 done
Copying config 31b86a2217 done
Writing manifest to image destination
Storing signatures
31b86a22177f45eb557f9b2bd30a91c1a004af1d6d44b6302cc0696ac3d11593
bash-5.1# podman images
REPOSITORY              TAG         IMAGE ID      CREATED             SIZE
quay.io/ansible/awx-ee  latest      31b86a22177f  About a minute ago  1.94 GB
bash-5.1#
```

**Comment by leetecarey** [comment]
Same Issue here 21.5.0

**Comment by Uquout7o** [comment]
As a workaround, now using novumrgi/awx-ee:stable as luhahn provided in issue #134 , had to configure it via the webGUI

**Comment by amirm-hrl** [comment]
I can confirm this also effect the project updates (from git source) on both v21.0.0 and v21.5.0 

```json
  "stdout_lines": [
    "the full traceback was:",
    "",
    "Traceback (most recent call last):",
    "  File \"/usr/local/bin/ansible-galaxy\", line 97, in <module>",
    "    mycli = getattr(__import__(\"ansible.cli.%s\" % sub, fromlist=[myclass]), myclass)",
    "  File \"/usr/local/lib/python3.8/site-packages/ansible/cli/galaxy.py\", line 24, in <module>",
    "    from ansible.galaxy.api import GalaxyAPI",
    "  File \"/usr/local/lib/python3.8/site-packages/ansible/galaxy/api.py\", line 28, in <module>",
    "    from ansible.module_utils.urls import open_url, prepare_multipart",
    "  File \"/usr/local/lib/python3.8/site-packages/ansible/module_utils/urls.py\", line 115, in <module>",
    "    from urllib3.contrib.pyopenssl import PyOpenSSLContext",
    "  File \"/usr/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py\", line 46, in <module>",
    "    import OpenSSL.SSL",
    "  File \"/usr/local/lib/python3.8/site-packages/OpenSSL/__init__.py\", line 8, in <module>",
    "    from OpenSSL import crypto, SSL",
    "  File \"/usr/local/lib/python3.8/site-packages/OpenSSL/crypto.py\", line 1517, in <module>",
    "    class X509StoreFlags(object):",
    "  File \"/usr/local/lib/python3.8/site-packages/OpenSSL/crypto.py\", line 1537, in X509StoreFlags",
    "    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK",
    "AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'"
  ],
  "stderr_lines": [
    "ERROR! Unexpected Exception, this is probably a bug: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'"
  ],
```

**Comment by fosterseth** [comment]
hi folks, the latest awx-ee image should now pin cryptography to 37.0.4 https://github.com/ansible/awx-ee/pull/136

Please retry with the latest image!

**Comment by deeco** [comment]
checking

**Comment by deeco** [comment]
@fosterseth  How to set the AlwaysPullPolicy for ee image using Kustomize ? see in logs says already present on host so not pulling the latest from quay.io

https://github.com/ansible/awx-operator#user-content-basic-install

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=<tag>

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: <tag>
- name: quay.io/ansible/awx-ee
    newTag: latest

# Specify a custom namespace in which to install AWX
namespace: awx

```

**Comment by deeco** [comment]
confirmed working with latest image, had to remove on host level to force it, is it possible to set to AlwaysPull ?

**Comment by dulanjanad** [comment]
> confirmed working with latest image, had to remove on host level to force it, is it possible to set to AlwaysPull ?
 
@deeco can you please elaborate on how you manage to fix this issue, wa are having the same issue on AWX. we have deployed AWX on K8S
