### ISSUE TITLE
DB Migration Failing

### ISSUE THREAD

**Issue by Yoiro** [ansible/awx#1300]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY
I wanted to upgrade to version 1.0.3 while changing the location of my DB by moving it to another server.

##### ENVIRONMENT
* AWX version: 1.0.3.57
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: RHEL7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Do a git pull and live re-run install.yml by specifying another DB than the one used by the application

##### EXPECTED RESULTS

The application updates and I keep the old data.

##### ACTUAL RESULTS

awx_task container is endlessly "upgrading" (as told by the UI).

##### ADDITIONAL INFORMATION

I also tried to clean the DB that is on the server after dumping it, ran install.yml, et tried to live-update the DB, but I run into the same problem.

When I run the install.yml with an already migrated database I get this error in awx_task logs:

```
[2018-02-20 08:49:15,903: ERROR/MainProcess] Signal handler <function handle_ha_toplogy_worker_ready at 0x4e76c08> raised: ProgrammingError('column main_instance.capacity_adjustment does not exist\nLINE 1: ..._instance"."version", "main_instance"."capacity", "main_inst...\n                                                             ^\n',)
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 227, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 223, in handle_ha_toplogy_worker_ready
    instances, removed_queues, added_queues = register_celery_worker_queues(sender.app, sender.hostname)
  File "/usr/lib/python2.7/site-packages/awx/main/utils/ha.py", line 62, in register_celery_worker_queues
    instance = Instance.objects.me()
  File "/usr/lib/python2.7/site-packages/awx/main/managers.py", line 86, in me
    return node[0]
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 289, in __getitem__
    return list(qs)[0]
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception
ProgrammingError: column main_instance.capacity_adjustment does not exist
LINE 1: ..._instance"."version", "main_instance"."capacity", "main_inst...
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 227, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 223, in handle_ha_toplogy_worker_ready
    instances, removed_queues, added_queues = register_celery_worker_queues(sender.app, sender.hostname)
  File "/usr/lib/python2.7/site-packages/awx/main/utils/ha.py", line 62, in register_celery_worker_queues
    instance = Instance.objects.me()
  File "/usr/lib/python2.7/site-packages/awx/main/managers.py", line 86, in me
    return node[0]
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 289, in __getitem__
    return list(qs)[0]
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception
ProgrammingError: column main_instance.capacity_adjustment does not exist
LINE 1: ..._instance"."version", "main_instance"."capacity", "main_inst...
```

**Comment by matburt** [comment]
What version are you upgrading from?

**Comment by Yoiro** [comment]
I was working with a 1.0.2 before.
I avoided the problem by using a fresh new database as there was not much records in the old one so it wasn't really a problem to redo the work.

**Comment by matburt** [comment]
1.0.2 -> 1.0.3.1+ is not supported

**Comment by Yoiro** [comment]
Thanks for the answer.
