### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable when linking a workflow_job_template from another workflow_job_template

### ISSUE THREAD

**Issue by eschaarschmidt** [ansible/awx#13047]
##### ISSUE TYPE
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME
 - Collection

##### SUMMARY

We are using the awx ansible collection to create workflow templates in awx.
We want to trigger anouther workflow inside a awx.awx.workflow_job_template.
For this to be functional, we add 

```
  - name: name
    awx.awx.workflow_job_template_node:
      identifier: "id-node"
      workflow_job_template: "job_template_name"  
      organization: Default
      unified_job_template: "job_template to trigger"
```

and then link it with:

  - name: name
    awx.awx.workflow_job_template_node:
      identifier: "id-of-node-before"
      workflow_job_template: "job_template_mane"
      organization: Default
      success_nodes:
        - "id-node"

The execution of this play seems to work, but it creates this error:

```
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1665573975.051087-1110-152503674402077/AnsiballZ_workflow_job_template_node.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1665573975.051087-1110-152503674402077/AnsiballZ_workflow_job_template_node.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1665573975.051087-1110-152503674402077/AnsiballZ_workflow_job_template_node.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.awx.awx.plugins.modules.workflow_job_template_node', init_globals=dict(_module_fqn='ansible_collections.awx.awx.plugins.modules.workflow_job_template_node', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_awx.awx.workflow_job_template_node_payload_rqego7hx/ansible_awx.awx.workflow_job_template_node_payload.zip/ansible_collections/awx/awx/plugins/modules/workflow_job_template_node.py", line 403, in <module>
  File "/tmp/ansible_awx.awx.workflow_job_template_node_payload_rqego7hx/ansible_awx.awx.workflow_job_template_node_payload.zip/ansible_collections/awx/awx/plugins/modules/workflow_job_template_node.py", line 313, in main
TypeError: 'NoneType' object is not subscriptable
fatal: [localhost]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-tmp-1665573975.051087-1110-152503674402077/AnsiballZ_workflow_job_template_node.py", line 107, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-tmp-1665573975.051087-1110-152503674402077/AnsiballZ_workflow_job_template_node.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-tmp-1665573975.051087-1110-152503674402077/AnsiballZ_workflow_job_template_node.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.awx.awx.plugins.modules.workflow_job_template_node', init_globals=dict(_module_fqn='ansible_collections.awx.awx.plugins.modules.workflow_job_template_node', _modlib_path=modlib_path),
      File "/usr/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_awx.awx.workflow_job_template_node_payload_rqego7hx/ansible_awx.awx.workflow_job_template_node_payload.zip/ansible_collections/awx/awx/plugins/modules/workflow_job_template_node.py", line 403, in <module>
      File "/tmp/ansible_awx.awx.workflow_job_template_node_payload_rqego7hx/ansible_awx.awx.workflow_job_template_node_payload.zip/ansible_collections/awx/awx/plugins/modules/workflow_job_template_node.py", line 313, in main
    TypeError: 'NoneType' object is not subscriptable
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

##### ENVIRONMENT
* AWX version: 21.5.0
* AWX install method: developer environment
* AWX deployment target: kubernetes
* Operating System: Ubuntu in WSL2 on Windows
* Web Browser:

##### STEPS TO REPRODUCE

Create workflow_job_template 1 with multiple workflow_job_template_nodes
Create workflow_job_template 2 with multiple workflow_job_template_nodes
Create an workflow_job_template_node in workflow_job_template 2 to execute workflow_job_template 1

##### EXPECTED RESULTS

The workflow template node referencing another workflow template is created without error

##### ACTUAL RESULTS

The workflow template node referencing another workflow template is created with the error described above

**Comment by sarabrajsingh** [comment]
hi @eschaarschmidt,

are you able to reproduce this error from within the application itself? we are trying to figure out if this potential bug is actually in `awx` or within `awx.collections`.

thanks,

AWX Team

**Comment by AMC-7** [comment]
For me, this error occurred when I was referencing the wrong name of the job template. Seems you're potentially doing the same with `job_template_mane`?

**Comment by akus062381** [comment]
Hi @eschaarschmidt,

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
