### ISSUE TITLE
Job template launch through AWX CLI is giving error - argparse.ArgumentError: argument --timeout: conflicting option string: --timeout

### ISSUE THREAD

**Issue by outjoker** [ansible/awx#13086]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Launching AWX job is giving an error using AWX CLI 
here is the error snippet 

```
awx job_templates launch '<jobname>' -v

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 18.217.0.125:8043

DEBUG:urllib3.connectionpool:https://18.217.0.125:8043 "GET /api/ HTTP/1.1" 200 186

DEBUG:awxkit.api.client:"GET https://18.217.0.125:8043/api/" elapsed: 0:00:00.062448

DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.api.ApiV2'> by url: /api/v2/

DEBUG:urllib3.connectionpool:https://18.217.0.125:8043 "GET /api/v2/ HTTP/1.1" 200 1708

DEBUG:awxkit.api.client:"GET https://18.217.0.125:8043/api/v2/" elapsed: 0:00:00.060663

DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.job_templates.JobTemplates'> by url: /api/v2/job_templates/

DEBUG:urllib3.connectionpool:https://18.217.0.125:8043 "OPTIONS /api/v2/job_templates/ HTTP/1.1" 200 25550

DEBUG:awxkit.api.client:"OPTIONS https://18.217.0.125:8043/api/v2/job_templates/" elapsed: 0:00:00.208581

DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.job_templates.JobTemplates'> by url: /api/v2/job_templates/

DEBUG:urllib3.connectionpool:https://18.217.0.125:8043 "OPTIONS /api/v2/job_templates/1/ HTTP/1.1" 200 13963

DEBUG:awxkit.api.client:"OPTIONS https://18.217.0.125:8043/api/v2/job_templates/1/" elapsed: 0:00:00.167353

DEBUG:urllib3.connectionpool:https://18.217.0.125:8043 "OPTIONS /api/v2/job_templates/1/launch/ HTTP/1.1" 200 7084

DEBUG:awxkit.api.client:"OPTIONS https://18.217.0.125:8043/api/v2/job_templates/1/launch/" elapsed: 0:00:00.108663

Traceback (most recent call last):

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/__init__.py", line 25, in run

    cli.parse_resource()

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/client.py", line 168, in parse_resource

    response = self.parse_action(resource)

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/client.py", line 229, in parse_action

    parser = ResourceOptionsParser(self.v2, page, self.resource, subparsers)

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/options.py", line 103, in __init__

    self.handle_custom_actions()

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/options.py", line 286, in handle_custom_actions

    action(self.page).add_arguments(self.parser, self)

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/custom.py", line 78, in add_arguments

    resource_options_parser.build_query_arguments(self.action, 'LAUNCH')

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/options.py", line 277, in build_query_arguments

    **kwargs

  File "/usr/lib/python3.6/argparse.py", line 1361, in add_argument

    return self._add_action(action)

  File "/usr/lib/python3.6/argparse.py", line 1724, in _add_action

    self._optionals._add_action(action)

  File "/usr/lib/python3.6/argparse.py", line 1565, in _add_action

    action = super(_ArgumentGroup, self)._add_action(action)

  File "/usr/lib/python3.6/argparse.py", line 1375, in _add_action

    self._check_conflict(action)

  File "/usr/lib/python3.6/argparse.py", line 1514, in _check_conflict

    conflict_handler(action, confl_optionals)

  File "/usr/lib/python3.6/argparse.py", line 1523, in _handle_conflict_error

    raise ArgumentError(action, message % conflict_string)

argparse.ArgumentError: argument --timeout: conflicting option string: --timeout

```

however awx ping is seeming to work 

```
awx ping

{

     "ha": false,

     "version": "21.6.1.dev157+g8333b0cf66.d20220930",

     "active_node": "awx_1",

     "install_uuid": "89fc8c20-977e-4f2b-8d62-ab50976ab06b",

     "instances": [

          {

               "node": "awx_1",

               "node_type": "hybrid",

               "uuid": "00000000-0000-0000-0000-000000000000",

               "heartbeat": "2022-10-21T06:49:32.193420Z",

               "capacity": 57,

               "version": "21.6.1.dev157+g8333b0cf66.d20220930"

          },

          {

               "node": "receptor-1",

               "node_type": "execution",

               "uuid": "00000000-0000-0000-0000-000000000000",

               "heartbeat": "2022-10-21T06:48:35.532876Z",

               "capacity": 0,

               "version": "ansible-runner-???"

          },

          {

               "node": "receptor-2",

               "node_type": "execution",

               "uuid": "00000000-0000-0000-0000-000000000000",

               "heartbeat": "2022-10-21T06:48:35.785869Z",

               "capacity": 0,

               "version": "ansible-runner-???"

          }

     ],

     "instance_groups": [

          {

               "name": "controlplane",

               "capacity": 57,

               "instances": [

                    "awx_1"

               ]

          },

          {

               "name": "default",

               "capacity": 57,

               "instances": [

                    "awx_1",

                    "receptor-1",

                    "receptor-2"

               ]

          }

     ]

}

```

### AWX version

3.8.6

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Ansible version

2.10.8

### Operating system

Ubuntu 22.04.1 LTS

### Web browser

Chrome

### Steps to reproduce

```
awx --conf.host https://<ipadress>:<port>     --conf.username <username> --conf.password <password>     --conf.insecure     users list
  
 awx login -f human
 awx login -f human --conf.insecure
```

 and then upon running the command
 
```
  awx --conf.host https://127.0.0.1 --conf.username awxuser --conf.password awxpassword --conf.insecure job_templates launch 'GitOps with Marketplace'
```

which is giving the error 

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 18.217.0.125:8043

DEBUG:urllib3.connectionpool:https://18.217.0.125:8043 "GET /api/ HTTP/1.1" 200 186

DEBUG:awxkit.api.client:"GET https://18.217.0.125:8043/api/" elapsed: 0:00:00.062448

DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.api.ApiV2'> by url: /api/v2/

DEBUG:urllib3.connectionpool:https://18.217.0.125:8043 "GET /api/v2/ HTTP/1.1" 200 1708

DEBUG:awxkit.api.client:"GET https://18.217.0.125:8043/api/v2/" elapsed: 0:00:00.060663

DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.job_templates.JobTemplates'> by url: /api/v2/job_templates/

DEBUG:urllib3.connectionpool:https://18.217.0.125:8043 "OPTIONS /api/v2/job_templates/ HTTP/1.1" 200 25550

DEBUG:awxkit.api.client:"OPTIONS https://18.217.0.125:8043/api/v2/job_templates/" elapsed: 0:00:00.208581

DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.job_templates.JobTemplates'> by url: /api/v2/job_templates/

DEBUG:urllib3.connectionpool:https://18.217.0.125:8043 "OPTIONS /api/v2/job_templates/1/ HTTP/1.1" 200 13963

DEBUG:awxkit.api.client:"OPTIONS https://18.217.0.125:8043/api/v2/job_templates/1/" elapsed: 0:00:00.167353

DEBUG:urllib3.connectionpool:https://18.217.0.125:8043 "OPTIONS /api/v2/job_templates/1/launch/ HTTP/1.1" 200 7084

DEBUG:awxkit.api.client:"OPTIONS https://18.217.0.125:8043/api/v2/job_templates/1/launch/" elapsed: 0:00:00.108663

Traceback (most recent call last):

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/__init__.py", line 25, in run

    cli.parse_resource()

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/client.py", line 168, in parse_resource

    response = self.parse_action(resource)

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/client.py", line 229, in parse_action

    parser = ResourceOptionsParser(self.v2, page, self.resource, subparsers)

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/options.py", line 103, in __init__

    self.handle_custom_actions()

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/options.py", line 286, in handle_custom_actions

    action(self.page).add_arguments(self.parser, self)

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/custom.py", line 78, in add_arguments

    resource_options_parser.build_query_arguments(self.action, 'LAUNCH')

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/options.py", line 277, in build_query_arguments

    **kwargs

  File "/usr/lib/python3.6/argparse.py", line 1361, in add_argument

    return self._add_action(action)

  File "/usr/lib/python3.6/argparse.py", line 1724, in _add_action

    self._optionals._add_action(action)

  File "/usr/lib/python3.6/argparse.py", line 1565, in _add_action

    action = super(_ArgumentGroup, self)._add_action(action)

  File "/usr/lib/python3.6/argparse.py", line 1375, in _add_action

    self._check_conflict(action)

  File "/usr/lib/python3.6/argparse.py", line 1514, in _check_conflict

    conflict_handler(action, confl_optionals)

  File "/usr/lib/python3.6/argparse.py", line 1523, in _handle_conflict_error

    raise ArgumentError(action, message % conflict_string)

argparse.ArgumentError: argument --timeout: conflicting option string: --timeout

```

### Expected results

the job should have launched on the awx instance. 

### Actual results

the following error comes 

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 18.217.0.125:8043

DEBUG:urllib3.connectionpool:https://18.217.0.125:8043 "GET /api/ HTTP/1.1" 200 186

DEBUG:awxkit.api.client:"GET https://18.217.0.125:8043/api/" elapsed: 0:00:00.062448

DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.api.ApiV2'> by url: /api/v2/

DEBUG:urllib3.connectionpool:https://18.217.0.125:8043 "GET /api/v2/ HTTP/1.1" 200 1708

DEBUG:awxkit.api.client:"GET https://18.217.0.125:8043/api/v2/" elapsed: 0:00:00.060663

DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.job_templates.JobTemplates'> by url: /api/v2/job_templates/

DEBUG:urllib3.connectionpool:https://18.217.0.125:8043 "OPTIONS /api/v2/job_templates/ HTTP/1.1" 200 25550

DEBUG:awxkit.api.client:"OPTIONS https://18.217.0.125:8043/api/v2/job_templates/" elapsed: 0:00:00.208581

DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.job_templates.JobTemplates'> by url: /api/v2/job_templates/

DEBUG:urllib3.connectionpool:https://18.217.0.125:8043 "OPTIONS /api/v2/job_templates/1/ HTTP/1.1" 200 13963

DEBUG:awxkit.api.client:"OPTIONS https://18.217.0.125:8043/api/v2/job_templates/1/" elapsed: 0:00:00.167353

DEBUG:urllib3.connectionpool:https://18.217.0.125:8043 "OPTIONS /api/v2/job_templates/1/launch/ HTTP/1.1" 200 7084

DEBUG:awxkit.api.client:"OPTIONS https://18.217.0.125:8043/api/v2/job_templates/1/launch/" elapsed: 0:00:00.108663

Traceback (most recent call last):

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/__init__.py", line 25, in run

    cli.parse_resource()

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/client.py", line 168, in parse_resource

    response = self.parse_action(resource)

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/client.py", line 229, in parse_action

    parser = ResourceOptionsParser(self.v2, page, self.resource, subparsers)

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/options.py", line 103, in __init__

    self.handle_custom_actions()

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/options.py", line 286, in handle_custom_actions

    action(self.page).add_arguments(self.parser, self)

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/custom.py", line 78, in add_arguments

    resource_options_parser.build_query_arguments(self.action, 'LAUNCH')

  File "/root/.local/lib/python3.6/site-packages/awxkit/cli/options.py", line 277, in build_query_arguments

    **kwargs

  File "/usr/lib/python3.6/argparse.py", line 1361, in add_argument

    return self._add_action(action)

  File "/usr/lib/python3.6/argparse.py", line 1724, in _add_action

    self._optionals._add_action(action)

  File "/usr/lib/python3.6/argparse.py", line 1565, in _add_action

    action = super(_ArgumentGroup, self)._add_action(action)

  File "/usr/lib/python3.6/argparse.py", line 1375, in _add_action

    self._check_conflict(action)

  File "/usr/lib/python3.6/argparse.py", line 1514, in _check_conflict

    conflict_handler(action, confl_optionals)

  File "/usr/lib/python3.6/argparse.py", line 1523, in _handle_conflict_error

    raise ArgumentError(action, message % conflict_string)

argparse.ArgumentError: argument --timeout: conflicting option string: --timeout

 
```

### Additional information

aws ping is working succesfully 
```
awx ping

{

     "ha": false,

     "version": "21.6.1.dev157+g8333b0cf66.d20220930",

     "active_node": "awx_1",

     "install_uuid": "89fc8c20-977e-4f2b-8d62-ab50976ab06b",

     "instances": [

          {

               "node": "awx_1",

               "node_type": "hybrid",

               "uuid": "00000000-0000-0000-0000-000000000000",

               "heartbeat": "2022-10-21T06:49:32.193420Z",

               "capacity": 57,

               "version": "21.6.1.dev157+g8333b0cf66.d20220930"

          },

          {

               "node": "receptor-1",

               "node_type": "execution",

               "uuid": "00000000-0000-0000-0000-000000000000",

               "heartbeat": "2022-10-21T06:48:35.532876Z",

               "capacity": 0,

               "version": "ansible-runner-???"

          },

          {

               "node": "receptor-2",

               "node_type": "execution",

               "uuid": "00000000-0000-0000-0000-000000000000",

               "heartbeat": "2022-10-21T06:48:35.785869Z",

               "capacity": 0,

               "version": "ansible-runner-???"

          }

     ],

     "instance_groups": [

          {

               "name": "controlplane",

               "capacity": 57,

               "instances": [

                    "awx_1"

               ]

          },

          {

               "name": "default",

               "capacity": 57,

               "instances": [

                    "awx_1",

                    "receptor-1",

                    "receptor-2"

               ]

          }

     ]

}
```

**Comment by fosterseth** [comment]
needs investigation for now

**Comment by john-westcott-iv** [comment]
@outjoker We recently added a [change to awxkit](https://github.com/ansible/awx/pull/12875/files#diff-a9bd7eb6b2412558016de55fd070193a8c6284ea82d5bc65c6b89d4295b37c1fR61) that might be causing this issue. Previously there was a `--timeout` option globally for all awx commands. In AWX itself we added a timeout option for job template prompts. Because of how awxkit works with the API we had to modify the global `--timeout` to be `--action-timeout` and added a `--timeout` option specifically to the actions that work with jobs. In your issue it says you are using awx version `3.8.6`, which is actually a Tower version, but would not have the new promotable timeout option on job templates. I think this maybe causing your issue with the `--timeout` option. Could you try downgrading to awxkit version 21.6.0 or earlier and trying again?

As a side note, for issues relating to Tower you can also open issues with Red Hat.

**Comment by emoruzzi** [comment]
Also experiencing the same error, using the [latest awx release](https://github.com/ansible/awx/releases/tag/21.7.0).
```
 awx --version
3.8.6

awx ping |jq .version
"21.7.0"

awx job_templates list                     
argument --timeout: conflicting option string: --timeout
```

**Comment by john-westcott-iv** [comment]
Where are you getting that version of awxkit from?
If you do a `pip install --upgrade awxkit==21.7.0` and get the version that matches with your awx version does it work?

**Comment by emoruzzi** [comment]
> Where are you getting that version of awxkit from? If you do a `pip install --upgrade awxkit==21.7.0` and get the version that matches with your awx version does it work?

https://docs.ansible.com/ansible-tower/latest/html/towercli/usage.html#installation
`pip3 install --user https://releases.ansible.com/ansible-tower/cli/ansible-tower-cli-latest.tar.gz`

**Comment by emoruzzi** [comment]
```
➜  ~ pip3 install --user https://releases.ansible.com/ansible-tower/cli/ansible-tower-cli-latest.tar.gz

Collecting https://releases.ansible.com/ansible-tower/cli/ansible-tower-cli-latest.tar.gz
  Using cached https://releases.ansible.com/ansible-tower/cli/ansible-tower-cli-latest.tar.gz (92 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: PyYAML in /opt/homebrew/lib/python3.10/site-packages (from awxkit==3.8.6) (5.4.1)
Requirement already satisfied: requests in /opt/homebrew/lib/python3.10/site-packages (from awxkit==3.8.6) (2.28.1)
Requirement already satisfied: charset-normalizer<3,>=2 in /opt/homebrew/lib/python3.10/site-packages (from requests->awxkit==3.8.6) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.10/site-packages (from requests->awxkit==3.8.6) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.10/site-packages (from requests->awxkit==3.8.6) (2022.6.15)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/homebrew/lib/python3.10/site-packages (from requests->awxkit==3.8.6) (1.26.12)
Building wheels for collected packages: awxkit
  Building wheel for awxkit (setup.py) ... done
  Created wheel for awxkit: filename=awxkit-3.8.6-py3-none-any.whl size=110690 sha256=1e45c0ed3bc2a00f0ddf8a8bcfa347e336f007949ce2a4c42a71df578ae78e0c
  Stored in directory: /Users/emoruzzi/Library/Caches/pip/wheels/05/29/bb/c5db4bed33f96abfcf15d5a21e2626777f57d9b0b358afbd13
Successfully built awxkit
Installing collected packages: awxkit
Successfully installed awxkit-3.8.6

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python3.10 -m pip install --upgrade pip
➜  ~ awx --version
3.8.6
➜  ~ awx job_templates list                                                                            
argument --timeout: conflicting option string: --timeout
```

Using specific version works tho
```
pip install --upgrade awxkit==21.7.0
awx --version
21.7.0
awx job_templates list |head

{
     "count": 2,
     "next": null,
     "previous": null,
     "results": [
          {
```

**Comment by runejuhl** [comment]
Just saw this issue, again with the most recent awxcli release. I'm a bit surprised that this issue has been closed, when the problem still exists in the most recent release. Is there a solution for this that doesn't involve downgrading?

**Comment by jahknem** [comment]
I have the same issue with version 3.8.6. Downgrading was the only solution which has helped.

**Comment by ccope** [comment]
`pipx install awxkit` installs 3.8.6 for me, but it's a very old version. latest appears to be 24.3.1. `pipx install awxkit==24.3.1` gives me a working install

**Comment by luisxkimo** [comment]
Confirm from my side same issue with versions
3.8.X
3.7.X
3.6.X

Command executed:

awx job_templates list
