### ISSUE TITLE
AWX Job cleanup defaulting to 30 days even after changing to different range

### ISSUE THREAD

**Issue by b3rgman** [ansible/awx#1312]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Upon changing the numbers of days in the job cleanup (eg: 3) it defaults to 30 when running the job.

##### ENVIRONMENT
* AWX version: 2.5.0a1
* AWX install method: docker on linux
* Ansible version:  2.5.0a1
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

When running management jobs, I launch cleanup job details.  It asks me for the number of days to retain.  I input 3.  I launch the job. In the extra vars window it shows 30.  No jobs are cleaned up.
##### EXPECTED RESULTS

I expect 3 days of jobs to be left.

##### ACTUAL RESULTS

It defaults to 30.  No jobs are cleaned

##### ADDITIONAL INFORMATION

I also set the schedule to 3 days.  The jobs are still not purged.

**Comment by AlanCoding** [comment]
Confirmed UI issue, even when putting in another number, the data submitted gives 30 days. API accepts input of the format:

```json
{"extra_vars": {"days": 33}}
```

UI console shows this, when I start recording right before hitting the rocket ship (more errors are shown on page load).

```
angular.js:14800 TypeError: Cannot read property '$setPristine' of undefined
    at onOpen (http://localhost:8013/static/js/app.810d75bbd505d831d1bf.js:87445:44)
    at HTMLDivElement.open (http://localhost:8013/static/js/app.810d75bbd505d831d1bf.js:67426:21)
    at $.(anonymous function).(anonymous function)._trigger (http://localhost:8013/static/js/vendor.73d6dd69261eea682f5a.js:19262:13)
    at $.(anonymous function).(anonymous function).open (http://localhost:8013/static/js/vendor.73d6dd69261eea682f5a.js:73486:8)
    at $.(anonymous function).(anonymous function).open (http://localhost:8013/static/js/vendor.73d6dd69261eea682f5a.js:18709:25)
    at HTMLDivElement.<anonymous> (http://localhost:8013/static/js/vendor.73d6dd69261eea682f5a.js:18821:40)
    at Function.each (http://localhost:8013/static/js/vendor.73d6dd69261eea682f5a.js:8179:19)
    at jQuery.fn.init.each (http://localhost:8013/static/js/vendor.73d6dd69261eea682f5a.js:7951:17)
    at jQuery.fn.init.$.fn.(anonymous function) [as dialog] (http://localhost:8013/static/js/vendor.73d6dd69261eea682f5a.js:18801:10)
    at http://localhost:8013/static/js/app.810d75bbd505d831d1bf.js:87491:35
```

**Comment by tidypete** [comment]
Having the same issue in AWX 1.0.4.38

**Comment by jaredevantabor** [comment]
this is fixed in devel
