### ISSUE TITLE
K8S / MAIN / RECEPTOR : Task killed trying opening receptor.conf in W mode

### ISSUE THREAD

**Issue by Ghost0shell** [ansible/awx#13224]
##### ISSUE TYPE
 
Bug, Docs Fix or other nominal change

##### COMPONENT NAME
Backend

##### SUMMARY

In a kubernetes context , awx is trying to open the receptor conf file in write mode, which is in readonly mode due to infrastructure type. 

##### ENVIRONMENT
* AWX version: 21.8.0
* AWX install method: operator
* AWX deployment target: kubernetes

##### STEPS TO REPRODUCE

upgrade to awx 21.8 or 21.9 under kubernetes and see the task container crashlooping.

##### EXPECTED RESULTS

cool start of the task container without crash

##### ACTUAL RESULTS

```
OSError: [Errno 30] Read-only file system: '/etc/receptor/receptor.conf'
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/__init__.py", line 201, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/management/commands/run_dispatcher.py", line 81, in handle
    consumer.run()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/base.py", line 181, in run
    self.worker.on_start()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/task.py", line 140, in on_start
    dispatch_startup()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/system.py", line 86, in dispatch_startup
    write_receptor_config()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 671, in write_receptor_config
    with open(__RECEPTOR_CONF, 'w') as file:
```

##### ADDITIONAL INFORMATION

the problematic function seems to be write_receptor_config:

```
def write_receptor_config():
    lock = FileLock(__RECEPTOR_CONF_LOCKFILE)
    with lock:
        receptor_config = list(RECEPTOR_CONFIG_STARTER)

        this_inst = Instance.objects.me()
        instances = Instance.objects.filter(node_type=Instance.Types.EXECUTION)
        existing_peers = {link.target_id for link in InstanceLink.objects.filter(source=this_inst)}
        new_links = []
        for instance in instances:
            peer = {'tcp-peer': {'address': f'{instance.hostname}:{instance.listener_port}', 'tls': 'tlsclient'}}
            receptor_config.append(peer)
            if instance.id not in existing_peers:
                new_links.append(InstanceLink(source=this_inst, target=instance, link_state=InstanceLink.States.ADDING))

        InstanceLink.objects.bulk_create(new_links)

        with open(__RECEPTOR_CONF, 'w') as file:
            yaml.dump(receptor_config, file, default_flow_style=False)
```
which is called in systems.py this way. i'm not pretty sur but shouldnt it be "if not settings.IS_K8S" instead ? 

```
    # TODO: Enable this on VM installs
    if settings.IS_K8S:
        write_receptor_config()
```

**Comment by Ghost0shell** [comment]
Answering myself : 

i just understood the sense the new function : this one is mounting a new receptor file before starting to work. The problem is located on awx-operator who mount a receptor.conf configmap .

**Comment by fosterseth** [comment]
@Ghost0shell what version of awx operator are you using? you will need to be on 0.29.0 at least, if using >= 21.8 AWX

**Comment by akus062381** [comment]
Hi @Ghost0shell,

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
