### ISSUE TITLE
Unable to Use Mutiple Vaults in Same Job Template

### ISSUE THREAD

**Issue by mneumarkidg** [ansible/awx#1329]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Trying to create a job template using several vault passwords... Exception provided from application

##### ENVIRONMENT
* AWX version: 1.0.3.41
* AWX install method:docker on linux
* Ansible version:  2.4.3.0
* Operating System: CentOS 7
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Assigned 10+ vaults to job template. Run and produces exception...

##### EXPECTED RESULTS

Successful playbook execution

##### ACTUAL RESULTS

Enter passphrase for /tmp/awx_6664_0c_C6H/credential_3: 
Identity added: /tmp/awx_6664_0c_C6H/credential_3 (/tmp/awx_6664_0c_C6H/credential_3)
ansible-playbook 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Using /etc/ansible/ansible.cfg as config file
Vault password (**********): 
Vault password (**********): 
Vault password (**********): 
Vault password (**********): 
Vault password (**********): 
Vault password (**********): 
Vault password (**********): 
Vault password (**********): 
Vault password (**********): 
Vault password (**********): 
Parsed /tmp/awx_6664_0c_C6H/tmpbEmBQz inventory source with script plugin
ERROR! Unexpected Exception, this is probably a bug: 'NoneType' object is not iterable
the full traceback was:
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 106, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 82, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 54, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 106, in _load_playbook_data
    entry_obj = Play.load(entry, variable_manager=variable_manager, loader=self._loader)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/play.py", line 117, in load
    return p.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 255, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/usr/lib/python2.7/site-packages/ansible/playbook/play.py", line 191, in _load_roles
    role_includes = load_list_of_roles(ds, play=self, variable_manager=self._variable_manager, loader=self._loader)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/helpers.py", line 352, in load_list_of_roles
    i = RoleInclude.load(role_def, play=play, current_role_path=current_role_path, variable_manager=variable_manager, loader=loader)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/role/include.py", line 59, in load
    return ri.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 245, in load_data
    ds = self.preprocess_data(ds)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/role/definition.py", line 93, in preprocess_data
    role_name = self._load_role_name(ds)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/role/definition.py", line 130, in _load_role_name
    all_vars = self._variable_manager.get_vars(play=self._play)
  File "/usr/lib/python2.7/site-packages/ansible/vars/manager.py", line 364, in get_vars
    for vars_file_item in play.get_vars_files():
TypeError: 'NoneType' object is not iterable

**Comment by AlanCoding** [comment]
This feels like a shot in the dark, but it could be the same as https://github.com/ansible/ansible/issues/31249, I notice that fix was put into 2.5, not necessarily into 2.4.

Do you hit this if you upgrade to the 2.5 beta?

**Comment by wenottingham** [comment]
Please test with Ansible 2.5, and reopen if this persists.
