### ISSUE TITLE
Thycotic Secret Server SSH key + passphrase does not work

### ISSUE THREAD

**Issue by timothydilbert** [ansible/awx#13384]
##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME
 - API
 - UI
 - CLI
 - Other

##### SUMMARY
We use Thycotic Secret Server as an external secret management platform. SSH Keys stored in Secret Server are rotated every X days. When we try to use those SSH keys with Job Templates, it causes errors in the Ansible Automation Platform and the playbook does not run.

##### ENVIRONMENT
* AWX version: Ansible Automation Platform Controller 4.2.0
* AWX install method: operator, developer environment
* AWX deployment target: N/A
* Operating System: RHEL 8
* Web Browser: N/A

##### STEPS TO REPRODUCE

1. On an Ubuntu server, create a sudo user with an SSH key (no password).
2. Create a secret in the Thycotic Secret server using the **Unix Account (SSH Key Rotation - No Password)** template.
3. Wait for the heartbeat to report as being successful, confirming that the original SSH key provided is valid.
4. Use Secret Server to rotate the SSH key and generate a new one.
5. Go to Ansible Automation Platform, add a new credential, mapping the **SSH Private Key** (private-key) and **Private Key Passphrase** (private-key-passphrase) to the Thycotic Secret and Field names.
6. Try to run a Job Template using those credentials.

##### EXPECTED RESULTS

Ansible should connect to the Host specified on the Job Template. 

##### ACTUAL RESULTS

A python error is thrown with the following output:
```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 539, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 271, in run
    res = self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 326, in _run_internal
    transmitter_future.result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/utils/common.py", line 1153, in wrapper_cleanup_new_process
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 398, in transmit
    ansible_runner.interface.run(streamer='transmit', _output=_socket.makefile('wb'), **self.runner_params)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/ansible_runner/interface.py", line 210, in run
    r.run()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/ansible_runner/streaming.py", line 48, in run
    json.dumps({'kwargs': self.kwargs}, cls=UUIDEncoder).encode('utf-8')
  File "/usr/lib64/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib64/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/ansible_runner/streaming.py", line 26, in default
    return json.JSONEncoder.default(self, obj)
  File "/usr/lib64/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
```

##### ADDITIONAL INFORMATION

While troubleshooting we noticed that if we download the encrypted private SSH key from the Secret Server, upload that encrypted SSH key and passphrase into Ansible Automation Platform, the connect WILL work. As such, the problem appears to be related to Ansible's ability to download and decrypt the SSH key before attempting to connect to the Linux host.

**Comment by timothydilbert** [comment]
In case this helps to troubleshoot:
```
ansible [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)]
  jinja version = 3.1.2
  libyaml = True
```

**Comment by tarunchy** [comment]
Any ETA when this issue can be fixed?

**Comment by akus062381** [comment]
@timothydilbert, thank you for your submission.

Can you please provide us with the API endpoint for the Thycotic credential lookup?

**Comment by timothydilbert** [comment]
@akus062381. Under Credentials we have the Secret Server URL set to: https://secret.server.local/SecretServer.

I should mention that we have other secrets pulling from Secret Server without issue (e.g. AD users). The error seems to be isolated to pulling the SSH Key + Passcode from Secret Server.

**Comment by timothydilbert** [comment]
I wouldn't consider this a solution, but I created a new Linux user that authenticates with a password (no SSH key). Secret Server rotates the password for the user, which still meets our corporate policy. The error went away when I used that external credential from Secret Server, authenticating with SSH username + password.

Just mentioning this for anyone reading and looking for a quick solution.

**Comment by tarunchy** [comment]
Hello I have found the fix this issue. I created a fork and updated the code - https://github.com/tarunchy/awx/blob/devel/awx/main/credential_plugins/tss.py 
I tested from awx shell console. Love to contribute back to Ansible community. Please review and let me know if I can raise a PR for merge

**Comment by shanemcd** [comment]
Please open a PR and we can review/discuss there.

**Comment by tarunchy** [comment]
PR already opened - https://github.com/ansible/awx/pull/13427 and updated the description for the change details.
