### ISSUE TITLE
Can't delete the notification templates

### ISSUE THREAD

**Issue by elibramson** [ansible/awx#13393]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary
We have 2 notification templates, that we can't delete.

When we try to delete these notification templates, we get the following error for the first template:

> DELETE api/v2/notification_templates/1/ 405
> Delete not allowed while there are pending notifications

We checked the number of pending queries by this command:
> SELECT *
> FROM public.main_notification WHERE status='pending';

And we saw, that there are about 300 notifications that are stuck in the "pending" state.

We tried to delete the pending notifications from the database by the following query:

> DELETE
> FROM public.main_notification
> WHERE status='pending';

But we get this error:

> SQL Error [23503]: ERROR: update or delete on table "main_notification" violates foreign key constraint "main_activitystream__notification_id_bbfaa8ac_fk_main_noti" on table "main_activitystream_notification"
>   Detail: Key (id)=(11259541) is still referenced from table "main_activitystream_notification".

### AWX version

21.2.0

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

Unknown

### Expected results

The notification templates are deleted

### Actual results

The notification templates are not deleted

**Comment by akus062381** [comment]
hi @elibogomolnyi! thank you so much for reporting this problem. Would you be able to provide the traceback you're seeing? Also, can you please provide more specific details on the notification templates themselves? This will help us try to recreate this issue (the more details the better).

**Comment by elibramson** [comment]
Hi @akus062381, thank you for your response.

I can't see anything related to it in the backend logs; what I get in the awx-web logs is:

> 2023-01-05 14:36:13,732 WARNING  [41e6d8e49b06447c9cbcf658ac1eb1fe] django.request Method Not Allowed: /api/v2/notification_templates/4/
> 172.27.4.140 - - [05/Jan/2023:14:36:13 +0000] "DELETE /api/v2/notification_templates/4/ HTTP/1.1" 405 68 "https://unicorn.cyberark.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" "194.90.225.101"
> [pid: 1278|app: 0|req: 735/410033] 172.27.4.140 () {66 vars in 3702 bytes} [Thu Jan  5 14:36:13 2023] DELETE /api/v2/notification_templates/4/ => generated 68 bytes in 543 msecs (HTTP/1.1 405) 14 headers in 609 bytes (1 switches on core 0)

Unfortunately, I can provide details about this error reproduction since we have been using AWX for a long time, and different users modified this template and we also upgrade AWX from time to time.

After we made an AWX migration to another K8s cluster, we saw that the AWX pod gets restarted every 5 minutes. We mentioned that our logs were full of the errors like this:

> 2022-12-29 09:59:09,003 ERROR    [809a91c31a0f42e0a7d574e2b9ad8b77] awx.main.tasks.system Send Notification Failed HTTPSConnectionPool(host='k3vzi1jferfe.execute-api.eu-west-1.amazonaws.com', port=443): Max retries exceeded with url: /v1/callback (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa46ccd2dc0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
> Traceback (most recent call last):
>   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
>     conn = connection.create_connection(
>   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
>     raise err
>   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
>     sock.connect(sa)
> TimeoutError: [Errno 110] Connection timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
>     httplib_response = self._make_request(
>   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
>     self._validate_conn(conn)
>   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
>     conn.connect()
>   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/urllib3/connection.py", line 353, in connect
>     conn = self._new_conn()
>   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa46ccd2dc0>: Failed to establish a new connection: [Errno 110] Connection timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/requests/adapters.py", line 439, in send
>     resp = conn.urlopen(
>   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
>     retries = retries.increment(
>   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='k3vzi1jferfe.execute-api.eu-west-1.amazonaws.com', port=443): Max retries exceeded with url: /v1/callback (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa46ccd2dc0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/system.py", line 294, in send_notifications
>     sent = notification.notification_template.send(notification.subject, notification.body)
>   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/models/notifications.py", line 185, in send
>     return backend_obj.send_messages([notification_obj])
>   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/notifications/webhook_backend.py", line 71, in send_messages
>     r = chosen_method(
>   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/requests/api.py", line 117, in post
>     return request('post', url, data=data, json=json, **kwargs)
>   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/requests/api.py", line 61, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/requests/sessions.py", line 542, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/requests/sessions.py", line 655, in send
>     r = adapter.send(request, **kwargs)
>   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/requests/adapters.py", line 516, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='k3vzi1jferfe.execute-api.eu-west-1.amazonaws.com', port=443): Max retries exceeded with url: /v1/callback (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa46ccd2dc0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

From the logs above we defined, the pod restart happens because of some problems with notifications. We saw two notification templates with the type **Webhook**; they all had k3vzi1jferfe.execute-api.eu-west-1.amazonaws.com as the target URL. We decided to delete them, but we couldn't do it because of the error described in this issue. So to make the AWX work again, we changed the target URL to the valid one (the DataDogs URL) for both templates. After it, we stopped receiving the errors, and AWX started working without restarts.

But still, we can't delete these notification templates.

**Comment by elibramson** [comment]
@akus062381 
Please pay attention, that I've edited the issue. After we restarted the awx pods, we don't get the **Bad Gateway** error anymore, only the "**Delete not allowed while there are pending notifications**" for both pods

**Comment by gamuniz** [comment]
@elibogomolnyi It should be possible to delete those notifications if you change the status from pending to failed from the task container:
awx-manage shell_plus
for n in Notification.objects.all():
    if n.status=='pending':
        n.update_fields(status='failed')

*NOTE* shell_plus is powerful so I wouldn't recommend doing anything besides the above.
