### ISSUE TITLE
Ansible automation platform, proxy and environment variables

### ISSUE THREAD

**Issue by cwarner-mdsol** [ansible/awx#13472]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

`project_update` should receive proxy settings from the job template. So for instance, using a controller node without modifying global job settings one should be able to set the following environment variables:

{
  "HTTP_PROXY": "http://proxy.here:3128/",
  "HTTPS_PROXY": "http://proxy.here:3128/"
}

In the template and the [project_update](https://github.com/ansible/awx/blob/devel/awx/playbooks/project_update.yml) playbook should respect those proxy values so scm's downstream can pull source artifacts from where ever required.

### AWX version

4.1.0

### Select the relevant components

- [ ] UI
- [X] API
- [X] Docs
- [ ] Collection
- [X] CLI
- [X] Other

### Installation method

N/A

### Modifications

no

### Ansible version

2.13.3

### Operating system

rhel8

### Steps to reproduce

Setup a proxy and then spin an automation platform remote node. Set the proxy variables via global job settings and things work. Then set the proxy settings via the actual job template and it fails. Specifically at project_update

### Expected results

When the remote environment variables for proxy support are set in the template variables they should be apart of project_update's run BEFORE attempting to pull down the code.

### Actual results

We get a failure because the node in question isn't able to route traffic through the proxy.

### Additional information

This is not container group related and is related to actual private data center instances.

**Comment by djyasin** [comment]
Hello @cwarner-mdsol,
Based on the version number you provided, it appears that you are an AAP customer. Please reach out to the Red Hat support team and submit a ticket.

Here is the link to do so:

https://access.redhat.com/support

Thank you for your submission and for supporting AWX!

**Comment by cwarner-mdsol** [comment]
We opened a ticket there as well, we currently have a work-around implemented but figured this would likely need to be remedied here in awx as well. I'd like to leave this open as well until we can decide on a proper fix or maybe there is some other way to deal with it, but i'd like to have that discussion in the open.

**Comment by AlanCoding** [comment]
> `project_update` should receive proxy settings from the job template. So for instance, using a controller node without modifying global job settings one should be able to set the following environment variables:

This isn't clear enough for me. Where did you put these PROXY_ env vars? Did you put them in `AWX_TASK_ENV` , as visible in `/api/v2/settings/`? It will be most helpful to show API details for reproduction steps. Likewise, it would be helpful to get `/api/v2/project_updates/42/` for the id of the project update you saw failed, as this will list environment variables that were applied to the job.

However, the project update runs a playbook. As I'm sure you are aware, the environment variables in the context where `ansible-playbook` is invoked are not necessarily passed through to the subprocess where a `command:` task runs its command. This is why we have a different `GALAXY_TASK_ENV` setting to apply environment variables to `ansible-galaxy` commands, as these commonly require their own proxy settings. Likewise, the git server often requires its own proxy settings, separate from the rest of the app. Saying that your proxy settings didn't apply to the project update is too broad, what actions in the project update require the proxy?

**Comment by cwarner-mdsol** [comment]
Sure I can expound a bit, our setup includes automation controller nodes in different data centers. In this particular data center we have a proxy setup to reach out to the internet where we have a table of domains we allow these nodes to access.

In running a job we found that there is no proxy functionality at the job level without affecting all automation controller nodes. Digging further it looked like the project_update playbook didn't have any functionality for proxy configuration there at least not for the git task. So even if you set the `http_proxy` environment variable via the job template. That never gets serialized as part of job_env because [project_update](https://github.com/ansible/awx/blob/devel/awx/playbooks/project_update.yml) has to run first. While we have a way to set env vars, we need to make sure that project_update is encapsulated as apart of that.

Running project_update without those environment variable updates:

`Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1441, in run
    self.pre_run_hook(self.instance, private_data_dir)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1932, in pre_run_hook
    sync_task.run(local_project_sync.id)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 901, in _wrapped
    return f(self, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1580, in run
    raise AwxTaskError.TaskError(self.instance, rc)
Exception: project_update 357935 (failed) encountered an error (rc=None), please see task stdout for details.`

What we've done is add:
```
environment:
   http-proxy: "http://proxy.here:3128"
```
To the git task here https://github.com/ansible/awx/blob/devel/awx/playbooks/project_update.yml#L37-L46 in the interim.

I don't want to prescribe exactly how it should look but environment variables especially the ones for proxy should be grabbed before running project_update or during project_update and apply specifically only to the controller nodes where a playbook is run.

**Comment by AlanCoding** [comment]
It could be documented better, but there is a standard practice for setting things up for a proxy git server, and so far it doesn't sound like its shortcomings are a problem for you. To replicate this standard practice:

PATCH `/api/v2/jobs/settings/`

```json
{
    "AWX_TASK_ENV": {
        "HTTP_PROXY": "foo.invalid",
        "HTTPS_PROXY": "foo.invalid"
    },
}
```

then I obtain the following in the git task when I update a project

```
TASK [update project using git] ************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/git ls-remote https://github.com/ansible/test-playbooks.git -h refs/heads/pull/297/head", "msg": "fatal: unable to access 'https://github.com/ansible/test-playbooks.git/': Could not resolve proxy: foo.invalid", "rc": 128, "stderr": "fatal: unable to access 'https://github.com/ansible/test-playbooks.git/': Could not resolve proxy: foo.invalid\n", "stderr_lines": ["fatal: unable to access 'https://github.com/ansible/test-playbooks.git/': Could not resolve proxy: foo.invalid"], "stdout": "", "stdout_lines": []}
```

from `/api/v2/project_updates/223/`, also see `job_env`

```
        "HTTP_PROXY": "foo.invalid",
        "HTTPS_PROXY": "foo.invalid",
```

**Comment by cwarner-mdsol** [comment]
Right, that doesn't work for specific controllers. So setting `AWX_TASK_ENV` isn't the problem, the problem is that setting it sets those variables for every controller node. We don't want that, I should be able to set `AWX_TASK_ENV`only to proxy for "X" instance group or controller node or even job. 

It might be easier to get on the same page if we discuss this scenario. If I have 5 controller nodes in the United States and 5 controller nodes in Africa, the controller nodes in Africa should be able to have one proxy setting and the controller nodes in the US should be able to have a completely different set of proxy settings.

**Comment by Dixie9000** [comment]
@cwarner-mdsol Maybe I'm missing something, but based on your example, i.e. Africa vs US, you would have separate `settings.yml` files for different environments under your `group_vars` folder in IAC, such as an Africa group, and a US group, each with their own respective `settings.yml` files. I assume you're using an IAC.

You said: >there is no proxy functionality at the job level without affecting all automation controller nodes.

You can set a different proxy in the extra_vars setting of a job iirc, pretty sure I've done it before. You can easily assign differentiating `settings.yml` files for different controller groups if you wish. I do this at my company because I have a separate controller for qa and prod, each with their own respective proxies.

**Comment by cwarner-mdsol** [comment]
@Dixie9000 thanks for the commentary, but I don't want to sidetrack this issue. With all due respect, making assumptions and then providing solutions based on that instead of sticking to whats been provided isn't necessarily helpful and i'd like to come up with a reasonable solution based on the actual problem stated above and not conjecture. Further in this specific case the suggestion wouldn't work as project_update would still fail; sincerely appreciate you trying to help though 🙂

**Comment by Dixie9000** [comment]
No offense, but it's not conjecture or sidetracking. You gave an example of a use-case (i.e. Africa/US). And I responded to that use-case with what I've done to overcome git-based scm proxying because I had the same issue in my environment, and it's based on separate controller environments that I have with separate proxies. You set them at the controller node settings level.

It would be nice to have a feature of adding a proxy prior to running a project update; I can't fathom a reasonable use-case for this requested feature, but I did in fact answer your question with regards to Africa vs. US. You have one node and it's proxy setup for US in settings and another node in Africa with it's own respective proxying.

You said: >I should be able to set AWX_TASK_ENV only to proxy for "X" instance group or controller node or even job.

You can set different proxies on different controller nodes. This was already explained. If you need a separate proxy for each different git project you're trying to get to that's an entirely different story. It just sounds like you haven't configured proxying properly.

No one on Github knows exactly how your environment is setup, we're just going off what you're telling us.

**Comment by cwarner-mdsol** [comment]
@Dixie9000 please read above, i'm not sure what else to say and am not prepared to go back and forth. If you think you have the solution based on the above and provided the answer, ok? I'm telling you it isn't the solution or the answer and that is side-tracking as it derails the conversation for genuine questions/solutions based on the information provided. If you're saying you need more information, don't understand or want clarity then fine but saying you answered the question about US/Africa based on your own setup helps no one which is the textbook definition of conjecture. All of this respectfully, I just want to stick to the above, thanks.

**Comment by irgama** [comment]
I have also run into an issue related to this. 
I need to set a proxy specifically for our git projects, which works when I use the global settings. 
The problem comes in when I then need to run a playbook against a windows system, and winrm tries to use the proxy. It kills the connection. 
I have had to go in and modify the playbook file as was shown earlier in this. 
Yes, I could go in and setup no_proxy in *just* the right way, but it would just be nice if I could specifically set env vars for projects

**Comment by AlanCoding** [comment]
@irgama would https://github.com/ansible/awx/pull/14190 help your situation?
