### ISSUE TITLE
When starting a job from template, the SCM update job fails with Error 500.

### ISSUE THREAD

**Issue by rndmh3ro** [ansible/awx#1349]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When starting a job from template, the SCM update job prior to this job fails with Error 500 and `ValueError: Invalid IPv6 URL` in logs.

##### ENVIRONMENT
* AWX version: 1.0.4.14
* AWX install method: docker on linux
* Ansible version:  2.4.3.0 
* Operating System: Red Hat Enterprise Linux Server release 7.4
* Web Browser: Firefox Latest

##### STEPS TO REPRODUCE

When starting a job from template, the SCM update job fails with Error 500 and `ValueError: Invalid IPv6 URL` in logs. This does not happen if I start the SCM Update from the Projects Page. It does not matter what kind of job I start.

##### EXPECTED RESULTS

No 500 error.

##### ACTUAL RESULTS

Logs from awx_web:
```2018-02-26 15:13:05,016 ERROR    django.request Internal Server Error: /api/v2/project_updates/16/stdout/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 255, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 210, in get
    return self.retrieve(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/views.py", line 4591, in retrieve
    content, start, end, absolute_end = unified_job.result_stdout_raw_limited(start_line, end_line)
  File "/usr/lib/python2.7/site-packages/awx/main/models/projects.py", line 510, in result_stdout_raw_limited
    return self._result_stdout_raw_limited(start_line, end_line, redact_sensitive=redact_sensitive)
  File "/usr/lib/python2.7/site-packages/awx/main/models/unified_jobs.py", line 1052, in _result_stdout_raw_limited
    return_buffer = UriCleaner.remove_sensitive(return_buffer)
  File "/usr/lib/python2.7/site-packages/awx/main/redact.py", line 20, in remove_sensitive
    o = urlparse.urlsplit(match.group(1))
  File "/usr/lib64/python2.7/urlparse.py", line 190, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```
In the Standard Out of the SCM Update job only this is written:
```
Using /etc/ansible/ansible.cfg as config file

PLAY [all] *********************************************************************


TASK [delete project directory before update] **********************************
skipping: [localhost]
```

Adresses:
``` ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:50:56:b2:e2:5f brd ff:ff:ff:ff:ff:ff
    inet 172.31.224.73/27 brd 172.31.224.95 scope global ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:feb2:e25f/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:2c:7c:c0:81 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:2cff:fe7c:c081/64 scope link
       valid_lft forever preferred_lft forever
5: veth326ad54@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP
    link/ether fe:dc:a8:b1:d2:e8 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::fcdc:a8ff:feb1:d2e8/64 scope link
       valid_lft forever preferred_lft forever
7: veth3d49e88@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP
    link/ether 12:84:b3:57:f6:ec brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::1084:b3ff:fe57:f6ec/64 scope link
       valid_lft forever preferred_lft forever
9: vetha800b2e@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP
    link/ether 42:8f:16:55:34:2d brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::408f:16ff:fe55:342d/64 scope link
       valid_lft forever preferred_lft forever
11: veth03c3e67@if10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP
    link/ether 06:86:28:67:83:99 brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::486:28ff:fe67:8399/64 scope link
       valid_lft forever preferred_lft forever
13: veth3a66f4f@if12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP
    link/ether 22:87:25:46:a5:cb brd ff:ff:ff:ff:ff:ff link-netnsid 4
    inet6 fe80::2087:25ff:fe46:a5cb/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by wenottingham** [comment]
What is the configuration for the project in question?

**Comment by rndmh3ro** [comment]
Okay, I downloaded the SCM Update Standard out Log and there was more information in there:
```TASK [fetch galaxy roles from requirements.yml] ********************************
Username for 'http://red.ac.ted.com': Password for 'http://user@red.ac.ted.com': 
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["ansible-galaxy", "install", "-r", "requirements.yml", "-p", "/var/lib/awx/projects/_6__project/roles/", "--force"], "delta": "0:00:40.792326", "end": "2018-02-26 15:22:31.149900", "msg": "non-zero return code", "rc": 1, "start": "2018-02-26 15:21:50.357574", "stderr": " [WARNING]: - dependency geerlingguy.java from role geerlingguy.jenkins differs
from already installed version (1.7.6), skipping

 [WARNING]: - ansible_project-puppet_rollout was NOT installed successfully: - command git clone http://red.ac.ted.com/scm/project/ansible_project-puppet_rollout.git ansible_project-puppet_rollout failed in directory /tmp/tmp9Mrchw (rc=128)
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.",
```

The problem seems to be that in my `requirements.yml` there is an entry for our internal git-repository which awx does not have access to.

**Comment by rndmh3ro** [comment]
Okay, I can confirm that removing the entry in the requirements-file fixes the problem for me.

However I guess there should be 500 error message in the gui because of this, right?

@wenottingham do you need any more information?

**Comment by wenottingham** [comment]
If possible, make your 'redacted' above resemble the URL exposed in the actual error (syntax, formatting) as much as possible. Other than that, no.

**Comment by rndmh3ro** [comment]
I updated the logs!

**Comment by chrismeyersfsu** [comment]
fixed by commits:
04693ecb0f853f0115a8ad7ea3c561baef217fcf
09d5645b90ff96ba67f0b84c0265679e66fec318
