### ISSUE TITLE
Error with inline vault password

### ISSUE THREAD

**Issue by fchiacchiaretta** [ansible/awx#137]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
When I try to setup and sync an inventory source (type Sourced from a project) which includes a group variable with an inline vault encrypted value, sync fails.

##### ENVIRONMENT
* AWX version: 1.0.0.338
* Ansible version:  2.3.1.0
* Operating System: CentOS 7.3

##### STEPS TO REPRODUCE
1. Create an empty inventory
2. Move to "Sources" tab and setup a reference to an existing project
3. Start sync

##### EXPECTED RESULTS
Inventory is properly synced.

##### ACTUAL RESULTS
Here is the output:
```
2017-09-12 15:55:22,949 INFO     awx.main.commands.inventory_import Updating inventory 2: Collaudo
2017-09-12 15:55:22,966 INFO     awx.main.commands.inventory_import Reading Ansible inventory source: /var/lib/awx/projects/_6__ansible/inventory/collaudo/hosts
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==1.0.0.338', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 107, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 661, in handle
    return self.handle_noargs(**options)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 955, in handle_noargs
    self.is_custom)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 210, in load_inventory_source
    is_custom=is_custom).load()
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 179, in load
    data = self.command_to_json(base_args + ['--list'])
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 163, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory backport failed (rc=4) with stdout:

stderr:
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/var/lib/awx/projects/_6__ansible/inventory/collaudo/group_vars/buildbot': line 9, column 17, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

nexus_user: admin
nexus_password: !vault |
                ^ here
```
Are inline secrets supported or should I use a vault file instead?

Regards,
Federico Chiacchiaretta

**Comment by jlmitch5** [comment]
thanks for filing. At a glance, this seems to be an api issue based on the python traceback.

**Comment by matburt** [comment]
Unfortunately we don't currently support unvaulting for scm-based inventory files, but it's something on our roadmap.

Reason being that we aren't currently invoking ansible to get this inventory which obviates the ability to handle vaulted information.  Ansible is currently working on modularizing their inventory scripts which will be required for us to do this.
