### ISSUE TITLE
AWX running jobs stuck during Cleanup Job (Management Job) and eventually fails

### ISSUE THREAD

**Issue by CMPluto** [ansible/awx#13790]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

AWX running jobs get stuck during Cleanup Schedule Job (Management Job)
Jobs stuck during cleanup job Schedule. And once the cleanup is over all the stuck jobs starts failing.

Please suggest the remedy to resolve this issue.

### AWX version

21.13.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

Ubuntu 18.04.6 LTS

### Web browser

Chrome

### Steps to reproduce

Start a cleanup schedule job. Make sure you have at least 4-7 days of cleanup jobs data that gets deleted using this "Cleanup Job Details" "Clean up Schedule Job" (Management Job. 

Also run multiple jobs during this cleanup job period. 
All jobs will get stuck and once the cleanup job gets completed. all the stuck jobs will eventually fail.

### Expected results

Cleanup job should not affect ongoing jobs. It should not get the highest priority and should stop backend DB operations.

### Actual results

AWX running jobs got stuck during " Cleanup Job Details"Cleanup Schedule Job (Management Job). it shows jobs are in running state but they are stuck.
 And once the cleanup is over all the stuck jobs starts failing.

**Comment by CMPluto** [comment]
@AlanCoding @joefiorini @farcaller @lukesneeringer  please suggest.

**Comment by farcaller** [comment]
I suggest you not to ping random unrelated people 😃

**Comment by fosterseth** [comment]
Can you give us logs or job_explanation for the failed jobs?

**Comment by CMPluto** [comment]
Cleanup job is taking 2 hours and every time it  initiates deleting data from 11/19/2022. and runs in endless loop and then causes job failures after 2 hrs. I have to manually restart all the pods on awx by using "kubectl rollout restart deploy awx -n awx" to bring the awx system to stable state.
please suggest.


Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/connection.py", line 1393, in get_connection
    if connection.can_read():
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/connection.py", line 809, in can_read
    return self._parser.can_read(timeout)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/connection.py", line 411, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/connection.py", line 423, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/connection.py", line 611, in connect
    sock = self.retry.call_with_retry(
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/connection.py", line 612, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/connection.py", line 1129, in _connect
    sock.connect(self.path)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 583, in run
    res = ansible_runner.interface.run(
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/ansible_runner/interface.py", line 211, in run
    r.run()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/ansible_runner/runner.py", line 317, in run
    result_id = child.expect(password_patterns, timeout=self.config.pexpect_timeout, searchwindowsize=100)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/pexpect/spawnbase.py", line 340, in expect
    return self.expect_list(compiled_pattern_list,
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/pexpect/pty_spawn.py", line 500, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/pexpect/spawnbase.py", line 179, in read_nonblocking
    self._log(s, 'read')
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/pexpect/spawnbase.py", line 130, in _log
    second_log.write(s)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/ansible_runner/utils/__init__.py", line 358, in write
    self._emit_event(line)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/ansible_runner/utils/__init__.py", line 403, in _emit_event
    self._event_callback(event_data)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/ansible_runner/runner.py", line 86, in event_callback
    should_write = self.event_handler(event_data)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/callback.py", line 164, in event_handler
    self.dispatcher.dispatch(event_data)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/queue.py", line 32, in dispatch
    self.connection.rpush(self.queue, json.dumps(obj, cls=AnsibleJSONEncoder))
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/commands/core.py", line 2695, in rpush
    return self.execute_command("RPUSH", name, *values)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/client.py", line 1235, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/connection.py", line 1397, in get_connection
    connection.connect()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/connection.py", line 617, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 2 connecting to unix socket: /var/run/redis/redis.sock. No such file or directory.
1
ad hoc commands: 0 deleted, 0 skipped.
2
deleting "2022-11-19 21:28:23.202090+00:00-76757-successful" (type dependency)
3
deleting "2022-11-19 21:41:52.542012+00:00-76762-successful" (type dependency)
4
deleting "2022-11-19 21:54:00.627956+00:00-76767-successful" (type dependency)
5
deleting "2022-11-19 22:02:36.228566+00:00-76772-successful" (type dependency)
6
deleting "2022-11-19 22:07:15.107783+00:00-76777-successful" (type dependency)
7
deleting "2022-11-19 22:09:16.926580+00:00-76781-successful" (type dependency)
8
deleting "2022-11-19 22:23:41.736071+00:00-76788-successful" (type dependency)
9
deleting "2022-11-19 22:28:12.748285+00:00-76796-successful" (type dependency)
10
deleting "2022-11-19 22:30:11.014643+00:00-76800-successful" (type dependency)
11
deleting "2022-11-19 22:32:13.019356+00:00-76805-successful" (type dependency)
12
deleting "2022-11-19 22:47:18.538065+00:00-76811-successful" (type dependency)
13
deleting "2022-11-19 22:56:13.534162+00:00-76816-successful" (type dependency)
14
deleting "2022-11-19 22:58:42.732067+00:00-76821-successful" (type dependency)
15
deleting "2022-11-19 23:01:14.113935+00:00-76826-successful" (type dependency)
16
deleting "2022-11-19 23:03:07.187491+00:00-76830-successful" (type dependency)
17
deleting "2022-11-19 23:05:13.824540+00:00-76836-successful" (type dependency)
18
deleting "2022-11-19 23:10:13.701675+00:00-76840-successful" (type dependency)
19
deleting "2022-11-19 23:11:27.435525+00:00-76843-successful" (type dependency)
20
deleting "2022-11-19 23:13:15.147776+00:00-76848-successful" (type dependency)
21
deleting "2022-11-19 23:14:35.072117+00:00-76851-successful" (type dependency)
22
deleting "2022-11-19 23:16:02.860106+00:00-76854-successful" (type dependency)
23
deleting "2022-11-19 23:17:22.705796+00:00-76857-successful" (type dependency)
24
deleting "2022-11-19 23:18:17.840560+00:00-76860-successful" (type dependency)
25
deleting "2022-11-19 23:19:18.216368+00:00-76865-successful" (type dependency)
26
deleting "2022-11-19 23:21:11.321217+00:00-76871-successful" (type dependency)

**Comment by fosterseth** [comment]
seems your redis container is crashing after some time. Do you have resources requests / limits defined for the containers? does kubectl get pods show that they restarted after that 2 hour mark?

Can you increase the amount of days in the prompt to try to get the system to delete less jobs in one go?

so instead of the default 30, maybe bump up to 180 and run. Then run again, with 150, 120, etc. until you get back to whatever desired period of time

not ideal but maybe this will help get the jobs cleaned up and then going forward will do a regular scheduling of cleanup jobs

**Comment by djyasin** [comment]
We are closing this issue due to inactivity. If you are still experiencing trouble, please open a new issue and mention this one in it.
