### ISSUE TITLE
Can't connect to rabbitMQ on fresh ec2 instance.

### ISSUE THREAD

**Issue by Nicarim** [ansible/awx#1393]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
I've got an issue with installer, specifically when running task / web container it seems to read wrong variables from environmental, and instead of using for rabbitmq `rabbitmq:5672` address it uses `127.0.0.1:5672`

Full error log inside `task` container

```
task_1       | [2018-02-28 14:55:02,723: DEBUG/Beat] Current schedule:
task_1       | <Entry: purge_stdout_files awx.main.tasks.purge_old_stdout_files() <freq: 7.00 days>
task_1       | <Entry: tower_scheduler awx.main.tasks.awx_periodic_scheduler() <freq: 30.00 seconds>
task_1       | <Entry: isolated_heartbeat awx.main.tasks.awx_isolated_heartbeat() <freq: 10.00 minutes>
task_1       | <Entry: task_manager awx.main.scheduler.tasks.run_task_manager() <freq: 20.00 seconds>
task_1       | <Entry: cluster_heartbeat awx.main.tasks.cluster_node_heartbeat() <freq: 1.00 minute>
task_1       | <Entry: celery.backend_cleanup celery.backend_cleanup() <crontab: 0 4 * * * (m/h/d/dM/MY)>
task_1       | <Entry: admin_checks awx.main.tasks.run_administrative_checks() <freq: 30.00 days>
task_1       | [2018-02-28 14:55:02,727: DEBUG/Beat] beat: Ticking with max interval->1.00 minute
task_1       | [2018-02-28 14:55:02,738: ERROR/Beat] beat: Connection error: [Errno 111] Connection refused. Trying again in 2.0 seconds...
task_1       | [2018-02-28 14:55:04,336: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
task_1       | Trying again in 4.00 seconds...
task_1       | 
task_1       | [2018-02-28 14:55:04,750: ERROR/Beat] beat: Connection error: [Errno 111] Connection refused. Trying again in 4.0 seconds...
task_1       | [2018-02-28 14:55:08,352: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
task_1       | Trying again in 6.00 seconds...
```
And it goes...

Same for operations that use rabbitMQ on web:
```
web_1        | error: [Errno 111] Connection refused
web_1        | 2018-02-28 15:04:22,988 ERROR    django.request Internal Server Error: /api/v2/instances/1/
web_1        | Traceback (most recent call last):
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
web_1        |     response = get_response(request)
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
web_1        |     response = self._get_response(request)
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
web_1        |     response = self.process_exception_by_middleware(e, request)
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
web_1        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
web_1        |     return func(*args, **kwargs)
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
web_1        |     return view_func(*args, **kwargs)
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
web_1        |     return self.dispatch(request, *args, **kwargs)
web_1        |   File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 284, in dispatch
web_1        |     return super(APIView, self).dispatch(request, *args, **kwargs)
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
web_1        |     response = self.handle_exception(exc)
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
web_1        |     self.raise_uncaught_exception(exc)
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
web_1        |     response = handler(request, *args, **kwargs)
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 257, in put
web_1        |     return self.update(request, *args, **kwargs)
web_1        |   File "/usr/lib/python2.7/site-packages/awx/api/views.py", line 594, in update
web_1        |     handle_ha_toplogy_changes.apply_async()
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/task.py", line 573, in apply_async
web_1        |     **dict(self._get_exec_options(), **options)
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/base.py", line 354, in send_task
web_1        |     reply_to=reply_to or self.oid, **options
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/amqp.py", line 310, in publish_task
web_1        |     **kwargs
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
web_1        |     routing_key, mandatory, immediate, exchange, declare)
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/connection.py", line 470, in _ensured
web_1        |     interval_max)
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/connection.py", line 382, in ensure_connection
web_1        |     interval_start, interval_step, interval_max, callback)
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/utils/__init__.py", line 246, in retry_over_time
web_1        |     return fun(*args, **kwargs)
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/connection.py", line 250, in connect
web_1        |     return self.connection
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/connection.py", line 756, in connection
web_1        |     self._connection = self._establish_connection()
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/connection.py", line 711, in _establish_connection
web_1        |     conn = self.transport.establish_connection()
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
web_1        |     conn = self.Connection(**opts)
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/connection.py", line 165, in __init__
web_1        |     self.transport = self.Transport(host, connect_timeout, ssl)
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/connection.py", line 186, in Transport
web_1        |     return create_transport(host, connect_timeout, ssl)
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/transport.py", line 299, in create_transport
web_1        |     return TCPTransport(host, connect_timeout)
web_1        |   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/transport.py", line 95, in __init__
web_1        |     raise socket.error(last_err)

```
I connected to respective containers via exec /bin/bash and environmental variables are there. Same for `awx-manage shell` os.getenv('RABBITMQ_HOST') it returns proper "rabbitmq". 

`/etc/awx/settings.py` is also correctly configured with os.getenv's

I'm having trouble understanding what is going on.

##### ENVIRONMENT
* AWX version: 1.0.4.29 (git checkout 1.0.4 after cloning)
* AWX install method: docker on linux
* Ansible version: ansible 2.4.3.0
* Operating System: Ubuntu 16.04
* Web Browser: Doesn't matter / Chrome

##### STEPS TO REPRODUCE

Ran the installer per guide. Configured inventory with external postgres volume and docker-compose.

##### EXPECTED RESULTS

Should be connecting to rabbitMQ

##### ACTUAL RESULTS

Doesn't - see errors above.

##### ADDITIONAL INFORMATION

Part of docker-compose
```
services:

  web:
    image: awx_web:1.0.4.29
    depends_on:
      - rabbitmq
      - memcached
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
      SECRET_KEY: <>
      DATABASE_NAME: awx
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpass
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
      AWX_ADMIN_USER: admin
      AWX_ADMIN_PASSWORD: <>

```
Inventory used for installation

```
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"

[all:vars]

# Remove these lines if you want to run a local image build
# Otherwise the setup playbook will install the official Ansible images. Versions may
# be selected based on: latest, 1, 1.0, 1.0.0, 1.0.0.123
# by default the base will be used to search for ansible/awx_web and ansible/awx_task
rabbitmq_version=3.6.14

# This will create or update a default admin (superuser) account in AWX, if not provided
# then these default values are used
default_admin_user=admin
default_admin_password=<>

# AWX Secret key
# It's *very* important that this stay the same between upgrades or you will lose the ability to decrypt
# your credentials
awx_secret_key=<>

# Openshift Install
# Will need to set -e openshift_password=developer -e docker_registry_password=$(oc whoami -t)
# openshift_host=127.0.0.1:8443
# awx_openshift_project=awx
# openshift_user=developer
# awx_node_port=30083

# Kubernetes Install
# kubernetes_context=test-cluster
# awx_kubernetes_namespace=awx

# Common Docker parameters
postgres_data_dir=/home/ubuntu/pgdocker
host_port=80

# Required for Openshift when building the image on your own
# Optional for Openshift if using Dockerhub or another prebuilt registry
# Required for Standalone Docker Install if building the image on your own
# Optional for Standalone Docker Install if using Dockerhub or another prebuilt registry
# Required for Docker Compose Install if building the image on your own
# Optional for Docker Compose Install if using Dockerhub or another prebuilt registry
# Define if you want the image pushed to a registry. The container definition will also use these images
# docker_registry=172.30.1.1:5000
# docker_registry_repository=awx
# docker_registry_username=developer

# Docker Compose Install
use_docker_compose=true
# The docker_compose.yml file will be created in this directory
# The name of the directory (here "awx") will be the prefix of the docker containers
docker_compose_dir=/home/ubuntu/awx_instance


# Docker_image will not attempt to push to remote if the image already exists locally
# Set this to true to delete images from docker on the build host so that they are pushed to the remote repository
# docker_remove_local_images=False

# Set pg_hostname if you have an external postgres server, otherwise
# a new postgres service will be created
# pg_hostname=postgresql
pg_username=awx
pg_password=awxpass
pg_database=awx
pg_port=5432

# Use a local distribution build container image for building the AWX package
# This is helpful if you don't want to bother installing the build-time dependencies as
# it is taken care of already.
# NOTE: IMPORTANT: If you are running a mininshift install, using this container might not work
#                  if you are using certain drivers like KVM where the source tree can't be mapped
#                  into the build container.
#                  Thus this setting must be set to False which will trigger a local build. To view the
#                  typical dependencies that you might need to install see:
#                  installer/image_build/files/Dockerfile.sdist
# use_container_for_build=true

# Build AWX with official logos
# Requires cloning awx-logos repo into the project root.
# Review the trademark guidelines at https://github.com/ansible/awx-logos/blob/master/TRADEMARKS.md
# awx_official=false

# Proxy
#http_proxy=http://proxy:3128
#https_proxy=http://proxy:3128
#no_proxy=mycorp.org

# Container networking configuration
# Set the awx_task and awx_web containers' search domain(s)
#awx_container_search_domains=example.com,ansible.com
# Alternate DNS servers
#awx_alternate_dns_servers="10.1.2.3,10.2.3.4"

# AWX project data folder. If you need access to the location where AWX stores the projects
# it manages from the docker host, you can set this to turn it into a volume for the container.
project_data_dir=/home/ubuntu/awx_instance/projects

```

Can't think of more things to check.

**Comment by Nicarim** [comment]
Installing from docker hub 1.0.4.14 version seems to work fine. There must be regression somewhere.

**Comment by shanemcd** [comment]
I am unable to recreate this. I deleted all of my images and containers and re-ran the installer.

```
devel ✔ $ make VERSION
awx: 1.0.4.29
```
```
$ docker exec -ti awx_task bash
[root@awx awx]# env | grep RABBITMQ_HOST
AWXWEB_ENV_RABBITMQ_HOST=rabbitmq
RABBITMQ_HOST=rabbitmq
[root@awx awx]# exit
exit
$ docker logs awx_task 2>&1 | grep "Connected to amqp"
[2018-02-28 16:27:31,654: INFO/MainProcess] Connected to amqp://guest:**@rabbitmq:5672/awx
```

Can you pull remove your containers and try again? Is `RABBITMQ_HOST` set if you exec into the task container?

**Comment by shanemcd** [comment]
Closing this since we haven't heard back. If the problem persists let us know and we'll reopen.
