### ISSUE TITLE
VCenter Inventory fails with unhelpful error.

### ISSUE THREAD

**Issue by Anthonyjmartin** [ansible/awx#1395]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When attempting to use VMWare VCenter as an inventory source it fails with the following error:

```
Plugin ini failed: /usr/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py:10: Error parsing host definition '"""': No closing quotation
```
##### ENVIRONMENT
* AWX version: 1.0.4.14
* AWX install method: docker on linux
* Ansible version:  2.4.3.0
* Operating System: Red Hat Enterprise Linux Server release 7.4 (Maipo)
* Web Browser: Google Chrome Version 64.0.3282.167 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

Configure an inventory source to use VCenter and sync.

##### EXPECTED RESULTS

Sync full VCenter inventory

##### ACTUAL RESULTS

```
2018-02-28 16:21:08,866 INFO     awx.main.commands.inventory_import Updating inventory 2: VCenter Servers
2018-02-28 16:21:08,876 DEBUG    awx.main.commands.inventory_import Using system install of ansible-inventory CLI: /usr/bin/ansible-inventory
2018-02-28 16:21:08,876 INFO     awx.main.commands.inventory_import Reading Ansible inventory source: /usr/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==1.0.4.14', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 993, in handle
    self.is_custom)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 242, in load_inventory_source
    is_custom=is_custom).load()
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 177, in load
    data = self.command_to_json(base_args + ['--list'])
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 160, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=4) with stdout:
stderr:
ERROR! Could not parse inventory source /usr/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py with available plugins:
Plugin script failed: Inventory script (/usr/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py) had an execution error: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py", line 727, in <module>
    print(VMWareInventory().show())
  File "/usr/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py", line 134, in __init__
    self.do_api_calls_update_cache()
  File "/usr/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py", line 176, in do_api_calls_update_cache
    self.inventory = self.instances_to_inventory(self.get_instances())
  File "/usr/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py", line 329, in get_instances
    return self._get_instances(kwargs)
  File "/usr/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py", line 336, in _get_instances
    si = SmartConnect(**inkwargs)
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyVim/connect.py", line 836, in SmartConnect
    sslContext)
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyVim/connect.py", line 718, in __FindSupportedVersion
    sslContext)
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyVim/connect.py", line 638, in __GetServiceVersionDescription
    path + "/vimServiceVersions.xml", sslContext)
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyVim/connect.py", line 604, in __GetElementTree
    conn.request("GET", path)
  File "/usr/lib64/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1227, in connect
    HTTPConnection.connect(self)
  File "/usr/lib64/python2.7/httplib.py", line 807, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known
 
Plugin ini failed: /usr/lib/python2.7/site-packages/awx/plugins/inventory/vmware_inventory.py:10: Error parsing host definition '"""': No closing quotation
```

**Comment by mkempster22** [comment]
I had this the other day, for me it was a typo in the username for the credential I was using. I'd guess it mainly is about incorrect login details then, Unless its a generic error.

It's definitely not the most helpful error, I only knew it was a credential issue as I had just been changing the credentials around

Edit: My specific typo was one too many \\'s after my domain. i.e.  DOMAIN\\\username --> DOMAIN\username

**Comment by Anthonyjmartin** [comment]
I made sure that wasn't the case and the credentials work while using the webpage.

**Comment by mkempster22** [comment]
Coming back to this issue i'm now getting this whilst setting up a different vcenter, the one that worked previously is vmware 6.5, the one not working is 5.5

Could this be an issue with configuring it with 5.5?
@Anthonyjmartin what version was yours? and did you fix the issue?

**Comment by Anthonyjmartin** [comment]
The version I tested against was 6.0. I will check with my VMware guy to
see if we have an instance of 6.5 I can test against.

Anthony Martin

Linux System Administrator

**Comment by mkempster22** [comment]
Ah okay thanks.
Just tried this on our dev AWX and it works fine, seems to definitely be an issue with 5.5 but only on older versions of AWX.

Unfortunately can't upgrade AWX without wiping the database, and that cluster has to be 5.5 so i'm stuck with it

**Comment by AlanCoding** [comment]
This issue isn't quoting the correct error from the output

> socket.gaierror: [Errno -2] Name or service not known

is your error, and other people have already identified the root cause.

The ini error message is because Ansible core tries all available inventory plugins when parsing inventory. This has already been "fixed" in that only the script is enabled for calls to `ansible-inventory` of this type, so that irrelevant message will no longer be given.

**Comment by shanemcd** [comment]
If this is still a problem please open an issue at https://github.com/ansible-collections/community.vmware
