### ISSUE TITLE
cannot access '/var/log/tower/profile/': Permission denied

### ISSUE THREAD

**Issue by TheRealHaoLiu** [ansible/awx#14019]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

bash-4.4$ ls /var/log/tower/profile/
ls: cannot access '/var/log/tower/profile/': Permission denied

unable to access profile for debugging

### AWX version

devel

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

exec into container and do `ls /var/log/tower/profile/`

### Expected results

able to access '/var/log/tower/profile/'

### Actual results

unable to access '/var/log/tower/profile/'

**Comment by shanemcd** [comment]
What code is trying to access that directory?

**Comment by AlanCoding** [comment]
https://github.com/ansible/awx/blob/devel/awx/main/middleware.py#L41

It's used by `TimingMiddleware`

but that `self.dest` seems to be defunct, it calls out to a utils method

https://github.com/ansible/awx/blob/devel/awx/main/utils/profiling.py#L73

I believe that's the functional place we set that location.

**Comment by shanemcd** [comment]
Is that the right place for it? We removed `/var/log/tower` in https://github.com/ansible/awx/commit/6d11003975948855033605624dfe9f6521c963a9. I'd hate to add it back.

**Comment by jsprhssng** [comment]
@shanemcd - I get a similar error when enabling debugging via web ui. AWX web responds 'A server error has occurred.'

Log from the web container shows;

PermissionError: [Errno 13] Permission denied: '/var/log/tower'

**Comment by AlanCoding** [comment]
^ Interesting...

https://github.com/ansible/awx/pull/14211

The error I pasted in that isn't the same as above, but it makes sense that it would be a file-does-not-exist in the awx_devel container, but a Permission denied error in OCP, with both having the same root cause. There was a change some time ago when we had OCP set the environment variable AWX_LOGGING_MODE=stdout. I'm interested to ask if you could check to see if that's absent in your case, and that might explain the problem, which may come from a mismatch of operator/AWX versions.

**Comment by prabhjotbawa** [comment]
I've no clue why the app suddenly stopped working but I'm seeing the a similar error in the awx-web pod.
```
Traceback (most recent call last):
78
File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
79
response = get_response(request)
80
File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
81
response = self.process_response(request, response)
82
File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/middleware.py", line 58, in process_response
83
response['X-API-Profile-File'] = self.prof.stop()
84
File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/utils/profiling.py", line 129, in stop
85
res = self.output_results()
86
File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/utils/profiling.py", line 90, in output_results
87
super().output_results()
88
File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/utils/profiling.py", line 22, in output_results
89
os.makedirs(self.dest)
90
File "/usr/lib64/python3.9/os.py", line 215, in makedirs
91
makedirs(head, exist_ok=exist_ok)
92
File "/usr/lib64/python3.9/os.py", line 225, in makedirs
93
mkdir(name, mode)
94
PermissionError: [Errno 13] Permission denied: '/var/log/tower'
95
2023-07-07 17:28:13,533 ERROR [686d5b6a4fa04b478fc50be5ea43977e] django.request Internal Server Error: /
```

I added AWX_LOGGING_MODE as an environment variable but still see the same error, I've installed the application via the awx operator 2.3.0

**Comment by prabhjotbawa** [comment]
I think there is a bug in the Troubleshooting settings page. At least that was the path that I hit and got stuck with the above error.

I edited the page to set "Debug Web requests" as ON but then started seeing the error
<img width="1296" alt="Screen Shot 2023-07-07 at 3 42 29 PM" src="https://github.com/ansible/awx/assets/42355705/547017f1-7c6c-402b-bf5e-289eac9b9dd5">

I removed the database records for keys AWX_CLEANUP_PATHS, AWX_REQUEST_PROFILE and RECEPTOR_RELEASE_WORK, cleared the web cache and was able to login again.

**Comment by jsprhssng** [comment]
> I think there is a bug in the Troubleshooting settings page. At least that was the path that I hit and got stuck with the above error.
> 
> I edited the page to set "Debug Web requests" as ON but then started seeing the error <img alt="Screen Shot 2023-07-07 at 3 42 29 PM" width="1296" src="https://user-images.githubusercontent.com/42355705/251830770-547017f1-7c6c-402b-bf5e-289eac9b9dd5.png">
> 
> I removed the database records for keys AWX_CLEANUP_PATHS, AWX_REQUEST_PROFILE and RECEPTOR_RELEASE_WORK, cleared the web cache and was able to login again.

Yes i think its a bug too, we had the same error, reported it here https://github.com/ansible/awx-operator/issues/1485

**Comment by janorn** [comment]
Just a short help for us non sql literal
Run this sql on the awx db:
```
DELETE FROM conf_setting
WHERE key = 'AWX_CLEANUP_PATHS';
DELETE FROM conf_setting
WHERE key = 'AWX_REQUEST_PROFILE';
DELETE FROM conf_setting
WHERE key = 'RECEPTOR_RELEASE_WORK';
```
Thanks to @prabhjotbawa for the hint!

**Comment by prabhjotbawa** [comment]
@janorn Thanks for the mention, and also sharing the command to delete those entries, I forgot to mention the name of the table :). We could also remove them in a single command:

`DELETE from conf_setting where key in ('AWX_CLEANUP_PATHS','AWX_REQUEST_PROFILE','RECEPTOR_RELEASE_WORK');`

**Comment by phire-tc** [comment]
This is still present in AWX 24.6.1 (installed with awx-operator-2.19.1):

```
[pid: 19|app: 0|req: 3/17] 10.4.0.20 () {64 vars in 1055 bytes} [Wed Nov 20 16:39:48 2024] GET /api/v2/settings/debug/ => generated 145 bytes in 102 msecs (HTTP/1.1 500) 3 headers in 179 bytes (1 switches on core 0)
10.4.0.20 - - [20/Nov/2024:16:39:49 +0000] "GET /api/v2/settings/debug/ HTTP/1.1" 500 156 "http://awx.opfao.xyz/" "Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0" "10.2.248.6"
10.4.0.13 - - [20/Nov/2024:16:39:53 +0000] "GET /websocket/ HTTP/1.1" 101 405 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0" "10.2.248.6"
2024-11-20 16:39:53,795 ERROR    [1b24e55b6320457287cd3667a02bb8d5] django.request Internal Server Error: /
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/middleware.py", line 58, in process_response
    response['X-API-Profile-File'] = self.prof.stop()
                                     ^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/utils/profiling.py", line 129, in stop
    res = self.output_results()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/utils/profiling.py", line 90, in output_results
    super().output_results()
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/utils/profiling.py", line 22, in output_results
    os.makedirs(self.dest)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/var/log/tower'
2024-11-20 16:39:53,795 ERROR    [1b24e55b6320457287cd3667a02bb8d5] django.request Internal Server Error: /
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/middleware.py", line 58, in process_response
    response['X-API-Profile-File'] = self.prof.stop()
                                     ^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/utils/profiling.py", line 129, in stop
    res = self.output_results()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/utils/profiling.py", line 90, in output_results
    super().output_results()
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/utils/profiling.py", line 22, in output_results
    os.makedirs(self.dest)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/var/log/tower'
[pid: 22|app: 0|req: 4/18] 10.4.0.20 () {64 vars in 1047 bytes} [Wed Nov 20 16:39:53 2024] GET / => generated 3820 bytes in 72 msecs (HTTP/1.1 500) 3 headers in 179 bytes (1 switches on core 0)
10.4.0.20 - - [20/Nov/2024:16:39:53 +0000] "GET / HTTP/1.1" 500 3832 "http://awx.opfao.xyz/" "Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0" "10.2.248.6"
```

**Comment by nlaphine** [comment]
So how do we get out of this then ?
`bash-5.1$ sudo mkdir /var/log/tower

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for awx: 
sudo: a password is required`

I am assuming the awx user was created with no password.

is there something i can put in the values.yml ?
I've tried
`spec:
    initContainers:
      securityContext:
        allowPrivilegeEscalation: true
        runAsUser: 0 
        capabilities:
          add:
            - CAP_SYS_ADMIN
        privileged: true

`
and that hasn't worked, probably cause i have done it wrong.

**Comment by dmzoneill** [comment]
Fixed in `awx/main/utils/profiling.py` and `awx/main/middleware.py`.

**Root cause:** `AWXProfileBase.output_results()` calls `os.makedirs(self.dest)` unconditionally when the destination directory does not exist. In containerized deployments, `/var/log/tower/profile/` and `/var/log/tower/timing/` are not writable, so this raises `PermissionError` on every profiled request when `AWX_REQUEST_PROFILE` is enabled — crashing with a 500 error.

**Fix (three changes):**

1. **`AWXProfileBase.output_results()` in `profiling.py`** — Wrap `os.makedirs()` in `try/except OSError`. On failure, emit a `logger.warning()` via `logging.getLogger('awx.main.utils.profiling')` with a clear message (directory path, OS error, and a hint to check writability or disable `AWX_REQUEST_PROFILE`), then `return False` to signal that output could not be written.

2. **`AWXProfiler.output_results()` in `profiling.py`** — Check the return value of `super().output_results()`. If it's falsy (directory creation failed), return `None` immediately — skipping all subsequent file writes that would also fail with `PermissionError`.

3. **`TimingMiddleware.process_response()` in `middleware.py`** — Only set the `X-API-Profile-File` response header when `prof.stop()` returns a non-`None` path. This prevents a crash when profiling data cannot be persisted.

**Result:** With `AWX_REQUEST_PROFILE=True` and an unwritable `/var/log/tower/profile/`, requests complete normally. A single warning is logged instead of every request crashing with a 500 error. The fix is backward-compatible — when the directory is writable, behaviour is unchanged.

A PR will follow.
