### ISSUE TITLE
AWX 22.3.0 ws_relay doesnt start because of psycopg module missing

### ISSUE THREAD

**Issue by bdoublet91** [ansible/awx#14032]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

When I launch AWX with docker-compose dev deployment, All starting well except a supervisor service:
tower-processes:awx-wsrelay              STARTING  

When I execute the command directly into the awx controler node:
awx-manage run_wsrelay

```yaml
 awx-manage run_wsrelay
Traceback (most recent call last):
  File "/usr/local/bin/awx-manage", line 9, in <module>
    load_entry_point('awx', 'console_scripts', 'awx-manage')()
  File "/awx_devel/awx/__init__.py", line 200, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 275, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 48, in load_command_class
    module = import_module("%s.management.commands.%s" % (app_name, name))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/awx_devel/awx/main/management/commands/run_wsrelay.py", line 19, in <module>
    from awx.main.wsrelay import WebSocketRelayManager
  File "/awx_devel/awx/main/wsrelay.py", line 14, in <module>
    import psycopg
ModuleNotFoundError: No module named 'psycopg'
```

### AWX version

22.3.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

CONTROL_PLANE_NODE_COUNT=2 EXECUTION_NODE_COUNT=3 COMPOSE_TAG=22.3.0 make docker-compose-build
CONTROL_PLANE_NODE_COUNT=2 EXECUTION_NODE_COUNT=3 COMPOSE_TAG=22.3.0 make docker-compose

### Expected results

tower-processes:awx-wsrelay              STARTING  

### Actual results

tower-processes:awx-wsrelay              RUNNING

### Additional information

To fix it, I have installed the psycopg module in awx venv
Execute on all controler node
```
source /var/lib/awx/venv/awx/bin/activate
python3 -m pip install psycopg
supervisorctl -c  /etc/supervisord.conf status
tower-processes:awx-wsrelay              RUNNING   pid 13065, uptime 0:00:25
```

```bash
awx-manage run_wsrelay
2023-05-23 10:19:14,797 INFO     [-] awx.main.wsrelay Active instance with hostname awx_1 is registered.
```

**Comment by shanemcd** [comment]
I think you haven't pulled the latest code. I'm looking at the PR here: https://github.com/ansible/awx/pull/13965/files and can see that line has changed: 

https://github.com/ansible/awx/pull/13965/files#diff-b69d338298e3d06aa13b373c0711acf05d206a7e11b43724b566386f895126aaL14-R14

**Comment by john-westcott-iv** [comment]
wsrelay should now use asyncpg. Like @shanemcd said, I would pull the latest code and then run `make docker-compose-build` and then `make docker-compose` to see if it will come up properly .

**Comment by shanemcd** [comment]
The code is mounted into the container, so as long as you're running the right image + checked out the correct tag, shouldn't need to rebuild when the code itself changes.

**Comment by relrod** [comment]
Going to close this out because it's been two weeks with no update. Please reach out on Matrix or the mailing list if you need further help.
