### ISSUE TITLE
TypeError: add() got an unexpected keyword argument 'through_defaults'

### ISSUE THREAD

**Issue by domq** [ansible/awx#14126]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

AWX's seemingly ancient `awx.main.fields.OrderedManyToManyDescriptor` homemade Django extension is incompatible with Django 2.2 and above. As explained in https://github.com/jazzband/django-taggit/issues/629, overloaded `add()` implementations now need to ferry around an [additional `through_defaults` kwarg](https://docs.djangoproject.com/en/2.2/ref/models/relations/#django.db.models.fields.related.RelatedManager.add).

### AWX version

22.3.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

openshift

### Modifications

yes

### Steps to reproduce

To exhibit the problem, type the following at the `awx-manage shell_plus` prompt:

```
j = JobTemplate(); j.save(); j.instance_groups.set([])
```

### Expected results

Laconic answer or lack thereof

### Actual results

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 1236, in set
    self.add(*new_objs, through_defaults=through_defaults)
TypeError: add() got an unexpected keyword argument 'through_defaults'
```

### Additional information

I have modified the deployment topology, but this is irrelevant as I did not modify the Django code in any way. I am trying to enforce postconditions in the AWX database by means of [`awx_script`](https://github.com/epfl-si/wp-ops/blob/master/ansible/roles/awx-instance/library/awx_script.py) Ansible tasks, which run `awx-manage shell_plus` scripts.

**Comment by domq** [comment]
Workaround: don't use `JobTemplate().instance_groups.set()`, manipulate the `.instance_groups` relation with `.add()` / `.remove()` instead.

**Comment by fosterseth** [comment]
@domq a quick scan doesn't reveal we do the .set() operation in our codebase, so maybe we are good for now. Did you see any errors related to this while running AWX by chance?

**Comment by AlanCoding** [comment]
I have proposed this patch https://github.com/ansible/awx/pull/13950 as a better way to move forward with these fields. @fosterseth is right for the moment. The only functions the API uses of the descriptor are `.add` and `.remove`, and these are the only ones which are "supported" for the custom field. Yes, that means you have to clear _all_ objects and add them back to adjust the order slightly. This is what the UI and collection does.

The point about `through_defaults` is, as one would expect, already noticed and handled correctly in the proposed library

https://github.com/jazzband/django-sortedm2m/blob/ddf321fc9736b9a9477d496c60250270111cf2ce/sortedm2m_tests/test_field.py#L235
