### ISSUE TITLE
awx-manage run_wsrelay Name or service not known

### ISSUE THREAD

**Issue by jollyekb** [ansible/awx#14137]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

when set postgres servers as a list, awx-manage run_wsrelay make error
`2023-06-16 09:45:19,427 INFO     [-] awx.main.wsrelay Active instance with hostname awx-web-754d76b985-jdg7x is registered.
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/__init__.py", line 200, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/management/commands/run_wsrelay.py", line 168, in handle
    asyncio.run(websocket_relay_manager.run())
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/wsrelay.py", line 285, in run
    async_conn = await asyncpg.connect(
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/asyncpg/connection.py", line 2092, in connect
    return await connect_utils._connect(
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/asyncpg/connect_utils.py", line 895, in _connect
    raise last_error
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/asyncpg/connect_utils.py", line 881, in _connect
    return await _connect_addr(
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/asyncpg/connect_utils.py", line 773, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/asyncpg/connect_utils.py", line 825, in __connect_addr
    tr, pr = await compat.wait_for(connector, timeout=timeout)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/asyncpg/compat.py", line 56, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/usr/lib64/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/asyncpg/connect_utils.py", line 684, in _create_ssl_connection
    tr, pr = await loop.create_connection(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1026, in create_connection
    infos = await self._ensure_resolved(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1405, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 861, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib64/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known`

/etc/tower/conf.d/credentials.py
`DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'awx.main.db.profiled_pg',
        'NAME': "awx",
        'USER': "awx",
        'PASSWORD': "VeryH@rdP@$$,
        'HOST': 'server1.dev.local,server2.dev.local,server3.dev.local',
        'PORT': "5432",
        'OPTIONS': { 'sslmode': 'disable',
                     'keepalives': 1,
                     'keepalives_idle': 5,
                     'keepalives_interval': 5,
                     'keepalives_count': 5,
        },
    }
}

BROADCAST_WEBSOCKET_SECRET = "somesecret"`

### AWX version

22.3.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

set list of servers postgresql

### Expected results

working well

### Actual results

Pod awx-task crushing

**Comment by djyasin** [comment]
Hello @jollyekb,
We are sorry to hear you're having difficulty! If you try limiting the `HOST` to one server, does it resolve the issue for you? If not, please let us know!
