### ISSUE TITLE
Cleanup Job failed: Value must be an integer.

### ISSUE THREAD

**Issue by andy812** [ansible/awx#14169]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Cleanup Job does not work, the error is:
Traceback (most recent call last):
```
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.InvalidDatetimeFormat: invalid value "defa" for "YYYY"
DETAIL:  Value must be an integer.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/__init__.py", line 200, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
    return self.cleanup(Job)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/management/commands/cleanup_jobs.py", line 175, in cleanup
    skipped, deleted = delete_meta.delete()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/management/commands/cleanup_jobs.py", line 140, in delete
    self.find_partitions_to_drop()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/management/commands/cleanup_jobs.py", line 109, in find_partitions_to_drop
    cursor.execute(query)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
django.db.utils.DataError: invalid value "defa" for "YYYY"
DETAIL:  Value must be an integer.
```

I've got AWX installed by awx-operator.

### AWX version

22.3.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

1. Run Cleanup Job
2. Get error

### Expected results

Cleanup Job executed successfully

### Actual results

Cleanup Job failed

**Comment by fosterseth** [comment]
@andy812 can you provide the api endpoint for that manage job? i.e. `api/v2/system_jobs/<systemjobid>`

**Comment by andy812** [comment]
> @andy812 can you provide the api endpoint for that manage job? i.e. `api/v2/system_jobs/<systemjobid>`

<img width="516" alt="изображение" src="https://github.com/ansible/awx/assets/29895539/d71a1b98-27ca-4fbf-9172-83978d677df4">

**Comment by fosterseth** [comment]
@andy812 in your browser you should be able to navigate to https://awx-url/api/v2/system_jobs/282949

can you copy and paste the info from that api page?
