### ISSUE TITLE
ERROR! Unexpected Exception, this is probably a bug: Cannot call rmtree on a symbolic link 

### ISSUE THREAD

**Issue by djyasin** [ansible/awx#14284]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Cannot run `make docker-compose` to spin up devel environment if a symlink exists. This can be fixed by manually removing the symlink, but it is not a desirable work flow.

Set up:

Traceback:
`Traceback (most recent call last):
  File "/home/alancoding/repos/ansible/lib/ansible/cli/__init__.py", line 659, in cli_executor
    exit_code = cli.run()
                ^^^^^^^^^
  File "/home/alancoding/repos/ansible/lib/ansible/cli/galaxy.py", line 736, in run
    return context.CLIARGS['func']()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/ansible/lib/ansible/cli/galaxy.py", line 118, in method_wrapper
    return wrapped_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/ansible/lib/ansible/cli/galaxy.py", line 1390, in execute_install
    self._execute_install_collection(
  File "/home/alancoding/repos/ansible/lib/ansible/cli/galaxy.py", line 1439, in _execute_install_collection
    install_collections(
  File "/home/alancoding/repos/ansible/lib/ansible/galaxy/collection/__init__.py", line 771, in install_collections
    install(concrete_coll_pin, output_path, artifacts_manager)
  File "/home/alancoding/repos/ansible/lib/ansible/galaxy/collection/__init__.py", line 1493, in install
    shutil.rmtree(b_collection_path)
  File "/usr/lib64/python3.11/shutil.py", line 744, in rmtree
    onerror(os.path.islink, path, sys.exc_info())
  File "/usr/lib64/python3.11/shutil.py", line 742, in rmtree
    raise OSError("Cannot call rmtree on a symbolic link")
OSError: Cannot call rmtree on a symbolic link`

### AWX version

22.5.1

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [X] Other

### Installation method

docker development environment

### Modifications

no

### Steps to reproduce

- Create a symlink. This can be done via $ `make symlink_collection`
- Run `make docker-compose`

You will then see the following error: 

ERROR! Unexpected Exception, this is probably a bug: Cannot call rmtree on a symbolic link 

### Expected results

Successful docker dev environment

### Actual results

Encounter this message: `ERROR! Unexpected Exception, this is probably a bug: Cannot call rmtree on a symbolic link `

**Comment by djyasin** [comment]
Opened new issue in the Ansible Core repo: https://github.com/ansible/ansible/issues/81350
