### ISSUE TITLE
New UI no longer works in 22.7.0

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#14345]
### Please confirm the following

- [x] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

When trying to open new UI I get server error, this is what I see in logs of awx-web:

```
2023-08-16 09:59:23,079 ERROR    [7a31d03635de4ad08da2f897ddf30781] django.request Internal Server Error: /ui_next/dashboard
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index_awx.html
2023-08-16 09:59:23,079 ERROR    [7a31d03635de4ad08da2f897ddf30781] django.request Internal Server Error: /ui_next/dashboard
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index_awx.html
```

### AWX version

22.7.0

### Select the relevant components

- [ ] UI
- [X] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

minikube

### Modifications

no

### Operating system

OL9

### Steps to reproduce

Install AWX 22.7.0, open new UI

### Expected results

New UI works

### Actual results

UI doesn't work

**Comment by jamestalton** [comment]
The Ansible-UI repo has undergone changes needed.
We need to discuss how AWX is going to be hosting the standalone UI going forward.

**Comment by mabashian** [comment]
linking https://github.com/ansible/ansible-ui/pull/766

**Comment by TheRealHaoLiu** [comment]
https://github.com/ansible/ansible-ui/pull/766/files#diff-2606df06d89b38ff979770f810c3c269083e7c0fbafb27aba7f9ea0297179828L128-R157 this seems to be causing some problem...
