### ISSUE TITLE
enable debug in troubleshoot setting breaks the UI

### ISSUE THREAD

**Issue by Sam-su2060** [ansible/awx#14374]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hello,

After enabling debug under troubleshoot settings I got the following: 
```
Server Error
A server error has occurred.
```
And the following error logs from awx-web container:
 `PermissionError: [Errno 13] Permission denied: '/var/log/tower'`

Thanks, 

### AWX version

22.7.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

enable debug under troubleshoot settings.

### Expected results

continue to use UI

### Actual results

[Untitled.pdf](https://github.com/ansible/awx/files/12421778/Untitled.pdf)

**Comment by djyasin** [comment]
We were able to reproduce this issue in both docker and kube.

**Comment by marshmalien** [comment]
This issue is likely not related to the UI. For those looking to reproduce, here is the toggle in question: 
<img width="936" alt="Screenshot 2023-08-30 at 12 19 03 PM" src="https://github.com/ansible/awx/assets/15881645/2b58b846-b3b9-4db9-b0e5-0c399239ca8b">
```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "/awx_devel/./awx/main/middleware.py", line 58, in process_response
    response['X-API-Profile-File'] = self.prof.stop()
  File "/awx_devel/./awx/main/utils/profiling.py", line 129, in stop
    res = self.output_results()
  File "/awx_devel/./awx/main/utils/profiling.py", line 90, in output_results
    super().output_results()
  File "/awx_devel/./awx/main/utils/profiling.py", line 22, in output_results
    os.makedirs(self.dest)
  File "/usr/lib64/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib64/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)

Exception Type: PermissionError at /api/v2/
Exception Value: [Errno 13] Permission denied: '/var/log/tower'
```
