### ISSUE TITLE
awx.awx.schedule -  Specifying unified_job_template as ID doesn't work

### ISSUE THREAD

**Issue by pluto00987** [ansible/awx#14458]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Per the [docs](https://docs.ansible.com/ansible/latest/collections/awx/awx/schedule_module.html#parameter-unified_job_template), the unified_job_template parameter can be specified as a Name, ID, or URL. However, specifying an ID thrown an exception in collection versions >19.2.2.

I believe the problem is caused by this change https://github.com/ansible/awx/pull/11135/files#diff-51b779436b7298bec9ef390eb72bb99b2d67c558757579c931908a1aa8d7662bL196 

### AWX version

21.14.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Steps to reproduce

Try scheduling a job using the job template ID as such:

```
    - name: Test schedule job w/ ID
      vars:
        start_time: "2025-04-03 12:02:14"
      awx.awx.schedule:
        name: "Test w/ ID"
        unified_job_template: '30'
        rrule: "{{ query('awx.awx.schedule_rrule', 'minute', start_date=start_time, timezone='UTC', every='1', end_on='1') }}"
```

### Expected results

The job should be scheduled

### Actual results

  "exception": "Traceback (most recent call last):\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1695053652.058952-44-236635489272730/AnsiballZ_schedule.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1695053652.058952-44-236635489272730/AnsiballZ_schedule.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1695053652.058952-44-236635489272730/AnsiballZ_schedule.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.awx.awx.plugins.modules.schedule', init_globals=dict(_module_fqn='ansible_collections.awx.awx.plugins.modules.schedule', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_awx.awx.schedule_payload_tnadnbuu/ansible_awx.awx.schedule_payload.zip/ansible_collections/awx/awx/plugins/modules/schedule.py\", line 362, in <module>\n  File \"/tmp/ansible_awx.awx.schedule_payload_tnadnbuu/ansible_awx.awx.schedule_payload.zip/ansible_collections/awx/awx/plugins/modules/schedule.py\", line 266, in main\nTypeError: 'NoneType' object is not subscriptable\n",

### Additional information

Tested with collection versions 19.4.0 and 23.1.0 with the same result (line number in exception differ though). 'Actual results' were from version 23.1.0 (ie latest)

Specifying the job template by name, rather than ID, works as expected.

**Comment by AlanCoding** [comment]
Reformatting the traceback:

```
Traceback (most recent call last):
 File "/home/runner/.ansible/tmp/ansible-tmp-1695053652.058952-44-236635489272730/AnsiballZ_schedule.py", line 107, in 
    _ansiballz_main()
 File "/home/runner/.ansible/tmp/ansible-tmp-1695053652.058952-44-236635489272730/AnsiballZ_schedule.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
 File "/home/runner/.ansible/tmp/ansible-tmp-1695053652.058952-44-236635489272730/AnsiballZ_schedule.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.awx.awx.plugins.modules.schedule', init_globals=dict(_module_fqn='ansible_collections.awx.awx.plugins.modules.schedule', _modlib_path=modlib_path),
 File "/usr/lib64/python3.9/runpy.py", line 225, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
 File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
 File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
 File "/tmp/ansible_awx.awx.schedule_payload_tnadnbuu/ansible_awx.awx.schedule_payload.zip/ansible_collections/awx/awx/plugins/modules/schedule.py", line 362, in 
 File "/tmp/ansible_awx.awx.schedule_payload_tnadnbuu/ansible_awx.awx.schedule_payload.zip/ansible_collections/awx/awx/plugins/modules/schedule.py", line 266, in main
TypeError: 'NoneType' object is not subscriptable
```

It doesn't give line numbers within the module (due to being a zip file) but the line numbers of 362 and 266 should be enough.

https://github.com/ansible/awx/blob/1f91773a3c70aeac62c809c6c317c88b30efc25a/awx_collection/plugins/modules/schedule.py#L362

However, these line numbers are invalid for the version 21.14.0

Can we get the version of the _collection_ you're using? The commit you mention 75a873079de5158af21eed1f7be0700b8e95f70d also doesn't have these line numbers.

Current devel, as of this comment, would give

https://github.com/ansible/awx/blob/1f91773a3c70aeac62c809c6c317c88b30efc25a/awx_collection/plugins/modules/schedule.py#L362

https://github.com/ansible/awx/blob/1f91773a3c70aeac62c809c6c317c88b30efc25a/awx_collection/plugins/modules/schedule.py#L266

This 266 line could be consistent with the exception type of `None['id']`.

**Comment by pluto00987** [comment]
@AlanCoding I mentioned versions in 'additional information' but it was a bit ambiguous overall..
To clarify, it works as expected with collection version 19.2.2. I does not work with collection 19.4.0 (I don't think there was a 19.3.0 collection released?). The change I mentioned is from 19.4.0.
It also doesn't work with collection 23.1.0 (latest). It produces the same exception/error, though the line numbers differ due to other changes in the file. The exception I pasted is from that version.
The 21.14.0 is the server version, but mentioning that probably only confused things :)

**Comment by AlanCoding** [comment]
I'm fairly sure this is going to be easy to address. It will be a while before we get around to it, but you could try. You can start by adding a task to the schedule tests:

https://github.com/ansible/awx/blob/devel/awx_collection/tests/integration/targets/schedule/tasks/main.yml

These will run in the checks, so no concern about getting it wrong.

There are plenty of ways to run the content, and I put some hacky instructions here:

https://github.com/ansible/awx/blob/devel/awx_collection/tools/README.md

**Comment by AlanCoding** [comment]
I got a tip that the same behavior has been observed with the `workflow_job_template_node` module. Since these both have the `unified_job_template` option, I highly suspect it's the same pattern of error, and I'd like to get them both addressed together.

**Comment by pluto00987** [comment]
@AlanCoding It seems that the underlying issue (using ID for `unified_job_template`) in `workflow_job_template_name` was addressed in #11198. After banging on this issue some today the fix I ended up with for the `schedule` module was basically the same as that one.

I didn't look at adding or modifying test cases. I'm not sure when I'll have time to do that.
