### ISSUE TITLE
 django.security.csrf Forbidden

### ISSUE THREAD

**Issue by 71Imapla** [ansible/awx#14467]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

I am seeing the following error when attempting to logn just after I updated my awx-operator version to 2.5.3 ( AWX version: 23.1.0):

```
[20/Sep/2023:05:52:11 +0000] "GET /api/login/ HTTP/1.1" 200 5763 "https://prod-ansible-awx.devnull.org/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.31" 
[pid: 39|app: 0|req: 183/701] () {64 vars in 1170 bytes} [Wed Sep 20 05:52:11 2023] GET /api/login/ => generated 5763 bytes in 130 msecs (HTTP/1.1 200) 10 headers in 460 bytes (1 switches on core 0)
2023-09-20 05:52:11,585 WARNING  [c6efd6a7ec4246049090120182e04f69] django.request Bad Request: /
2023-09-20 05:52:11,585 WARNING  [c6efd6a7ec4246049090120182e04f69] django.request Bad Request: /
[pid: 37|app: 0|req: 31/702] 10.39.8.0 () {28 vars in 287 bytes} [Wed Sep 20 05:52:11 2023] GET / => generated 3872 bytes in 110 msecs ( 400) 6 headers in 248 bytes (1 switches on core 0)
20/Sep/2023:05:52:11 +0000] "GET /" 400 3872 "-" "-" "-"
2023-09-20 05:52:11,738 WARNING  [e9d424511f904fd1ac2020950ed03963] django.security.csrf Forbidden (Origin checking failed - https://prod-ansible-awx.devnull.org does not match any trusted origins.): /api/login/
[20/Sep/2023:05:52:11 +0000] "POST /api/login/ HTTP/1.1" 403 1019 "https://prod-ansible-awx.devnull.org/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.31" 
```

I am getting an error message on the UI - "There was a problem logging in. Please try again" as well. 

Note that this works perfectly in my lab and dev environments.  Here is what I captured when logging in on my lab environment:

```
[20/Sep/2023:06:04:21 +0000] "GET /" 400 3872 "-" "-" "-"
[20/Sep/2023:06:04:21 +0000] "GET /api/login/ HTTP/1.1" 200 5763 "https://lab-ansible-awx.devnull.org/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.31" 
[pid: 5744|app: 0|req: 689/1121017] () {66 vars in 1197 bytes} [Wed Sep 20 06:04:20 2023] GET /api/login/ => generated 5763 bytes in 309 msecs (HTTP/1.1 200) 10 headers in 460 bytes (1 switches on core 0)
2023-09-20 06:04:21,748 INFO     [3816f2ed1b214e3ba69972e45999def0] awx.api.generics User logged in 
```

Note that these environments are on different K8s clusters.

### AWX version

23.1.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.14

### Operating system

Ubuntu 20.04 LTS in DEV / PROD, Oracle Linux 8 in LAB

### Web browser

Edge

### Steps to reproduce

I used the exact same steps to update my lab, dev, and prod environment.  They are different k8s clusters, and awx is using different namespaces in each. 

Update AWX operator to 2.5.3

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=2.5.3

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.5.3

# Specify a custom namespace in which to install AWX
namespace: prodawx
```

### Expected results

Able to login without csrf causing issues.

### Actual results

UI reports login "There was a problem logging in. Please try again"

```
[20/Sep/2023:05:52:11 +0000] "GET /api/login/ HTTP/1.1" 200 5763 "https://prod-ansible-awx.devnull.org/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.31" 
[pid: 39|app: 0|req: 183/701] () {64 vars in 1170 bytes} [Wed Sep 20 05:52:11 2023] GET /api/login/ => generated 5763 bytes in 130 msecs (HTTP/1.1 200) 10 headers in 460 bytes (1 switches on core 0)
2023-09-20 05:52:11,585 WARNING  [c6efd6a7ec4246049090120182e04f69] django.request Bad Request: /
2023-09-20 05:52:11,585 WARNING  [c6efd6a7ec4246049090120182e04f69] django.request Bad Request: /
[pid: 37|app: 0|req: 31/702] 10.39.8.0 () {28 vars in 287 bytes} [Wed Sep 20 05:52:11 2023] GET / => generated 3872 bytes in 110 msecs ( 400) 6 headers in 248 bytes (1 switches on core 0)
20/Sep/2023:05:52:11 +0000] "GET /" 400 3872 "-" "-" "-"
2023-09-20 05:52:11,738 WARNING  [e9d424511f904fd1ac2020950ed03963] django.security.csrf Forbidden (Origin checking failed - https://prod-ansible-awx.devnull.org does not match any trusted origins.): /api/login/
[20/Sep/2023:05:52:11 +0000] "POST /api/login/ HTTP/1.1" 403 1019 "https://prod-ansible-awx.devnull.org/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.31" 
```

### Additional information

Note I also noticed that this particular error is showing on all of my environments, and is VERY noisy (repeats fequently(:

```
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '_:443'. The domain name provided is not valid according to RFC 1034/1035.
2023-09-20 05:51:27,724 WARNING  [5f4bfebd318a4d329acf0df9264cfca3] django.request Bad Request: /
2023-09-20 05:51:27,724 WARNING  [5f4bfebd318a4d329acf0df9264cfca3] django.request Bad Request: /
[pid: 38|app: 0|req: 291/569] 10.39.6.0 () {28 vars in 287 bytes} [Wed Sep 20 05:51:27 2023] GET / => generated 3872 bytes in 118 msecs ( 400) 6 headers in 248 bytes (1 switches on core 0)
[20/Sep/2023:05:51:27 +0000] "GET /" 400 3872 "-" "-" "-"
2023-09-20 05:51:28,159 ERROR    [9a1acfe684b644b793cfd15a58a8fce0] django.security.DisallowedHost Invalid HTTP_HOST header: '_:443'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '_:443'. The domain name provided is not valid according to RFC 1034/1035.
2023-09-20 05:51:28,163 WARNING  [9a1acfe684b644b793cfd15a58a8fce0] django.request Bad Request: /
2023-09-20 05:51:28,163 WARNING  [9a1acfe684b644b793cfd15a58a8fce0] django.request Bad Request: /
[pid: 35|app: 0|req: 61/570] () {28 vars in 287 bytes} [Wed Sep 20 05:51:28 2023] GET / => generated 3872 bytes in 123 msecs ( 400) 6 headers in 248 bytes (1 switches on core 0)
10.39.4.0 - - [20/Sep/2023:05:51:28 +0000] "GET /" 400 3872 "-" "-" "-"
2023-09-20 05:51:28,176 ERROR    [f8b738d079e146fba3be1d1ae6637454] django.security.DisallowedHost Invalid HTTP_HOST header: '_:443'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '_:443'. The domain name provided is not valid according to RFC 1034/1035.
2023-09-20 05:51:28,181 WARNING  [f8b738d079e146fba3be1d1ae6637454] django.request Bad Request: /
2023-09-20 05:51:28,181 WARNING  [f8b738d079e146fba3be1d1ae6637454] django.request Bad Request: /
```

**Comment by 71Imapla** [comment]
I have reverted back to AWX 21.10.2 (operator version 1.1.3) -- and my Production instance is once again happy. However, I would like to upgrade it to operator version 2.5.3 / awx version 23.1.0 asap, so my environments have matching versions.

**Comment by fosterseth** [comment]
django 4 made some changes around this, please see this solution here https://github.com/ansible/awx/issues/14024#issuecomment-1650090658

**Comment by fosterseth** [comment]
closing due to inactivity, please open a new issue if you are still experiencing a problem around this

**Comment by 71Imapla** [comment]
@fosterseth -- Thank you for the awesome information. I was able to upgrade to AWX 23.1.0 / operator version 2.5.3 tonight with the added details that were linked above.
