### ISSUE TITLE
Instance Install Bundle Server Error

### ISSUE THREAD

**Issue by gseyerl** [ansible/awx#14632]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hi,
thanks for the work on AWX, appreciate your work.

The install bundle download worked for me using an older version of AWX at some point.

Now, we run AWX Version 23.0.3

I followed the documentation here (https://github.com/ansible/awx/blob/devel/docs/execution_nodes.md)

If I try to download the install bundle from a freshly created instance, I get the following error:

```
2023-11-06 12:44:33,552 ERROR    [10e0b1c47d664bc585fab2e421f9fbe1] django.request Internal Server Error: /api/v2/instances/43/install_bundle/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/api/generics.py", line 332, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/api/views/instance_install_bundle.py", line 65, in get
    tar.add(os.path.realpath('/etc/receptor/tls/ca/mesh-CA.crt'), arcname=f"{instance_obj.hostname}_install_bundle/receptor/tls/ca/mesh-CA.crt")
  File "/usr/lib64/python3.9/tarfile.py", line 2157, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/lib64/python3.9/tarfile.py", line 2030, in gettarinfo
    statres = os.lstat(name)
FileNotFoundError: [Errno 2] No such file or directory: '/etc/receptor/tls/ca/mesh-CA.crt'

2023-11-06 12:44:33,552 ERROR    [10e0b1c47d664bc585fab2e421f9fbe1] django.request Internal Server Error: /api/v2/instances/43/install_bundle/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/api/generics.py", line 332, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/api/views/instance_install_bundle.py", line 65, in get
    tar.add(os.path.realpath('/etc/receptor/tls/ca/mesh-CA.crt'), arcname=f"{instance_obj.hostname}_install_bundle/receptor/tls/ca/mesh-CA.crt")
  File "/usr/lib64/python3.9/tarfile.py", line 2157, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/lib64/python3.9/tarfile.py", line 2030, in gettarinfo
    statres = os.lstat(name)
FileNotFoundError: [Errno 2] No such file or directory: '/etc/receptor/tls/ca/mesh-CA.crt'
```

Thank you already.
Ciao
G

### AWX version

23.0.3

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.15.5

### Steps to reproduce

Add new instance.

Try to download the install Bundle.

### Expected results

Download of install bundle tar

### Actual results

HTTP 500:
A server error has occurred

**Comment by fosterseth** [comment]
can you provide the output of

`kubectl get deployment <web-deployment-name> -o yaml` (most like `awx-web`)

to get deployment name you can run `kubectl get deploy`

**Comment by gseyerl** [comment]
Hi,
thank you and sorry for the delay.

Thanks for pointing me into the right direction.

Actually, we have a company proxy policy and therefore, we have to use a local container registry. The AWX version was more recent than the operator version and the old configmap/deployment did not work for this AWX version.

We recreated all objects with the newest operator version and it works now.

Sorry for the wrong issue.

G
