### ISSUE TITLE
Grafana Notification is not working.

### ISSUE THREAD

**Issue by learnwithvikasjha** [ansible/awx#14675]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Notification Configuration:
![image](https://github.com/ansible/awx/assets/123352775/32988151-8df8-4270-8102-60532484cec4)

**Error Logs of awx_task:** 

2023-11-18 16:40:43,959 DEBUG    awx.main.dispatch task 1d09d510-7c48-4b5f-b8be-9f59af200e32 starting awx.main.tasks.send_notifications(*[[43]])
2023-11-18 16:40:44,087 ERROR    awx.main.notifications.grafana_backend Error sending notification grafana: 400
2023-11-18 16:40:44,088 ERROR    awx.main.tasks Send Notification Failed Error sending notification grafana: 400
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 336, in send_notifications
    sent = notification.notification_template.send(notification.subject, notification.body)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/notifications.py", line 194, in send
    return backend_obj.send_messages([notification_obj])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/notifications/grafana_backend.py", line 99, in send_messages
    raise Exception(smart_text(_("Error sending notification grafana: {}").format(r.status_code)))
Exception: Error sending notification grafana: 400
You have new mail in /var/spool/mail/root

### AWX version

AWX 17.1.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Operating system

centos

### Web browser

Chrome

### Steps to reproduce

1. Go to AWX Notification.
- Give a name: "alert to grafana"
- Description is blank
- Organization: Default
- Type: Grafana

2. Type Details:
- Grafana URL: Provide Grafana URL
- Grafana API key: Provide Grafana Service Account Token. Please note this service account token as admin privileges in Grafana.
- ID of the dashboard (optional): Left it blank
- ID of the panel (optional): Left it blank
- Tags for the annotation: ansible

### Expected results

Grafana annotation creation.

### Actual results

2023-11-18 16:40:43,049 DEBUG    awx.main.dispatch task 92d16647-28b7-49c2-8a1c-779c2d71ac9b starting awx.main.tasks.handle_work_success(*[])
2023-11-18 16:40:43,066 DEBUG    awx.main.dispatch task 050a0207-f36b-4276-9a63-8da9fa5bf8ff starting awx.main.scheduler.tasks.run_task_manager(*[])
2023-11-18 16:40:43,072 DEBUG    awx.main.scheduler Running Tower task manager.
2023-11-18 16:40:43,079 DEBUG    awx.main.scheduler Starting Scheduler
2023-11-18 16:40:43,105 DEBUG    awx.main.scheduler Finishing Scheduler
2023-11-18 16:40:43,959 DEBUG    awx.main.dispatch task 1d09d510-7c48-4b5f-b8be-9f59af200e32 starting awx.main.tasks.send_notifications(*[[43]])
2023-11-18 16:40:44,087 ERROR    awx.main.notifications.grafana_backend Error sending notification grafana: 400
2023-11-18 16:40:44,088 ERROR    awx.main.tasks Send Notification Failed Error sending notification grafana: 400
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 336, in send_notifications
    sent = notification.notification_template.send(notification.subject, notification.body)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/notifications.py", line 194, in send
    return backend_obj.send_messages([notification_obj])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/notifications/grafana_backend.py", line 99, in send_messages
    raise Exception(smart_text(_("Error sending notification grafana: {}").format(r.status_code)))
Exception: Error sending notification grafana: 400

**Comment by dmzoneill** [comment]
hi @learnwithvikasjha 

Thanks for your bug report.
I've done an investigation and concluded this is frustrating ;).
With relation to the 4XX you are getting, I'm going to need some more information.

Firstly, here is my deployment setup:

```
rm -rvf awx
git clone git@github.com:ansible/awx.git
cd awx
make docker-clean
make clean
make docker-clean-volumes
docker system prune -af
make docker-compose-build
make docker-compose
mkdir grafana
cd grafana 
mkdir grafana
docker run -d -p 6000:3000 --name=grafana grafana/grafana-enterprise
```

Note* once you run Grafana for the first time, you can copy these files out with docker cp.
The reason for copying them out is that the port 3000 conflicts with awx.
So we need to put Grafana on some other port

```

docker cp grafana:/usr/share/grafana/conf .

[daoneill@fedora grafana]$ tree
.
├── conf
│   ├── defaults.ini
│   ├── ldap_multiple.toml
│   ├── ldap.toml
│   ├── provisioning
│   │   ├── access-control
│   │   │   └── sample.yaml
│   │   ├── alerting
│   │   │   └── sample.yaml
│   │   ├── dashboards
│   │   │   └── sample.yaml
│   │   ├── datasources
│   │   │   └── sample.yaml
│   │   ├── notifiers
│   │   │   └── sample.yaml
│   │   └── plugins
│   │       └── sample.yaml
│   └── sample.ini
├── grafana

14 directories, 12 files
```

Change the grafana port
```
grep 6000 conf/defaults.ini 
http_port = 6000
```

Re-run the grafana container using the mounts
```
docker run -d -v /home/daoneill/src/awx/grafana/conf:/usr/share/grafana/conf -v /home/daoneill/src/awx/grafana/grafana:/var/lib/grafana -p 6000:6000 --name=grafana grafana/grafana-enterprise
```

Could you kindly apply the patch to your local environment with:
https://github.com/ansible/awx/pull/14802

And get the error in the output, when you hit "test" on the Grafana notifier page

```
docker logs awx_tools_1
```

I was successfully able to fix the issue by determining I need to make some changes to Grafana.
As we don't know what the error is on your end yet, we will need this debug output to proceed.

![image](https://github.com/ansible/awx/assets/15192260/af78e16e-1801-418f-a53d-a5731b00dffb)

**Comment by dmzoneill** [comment]
Closing this issue due to inactivity.

**Summary of what happened:**

- This issue was reported against AWX **17.1.0**, which is now end-of-life and no longer supported.
- The issue was investigated in January 2024. A full Grafana test environment was set up and working notifications were successfully reproduced, suggesting the problem may be environment- or version-specific.
- PR #14802 was opened to add debug logging to the Grafana notifier to help diagnose the HTTP 400 error.
- The reporter was asked to apply the debug patch and share the resulting logs — **there has been no response in over 18 months**.

**If you are still experiencing this issue on a current, supported version of AWX:**

Please reopen this issue (or open a new one) and include:
1. Your AWX version (please use a [currently supported release](https://github.com/ansible/awx/releases))
2. Debug logs from the Grafana notification path
3. The full error response from Grafana if available

Thank you for your report.
