### ISSUE TITLE
Job stuck in "Running" state while all other jobs stuck in "Pending"

### ISSUE THREAD

**Issue by dangoncalves** [ansible/awx#14729]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

I experienced a bug in AWX that is a little bit strange: we had just one job stuck in "Running" state while all other jobs were stuck in "Pending". Cancelling the running job broke the deadlock and everything returned to a normal situation.

After analyzing the logs, I found this stacktrace:
```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 173, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'last_job'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/task.py", line 102, in perform_work
    result = self.run_callable(body)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/task.py", line 77, in run_callable
    return _call(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/tasks.py", line 25, in task_manager
    run_manager(TaskManager, "task")
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/tasks.py", line 20, in run_manager
    manager().schedule()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/task_manager.py", line 136, in schedule
    self._schedule()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/task_manager.py", line 57, in inner
    result = func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/task_manager.py", line 741, in _schedule
    self.process_tasks()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/task_manager.py", line 710, in process_tasks
    self.process_pending_tasks(pending_tasks)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/task_manager.py", line 57, in inner
    result = func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/task_manager.py", line 641, in process_pending_tasks
    self.start_task(task, instance_group, None)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/task_manager.py", line 57, in inner
    result = func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/scheduler/task_manager.py", line 552, in start_task
    task.save()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/models/unified_jobs.py", line 916, in save
    self._update_parent_instance()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/models/unified_jobs.py", line 834, in _update_parent_instance
    parent_instance.save(update_fields=update_fields)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/models/jobs.py", line 359, in save
    return super(JobTemplate, self).save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/models/unified_jobs.py", line 276, in save
    updated_fields = self._set_status_and_last_job_run(save=False)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/models/unified_jobs.py", line 301, in _set_status_and_last_job_run
    last_job_run = self._get_last_job_run()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/models/unified_jobs.py", line 296, in _get_last_job_run
    if self.last_job:
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 187, in __get__
    rel_obj = self.get_object(instance)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 154, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
awx.main.models.unified_jobs.UnifiedJob.DoesNotExist: UnifiedJob matching query does not exist.
```
After looking at existing issues, I found [this one that may be related](https://github.com/ansible/awx/issues/13512) and [this PR that is still a draft](https://github.com/ansible/awx/pull/13553)

### AWX version

21.13.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Not sure it's a good way to reproduce, but before having this situation we updated the related project and launched the stuck job.

### Expected results

All jobs should be executed as expected, especially going from "pending" to "running" state.

### Actual results

After updating the project, the job stuck in running state and blocks all other jobs.

### Additional information

Just to clarify one thing: the stuck "running" job is not the syncing project job, but a manually launched job.

**Comment by djyasin** [comment]
@dangoncalves would you be able to provide us with detailed steps to reproduce this issue? This will better enable us to understand what may be occurring. Thank you for your time!

**Comment by AlanCoding** [comment]
> Not sure it's a good way to reproduce, but before having this situation we updated the related project and launched the stuck job.

This is relevant, but not enough to reproduce yet. From your traceback, we have `self.start_task(task, instance_group, None)`. That means that we have a job which runs in a container_group (which I would expect). Importantly, this means that _that job_ is what produced the error with the exploding attribute.

What kind of details do you have for the project update? Did it create a related project update? What are the details of that? Is it in pending?

It wouldn't quite add up that the project update (created by update-on-launch) is in pending. The project update should be a hard blocker for the job, so the task manager shouldn't be calling `self.start_task` for that job (from the tb), because it is blocked. The project update could contain some hints about what went wrong.

**Comment by dangoncalves** [comment]
Hello @AlanCoding,

thanks for your reply and your insights. Unfortunately I wasn't able to reproduce this issue but I can tell you that the project update was created at 3:56:01 PM, started at 3:56:02 PM and finished at 3:56:27 PM. The project has no update-on-launch option but clean and delete options. I found nothing relevant in logs, but I let you look if you find something interessant:

```
Identity added: /tmp/awx_12550259_kly6w83r/artifacts/12550259/ssh_key_data (matthew@laptop-2.local)

PLAY [Update source tree if necessary] *****************************************

TASK [Delete project directory before update] **********************************
changed: [localhost]

TASK [Update project using git] ************************************************
changed: [localhost]

TASK [Set the git repository version] ******************************************
ok: [localhost]

TASK [Repository Version] ******************************************************
ok: [localhost] => {
    "msg": "Repository Version c832da242ea4500190e6b65c42e114c954a6d3e7"
}

PLAY [Perform project signature/checksum verification] *************************

PLAY [Install content with ansible-galaxy command if necessary] ****************

TASK [Warn about disabled content sync] ****************************************
skipping: [localhost]

TASK [End play due to disabled content sync] ***********************************
skipping: [localhost]

TASK [Fetch galaxy roles from requirements.(yml/yaml)] *************************
[WARNING]: Unable to find '/var/lib/awx/projects/_5970__gtdp_ops_automation_pla
ybook_preprod_1126512651_am/roles' in expected paths (use -vvvvv to see paths)
skipping: [localhost]

TASK [Fetch galaxy collections from collections/requirements.(yml/yaml)] *******
changed: [localhost] => (item=/var/lib/awx/projects/_5970__gtdp_ops_automation_playbook_preprod_1126512651_am/collections/requirements.yml)

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=3    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
```

Worth noting that the stuck job (which was not the project update) was in running state but has not start time: created at 3:58:19 PM and finished (cancelled) at 4:19:46 PM. Moreover, this job has no controller node nor container group.

I Hope this will help.

**Comment by thedoubl3j** [comment]
hey @dangoncalves have you been able to reliably reproduce this? if so, can you test out https://github.com/ansible/awx/pull/13553 and see if it helps?

**Comment by thedoubl3j** [comment]
@dangoncalves were you able to test out the draft PR that you originally linked in the issue? did that help any?

**Comment by dangoncalves** [comment]
Hello @thedoubl3j unfortunately I was not able to reproduce at this time so I cannot test the draft PR.
