### ISSUE TITLE
Something went wrong... There was an error loading this content. Please reload the page. Back to Dashboard.

### ISSUE THREAD

**Issue by birb57** [ansible/awx#14819]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hi

when trying to enter data in prompt for a job schedule I encounter below error just after slecting inventory :

TypeError: Cannot read properties of undefined (reading 'split')
TypeError: Cannot read properties of undefined (reading 'split')
    at https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:2056367
    at $Z (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:2056411)
    at ao (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:851391)
    at Ks (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:903735)
    at Al (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:890981)
    at Tl (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:890909)
    at El (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:890772)
    at yl (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:887738)
    at https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:837183
    at t.unstable_runWithPriority (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:933489)

Thanks for your support

### AWX version

23.6.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.12.5

### Operating system

Red Hat 

### Steps to reproduce

I create a schedule for my awx template (yum update) and when trying to enter data in "Prompt" I encounter upper error just after selecting inventory

### Expected results

no error

### Actual results

TypeError: Cannot read properties of undefined (reading 'split')
TypeError: Cannot read properties of undefined (reading 'split')
    at https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:2056367
    at $Z (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:2056411)
    at ao (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:851391)
    at Ks (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:903735)
    at Al (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:890981)
    at Tl (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:890909)
    at El (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:890772)
    at yl (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:887738)
    at https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:837183
    at t.unstable_runWithPriority (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:933489)

### Additional information

TypeError: Cannot read properties of undefined (reading 'split')
TypeError: Cannot read properties of undefined (reading 'split')
    at https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:2056367
    at $Z (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:2056411)
    at ao (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:851391)
    at Ks (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:903735)
    at Al (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:890981)
    at Tl (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:890909)
    at El (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:890772)
    at yl (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:887738)
    at https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:837183
    at t.unstable_runWithPriority (https://tower.cedelgroup.com/static/js/main.fcec0bf3.js:2:933489)

**Comment by fosterseth** [comment]
thanks for opening this issue, what data did you enter into the fields that we can use to replicate?

please provide a minimal reproducer on a fresh environment

**Comment by birb57** [comment]
Hello Fosterseth

I already give some info on how to:

 create a schedule for my awx worflow template (yum update) and when trying to enter data in "Prompt" I encounter upper error just after selecting inventory


Thanks for your help

**Comment by birb57** [comment]
hi

some news ?

thanks
