### ISSUE TITLE
Can't create system auditor user

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#1486]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### STEPS TO REPRODUCE

* Create a system auditor user via the UI OR
* POST to `/api/v2/organization/1/users/`

```
{
	"first_name": "Djkfd",
	"last_name": "Kjdlkf",
	"organization": 1,
	"email": "dfdlj@kdjfd.com",
	"username": "admin",
	"password": "abc123",
	"password_confirm": "abc123",
	"user_type": {
		"type": "system_auditor",
		"label": "System Auditor"
	},
	"is_superuser": false,
	"is_system_auditor": true
}
```

##### EXPECTED RESULTS

* For a system auditor user to be created

##### ACTUAL RESULTS

500

##### ADDITIONAL INFORMATION

```
2018-03-08 21:19:35,536 ERROR    django.request Internal Server Error: /api/v2/organizations/1/users/
Traceback (most recent call last):
  File "/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "./awx/wsgi.py", line 65, in _legacy_get_response
    return super(AWXWSGIHandler, self)._legacy_get_response(request)
  File "/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "./awx/api/generics.py", line 284, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "./awx/api/views.py", line 968, in post
    user = User.objects.get(id=ret.data['id'])
KeyError: 'id'
```

**Comment by ryanpetrello** [comment]
Resolved downstream.
