### ISSUE TITLE
Inventory sync issue post upgrade to 23.7.0

### ISSUE THREAD

**Issue by leosimony** [ansible/awx#14882]
##### ISSUE TYPE

 - Breaking Change

##### COMPONENT NAME

 - API
 - UI
 - Collection

##### SUMMARY
Inventory sync fails to post the upgrade to 23.7.0. Mysteriously making a change in the inventory source template gives unexpected results, more details are given below.

##### ENVIRONMENT
* AWX version: 23.7.0
* AWX install method: operator
* AWX deployment target: kubernetes (k3s)
Client Version: v1.24.3+k3s1
Kustomize Version: v4.5.4
Server Version: v1.24.3+k3s1
* Operating System: Ubuntu 22.04.3 LTS
* Web Browser: Chrome

##### STEPS TO REPRODUCE

```
---
plugin: amazon.aws.aws_ec2
regions:
   - us-east-1
   - ap-south-1
filters:
  instance-state-name: running
keyed_groups:
  - key: placement.region
    prefix: aws_region
  - key: tags.Group
    separator: ''
  - prefix: instance_type
    key: instance_type
  - key: tags.Name
    separator: ''
hostnames:
  - network-interface.addresses.association.public-ip
```

compose:
  ansible_host: network-interface.addresses.association.public-ip
  
I am running inventory sync with the above config results in the error.

##### EXPECTED RESULTS

Inventory sync should be complete.

##### ACTUAL RESULTS

```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 605, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 318, in run
    res = self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 393, in _run_internal
    res = processor_future.result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/utils/common.py", line 1177, in wrapper_cleanup_new_process
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 461, in processor
    return ansible_runner.interface.run(
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/ansible_runner/interface.py", line 213, in run
    r.run()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/ansible_runner/streaming.py", line 361, in run
    self.artifacts_callback(data)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/ansible_runner/streaming.py", line 335, in artifacts_callback
    unstream_dir(self._input, length, self.artifact_dir)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/ansible_runner/utils/streaming.py", line 73, in unstream_dir
    data = source.read(chunk_size)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/ansible_runner/utils/base64io.py", line 259, in read
    results.write(base64.b64decode(data))
  File "/usr/lib64/python3.9/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

##### ADDITIONAL INFORMATION

```
---
plugin: amazon.aws.aws_ec2
regions:
   - us-east-1
   - ap-south-1
filters:
  tag:Name: ASRWPRIMARY
  instance-state-name: running
keyed_groups:
  - key: placement.region
    prefix: aws_region
  - key: tags.Group
    separator: ''
  - prefix: instance_type
    key: instance_type
  - key: tags.Name
    separator: ''
hostnames:
  - network-interface.addresses.association.public-ip
```

Running inventory sync with the above config works fine without any errors. All of a sudden why the "tag:Name" value makes a difference is a mystery. 

We have upgraded to 23.7.0 last Feb 9,2024.

**Comment by the-paulus** [comment]
I had the same issue and was able to fix it by editing the AWX resource.

`kubectl edit AWX -n awx`

Add the following to the spec section:

```
ee_extra_env: |
    - name: RECEPTOR_KUBE_SUPPORT_RECONNECT
      value: disabled
```

**Comment by leosimony** [comment]
@the-paulus 
Thank you for the update. I have made the changes as mentioned, awx-task pod was recreated and that's fixed the issue. Now I can do inventory sync with my existing config itself.
