### ISSUE TITLE
django.db.utils.ProgrammingError: unrecognized configuration parameter "idle_session_timeout"

### ISSUE THREAD

**Issue by gstorme** [ansible/awx#15326]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Upgraded from AWX 24.2.0 to 24.6.1 by upgrading awx-operator to 2.19.1.
Since the upgrade, all jobs remain in the pending state.

Output of the awx-migration-24.6.1-gdqcb pod:

```Operations to perform:
  Apply all migrations: auth, conf, contenttypes, dab_rbac, dab_resource_registry, main, oauth2_provider, sessions, sites, social_django, sso
Running migrations:
  Applying dab_rbac.0001_initial... OK
  Applying main.0191_add_django_permissions... OK
2024-07-03 08:13:10,644 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition WorkflowJobTemplate Admin pk=RoleDefinition object (1) with 5 permissions
2024-07-03 08:13:10,649 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Organization WorkflowJobTemplate Admin pk=RoleDefinition object (2) with 7 permissions
2024-07-03 08:13:10,654 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition WorkflowJobTemplate Execute pk=RoleDefinition object (3) with 2 permissions
2024-07-03 08:13:10,659 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition WorkflowJobTemplate Approve pk=RoleDefinition object (4) with 2 permissions
2024-07-03 08:13:10,665 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition NotificationTemplate Admin pk=RoleDefinition object (5) with 3 permissions
2024-07-03 08:13:10,670 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Organization NotificationTemplate Admin pk=RoleDefinition object (6) with 5 permissions
2024-07-03 08:13:10,676 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Inventory Admin pk=RoleDefinition object (7) with 6 permissions
2024-07-03 08:13:10,681 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Organization Inventory Admin pk=RoleDefinition object (8) with 8 permissions
2024-07-03 08:13:10,686 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Inventory Use pk=RoleDefinition object (9) with 2 permissions
2024-07-03 08:13:10,690 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Inventory Adhoc pk=RoleDefinition object (10) with 2 permissions
2024-07-03 08:13:10,695 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Inventory Update pk=RoleDefinition object (11) with 2 permissions
2024-07-03 08:13:10,701 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition JobTemplate Admin pk=RoleDefinition object (12) with 4 permissions
2024-07-03 08:13:10,705 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Organization JobTemplate Admin pk=RoleDefinition object (13) with 5 permissions
2024-07-03 08:13:10,710 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition JobTemplate Execute pk=RoleDefinition object (14) with 2 permissions
2024-07-03 08:13:10,716 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Credential Admin pk=RoleDefinition object (15) with 4 permissions
2024-07-03 08:13:10,720 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Organization Credential Admin pk=RoleDefinition object (16) with 6 permissions
2024-07-03 08:13:10,725 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Credential Use pk=RoleDefinition object (17) with 2 permissions
2024-07-03 08:13:10,731 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition ExecutionEnvironment Admin pk=RoleDefinition object (18) with 3 permissions
2024-07-03 08:13:10,735 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Organization ExecutionEnvironment Admin pk=RoleDefinition object (19) with 5 permissions
2024-07-03 08:13:10,740 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Project Admin pk=RoleDefinition object (20) with 5 permissions
2024-07-03 08:13:10,744 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Organization Project Admin pk=RoleDefinition object (21) with 7 permissions
2024-07-03 08:13:10,749 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Project Use pk=RoleDefinition object (22) with 2 permissions
2024-07-03 08:13:10,759 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Project Update pk=RoleDefinition object (23) with 2 permissions
2024-07-03 08:13:10,765 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Team Admin pk=RoleDefinition object (24) with 4 permissions
2024-07-03 08:13:10,769 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Team Member pk=RoleDefinition object (25) with 2 permissions
2024-07-03 08:13:10,775 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Organization Member pk=RoleDefinition object (26) with 2 permissions
2024-07-03 08:13:10,781 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition InstanceGroup Admin pk=RoleDefinition object (27) with 4 permissions
2024-07-03 08:13:10,785 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition InstanceGroup Use pk=RoleDefinition object (28) with 2 permissions
2024-07-03 08:13:10,790 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Organization Admin pk=RoleDefinition object (29) with 46 permissions
2024-07-03 08:13:10,795 INFO     [-] awx.main.migrations._dab_rbac Created RoleDefinition Organization Audit pk=RoleDefinition object (30) with 10 permissions
2024-07-03 08:13:11,259 INFO     [-] awx.main.migrations._dab_rbac Created custom Role Definition Credential Read, pk=31
2024-07-03 08:13:11,639 INFO     [-] awx.main.migrations._dab_rbac Created custom Role Definition Inventory Read, pk=32
2024-07-03 08:13:11,832 INFO     [-] awx.main.migrations._dab_rbac Created custom Role Definition Organization Read, pk=33
2024-07-03 08:13:14,991 INFO     [-] awx.main.migrations._dab_rbac Created custom Role Definition JobTemplate Read, pk=34
2024-07-03 08:13:17,442 INFO     [-] awx.main.migrations._dab_rbac Created custom Role Definition Project Read, pk=35
  Applying main.0192_custom_roles... OK
  Applying main.0193_alter_notification_notification_type_and_more... OK
  Applying main.0194_alter_inventorysource_source_and_more... OK
  Applying main.0195_EE_permissions... OK
```

The awx-task pod errors:

```
2024-07-03 09:47:43,859 ERROR    [2edc9e30e6d4443cacd89c96a57cb6b5] awx.main.dispatch Worker failed to run task awx.main.scheduler.tasks.dependency_manager(*[], **{}
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedObject: unrecognized configuration parameter "idle_session_timeout"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/dispatch/worker/task.py", line 103, in perform_work
    result = self.run_callable(body)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/dispatch/worker/task.py", line 78, in run_callable
    return _call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/scheduler/tasks.py", line 30, in dependency_manager
    run_manager(DependencyManager, "dependency")
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/scheduler/tasks.py", line 20, in run_manager
    manager().schedule()
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/scheduler/task_manager.py", line 142, in schedule
    with advisory_lock(f"{self.prefix}_lock", lock_session_timeout_milliseconds=lock_session_timeout_milliseconds, wait=False) as acquired:
  File "/usr/lib64/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/utils/pglock.py", line 19, in advisory_lock
    idle_session_timeout = cur.execute('SHOW idle_session_timeout').fetchone()[0]
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: unrecognized configuration parameter "idle_session_timeout"
```

### AWX version

24.6.1

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

minikube

### Modifications

no

### Steps to reproduce

Upgrade AWX by upgrading awx-operator from 2.15.0 to 2.19.1.

### Expected results

Jobs are still started after the upgrade

### Actual results

Jobs remain in the pending state

### Additional information

minikube 1.32.0 on Debian 10.9

**Comment by gstorme** [comment]
https://github.com/ansible/awx/blob/94e5795dfc37b95c576d61f3e3b4e936c021548c/awx/main/utils/pglock.py#L15
I see that `idle_session_timeout` was introduced in PostgreSQL 14.
Our db server is postgresql 13, I'll upgrade it.

**Comment by gstorme** [comment]
Fixed after upgrading to Postgresql 14

**Comment by sdx23** [comment]
edit: ignore my comment. Documentation states the supported Postgresql version is (currently) 15 and newer might be compatible. https://ansible.readthedocs.io/projects/awx-operator/en/latest/user-guide/database-configuration.html#postgresql-version
