### ISSUE TITLE
Command run_callback_receiver Gives error: MetricsServer failed to start for service 'callback_receiver | OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by debeste123** [ansible/awx#15361]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

While running the run_callback_receiver command, I get an error mentrioning that the MetricsServer cannot be started because its address is already in use. 

awx-manage run_callback_receiver
2024-07-11 17:52:46,928 ERROR    [-] awx.main.analytics **MetricsServer failed to start for service 'callback_receiver.**
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/_init_.py", line 175, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/_init_.py", line 442, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/_init_.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/management/commands/run_callback_receiver.py", line 30, in handle
    CallbackReceiverMetricsServer().start()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/analytics/subsystem_metrics.py", line 39, in start
    prometheus_client.start_http_server(self.port(), addr='localhost', registry=self._registry)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/prometheus_client/exposition.py", line 171, in start_wsgi_server
    httpd = make_server(addr, port, app, TmpServer, handler_class=_SilentHandler)
  File "/usr/lib64/python3.9/wsgiref/simple_server.py", line 154, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib64/python3.9/socketserver.py", line 452, in _init_
    self.server_bind()
  File "/usr/lib64/python3.9/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib64/python3.9/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
**OSError: [Errno 98] Address already in use**

### AWX version

23.8.1

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

In AWX task pod, run awx-manage run_callback_receiver

### Expected results

The callback receiver to be restarted

### Actual results

Receive the error
MetricsServer failed to start for service 'callback_receiver
OSError: [Errno 98] Address already in use

**Comment by djyasin** [comment]
Hello, this appears that it could be a configuration issue rather than a bug.  Could you please ask this on the [Ansible Community Forum](https://forum.ansible.com/tag/awx)?

**Comment by djyasin** [comment]
We are going to go ahead and close this issue. We look forward to speaking with you there!
