### ISSUE TITLE
failed to fetch sources from project

### ISSUE THREAD

**Issue by dberardo-com** [ansible/awx#15488]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

i have a project that gets correctly cloned (synced) and i am now trying to sync an inventory from a yaml file source within that project.

the path to the yaml file is something like inventories/blabla/inventory.yml

it used to work in the past, but now i get this error when syncing (job log):

```

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/tasks/jobs.py", line 500, in run
    self.build_project_dir(self.instance, private_data_dir)
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/tasks/jobs.py", line 1634, in build_project_dir
    self.sync_and_copy(source_project, private_data_dir, scm_branch=inventory_update.inventory_source.scm_branch)
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/tasks/jobs.py", line 791, in sync_and_copy
    return self.sync_and_copy_without_lock(project, private_data_dir, scm_branch=scm_branch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/tasks/jobs.py", line 747, in sync_and_copy_without_lock
    sync_task.run(local_project_sync.id)
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/tasks/jobs.py", line 94, in _wrapped
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/tasks/signals.py", line 81, in _wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/tasks/jobs.py", line 665, in run
    raise AwxTaskError.TaskError(self.instance, rc)
Exception: project_update 390 (failed) encountered an error (rc=None), please see task stdout for details.
```

### AWX version

24.3.1

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

no idea

### Expected results

it should work, or at least give more log

### Actual results

error above

**Comment by fosterseth** [comment]
does result_traceback on the api/v2/projects_updates/#/ have more details on the error?

**Comment by dberardo-com** [comment]
the issue seems to be that the project containing the dynamic script that the inventory source uses to update the hosts list includes a git submodule whoe default branch is not origin/main.

As a workaround i did create that branch on the submodule, but it would be nice to understand why the ansible task that does the pull imposes a branch name different from the one found in the .gitmodules file.

ref: https://github.com/ansible/awx/issues/16004
