### ISSUE TITLE
Previous Task Failed: {"jobotype": "project_udate", "job_name": "Project2.4-pProject-ethf2yk77j58888", "job_id": "1346"}

### ISSUE THREAD

**Issue by zhixiang-liu2002** [ansible/awx#15559]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

When I batch execute jobs through the API, the first job's status is failed with error messages: Previous Task Failed: {"jobotype": "project_udate", "job_name": "Project2.4-pProject-ethf2yk77j58888", "job_id": "1346"}, but the ID 1346 is not in my job list. When I re execute this job, it will display as successful

### AWX version

23.6.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.9.27

### Operating system

Centos7

### Web browser

Chrome

### Steps to reproduce

Parallel execution of the workbook using API

### Expected results

all task will success

### Actual results

The first job will fail

### Additional information

[
![screenshot-20240929-181148](https://github.com/user-attachments/assets/9c776a56-aaa1-4600-b228-9981476207e4)
![screenshot-20240929-181235](https://github.com/user-attachments/assets/b9888fba-854d-4eb1-8387-5a49c25d59b8)
![screenshot-20240929-181251](https://github.com/user-attachments/assets/cfd34874-621f-400e-b340-6ae2efc72894)
![screenshot-20240929-181305](https://github.com/user-attachments/assets/a57c48af-f3ef-496a-bed1-2fe6493c3a64)
](url)
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 500, in run
    self.build_project_dir(self.instance, private_data_dir)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 1094, in build_project_dir
    self.sync_and_copy(job.project, private_data_dir, scm_branch=job.scm_branch)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 791, in sync_and_copy
    return self.sync_and_copy_without_lock(project, private_data_dir, scm_branch=scm_branch)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 747, in sync_and_copy_without_lock
    sync_task.run(local_project_sync.id)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 94, in _wrapped
    return f(self, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/signals.py", line 81, in _wrapped
    return f(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 665, in run
    raise AwxTaskError.TaskError(self.instance, rc)
Exception: project_update 1346 (failed) encountered an error (rc=None), please see task stdout for details.

**Comment by djyasin** [comment]
Hello @zhixiang-liu2002, it looks like this issue was reported on an older version of AWX. Are you still encountering this issue?

**Comment by thedoubl3j** [comment]
clsoing due to inactivity, if you or other folks are still experiencing this on devel, please feel free to re-open
