### ISSUE TITLE
devel image crashes with "ModuleNotFoundError: No module named 'ldap'"

### ISSUE THREAD

**Issue by phire-tc** [ansible/awx#15614]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### AWX version

ghcr.io/ansible/awx_devel:devel ID 70a33322c9f7

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

7.7.0+dfsg-3+deb12u1

### Operating system

Debian GNU/Linux 12 (bookworm)

### Web browser

Firefox

### Steps to reproduce

Checkout commit 68055bb89f

$ COMPOSE_TAG=devel make docker-compose

### Expected results

AWX runs.

### Actual results

A process called "daphne" crashes because it can't import the ldap module:

```
tools_awx_1       | make[1]: Entering directory '/awx_devel'                                                                                                                                                                                  
tools_awx_1       | Traceback (most recent call last):                                                                                                                                                                                        
tools_awx_1       |   File "/var/lib/awx/venv/awx/bin/daphne", line 8, in <module>                                                                                                                                                            
tools_awx_1       |     sys.exit(CommandLineInterface.entrypoint())                                                                                                                                                                           
tools_awx_1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                            
tools_awx_1       |   File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/daphne/cli.py", line 170, in entrypoint                                                                                                                      
tools_awx_1       |     cls().run(sys.argv[1:])                                                                                                                                                                                               
tools_awx_1       |   File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/daphne/cli.py", line 232, in run                                                                                                                             
tools_awx_1       |     application = import_by_path(args.application)                                                                                                                                                                        
tools_awx_1       |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                        
tools_awx_1       |   File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/daphne/utils.py", line 12, in import_by_path
tools_awx_1       |     target = importlib.import_module(module_path)                                                                                                                                                                         
tools_awx_1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                         
tools_awx_1       |   File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module                                                                                                                                          
tools_awx_1       |     return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                                                           
tools_awx_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                           
tools_awx_1       |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import                                                                                                                                                         
tools_awx_1       |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load                                                                                                                                                      
tools_awx_1       |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked                                                                                                                                             
tools_awx_1       |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked                                                                                                                                                       
tools_awx_1       |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module                                                                                                                                                 
tools_awx_1       |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                                                                                                                            
tools_awx_1       |   File "/awx_devel/awx/asgi.py", line 12, in <module>                                                                                                                                                                     
tools_awx_1       |     prepare_env()  # NOQA                                                                          
tools_awx_1       |     ^^^^^^^^^^^^^                                                                                  
tools_awx_1       |   File "/awx_devel/awx/__init__.py", line 107, in prepare_env                                                                                                                                                             
tools_awx_1       |     if not settings.DEBUG:  # pragma: no cover                                                                                                                                                                            
tools_awx_1       |            ^^^^^^^^^^^^^^                                                                          
tools_awx_1       |   File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
tools_awx_1       |     self._setup(name)                                                                              
tools_awx_1       |   File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
tools_awx_1       |     self._wrapped = Settings(settings_module)                                                                                                                                                                             
tools_awx_1       |                     ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                             
tools_awx_1       |   File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
tools_awx_1       |     mod = importlib.import_module(self.SETTINGS_MODULE)                                                                                                                                                                   
tools_awx_1       |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                   
tools_awx_1       |   File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module                                                                                                                                          
tools_awx_1       |     return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                                                           
tools_awx_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                           
tools_awx_1       |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import                                                                                                                                                         
tools_awx_1       |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load                                                                                                                                                      
tools_awx_1       |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked                                                                                                                                             
tools_awx_1       |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked                                                                                                                                                       
tools_awx_1       |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module                                                                                                                                                 
tools_awx_1       |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                                                                                                                            
tools_awx_1       |   File "/awx_devel/awx/settings/development.py", line 21, in <module>                                                                                                                                                     
tools_awx_1       |     from .defaults import *  # NOQA                                                                
tools_awx_1       |     ^^^^^^^^^^^^^^^^^^^^^^^                                                                        
tools_awx_1       |   File "/awx_devel/awx/settings/defaults.py", line 13, in <module>                                                                                                                                                        
tools_awx_1       |     import ldap                                                                                    
tools_awx_1       | ModuleNotFoundError: No module named 'ldap'                                                                                                                                                                               
tools_awx_1       | make[1]: Leaving directory '/awx_devel'                                                            
tools_awx_1       | make[1]: *** [Makefile:254: daphne] Error 1                                                                                                                                                                               
tools_awx_1       | 2024-11-05 13:56:08,594 WARN exited: awx-daphne (exit status 2; not expected)                                                                                                                                             
```

**Comment by mpserafim** [comment]
Hi try this:
- connect to tools_awx_1 and install:
`yum install python-devel openldap-devel gcc`
then run:
`pip install python-ldap`

**Comment by chrisdola** [comment]
@phire-tc Did you ever get past this?

**Comment by zwsyscall** [comment]
I'm rather shocked at the quality of tests. There is evidently no test pipeline for the docker release.

**Comment by Dherlou** [comment]
Currently facing a similar error message `ModuleNotFoundError: No module named 'split_settings'` when pulling the latest image.

**Comment by extrminal** [comment]
Got same problem passing `COMPOSE_TAG=devel` to make command

**Comment by sikorapatryk** [comment]
Currently have similar error message `ModuleNotFoundError: No module named 'ansible_base'` when pulling `release_4.5` image.

**Comment by epologov** [comment]
Have same issue when building image for k8s using "make awx-kube-build"

`
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/wsgi.py", line 10, in <module>
    prepare_env()
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/__init__.py", line 71, in prepare_env
Traceback (most recent call last):
    if not settings.DEBUG:  # pragma: no cover
           ^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/wsgi.py", line 10, in <module>
    self._setup(name)
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/settings/__init__.py", line 49, in <module>
    load_python_file_with_injected_context(settings_files_path, settings=DYNACONF)
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/ansible_base/lib/dynamic_config/dynaconf_helpers.py", line 275, in load_python_file_with_injected_context
    exec(code, scope)
  File "/etc/tower/conf.d/ldap.py", line 2, in <module>
    ldap.OPT_X_TLS_REQUIRE_CERT: True,
    ^^^^
**NameError: name 'ldap' is not defined**
unable to load app 0 (mountpoint='/') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
`

**Comment by kgal-akl** [comment]
i'm getting one for `ansible_base`:

```
tools_awx_1       | Traceback (most recent call last):
tools_awx_1       |   File "/usr/local/bin/awx-manage", line 9, in <module>
tools_awx_1       |     load_entry_point('awx', 'console_scripts', 'awx-manage')()
tools_awx_1       |   File "/awx_devel/awx/__init__.py", line 77, in manage
tools_awx_1       |     prepare_env()
tools_awx_1       |   File "/awx_devel/awx/__init__.py", line 71, in prepare_env
tools_awx_1       |     if not settings.DEBUG:  # pragma: no cover
tools_awx_1       |   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/conf/__init__.py", line 102, in __getattr__
tools_awx_1       |     self._setup(name)
tools_awx_1       |   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/conf/__init__.py", line 89, in _setup
tools_awx_1       |     self._wrapped = Settings(settings_module)
tools_awx_1       |   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/conf/__init__.py", line 217, in __init__
tools_awx_1       |     mod = importlib.import_module(self.SETTINGS_MODULE)
tools_awx_1       |   File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
tools_awx_1       |     return _bootstrap._gcd_import(name[level:], package, level)
tools_awx_1       |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
tools_awx_1       |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
tools_awx_1       |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
tools_awx_1       |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
tools_awx_1       |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
tools_awx_1       |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
tools_awx_1       |   File "/awx_devel/awx/settings/__init__.py", line 5, in <module>
tools_awx_1       |     from ansible_base.lib.dynamic_config import (
tools_awx_1       | ModuleNotFoundError: No module named 'ansible_base'
```
