### ISSUE TITLE
AWX CLI crashes with Python 3.12.8 and 3.13.1

### ISSUE THREAD

**Issue by mhassan1** [ansible/awx#15687]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

After upgrading from Python 3.12.7 to 3.12.8 or from Python 3.13.0 to 3.13.1, the AWX CLI crashes with the following:
```txt
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.13.1/lib/python3.13/site-packages/awxkit/cli/__init__.py", line 23, in run
    cli.parse_args(argv or sys.argv)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.13.1/lib/python3.13/site-packages/awxkit/cli/client.py", line 296, in parse_args
    self.args = self.parser.parse_known_args(self.argv)[0]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.13.1/lib/python3.13/argparse.py", line 1899, in parse_known_args
    return self._parse_known_args2(args, namespace, intermixed=False)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.13.1/lib/python3.13/argparse.py", line 1928, in _parse_known_args2
    namespace, args = self._parse_known_args(args, namespace, intermixed)
                      ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HelpfulArgumentParser._parse_known_args() takes 3 positional arguments but 4 were given
```

### AWX version

awxkit@24.6.1

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Operating system

MacOS Sonoma

### Steps to reproduce

```bash
pyenv install 3.13.1
pip install awxkit
awx --version
```

### Expected results

```txt
24.6.1
```

### Actual results

```txt
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.13.1/lib/python3.13/site-packages/awxkit/cli/__init__.py", line 23, in run
    cli.parse_args(argv or sys.argv)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.13.1/lib/python3.13/site-packages/awxkit/cli/client.py", line 296, in parse_args
    self.args = self.parser.parse_known_args(self.argv)[0]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.13.1/lib/python3.13/argparse.py", line 1899, in parse_known_args
    return self._parse_known_args2(args, namespace, intermixed=False)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.13.1/lib/python3.13/argparse.py", line 1928, in _parse_known_args2
    namespace, args = self._parse_known_args(args, namespace, intermixed)
                      ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HelpfulArgumentParser._parse_known_args() takes 3 positional arguments but 4 were given
```

### Additional information

This is not reproducible on Python 3.12.7 or Python 3.13.0.

**Comment by avalor1** [comment]
Same behaviour with python 3.12.8. 
Version 3.12.7 works.

**Comment by larsks** [comment]
I am seeing the same behavior running with Python 3.13.3. The full traceback is:

```
Traceback (most recent call last):
  File ".../lib64/python3.13/site-packages/awxkit/cli/__init__.py", line 23, in run
    cli.parse_args(argv or sys.argv)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File ".../lib64/python3.13/site-packages/awxkit/cli/client.py", line 296, in parse_args
    self.args = self.parser.parse_known_args(self.argv)[0]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/lib64/python3.13/argparse.py", line 1899, in parse_known_args
    return self._parse_known_args2(args, namespace, intermixed=False)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/argparse.py", line 1928, in _parse_known_args2
    namespace, args = self._parse_known_args(args, namespace, intermixed)
                      ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HelpfulArgumentParser._parse_known_args() takes 3 positional arguments but 4 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lars/.local/bin/awx", line 8, in <module>
    sys.exit(run())
             ~~~^^
  File ".../lib64/python3.13/site-packages/awxkit/cli/__init__.py", line 65, in run
    if cli.verbose:
       ^^^^^^^^^^^
AttributeError: 'CLI' object has no attribute 'verbose'
```
