### ISSUE TITLE
Normal users unable to view/edit/use Job Template Surveys

### ISSUE THREAD

**Issue by ethackal** [ansible/awx#157]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
When attempting to launch a job using a template containing a survey, normal users receive a modal with no form controls and are unable to launch.

##### ENVIRONMENT
* AWX version: 1.0.0

##### STEPS TO REPRODUCE
Create a new template with a survey for required variables. Attempt to launch the job as a normal user.

##### EXPECTED RESULTS
User should receive a the survey form to fill out before launching the job.

##### ACTUAL RESULTS
The survey modal appears but there is no form content. Web server reports a 500 error.

##### ADDITIONAL INFORMATION

```
2017-09-13 14:42:11,488 ERROR    django.request Internal Server Error: /api/v2/job_templates/8/survey_spec/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 246, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 454, in dispatch
    self.initial(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 377, in initial
    self.check_permissions(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 318, in check_permissions
    if not permission.has_permission(request, self):
  File "/usr/lib/python2.7/site-packages/awx/api/permissions.py", line 124, in has_permission
    response = self.check_permissions(request, view, obj)
  File "/usr/lib/python2.7/site-packages/awx/api/permissions.py", line 113, in check_permissions
    result = check_method and check_method(request, view, obj)
  File "/usr/lib/python2.7/site-packages/awx/api/permissions.py", line 37, in check_get_permissions
    parent_obj = view.get_parent_object()
AttributeError: 'JobTemplateSurveySpec' object has no attribute 'get_parent_object'
[pid: 29|app: 0|req: 14/62] 172.17.0.1 () {48 vars in 2097 bytes} [Wed Sep 13 14:42:11 2017] GET /api/v2/job_templates/8/survey_spec/ => generated 41 bytes in 47 msecs (HTTP/1.1 500) 4 headers in 157 bytes (1 switches on core 0)
```

**Comment by matburt** [comment]
This looks related to this recent change: https://github.com/ansible/awx/commit/41940687f1648ff1865d5ea9b677ddacbb42dbfe

**Comment by ethackal** [comment]
Adding ParentMixin to the JobTemplateSurveySpec definition seems to resolve it. Might pop up in other places though.

**Comment by matburt** [comment]
cc @AlanCoding who last touched

**Comment by AlanCoding** [comment]
> Adding ParentMixin to the JobTemplateSurveySpec definition seems to resolve it. Might pop up in other places though.

That's a good observation, and it really shows the problem the assumption that I incorrectly made, which was that `parent_model` implies the existence of `get_parent_object`.

It makes a lot of sense to have the ParentMixin correspond with the use of parent_model. My only nitpick about that approach is that we should switch the view's logic to also use get_parent_object if we go this route, just to be more consistent.

**Comment by AlanCoding** [comment]
After digging, I decided I didn't like that approach. Alternative:

https://github.com/ansible/awx/compare/devel...AlanCoding:step_parent?expand=1

I think the right way to fix this is to remove the pattern of declaring both `model` and `parent_model`. We may also adjust the `permissions.py` to only do the check if the view is of the sublist type.

The big missing piece is that we should have some tests to confirm that OPTIONS is returning the right data for users with only read permissions, because that is what this affects.

**Comment by AlanCoding** [comment]
This should be working in `devel` again. Thanks again for raising the issue.
