### ISSUE TITLE
Build AWX AI with errors (TemplateDoesNotExist)

### ISSUE THREAD

**Issue by RenanMonteiroS** [ansible/awx#15720]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

AWX is not building the UI correctly using Docker installation method.

### AWX version

24.6.1

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.14.17

### Operating system

Rocky Linux 9.5

### Steps to reproduce

````
sudo git clone https://github.com/ansible/awx.git
cd awk
make docker-compose-build
make docker-compose
make clean/ui ui
````

### Expected results

Build UI correctly.

### Actual results

 When accessing the URL, UI shows this message:
````
TemplateDoesNotExist at /
index_awx.html

Request Method: GET

Request URL: https://192.168.1.88:8043/
Django Version: 4.2.16
Exception Type: TemplateDoesNotExist
Exception Value: index_awx.html
Exception Location: /var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/template/loader.py, line 47, in select_template
Raised during: awx.ui.urls.IndexView
Python Executable: /var/lib/awx/venv/awx/bin/uwsgi
Python Version: 3.11.11
Python Path: ['.',  '',  '/usr/lib64/python311.zip',  '/usr/lib64/python3.11',  '/usr/lib64/python3.11/lib-dynload',  '/var/lib/awx/venv/awx/lib64/python3.11/site-packages',  '/awx_devel',  '/var/lib/awx/venv/awx/lib/python3.11/site-packages']
Server time: Thu, 19 Dec 2024 13:31:43 +0000
````

Traceback:
````
Environment:


Request Method: GET
Request URL: https://192.168.1.88:8043/

Django Version: 4.2.16
Python Version: 3.11.11
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.sites',
 'daphne',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_extensions',
 'polymorphic',
 'django_guid',
 'corsheaders',
 'awx.conf',
 'awx.main',
 'awx.api',
 'awx.ui',
 'solo',
 'ansible_base.rest_filters',
 'ansible_base.jwt_consumer',
 'ansible_base.resource_registry',
 'ansible_base.rbac',
 'flags',
 'drf_yasg',
 'debug_toolbar']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django_guid.middleware.guid_middleware',
 'ansible_base.lib.middleware.logging.log_request.LogTracebackMiddleware',
 'awx.main.middleware.SettingsCacheMiddleware',
 'awx.main.middleware.TimingMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'awx.main.middleware.MigrationRanCheckMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'awx.main.middleware.DisableLocalAuthMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'awx.main.middleware.OptionalURLPrefixPath',
 'crum.CurrentRequestUserMiddleware',
 'awx.main.middleware.URLModificationMiddleware',
 'awx.main.middleware.SessionTimeoutMiddleware']

Template loader postmortem
Django tried loading these templates, in this order:

Using engine default:
    * django.template.loaders.filesystem.Loader: /awx_devel/awx/templates/index_awx.html (Source does not exist)
    * django.template.loaders.filesystem.Loader: /awx_devel/awx/ui/public/index_awx.html (Source does not exist)
    * django.template.loaders.filesystem.Loader: /awx_devel/awx/ui/build/awx/index_awx.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/contrib/auth/templates/index_awx.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /var/lib/awx/venv/awx/lib64/python3.11/site-packages/rest_framework/templates/index_awx.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /var/lib/awx/venv/awx/lib64/python3.11/site-packages/django_extensions/templates/index_awx.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /var/lib/awx/venv/awx/lib64/python3.11/site-packages/polymorphic/templates/index_awx.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /awx_devel/awx/api/templates/index_awx.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /var/lib/awx/venv/awx/lib64/python3.11/site-packages/solo/templates/index_awx.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /var/lib/awx/venv/awx/lib64/python3.11/site-packages/flags/templates/index_awx.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /var/lib/awx/venv/awx/lib64/python3.11/site-packages/drf_yasg/templates/index_awx.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /var/lib/awx/venv/awx/lib64/python3.11/site-packages/debug_toolbar/templates/index_awx.html (Source does not exist)



Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: TemplateDoesNotExist at /
Exception Value: index_awx.html

````

**Comment by djyasin** [comment]
Hello,
Could you try restarting your dev containers? I think we run awx-manage collectstatic and that copies the built HTML into a location that Django can serve.

**Comment by djyasin** [comment]
Hi!

Thank you very much for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
