### ISSUE TITLE
Azure dynamic inventory breaks for VMs with win_rm listeners set

### ISSUE THREAD

**Issue by 01100010011001010110010101110000** [ansible/awx#1589]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - `azure_rm.py` dynamic inventory

##### ENVIRONMENT
* AWX version: 1.0.4
* AWX install method: docker
* Ansible version:  2.4.2
* Operating System: CentOS 7.4
* Web Browser: Chrome

##### STEPS TO REPRODUCE
 Run Azure inventory against a subscription containing a VM with a `win_rm` listener set

##### EXPECTED RESULTS
A JSON dump of the inventory, or a successful inventory job

##### ACTUAL RESULTS
```
Traceback (most recent call last):
  File "./azure_rm.py", line 860, in <module>
    main()
  File "./azure_rm.py", line 856, in main
    AzureInventory()
  File "./azure_rm.py", line 502, in __init__
    print(self._json_format_dict(pretty=self._args.pretty))
  File "./azure_rm.py", line 745, in _json_format_dict
    return json.dumps(self._inventory, sort_keys=True, indent=2)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <ProtocolTypes.http: 'Http'> is not JSON serializable
```

The script chokes on serializing ProtocolTypes to JSON. Calling `protocol.name` resolves this by putting the string into the dict, instead of the entire object.
##### ADDITIONAL INFORMATION
Due to my inability to read, there are two upstream PRs for this:
* ansible/ansible#37499
* ansible/ansible#18085

**Comment by yuwzho** [comment]
bug_resolved_by 37499

@01100010011001010110010101110000 Could you please close it?

**Comment by wenottingham** [comment]
Still need to merge this into AWX.

**Comment by wenottingham** [comment]
... and now closing.
