### ISSUE TITLE
Cannot delete token

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#1594]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### STEPS TO REPRODUCE

DELETE `/api/v2/tokens/N/`

##### EXPECTED RESULTS

204

##### ACTUAL RESULTS

```
awx_1        | 2018-03-16 19:13:40,480 ERROR    django.request Internal Server Error: /api/v2/tokens/11/
awx_1        | Traceback (most recent call last):
awx_1        |   File "/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
awx_1        |     response = get_response(request)
awx_1        |   File "./awx/wsgi.py", line 65, in _legacy_get_response
awx_1        |     return super(AWXWSGIHandler, self)._legacy_get_response(request)
awx_1        |   File "/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
awx_1        |     response = self._get_response(request)
awx_1        |   File "/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
awx_1        |     response = self.process_exception_by_middleware(e, request)
awx_1        |   File "/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
awx_1        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
awx_1        |   File "/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
awx_1        |     return func(*args, **kwargs)
awx_1        |   File "/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
awx_1        |     return view_func(*args, **kwargs)
awx_1        |   File "/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
awx_1        |     return self.dispatch(request, *args, **kwargs)
awx_1        |   File "./awx/api/generics.py", line 284, in dispatch
awx_1        |     return super(APIView, self).dispatch(request, *args, **kwargs)
awx_1        |   File "/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 494, in dispatch
awx_1        |     response = self.handle_exception(exc)
awx_1        |   File "/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 454, in handle_exception
awx_1        |     self.raise_uncaught_exception(exc)
awx_1        |   File "/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 491, in dispatch
awx_1        |     response = handler(request, *args, **kwargs)
awx_1        |   File "/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 219, in delete
awx_1        |     return self.destroy(request, *args, **kwargs)
awx_1        |   File "/venv/awx/lib/python2.7/site-packages/rest_framework/mixins.py", line 93, in destroy
awx_1        |     self.perform_destroy(instance)
awx_1        |   File "./awx/api/generics.py", line 487, in perform_destroy
awx_1        |     super(DestroyAPIView, self).perform_destroy(instance)
awx_1        |   File "/venv/awx/lib/python2.7/site-packages/rest_framework/mixins.py", line 97, in perform_destroy
awx_1        |     instance.delete()
awx_1        |   File "/venv/awx/lib/python2.7/site-packages/django/db/models/base.py", line 974, in delete
awx_1        |     return collector.delete()
awx_1        |   File "/venv/awx/lib/python2.7/site-packages/django/db/models/deletion.py", line 284, in delete
awx_1        |     count = qs._raw_delete(using=self.using)
awx_1        |   File "/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 631, in _raw_delete
awx_1        |     return sql.DeleteQuery(self.model).delete_qs(self, using)
awx_1        |   File "/venv/awx/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 80, in delete_qs
awx_1        |     cursor = self.get_compiler(using).execute_sql(CURSOR)
awx_1        |   File "/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
awx_1        |     raise original_exception
awx_1        | ProgrammingError: relation "oauth2_provider_refreshtoken" does not exist
awx_1        | LINE 1: DELETE FROM "oauth2_provider_refreshtoken" WHERE "oauth2_pro...
```

**Comment by rooftopcellist** [comment]
I don't see bug this on the latest devel. This should go away if you clear out your db and restart your container.  It is occurring as a result of some migrations I did when OAuth2 merged.
