### ISSUE TITLE
Login fails after setting activity timeout too high

### ISSUE THREAD

**Issue by Caidran** [ansible/awx#1651]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
No login possible 

##### ENVIRONMENT
* AWX version: latest
* AWX install method: docker on linux
* Ansible version:  2.4
* Operating System: RHEL 7.4
* Web Browser: Chrome/Firefox

##### STEPS TO REPRODUCE

Attempt to login after setting timeout expiry to > 1212121212121211

##### EXPECTED RESULTS

Log in

##### ACTUAL RESULTS

Invalid username/password generated
Happens for all accounts - admin account fails to login and all other accounts are LDAP authenticated which also fail.

awx_web container logs show the following when attempting to log in;

2018-03-22 09:53:49,940 ERROR    django.request Internal Server Error: /api/login/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 65, in _legacy_get_response
    return super(AWXWSGIHandler, self)._legacy_get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/contrib/auth/views.py", line 90, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 67, in post
    ret = super(LoggedLoginView, self).post(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/contrib/auth/views.py", line 119, in form_valid
    auth_login(self.request, form.get_user())
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 139, in login
    request.session.cycle_key()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 311, in cycle_key
    self.create()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 54, in create
    self.save(must_create=True)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 83, in save
    obj = self.create_model_instance(data)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 70, in create_model_instance
    expire_date=self.get_expiry_date(),
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 257, in get_expiry_date
    return modification + timedelta(seconds=expiry)
OverflowError: normalized days too large to fit in a C int
[pid: 28|app: 0|req: 3/9] 10.99.85.18 () {48 vars in 863 bytes} [Thu Mar 22 09:53:49 2018] POST /api/login/ => generated 41 bytes in 357 msecs (HTTP/1.1 500) 5 headers in 177 bytes (1 switches on core 0)

The timeout time was set to 12121212121211 (as a test) and this resulted in logins being disabled. 
To fix this I just removed the entry via the postgres database - command used in case anyone else sets their timeout too high;
\c awx
DELETE FROM public.conf_setting WHERE id = 96;
Probably best to double check id 96 is in fact the entry for the timeout.

The error handling for this could be improved I reckon, perhaps add a limit to the timeout activity entry to prevent this or at the very least a tip in the '?' entry for timeout to avoid setting too high.

Cheers

**Comment by AlanCoding** [comment]
What is the full variable name of the setting in question?

**Comment by Caidran** [comment]
'Idle time force log out' in the 'edit configuration' section. 
web log output when updating the field;

2018-03-22 12:59:00,024 DEBUG    awx.api.authentication User admin performed a PATCH to /api/v2/settings/all/ through the API

**Comment by AlanCoding** [comment]
Thanks, that translates to `SESSION_COOKIE_AGE`, ping @rooftopcellist, this came in with the OAuth2 material.

We have some piping in place to do validation of the configure-in-tower variables, which this one is.

**Comment by ryanpetrello** [comment]
@Caidran this should be resolved now via https://github.com/ansible/awx/commit/13759fd8ce421b9b2515926f1e68cadcd1962403

**Comment by MBcom** [comment]
For all who have the same problem - here a quick solution:
```bash
docker exec -it postgres bash
psql awx -U awx
update public.conf_setting set value = 30000000000 where key= 'SESSION_COOKIE_AGE';
\q
exit
```
Now you can login again.
