### ISSUE TITLE
Exception: Unrecognized launch config field survey_passwords

### ISSUE THREAD

**Issue by soloman747** [ansible/awx#1658]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
When trying to launch a unified workflow job using passwords, the workflow hangs on the inventory sync job. When running a 'docker log awx_task' command, it looks like I'm receiving the following exception:

[2018-03-23 00:11:33,187: ERROR/MainProcess] Task awx.main.scheduler.tasks.run_task_manager[5479bcab-2aec-4be4-b3a7-4891704d3ee8] raised unexpected: Exception('Unrecognized launch config field survey_passwords.',)

##### ENVIRONMENT
* AWX version: 1.0.4.124
* AWX install method: docker on linux
* Ansible version:  2.4.3
* Operating System: Centos
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a unified workflow job with a few job templates and an inventory sync job in the workflow and use password variables in the survey.

##### EXPECTED RESULTS

The workflow should run successfully without hanging

##### ACTUAL RESULTS

The job never completes. It hangs at the inventory sync job. This might also occur with a project scm sync job in the workflow, but I'm not completely sure.

##### ADDITIONAL INFORMATION

```
2018-03-23 00:17:12,246 ERROR    awx.main.scheduler Task awx.main.scheduler.tasks.run_task_manager encountered exception.
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/scheduler/tasks.py", line 37, in run_task_manager
    TaskManager().schedule()
  File "/usr/lib/python2.7/site-packages/awx/main/scheduler/task_manager.py", line 629, in schedule
    finished_wfjs = self._schedule()
  File "/usr/lib/python2.7/site-packages/awx/main/scheduler/task_manager.py", line 614, in _schedule
    self.spawn_workflow_graph_jobs(running_workflow_tasks)
  File "/usr/lib/python2.7/site-packages/awx/main/scheduler/task_manager.py", line 196, in spawn_workflow_graph_jobs
    job = spawn_node.unified_job_template.create_unified_job(**kv)
  File "/usr/lib/python2.7/site-packages/awx/main/models/inventory.py", line 1500, in create_unified_job
    return super(InventorySource, self).create_unified_job(**kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/models/unified_jobs.py", line 393, in create_unified_job
    unified_job.create_config_from_prompts(kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/models/unified_jobs.py", line 880, in create_config_from_prompts
    raise Exception('Unrecognized launch config field {}.'.format(field_name))
Exception: Unrecognized launch config field survey_passwords.
[2018-03-23 00:17:12,249: ERROR/MainProcess] Task awx.main.scheduler.tasks.run_task_manager[c29823d8-2fc7-40a4-ba2d-c79253cb4596] raised unexpected: Exception('Unrecognized launch config field survey_passwords.',)
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/scheduler/tasks.py", line 37, in run_task_manager
    TaskManager().schedule()
  File "/usr/lib/python2.7/site-packages/awx/main/scheduler/task_manager.py", line 629, in schedule
    finished_wfjs = self._schedule()
  File "/usr/lib/python2.7/site-packages/awx/main/scheduler/task_manager.py", line 614, in _schedule
    self.spawn_workflow_graph_jobs(running_workflow_tasks)
  File "/usr/lib/python2.7/site-packages/awx/main/scheduler/task_manager.py", line 196, in spawn_workflow_graph_jobs
    job = spawn_node.unified_job_template.create_unified_job(**kv)
  File "/usr/lib/python2.7/site-packages/awx/main/models/inventory.py", line 1500, in create_unified_job
    return super(InventorySource, self).create_unified_job(**kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/models/unified_jobs.py", line 393, in create_unified_job
    unified_job.create_config_from_prompts(kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/models/unified_jobs.py", line 880, in create_config_from_prompts
    raise Exception('Unrecognized launch config field {}.'.format(field_name))
Exception: Unrecognized launch config field survey_passwords.
[2018-03-23 00:17:26,777: INFO/MainProcess] Scaling down -2 processes.
[2018-03-23 00:17:26,778: DEBUG/MainProcess] basic.qos: prefetch_count->5432
[2018-03-23 00:17:31,896: DEBUG/Beat] beat: Synchronizing schedule...
[2018-03-23 00:17:31,916: INFO/Beat] Scheduler: Sending due task tower_scheduler (awx.main.tasks.awx_periodic_scheduler)
[2018-03-23 00:17:31,918: DEBUG/Beat] awx.main.tasks.awx_periodic_scheduler sent. id->c0466b22-2a05-4ac1-868c-0c28b34d0980
[2018-03-23 00:17:31,919: DEBUG/Beat] beat: Waking up now.
[2018-03-23 00:17:31,919: INFO/MainProcess] Received task: awx.main.tasks.awx_periodic_scheduler[c0466b22-2a05-4ac1-868c-0c28b34d0980] expires:[2018-03-23 00:17:51.917332+00:00]
[2018-03-23 00:17:31,919: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x30f8aa0> (args:(u'awx.main.tasks.awx_periodic_scheduler', u'c0466b22-2a05-4ac1-868c-0c28b34d0980', [], {}, {u'utc': True, u'is_eager': False, u'chord': None, u'group': None, u'args': [], u'retries': 0, u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'tower', u'exchange': u'tower'}, u'expires': u'2018-03-23T00:17:51.917332+00:00', u'hostname': 'celery@awx', u'task': u'awx.main.tasks.awx_periodic_scheduler', u'callbacks': None, u'correlation_id': u'c0466b22-2a05-4ac1-868c-0c28b34d0980', u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'reply_to': u'ebf3eb54-7a03-3352-a5e6-df53ebd2ceb6', u'id': u'c0466b22-2a05-4ac1-868c-0c28b34d0980', u'headers': {}}) kwargs:{})
[2018-03-23 00:17:31,921: DEBUG/MainProcess] Task accepted: awx.main.tasks.awx_periodic_scheduler[c0466b22-2a05-4ac1-868c-0c28b34d0980] pid:20372
2018-03-23 00:17:31,935 DEBUG    awx.main.tasks Last scheduler run was: 2018-03-23 00:17:01.909449+00:00
[2018-03-23 00:17:31,960: INFO/MainProcess] Task awx.main.tasks.awx_periodic_scheduler[c0466b22-2a05-4ac1-868c-0c28b34d0980] succeeded in 0.0399558200006s: None
[2018-03-23 00:17:31,973: INFO/Beat] Scheduler: Sending due task task_manager (awx.main.scheduler.tasks.run_task_manager)
[2018-03-23 00:17:31,974: DEBUG/Beat] awx.main.scheduler.tasks.run_task_manager sent. id->0b292032-d685-4beb-a953-9b5fe6e6c812
[2018-03-23 00:17:31,975: DEBUG/Beat] beat: Waking up in 18.41 seconds.
[2018-03-23 00:17:31,975: INFO/MainProcess] Received task: awx.main.scheduler.tasks.run_task_manager[0b292032-d685-4beb-a953-9b5fe6e6c812] expires:[2018-03-23 00:17:51.974214+00:00]
[2018-03-23 00:17:31,976: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x30f8aa0> (args:(u'awx.main.scheduler.tasks.run_task_manager', u'0b292032-d685-4beb-a953-9b5fe6e6c812', [], {}, {u'utc': True, u'is_eager': False, u'chord': None, u'group': None, u'args': [], u'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': False, u'routing_key': u'tower', u'exchange': u'tower'}, u'expires': u'2018-03-23T00:17:51.974214+00:00', u'hostname': 'celery@awx', u'task': u'awx.main.scheduler.tasks.run_task_manager', u'callbacks': None, u'correlation_id': u'0b292032-d685-4beb-a953-9b5fe6e6c812', u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'reply_to': u'ebf3eb54-7a03-3352-a5e6-df53ebd2ceb6', u'id': u'0b292032-d685-4beb-a953-9b5fe6e6c812', u'headers': {}}) kwargs:{})
[2018-03-23 00:17:31,977: DEBUG/MainProcess] Task accepted: awx.main.scheduler.tasks.run_task_manager[0b292032-d685-4beb-a953-9b5fe6e6c812] pid:20372
2018-03-23 00:17:31,989 DEBUG    awx.main.scheduler Running Tower task manager.
2018-03-23 00:17:31,997 DEBUG    awx.main.scheduler Starting Scheduler
2018-03-23 00:17:32,187 WARNING  awx.main.models.unified_jobs Fields set(['extra_vars']) are not allowed as overrides.
[2018-03-23 00:17:32,187: WARNING/Worker-445] Fields set(['extra_vars']) are not allowed as overrides.
2018-03-23 00:17:32,219 ERROR    awx.main.scheduler Task awx.main.scheduler.tasks.run_task_manager encountered exception.
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/scheduler/tasks.py", line 37, in run_task_manager
    TaskManager().schedule()
  File "/usr/lib/python2.7/site-packages/awx/main/scheduler/task_manager.py", line 629, in schedule
    finished_wfjs = self._schedule()
  File "/usr/lib/python2.7/site-packages/awx/main/scheduler/task_manager.py", line 614, in _schedule
    self.spawn_workflow_graph_jobs(running_workflow_tasks)
  File "/usr/lib/python2.7/site-packages/awx/main/scheduler/task_manager.py", line 196, in spawn_workflow_graph_jobs
    job = spawn_node.unified_job_template.create_unified_job(**kv)
  File "/usr/lib/python2.7/site-packages/awx/main/models/inventory.py", line 1500, in create_unified_job
    return super(InventorySource, self).create_unified_job(**kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/models/unified_jobs.py", line 393, in create_unified_job
    unified_job.create_config_from_prompts(kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/models/unified_jobs.py", line 880, in create_config_from_prompts
    raise Exception('Unrecognized launch config field {}.'.format(field_name))
Exception: Unrecognized launch config field survey_passwords.
```

**Comment by AlanCoding** [comment]
Related to https://github.com/ansible/awx/pull/1036

**Comment by soloman747** [comment]
To anyone else experiencing this problem, I've fabricated a workaround:

1) If you have a stuck unified workflow job, follow the advice from https://github.com/ansible/awx/issues/888

"
![image](https://user-images.githubusercontent.com/29128098/37839944-c98373fc-2e89-11e8-98f7-8f935187cbc2.png)"

2) Do remove all inventory sync or project SCM update steps from your workflow. Instead, add steps in your playbooks to send webhooks to the inventory sync or project SCM update URLs via the awx API. You can create a dummy user with credentials, limiting their scope to only have "update" permissions to those API urls. It's a messy solution but it works. I'm able to perform inventory syncs and project SCM updates in unified workflows using this method.

Good luck!
