### ISSUE TITLE
Inventory sources are not editable with LDAP-managed Organization Admin AWX users

### ISSUE THREAD

**Issue by acesaro** [ansible/awx#1664]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY
After creating an inventory source (EC2 type is the problem, but the issue occurs with other types as well) with an LDAP-managed AWX user (that is an Organization admin), an error appears when attempting to edit that inventory source.  The inventory source _can_ be edited by the local "admin" AWX user after that point.  This forces the LDAP-managed AWX user to have to recreate the inventory source to make any changes.

##### ENVIRONMENT
* AWX version: 1.0.4.125
* AWX install method: docker on AWS ECS
* Ansible version:  2.4.3.0
* Operating System: in container: CentOS Linux release 7.4.1708 (Core), docker host: Amazon Linux AMI 2017.09
* Web Browser: Firefox 59.0.1

##### STEPS TO REPRODUCE

1. Create an inventory.
2. Create an inventory source in the previously created inventory.  Use the Amazon Web Services credential type and enter other required attribute values.
3. Edit the previously created inventory source (change the Description value, for example) and notice that an error appears and the change does not apply.

##### EXPECTED RESULTS

The inventory source should save any changes made without an error that pops up.

##### ACTUAL RESULTS

1. Editing the inventory source results in a modal pop-up error in the UI like:
<img width="587" alt="image" src="https://user-images.githubusercontent.com/236515/37838521-7e41733a-2e8e-11e8-9df0-d014bb905538.png">

2. The resulting log in the awx_web container from this API call:

```
2018-03-23 15:38:36,900 ERROR    django.request Internal Server Error: /api/v2/inventory_sources/25/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 65, in _legacy_get_response
    return super(AWXWSGIHandler, self)._legacy_get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 284, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 257, in put
    return self.update(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 741, in update
    return super(RetrieveUpdateAPIView, self).update(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/mixins.py", line 67, in update
    instance = self.get_object()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 101, in get_object
    self.check_object_permissions(self.request, obj)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 344, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
  File "/usr/lib/python2.7/site-packages/awx/api/permissions.py", line 138, in has_object_permission
    return self.has_permission(request, view, obj)
  File "/usr/lib/python2.7/site-packages/awx/api/permissions.py", line 129, in has_permission
    response = self.check_permissions(request, view, obj)
  File "/usr/lib/python2.7/site-packages/awx/api/permissions.py", line 118, in check_permissions
    result = check_method and check_method(request, view, obj)
  File "/usr/lib/python2.7/site-packages/awx/api/permissions.py", line 82, in check_put_permissions
    request.data)
  File "/usr/lib/python2.7/site-packages/awx/main/access.py", line 117, in check_user_access
    result = access_method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/access.py", line 157, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/access.py", line 931, in can_change
    self.check_related('credential', Credential, data, obj=obj, role_field='use_role') and
  File "/usr/lib/python2.7/site-packages/awx/main/access.py", line 290, in check_related
    if current and (changed or mandatory) and (not user_has_resource_access(current)):
  File "/usr/lib/python2.7/site-packages/awx/main/access.py", line 283, in user_has_resource_access
    access_method_type = {'admin_role': 'change', 'execute_role': 'start'}[role_field]
KeyError: 'use_role'
```

3. Notice that the changes made have not applied to the inventory source.

##### ADDITIONAL INFORMATION

Included above in ACTUAL RESULTS

**Comment by acesaro** [comment]
I was able to workaround this by mapping an LDAP group that the user is part of to be a superuser (with `AUTH_LDAP_USER_FLAGS_BY_GROUP = { 'is_superuser': '<group DN>'}`).  Obviously this is still not working, as this user is an Organizational admin and originally created the inventory source but can no longer edit it.
