### ISSUE TITLE
RuntimeError: project local_path ntpdate cannot be found in /var/lib/awx/projects

### ISSUE THREAD

**Issue by ChuckPerry** [ansible/awx#1743]
ISSUE TYPE
-- Bug Report

COMPONENT NAME
-- UI

SUMMARY
After creating my project and job_template  without any issue.when I ran the job,It told me the messages below.
--- message ---
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 897, in run
cwd = self.build_cwd(instance, **kwargs)
File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 1260, in build_cwd
(job.project.local_path, root))
RuntimeError: project local_path ntpdate cannot be found in /var/lib/awx/projects
--- message ---

ENVIRONMENT
AWX version: 1.0.4.124
AWX install method: docker on centos7.3
Ansible version: 2.4.2.0

DETAILS
STATUS  Error
STARTED 2018/4/10 13:52:21
FINISHED 2018/4/10 13:52:22
RESULTS TRACEBACK
Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 897, in run cwd = self.build_cwd(instance, **kwargs) File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 1260, in build_cwd (job.project.local_path, root)) RuntimeError: project local_path ntpdate cannot be found in /var/lib/awx/projects
TEMPLATE ntp_test
JOB TYPE Run
LAUNCHED BY admin
INVENTORY all_servers
PROJECT ntpdate
PLAYBOOK ntpdate.yml
MACHINE CREDENTIAL ansible
FORKS 0
VERBOSITY 1 (Verbose)
INSTANCE GROUP tower
EXTRA VARIABLES 

logs here

[2018-04-10 06:03:51,084: INFO/Beat] Scheduler: Sending due task cluster_heartbeat (awx.main.tasks.cluster_node_heartbeat)
[2018-04-10 06:03:51,086: DEBUG/Beat] awx.main.tasks.cluster_node_heartbeat sent. id->fa90e0ac-d3b9-47b2-8bc1-9392cec89ae5
[2018-04-10 06:03:51,087: DEBUG/Beat] beat: Waking up in 8.06 seconds.
[2018-04-10 06:03:51,117: INFO/MainProcess] Received task: awx.main.tasks.cluster_node_heartbeat[fa90e0ac-d3b9-47b2-8bc1-9392cec89ae5] expires:[2018-04-10 06:04:41.085604+00:00]
[2018-04-10 06:03:51,117: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x247eb18> (args:(u'awx.main.tasks.cluster_node_heartbeat', u'fa90e0ac-d3b9-47b2-8bc1-9392cec89ae5', [], {}, {u'utc': True, u'is_eager': False, u'chord': None, u'group': None, u'args': [], u'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': False, u'routing_key': u'awx', u'exchange': u'awx'}, u'expires': u'2018-04-10T06:04:41.085604+00:00', u'hostname': 'celery@awx', u'task': u'awx.main.tasks.cluster_node_heartbeat', u'callbacks': None, u'correlation_id': u'fa90e0ac-d3b9-47b2-8bc1-9392cec89ae5', u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'reply_to': u'0886b66b-8ad0-3531-8f84-1d5d94419003', u'id': u'fa90e0ac-d3b9-47b2-8bc1-9392cec89ae5', u'headers': {}}) kwargs:{})
[2018-04-10 06:03:51,123: DEBUG/MainProcess] Task accepted: awx.main.tasks.cluster_node_heartbeat[fa90e0ac-d3b9-47b2-8bc1-9392cec89ae5] pid:2439
2018-04-10 06:03:51,134 DEBUG    awx.main.tasks Cluster node heartbeat task.
[2018-04-10 06:03:51,169: DEBUG/Worker-231] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2018 Pivotal Software, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'connection.blocked': True, u'authentication_failure_close': True, u'direct_reply_to': True, u'basic.nack': True, u'per_consumer_qos': True, u'consumer_priorities': True, u'consumer_cancel_notify': True, u'publisher_confirms': True}, u'cluster_name': u'rabbit@a25cfe4079e7', u'platform': u'Erlang/OTP 20.1.7', u'version': u'3.7.4'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2018-04-10 06:03:51,177: DEBUG/Worker-231] Open OK!
[2018-04-10 06:03:51,178: DEBUG/Worker-231] using channel_id: 1
[2018-04-10 06:03:51,180: DEBUG/Worker-231] Channel open
[2018-04-10 06:03:51,193: INFO/MainProcess] Received task: awx.main.tasks.handle_ha_toplogy_changes[cb34c77b-57c2-4802-b7f7-699bba1c47ff]
[2018-04-10 06:03:51,194: INFO/MainProcess] Scaling up 1 processes.
[2018-04-10 06:03:51,195: DEBUG/Worker-231] Closed channel #1
[2018-04-10 06:03:51,356: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x247eb18> (args:(u'awx.main.tasks.handle_ha_toplogy_changes', u'cb34c77b-57c2-4802-b7f7-699bba1c47ff', [], {}, {u'utc': True, u'is_eager': False, u'chord': None, u'group': None, u'args': [], u'retries': 0, u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'', u'exchange': u'tower_broadcast_all'}, u'expires': None, u'hostname': 'celery@awx', u'task': u'awx.main.tasks.handle_ha_toplogy_changes', u'callbacks': None, u'correlation_id': u'cb34c77b-57c2-4802-b7f7-699bba1c47ff', u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'reply_to': u'0889ae18-3454-320a-bae6-0b36aeda5735', u'id': u'cb34c77b-57c2-4802-b7f7-699bba1c47ff', u'headers': {}}) kwargs:{})
[2018-04-10 06:03:51,358: DEBUG/MainProcess] basic.qos: prefetch_count->2772
[2018-04-10 06:03:51,362: INFO/MainProcess] Task awx.main.tasks.cluster_node_heartbeat[fa90e0ac-d3b9-47b2-8bc1-9392cec89ae5] succeeded in 0.242688990998s: None
[2018-04-10 06:03:51,365: DEBUG/MainProcess] Task accepted: awx.main.tasks.handle_ha_toplogy_changes[cb34c77b-57c2-4802-b7f7-699bba1c47ff] pid:2439
2018-04-10 06:03:51,379 DEBUG    awx.main.tasks Reconfigure celeryd queues task on host celery@awx
[2018-04-10 06:03:51,397: DEBUG/Worker-231] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2018 Pivotal Software, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'connection.blocked': True, u'authentication_failure_close': True, u'direct_reply_to': True, u'basic.nack': True, u'per_consumer_qos': True, u'consumer_priorities': True, u'consumer_cancel_notify': True, u'publisher_confirms': True}, u'cluster_name': u'rabbit@a25cfe4079e7', u'platform': u'Erlang/OTP 20.1.7', u'version': u'3.7.4'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2018-04-10 06:03:51,399: DEBUG/Worker-231] Open OK!
[2018-04-10 06:03:51,399: DEBUG/Worker-231] using channel_id: 1
[2018-04-10 06:03:51,416: DEBUG/Worker-231] Channel open
[2018-04-10 06:03:51,422: DEBUG/MainProcess] pidbox received method active_queues() [reply_to:{u'routing_key': u'5b226a8c-0b83-32fd-8bd6-3c89c8bbda6e', u'exchange': u'reply.celery.pidbox'} ticket:04716f1b-f7b6-4267-9f69-5fede7944659]
[2018-04-10 06:03:51,427: DEBUG/Worker-231] Closed channel #1
2018-04-10 06:03:51,429 INFO     awx.main.tasks Workers on tower node 'awx' removed from queues [] and added to queues []
2018-04-10 06:03:51,432 INFO     awx.main.tasks Worker on tower node 'awx' updated celery routes {'awx.main.tasks.purge_old_stdout_files': {'queue': 'awx', 'routing_key': 'awx'}, 'awx.main.tasks.cluster_node_heartbeat': {'queue': 'awx', 'routing_key': 'awx'}} all routes are now {'awx.main.tasks.purge_old_stdout_files': {'queue': 'awx', 'routing_key': 'awx'}, 'awx.main.tasks.cluster_node_heartbeat': {'queue': 'awx', 'routing_key': 'awx'}}
[2018-04-10 06:03:51,437: INFO/MainProcess] Task awx.main.tasks.handle_ha_toplogy_changes[cb34c77b-57c2-4802-b7f7-699bba1c47ff] succeeded in 0.073682096001s: None
[2018-04-10 06:03:52,692: INFO/MainProcess] Received task: awx.main.tasks.update_inventory_computed_fields[717defce-261b-4156-b5d1-9183352cca6b]
[2018-04-10 06:03:52,693: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x247eb18> (args:(u'awx.main.tasks.update_inventory_computed_fields', u'717defce-261b-4156-b5d1-9183352cca6b', [3, True], {}, {u'utc': True, u'is_eager': False, u'chord': None, u'group': None, u'args': [3, True], u'retries': 0, u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'tower', u'exchange': u'tower'}, u'expires': None, u'hostname': 'celery@awx', u'task': u'awx.main.tasks.update_inventory_computed_fields', u'callbacks': None, u'correlation_id': u'717defce-261b-4156-b5d1-9183352cca6b', u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'reply_to': u'1824db10-77b7-34af-9def-6b39b732d388', u'id': u'717defce-261b-4156-b5d1-9183352cca6b', u'headers': {}}) kwargs:{})
[2018-04-10 06:03:52,694: DEBUG/MainProcess] Task accepted: awx.main.tasks.update_inventory_computed_fields[717defce-261b-4156-b5d1-9183352cca6b] pid:2440
2018-04-10 06:03:52,727 DEBUG    awx.main.models.inventory Going to update inventory computed fields
[2018-04-10 06:03:52,727: DEBUG/Worker-232] Going to update inventory computed fields
2018-04-10 06:03:52,864 DEBUG    awx.main.models.inventory Finished updating inventory computed fields
[2018-04-10 06:03:52,864: DEBUG/Worker-232] Finished updating inventory computed fields
[2018-04-10 06:03:52,868: INFO/MainProcess] Task awx.main.tasks.update_inventory_computed_fields[717defce-261b-4156-b5d1-9183352cca6b] succeeded in 0.174904447002s: None
[2018-04-10 06:03:53,016: INFO/MainProcess] Received task: awx.main.scheduler.tasks.run_job_launch[edfeccbd-c7f9-4f21-9c60-cff38c5eae35]
[2018-04-10 06:03:53,016: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x247eb18> (args:(u'awx.main.scheduler.tasks.run_job_launch', u'edfeccbd-c7f9-4f21-9c60-cff38c5eae35', [46], {}, {u'utc': True, u'is_eager': False, u'chord': None, u'group': None, u'args': [46], u'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': False, u'routing_key': u'tower', u'exchange': u'tower'}, u'expires': None, u'hostname': 'celery@awx', u'task': u'awx.main.scheduler.tasks.run_job_launch', u'callbacks': None, u'correlation_id': u'edfeccbd-c7f9-4f21-9c60-cff38c5eae35', u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'reply_to': u'1824db10-77b7-34af-9def-6b39b732d388', u'id': u'edfeccbd-c7f9-4f21-9c60-cff38c5eae35', u'headers': {}}) kwargs:{})
[2018-04-10 06:03:53,017: DEBUG/MainProcess] Task accepted: awx.main.scheduler.tasks.run_job_launch[edfeccbd-c7f9-4f21-9c60-cff38c5eae35] pid:2439
2018-04-10 06:03:53,039 DEBUG    awx.main.scheduler Starting Scheduler
2018-04-10 06:03:53,113 DEBUG    awx.main.scheduler Starting job 46 (pending) in group tower (remaining_capacity=18)
2018-04-10 06:03:53,128 INFO     awx.main.scheduler Submitting job 46 (waiting) to instance group 1.
2018-04-10 06:03:53,189 DEBUG    awx.main.scheduler job 46 (waiting) consumed 5 capacity units from tower with prior total of 0
[2018-04-10 06:03:53,220: DEBUG/Worker-231] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2018 Pivotal Software, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'connection.blocked': True, u'authentication_failure_close': True, u'direct_reply_to': True, u'basic.nack': True, u'per_consumer_qos': True, u'consumer_priorities': True, u'consumer_cancel_notify': True, u'publisher_confirms': True}, u'cluster_name': u'rabbit@a25cfe4079e7', u'platform': u'Erlang/OTP 20.1.7', u'version': u'3.7.4'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2018-04-10 06:03:53,221: DEBUG/Worker-231] Open OK!
[2018-04-10 06:03:53,221: DEBUG/Worker-231] using channel_id: 1
[2018-04-10 06:03:53,222: DEBUG/Worker-231] Channel open
[2018-04-10 06:03:53,231: DEBUG/Worker-231] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2018 Pivotal Software, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'connection.blocked': True, u'authentication_failure_close': True, u'direct_reply_to': True, u'basic.nack': True, u'per_consumer_qos': True, u'consumer_priorities': True, u'consumer_cancel_notify': True, u'publisher_confirms': True}, u'cluster_name': u'rabbit@a25cfe4079e7', u'platform': u'Erlang/OTP 20.1.7', u'version': u'3.7.4'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2018-04-10 06:03:53,234: DEBUG/Worker-231] Open OK!
[2018-04-10 06:03:53,234: DEBUG/Worker-231] using channel_id: 1
[2018-04-10 06:03:53,235: DEBUG/Worker-231] Channel open
[2018-04-10 06:03:53,276: DEBUG/Worker-231] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2018 Pivotal Software, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'connection.blocked': True, u'authentication_failure_close': True, u'direct_reply_to': True, u'basic.nack': True, u'per_consumer_qos': True, u'consumer_priorities': True, u'consumer_cancel_notify': True, u'publisher_confirms': True}, u'cluster_name': u'rabbit@a25cfe4079e7', u'platform': u'Erlang/OTP 20.1.7', u'version': u'3.7.4'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2018-04-10 06:03:53,285: DEBUG/Worker-231] Open OK!
[2018-04-10 06:03:53,285: DEBUG/Worker-231] using channel_id: 1
[2018-04-10 06:03:53,288: DEBUG/Worker-231] Channel open
[2018-04-10 06:03:53,300: DEBUG/Worker-231] Closed channel #1
[2018-04-10 06:03:53,302: INFO/MainProcess] Received task: awx.main.tasks.run_job[a8d4cfe9-08f9-4403-ade3-c01d670f1c8c]
[2018-04-10 06:03:53,302: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x247eb18> (args:(u'awx.main.tasks.run_job', u'a8d4cfe9-08f9-4403-ade3-c01d670f1c8c', [46], {}, {u'utc': True, u'is_eager': False, u'chord': None, u'group': None, u'args': [46], u'retries': 0, u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'tower', u'exchange': u'tower'}, u'expires': None, u'hostname': 'celery@awx', u'task': u'awx.main.tasks.run_job', u'callbacks': [{u'chord_size': None, u'task': u'awx.main.tasks.handle_work_success', u'args': [], u'immutable': False, u'subtask_type': None, u'kwargs': {u'task_actual': {u'type': u'job', u'id': 46}}, u'options': {}}], u'correlation_id': u'a8d4cfe9-08f9-4403-ade3-c01d670f1c8c', u'errbacks': [{u'chord_size': None, u'task': u'awx.main.tasks.handle_work_error', u'args': [], u'immutable': False, u'subtask_type': None, u'kwargs': {u'subtasks': [{u'type': u'job', u'id': 46}]}, u'options': {}}], u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'reply_to': u'0889ae18-3454-320a-bae6-0b36aeda5735', u'id':... kwargs:{})
[2018-04-10 06:03:53,305: DEBUG/MainProcess] Task accepted: awx.main.tasks.run_job[a8d4cfe9-08f9-4403-ade3-c01d670f1c8c] pid:2440
[2018-04-10 06:03:53,345: INFO/MainProcess] Task awx.main.scheduler.tasks.run_job_launch[edfeccbd-c7f9-4f21-9c60-cff38c5eae35] succeeded in 0.329042657s: None
[2018-04-10 06:03:53,619: DEBUG/Worker-232] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2018 Pivotal Software, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'connection.blocked': True, u'authentication_failure_close': True, u'direct_reply_to': True, u'basic.nack': True, u'per_consumer_qos': True, u'consumer_priorities': True, u'consumer_cancel_notify': True, u'publisher_confirms': True}, u'cluster_name': u'rabbit@a25cfe4079e7', u'platform': u'Erlang/OTP 20.1.7', u'version': u'3.7.4'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2018-04-10 06:03:53,620: DEBUG/Worker-232] Open OK!
[2018-04-10 06:03:53,620: DEBUG/Worker-232] using channel_id: 1
[2018-04-10 06:03:53,622: DEBUG/Worker-232] Channel open
[2018-04-10 06:03:53,639: DEBUG/Worker-232] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2018 Pivotal Software, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'connection.blocked': True, u'authentication_failure_close': True, u'direct_reply_to': True, u'basic.nack': True, u'per_consumer_qos': True, u'consumer_priorities': True, u'consumer_cancel_notify': True, u'publisher_confirms': True}, u'cluster_name': u'rabbit@a25cfe4079e7', u'platform': u'Erlang/OTP 20.1.7', u'version': u'3.7.4'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2018-04-10 06:03:53,642: DEBUG/Worker-232] Open OK!
[2018-04-10 06:03:53,642: DEBUG/Worker-232] using channel_id: 1
[2018-04-10 06:03:53,644: DEBUG/Worker-232] Channel open
2018-04-10 06:03:54,336 ERROR    awx.main.tasks Error flushing job stdout and saving event count.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 975, in run
    stdout_handle.flush()
UnboundLocalError: local variable 'stdout_handle' referenced before assignment
[2018-04-10 06:03:54,539: DEBUG/Worker-232] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2018 Pivotal Software, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'connection.blocked': True, u'authentication_failure_close': True, u'direct_reply_to': True, u'basic.nack': True, u'per_consumer_qos': True, u'consumer_priorities': True, u'consumer_cancel_notify': True, u'publisher_confirms': True}, u'cluster_name': u'rabbit@a25cfe4079e7', u'platform': u'Erlang/OTP 20.1.7', u'version': u'3.7.4'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2018-04-10 06:03:54,541: DEBUG/Worker-232] Open OK!
[2018-04-10 06:03:54,542: DEBUG/Worker-232] using channel_id: 1
[2018-04-10 06:03:54,543: DEBUG/Worker-232] Channel open
[2018-04-10 06:03:54,547: INFO/MainProcess] Received task: awx.main.tasks.update_inventory_computed_fields[03dce3e5-f5d6-47c7-a46e-f6010c0110bd]
[2018-04-10 06:03:54,548: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x247eb18> (args:(u'awx.main.tasks.update_inventory_computed_fields', u'03dce3e5-f5d6-47c7-a46e-f6010c0110bd', [3, True], {}, {u'utc': True, u'is_eager': False, u'chord': None, u'group': None, u'args': [3, True], u'retries': 0, u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'tower', u'exchange': u'tower'}, u'expires': None, u'hostname': 'celery@awx', u'task': u'awx.main.tasks.update_inventory_computed_fields', u'callbacks': None, u'correlation_id': u'03dce3e5-f5d6-47c7-a46e-f6010c0110bd', u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'reply_to': u'0889ae18-3454-320a-bae6-0b36aeda5735', u'id': u'03dce3e5-f5d6-47c7-a46e-f6010c0110bd', u'headers': {}}) kwargs:{})
[2018-04-10 06:03:54,551: DEBUG/MainProcess] Task accepted: awx.main.tasks.update_inventory_computed_fields[03dce3e5-f5d6-47c7-a46e-f6010c0110bd] pid:2439
[2018-04-10 06:03:54,552: DEBUG/Worker-232] Closed channel #1
2018-04-10 06:03:54,595 WARNING  awx.main.tasks job 46 (error) encountered an error (rc=None), please see task stdout for details.
2018-04-10 06:03:54,605 DEBUG    awx.main.models.inventory Going to update inventory computed fields
[2018-04-10 06:03:54,605: DEBUG/Worker-231] Going to update inventory computed fields
[2018-04-10 06:03:54,636: DEBUG/Worker-232] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2018 Pivotal Software, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'connection.blocked': True, u'authentication_failure_close': True, u'direct_reply_to': True, u'basic.nack': True, u'per_consumer_qos': True, u'consumer_priorities': True, u'consumer_cancel_notify': True, u'publisher_confirms': True}, u'cluster_name': u'rabbit@a25cfe4079e7', u'platform': u'Erlang/OTP 20.1.7', u'version': u'3.7.4'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2018-04-10 06:03:54,649: DEBUG/Worker-232] Open OK!
[2018-04-10 06:03:54,650: DEBUG/Worker-232] using channel_id: 1
[2018-04-10 06:03:54,657: DEBUG/Worker-232] Channel open
[2018-04-10 06:03:54,683: INFO/MainProcess] Received task: awx.main.tasks.handle_work_error[dabb0629-a3b1-4137-a96f-e9b934c0fb4b]
[2018-04-10 06:03:54,684: INFO/MainProcess] Scaling up 1 processes.
[2018-04-10 06:03:54,687: DEBUG/Worker-232] Closed channel #1
2018-04-10 06:03:54,790 DEBUG    awx.main.models.inventory Finished updating inventory computed fields
[2018-04-10 06:03:54,790: DEBUG/Worker-231] Finished updating inventory computed fields
[2018-04-10 06:03:54,899: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x247eb18> (args:(u'awx.main.tasks.handle_work_error', u'dabb0629-a3b1-4137-a96f-e9b934c0fb4b', [u'a8d4cfe9-08f9-4403-ade3-c01d670f1c8c'], {u'subtasks': [{u'type': u'job', u'id': 46}]}, {u'utc': True, u'is_eager': False, u'chord': None, u'group': u'5a76cb5b-8b1d-4955-8cd1-841bba34d7b0', u'args': [u'a8d4cfe9-08f9-4403-ade3-c01d670f1c8c'], u'retries': 0, u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'tower', u'exchange': u'tower'}, u'expires': None, u'hostname': 'celery@awx', u'task': u'awx.main.tasks.handle_work_error', u'callbacks': None, u'correlation_id': u'dabb0629-a3b1-4137-a96f-e9b934c0fb4b', u'errbacks': None, u'timelimit': [None, None], u'taskset': u'5a76cb5b-8b1d-4955-8cd1-841bba34d7b0', u'kwargs': {u'subtasks': [{u'type': u'job', u'id': 46}]}, u'eta': None, u'reply_to': u'0889ae18-3454-320a-bae6-0b36aeda5735', u'id': u'dabb0629-a3b1-4137-a96f-e9b934c0fb4b', u'headers': {}}) kwargs:{})
[2018-04-10 06:03:54,901: DEBUG/MainProcess] basic.qos: prefetch_count->2776
[2018-04-10 06:03:54,907: ERROR/MainProcess] Task awx.main.tasks.run_job[a8d4cfe9-08f9-4403-ade3-c01d670f1c8c] raised unexpected: Exception('job 46 (error) encountered an error (rc=None), please see task stdout for details.',)
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 564, in _wrapped
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 1006, in run
    raise AwxTaskError.TaskError(instance, rc)
Exception: job 46 (error) encountered an error (rc=None), please see task stdout for details.
[2018-04-10 06:03:54,912: INFO/MainProcess] Task awx.main.tasks.update_inventory_computed_fields[03dce3e5-f5d6-47c7-a46e-f6010c0110bd] succeeded in 0.359484050001s: None
[2018-04-10 06:03:54,916: DEBUG/MainProcess] Task accepted: awx.main.tasks.handle_work_error[dabb0629-a3b1-4137-a96f-e9b934c0fb4b] pid:2440
2018-04-10 06:03:54,929 DEBUG    awx.main.tasks Executing error task id a8d4cfe9-08f9-4403-ade3-c01d670f1c8c, subtasks: [{u'type': u'job', u'id': 46}]
[2018-04-10 06:03:54,951: DEBUG/Worker-232] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2018 Pivotal Software, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'connection.blocked': True, u'authentication_failure_close': True, u'direct_reply_to': True, u'basic.nack': True, u'per_consumer_qos': True, u'consumer_priorities': True, u'consumer_cancel_notify': True, u'publisher_confirms': True}, u'cluster_name': u'rabbit@a25cfe4079e7', u'platform': u'Erlang/OTP 20.1.7', u'version': u'3.7.4'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2018-04-10 06:03:54,955: DEBUG/Worker-232] Open OK!
[2018-04-10 06:03:54,955: DEBUG/Worker-232] using channel_id: 1
[2018-04-10 06:03:54,957: DEBUG/Worker-232] Channel open
[2018-04-10 06:03:54,962: DEBUG/Worker-232] Closed channel #1
[2018-04-10 06:03:54,968: INFO/MainProcess] Received task: awx.main.scheduler.tasks.run_job_complete[b2087d3d-b02d-4fe0-b6d9-9137abfe0cd0]
[2018-04-10 06:03:54,969: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x247eb18> (args:(u'awx.main.scheduler.tasks.run_job_complete', u'b2087d3d-b02d-4fe0-b6d9-9137abfe0cd0', [46], {}, {u'utc': True, u'is_eager': False, u'chord': None, u'group': None, u'args': [46], u'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': False, u'routing_key': u'tower', u'exchange': u'tower'}, u'expires': None, u'hostname': 'celery@awx', u'task': u'awx.main.scheduler.tasks.run_job_complete', u'callbacks': None, u'correlation_id': u'b2087d3d-b02d-4fe0-b6d9-9137abfe0cd0', u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'reply_to': u'0889ae18-3454-320a-bae6-0b36aeda5735', u'id': u'b2087d3d-b02d-4fe0-b6d9-9137abfe0cd0', u'headers': {}}) kwargs:{})
[2018-04-10 06:03:54,973: DEBUG/MainProcess] Task accepted: awx.main.scheduler.tasks.run_job_complete[b2087d3d-b02d-4fe0-b6d9-9137abfe0cd0] pid:2439
[2018-04-10 06:03:54,976: INFO/MainProcess] Task awx.main.tasks.handle_work_error[dabb0629-a3b1-4137-a96f-e9b934c0fb4b] succeeded in 0.0626770669987s: None
2018-04-10 06:03:55,001 DEBUG    awx.main.scheduler Starting Scheduler
[2018-04-10 06:03:55,046: INFO/MainProcess] Task awx.main.scheduler.tasks.run_job_complete[b2087d3d-b02d-4fe0-b6d9-9137abfe0cd0] succeeded in 0.076630298001s: None

**Comment by ryanpetrello** [comment]
@ChuckPerry,

Are you managing your project manually, or via a git/hg/subversion/ clone?

My guess as to what's happening here is that you've set up a manual project and haven't placed the playbooks on _every_ file system at `/var/lib/awx/projects/`

**Comment by ChuckPerry** [comment]
yes,first,I got this package from git clone.
and I wrote a local yaml on my /var/lib/awx/projects/
this‘s my file:

[root@node04 ~]# docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                                 NAMES
ec218f40a1f3        ansible/awx_task:latest      "/tini -- /bin/sh -c…"   2 weeks ago         Up 4 seconds        8052/tcp                                              awx_task
c392079ecc19        ansible/awx_web:latest       "/tini -- /bin/sh -c…"   2 weeks ago         Up 5 seconds        0.0.0.0:8088->8052/tcp                                awx_web
8ed7f3752599        memcached:alpine             "docker-entrypoint.s…"   2 weeks ago         Up 5 seconds        11211/tcp                                             memcached
a25cfe4079e7        ansible/awx_rabbitmq:3.7.4   "docker-entrypoint.s…"   2 weeks ago         Up 5 seconds        4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp   rabbitmq
78e6c2dd8d9d        postgres:9.6                 "docker-entrypoint.s…"   2 weeks ago         Up 5 seconds        5432/tcp                                              postgres
[root@node04 ~]# docker exec -it c392079ecc19 /bin/bash
[root@awxweb awx]# ll /var/lib/awx/projects/ntpdate/ntpdate.yml 
-rw-r--r-- 1 root root 179 Apr 10 03:26 /var/lib/awx/projects/ntpdate/ntpdate.yml
[root@awxweb awx]# cat /var/lib/awx/projects/ntpdate/ntpdate.yml
---
- hosts: all
  gather_facts: no
 
  tasks:
  - name: Check the date on the server.
    command: date
  - name: sync the date from network
    command: ntpdate ntp1.aliyun.com 


and my configration like this:

[root@node04 ~]# cat /home/ansible/awx/installer/inventory |egrep -v '^$|#'
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"
[all:vars]
dockerhub_base=ansible
dockerhub_version=latest
postgres_data_dir=/var/lib/pgdocker
host_port=8088
docker_compose_dir=/var/lib/awx
pg_username=awx
pg_password=Acoh4Isah8dieng
pg_database=awx
pg_port=5432
default_admin_user=admin
default_admin_password=Wei5eelienequei
awx_secret_key=HLRp33hwoReOakEyhiaZb9gTH999A8
awx_official=true

**Comment by ChuckPerry** [comment]
Oh,I see.
I put it in a wrong place.
I need create yaml in awx_task container.
Sorry for my misunderstand.

**Comment by wenottingham** [comment]
Closing, then.
