### ISSUE TITLE
Radius auth broken

### ISSUE THREAD

**Issue by haught** [ansible/awx#1758]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
Enabling radius authentication causes error and locks out all users including admin

##### ENVIRONMENT
* AWX version: 1.5.0 and devel (1.5.23)
* AWX install method: docker on linux, docker for mac
* Ansible version:  2.5.0
* Operating System: Linux - Docker
* Web Browser: N/A

##### STEPS TO REPRODUCE

In Settings->Authentication->Radius set a hostname/port/secret

##### EXPECTED RESULTS

Radius auth would work or at least the admin user would be able to log in

##### ACTUAL RESULTS

All users locked out.

##### ADDITIONAL INFORMATION

Setting django-radius==1.1.0 in requirements instead of 1.3.3 allows radius auth to work. (Introduced in https://github.com/ansible/awx/commit/556e6c4a117597fc36fdab53b32a4e29ed494a34 )

Error log:
2018-04-12 02:41:38,386 ERROR    django.request Internal Server Error: /api/login/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 65, in _legacy_get_response
    return super(AWXWSGIHandler, self)._legacy_get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/contrib/auth/views.py", line 90, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 67, in post
    ret = super(LoggedLoginView, self).post(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/edit.py", line 182, in post
    if form.is_valid():
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/forms/forms.py", line 183, in is_valid
    return self.is_bound and not self.errors
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/forms/forms.py", line 385, in full_clean
    self._clean_form()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/forms/forms.py", line 412, in _clean_form
    cleaned_data = self.clean()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/contrib/auth/forms.py", line 187, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 70, in authenticate
    user = _authenticate_with_backend(backend, backend_path, request, credentials)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 116, in _authenticate_with_backend
    return backend.authenticate(*args, **credentials)
  File "/usr/lib/python2.7/site-packages/awx/sso/backends.py", line 191, in authenticate
    return super(RADIUSBackend, self).authenticate(username, password)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/radiusauth/backends/radius.py", line 178, in authenticate
    result = self._radius_auth(server, username, password)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/radiusauth/backends/radius.py", line 146, in _radius_auth
    packet = self._get_auth_packet(username, password, client)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/radiusauth/backends/radius.py", line 82, in _get_auth_packet
    pkt["User-Password"] = pkt.PwCrypt(password)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/pyrad/packet.py", line 500, in PwCrypt
    if len(password) % 16 != 0:
TypeError: object of type 'NoneType' has no len()

**Comment by doves99** [comment]
Is there anyway to undo the Radius Authentication after it is broken via CLI?.  Or a file that can be erased and restart the AWX?

**Comment by rooftopcellist** [comment]
@doves99 you should be able to unset the radius URL and client_secret in AWX settings via the UI or manually (if you are in a docker dev build, this will be found in defaults.py).  AWX should automatically stop using radius to authenticate.  

As a temporary work around: 
It looks like the last place our code touches this is [here](https://github.com/ansible/awx/blob/devel/awx/sso/backends.py#L191).  Adding something like this here could at least keep it from blocking out the other auth backends.  I'll have to set up an OpenRadius server or something to get any further with this though.  

```
        try:    
            auth_res = super(RADIUSBackend, self).authenticate(username, password)
        except: auth_res = None
        return auth_res
```

**Comment by doves99** [comment]
https://github.com/ansible/tower/blob/devel/awx/sso/backends.py#L191 link doesn't work.

**Comment by ryanpetrello** [comment]
This issue should now be resolved via https://github.com/ansible/awx/commit/90308066af9000bf72cc1167a8ebb977eb43fc6a

**Comment by rooftopcellist** [comment]
@doves99 The link is fixed in my previous comment, and also present in the latest code.
