### ISSUE TITLE
Fail getting SAML Metadata

### ISSUE THREAD

**Issue by ken5scal** [ansible/awx#1834]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
- Accessing "SAML Service Provider Metadata URL" returns 502 

##### ENVIRONMENT
* AWX version: 1.0.4
* AWX install method: docker on linux (using default image)
* Ansible version:  2.4.3.0 
* Operating System: Amazon Linux 2
* Web Browser: Google Chrome (Secret Mode)

##### STEPS TO REPRODUCE
* Set Accordingly
![image](https://user-images.githubusercontent.com/9734362/39505453-51552a26-4e0d-11e8-8eba-f9de4fd263cd.png)
![image](https://user-images.githubusercontent.com/9734362/39505476-81c074b8-4e0d-11e8-8161-a6d7b799ae76.png)

```
{
"okta": {
  "entity_id": "http://www.okta.com/{hidden}",
  "url": "https://{hidden}.okta.com/app/awx_1/{hidden}/sso/saml",
  "x509cert": "{hidden}"
  }
}
```

* Hit `Save` 

* Access `https://{hidden}/sso/metadata/saml/`
* Returns 502 Bad Gateway

##### EXPECTED RESULTS
Able to see SAML Metadata

##### ACTUAL RESULTS
502 Bad Gateway

##### ADDITIONAL INFORMATION
* here is the log, and it seems I am "MissingBackend: Missing backend "saml" entry
"; but not sure where I need to specify the entry.

```
2018-05-02 05:08:52,785 ERROR    django.request Internal Server Error: /sso/metadata/saml/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 65, in _legacy_get_response
    return super(AWXWSGIHandler, self)._legacy_get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/sso/views.py", line 58, in get
    redirect_uri=complete_url,
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/utils.py", line 27, in load_backend
    Backend = get_backend(BACKENDS, name)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_core/backends/utils.py", line 57, in get_backend
    raise MissingBackend(name)
MissingBackend: Missing backend "saml" entry
2018-05-02 05:08:52,785 ERROR    django.request Internal Server Error: /sso/metadata/saml/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 65, in _legacy_get_response
    return super(AWXWSGIHandler, self)._legacy_get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/sso/views.py", line 58, in get
    redirect_uri=complete_url,
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/utils.py", line 27, in load_backend
    Backend = get_backend(BACKENDS, name)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_core/backends/utils.py", line 57, in get_backend
    raise MissingBackend(name)
MissingBackend: Missing backend "saml" entry
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 143, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/usr/lib/python2.7/site-packages/awx/main/views.py", line 88, in handle_500
    return handle_error(request, 500, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/views.py", line 56, in handle_error
    return render(request, 'error.html', kwargs, status=status)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
10.20.200.11 - - [02/May/2018:05:08:52 +0000] "GET /sso/metadata/saml/ HTTP/1.0" 502 575 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
2018/05/02 05:08:52 [error] 25#0: *125450 upstream prematurely closed connection while reading response header from upstream, client: 10.20.200.11, server: _, request: "GET /sso/metadata/saml/ HTTP/1.0", upstream: "uwsgi://127.0.0.1:8050", host: "awx.op.folio-sec.com"
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/defaulttags.py", line 40, in render
    output = self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/defaulttags.py", line 166, in render
    values = self.sequence.resolve(context, True)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 736, in resolve
    new_obj = func(obj, *arg_vals)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/templatetags/rest_framework.py", line 243, in items
    return value.items()
AttributeError: 'NoneType' object has no attribute 'items'
[pid: 1252|app: 0|req: 530/63641] 10.20.200.11 () {52 vars in 2507 bytes} [Wed May  2 05:08:52 2018] GET /sso/metadata/saml/ => generated 0 bytes in 41 msecs (HTTP/1.0 500) 0 headers in 0 bytes (0 switches on core 0)
```

**Comment by aperigault** [comment]
Maybe have you just an error in your configuration ?
I already see AWX silently failed when I set wrong configuration.

You can also try to update to 1.0.6.0. There is many bugs in SAML before.

**Comment by ken5scal** [comment]
Fmmm, let me try updating the AWX. Tx!

**Comment by ken5scal** [comment]
> You can also try to update to 1.0.6.0.

I upgraded to 1.0.6.5, but still the sam error

**Comment by ken5scal** [comment]
Additional information: exactly the same error

```
2018-07-03 03:54:04,619 ERROR    django.request Internal Server Error: /sso/metadata/saml/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 65, in _legacy_get_response
    return super(AWXWSGIHandler, self)._legacy_get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/sso/views.py", line 63, in get
    redirect_uri=complete_url,
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/utils.py", line 27, in load_backend
    Backend = get_backend(BACKENDS, name)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_core/backends/utils.py", line 57, in get_backend
    raise MissingBackend(name)
MissingBackend: Missing backend "saml" entry
2018-07-03 03:54:04,619 ERROR    django.request Internal Server Error: /sso/metadata/saml/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 65, in _legacy_get_response
    return super(AWXWSGIHandler, self)._legacy_get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/sso/views.py", line 63, in get
    redirect_uri=complete_url,
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/utils.py", line 27, in load_backend
    Backend = get_backend(BACKENDS, name)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_core/backends/utils.py", line 57, in get_backend
    raise MissingBackend(name)
MissingBackend: Missing backend "saml" entry
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 143, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/usr/lib/python2.7/site-packages/awx/main/views.py", line 88, in handle_500
    return handle_error(request, 500, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/views.py", line 56, in handle_error
    return render(request, 'error.html', kwargs, status=status)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/defaulttags.py", line 40, in render
    output = self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/defaulttags.py", line 166, in render
    values = self.sequence.resolve(context, True)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 736, in resolve
10.20.200.11 - - [03/Jul/2018:03:54:04 +0000] "GET /sso/metadata/saml/ HTTP/1.0" 502 575 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
2018/07/03 03:54:04 [error] 28#0: *62301 upstream prematurely closed connection while reading response header from upstream, client: 10.20.200.11, server: _, request: "GET /sso/metadata/saml/ HTTP/1.0", upstream: "uwsgi://127.0.0.1:8050", host: "awx.op.folio-sec.com"
    new_obj = func(obj, *arg_vals)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/templatetags/rest_framework.py", line 243, in items
    return value.items()
AttributeError: 'NoneType' object has no attribute 'items'
[pid: 1061|app: 0|req: 174/39655] 10.20.200.11 () {52 vars in 2696 bytes} [Tue Jul  3 03:54:04 2018] GET /sso/metadata/saml/ => generated 0 bytes in 275 msecs (HTTP/1.0 500) 0 headers in 0 bytes (0 switches on core 0)
[ec2-user@ip-10-20-24-10 ~]$
```

**Comment by ken5scal** [comment]
Maybe the same one as  #1982 ?

**Comment by wenottingham** [comment]
Apologies, but there have been many chances since 1.0.6. Please try a recent release such as 2.0, and reopen if the problem persists.
