### ISSUE TITLE
Normal user failed to relaunch the workflow template

### ISSUE THREAD

**Issue by chestercheng** [ansible/awx#1838]
**ISSUE TYPE**

- Bug Report

**COMPONENT NAME**

- UI

**SUMMARY**

First, I am a normal user with execute permission for the workflow template. I successfully executed first time as following figure.

![default](https://user-images.githubusercontent.com/36478905/39513404-ccdcc208-4e26-11e8-942a-0cbad0ba7d07.JPG)

 
When I relaunched the workflow template with rocket button on the upper-right corner, UI had no any response.  I checked the log of awx_web contanier. The error is shown as below.

```bash
2018-05-02 08:13:32,160 ERROR    django.request Internal Server Error: /api/v2/workflow_jobs/255/relaunch/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 65, in _legacy_get_response
    return super(AWXWSGIHandler, self)._legacy_get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 284, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/views.py", line 3741, in post
    obj = self.get_object()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 101, in get_object
    self.check_object_permissions(self.request, obj)
  File "/usr/lib/python2.7/site-packages/awx/api/views.py", line 3732, in check_object_permissions
    relaunch_perm, messages = request.user.can_access_with_errors(self.model, 'start', obj)
  File "/usr/lib/python2.7/site-packages/awx/main/access.py", line 130, in check_user_access_with_errors
    result = access_method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/access.py", line 1926, in can_start
    return self.can_recreate(obj)
  File "/usr/lib/python2.7/site-packages/awx/main/access.py", line 1932, in can_recreate
    for node in node_qs:
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 1120, in _fetch_all
    self._prefetch_related_objects()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 675, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 1466, in prefetch_related_objects
    "prefetch_related()." % lookup.prefetch_through)
ValueError: 'credential' does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().
2018-05-02 08:13:32,160 ERROR    django.request Internal Server Error: /api/v2/workflow_jobs/255/relaunch/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 65, in _legacy_get_response
    return super(AWXWSGIHandler, self)._legacy_get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 284, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/views.py", line 3741, in post
    obj = self.get_object()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 101, in get_object
    self.check_object_permissions(self.request, obj)
  File "/usr/lib/python2.7/site-packages/awx/api/views.py", line 3732, in check_object_permissions
    relaunch_perm, messages = request.user.can_access_with_errors(self.model, 'start', obj)
  File "/usr/lib/python2.7/site-packages/awx/main/access.py", line 130, in check_user_access_with_errors
    result = access_method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/access.py", line 1926, in can_start
    return self.can_recreate(obj)
  File "/usr/lib/python2.7/site-packages/awx/main/access.py", line 1932, in can_recreate
    for node in node_qs:
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 1120, in _fetch_all
    self._prefetch_related_objects()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 675, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 1466, in prefetch_related_objects
    "prefetch_related()." % lookup.prefetch_through)
ValueError: 'credential' does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().
172.18.0.6 - - [02/May/2018:08:13:32 +0000] "POST /api/v2/workflow_jobs/255/relaunch/ HTTP/1.1" 500 41 "https://10.21.97.96/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
[pid: 31|app: 0|req: 685/3753] 172.18.0.6 () {46 vars in 2408 bytes} [Wed May  2 08:13:32 2018] POST /api/v2/workflow_jobs/255/relaunch/ => generated 41 bytes in 113 msecs(HTTP/1.1 500) 5 headers in 177 bytes (1 switches on core 0)
```

**ENVIRONMENT**

- AWX version: 1.0.5.24
- AWX install method: docker on Linux
- Ansible version: 2.4.3.0
- Operating System: Linux Ubuntu 16.04
- Web Browser: Google Chrome

**STEPS TO REPRODUCE**

1. Configure workflow template by admin
2.  Normal user logged in and successfully launched workflow template. 
3. With "Relauch" button in Jobs pages, it had no reponse and show error in awx_web console.

**EXPECTED RESULTS**

Normal user can relaunch the workflow templates.

**ACTUAL RESULTS**

Failed when relaunched.

**ADDITIONAL INFORMATION**

When I changed to admin user to execute, it can be successfully launched and relaunched.

**Comment by ryanpetrello** [comment]
@chestercheng we've just released 1.0.7, which we believe resolves the underlying issue here. You can try it out here: https://github.com/ansible/awx/releases/tag/1.0.7

Let us know if you're still seeing this issue after installing the latest awx - thanks!
