### ISSUE TITLE
Cannot import inventory in awx via ui but have no issues importing when trying to recreate problem in container

### ISSUE THREAD

**Issue by barkardk** [ansible/awx#1885]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
AWX 1.0.6.5  on kubernetes I cannot use custom inventory scripts via AWX ui that use the ansible.inventory.manager api 
I have no issues using the script via cmd from within the awx-celery pod or 
if I upload custom scripts llike mababio/test.py from here http://www.pythonexample.com/code/ansible-dynamic-inventory-hostvars/  and run it then I get my inventory succesfully imported aswell. 
I would be nice to be able to use the ansible API for parsing inventory files  instead of creating a manual json mapping from scratch
It does work actually , just not via the awx web ui

##### ENVIRONMENT
* AWX version: AWX 1.0.6.5 
* AWX install method: kubernetes
* Ansible version:  ansible 2.5.2
* Web Browser: Firefox / Chrome

##### STEPS TO REPRODUCE
I have uploaded custom inventory script
***************************
```
#!/usr/bin/env python
 
import json
import sys
import os
import argparse

from ansible.parsing.dataloader import DataLoader
from ansible.inventory.manager import InventoryManager
 
 
def main():
  parser = argparse.ArgumentParser()
  parser.add_argument('--list', action = 'store_true')
  parser.add_argument('--host', action = 'store')
  parser.add_argument('--pretty', action = 'store_true')
  args = parser.parse_args()
  loader = DataLoader()

  
  sources = '/nfs_mount/foo'

  inventory = InventoryManager(loader=loader, sources=sources) 
  inventory.parse_sources()
  out = {'_meta': {'hostvars': {}}}
  if args.list:
    for group in inventory.groups.values():
      out[group.name] = {
          'hosts': [h.name for h in group.hosts],
          'vars': group.vars,
          'children': [c.name for c in group.child_groups]
      }
    for host in inventory.get_hosts():
      out['_meta']['hostvars'][host.name] = host.vars

    print(json.dumps(out, indent=4, sort_keys=True))
 

if __name__ == "__main__":
  main() 
```

***************************
I have  file '/nfs_mount/foo' available with the following contents

> [foo]
> host1  ansible_host=192.168.1.0
> host2  ansible_host=192.168.1.1

In  awx ui /my_imported_script/sources press sync 
To try to replicate in the pod via cmd  I logon to the container in kubernetes

kubectl exec -it awx-kubernetes-pod  -c awx-celery bash -n awx
I catch the scripts  that are created in /tmp in the awx-celery container via simple for loop  while I run the sync in the UI
`_while true; do ps -ef|grep inv ; cp -rfp /tmp/awx_* .; sleep 1; done_`
I will end up with the following command 
**`/usr/bin/awx-manage inventory_import --inventory-id 19 --group-filter ^.+$ --host-filter ^.+$ --exclude-empty-groups --source /tmp/awx_inventory_OvPnsK/tmp1NGkwV --custom -v2 `**

The inventory script is now stored in my local dir as **awx_inventory_OvPnsK/tmp1NGkwV** 
inspecting **awx_inventory_OvPnsK/tmp1NGkwV**  and it looks identical to the script uploaded in the ui itself 
In the awx-celery docker container I run the command 
**`/usr/bin/awx-manage inventory_import --inventory-id 19 --group-filter ^.+$ --host-filter ^.+$ --exclude-empty-groups --source /tmp/awx_inventory_OvPnsK/tmp1NGkwV --custom -v2 `**

The sync is succesful
The sync run in cmd from the pod  will also be visible and registered as succesful in web ui as
![image](https://user-images.githubusercontent.com/2832654/40119007-cd924650-591b-11e8-87fd-7d43e2ffdc38.png)

The inventory sync in UI will crash with error error (see actual results below)
However running the command caught in the container produces successful output and the hosts are indeed available in the UI for playbook runs

Output from within the awx-celery container
```

bash-4.2$ /usr/bin/awx-manage inventory_import --inventory-id 19 --group-filter ^.+$ --host-filter ^.+$ --exclude-empty-groups --source /tmp/awx_inventory_OvPnsK/tmp1NGkwV --custom -v2
2018-05-16 13:00:37,999 INFO     awx.main.commands.inventory_import Updating inventory 19: static_inventory
2018-05-16 13:00:38,101 DEBUG    awx.main.commands.inventory_import Using system install of ansible-inventory CLI: /usr/bin/ansible-inventory
2018-05-16 13:00:38,101 INFO     awx.main.commands.inventory_import Reading Ansible inventory source: /tmp/awx_inventory_OvPnsK/tmp1NGkwV
2018-05-16 13:00:39,439 ERROR    awx.main.commands.inventory_import  [ERROR]:
2018-05-16 13:00:39,439 INFO     awx.main.commands.inventory_import Processing JSON output...
2018-05-16 13:00:39,439 DEBUG    awx.main.commands.inventory_import Loaded group: all
2018-05-16 13:00:39,439 DEBUG    awx.main.commands.inventory_import Loaded group: foo
2018-05-16 13:00:39,440 DEBUG    awx.main.commands.inventory_import Adding child group foo to parent all
2018-05-16 13:00:39,440 DEBUG    awx.main.commands.inventory_import Loaded host: host1
2018-05-16 13:00:39,440 DEBUG    awx.main.commands.inventory_import Adding host host1 to group foo
2018-05-16 13:00:39,440 DEBUG    awx.main.commands.inventory_import Loaded host: host2
2018-05-16 13:00:39,440 DEBUG    awx.main.commands.inventory_import Adding host host2 to group foo
2018-05-16 13:00:39,440 DEBUG    awx.main.commands.inventory_import Adding child group foo to parent all
2018-05-16 13:00:39,440 DEBUG    awx.main.commands.inventory_import Finished loading from source: /tmp/awx_inventory_OvPnsK/tmp1NGkwV
2018-05-16 13:00:39,440 INFO     awx.main.commands.inventory_import Loaded 1 groups, 2 hosts
2018-05-16 13:00:39,442 INFO     awx.main.commands.inventory_import Inventory variables unmodified
2018-05-16 13:00:39,453 INFO     awx.main.commands.inventory_import Group "foo" added
2018-05-16 13:00:39,468 INFO     awx.main.commands.inventory_import Host "host1" added
2018-05-16 13:00:39,472 INFO     awx.main.commands.inventory_import Host "host2" added
2018-05-16 13:00:39,493 INFO     awx.main.commands.inventory_import Host "host1" added to group "foo" 
2018-05-16 13:00:39,493 INFO     awx.main.commands.inventory_import Host "host2" added to group "foo"
2018-05-16 13:00:39,497 DEBUG    awx.main.models.inventory Going to update inventory computed fields
2018-05-16 13:00:39,581 DEBUG    awx.main.models.inventory Finished updating inventory computed fields
2018-05-16 13:00:39,582 INFO     awx.main.commands.inventory_import Inventory import completed for  (static_inventory - 28) in 1.6s


```

##### EXPECTED RESULTS

![image](https://user-images.githubusercontent.com/2832654/40118748-0fc47a1c-591b-11e8-832f-625fea5dd991.png)

##### ACTUAL RESULTS
2018-05-16 12:56:43,413 INFO     awx.main.commands.inventory_import Updating inventory 19: static_inventory
2018-05-16 12:56:43,428 DEBUG    awx.main.commands.inventory_import Using system install of ansible-inventory CLI: /usr/bin/ansible-inventory
2018-05-16 12:56:43,428 INFO     awx.main.commands.inventory_import Reading Ansible inventory source: /tmp/awx_inventory_OvPnsK/tmp1NGkwV
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==1.0.6.5', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 991, in handle
    self.is_custom)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 242, in load_inventory_source
    is_custom=is_custom).load()
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 177, in load
    data = self.command_to_json(base_args + ['--list'])
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 160, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:

stderr:
 [WARNING]:  * Failed to parse /tmp/awx_inventory_OvPnsK/tmp1NGkwV with script
plugin: Inventory script (/tmp/awx_inventory_OvPnsK/tmp1NGkwV) had an execution
error:  [WARNING]: Unable to parse /nfs_mount/foo as an
inventory source  Traceback (most recent call last):   File
"/tmp/awx_inventory_OvPnsK/tmp1NGkwV", line 35, in <module>     main()   File
"/tmp/awx_inventory_OvPnsK/tmp1NGkwV", line 18, in main     inventory =
InventoryManager(loader=loader, sources="/nfs_mount/foo")   File
"/usr/lib/python2.7/site-packages/ansible/inventory/manager.py", line 145, in
__init__     self.parse_sources(cache=True)   File "/usr/lib/python2.7/site-
packages/ansible/inventory/manager.py", line 215, in parse_sources     raise
AnsibleError("No inventory was parsed, please check your configuration and
options.") ansible.errors.AnsibleError: No inventory was parsed, please check
your configuration and options.

 [WARNING]: Unable to parse /tmp/awx_inventory_OvPnsK/tmp1NGkwV as an inventory
source

ERROR! No inventory was parsed, please check your configuration and options.

![image](https://user-images.githubusercontent.com/2832654/40119087-fa24e498-591b-11e8-8a80-d52f3758db2f.png)

**Comment by AlanCoding** [comment]
So Ansible core doesn't yet give us an option to modify the verbosity running `ansible-inventory` that won't potentially interfere with the loading of the JSON content they give, so we don't have any automatic way for you to toggle the verbosity of the `ansible-inventory` command. To do that, I added `-vvvv` to the arg list in code manually. This reveals the true error, which I was able to get reproducing your steps, which you probably haven't seen before:

```
    3.245 INFO     Updating inventory 42: issue 1185
    3.276 INFO     Reading Ansible inventory source: /tmp/awx_inventory_KKi4NN/tmpbv0uZM
Traceback (most recent call last):
  File "/usr/local/bin/awx-manage", line 9, in <module>
    load_entry_point('awx', 'console_scripts', 'awx-manage')()
  File "/awx_devel/awx/__init__.py", line 109, in manage
    execute_from_command_line(sys.argv)
  File "/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/awx_devel/awx/main/management/commands/inventory_import.py", line 990, in handle
    self.is_custom)
  File "/awx_devel/awx/main/management/commands/inventory_import.py", line 241, in load_inventory_source
    is_custom=is_custom).load()
  File "/awx_devel/awx/main/management/commands/inventory_import.py", line 176, in load
    data = self.command_to_json(base_args + ['--list', '-vvvvv'])
  File "/awx_devel/awx/main/management/commands/inventory_import.py", line 159, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
ansible-inventory 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
  File "/usr/lib/python2.7/site-packages/ansible/plugins/inventory/script.py", line 110, in parse
    raise AnsibleError("Inventory script (%s) had an execution error: %s " % (path, err))


stderr:
 [WARNING]:  * Failed to parse /tmp/awx_inventory_KKi4NN/tmpbv0uZM with script
plugin: Inventory script (/tmp/awx_inventory_KKi4NN/tmpbv0uZM) had an execution
error:  [WARNING]: Unable to parse /nfs_mount/foo as an inventory
source  Traceback (most recent call last):   File
"/tmp/awx_inventory_KKi4NN/tmpbv0uZM", line 40, in <module>     main()    File
"/tmp/awx_inventory_KKi4NN/tmpbv0uZM", line 23, in main     inventory =
InventoryManager(loader=loader, sources=sources)    File "/usr/lib/python2.7
/site-packages/ansible/inventory/manager.py", line 145, in __init__
self.parse_sources(cache=True)   File "/usr/lib/python2.7/site-
packages/ansible/inventory/manager.py", line 215, in parse_sources     raise
AnsibleError("No inventory was parsed, please check your configuration and
options.") ansible.errors.AnsibleError: No inventory was parsed, please check
your configuration and options.

 [WARNING]: Unable to parse /tmp/awx_inventory_KKi4NN/tmpbv0uZM as an inventory
source

ERROR! No inventory was parsed, please check your configuration and options.
```

This configuration setting is actually rather non-obvious, because I was actually setting the verbosity for the script that you gave me, and your script invokes the inventory manager, but that second level of context automatically gets the configuration from the first level of context, so the higher verbosity is passed through.

The output also tells me what the ultimate error was. Correct that `foo` is not executable, because you intended for it to be an ini file. It's not marked `+x` in addition to the fact that it's not python or bash or anything like that.

The standard behavior that you _wanted_ but did not get was for Ansible to try the inventory ini plugin on your file. If it had, it would have recognized the content and parsed it.

Why did it not do that? Because AWX set the Ansible configuration variable to _only_ use the _script_ plugin, because the feature is "custom inventory scripts". By the time _you_ ask _your_ inventory manager to parse the inventory, that plugin selection is still there.

As brutal as this is, you should be able to get it to work by running the same script, but as an SCM-based inventory source, and not as a custom inventory script. So put that script in a github repo, chmod +x it, add a project that pulls it, create an inventory source from that project and sync it. This would not restrict your nested call to the script plugin, because SCM-based sources themselves are not limited to the script plugin.

**Comment by AlanCoding** [comment]
Confirmed that I can fix it by adding

```python
from ansible import constants as C


C.INVENTORY_ENABLED = ['script', 'ini']
```

After the imports in your script (you can't directly set the env var, because of the way that Ansible loads its config vars).

But in general, there's no guarantee that Ansible, itself, will be written in a way that this approach can work, so I don't imagine any kind of true support for this approach.

**Comment by barkardk** [comment]
Hi 
Excellent, thank you so much
I enabled the ini plugin as you suggested in my script and it worked wonderfully .  

The reason I am not using SCM is because my company uses perforce helix and its not supported by ansible. So nfs mounting the ini files into the containers for the part of our inventory that is statically configured seemed  a viable workaround. 

```
#!/usr/bin/env python

import json
import sys
import os
import argparse

from ansible.parsing.dataloader import DataLoader
from ansible.inventory.manager import InventoryManager
from ansible import constants as C 
C.INVENTORY_ENABLED = ['script', 'ini' ]

def main():
  parser = argparse.ArgumentParser()
  parser.add_argument('--list', action = 'store_true')
  parser.add_argument('--host', action = 'store')
  parser.add_argument('--pretty', action = 'store_true')
  args = parser.parse_args()
  loader = DataLoader()
  inventory = InventoryManager(loader=loader, sources="/mnt/inventory/temp/dev2")
  inventory.parse_sources()
  out = {'_meta': {'hostvars': {}}}
  if args.list:
    for group in inventory.groups.values():
      out[group.name] = {
          'hosts': [h.name for h in group.hosts],
          'vars': group.vars,
          'children': [c.name for c in group.child_groups]
      }
    for host in inventory.get_hosts():
      out['_meta']['hostvars'][host.name] = host.vars

    print(json.dumps(out, indent=4, sort_keys=True))


if __name__ == "__main__":
  main()

```

```
2018-05-18 07:28:36,464 INFO     awx.main.commands.inventory_import Updating inventory 19: static_inventory |  
-- | --
  | 2 | 2018-05-18 07:28:36,491 DEBUG    awx.main.commands.inventory_import Using system install of ansible-inventory CLI: /usr/bin/ansible-inventory |  
  | 3 | 2018-05-18 07:28:36,491 INFO     awx.main.commands.inventory_import Reading Ansible inventory source: /tmp/awx_inventory_OWeOts/tmptLSVgR |  
  | 4 | 2018-05-18 07:28:37,819 ERROR    awx.main.commands.inventory_import  [ERROR]: |  
  | 5 | 2018-05-18 07:28:37,820 ERROR    awx.main.commands.inventory_import |  
  | 6 | 2018-05-18 07:28:37,820 INFO     awx.main.commands.inventory_import Processing JSON output... |  
  | 7 | 2018-05-18 07:28:37,820 DEBUG    awx.main.commands.inventory_import Loaded group: all |  
  | 8 | 2018-05-18 07:28:37,820 DEBUG    awx.main.commands.inventory_import Loaded group: foo |  
  | 9 | 2018-05-18 07:28:37,820 DEBUG    awx.main.commands.inventory_import Adding child group foo to parent all |  
  | 10 | 2018-05-18 07:28:37,820 DEBUG    awx.main.commands.inventory_import Loaded host: host1 |  
  | 11 | 2018-05-18 07:28:37,820 DEBUG    awx.main.commands.inventory_import Adding host host1 to group foo |  
  | 12 | 2018-05-18 07:28:37,820 DEBUG    awx.main.commands.inventory_import Loaded host: host2 |  
  | 13 | 2018-05-18 07:28:37,821 DEBUG    awx.main.commands.inventory_import Adding host host2 to group foo |  
  | 14 | 2018-05-18 07:28:37,821 DEBUG    awx.main.commands.inventory_import Adding child group foo to parent all |  
  | 15 | 2018-05-18 07:28:37,821 DEBUG    awx.main.commands.inventory_import Finished loading from source: /tmp/awx_inventory_OWeOts/tmptLSVgR |  
  | 16 | 2018-05-18 07:28:37,821 INFO     awx.main.commands.inventory_import Loaded 1 groups, 2 hosts |  
  | 17 | 2018-05-18 07:28:37,823 INFO     awx.main.commands.inventory_import Inventory variables unmodified |  
  | 18 | 2018-05-18 07:28:37,850 INFO     awx.main.commands.inventory_import Group "foo" added |  
  | 19 | 2018-05-18 07:28:37,863 INFO     awx.main.commands.inventory_import Host "host1" variables unmodified |  
  | 20 | 2018-05-18 07:28:37,866 INFO     awx.main.commands.inventory_import Host "host2" variables unmodified |  
  | 21 | 2018-05-18 07:28:37,882 INFO     awx.main.commands.inventory_import Host "host1" added to group "foo" |  
  | 22 | 2018-05-18 07:28:37,883 INFO     awx.main.commands.inventory_import Host "host2" added to group "foo" |  
  | 23 | 2018-05-18 07:28:37,888 DEBUG    awx.main.models.inventory Going to update inventory computed fields |  
  | 24 | 2018-05-18 07:28:37,992 DEBUG    awx.main.models.inventory Finished updating inventory computed fields |  
  | 25 | 2018-05-18 07:28:37,993 INFO     awx.main.commands.inventory_import Inventory import completed for static_inventory in 1.5s |  

```
