### ISSUE TITLE
CentOS 7.5 update

### ISSUE THREAD

**Issue by mrj1m0thy** [ansible/awx#1899]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Server update to CentOS 7.5 makes api fail?

##### ENVIRONMENT
* AWX version: 1.0.5.22
* AWX install method: docker on linux
* Ansible version:  2.5.0
* Operating System: CentOS 7.5
* Web Browser: Chrome Version 66.0.3359.117

##### STEPS TO REPRODUCE

1. Create a fresh install of AWX on a CentOS 7.5 machine
2. Delete the demo inventory

##### EXPECTED RESULTS

Demo Inventory is deleted

##### ACTUAL RESULTS

After a server update to CentOS 7.5 I began to recieve the error: "Call to /api/v2/inventories/1/ failed. DELETE returned status: 500 A server error has occurred." After attempting to delete the default demo inventory on a fresh install of AWX. 

##### ADDITIONAL INFORMATION
awx_web docker container has a centos version of 7.4.1708 and the version of the machine running docker is CentOS 7.5.1804

awx_web logs:

error: [Errno 104] Connection reset by peer                                                                                                                                                              [138/4664]
2018-05-22 16:04:20,292 ERROR    django.request Internal Server Error: /api/v2/inventories/1/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 65, in _legacy_get_response
    return super(AWXWSGIHandler, self)._legacy_get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 284, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 219, in delete
    return self.destroy(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/views.py", line 2075, in destroy
    obj.schedule_deletion(getattr(request.user, 'id', None))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/models/inventory.py", line 475, in schedule_deletion
    delete_inventory.delay(self.pk, user_id)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/task.py", line 461, in delay
    return self.apply_async(args, kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/task.py", line 573, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/base.py", line 354, in send_task
    reply_to=reply_to or self.oid, **options
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/amqp.py", line 310, in publish_task
    **kwargs
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/connection.py", line 470, in _ensured
    interval_max)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/connection.py", line 382, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/utils/__init__.py", line 246, in retry_over_time
    return fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/connection.py", line 250, in connect
    return self.connection
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/connection.py", line 756, in connection
    self._connection = self._establish_connection()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/connection.py", line 711, in _establish_connection
    conn = self.transport.establish_connection()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/connection.py", line 180, in __init__
    (10, 30),  # tune
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/abstract_channel.py", line 67, in wait
    self.channel_id, allowed_methods, timeout)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/connection.py", line 241, in _wait_method
    channel, method_sig, args, content = read_timeout(timeout)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/connection.py", line 330, in read_timeout
    return self.method_reader.read_method()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
    raise m

**Comment by scottlinux** [comment]
Is selinux preventing the connection?

**Comment by mrj1m0thy** [comment]
Turns out when I upgraded, the pgdata folder holding the database information had to be replaced. Exporting the data using pg_dump and them pg_restore to put it back after reinstalling worked fine. This same issue occurs when upgrading from AWX 1.0.5 to 1.0.6, however exporting and importing the database doesn't work in this case because the database has changed (so it seems).
