### ISSUE TITLE
OpenStack source inventory not working

### ISSUE THREAD

**Issue by sorinnmiroiu** [ansible/awx#1921]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
Error synchronizing inventory with OpenStack

##### ENVIRONMENT
* AWX version: 3.2.2
* AWX install method: -
* Ansible version:  2.4.3.0
* Operating System: RHEL 7.4
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

Trying to synchronize an Ansible Tower inventory using an OpenStack source, but without success.
I created an OpenStack credential, providing the necessary data into it (for the record, this OpenStack credential is used in a playbook which provisions VMs into a PowerVC).

##### EXPECTED RESULTS

Import instances to inventory

##### ACTUAL RESULTS

3.197 INFO     Updating inventory 16: PowerVC Inventory
    3.241 DEBUG    Using system install of ansible-inventory CLI: /usr/bin/ansible-inventory
    3.241 INFO     Reading Ansible inventory source: /var/lib/awx/venv/awx/lib/python2.7/site-packages/awx/plugins/inventory/openstack.py
    3.257 DEBUG    Using private credential data in '/tmp/awx_1717_AvYfdO'.
    3.260 DEBUG    Using fresh temporary directory '/tmp/awx_proot_pwU1BE' for isolation.
    3.260 DEBUG    Running from `/var/lib/awx/venv/awx/lib/python2.7/site-packages/awx/plugins/inventory` working directory.
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==3.2.2', 'console_scripts', 'awx-manage')()
  File "/lib/python2.7/site-packages/awx/__init__.py", line 107, in manage
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 661, in handle
    return self.handle_noargs(**options)
  File "/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 995, in handle_noargs
  File "/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 245, in load_inventory_source
  File "/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 180, in load
  File "/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 163, in command_to_json
RuntimeError: ansible-inventory failed (rc=4) with stdout:

stderr:
ERROR! Could not parse inventory source /var/lib/awx/venv/awx/lib/python2.7/site-packages/awx/plugins/inventory/openstack.py with available plugins:
Plugin script failed: Inventory script (/var/lib/awx/venv/awx/lib/python2.7/site-packages/awx/plugins/inventory/openstack.py) had an execution error: Error fetching server list on devstack::

 
Plugin ini failed: /var/lib/awx/venv/awx/lib/python2.7/site-packages/awx/plugins/inventory/openstack.py:48: Expected key=value host variable assignment, got: argparse

**Comment by wenottingham** [comment]
If you are having issues with Ansible Tower, please contact your Red Hat support rep.
