### ISSUE TITLE
"Internal Server Error"  on custom AWX docker image build for Kuberentes use 

### ISSUE THREAD

**Issue by idgdmg** [ansible/awx#1946]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY
Building the custom image of AWX using ansible-playbook produces the following "Internal Server error"

2018-06-02 17:05:10,905 INFO spawned: 'daphne' with pid 103
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/daphne", line 11, in &lt;module&gt;
    sys.exit(CommandLineInterface.entrypoint())
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/daphne/cli.py", line 144, in entrypoint
    cls().run(sys.argv[1:])
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/daphne/cli.py", line 174, in run
    channel_layer = importlib.import_module(module_path)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/awx/asgi.py", line 37, in &lt;module&gt;
    channel_layer = get_channel_layer()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/channels/asgi.py", line 115, in get_channel_layer
    django.setup(set_prefix=False)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib64/python2.7/logging/config.py", line 803, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib64/python2.7/logging/config.py", line 636, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure logger 'awx': Unable to add handler 'external_logger': 'external_logger'
2018-06-02 17:05:11,845 INFO exited: daphne (exit status 1; not expected)
2018-06-02 17:05:14,849 INFO spawned: 'daphne' with pid 112

##### ENVIRONMENT
* AWX version:  awx-1.0.6.12.tar.gz
* AWX install method: ansible-playbook

Command used: ansible-playbook -v ~/awx/installer/install.yml -b -i ~/awx/installer/inventory -e docker_registry_password=XXXX 

* Ansible version:  ansible 2.5.4, Python 2.7.0
* Operating System: Kuberentes Container
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1) git pull the awx-
cd ~ && git clone https://github.com/ansible/awx.git && cd ~/awx/installer
2) Comment out 
#dockerhub_base=ansible
#dockerhub_version=latest

3) Create custom repo and run the ansible-playbook 
ansible-playbook -v ~/awx/installer/install.yml -b -i ~/awx/installer/inventory -e docker_registry_password=XXXX 

4) Coincidentally -  the custom image (so UNCOMMENTED lines "dockerhub_base" and "dockerhub_version") works great out of the box.  That happens ONLY if attempted to build a custom image

##### EXPECTED RESULTS

AWX logo prompt 

##### ACTUAL RESULTS

Internal Server Error

##### ADDITIONAL INFORMATION
Errors from awx-web  Kubernetes log 

  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/awx/asgi.py", line 37, in &lt;module&gt;
    channel_layer = get_channel_layer()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/channels/asgi.py", line 115, in get_channel_layer
    django.setup(set_prefix=False)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib64/python2.7/logging/config.py", line 803, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib64/python2.7/logging/config.py", line 636, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure logger 'awx': Unable to add handler 'external_logger': 'external_logger'
2018-06-02 17:05:11,845 INFO exited: daphne (exit status 1; not expected)
2018-06-02 17:05:14,849 INFO spawned: 'daphne' with pid 112
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/daphne", line 11, in &lt;module&gt;
    sys.exit(CommandLineInterface.entrypoint())
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/daphne/cli.py", line 144, in entrypoint
    cls().run(sys.argv[1:])
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/daphne/cli.py", line 174, in run
    channel_layer = importlib.import_module(module_path)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/awx/asgi.py", line 37, in &lt;module&gt;
    channel_layer = get_channel_layer()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/channels/asgi.py", line 115, in get_channel_layer
    django.setup(set_prefix=False)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib64/python2.7/logging/config.py", line 803, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib64/python2.7/logging/config.py", line 636, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure logger 'awx': Unable to add handler 'external_logger': 'external_logger'
2018-06-02 17:05:15,801 INFO exited: daphne (exit status 1; not expected)
2018-06-02 17:05:16,802 INFO gave up: daphne entered FATAL state, too many start retries too quickly
No previous hash foundRESULT 2

**Comment by idgdmg** [comment]
More details
1) jump into the awx_web container

sudo docker exec -ti  `sudo docker ps | grep web | awk '{print $NF}'` /bin/bash

2) error is here:
awx-manage --help
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==1.0.6.5', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib64/python2.7/logging/config.py", line 803, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib64/python2.7/logging/config.py", line 636, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure logger 'awx': Unable to add handler 'external_logger': 'external_logger'

**Comment by AlanCoding** [comment]
It's pretty clear that somehow you have a mismatch between these two settings files, the defaults in the image:

https://github.com/ansible/awx/blob/72f2994cc5f00848dd3e68074c32cef88707f48b/awx/settings/defaults.py

And your custom settings:

https://github.com/ansible/awx/blob/72f2994cc5f00848dd3e68074c32cef88707f48b/installer/roles/image_build/files/settings.py

A change was made to both of these files, and if one file has the change while the other does not, then I expect it to cause the type of error you reported here. Specifically, I would expect this when the local settings (`settings.py`) was up-to-date and the `defaults.py` file was out-of-date.

From what you say, this would seem to point to the image being out of date. I have not yet dug in to debug this, but this is where I would start.

**Comment by idgdmg** [comment]
@AlanCoding  - can you elaborate on the mistmatch? Both files have been checkout from the github.repo and I do not see any obvious smoking gun..

**Comment by idgdmg** [comment]
The recent file on github clearly has the DEVELOPMENT modules!!! I have compared with the previous pull, made a couple of weeks ago


` diff /tmp/aaa awx/installer/roles/image_build/files/settings.py
10a11
> ANSIBLE_ROLES_PATH = '/etc/ansible/roles:/usr/share/ansible/roles:/var/lib/awx/projects/'
40,41c41,42
< SERVER_EMAIL = 'root@localhost'
< DEFAULT_FROM_EMAIL = 'webmaster@localhost'
---
> SERVER_EMAIL = 'awx@idgesg.net'
> DEFAULT_FROM_EMAIL = 'awx@idgesg.net'
44c45
< EMAIL_HOST = 'localhost'
---
> EMAIL_HOST = 'mta1.pcworld.com'
58c59
< LOGGING['loggers']['awx']['handlers'] = ['console', 'external_logger']
---
> LOGGING['loggers']['awx']['handlers'] = ['console']
60,61c61,63
< LOGGING['loggers']['awx.main.tasks']['handlers'] = ['console', 'external_logger']
< LOGGING['loggers']['awx.main.scheduler']['handlers'] = ['console', 'external_logger']
---
> LOGGING['loggers']['awx.main.commands.inventory_import']['handlers'] = ['console']
> LOGGING['loggers']['awx.main.tasks']['handlers'] = ['console']
> LOGGING['loggers']['awx.main.scheduler']['handlers'] = ['console']`

**Comment by jakemcdermott** [comment]
Hello @idgdmg 

When using AWX, you are highly encouraged to not modify the container image files or installer scripts (beyond specifying variables, of course) when using AWX. 

If you see similar problems using an unmodified container image, please create an issue for that. Thank you!
