### ISSUE TITLE
Multiple failures during AWX initialization with local Docker

### ISSUE THREAD

**Issue by piroux** [ansible/awx#1972]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
While deploying AWX with Ansible on a local docker and building the images locally,
the playbook `install.yml` finishes successfully but the subsequent migrations of AWX in awx_task do no complete and multiple issues ensue because there is currently no way to check to that everything went through during the initialization.

##### ENVIRONMENT
* AWX version:
```
$ git describe --long --first-parent                                   
1.0.6-0-g327d3c3f5
```
* AWX install method: docker on linux (building the awx images locally)
* Ansible version:  devel
* Operating System: Ubuntu 14.04
* Web Browser: Google chrome last version

##### STEPS TO REPRODUCE
```console
$ # Changes made to installer/inventory :
$ # - comment dockerhub statements
$ # - change port from 80 to 8087
$ # - change user/password
$ ansible-playbook -vv -i installer/inventory installer/install.yml
```

##### EXPECTED RESULTS
The initialization should complete its full migrations and instance creation the first time or **fail fast** if the _"happy path"_ is not followed !!
##### ACTUAL RESULTS
```console
$ docker logs -f awx_task
2018-06-08T09:44:25.203865658Z Using /etc/ansible/ansible.cfg as config file
2018-06-08T09:44:25.924522979Z 127.0.0.1 | SUCCESS => {
2018-06-08T09:44:25.924550559Z     "changed": false, 
2018-06-08T09:44:25.924554135Z     "elapsed": 0, 
2018-06-08T09:44:25.924557026Z     "path": null, 
2018-06-08T09:44:25.924559897Z     "port": 5432, 
2018-06-08T09:44:25.924562551Z     "search_regex": null, 
2018-06-08T09:44:25.924565301Z     "state": "started"
2018-06-08T09:44:25.924568201Z }
2018-06-08T09:44:26.233707860Z Using /etc/ansible/ansible.cfg as config file
2018-06-08T09:44:26.922357723Z 127.0.0.1 | SUCCESS => {
2018-06-08T09:44:26.922393193Z     "changed": false, 
2018-06-08T09:44:26.922397506Z     "elapsed": 0, 
2018-06-08T09:44:26.922400662Z     "path": null, 
2018-06-08T09:44:26.922403883Z     "port": 11211, 
2018-06-08T09:44:26.922406969Z     "search_regex": null, 
2018-06-08T09:44:26.922410214Z     "state": "started"
2018-06-08T09:44:26.922413438Z }
2018-06-08T09:44:27.339105885Z Using /etc/ansible/ansible.cfg as config file
2018-06-08T09:44:28.131366751Z 127.0.0.1 | SUCCESS => {
2018-06-08T09:44:28.131407560Z     "changed": false, 
2018-06-08T09:44:28.131416179Z     "elapsed": 0, 
2018-06-08T09:44:28.131421344Z     "path": null, 
2018-06-08T09:44:28.131426416Z     "port": 5672, 
2018-06-08T09:44:28.131431649Z     "search_regex": null, 
2018-06-08T09:44:28.131436075Z     "state": "started"
2018-06-08T09:44:28.131440581Z }
2018-06-08T09:44:28.516278745Z Using /etc/ansible/ansible.cfg as config file
2018-06-08T09:44:29.410034950Z 127.0.0.1 | SUCCESS => {
2018-06-08T09:44:29.410088710Z     "changed": true, 
2018-06-08T09:44:29.410094849Z     "db": "awx"
2018-06-08T09:44:29.410098297Z }
2018-06-08T09:44:32.007342016Z Operations to perform:
2018-06-08T09:44:32.007383063Z   Apply all migrations: auth, conf, contenttypes, djcelery, main, network_ui, oauth2_provider, sessions, sites, social_django, sso, taggit
2018-06-08T09:44:32.007390575Z Running migrations:
2018-06-08T09:44:32.024935105Z   Applying contenttypes.0001_initial... OK
2018-06-08T09:44:32.042836650Z   Applying contenttypes.0002_remove_content_type_name... OK
2018-06-08T09:44:32.127353303Z   Applying auth.0001_initial... OK
2018-06-08T09:44:32.145135123Z   Applying auth.0002_alter_permission_name_max_length... OK
[...]
2018-06-08T09:46:57.446589275Z   Applying social_django.0007_code_timestamp... OK
2018-06-08T09:46:57.489062867Z   Applying social_django.0008_partial_timestamp... OK
2018-06-08T09:46:58.327336660Z   Applying sso.0001_initial... OK
2018-06-08T09:47:00.812236111Z   Applying sso.0002_expand_provider_options... OK
2018-06-08T09:47:07.528082784Z Traceback (most recent call last):
2018-06-08T09:47:07.528235426Z   File "/usr/bin/awx-manage", line 9, in <module>
2018-06-08T09:47:07.531646889Z     load_entry_point('awx==1.0.6.15', 'console_scripts', 'awx-manage')()
2018-06-08T09:47:07.531681489Z   File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
2018-06-08T09:47:07.531820552Z     execute_from_command_line(sys.argv)
2018-06-08T09:47:07.531849077Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
2018-06-08T09:47:07.532838889Z     utility.execute()
2018-06-08T09:47:07.532860930Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
2018-06-08T09:47:07.532868631Z     self.fetch_command(subcommand).run_from_argv(self.argv)
2018-06-08T09:47:07.532875206Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
2018-06-08T09:47:07.532881899Z     self.execute(*args, **cmd_options)
2018-06-08T09:47:07.532888291Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
2018-06-08T09:47:07.532895159Z     output = self.handle(*args, **options)
2018-06-08T09:47:07.532901461Z   File "/usr/lib/python2.7/site-packages/awx/main/management/commands/create_preload_data.py", line 47, in handle
2018-06-08T09:47:07.532927140Z     created_by=superuser)
2018-06-08T09:47:07.532933858Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
2018-06-08T09:47:07.532940729Z     return getattr(self.get_queryset(), name)(*args, **kwargs)
2018-06-08T09:47:07.532947074Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 394, in create
2018-06-08T09:47:07.532953727Z     obj.save(force_insert=True, using=self.db)
2018-06-08T09:47:07.532960099Z   File "/usr/lib/python2.7/site-packages/awx/main/models/inventory.py", line 700, in save
2018-06-08T09:47:07.532966787Z     super(Host, self).save(*args, **kwargs)
2018-06-08T09:47:07.532973006Z   File "/usr/lib/python2.7/site-packages/awx/main/models/base.py", line 275, in save
2018-06-08T09:47:07.532979506Z     super(PrimordialModel, self).save(*args, **kwargs)
2018-06-08T09:47:07.532985715Z   File "/usr/lib/python2.7/site-packages/awx/main/models/base.py", line 164, in save
2018-06-08T09:47:07.533016667Z     super(CreatedModifiedModel, self).save(*args, **kwargs)
2018-06-08T09:47:07.533023094Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
2018-06-08T09:47:07.533029752Z     force_update=force_update, update_fields=update_fields)
2018-06-08T09:47:07.533036137Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/base.py", line 848, in save_base
2018-06-08T09:47:07.533042899Z     update_fields=update_fields, raw=raw, using=using,
2018-06-08T09:47:07.533049199Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
2018-06-08T09:47:07.533055855Z     for receiver in self._live_receivers(sender)
2018-06-08T09:47:07.533062097Z   File "/usr/lib/python2.7/site-packages/awx/main/signals.py", line 146, in emit_update_inventory_on_created_or_deleted
2018-06-08T09:47:07.533101465Z     update_inventory_computed_fields.delay(inventory.id, True)
2018-06-08T09:47:07.533109814Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/task.py", line 461, in delay
2018-06-08T09:47:07.533116632Z     return self.apply_async(args, kwargs)
2018-06-08T09:47:07.533122797Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/task.py", line 573, in apply_async
2018-06-08T09:47:07.533129389Z     **dict(self._get_exec_options(), **options)
2018-06-08T09:47:07.533135549Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/base.py", line 345, in send_task
2018-06-08T09:47:07.533142214Z     options = router.route(options, name, args, kwargs)
2018-06-08T09:47:07.533165187Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/routes.py", line 50, in route
2018-06-08T09:47:07.533173296Z     route = self.lookup_route(task, args, kwargs)
2018-06-08T09:47:07.533179610Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/routes.py", line 78, in lookup_route
2018-06-08T09:47:07.533186326Z     return _first_route(self.routes, task, args, kwargs)
2018-06-08T09:47:07.533192567Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/utils/functional.py", line 233, in _matcher
2018-06-08T09:47:07.533199323Z     answer = getattr(maybe_evaluate(obj), method)(*args, **kwargs)
2018-06-08T09:47:07.533205798Z   File "/usr/lib/python2.7/site-packages/awx/main/utils/ha.py", line 58, in route_for_task
2018-06-08T09:47:07.533212571Z     (changed, instance) = Instance.objects.get_or_register()
2018-06-08T09:47:07.533218890Z   File "/usr/lib/python2.7/site-packages/awx/main/managers.py", line 106, in get_or_register
2018-06-08T09:47:07.533225500Z     return (False, self.me())
2018-06-08T09:47:07.533246715Z   File "/usr/lib/python2.7/site-packages/awx/main/managers.py", line 88, in me
2018-06-08T09:47:07.533254282Z     raise RuntimeError("No instance found with the current cluster host id")
2018-06-08T09:47:07.533261053Z RuntimeError: No instance found with the current cluster host id
2018-06-08T09:55:56.011873319Z Traceback (most recent call last):
2018-06-08T09:55:56.011942768Z   File "/usr/bin/awx-manage", line 9, in <module>
2018-06-08T09:55:56.012043641Z     load_entry_point('awx==1.0.6.15', 'console_scripts', 'awx-manage')()
2018-06-08T09:55:56.012053201Z   File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
2018-06-08T09:55:56.012056860Z     execute_from_command_line(sys.argv)
2018-06-08T09:55:56.012060093Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
2018-06-08T09:55:56.012064075Z     utility.execute()
2018-06-08T09:55:56.012067205Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
2018-06-08T09:55:56.012070604Z     self.fetch_command(subcommand).run_from_argv(self.argv)
2018-06-08T09:55:56.012094764Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
2018-06-08T09:55:56.012098928Z     self.execute(*args, **cmd_options)
2018-06-08T09:55:56.012101661Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
2018-06-08T09:55:56.012104689Z     output = self.handle(*args, **options)
2018-06-08T09:55:56.012107380Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
2018-06-08T09:55:56.012110360Z     return func(*args, **kwargs)
2018-06-08T09:55:56.012113064Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/transaction.py", line 267, in __exit__
2018-06-08T09:55:56.012116028Z     connection.set_autocommit(True)
2018-06-08T09:55:56.012118649Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 416, in set_autocommit
2018-06-08T09:55:56.012121560Z     self.run_and_clear_commit_hooks()
2018-06-08T09:55:56.012124162Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 651, in run_and_clear_commit_hooks
2018-06-08T09:55:56.012127408Z     func()
2018-06-08T09:55:56.012130072Z   File "/usr/lib/python2.7/site-packages/awx/main/models/ha.py", line 203, in <lambda>
2018-06-08T09:55:56.012133118Z     connection.on_commit(lambda: apply_cluster_membership_policies.apply_async())
2018-06-08T09:55:56.012135972Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/task.py", line 573, in apply_async
2018-06-08T09:55:56.012138771Z     **dict(self._get_exec_options(), **options)
2018-06-08T09:55:56.012141442Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/base.py", line 354, in send_task
2018-06-08T09:55:56.012148106Z     reply_to=reply_to or self.oid, **options
2018-06-08T09:55:56.012180832Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/amqp.py", line 310, in publish_task
2018-06-08T09:55:56.012185276Z     **kwargs
2018-06-08T09:55:56.012187984Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
2018-06-08T09:55:56.012190838Z     routing_key, mandatory, immediate, exchange, declare)
2018-06-08T09:55:56.012193618Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/connection.py", line 470, in _ensured
2018-06-08T09:55:56.012196500Z     interval_max)
2018-06-08T09:55:56.012199141Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/connection.py", line 382, in ensure_connection
2018-06-08T09:55:56.012201985Z     interval_start, interval_step, interval_max, callback)
2018-06-08T09:55:56.012204674Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/utils/__init__.py", line 246, in retry_over_time
2018-06-08T09:55:56.012207561Z     return fun(*args, **kwargs)
2018-06-08T09:55:56.012214728Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/connection.py", line 250, in connect
2018-06-08T09:55:56.012217666Z     return self.connection
2018-06-08T09:55:56.012220329Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/connection.py", line 756, in connection
2018-06-08T09:55:56.012223211Z     self._connection = self._establish_connection()
2018-06-08T09:55:56.012225834Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/connection.py", line 711, in _establish_connection
2018-06-08T09:55:56.012242588Z     conn = self.transport.establish_connection()
2018-06-08T09:55:56.012245343Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
2018-06-08T09:55:56.012248270Z     conn = self.Connection(**opts)
2018-06-08T09:55:56.012251177Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/connection.py", line 171, in __init__
2018-06-08T09:55:56.012254081Z     (10, 10),  # start
2018-06-08T09:55:56.012256719Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/abstract_channel.py", line 67, in wait
2018-06-08T09:55:56.012259573Z     self.channel_id, allowed_methods, timeout)
2018-06-08T09:55:56.012262271Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/connection.py", line 241, in _wait_method
2018-06-08T09:55:56.012265144Z     channel, method_sig, args, content = read_timeout(timeout)
2018-06-08T09:55:56.012267871Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/connection.py", line 330, in read_timeout
2018-06-08T09:55:56.012270742Z     return self.method_reader.read_method()
2018-06-08T09:55:56.012273435Z   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
2018-06-08T09:55:56.012276280Z     raise m
2018-06-08T09:55:56.012278888Z socket.error: [Errno 104] Connection reset by peer
2018-06-08T09:55:56.011802960Z Successfully registered instance awx
2018-06-08T09:55:56.012305738Z (changed: True)
2018-06-08T10:04:42.857335051Z Traceback (most recent call last):
2018-06-08T10:04:42.857722102Z   File "/usr/bin/awx-manage", line 9, in <module>
2018-06-08T10:04:42.857739150Z     load_entry_point('awx==1.0.6.15', 'console_scripts', 'awx-manage')()
2018-06-08T10:04:42.857746411Z   File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
2018-06-08T10:04:42.857864449Z     execute_from_command_line(sys.argv)
```

In the meantime, in awx_web :

```console
$ docker logs -f awx_web
[...]
2018-06-08T09:44:26.214442484Z 349 static files copied to '/var/lib/awx/public/static'.
2018-06-08T09:44:26.418850882Z 2018-06-08 09:44:26,418 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2018-06-08T09:44:26.427170169Z 2018-06-08 09:44:26,426 INFO RPC interface 'supervisor' initialized
2018-06-08T09:44:26.427233467Z 2018-06-08 09:44:26,427 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2018-06-08T09:44:26.427413734Z 2018-06-08 09:44:26,427 INFO supervisord started with pid 20
2018-06-08T09:44:27.430607119Z 2018-06-08 09:44:27,430 INFO spawned: 'awx-config-watcher' with pid 23
2018-06-08T09:44:27.433212154Z 2018-06-08 09:44:27,432 INFO spawned: 'daphne' with pid 24
2018-06-08T09:44:27.435474350Z 2018-06-08 09:44:27,435 INFO spawned: 'nginx' with pid 25
2018-06-08T09:44:27.438193789Z 2018-06-08 09:44:27,437 INFO spawned: 'uwsgi' with pid 26
2018-06-08T09:44:27.461242963Z *** Starting uWSGI 2.0.17 (64bit) on [Fri Jun  8 09:44:27 2018] ***
2018-06-08T09:44:27.461297152Z compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-28) on 08 June 2018 09:41:46
2018-06-08T09:44:27.461302658Z os: Linux-3.13.0-144-generic #193-Ubuntu SMP Thu Mar 15 17:03:53 UTC 2018
2018-06-08T09:44:27.461307093Z nodename: awxweb
2018-06-08T09:44:27.461311182Z machine: x86_64
2018-06-08T09:44:27.461314841Z clock source: unix
2018-06-08T09:44:27.461318523Z pcre jit disabled
2018-06-08T09:44:27.461322215Z detected number of CPU cores: 4
2018-06-08T09:44:27.461326048Z current working directory: /var/lib/awx
2018-06-08T09:44:27.461329976Z detected binary path: /var/lib/awx/venv/awx/bin/uwsgi
2018-06-08T09:44:27.461333939Z uWSGI running as root, you can use --uid/--gid/--chroot options
2018-06-08T09:44:27.461338240Z *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
2018-06-08T09:44:27.461342225Z your memory page size is 4096 bytes
2018-06-08T09:44:27.461346154Z  *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
2018-06-08T09:44:27.461350248Z detected max file descriptor number: 524288
2018-06-08T09:44:27.461354165Z lock engine: pthread robust mutexes
2018-06-08T09:44:27.461786387Z thunder lock: disabled (you can enable it with --thunder-lock)
2018-06-08T09:44:27.462490516Z uwsgi socket 0 bound to TCP address 127.0.0.1:8050 fd 3
2018-06-08T09:44:27.462769371Z uWSGI running as root, you can use --uid/--gid/--chroot options
2018-06-08T09:44:27.462813894Z *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
2018-06-08T09:44:27.462826287Z Python version: 2.7.5 (default, Apr 11 2018, 07:36:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
2018-06-08T09:44:27.499866848Z *** Python threads support is disabled. You can enable it with --enable-threads ***
2018-06-08T09:44:27.499901670Z Python main interpreter initialized at 0xbebc40
2018-06-08T09:44:27.499907761Z uWSGI running as root, you can use --uid/--gid/--chroot options
2018-06-08T09:44:27.499913134Z *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
2018-06-08T09:44:27.499918335Z your server socket listen backlog is limited to 100 connections
2018-06-08T09:44:27.499923355Z your mercy for graceful operations on workers is 60 seconds
2018-06-08T09:44:27.500562698Z mapped 609552 bytes (595 KB) for 5 cores
2018-06-08T09:44:27.500855925Z *** Operational MODE: preforking ***
2018-06-08T09:44:27.501484724Z uWSGI running as root, you can use --uid/--gid/--chroot options
2018-06-08T09:44:27.501500465Z *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
2018-06-08T09:44:27.501506095Z *** uWSGI is running in multiple interpreter mode ***
2018-06-08T09:44:27.501511105Z spawned uWSGI master process (pid: 26)
2018-06-08T09:44:27.502013585Z spawned uWSGI worker 1 (pid: 28, cores: 1)
2018-06-08T09:44:27.502399907Z spawned uWSGI worker 2 (pid: 29, cores: 1)
2018-06-08T09:44:27.502795787Z spawned uWSGI worker 3 (pid: 30, cores: 1)
2018-06-08T09:44:27.503194631Z spawned uWSGI worker 4 (pid: 31, cores: 1)
2018-06-08T09:44:27.503644022Z spawned uWSGI worker 5 (pid: 32, cores: 1)
2018-06-08T09:44:27.521968981Z READY
2018-06-08T09:44:28.523461347Z 2018-06-08 09:44:28,523 INFO success: awx-config-watcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-06-08T09:44:28.523647818Z 2018-06-08 09:44:28,523 INFO success: daphne entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-06-08T09:44:28.523791444Z 2018-06-08 09:44:28,523 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-06-08T09:44:28.523900155Z 2018-06-08 09:44:28,523 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-06-08T09:44:31.967761562Z 2018-06-08 09:44:31,967 INFO     Starting server at tcp:port=8051:interface=127.0.0.1, channel layer awx.asgi:channel_layer.
2018-06-08T09:44:31.969370094Z 2018-06-08 09:44:31,969 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2018-06-08T09:44:31.969590117Z 2018-06-08 09:44:31,969 INFO     Using busy-loop synchronous mode on channel layer
2018-06-08T09:44:31.969599854Z 2018-06-08 09:44:31,969 INFO     Listening on endpoint tcp:port=8051:interface=127.0.0.1
2018-06-08T09:44:32.353832837Z WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0xbebc40 pid: 30 (default app)
2018-06-08T09:44:32.403023902Z WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0xbebc40 pid: 32 (default app)
2018-06-08T09:44:32.414744702Z WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0xbebc40 pid: 31 (default app)
2018-06-08T09:44:32.422826771Z WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0xbebc40 pid: 28 (default app)
2018-06-08T09:44:32.500910000Z WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0xbebc40 pid: 29 (default app)
2018-06-08T09:45:01.536382344Z RESULT 2
2018-06-08T09:45:01.536468339Z OKREADY
2018-06-08T09:46:01.607343625Z No previous hash foundRESULT 2
2018-06-08T09:46:01.607384524Z OKREADY
2018-06-08T09:46:16.681534748Z 2018-06-08 09:46:16,680 ERROR    Error trying to receive messages: [Errno 104] Connection reset by peer
2018-06-08T09:47:01.741221864Z RESULT 2
2018-06-08T09:47:01.741269589Z OKREADY
2018-06-08T09:48:01.819155626Z RESULT 2
2018-06-08T09:48:01.819208627Z OKREADY
2018-06-08T09:48:06.377148331Z 2018-06-08 09:48:06,376 ERROR    Error trying to receive messages: [Errno 104] Connection reset by peer
2018-06-08T09:49:01.449196294Z RESULT 2
2018-06-08T09:49:01.449234222Z OKREADY
2018-06-08T09:49:56.073004169Z 2018-06-08 09:49:56,071 ERROR    Error trying to receive messages: [Errno 104] Connection reset by peer
2018-06-08T09:50:01.080764304Z RESULT 2
2018-06-08T09:50:01.080828085Z OKREADY
2018-06-08T09:51:01.158009451Z RESULT 2
2018-06-08T09:51:01.158090316Z OKREADY
[...]
```

You can take a look at the complete logs here: https://gist.github.com/piroux/b9cf0af86c55f994eb441167d6ff9608

The initialization in awx_task becomes locked here and it seems that the instance is not initially successfully created.
The awx-manage fails and only 10min later, it eventually creates the instance: [`2018-06-08T09:55:56.011802960Z Successfully registered instance awx`](https://gist.github.com/piroux/b9cf0af86c55f994eb441167d6ff9608#file-awx_task_20180608-100921z-log-L238)

But it continues to fail afterward as you can acknowledge in both logs.

I think the web interface becomes available as soon as the first failure of `awx-manage`, however the tower instance does not seem to be properly created because others errors `awx-manager` afterward.
Please note that I only started to access the web interface at `2018-06-08T10:03`.

One can log in, but even trying to update the Default project fails because it stays in a pending state and one cannot even open its job page because the websockets fails too (I do not know if it is related):
![screenshot from 2018-06-08 12-08-21](https://user-images.githubusercontent.com/438492/41155746-76927224-6b1f-11e8-92dc-2b00616edee9.png)

Moreover, in the Instance tab of the web interface, the tower instance stays `UNAVAILABLE`:
![screenshot from 2018-06-08 12-06-07](https://user-images.githubusercontent.com/438492/41155754-7d184a4c-6b1f-11e8-919a-3f1d881d1098.png)

To sum up, you can see that there are issues:
- with creating the tower instance because the `awx-manage` command fails and even afterward once it is said to be created in the logs, it is `UNAVAILABLE` according to the Instance tab in the web interface,
- with websockets (code 499) in `awx_web` preventing to understand as a simple user why the Default project update is failing,
- with amqp/kombu/celery from `awx_task`, probably triggering both previous errors.

Please note that I have not seen any issue with the `rabbitmq` container while looking at its logs (only info statements)

##### ADDITIONAL INFORMATION

I think a task is really missing at the end of the installer. Indeed, such a this task should let the installer:
- fail fast if a single error is detected during the initialization,
- wait for the entire initialization to complete (migrations + instance creation).

**Comment by aoyawale** [comment]
did you upgrade between versions or was it a clean install?

**Comment by piroux** [comment]
Completely fresh install because before running the install.yml playbook, I execute these commands :
``` console
$ rm -rf ../other_dir/pgdocker && mkdir ../other_dir/pgdocker
$ docker system prune -a -f
```
So it forces to rebuild the AWX docker images and to redo the complete initialization (migrations + instance creation).

**Comment by aoyawale** [comment]
try removing all the containers by using `docker ps` and grabbing container id and do `docker rmi container id` since its a new install and you don't have nothing to loose.  Remove the AWX containers then try again.

**Comment by piroux** [comment]
This is already covered by the [`prune` command](https://docs.docker.com/engine/reference/commandline/system_prune/#extended-description) which I mentioned above:
```
Remove all unused containers, networks, images (both dangling and unreferenced), and optionally, volumes.
```
Obviously I stop the 5 awx containers before issuing the prune command.

**Comment by jakemcdermott** [comment]
@piroux 

Are you still seeing this? I am not able to reproduce this when using the following steps prior to running local docker install:

```
docker rm -f $(docker ps -a -q)
docker rmi -f $(docker images -a -q)
rm -rf /tmp/pgdocker/
```

Please re-open if you are still seeing this.
