### ISSUE TITLE
AWX SAML settings.py configuration can cause AssertionErrors

### ISSUE THREAD

**Issue by willthames** [ansible/awx#1982]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea
 - Documentation

##### COMPONENT NAME
 - API

##### SUMMARY

When using settings.py to configure SAML authentication, the `required=True` setting on certain fields causes problems

##### ENVIRONMENT
* AWX version: 1.0.6
* AWX install method: minikube
* Ansible version:  2.5.3
* Operating System: OS X
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Using standard 1.0.6 awx_web, set all the required SAML values:

```
SOCIAL_AUTH_SAML_SP_ENTITY_ID = 'https://awx.local'
SOCIAL_AUTH_SAML_SP_PUBLIC_CERT = '{{ awx_sso_public_cert|trim }}'
SOCIAL_AUTH_SAML_SP_PRIVATE_KEY = '{{ awx_sso_private_key|trim }}'
SOCIAL_AUTH_SAML_ORG_INFO = {
  "en-US": {
    "url": "https://awx.local/",
    "displayname": "AWX Dev",
    "name": "awx-dev"
  }
}
SOCIAL_AUTH_SAML_TECHNICAL_CONTACT = {
  "givenName": "xyz",
  "emailAddress": "xyz@example.com"
}
SOCIAL_AUTH_SAML_SUPPORT_CONTACT = {
  "givenName": "xyz",
  "emailAddress": "xyz@example.com"
}
SOCIAL_AUTH_SAML_ENABLED_IDPS = {
  "auth0": {
    "entity_id": "{{ auth0_entity_id }}",
    "url": "{{ auth0_url }}",
    "x509cert": "...",
    "attr_user_permanent_id": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
    "attr_email": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
    "attr_username": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn",
    "attr_first_name": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname",
    "attr_last_name": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname",
  }
}
```

##### EXPECTED RESULTS

Working SSO with login. Note that the above settings work fine as configured through the web interface.

##### ACTUAL RESULTS

```
2018-06-12 04:17:45,000 ERROR    django.request Internal Server Error: /
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 59, in _legacy_get_response
    if getattr(resolve(request.path), 'url_name', '') == 'migrations_notran':
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/urls/base.py", line 27, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/awx/urls.py", line 17, in <module>
    url(r'^sso/', include('social_django.urls', namespace='social')),
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/urls.py", line 6, in <module>
    from . import views
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/views.py", line 10, in <module>
    from .utils import psa
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/utils.py", line 13, in <module>
    BACKENDS = settings.AUTHENTICATION_BACKENDS
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 489, in __getattr_without_cache__
    return getattr(self._wrapped, name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 402, in __getattr__
    value = self._get_local(name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 356, in _get_local
    value = field.get_default()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/fields.py", line 479, in get_default
    return self.default()
  File "/usr/lib/python2.7/site-packages/awx/sso/fields.py", line 161, in _default_from_required_settings
    if all([getattr(settings, rs, None) for rs in required_settings]):
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 489, in __getattr_without_cache__
    return getattr(self._wrapped, name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 402, in __getattr__
    value = self._get_local(name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 335, in _get_local
    field = self.registry.get_setting_field(name)
  File "/usr/lib/python2.7/site-packages/awx/conf/registry.py", line 143, in get_setting_field
    field_instance = field_class(**field_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/fields.py", line 1654, in __init__
    super(DictField, self).__init__(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/fields.py", line 320, in __init__
    assert not (read_only and required), NOT_READ_ONLY_REQUIRED
```
##### ADDITIONAL INFORMATION

With the following patch, the application works:

```
diff --git a/awx/sso/conf.py b/awx/sso/conf.py
index 75178d6d1..58b9b7ab1 100644
--- a/awx/sso/conf.py
+++ b/awx/sso/conf.py
@@ -1005,7 +1005,6 @@ register(
 register(
     'SOCIAL_AUTH_SAML_ORG_INFO',
     field_class=fields.SAMLOrgInfoField,
-    required=True,
     label=_('SAML Service Provider Organization Info'),
     help_text=_('Provide the URL, display name, and the name of your app. Refer to'
                 ' the Ansible Tower documentation for example syntax.'),
@@ -1025,7 +1024,6 @@ register(
     'SOCIAL_AUTH_SAML_TECHNICAL_CONTACT',
     field_class=fields.SAMLContactField,
     allow_blank=True,
-    required=True,
     label=_('SAML Service Provider Technical Contact'),
     help_text=_('Provide the name and email address of the technical contact for'
                 ' your service provider. Refer to the Ansible Tower documentation'
@@ -1043,7 +1041,6 @@ register(
     'SOCIAL_AUTH_SAML_SUPPORT_CONTACT',
     field_class=fields.SAMLContactField,
     allow_blank=True,
-    required=True,
     label=_('SAML Service Provider Support Contact'),
     help_text=_('Provide the name and email address of the support contact for your'
                 ' service provider. Refer to the Ansible Tower documentation for'
```

I would raise this as a PR, but someone presumably spent effort putting those `required=True` settings in there for a reason!

**Comment by jakemcdermott** [comment]
Hello @willthames 

To configure SAML, you should definitely use the rest API or the UI instead of modifying the settings file. If you continue to see this issue when doing so, please create an issue for it as it would indicate an API or UI bug. Thank you!
