### ISSUE TITLE
1.0.6.23 - New Docker images won't install. FRESH Vm

### ISSUE THREAD

**Issue by amostech** [ansible/awx#2021]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

Trying to install @latest from Docker Hub and it's always failing. This installation process used to work because I installed it using docker images last week and it worked.

On monday morning I tried to login to the AWX dashboard and I realized that I had no access to it anymore. Trying to reinstall fresh and the process does not complete.

##### ENVIRONMENT
* AWX version: 1.0.6.23 (latest as of now)
* AWX install method: docker on Centos 7
* Ansible version:  2.5.5
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1) Create a Centos 7 VM
2) Disable SELINUX: https://www.centos.org/docs/5/html/5.1/Deployment_Guide/sec-sel-enable-disable.html
3) Stop Firewall: systemctl stop firewalld
4) Prepare package subsystem:

yum repolist
yum install epel-release
yum install git gettext ansible docker nodejs npm gcc-c++ bzip2 python-docker-py

5) Start Docker service

systemctl start docker
systemctl enable docker

5) Clone Ansible AWX from Github:

git clone https://github.com/ansible/awx.git

6) Install Ansible AWX docker containers:

ansible-playbook -i inventory install.yml

##### EXPECTED RESULTS

That the ansible AWX console installed properly.

##### ACTUAL RESULTS

I'm having many issues today with this, but as of this moment the latest error I got was:

```

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error starting container
b7b77a522a776c056af96de403bc7d6c943194047855dd3ed0132d24abe60270: 500 Server Error: 
Internal Server Error (\"{\"message\":\"driver failed programming external connectivity on endpoint 
awx_web (42b44ac228e48b6416ce6fad98aa0755e421473ededc36551959bb67b15c2082):  
(iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 80 -j DNAT --to-destination 
172.17.0.5:8052 ! -i docker0: iptables: No chain/target/match by that name.\\n (exit status 1))\"}\")"}

```

**Comment by amostech** [comment]
It looks like this problem is related to Docker not creating the correct iptables rules during installation. 

For future reference executing the following commands unblocked this case:

1. Clear all chains:

```
iptables -t filter -F
```

```
iptables -t filter -X
```

2. Then restart Docker Service:
```
systemctl restart docker
```

That worked ok. Now I'm trying to install Ansible AWX v.1.0.5 to compare and understand the reason why v1.0.6.23 is failing.

**Comment by amostech** [comment]
After unblocking the iptables port 80 issue. The following problem is being repeatedly reported in awx_task logs:

```
2018-06-26 22:39:22,909 INFO     awx.main.tasks Syncing Schedules
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 785, in handle_argv
    return self.execute(command, argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 717, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/worker/__init__.py", line 96, in __init__
    self.on_before_init(**kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/apps/worker.py", line 120, in on_before_init
    conf=self.app.conf, options=kwargs,
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 103, in celery_startup
    for sch in Schedule.objects.all():
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
django.db.utils.ProgrammingError: column main_schedule.inventory_id does not exist
LINE 1: ...hedule"."modified_by_id", "main_schedule"."name", "main_sche...
                                                             ^
2018-06-26 22:39:23,060 INFO exited: celery (exit status 1; not expected)
2018-06-26 22:39:24,064 INFO spawned: 'celery' with pid 466
```

No apparent errors displayed in awx_web logs though. I'm stuck at this point. Not sure how to proceed. It looks like the installer is not being able to create the required postgres tables?

**Comment by amostech** [comment]
Please disregard this issue. I was running a VM with 1GB of RAM and the process was not working properly.

Closing it.
