### ISSUE TITLE
Problem with non ASCII characters in awx-cli receive

### ISSUE THREAD

**Issue by icsm2017** [ansible/awx#2029]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
When I use `awx-cli receive` to migrate data, I have unicode characters in the content files. During the import I have an error.

##### ENVIRONMENT
* AWX version: 1.0.2 -> 1.0.6 (target)
* AWX install method: docker on linux
* Ansible version:  2.4.2 -> 2.5.5 (target)
* Operating System: RHEL 7.4
* Web Browser: Chrome

##### STEPS TO REPRODUCE
1 - Import data in file with `awx-cli receive -u admin  -p ***** -h http://ansible-build --all > assets.json`
2 - an extract from the file :  
```
  {
    "inputs": {
      "vault_password": ""
    },
    "name": "Ingdev Forge Vault Master",
    "asset_type": "credential",
    "credential_type": "Vault",
    "organization": "Ing\u00e9nieries de d\u00e9veloppement",
    "asset_relation": {
      "roles": [
        {
          "team": [],
          "name": "Use",
          "user": []
        },
        {
          "team": [],
          "name": "Read",
          "user": []
        },
        {
          "team": [
            "Ing\u00e9nieries de d\u00e9veloppement - Forge"
          ],
          "name": "Admin",
          "user": [
            "97000t"
          ]
        }
      ]
    }
```
3 - export the data to the target server : `awx-cli send -u admin  -p ***** -h http://ansible-target assets.json`

##### EXPECTED RESULTS

Data has been migrated with special characters like "é"

##### ACTUAL RESULTS

```
Traceback (most recent call last):
  File "/bin/awx-cli", line 11, in <module>
    load_entry_point('ansible-tower-cli==3.3.0', 'console_scripts', 'awx-cli')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/conf.py", line 359, in method_with_context_managed
    method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/misc.py", line 366, in send
    sender.send(source, prevent, secret_management)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/transfer/send.py", line 51, in send
    self.print_header_row(asset_type, asset_name)
  File "/usr/lib/python2.7/site-packages/tower_cli/cli/transfer/logging_command.py", line 27, in print_header_row
    self.my_print("{} [{}] {}".format(asset_type.replace("_", " ").upper(), asset_name, stars))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 4: ordinal not in range(128)
```

**Comment by AlanCoding** [comment]
Thank you for the report, this is something we would like to address.

I have re-filed your issue in the tower-cli repo https://github.com/ansible/tower-cli/issues/562, the issue queue here can only address issues related to the AWX server, and CLI issues have to be addressed in that other repo.

**Comment by krentiken** [comment]
ok. thanks for the answer
