### ISSUE TITLE
Attempting to log on with a LDAP user simply logs a 401 error

### ISSUE THREAD

**Issue by mhurron** [ansible/awx#2060]
##### ISSUE TYPE
 - Bug Report
 

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Attempting to log on with a LDAP user simply logs a 401 error. Logging in with a locally defined user works.

- "POST /api/login/ HTTP/1.1" 401 5879 "https://host.domain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.1 Safari/605.1.15"

##### ENVIRONMENT
* AWX version: 1.0.6.25
* AWX install method: docker on linux
* Ansible version:  version included in docker container
* Operating System: RHEL7
* Web Browser: Safari

##### STEPS TO REPRODUCE

Configure LDAP: (obviously changed sensitive information)

"AUTH_LDAP_SERVER_URI": "ldap://controller.domain.com:389",
    "AUTH_LDAP_BIND_DN": "CN=awxuser,OU=Users,DC=domain,DC=com",
    "AUTH_LDAP_BIND_PASSWORD": [password],
    "AUTH_LDAP_START_TLS": false,
    "AUTH_LDAP_CONNECTION_OPTIONS": {
        "OPT_NETWORK_TIMEOUT": 30,
        "OPT_REFERRALS": 0
    },
    "AUTH_LDAP_USER_SEARCH": ["OU=Users,DC=domain,DC=com","SCOPE_SUBTREE","(cn=%(user)s)"],
    "AUTH_LDAP_USER_DN_TEMPLATE": "",
    "AUTH_LDAP_USER_ATTR_MAP": {},
    "AUTH_LDAP_GROUP_SEARCH": ["OU=Groups,dc=domain,dc=com","SCOPE_SUBTREE","(objectClass=group)"],
    "AUTH_LDAP_GROUP_TYPE": "ActiveDirectoryGroupType",
    "AUTH_LDAP_GROUP_TYPE_PARAMS": {},
    "AUTH_LDAP_REQUIRE_GROUP": null,
    "AUTH_LDAP_DENY_GROUP": null,
    "AUTH_LDAP_USER_FLAGS_BY_GROUP": {"is_superuser": "CN=admins,OU=Groups,DC=domain,dc=com"},

Login via UI with LDAP user.

##### EXPECTED RESULTS

Access should be granted

##### ACTUAL RESULTS

"POST /api/login/ HTTP/1.1" 401 5879 "https://host.domain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.1 Safari/605.1.15"

UI displays - Invalid username and/or password. Please try again.

**Comment by mhurron** [comment]
After a little digging it appears that the authentication failure is occurring at sso/backends.py https://github.com/mhurron/awx/blob/a98367f4ac8845ff975a910dabdaf666f8e405d5/awx/sso/backends.py#L104-L106

```
user = User.objects.get(username=username)
if user and (not user.profile or not user.profile.ldap_dn):
    return None
```

Logging in as a valid LDAP user is creating the user and profile in Django, but not filling in the ldap_dn property.

**Comment by onitake** [comment]
I'm not 100% sure, but it seems like I was hitting the same issue here.

My LDAP group parameters were specified as follows:
```json
{
 "name_attr": "cn",
 "ldap_group_user_attr": "uid"
}
```
This has worked fine in 1.0. In 1.0.6, it doesn't, but the paramters are no longer required, because these exact values are now the defaults of `PosixUIDGroupType`.
After removing them login will succeed again.

However, if you need custom values for these parameters, it seems to me that there is an invalid unicode/non-unicode string key search buried in the code, which will produce the following stack trace:
```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awx/sso/backends.py", line 110, in authenticate
    return super(LDAPBackend, self).authenticate(username, password)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 167, in authenticate
    user = ldap_user.authenticate(password)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 339, in authenticate
    self._get_or_create_user()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 570, in _get_or_create_user
    signal_responses = populate_user.send(self.backend.__class__, user=self._user, ldap_user=self)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/usr/lib/python2.7/site-packages/awx/sso/backends.py", line 352, in on_populate_user
    ldap_user._get_groups().get_group_dns()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 828, in get_group_dns
    group_infos = self._get_group_infos()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 840, in _get_group_infos
    self._group_search)
  File "/usr/lib/python2.7/site-packages/awx/sso/ldap_group_types.py", line 46, in user_groups
    groups = search.execute(ldap_user.connection)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django_auth_ldap/config.py", line 164, in execute
    self.attrlist)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/ldap/ldapobject/simple.py", line 875, in search_s
    timeout=self.timeout
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/ldap/ldapobject/simple.py", line 852, in search_ext_s
    sizelimit
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/ldap/ldapobject/simple.py", line 828, in search_ext
    sizelimit,
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/ldap/ldapobject/simple.py", line 91, in _ldap_call
    result = func(*args, **kwargs)
TypeError: ('expected string in list', u'cn')
```

**Comment by chrismeyersfsu** [comment]
Hey @onitake I've been able to recreate your issue and have a fix. If you get a chance, can you see if the fix works for you? Thanks!

https://github.com/ansible/awx/pull/2425

**Comment by onitake** [comment]
@chrismeyersfsu I'll try, but I'm a bit short on time currently. Still, thanks for the fix!

**Comment by jakemcdermott** [comment]
This should be resolved with @chrismeyersfsu 's recent code changes. Please re-open if you continue to see this issue after updating to the latest version of AWX. Thanks!
