### ISSUE TITLE
Inventory Sync fails when role has no meta/main.yml

### ISSUE THREAD

**Issue by juame** [ansible/awx#2071]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Inventory Sync fails when there's a role in `roles/requirements.yml` without meta information.

##### ENVIRONMENT
* AWX version: 1.0.6.11
* AWX install method: docker on linux
* Ansible version:  2.5.3
* Operating System: Docker on RedHat
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Create role and push it to a git repository **(no `meta/main.yml`)** :
```
.
├── README.md
├── defaults
│   └── main.yml
├── tasks
│   └── main.yml
└── vars
    └── main.yml
```
2. Add git repository with role to roles/requirements.yml
```
- src: ssh://git@git.example.com/project/role_xyz.git
  scm: git
  version: master
```
3. Trigger Project Sync (Get latest SCM revision)
4. Trigger Inventory Sync

##### EXPECTED RESULTS

It should just work or display a better error message to the user.

##### ACTUAL RESULTS

Inventory Sync (Sourced from a Project - GIT) fails with error (stdout awx_task container):
```
[2018-07-17 06:34:48,248: ERROR/MainProcess] Task awx.main.tasks.run_inventory_update[88d99090-e543-4ac8-a036-e9fb070fab71] raised unexpected: Exception(u'inventory_update 903 (error) encountered an error (rc=None), please see task stdout for details.',)
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 574, in _wrapped
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 1027, in run
    raise AwxTaskError.TaskError(instance, rc)
Exception: inventory_update 903 (error) encountered an error (rc=None), please see task stdout for details.
```

##### ADDITIONAL INFORMATION

![screen shot 2018-07-17 at 08 58 11](https://user-images.githubusercontent.com/7010789/42801800-1afecaa2-89a1-11e8-9f46-662cdf8e5ad2.png)

**Comment by AlanCoding** [comment]
could you navigate to `/api/v2/project_updates/904/stdout/` and give the output there? There is supposed to be a clickable link to this in the job details page, but I don't see this link in your case.

**Comment by juame** [comment]
@AlanCoding copy & paste of the stdout:
```


HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: text/plain ;utf-8
Vary: Accept
X-API-Node: awx
X-API-Time: 0.035s



Enter passphrase for /tmp/awx_904_8QimoI/credential_2: 
Identity added: /tmp/awx_904_8QimoI/credential_2 (/tmp/awx_904_8QimoI/credential_2)
Using /etc/ansible/ansible.cfg as config file


PLAY [all] *********************************************************************

TASK [delete project directory before update] **********************************
skipping: [localhost]

TASK [check repo using git] ****************************************************
ok: [localhost]

PLAY [all] *********************************************************************

TASK [detect requirements.yml] *************************************************
ok: [localhost]

TASK [fetch galaxy roles from requirements.yml] ********************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["ansible-galaxy", "install", "-r", "requirements.yml", "-p", "/var/lib/awx/projects/_5__awx_prod_zhb/roles/"], "delta": "0:00:01.297383", "end": "2018-07-17 06:34:47.908958", "msg": "non-zero return code", "rc": 1, "start": "2018-07-17 06:34:46.611575", "stderr": "\\u001b[1;35m [WARNING]: - role_xyz was NOT installed successfully: this role does\\u001b[0m\\n\\u001b[1;35mnot appear to have a meta/main.yml file.\\u001b[0m\\n\\u001b[1;35m\\u001b[0m\\n\\u001b[0;31mERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.\\u001b[0m", "stderr_lines": ["\\u001b[1;35m [WARNING]: - role_xyz was NOT installed successfully: this role does\\u001b[0m", "\\u001b[1;35mnot appear to have a meta/main.yml file.\\u001b[0m", "\\u001b[1;35m\\u001b[0m", "\\u001b[0;31mERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.\\u001b[0m"], "stdout": "- role_xyz1 (master) is already installed, skipping.\\n- role_xyz2 (master) is already installed, skipping.\\n- role_xyz3 (master) is already installed, skipping.\\n- role_xyz4 (master) is already installed, skipping.", "stdout_lines": ["- role_xyz1 (master) is already installed, skipping.", "- role_xyz2 (master) is already installed, skipping.", "- role_xyz3 (master) is already installed, skipping.", "- role_xyz4 (master) is already installed, skipping."]}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   
```

**Comment by AlanCoding** [comment]
The UI issues for failed dependent project updates are known and on the agenda: https://github.com/ansible/awx/issues/1907

It sounds like the main issue is that we need to be clear about surfacing the error from the "fetch galaxy roles", or is there some adjustment that we should make to the playbook to handle these cases?

relevant playbook content:

https://github.com/ansible/awx/blob/f0707ad7013fb77e3a917c570466bb54b7d934ca/awx/playbooks/project_update.yml#L137-L147

**Comment by juame** [comment]
@AlanCoding thanks for your feedback! So, the UI fix will help others to find the reason faster than I did. ;-)
To be honest: Don't know what's the best way to handle errors from the `ansible-galaxy` command.

**Comment by matburt** [comment]
Original issue should probably be taken up with the galaxy team... we'll work on better presentation of errors elsewhere.
