### ISSUE TITLE
auto restart containers

### ISSUE THREAD

**Issue by mwasilew2** [ansible/awx#210]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - Installer

##### SUMMARY
containers created after following: https://github.com/ansible/awx/blob/devel/INSTALL.md will not come back online if the docker daemon dies/host reboots

this issue is about changing restart_policy on the docker_containers in: https://github.com/ansible/awx/blob/devel/installer/local_docker/tasks/main.yml

##### ENVIRONMENT
* AWX version: 1.0.0.395
* Ansible version:  2.3.2.0
* Operating System: Debian 9.1
* Web Browser: Firefox

##### STEPS TO REPRODUCE

- follow the installation docs as linked above
- reboot the host machine
- AWX should come back online by itself

##### ADDITIONAL INFORMATION

I'm happy to submit a PR, can someone confirm this to be in-line with the general direction?

**Comment by matburt** [comment]
Yep this is definitely how we want this to behave.

Edit... fixing this bug, I mean. We definitely want the containers to come back up after restart.

**Comment by daoustc** [comment]
How we can restart projet after reboot ?

**Comment by mwasilew2** [comment]
@daoustc you can restart it by reapplying the install playbook (or applying the fix manually and running the install playbook)

I forked devel and I'm getting python errors on: `(container)/awx_devel$ make test`  (haven't touched anything yet)

first error in a row:
```
awx/sso/tests/unit/test_ldap.py .F
awx/sso/tests/unit/test_tacacsplus.py .....

========================================================================================== FAILURES ==========================================================================================
______________________________________________________________________ RunAdHocCommandTest.test_ad_hoc_command_options _______________________________________________________________________
Traceback (most recent call last):
  File "/venv/awx/lib/python2.7/site-packages/mock/mock.py", line 1297, in patched
    arg = patching.__enter__()
  File "/venv/awx/lib/python2.7/site-packages/mock/mock.py", line 1369, in __enter__
    original, local = self.get_original()
  File "/venv/awx/lib/python2.7/site-packages/mock/mock.py", line 1343, in get_original
    "%s does not have the attribute %r" % (target, name)
AttributeError: <class BaseTask of default:0x5434250> does not have the attribute 'run_pexpect'

```


debug info (inside the awx_devel container):
```
# uname -a
Linux awx 4.12.13-300.fc26.x86_64 #1 SMP Thu Sep 14 16:00:38 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
# python
Python 2.7.5 (default, Aug  4 2017, 00:39:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mock
>>> mock.__version__
'2.0.0'
>>> 

```

the image was built from the latest centos:7 (released 5 days ago):
```
docker history gcr.io/ansible-tower-engineering/awx_devel:devel
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
dbe8a98ac243        3 hours ago         /bin/sh -c #(nop)  CMD ["/bin/sh" "-c" "/s...   0B                  
f50ff7858217        3 hours ago         /bin/sh -c #(nop)  ENTRYPOINT ["/tini" "--"]    0B                  
bb8b3a439d42        3 hours ago         /bin/sh -c #(nop)  EXPOSE 22/tcp 8013/tcp ...   0B                  
c630b6d0c58d        3 hours ago         /bin/sh -c #(nop) WORKDIR /                     0B                  
6fd353f2b727        3 hours ago         /bin/sh -c chmod +x /tini                       19.9kB              
aae12be926e8        3 hours ago         /bin/sh -c #(nop) ADD 4fa3d24e60ad01b3ac84...   19.9kB              
e0a1df8378ca        3 hours ago         /bin/sh -c #(nop)  ENV LC_ALL=en_US.UTF-8       0B                  
4d5bbe0badf1        3 hours ago         /bin/sh -c #(nop)  ENV LANGUAGE=en_US:en        0B                  
e79b42ed51b7        3 hours ago         /bin/sh -c #(nop)  ENV LANG=en_US.UTF-8         0B                  
71343bb01c95        3 hours ago         /bin/sh -c localedef -c -i en_US -f UTF-8 ...   3.49MB              
b132cf24c475        3 hours ago         /bin/sh -c SWIG_FEATURES="-cpperraswarn -i...   618MB               
7e8219f9b7df        3 hours ago         /bin/sh -c #(nop) WORKDIR /tmp                  0B                  
bd690b9c94ed        3 hours ago         /bin/sh -c openssl x509 -req -days 365 -in...   2.28kB              
77474944c21f        3 hours ago         /bin/sh -c openssl req -nodes -newkey rsa:...   3.76kB              
ca3a80ef76c7        3 hours ago         /bin/sh -c ln -s /awx_devel/tools/docker-c...   56B                 
2334b5eff4ed        3 hours ago         /bin/sh -c ln -s /awx_devel/tools/docker-c...   52B                 
640d5ac615bd        3 hours ago         /bin/sh -c ln -Ffs /awx_devel/tools/docker...   53B                 
2930086f05a2        3 hours ago         /bin/sh -c ln -Ffs /awx_devel/tools/docker...   42B                 
03df7dd38fa6        3 hours ago         /bin/sh -c #(nop) ADD dir:c0bdde66905c41f1...   1.13MB              
e8f950e8c1d6        3 hours ago         /bin/sh -c #(nop) ADD file:4af34316a030706...   279B                
1ab7d0d948fd        3 hours ago         /bin/sh -c #(nop) ADD file:f652a529873c9a7...   10B                 
b8b1f422a506        3 hours ago         /bin/sh -c pip2 install supervisor              3.18MB              
688f2791a0dd        3 hours ago         /bin/sh -c pip2 install honcho                  113kB               
6a2f84931293        3 hours ago         /bin/sh -c mkdir -p /data/db                    0B                  
2a061e423c23        3 hours ago         /bin/sh -c /usr/bin/ssh-keygen -q -t rsa -...   2.08kB              
d36b1e16876a        3 hours ago         /bin/sh -c pip install virtualenv               3.88MB              
a8a912ee92ce        3 hours ago         /bin/sh -c yum -y update && yum -y install...   466MB               
27867452faf5        3 hours ago         /bin/sh -c yum -y localinstall http://down...   20.8MB              
133ecab5f733        3 hours ago         /bin/sh -c curl --silent --location https:...   20.5MB              
f7840b7f10a0        3 hours ago         /bin/sh -c yum -y update && yum -y install...   74.7MB              
4b49ee974b22        3 hours ago         /bin/sh -c #(nop) ADD multi:57ef39d5a0fc9d...   19.5kB              
7a486512255b        3 hours ago         /bin/sh -c mkdir /tmp/requirements              0B                  
db0b70467746        3 hours ago         /bin/sh -c #(nop) ADD file:9050482d42ae243...   20.3kB              
196e0ce0c9fb        5 days ago          /bin/sh -c #(nop)  CMD ["/bin/bash"]            0B                  
<missing>           5 days ago          /bin/sh -c #(nop)  LABEL name=CentOS Base ...   0B                  
<missing>           5 days ago          /bin/sh -c #(nop) ADD file:1ed4d1a29d09a63...   197MB
```

I've initialized awx with `awx-manage createsuperuser` and `awx-manage create_preload_data` and it's accessible over a web browser on localhost

looking at BaseTask in awx/awx/main/tasks.py, line 873: https://github.com/ansible/awx/blob/e4fa0e8a3939fea9034678323562c846b28275e2/awx/main/tasks.py#L873 it's unclear to me what went wrong

any ideas?

**Comment by matburt** [comment]
I repulled my image and refreshed all of my dev containers and tests are all passing for me? I did have some issues before that though.

**Comment by matburt** [comment]
I'll typically just run pytest on awx/main/tests/{functional,unit} I may update the make target to do that.

**Comment by tupcakes** [comment]
> Yep this is definitely how we want this to behave

Honest question. Why is this? I would think you'd want the application to come back up after a server restart.

**Comment by matburt** [comment]
> Honest question. Why is this? I would think you'd want the application to come back up after a server restart.

I might not have been clear, I meant to suggest that we *do* want the containers to come back up after restart. Meaning, the fixing of this bug is how we want it to behave (I updated my original comment)

**Comment by daoustc** [comment]
For me a restart in automatic or a script like tower's project.

ansible-tower-service
http://docs.ansible.com/ansible-tower/latest/html/administration/init_script.html

**Comment by tupcakes** [comment]
Ok gotcha. Need more coffee.

**Comment by matburt** [comment]
done in #228
