### ISSUE TITLE
SAML XML metadata endpoint produces "sp_acs_url_invalid" error no matter which value is provided

### ISSUE THREAD

**Issue by balpert89** [ansible/awx#214]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

 - API

##### SUMMARY
SAML metadata produces error although the ACS address is created automatically.

##### STEPS TO REPRODUCE
Configure AWX with a SAML provider. It does not matter which values to provide, the metadata endpoint still reports a `Invalid dict settings: sp_acs_url_invalid`

##### EXPECTED RESULTS

The correct metadata xml document.

##### ACTUAL RESULTS
`Invalid dict settings: sp_acs_url_invalid`
##### ADDITIONAL INFORMATION

I cannot bring AWX to generate the needed metadata, browsing to the metadata endpoint provides the following: Invalid dict settings: sp_acs_url_invalid

Log from the awx-web container:
```
2017-09-15 20:42:51,465 ERROR    awx.sso.views unable to generate SAML metadata
--
  | Traceback (most recent call last):
  | File "/usr/lib/python2.7/site-packages/awx/sso/views.py", line 90, in get
  | metadata, errors = saml_backend.generate_metadata_xml()
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social/backends/saml.py", line 238, in generate_metadata_xml
  | saml_settings = OneLogin_Saml2_Settings(config)
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/onelogin/saml2/settings.py", line 104, in __init__
  | ','.join(self.__errors)
  | OneLogin_Saml2_Error: Invalid dict settings: sp_acs_url_invalid

2017-09-15 20:47:01,511 ERROR    awx.sso.views unable to generate SAML metadata
--
  | Traceback (most recent call last):
  | File "/usr/lib/python2.7/site-packages/awx/sso/views.py", line 90, in get
  | metadata, errors = saml_backend.generate_metadata_xml()
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social/backends/saml.py", line 238, in generate_metadata_xml
  | saml_settings = OneLogin_Saml2_Settings(config)
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/onelogin/saml2/settings.py", line 104, in __init__
  | ','.join(self.__errors)
  | OneLogin_Saml2_Error: Invalid dict settings: sp_acs_url_invalid
```
This error is risen because of this (/var/lib/awx/venv/awx/lib/python2.7/site-packages/social/backends/saml.py):
```
    def generate_metadata_xml(self):
        """
        Helper method that can be used from your web app to generate the XML
        metadata required to link your web app as a Service Provider with
        each IdP you wish to use.

        Returns (metadata XML string, list of errors)

        Example usage (Django):
            from social.apps.django_app.utils import load_strategy, \
                                                     load_backend
            def saml_metadata_view(request):
                complete_url = reverse('social:complete', args=("saml", ))
                saml_backend = load_backend(load_strategy(request), "saml",
                                            complete_url)
                metadata, errors = saml_backend.generate_metadata_xml()
                if not errors:
                    return HttpResponse(content=metadata,
                                        content_type='text/xml')
                return HttpResponseServerError(content=', '.join(errors))
        """
        # python-saml requires us to specify something here even
        # though it's not used
        idp = DummySAMLIdentityProvider()
        config = self.generate_saml_config(idp)
        saml_settings = OneLogin_Saml2_Settings(config) << This one throws an exception
        metadata = saml_settings.get_sp_metadata()
        errors = saml_settings.validate_metadata(metadata)
        return metadata, errors
```
The dummy class (/var/lib/awx/venv/awx/lib/python2.7/site-packages/social/backends/saml.py):
```
class DummySAMLIdentityProvider(SAMLIdentityProvider):
    """
    A placeholder IdP used when we must specify something, e.g. when
    generating SP metadata.

    If OneLogin_Saml2_Auth is modified to not always require IdP
    config, this can be removed.
    """
    def __init__(self):
        super(DummySAMLIdentityProvider, self).__init__(
            'dummy',
            entity_id='https://dummy.none/saml2',
            url='https://dummy.none/SSO',
            x509cert=''
        )
```
Maybe the Dummy class settings are messed up. I am not sure if this error occurs because I messed up the configuration, though (I am not proficient in python). Please take a look at it:

![30502839-3a6285ec-9a68-11e7-990f-4cef2987e8b3](https://user-images.githubusercontent.com/28100685/30605805-cf58fca8-9d6f-11e7-9bc5-1c4c2551f8b0.png)

Best regards and have a nice evening (from germany)

**Comment by abhipanda** [comment]
Hi,

I am facing the same issue trying to configure SAML in our local instance.
Is this a blocker for any SAML configuration or for specific conditions ?

Thanks,

**Comment by matburt** [comment]
Can you try this with the latest AWX version?

**Comment by matburt** [comment]
No comment in over a month, closing
