### ISSUE TITLE
celery does not restore connection to the database after losing it

### ISSUE THREAD

**Issue by YuriGrigorov** [ansible/awx#2210]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - celery

##### SUMMARY
If for some reason connection between celery and database is lost, celery stops running tasks. When connection is restored, celery does not restore the connection to the database. You need to restart celery to solve problem.

##### ENVIRONMENT
* AWX version: 1.0.7.3
* Operating System: CentOS 7

##### STEPS TO REPRODUCE
Run all components.
Stop the database (or add iptables rule to deny access from celery).
Watch celery log.
```
[2018-08-29 19:47:59,749: ERROR/Beat] Message Error: Couldn't apply scheduled task task_manager: connection already closed
```
Start the database.
After database is up error messagese still present.

##### EXPECTED RESULTS
The connection to the database must be restored

##### ACTUAL RESULTS
The connection to the database is not restored

##### ADDITIONAL INFORMATION
```
Aug 29 22:47:59 celery[273]: [2018-08-29 19:47:59,622: INFO/Beat] Scheduler: Sending due task cluster_heartbeat (awx.main.tasks.cluster_node_heartbeat)
Aug 29 22:47:59 celery[273]: [2018-08-29 19:47:59,698: ERROR/Beat] Message Error: Couldn't apply scheduled task cluster_heartbeat: server closed the connection unexpectedly
Aug 29 22:47:59 celery[273]: This probably means the server terminated abnormally
Aug 29 22:47:59 celery[273]: before or while processing the request.
Aug 29 22:47:59 celery[273]: ['  File "/var/lib/awx/venv/awx/bin/celery", line 11, in <module>\n    sys.exit(main())\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/__main__.py", line 30, in main\n    main()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main\n    cmd.execute_from_commandline(argv)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline\n    super(CeleryCommand, self).execute_from_commandline(argv)))\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline\n    return self.handle_argv(self.prog_name, argv[1:])\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 785, in handle_argv\n    return self.execute(command, argv)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 717, in execute\n    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv\n    return self(*args, **options)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/base.py", line 274, in __call__\n    ret = self.run(*args, **kwargs)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run\n    state_db=self.node_format(state_db, hostname), **kwargs\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start\n    self.blueprint.start(self)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start\n    step.start(parent)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start\n    return self.obj.start()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/billiard/process.py", line 137, in start\n    self._popen = Popen(self)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/billiard/forking.py", line 105, in __init__\n    code = process_obj._bootstrap()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/billiard/process.py", line 292, in _bootstrap\n    self.run()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 553, in run\n    self.service.start(embedded_process=True)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 479, in start\n    interval = self.scheduler.tick()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 221, in tick\n    next_time_to_run = self.maybe_due(entry, self.publisher)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 207, in maybe_due\n    exc, traceback.format_stack(), exc_info=True)\n']
Aug 29 22:47:59 celery[273]: Traceback (most recent call last):
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 204, in maybe_due
Aug 29 22:47:59 celery[273]: result = self.apply_async(entry, publisher=publisher)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 260, in apply_async
Aug 29 22:47:59 celery[273]: entry, exc=exc)), sys.exc_info()[2])
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 252, in apply_async
Aug 29 22:47:59 celery[273]: **entry.options)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/task.py", line 573, in apply_async
Aug 29 22:47:59 celery[273]: **dict(self._get_exec_options(), **options)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/base.py", line 345, in send_task
Aug 29 22:47:59 celery[273]: options = router.route(options, name, args, kwargs)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/routes.py", line 50, in route
Aug 29 22:47:59 celery[273]: route = self.lookup_route(task, args, kwargs)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/routes.py", line 78, in lookup_route
Aug 29 22:47:59 celery[273]: return _first_route(self.routes, task, args, kwargs)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/utils/functional.py", line 233, in _matcher
Aug 29 22:47:59 celery[273]: answer = getattr(maybe_evaluate(obj), method)(*args, **kwargs)
Aug 29 22:47:59 celery[273]: File "/usr/lib/python2.7/site-packages/awx/main/utils/ha.py", line 11, in route_for_task
Aug 29 22:47:59 celery[273]: (changed, instance) = Instance.objects.get_or_register()
Aug 29 22:47:59 celery[273]: File "/usr/lib/python2.7/site-packages/awx/main/managers.py", line 104, in get_or_register
Aug 29 22:47:59 celery[273]: return self.register()
Aug 29 22:47:59 celery[273]: File "/usr/lib/python2.7/site-packages/awx/main/managers.py", line 95, in register
Aug 29 22:47:59 celery[273]: with advisory_lock('instance_registration_%s' % hostname):
Aug 29 22:47:59 celery[273]: File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
Aug 29 22:47:59 celery[273]: return self.gen.next()
Aug 29 22:47:59 celery[273]: File "/usr/lib/python2.7/site-packages/awx/main/utils/pglock.py", line 13, in advisory_lock
Aug 29 22:47:59 celery[273]: with django_pglocks_advisory_lock(*args, **kwargs) as internal_lock:
Aug 29 22:47:59 celery[273]: File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
Aug 29 22:47:59 celery[273]: return self.gen.next()
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django_pglocks/__init__.py", line 66, in advisory_lock
Aug 29 22:47:59 celery[273]: cursor.execute(command)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
Aug 29 22:47:59 celery[273]: return self.cursor.execute(sql, params)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
Aug 29 22:47:59 celery[273]: six.reraise(dj_exc_type, dj_exc_value, traceback)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
Aug 29 22:47:59 celery[273]: return self.cursor.execute(sql)
Aug 29 22:47:59 celery[273]: SchedulingError: Couldn't apply scheduled task cluster_heartbeat: server closed the connection unexpectedly
Aug 29 22:47:59 celery[273]: This probably means the server terminated abnormally
Aug 29 22:47:59 celery[273]: before or while processing the request.
Aug 29 22:47:59 celery[273]: [2018-08-29 19:47:59,748: INFO/Beat] Scheduler: Sending due task task_manager (awx.main.scheduler.tasks.run_task_manager)
Aug 29 22:47:59 celery[273]: [2018-08-29 19:47:59,749: ERROR/Beat] Message Error: Couldn't apply scheduled task task_manager: connection already closed
Aug 29 22:47:59 celery[273]: ['  File "/var/lib/awx/venv/awx/bin/celery", line 11, in <module>\n    sys.exit(main())\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/__main__.py", line 30, in main\n    main()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main\n    cmd.execute_from_commandline(argv)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline\n    super(CeleryCommand, self).execute_from_commandline(argv)))\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline\n    return self.handle_argv(self.prog_name, argv[1:])\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 785, in handle_argv\n    return self.execute(command, argv)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 717, in execute\n    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv\n    return self(*args, **options)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/base.py", line 274, in __call__\n    ret = self.run(*args, **kwargs)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run\n    state_db=self.node_format(state_db, hostname), **kwargs\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start\n    self.blueprint.start(self)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start\n    step.start(parent)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start\n    return self.obj.start()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/billiard/process.py", line 137, in start\n    self._popen = Popen(self)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/billiard/forking.py", line 105, in __init__\n    code = process_obj._bootstrap()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/billiard/process.py", line 292, in _bootstrap\n    self.run()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 553, in run\n    self.service.start(embedded_process=True)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 479, in start\n    interval = self.scheduler.tick()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 221, in tick\n    next_time_to_run = self.maybe_due(entry, self.publisher)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 207, in maybe_due\n    exc, traceback.format_stack(), exc_info=True)\n']
Aug 29 22:47:59 celery[273]: Traceback (most recent call last):
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 204, in maybe_due
Aug 29 22:47:59 celery[273]: result = self.apply_async(entry, publisher=publisher)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 260, in apply_async
Aug 29 22:47:59 celery[273]: entry, exc=exc)), sys.exc_info()[2])
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 252, in apply_async
Aug 29 22:47:59 celery[273]: **entry.options)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/task.py", line 573, in apply_async
Aug 29 22:47:59 celery[273]: **dict(self._get_exec_options(), **options)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/base.py", line 345, in send_task
Aug 29 22:47:59 celery[273]: options = router.route(options, name, args, kwargs)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/routes.py", line 50, in route
Aug 29 22:47:59 celery[273]: route = self.lookup_route(task, args, kwargs)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/routes.py", line 78, in lookup_route
Aug 29 22:47:59 celery[273]: return _first_route(self.routes, task, args, kwargs)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/utils/functional.py", line 233, in _matcher
Aug 29 22:47:59 celery[273]: answer = getattr(maybe_evaluate(obj), method)(*args, **kwargs)
Aug 29 22:47:59 celery[273]: File "/usr/lib/python2.7/site-packages/awx/main/utils/ha.py", line 11, in route_for_task
Aug 29 22:47:59 celery[273]: (changed, instance) = Instance.objects.get_or_register()
Aug 29 22:47:59 celery[273]: File "/usr/lib/python2.7/site-packages/awx/main/managers.py", line 104, in get_or_register
Aug 29 22:47:59 celery[273]: return self.register()
Aug 29 22:47:59 celery[273]: File "/usr/lib/python2.7/site-packages/awx/main/managers.py", line 95, in register
Aug 29 22:47:59 celery[273]: with advisory_lock('instance_registration_%s' % hostname):
Aug 29 22:47:59 celery[273]: File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
Aug 29 22:47:59 celery[273]: return self.gen.next()
Aug 29 22:47:59 celery[273]: File "/usr/lib/python2.7/site-packages/awx/main/utils/pglock.py", line 13, in advisory_lock
Aug 29 22:47:59 celery[273]: with django_pglocks_advisory_lock(*args, **kwargs) as internal_lock:
Aug 29 22:47:59 celery[273]: File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
Aug 29 22:47:59 celery[273]: return self.gen.next()
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django_pglocks/__init__.py", line 64, in advisory_lock
Aug 29 22:47:59 celery[273]: cursor = connections[using].cursor()
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
Aug 29 22:47:59 celery[273]: return self._cursor()
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
Aug 29 22:47:59 celery[273]: return self._prepare_cursor(self.create_cursor(name))
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
Aug 29 22:47:59 celery[273]: six.reraise(dj_exc_type, dj_exc_value, traceback)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
Aug 29 22:47:59 celery[273]: return self._prepare_cursor(self.create_cursor(name))
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor
Aug 29 22:47:59 celery[273]: cursor = self.connection.cursor()
Aug 29 22:47:59 celery[273]: SchedulingError: Couldn't apply scheduled task task_manager: connection already closed
Aug 29 22:47:59 celery[273]: [2018-08-29 19:47:59,761: INFO/Beat] Scheduler: Sending due task tower_scheduler (awx.main.tasks.awx_periodic_scheduler)
Aug 29 22:47:59 celery[273]: [2018-08-29 19:47:59,762: ERROR/Beat] Message Error: Couldn't apply scheduled task tower_scheduler: connection already closed
Aug 29 22:47:59 celery[273]: ['  File "/var/lib/awx/venv/awx/bin/celery", line 11, in <module>\n    sys.exit(main())\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/__main__.py", line 30, in main\n    main()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main\n    cmd.execute_from_commandline(argv)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline\n    super(CeleryCommand, self).execute_from_commandline(argv)))\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline\n    return self.handle_argv(self.prog_name, argv[1:])\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 785, in handle_argv\n    return self.execute(command, argv)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 717, in execute\n    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv\n    return self(*args, **options)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/base.py", line 274, in __call__\n    ret = self.run(*args, **kwargs)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run\n    state_db=self.node_format(state_db, hostname), **kwargs\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start\n    self.blueprint.start(self)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start\n    step.start(parent)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start\n    return self.obj.start()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/billiard/process.py", line 137, in start\n    self._popen = Popen(self)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/billiard/forking.py", line 105, in __init__\n    code = process_obj._bootstrap()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/billiard/process.py", line 292, in _bootstrap\n    self.run()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 553, in run\n    self.service.start(embedded_process=True)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 479, in start\n    interval = self.scheduler.tick()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 221, in tick\n    next_time_to_run = self.maybe_due(entry, self.publisher)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 207, in maybe_due\n    exc, traceback.format_stack(), exc_info=True)\n']
Aug 29 22:47:59 celery[273]: Traceback (most recent call last):
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 204, in maybe_due
Aug 29 22:47:59 celery[273]: result = self.apply_async(entry, publisher=publisher)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 260, in apply_async
Aug 29 22:47:59 celery[273]: entry, exc=exc)), sys.exc_info()[2])
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 252, in apply_async
Aug 29 22:47:59 celery[273]: **entry.options)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/task.py", line 573, in apply_async
Aug 29 22:47:59 celery[273]: **dict(self._get_exec_options(), **options)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/base.py", line 345, in send_task
Aug 29 22:47:59 celery[273]: options = router.route(options, name, args, kwargs)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/routes.py", line 50, in route
Aug 29 22:47:59 celery[273]: route = self.lookup_route(task, args, kwargs)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/routes.py", line 78, in lookup_route
Aug 29 22:47:59 celery[273]: return _first_route(self.routes, task, args, kwargs)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/utils/functional.py", line 233, in _matcher
Aug 29 22:47:59 celery[273]: answer = getattr(maybe_evaluate(obj), method)(*args, **kwargs)
Aug 29 22:47:59 celery[273]: File "/usr/lib/python2.7/site-packages/awx/main/utils/ha.py", line 11, in route_for_task
Aug 29 22:47:59 celery[273]: (changed, instance) = Instance.objects.get_or_register()
Aug 29 22:47:59 celery[273]: File "/usr/lib/python2.7/site-packages/awx/main/managers.py", line 104, in get_or_register
Aug 29 22:47:59 celery[273]: return self.register()
Aug 29 22:47:59 celery[273]: File "/usr/lib/python2.7/site-packages/awx/main/managers.py", line 95, in register
Aug 29 22:47:59 celery[273]: with advisory_lock('instance_registration_%s' % hostname):
Aug 29 22:47:59 celery[273]: File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
Aug 29 22:47:59 celery[273]: return self.gen.next()
Aug 29 22:47:59 celery[273]: File "/usr/lib/python2.7/site-packages/awx/main/utils/pglock.py", line 13, in advisory_lock
Aug 29 22:47:59 celery[273]: with django_pglocks_advisory_lock(*args, **kwargs) as internal_lock:
Aug 29 22:47:59 celery[273]: File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
Aug 29 22:47:59 celery[273]: return self.gen.next()
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django_pglocks/__init__.py", line 64, in advisory_lock
Aug 29 22:47:59 celery[273]: cursor = connections[using].cursor()
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
Aug 29 22:47:59 celery[273]: return self._cursor()
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
Aug 29 22:47:59 celery[273]: return self._prepare_cursor(self.create_cursor(name))
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
Aug 29 22:47:59 celery[273]: six.reraise(dj_exc_type, dj_exc_value, traceback)
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor
Aug 29 22:47:59 celery[273]: return self._prepare_cursor(self.create_cursor(name))
Aug 29 22:47:59 celery[273]: File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor
Aug 29 22:47:59 celery[273]: cursor = self.connection.cursor()
Aug 29 22:47:59 celery[273]: SchedulingError: Couldn't apply scheduled task tower_scheduler: connection already closed
Aug 29 22:47:59 celery[273]: [2018-08-29 19:47:59,763: DEBUG/Beat] beat: Waking up in 19.99 seconds.
```

**Comment by ryanpetrello** [comment]
@YuriGrigorov this should be resolved in the latest version of awx (1.0.8).  If you're still encountering problems after upgrading, please let us know and we'll reopen this issue.
