### ISSUE TITLE
Anisble Tower Job fails when size of the extra-vars is more

### ISSUE THREAD

**Issue by Wolfsharad** [ansible/awx#2233]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

I am having a Job in Ansible Tower. All inputs for the job is passed in the extra-vars (in JSON format)

When the size of extra-vars is small the Job runs fine. But when it is big, say 800KB or 160000 lines of extra-vars, the Job is failing with error.

##### ENVIRONMENT
* AWX version: 2.4.5
* Ansible version:  1.9.1
* Operating System: RHEL 6

##### STEPS TO REPRODUCE

1. Create any sample play-book
2. Pass Huge sized extra_vars to it
##### EXPECTED RESULTS
Play should start executing as a Normal job

##### ACTUAL RESULTS
Play did not start rather throwing the below Error. Following is the std_out of the job.

[2018-08-30 07:13:27,641: DEBUG/Worker-6835] Database error updating Job, retrying in 5 seconds (retry #1): could not receive data from server: Bad file descriptor

[2018-08-30 07:13:32,649: DEBUG/Worker-6835] Database error updating Job, retrying in 5 seconds (retry #2): could not receive data from server: Bad file descriptor

[2018-08-30 07:13:37,653: DEBUG/Worker-6835] Database error updating Job, retrying in 5 seconds (retry #3): could not receive data from server: Bad file descriptor

[2018-08-30 07:13:42,660: DEBUG/Worker-6835] Database error updating Job, retrying in 5 seconds (retry #4): could not receive data from server: Bad file descriptor

[2018-08-30 07:13:47,667: DEBUG/Worker-6835] Database error updating Job, retrying in 5 seconds (retry #5): could not receive data from server: Bad file descriptor

[2018-08-30 07:13:52,674: DEBUG/Worker-6835] Database error updating Job, retrying in 5 seconds (retry #6): could not receive data from server: Bad file descriptor

[2018-08-30 07:13:52,682: WARNING/Worker-6835] Traceback (most recent call last):
[2018-08-30 07:13:52,683: WARNING/Worker-6835] File "/usr/lib64/python2.6/logging/handlers.py", line 76, in emit
[2018-08-30 07:13:52,687: WARNING/Worker-6835] if self.shouldRollover(record):
[2018-08-30 07:13:52,687: WARNING/Worker-6835] File "/usr/lib64/python2.6/logging/handlers.py", line 150, in shouldRollover
[2018-08-30 07:13:52,687: WARNING/Worker-6835] self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
[2018-08-30 07:13:52,687: WARNING/Worker-6835] IOError: [Errno 9] Bad file descriptor
[2018-08-30 07:13:52,674: ERROR/Worker-6835] Failed to update Job after 5 retries.
[2018-08-30 07:13:52,724: WARNING/Worker-6835] /usr/lib/python2.6/site-packages/awx/lib/site-packages/celery/app/trace.py:348: RuntimeWarning: Exception raised outside body: OperationalError('could not receive data from server: Bad file descriptor\n',):
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/celery/app/trace.py", line 253, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/celery/app/trace.py", line 201, in on_error
    R = I.handle_error_state(task, eager=eager)
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/celery/app/trace.py", line 85, in handle_error_state
    }[self.state](task, store_errors=store_errors)
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/celery/app/trace.py", line 118, in handle_failure
    req.id, exc, einfo.traceback, request=req,
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/celery/backends/base.py", line 120, in mark_as_failure
    traceback=traceback, request=request)
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/celery/backends/base.py", line 251, in store_result
    request=request, **kwargs)
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/djcelery/backends/database.py", line 29, in _store_result
    traceback=traceback, children=self.current_task_children(request),
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/djcelery/managers.py", line 42, in _inner
    return fun(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/djcelery/managers.py", line 181, in store_result
    'meta': {'children': children}})
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/djcelery/managers.py", line 87, in update_or_create
    return get_queryset(self).update_or_create(**kwargs)
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/djcelery/managers.py", line 70, in update_or_create
    obj, created = self.get_or_create(**kwargs)
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/django/db/models/query.py", line 376, in get_or_create
    return self.get(**lookup), False
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
OperationalError: could not receive data from server: Bad file descriptor

  exc, exc_info.traceback)))
[2018-08-30 07:13:52,743: ERROR/Worker-6835] Pool process <Worker(Worker-6835, started daemon)> error: OSError(9, 'Bad file descriptor')
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/billiard/pool.py", line 288, in run
    sys.exit(self.workloop(pid=pid))
  File "/usr/lib/python2.6/site-packages/awx/lib/site-packages/billiard/pool.py", line 372, in workloop
    put((READY, (job, i, (False, einfo), inqW_fd)))
OSError: [Errno 9] Bad file descriptor

##### ADDITIONAL INFORMATION

No other information in any of the logs apart from the above Error message

**Comment by wenottingham** [comment]
This repo is for issues with AWX. You have filed a traceback/issue for Ansible Tower.

If you are having issues with Ansible Tower, please contact your Red Hat support rep. I would note that the version you are referencing has been out of support for over a year.
