### ISSUE TITLE
500 Error during SAML Login - /api/v2/users/2/admin_of_organizations/ FAILED

### ISSUE THREAD

**Issue by cpatry-poly** [ansible/awx#2237]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
First time of each day we log to AWX using SAML, the login FAILED with this message : `ERROR! Call to /api/v2/users/2/admin_of_organizations/ failed. GET returned status: 500. A server error has occurred.`

![capture d ecran de 2018-09-11 09-40-13](https://user-images.githubusercontent.com/1652493/45346265-0b63f200-b5a9-11e8-9102-0159a31c859e.png)

##### ENVIRONMENT
* AWX version: 1.0.7.2
* AWX install method: docker on linux
* Ansible version:  2.6
* Operating System: Debian
* Web Browser: Firefox 61

##### STEPS TO REPRODUCE

Configure SAML and use the **S** button on the login screen

##### EXPECTED RESULTS

Logged. Home page.

##### ACTUAL RESULTS

Login Failed. Login page.

##### ADDITIONAL INFORMATION

After the error message. We use the **S** button again, and this time, everytime, it works perfectly, and we are redirected to the home page, correctly logged in.
May be it's a misconfiguration on our side, but as it worked everytime the second try, we don't really think so.

Here are the Web docker logs during login:

```
Sep 11 07:38:22 server01 docker[3329]: 172.16.98.14 - - [11/Sep/2018:07:38:22 +0000] "GET /sso/login/saml/?idp=idp HTTP/1.1" 302 0 "https://ans01.com/" "Firefox/61.0" "10.5.18.15"
Sep 11 07:38:25 server01 docker[3329]: [pid: 5396|app: 0|req: 23/446749] 172.16.98.14 () {54 vars in 1773 bytes} [Tue Sep 11 07:38:25 2018] POST /sso/complete/saml/ => generated 0 bytes in 184 msecs (HTTP/1.1 302) 11 headers in 537 bytes (1 switches on core 0)
Sep 11 07:38:25 server01 docker[3329]: 172.16.98.14 - - [11/Sep/2018:07:38:25 +0000] "POST /sso/complete/saml/ HTTP/1.1" 302 0 "https://saml01/adfs/ls/IdpInitiatedSignOn.aspx?loginToRp=awx&SAMLRequest=
Sep 11 07:38:25 server01 docker[3329]: 2018-09-11 07:38:25,721 INFO     awx.sso.views User cpatry logged in
Sep 11 07:38:25 server01 docker[3329]: 172.16.98.14 - - [11/Sep/2018:07:38:25 +0000] "GET /sso/complete/ HTTP/1.1" 301 0 "https://saml01/adfs/ls/IdpInitiatedSignOn.aspx?loginToRp=awx&SAMLRequest=
Sep 11 07:38:25 server01 docker[3329]: [pid: 5378|app: 0|req: 642/446750] 172.16.98.14 () {50 vars in 1644 bytes} [Tue Sep 11 07:38:25 2018] GET /sso/complete/ => generated 0 bytes in 77 msecs (HTTP/1.1 301) 10 headers in 1897 bytes (1 switches on core 0)
Sep 11 07:38:25 server01 docker[3329]: [pid: 5387|app: 0|req: 288/446751] 172.16.98.14 () {50 vars in 3137 bytes} [Tue Sep 11 07:38:25 2018] GET / => generated 11339 bytes in 184 msecs (HTTP/1.1 200) 7 headers in 312 bytes (1 switches on core 0)
Sep 11 07:38:25 server01 docker[3329]: 172.16.98.14 - - [11/Sep/2018:07:38:25 +0000] "GET / HTTP/1.1" 200 11339 "https://saml01/adfs/ls/IdpInitiatedSignOn.aspx?loginToRp=awx&SAMLRequest=
Sep 11 07:38:26 server01 docker[3329]: [pid: 5306|app: 0|req: 941/446752] 172.16.98.14 () {50 vars in 2423 bytes} [Tue Sep 11 07:38:26 2018] GET /api/ => generated 198727 bytes in 56 msecs (HTTP/1.1 200) 11 headers in 474 bytes (1 switches on core 0)
Sep 11 07:38:26 server01 docker[3329]: 172.16.98.14 - - [11/Sep/2018:07:38:26 +0000] "GET /api/ HTTP/1.1" 200 198727 "https://ans01.com/" "Firefox/61.0" "10.5.18.15"
Sep 11 07:38:26 server01 docker[3329]: 2018-09-11 07:38:26,905 INFO     awx.api.generics User cpatry logged out.
Sep 11 07:38:26 server01 docker[3329]: [pid: 5387|app: 0|req: 289/446753] 172.16.98.14 () {50 vars in 2437 bytes} [Tue Sep 11 07:38:26 2018] GET /api/logout/ => generated 0 bytes in 45 msecs (HTTP/1.1 302) 10 headers in 396 bytes (1 switches on core 0)
Sep 11 07:38:26 server01 docker[3329]: 172.16.98.14 - - [11/Sep/2018:07:38:26 +0000] "GET /api/logout/ HTTP/1.1" 302 0 "https://ans01.com/" "Firefox/61.0" "10.5.18.15"
Sep 11 07:38:26 server01 docker[3329]: 2018-09-11 07:38:26,922 ERROR    django.request Internal Server Error: /api/
Sep 11 07:38:26 server01 docker[3329]: Traceback (most recent call last):
Sep 11 07:38:26 server01 docker[3329]:   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 131, in get_response
Sep 11 07:38:26 server01 docker[3329]:     response = middleware_method(request, response)
Sep 11 07:38:26 server01 docker[3329]:   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/contrib/sessions/middleware.py", line 61, in process_response
Sep 11 07:38:26 server01 docker[3329]:     "The request's session was deleted before the "
Sep 11 07:38:26 server01 docker[3329]: SuspiciousOperation: The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example.
Sep 11 07:38:26 server01 docker[3329]: 172.16.98.14 - - [11/Sep/2018:07:38:26 +0000] "GET /static/partials/breadcrumb.html HTTP/1.1" 200 466 "https://ans01.com/" "Firefox/61.0" "10.5.18.15"
Sep 11 07:38:26 server01 docker[3329]: 2018-09-11 07:38:26,922 ERROR    django.request Internal Server Error: /api/
Sep 11 07:38:26 server01 docker[3329]: Traceback (most recent call last):
Sep 11 07:38:26 server01 docker[3329]:   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 131, in get_response
Sep 11 07:38:26 server01 docker[3329]:     response = middleware_method(request, response)
Sep 11 07:38:26 server01 docker[3329]:   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/contrib/sessions/middleware.py", line 61, in process_response
Sep 11 07:38:26 server01 docker[3329]:     "The request's session was deleted before the "
Sep 11 07:38:26 server01 docker[3329]: SuspiciousOperation: The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example.
Sep 11 07:38:26 server01 docker[3329]: [pid: 5333|app: 0|req: 859/446754] 172.16.98.14 () {52 vars in 2445 bytes} [Tue Sep 11 07:38:26 2018] GET /api/ => generated 41 bytes in 74 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
Sep 11 07:38:26 server01 docker[3329]: 172.16.98.14 - - [11/Sep/2018:07:38:26 +0000] "GET /api/ HTTP/1.1" 500 52 "https://ans01.com/" "Firefox/61.0" "10.5.18.15"
Sep 11 07:38:26 server01 docker[3329]: 2018-09-11 07:38:26,994 ERROR    django.request Internal Server Error: /api/v2/users/2/admin_of_organizations/
Sep 11 07:38:26 server01 docker[3329]: Traceback (most recent call last):
Sep 11 07:38:26 server01 docker[3329]:   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 131, in get_response
Sep 11 07:38:26 server01 docker[3329]:     response = middleware_method(request, response)
Sep 11 07:38:26 server01 docker[3329]:   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/contrib/sessions/middleware.py", line 61, in process_response
Sep 11 07:38:26 server01 docker[3329]:     "The request's session was deleted before the "
Sep 11 07:38:26 server01 docker[3329]: SuspiciousOperation: The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example.
Sep 11 07:38:26 server01 docker[3329]: 2018-09-11 07:38:26,994 ERROR    django.request Internal Server Error: /api/v2/users/2/admin_of_organizations/
Sep 11 07:38:26 server01 docker[3329]: Traceback (most recent call last):
Sep 11 07:38:26 server01 docker[3329]:   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 131, in get_response
Sep 11 07:38:26 server01 docker[3329]:     response = middleware_method(request, response)
Sep 11 07:38:26 server01 docker[3329]:   File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/contrib/sessions/middleware.py", line 61, in process_response
Sep 11 07:38:26 server01 docker[3329]:     "The request's session was deleted before the "
Sep 11 07:38:26 server01 docker[3329]: SuspiciousOperation: The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example.
Sep 11 07:38:26 server01 docker[3329]: [pid: 5396|app: 0|req: 24/446755] 172.16.98.14 () {50 vars in 2491 bytes} [Tue Sep 11 07:38:26 2018] GET /api/v2/users/2/admin_of_organizations/ => generated 41 bytes in 133 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
Sep 11 07:38:27 server01 docker[3329]: 172.16.98.14 - - [11/Sep/2018:07:38:27 +0000] "GET /api/v2/users/2/admin_of_organizations/ HTTP/1.1" 500 52 "https://ans01.com/" "Firefox/61.0" "10.5.18.15"
Sep 11 07:38:27 server01 docker[3329]: [pid: 5306|app: 0|req: 942/446756] 172.16.98.14 () {50 vars in 2380 bytes} [Tue Sep 11 07:38:26 2018] GET /api/ => generated 198727 bytes in 39 msecs (HTTP/1.1 200) 9 headers in 323 bytes (1 switches on core 0)
Sep 11 07:38:27 server01 docker[3329]: 172.16.98.14 - - [11/Sep/2018:07:38:27 +0000] "GET /api/ HTTP/1.1" 200 198727 "https://ans01.com/" "Firefox/61.0" "10.5.18.15"
Sep 11 07:38:27 server01 docker[3329]: 172.16.98.14 - - [11/Sep/2018:07:38:27 +0000] "GET /api/v2/auth/ HTTP/1.1" 200 161 "https://ans01.com/" "Firefox/61.0" "10.5.18.15"
Sep 11 07:38:27 server01 docker[3329]: [pid: 5378|app: 0|req: 643/446757] 172.16.98.14 () {50 vars in 2396 bytes} [Tue Sep 11 07:38:27 2018] GET /api/v2/auth/ => generated 161 bytes in 30 msecs (HTTP/1.1 200) 8 headers in 223 bytes (1 switches on core 0)
```

Thanks for your help.

**Comment by one-t** [comment]
Tested with Okta- this is working now BUT there is a new issue...

**Comment by cpatry-poly** [comment]
A new issue ?
