### ISSUE TITLE
AWX unable to connect to external RHEL Postgress9.2

### ISSUE THREAD

**Issue by forprem** [ansible/awx#2376]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY
AWX not able to connect to new external RHEL Postgres 9.2

##### ENVIRONMENT
* AWX version: 2.0.0
* AWX install method: Docker on linux,
* Ansible version:  2.6.5
* Operating System: RHEL7.5
* Web Browser:

##### STEPS TO REPRODUCE

executing ansible-playbook -i inventory install.yml

CREATE USER awx WITH PASSWORD 'awxpass';
CREATE DATABASE awx OWNER awx;
+pg_hostname=192.168.0.123

##### EXPECTED RESULTS

AWX UI up and running 

##### ACTUAL RESULTS

AWX UI says its upgrading

##### ADDITIONAL INFORMATION

Getting error on AWX_Web container:
2018-10-05 20:40:58,202 WARNING  awx.conf.settings Database settings are not available, using defaults, error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 80, in <module>
    application = get_wsgi_application()
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 77, in get_wsgi_application
    return AWXWSGIHandler()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 151, in __init__
    self.load_middleware()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 56, in load_middleware
    mw_class = import_string(middleware_path)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/awx/sso/middleware.py", line 18, in <module>
    from social_django import utils
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/utils.py", line 13, in <module>
    BACKENDS = settings.AUTHENTICATION_BACKENDS
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 531, in __getattr_without_cache__
   return getattr(self._wrapped, name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 444, in __getattr__
    value = self._get_local(name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 361, in _get_local
    self._preload_cache()
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 323, in _preload_cache
    for setting in Setting.objects.filter(key__in=settings_to_cache.keys(), user__isnull=True).order_by('pk'):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
ProgrammingError: relation "conf_setting" does not exist
LINE 1: ...f_setting"."value", "conf_setting"."user_id" FROM "conf_sett...
                                                             ^
WSGI app 0 (mountpoint='') ready in 10 seconds on interpreter 0x2147880 pid: 138 (default app)
2018-10-05 20:40:58,559 WARNING  awx.conf.settings Database settings are not available, using defaults, error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 80, in <module>
    application = get_wsgi_application()
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 77, in get_wsgi_application
    return AWXWSGIHandler()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 151, in __init__
    self.load_middleware()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 56, in load_middleware
    mw_class = import_string(middleware_path)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/awx/sso/middleware.py", line 18, in <module>
    from social_django import utils
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/utils.py", line 13, in <module>
    BACKENDS = settings.AUTHENTICATION_BACKENDS
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 531, in __getattr_without_cache__
    return getattr(self._wrapped, name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 444, in __getattr__
    value = self._get_local(name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 361, in _get_local
    self._preload_cache()
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 323, in _preload_cache
    for setting in Setting.objects.filter(key__in=settings_to_cache.keys(), user__isnull=True).order_by('pk'):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
ProgrammingError: relation "conf_setting" does not exist
LINE 1: ...f_setting"."value", "conf_setting"."user_id" FROM "conf_sett...
                                                             ^
WSGI app 0 (mountpoint='') ready in 10 seconds on interpreter 0x2147880 pid: 134 (default app)
2018-10-05 20:40:58,675 WARNING  awx.conf.settings Database settings are not available, using defaults, error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 80, in <module>
    application = get_wsgi_application()
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 77, in get_wsgi_application
    return AWXWSGIHandler()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 151, in __init__
    self.load_middleware()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 56, in load_middleware
    mw_class = import_string(middleware_path)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/awx/sso/middleware.py", line 18, in <module>
    from social_django import utils
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/utils.py", line 13, in <module>
    BACKENDS = settings.AUTHENTICATION_BACKENDS
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 531, in __getattr_without_cache__
    return getattr(self._wrapped, name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 444, in __getattr__
    value = self._get_local(name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 361, in _get_local
    self._preload_cache()
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 323, in _preload_cache
    for setting in Setting.objects.filter(key__in=settings_to_cache.keys(), user__isnull=True).order_by('pk'):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
ProgrammingError: relation "conf_setting" does not exist
LINE 1: ...f_setting"."value", "conf_setting"."user_id" FROM "conf_sett...
                                                             ^
2018-10-05 20:40:58,682 WARNING  awx.conf.settings Database settings are not available, using defaults, error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 80, in <module>
    application = get_wsgi_application()
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 77, in get_wsgi_application
    return AWXWSGIHandler()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 151, in __init__
    self.load_middleware()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 56, in load_middleware
    mw_class = import_string(middleware_path)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/awx/sso/middleware.py", line 18, in <module>
    from social_django import utils
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/utils.py", line 13, in <module>
    BACKENDS = settings.AUTHENTICATION_BACKENDS
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 531, in __getattr_without_cache__
    return getattr(self._wrapped, name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 444, in __getattr__
    value = self._get_local(name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 361, in _get_local
    self._preload_cache()
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 323, in _preload_cache
    for setting in Setting.objects.filter(key__in=settings_to_cache.keys(), user__isnull=True).order_by('pk'):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
ProgrammingError: relation "conf_setting" does not exist
LINE 1: ...f_setting"."value", "conf_setting"."user_id" FROM "conf_sett...
                                                             ^
WSGI app 0 (mountpoint='') ready in 10 seconds on interpreter 0x2147880 pid: 136 (default app)
WSGI app 0 (mountpoint='') ready in 10 seconds on interpreter 0x2147880 pid: 135 (default app)
2018-10-05 20:40:58,782 WARNING  awx.conf.settings Database settings are not available, using defaults, error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 80, in <module>
    application = get_wsgi_application()
  File "/usr/lib/python2.7/site-packages/awx/wsgi.py", line 77, in get_wsgi_application
    return AWXWSGIHandler()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 151, in __init__
    self.load_middleware()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 56, in load_middleware
    mw_class = import_string(middleware_path)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/awx/sso/middleware.py", line 18, in <module>
    from social_django import utils
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/utils.py", line 13, in <module>
    BACKENDS = settings.AUTHENTICATION_BACKENDS
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 531, in __getattr_without_cache__
    return getattr(self._wrapped, name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 444, in __getattr__
    value = self._get_local(name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 361, in _get_local
    self._preload_cache()
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 323, in _preload_cache
    for setting in Setting.objects.filter(key__in=settings_to_cache.keys(), user__isnull=True).order_by('pk'):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)

**Comment by wenottingham** [comment]
Postrgres 9.2 is not supported, see the minimum requirements in INSTALL.md.
