### ISSUE TITLE
Fail to build sdist builder image with ansible/docker (Stale file handle)

### ISSUE THREAD

**Issue by Glandos** [ansible/awx#240]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

I tried to install AWX using the installer with Docker, and it fails

##### STEPS TO REPRODUCE

Simply run the installer with ansible-playbook -vvvv -i inventory install.yml

##### EXPECTED RESULTS

The task "Build sdist builder images" should succeed

##### ACTUAL RESULTS

This is the output:

```
TASK [image_build : Build sdist builder image] ****************************************************************************************************************************************************************
task path: [...]/awx/installer/image_build/tasks/main.yml:50
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/docker/docker_image.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: glandos
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/glandos/.ansible/tmp/ansible-tmp-1506006537.5-111460901009556 `" && echo ansible-tmp-1506006537.5-111460901009556="` echo /home/glandos/.ansible/tmp/ansible-tmp-1506006537.5-111460901009556 `" ) && sleep 0'
<localhost> PUT /tmp/tmpW0Nuao TO /home/glandos/.ansible/tmp/ansible-tmp-1506006537.5-111460901009556/docker_image.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/glandos/.ansible/tmp/ansible-tmp-1506006537.5-111460901009556/ /home/glandos/.ansible/tmp/ansible-tmp-1506006537.5-111460901009556/docker_image.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/env python /home/glandos/.ansible/tmp/ansible-tmp-1506006537.5-111460901009556/docker_image.py; rm -rf "/home/glandos/.ansible/tmp/ansible-tmp-1506006537.5-111460901009556/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "api_version": null, 
            "archive_path": null, 
            "buildargs": {
                "http_proxy": "http://[...]:8123", 
                "https_proxy": "http://[...]:8123", 
                "no_proxy": ""
            }, 
            "cacert_path": null, 
            "cert_path": null, 
            "container_limits": null, 
            "debug": false, 
            "docker_host": null, 
            "dockerfile": "Dockerfile.sdist", 
            "filter_logger": false, 
            "force": true, 
            "http_timeout": null, 
            "key_path": null, 
            "load_path": null, 
            "name": "awx_sdist_builder", 
            "nocache": "False", 
            "path": "image_build/files", 
            "pull": true, 
            "push": false, 
            "repository": null, 
            "rm": true, 
            "ssl_version": null, 
            "state": "present", 
            "tag": "1.0.0.519", 
            "timeout": null, 
            "tls": null, 
            "tls_hostname": null, 
            "tls_verify": null, 
            "use_tls": "no"
        }
    }, 
    "msg": "Error building awx_sdist_builder - code: 1, message: The command '/bin/sh -c yum install -y epel-release' returned a non-zero code: 1, logs: [u'Step 1/11 : FROM centos:7\\n', u' ---> 196e0ce0c9fb\\n', u'Step 2/11 : RUN cd /tmp\\n', u' ---> Using cache\\n', u' ---> c1e05ff859df\\n', u'Step 3/11 : RUN yum makecache\\n', u' ---> Using cache\\n', u' ---> e4e105413ec6\\n', u'Step 4/11 : RUN yum install -y epel-release\\n', u' ---> Running in 4dde23341777\\n', u'Loaded plugins: fastestmirror, ovl\\n', u'Loading mirror speeds from cached hostfile\\n', u' * base: centos.alpha-labs.net\\n', u' * extras: centos.alpha-labs.net\\n', u' * updates: centos.bio.lmu.de\\n', u'Resolving Dependencies\\n', u'--> Running transaction check\\n', u'---> Package epel-release.noarch 0:7-9 will be installed\\n', u'--> Finished Dependency Resolution\\n', u'\\nDependencies Resolved\\n', u'\\n================================================================================\\n Package                Arch             Version         Repository        Size\\n================================================================================\\nInstalling:\\n epel-release           noarch           7-9             extras            14 k\\n\\nTransaction Summary\\n================================================================================\\nInstall  1 Package\\n\\n', u'Total download size: 14 k\\n', u'Installed size: 24 k\\n', u'Downloading packages:\\n', u'\\x1b[91mwarning: /var/cache/yum/x86_64/7/extras/packages/epel-release-7-9.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY\\n\\x1b[0m', u'Public key for epel-release-7-9.noarch.rpm is not installed\\n', u'Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7\\n', u'\\x1b[91mImporting GPG key 0xF4A80EB5:\\n Userid     : \"CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>\"\\n Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5\\n Package    : centos-release-7-4.1708.el7.centos.x86_64 (@CentOS)\\n From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7\\n\\x1b[0m', u'Running transaction check\\n', u'Running transaction test\\n', u'Transaction test succeeded\\n', u'Running transaction\\n', u'  Installing : epel-release-7-9.noarch                                      1/1', u' \\n  Verifying  : epel-release-7-9.noarch                                      1/1', u' \\n', u'\\x1b[91mTraceback (most recent call last):\\n  File \"/usr/bin/yum\", line 29, in <module>\\n    yummain.user_main(sys.argv[1:], exit_code=True)\\n  File \"/usr/share/yum-cli/yummain.py\", line 370, in user_main\\n\\x1b[0m', u'\\x1b[91m    errcode = main(args)\\n  File \"/usr/share/yum-cli/yummain.py\", line 276, in main\\n    return_code = base.doTransaction()\\n  File \"/usr/share/yum-cli/cli.py\", line 783, in doTransaction\\n\\x1b[0m', u'\\x1b[91m    resultobject = self.runTransaction(cb=cb)\\n  File \"/usr/lib/python2.7/site-packages/yum/__init__.py\", line 1943, in runTransaction\\n\\x1b[0m', u'\\x1b[91m    self.verifyTransaction(resultobject, vTcb)\\n  File \"/usr/lib/python2.7/site-packages/yum/__init__.py\", line 2006, in verifyTransaction\\n\\x1b[0m', u'\\x1b[91m    po.yumdb_info.releasever = self.conf.yumvar[\\'releasever\\']\\n  File \"/usr/lib/python2.7/site-packages/yum/rpmsack.py\", line 1930, in __setattr__\\n\\x1b[0m', u'\\x1b[91m    self._write(attr, value)\\n  File \"/usr/lib/python2.7/site-packages/yum/rpmsack.py\", line 1854, in _write\\n\\x1b[0m', u'\\x1b[91m    misc.unlink_f(fn + \\'.tmp\\')\\n  File \"/usr/lib/python2.7/site-packages/yum/misc.py\", line 955, in unlink_f\\n\\x1b[0m', u'\\x1b[91m    os.unlink(filename)\\nOSError\\x1b[0m', u'\\x1b[91m: \\x1b[0m', u\"\\x1b[91m[Errno 116] Stale file handle: '/var/lib/yum/yumdb/e/d776b9de6b5e994c55d09b7f2224ebefbb4c972a-epel-release-7-9-noarch/releasever.tmp'\\n\\x1b[0m\", u'Removing intermediate container 4dde23341777\\n']"
}
```

**Comment by matburt** [comment]
I've not seen that error after building quite a bit. Is this being done on an NFS filesystem mount?

**Comment by Glandos** [comment]
Well, I don't think so. Even if my computer (with openSuse Tumbleweed) has some NFS mounts for sharing work with team mates, I used standard local path for everything else.

I have to admit that I am also puzzled by that. Of course I ran this multiple times. I even deleted the centos image from docker before a new try, just in case…

**Comment by matburt** [comment]
What version of docker are you using? Where is it sourced from?

**Comment by Glandos** [comment]
```
# env LANG=C zypper if docker
Loading repository data...
Reading installed packages...


Information for package docker:
-------------------------------
Repository     : repo-oss                   
Name           : docker                     
Version        : 17.04.0_ce-6.1             
Arch           : x86_64                     
Vendor         : openSUSE                   
Installed Size : 52.5 MiB                   
Installed      : Yes                        
Status         : up-to-date                 
Source package : docker-17.04.0_ce-6.1.src  
Summary        : The Linux container runtime
```

**Comment by Glandos** [comment]
I have manually tested it:
```
# docker run --name centos_test --rm -i -t centos:7 bash
```

Then, within the container itself:

```
# yum install epel-release

[…truncated…]

Running transaction
  Installing : epel-release-7-9.noarch                                                                                                                                                                     1/1 
  Verifying  : epel-release-7-9.noarch                                                                                                                                                                     1/1 
Traceback (most recent call last):
  File "/usr/bin/yum", line 29, in <module>
    yummain.user_main(sys.argv[1:], exit_code=True)
  File "/usr/share/yum-cli/yummain.py", line 370, in user_main
    errcode = main(args)
  File "/usr/share/yum-cli/yummain.py", line 276, in main
    return_code = base.doTransaction()
  File "/usr/share/yum-cli/cli.py", line 783, in doTransaction
    resultobject = self.runTransaction(cb=cb)
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 1943, in runTransaction
    self.verifyTransaction(resultobject, vTcb)
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 2006, in verifyTransaction
    po.yumdb_info.releasever = self.conf.yumvar['releasever']
  File "/usr/lib/python2.7/site-packages/yum/rpmsack.py", line 1930, in __setattr__
    self._write(attr, value)
  File "/usr/lib/python2.7/site-packages/yum/rpmsack.py", line 1854, in _write
    misc.unlink_f(fn + '.tmp')
  File "/usr/lib/python2.7/site-packages/yum/misc.py", line 955, in unlink_f
    os.unlink(filename)
OSError: [Errno 116] Stale file handle: '/var/lib/yum/yumdb/e/d776b9de6b5e994c55d09b7f2224ebefbb4c972a-epel-release-7-9-noarch/releasever.tmp'
[root@beaa3cbc4b37 /]# ll /var/lib/yum/yumdb/e/d776b9de6b5e994c55d09b7f2224ebefbb4c972a-epel-release-7-9-noarch/              
ls: cannot access /var/lib/yum/yumdb/e/d776b9de6b5e994c55d09b7f2224ebefbb4c972a-epel-release-7-9-noarch/releasever.tmp: Stale file handle
total 8
-rw-r--r-- 1 root root 6 Sep 22 08:52 from_repo
-rw-r--r-- 1 root root 4 Sep 22 08:52 reason
-????????? ? ?    ?    ?            ? releasever.tmp
```

If I try to run the command again, it goes further:

```
# yum install epel-release

[…truncated…]

Running transaction
Warning: RPMDB altered outside of yum.
  Updating   : epel-release-7-10.noarch                                                                                                                                                                    1/2 
  Cleanup    : epel-release-7-9.noarch                                                                                                                                                                     2/2 
  Verifying  : epel-release-7-10.noarch                                                                                                                                                                    1/2 
Traceback (most recent call last):
  File "/usr/bin/yum", line 29, in <module>
    yummain.user_main(sys.argv[1:], exit_code=True)
  File "/usr/share/yum-cli/yummain.py", line 370, in user_main
    errcode = main(args)
  File "/usr/share/yum-cli/yummain.py", line 276, in main
    return_code = base.doTransaction()
  File "/usr/share/yum-cli/cli.py", line 783, in doTransaction
    resultobject = self.runTransaction(cb=cb)
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 1943, in runTransaction
    self.verifyTransaction(resultobject, vTcb)
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 2031, in verifyTransaction
    po.yumdb_info.checksum_type = str(csum[0])
  File "/usr/lib/python2.7/site-packages/yum/rpmsack.py", line 1930, in __setattr__
    self._write(attr, value)
  File "/usr/lib/python2.7/site-packages/yum/rpmsack.py", line 1854, in _write
    misc.unlink_f(fn + '.tmp')
  File "/usr/lib/python2.7/site-packages/yum/misc.py", line 955, in unlink_f
    os.unlink(filename)
OSError: [Errno 116] Stale file handle: '/var/lib/yum/yumdb/e/16c1f0d7c32bee3a612690c5556796e76615dc8a-epel-release-7-10-noarch/checksum_type.tmp'
[root@beaa3cbc4b37 /]# ll /var/lib/yum/yumdb/e/16c1f0d7c32bee3a612690c5556796e76615dc8a-epel-release-7-10-noarch/ 
ls: cannot access /var/lib/yum/yumdb/e/16c1f0d7c32bee3a612690c5556796e76615dc8a-epel-release-7-10-noarch/checksum_type.tmp: Stale file handle
total 32
-????????? ? ?    ?     ?            ? checksum_type.tmp
-rw-r--r-- 1 root root 20 Sep 22 08:56 command_line
-rw-r--r-- 1 root root  4 Sep 22 08:56 from_repo
-rw-r--r-- 2 root root  4 Sep 22 08:52 reason
-rw-r--r-- 1 root root  1 Sep 22 08:56 releasever
-rw-r--r-- 1 root root 10 Sep 22 08:56 ts_install_langs
-rw-r--r-- 1 root root  4 Sep 22 08:56 tsflag_nodocs
-rw-r--r-- 1 root root  9 Sep 22 08:56 var_infra
-rw-r--r-- 1 root root 36 Sep 22 08:56 var_uuid
```

But then the package is successfully installed. However, for each installed package, the verify phase fail with the same error on `checksum_type.tmp`. It seems that Docker is failing somewhere.

**Comment by matburt** [comment]
So it seems like this may be something specific to your system. I'm not sure how to help you, maybe the Docker folks know something ? :frowning:

**Comment by Glandos** [comment]
I don't want to be rude, but even if it's the first time I'm using Docker, I've experienced exactly what its haters are saying: this is not reliable. It should be reproducible, and instead, it raises rare return code from simple `unlink` call.
I was just thinking that I could use Docker as a developer to test AWX installation before deploying it in another way. Now, I know that will try to avoid it as much as possible.

**Comment by matburt** [comment]
It is currently the only accepted installation method for AWX. I'm sorry you're having trouble. I'm not on the Docker team nor do I know the intricacies of the packaging and setup for your distro and platform. I suspect someone there may be able to help you if it's more systemic. I'd certainly prefer you to be able to use AWX if you wanted.
