### ISSUE TITLE
2.0.1 Install on linux from rpm. sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.

### ISSUE THREAD

**Issue by franysk** [ansible/awx#2480]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### ENVIRONMENT
* AWX version: 2.0.1
* AWX install method: no-containers
* Ansible version:   2.7.0
* Operating System: CentOS Linux release 7.5.1804
* Web Browser:

##### STEPS TO REPRODUCE

 sudo -u awx /opt/awx/bin/awx-manage migrate

##### EXPECTED RESULTS

running migarations successfully

##### ACTUAL RESULTS

Operations to perform:
  Apply all migrations: auth, conf, contenttypes, djcelery, main, oauth2_provider, sessions, sites, social_django, sso, taggit
Running migrations:
  Applying main.0006_v320_release...Traceback (most recent call last):
  File "/opt/awx/bin/awx-manage", line 11, in <module>
    sys.exit(manage())
  File "/usr/lib/python2.7/site-packages/awx-2.0.1-py2.7.egg/awx/__init__.py", line 116, in manage
    execute_from_command_line(sys.argv)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/migrations/operations/special.py", line 108, in database_forwards
    self._run_sql(schema_editor, self.sql)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/migrations/operations/special.py", line 129, in _run_sql
    schema_editor.execute(sql, params=params)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/backends/base/schema.py", line 120, in execute
    cursor.execute(sql, params)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/backends/utils.py", line 83, in execute
    sql = self.db.ops.last_executed_query(self.cursor, sql, params)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/backends/sqlite3/operations.py", line 135, in last_executed_query
    params = self._quote_params_for_last_executed_query(params)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/db/backends/sqlite3/operations.py", line 124, in _quote_params_for_last_executed_query
    return cursor.execute(sql, params).fetchone()
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.

**Comment by ryanpetrello** [comment]
@franysk whatever install method you're using doesn't sound like it's supported in awx.  Please take a look at the installation docs here:  https://github.com/ansible/awx/blob/devel/INSTALL.md
