### ISSUE TITLE
what is pkg_resources.DistributionNotFound error ??

### ISSUE THREAD

**Issue by hanjh1986** [ansible/awx#251]
I just want to only run awx's django application, so
downloaded awx-repo(through git clone~) and try to run manage.py in awx directory

$ cd awx
$ python manage.py runserver

but, I found this error

D:\dev\AWX_0920\awx>python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    from awx import manage
  File "D:\dev\AWX_0920\awx\awx\__init__.py", line 10, in <module>
    __version__ = get_distribution('awx').version
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 557, in get_distribution
    dist = get_provider(dist)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 431, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'awx' distribution was not found and is required by the application

Is there anything need to run manage.py??
what is different between only just running django's manage.py and installing AWX's prerequsites?

I want to know how to resolve pkg_resources.DistributionNotFound error

**Comment by wwitzel3** [comment]
The easiest way to get started running awx is with one of our containerized deployments. You can read more about running AWX at https://github.com/ansible/awx/blob/devel/INSTALL.md
