### ISSUE TITLE
Inventory sync fails due to missing python default modules

### ISSUE THREAD

**Issue by HelffCare** [ansible/awx#2612]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Ansible-inventory fails due to missing modules.

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method: docker on Linux
* Ansible version:  2.7.1
* Operating System: CentOS 
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Create new Inventory
2. Create Source
3. Select "Sourced from a Project as source"
4. Choose a inventory file (YAML file) out of your GIT repo
5. Sync

##### EXPECTED RESULTS

It should import the hosts listed in the inventory file.

##### ACTUAL RESULTS

The job fails due to missing ansible modules. See below error log for more details.
##### ADDITIONAL INFORMATION

Error log:
```
    1.543 INFO     Updating inventory 2: Loadbalancer
    1.562 INFO     Reading Ansible inventory source: /var/lib/awx/projects/_6__ccloud_git/ansible/inventory/eu-de-1
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==2.0.1', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 116, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 994, in handle
    self.is_custom)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 245, in load_inventory_source
    is_custom=is_custom).load()
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 180, in load
    data = self.command_to_json(base_args + ['--list'])
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 163, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
Traceback (most recent call last):
  File "/usr/bin/ansible-inventory", line 40, in <module>
    from ansible.errors import AnsibleError, AnsibleOptionsError, AnsibleParserError
ImportError: No module named errors
```

**Comment by wenottingham** [comment]
Do you have multiple versions of Ansible in your container somehow?

**Comment by HelffCare** [comment]
I am using the awx task container hosted on Docker:
https://hub.docker.com/r/ansible/awx_task/
I was running version 1.0 and didn't had any issues.
But somehow I am not able to get 2.1.0 running. Usually I make modifications to the Dockerfile to match my requirements but even with the plain awx_task and awx_web contaienr I am not able to get it running.
It uses just one Ansible version:
```
# ansible --version
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)
```

**Comment by HelffCare** [comment]
I found a workaround for the mentioned issue.
I created a custom VENV and added this to the "ANSIBLE_VENV_PATH" in the `/etc/tower/settings.py`.
With my custom VENV everything runs fine again, but AWX should be able to run the basic Ansible modules with the default ENV.  
It still bothers me, that obviously no one else experiences this issue. So you can also close this bug report if it works for everyone else.
