### ISSUE TITLE
New Activity Stream entries for inventory update creation missing links

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2733]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
[background]

A change happened recently (I still don't know the source of it) that caused activity stream entries to be produced for creation of inventory updates. (i.e. the action of updating an inventory)

[bug]

These entries are not hooked up to show and link the related inventory update.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: any
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Update an inventory

view activity stream

##### EXPECTED RESULTS

no unlinked entries

##### ACTUAL RESULTS

UI:

![screen shot 2018-11-18 at 11 43 11 am](https://user-images.githubusercontent.com/1385596/48675480-42b1ca80-eb27-11e8-90f7-0d453f3d69de.png)

needs link to inventory update

API:

```json
{
    "id": 15580,
    "type": "activity_stream",
    "url": "/api/v2/activity_stream/15580/",
    "related": {
        "actor": "/api/v2/users/1/"
    },
    "summary_fields": {
        "actor": {
            "username": "admin",
            "first_name": "",
            "last_name": "",
            "id": 1
        }
    },
    "timestamp": "2018-11-18T16:42:51.662086Z",
    "operation": "create",
    "changes": {
        "cancel_flag": false,
        "job_args": "",
        "emitted_events": 0,
        "source_regions": "",
        "job_explanation": "",
        "license_error": false,
        "source_project_update": null,
        "start_args": "hidden",
        "celery_task_id": "",
        "id": 1085,
        "overwrite": false,
        "controller_node": "",
        "source_vars": "",
        "modified_by": "admin",
        "job_cwd": "",
        "old_pk": null,
        "instance_filters": "",
        "created_by": "admin",
        "failed": false,
        "source_script": "Inventory Script - BellChampionshipẍ-39",
        "group_by": "",
        "inventory": "Inventory - TalkCommunication箣-812",
        "unifiedjob_ptr": "2018-11-18 16:42:51.643909+00:00-1085-new",
        "status": "new",
        "description": "",
        "overwrite_vars": false,
        "schedule": null,
        "started": null,
        "elapsed": "0.0",
        "finished": null,
        "job_env": "{}",
        "execution_node": "",
        "polymorphic_ctype": "inventory update",
        "inventory_source": "custom-group-P7bvTsFAey (Inventory - TalkCommunication箣 - 775)-775",
        "name": "Inventory - TalkCommunication箣 - custom-group-P7bvTsFAey (Inventory - TalkCommunication箣 - 775)",
        "created": "2018-11-18 16:42:51.643909+00:00",
        "result_traceback": "",
        "verbosity": 1,
        "instance_group": null,
        "source_path": "",
        "modified": "2018-11-18 16:42:51.653447+00:00",
        "unified_job_template": "custom-group-P7bvTsFAey (Inventory - TalkCommunication箣 - 775)-775",
        "source": "custom",
        "timeout": 0,
        "launch_type": "manual"
    },
    "object1": "inventory_update",
    "object2": "",
    "object_association": ""
}
```

no related inventory update

##### ADDITIONAL INFORMATION

A field for this exists in the models, so there's no schema change to make it work

**Comment by AlanCoding** [comment]
Discovered origin of the change:

```
awx_1        | 16:48:42 uwsgi.1      | 2018-11-18 16:48:42,118 ERROR    django.request Internal Server Error: /api/v2/inventory_sources/775/update/
awx_1        | 16:48:42 uwsgi.1      | Traceback (most recent call last):
awx_1        | 16:48:42 uwsgi.1      |   File "/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
awx_1        | 16:48:42 uwsgi.1      |     response = get_response(request)
awx_1        | 16:48:42 uwsgi.1      |   File "./awx/wsgi.py", line 71, in _legacy_get_response
awx_1        | 16:48:42 uwsgi.1      |     return super(AWXWSGIHandler, self)._legacy_get_response(request)
awx_1        | 16:48:42 uwsgi.1      |   File "/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
awx_1        | 16:48:42 uwsgi.1      |     response = self._get_response(request)
awx_1        | 16:48:42 uwsgi.1      |   File "/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
awx_1        | 16:48:42 uwsgi.1      |     response = self.process_exception_by_middleware(e, request)
awx_1        | 16:48:42 uwsgi.1      |   File "/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
awx_1        | 16:48:42 uwsgi.1      |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
awx_1        | 16:48:42 uwsgi.1      |   File "/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
awx_1        | 16:48:42 uwsgi.1      |     return func(*args, **kwargs)
awx_1        | 16:48:42 uwsgi.1      |   File "/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
awx_1        | 16:48:42 uwsgi.1      |     return view_func(*args, **kwargs)
awx_1        | 16:48:42 uwsgi.1      |   File "/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
awx_1        | 16:48:42 uwsgi.1      |     return self.dispatch(request, *args, **kwargs)
awx_1        | 16:48:42 uwsgi.1      |   File "./awx/api/generics.py", line 328, in dispatch
awx_1        | 16:48:42 uwsgi.1      |     return super(APIView, self).dispatch(request, *args, **kwargs)
awx_1        | 16:48:42 uwsgi.1      |   File "/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 494, in dispatch
awx_1        | 16:48:42 uwsgi.1      |     response = self.handle_exception(exc)
awx_1        | 16:48:42 uwsgi.1      |   File "/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 454, in handle_exception
awx_1        | 16:48:42 uwsgi.1      |     self.raise_uncaught_exception(exc)
awx_1        | 16:48:42 uwsgi.1      |   File "/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 491, in dispatch
awx_1        | 16:48:42 uwsgi.1      |     response = handler(request, *args, **kwargs)
awx_1        | 16:48:42 uwsgi.1      |   File "./awx/api/views/__init__.py", line 2127, in post
awx_1        | 16:48:42 uwsgi.1      |     update = obj.update()
awx_1        | 16:48:42 uwsgi.1      |   File "./awx/main/models/unified_jobs.py", line 306, in update
awx_1        | 16:48:42 uwsgi.1      |     unified_job = self.create_unified_job()
awx_1        | 16:48:42 uwsgi.1      |   File "./awx/main/models/inventory.py", line 1538, in create_unified_job
awx_1        | 16:48:42 uwsgi.1      |     return super(InventorySource, self).create_unified_job(**kwargs)
awx_1        | 16:48:42 uwsgi.1      |   File "./awx/main/models/unified_jobs.py", line 408, in create_unified_job
awx_1        | 16:48:42 uwsgi.1      |     activity_stream_create(None, unified_job, True)
awx_1        | 16:48:42 uwsgi.1      |   File "./awx/main/signals.py", line 438, in activity_stream_create
awx_1        | 16:48:42 uwsgi.1      |     raise Exception('alan!')
awx_1        | 16:48:42 uwsgi.1      | Exception: alan!
```

In unified jobs, `create_unified_job`, `activity_stream_create` is new.

**Comment by AlanCoding** [comment]
no longer needed
