### ISSUE TITLE
Activity Stream v1 version server error with token entries

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2879]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Versioning problem - tokens cause server errors in `/api/v1/activity_stream/` or similar

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Create a token

##### EXPECTED RESULTS

View activity stream for that action in v1

##### ACTUAL RESULTS

```
2018-12-06 02:02:22,963 ERROR    django.request Internal Server Error: /api/v1/activity_stream/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/lib/python2.7/site-packages/awx/wsgi.py", line 71, in _legacy_get_response
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/lib/python2.7/site-packages/awx/api/generics.py", line 327, in dispatch
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/mixins.py", line 45, in list
    return self.get_paginated_response(serializer.data)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/serializers.py", line 742, in data
    ret = super(ListSerializer, self).data
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/serializers.py", line 660, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/serializers.py", line 504, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/fields.py", line 1816, in to_representation
    return method(value)
  File "/lib/python2.7/site-packages/awx/api/serializers.py", line 338, in _get_related
  File "/lib/python2.7/site-packages/awx/api/serializers.py", line 4958, in get_related
  File "/lib/python2.7/site-packages/awx/api/serializers.py", line 621, in reverse
  File "/lib/python2.7/site-packages/awx/api/versioning.py", line 52, in reverse
  File "/lib/python2.7/site-packages/awx/api/versioning.py", line 23, in drf_reverse
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/reverse.py", line 63, in _reverse
    url = django_reverse(viewname, args=args, kwargs=kwargs, **extra)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'o_auth2_token_detail' with keyword arguments '{'pk': 1L, u'version': u'v1'}' not found. 1 pattern(s) tried: [u'api/(?P<version>(v2))/tokens/(?P<pk>[0-9]+)/$']
```

Token exists, but does not exist in v1

**Comment by AlanCoding** [comment]
Link fix https://github.com/ansible/awx/pull/2880

**Comment by AlanCoding** [comment]
@unlikelyzero @rooftopcellist I'm fairly sure we would have heard some noise about this by now if this issue had not been resolved with the linked fix. Closing.
