### ISSUE TITLE
Migrations_Notran never finished

### ISSUE THREAD

**Issue by nmartinez-nimeops** [ansible/awx#2967]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Migrations_Notran never finished...

##### ENVIRONMENT
dockerhub_version: "2.1.2"
rabbitmq_version: "3.7.4"
rabbitmq_image: "ansible/awx_rabbitmq:{{rabbitmq_version}}"
rabbitmq_default_vhost: "awx"
rabbitmq_erlang_cookie: "{{ rabbitmq_erlang_cookie }}"
rabbitmq_port: "5672"
rabbitmq_default_username: "awx"
rabbitmq_default_password: "{{ rabbitmq_password }}"
postgresql_version: "9.6"
postgresql_image: "postgres:{{postgresql_version}}"

##### ADDITIONAL INFORMATION

awx_task container logs:
```
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==2.1.2.0', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 150, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/run_dispatcher.py", line 100, in handle
    reaper.reap()
  File "/usr/lib/python2.7/site-packages/awx/main/dispatch/reaper.py", line 36, in reap
    me = instance or Instance.objects.me()
  File "/usr/lib/python2.7/site-packages/awx/main/managers.py", line 86, in me
    if node.exists():
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 673, in exists
    return self.query.has_results(using=self.db)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/query.py", line 517, in has_results
    return compiler.has_results()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 858, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
django.db.utils.ProgrammingError: relation "main_instance" does not exist
LINE 1: SELECT (1) AS "a" FROM "main_instance" WHERE "main_instance"...
                               ^
```

pgsql container logs:
```
ERROR:  relation "main_instance" does not exist at character 24
STATEMENT:  SELECT (1) AS "a" FROM "main_instance" WHERE "main_instance"."hostname" = 'awx' LIMIT 1
```

**Comment by nmartinez-nimeops** [comment]
Working perfect with dockerhub_version: "2.1.1"

**Comment by nmartinez-nimeops** [comment]
So it's ok in 2.1.2 or not?? Why closed?
