### ISSUE TITLE
Provide environment details on inventory updates (to indicate venv used)

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#3059]
##### ISSUE TYPE
With #3039 we have custom virtual environments working with inventory updates, but it is not eminently clear from the inventory update view what venv was used at the time.

We should add the venv detail to the inventory update view like it is available for jobs <insert example here>

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Provide same info provided on jobs regarding environment used to execute inventory update

##### ADDITIONAL INFORMATION
Would help when diagnosing problems that are ansible version dependent (using plugin or script for inventory update?) like:

```
    6.772 INFO     Updating inventory 132: Inventory - PlayFeed孧
    6.799 INFO     Reading Ansible inventory source: /tmp/awx_523_2casc_vc/gcp_compute.yml
Traceback (most recent call last):
  File "/usr/local/bin/awx-manage", line 9, in <module>
    load_entry_point('awx', 'console_scripts', 'awx-manage')()
  File "/awx_devel/awx/__init__.py", line 150, in manage
    execute_from_command_line(sys.argv)
  File "/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/awx_devel/awx/main/management/commands/inventory_import.py", line 1021, in handle
    raise exc
  File "/awx_devel/awx/main/management/commands/inventory_import.py", line 921, in handle
    data = AnsibleInventoryLoader(source=source, is_custom=self.is_custom).load()
  File "/awx_devel/awx/main/management/commands/inventory_import.py", line 170, in load
    return self.command_to_json(base_args + ['--list'])
  File "/awx_devel/awx/main/management/commands/inventory_import.py", line 153, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
 [WARNING]:  * Failed to parse /tmp/awx_523_2casc_vc/gcp_compute.yml with
gcp_compute plugin: [{u'domain': u'global', u'message': u"Invalid value for
field 'zone': 'all'. Unknown zone.", u'reason': u'invalid'}]
 [WARNING]: Unable to parse /tmp/awx_523_2casc_vc/gcp_compute.yml as an
inventory source
ERROR! No inventory was parsed, please check your configuration and options.
```

**Comment by kdelee** [comment]
@jladdjr will help with inventory_plugins move + customers debugging issues related to what venv to choose

Will circle back with example from jobs detail

**Comment by kdelee** [comment]
Woops, it is in the detail view but not the list view :scream: 

So
```
https://127.0.0.1:8043/api/v2/inventory_updates/523/
```
has `job_env` info but
```
https://127.0.0.1:8043/api/v2/inventory_updates/?id=523
```
DOES NOT
