### ISSUE TITLE
AWX Inventory sync from Openstack Broken since 3.0.0.0

### ISSUE THREAD

**Issue by oekotaco** [ansible/awx#3075]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Inventory sync does not work anymore

##### ENVIRONMENT
* AWX version: 3.0.0.0
* AWX install method: docker
* Ansible version:  2.7.6
* Operating System: Debian
* Web Browser: 

##### STEPS TO REPRODUCE

create a inventory with clouds.yaml for syncing inventory from openstack.

##### EXPECTED RESULTS

Inventory should be synced.

##### ACTUAL RESULTS

Sync failed with the following messages:
``
1
    1.558 INFO     Updating inventory 10: I-OS-TI
2
    1.572 INFO     Reading Ansible inventory source: /var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/plugins/inventory/openstack.py
3
    1.574 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
4
    1.574 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
5
    1.574 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python2.7/site-packages:
6
   74.794 INFO     Processing JSON output...
7
   74.799 INFO     Loaded 63 groups, 20 hosts
8
Traceback (most recent call last):
9
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 11, in <module>
10
    load_entry_point('awx==3.0.0.0', 'console_scripts', 'awx-manage')()
11
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 150, in manage
12
    execute_from_command_line(sys.argv)
13
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
14
    utility.execute()
15
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
16
    self.fetch_command(subcommand).run_from_argv(self.argv)
17
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
18
    self.execute(*args, **cmd_options)
19
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 330, in execute
20
    output = self.handle(*args, **options)
21
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1030, in handle
22
    raise exc
23
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 975, in handle
24
    self.load_into_database()
25
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 824, in load_into_database
26
    self._delete_hosts()
27
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 413, in _delete_hosts
28
    instance_ids = all_instance_ids[offset:(offset + self._batch_size)]
29
TypeError: 'dict_keys' object is not subscriptable

**Comment by ryanpetrello** [comment]
Hey @oekotaco,

This should be resolved in `devel` via https://github.com/ansible/awx/pull/3058

**Comment by oekotaco** [comment]
Hey @ryanpetrello 

Thanks a lot this solved the issue for me.
