### ISSUE TITLE
Show appropriate error message when non-existent value passed to the SAML attribute

### ISSUE THREAD

**Issue by hiyokotaisa** [ansible/awx#3102]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

AWX should shows appropriate error message when using the SAML authentication.
If non-existent value passed to the SAML attribute like `attr_email`, `list index out of range` error shows on login page when the user login to the tower.

That error message is difficult to understand what is the cause of the issue, so it would be great if the AWX will shows `email address not found` or any appropriate error message.

**Comment by mabashian** [comment]
This _seems_ like it's a python error getting exposed in the UI.  Typically the UI displays whatever error message the api passes back in the response.

**Comment by ryanpetrello** [comment]
@hiyokotaisa could you give some reproduction steps for the error you're seeing?  Thanks.

**Comment by amard33p** [comment]
Got the same issue while creating a project using awx cli:

```
[root@ub18-dev-01:~] awx --conf.host http://127.0.0.1 projects create --wait --organization 1 --name='TestProject' --local_path 'testproj' -v
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:80
DEBUG:urllib3.connectionpool:http://127.0.0.1:80 "GET /api/ HTTP/1.1" 200 186
DEBUG:awxkit.api.client:"GET http://127.0.0.1/api/" elapsed: 0:00:00.062280
DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.api.ApiV2'> by url: /api/v2/
DEBUG:urllib3.connectionpool:http://127.0.0.1:80 "GET /api/v2/ HTTP/1.1" 200 1688
DEBUG:awxkit.api.client:"GET http://127.0.0.1/api/v2/" elapsed: 0:00:00.078925
DEBUG:urllib3.connectionpool:http://127.0.0.1:80 "GET /api/ HTTP/1.1" 200 186
DEBUG:awxkit.api.client:"GET http://127.0.0.1/api/" elapsed: 0:00:00.062371
DEBUG:urllib3.connectionpool:http://127.0.0.1:80 "POST /api/login/ HTTP/1.1" 302 0
DEBUG:awxkit.api.client:"POST http://127.0.0.1/api/login/" elapsed: 0:00:00.364928
DEBUG:urllib3.connectionpool:http://127.0.0.1:80 "GET /api/ HTTP/1.1" 200 186
DEBUG:awxkit.api.client:"GET http://127.0.0.1/api/" elapsed: 0:00:00.081151
DEBUG:urllib3.connectionpool:http://127.0.0.1:80 "GET /api/ HTTP/1.1" 200 186
DEBUG:awxkit.api.client:"GET http://127.0.0.1/api/" elapsed: 0:00:00.077416
DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.projects.Projects'> by url: /api/v2/projects/
DEBUG:urllib3.connectionpool:http://127.0.0.1:80 "OPTIONS /api/v2/projects/ HTTP/1.1" 200 17361
DEBUG:awxkit.api.client:"OPTIONS http://127.0.0.1/api/v2/projects/" elapsed: 0:00:00.203726
DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.projects.Projects'> by url: /api/v2/projects/
DEBUG:urllib3.connectionpool:http://127.0.0.1:80 "OPTIONS /api/v2/projects/1/ HTTP/1.1" 200 8958
DEBUG:awxkit.api.client:"OPTIONS http://127.0.0.1/api/v2/projects/1/" elapsed: 0:00:00.172019
DEBUG:urllib3.connectionpool:http://127.0.0.1:80 "OPTIONS /api/v2/projects/1/update/ HTTP/1.1" 200 697
DEBUG:awxkit.api.client:"OPTIONS http://127.0.0.1/api/v2/projects/1/update/" elapsed: 0:00:00.088712
awx: unrecognized arguments: -v
DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.projects.Projects'> by url: /api/v2/projects/
DEBUG:urllib3.connectionpool:http://127.0.0.1:80 "POST /api/v2/projects/ HTTP/1.1" 201 2293
DEBUG:awxkit.api.client:"POST http://127.0.0.1/api/v2/projects/" elapsed: 0:00:00.274274
DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.projects.Project'> by url: /api/v2/projects/
DEBUG:awxkit.api.registry:Retrieved <class 'awxkit.api.pages.projects.ProjectUpdates'> by url: /api/v2/projects/15/project_updates/
DEBUG:urllib3.connectionpool:http://127.0.0.1:80 "GET /api/v2/projects/15/project_updates/?order_by=-created HTTP/1.1" 200 52
DEBUG:awxkit.api.client:"GET http://127.0.0.1/api/v2/projects/15/project_updates/?order_by=-created" elapsed: 0:00:00.090146
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/awxkit/cli/__init__.py", line 25, in run
    cli.parse_resource()
  File "/usr/local/lib/python3.6/dist-packages/awxkit/cli/client.py", line 168, in parse_resource
    response = self.parse_action(resource)
  File "/usr/local/lib/python3.6/dist-packages/awxkit/cli/client.py", line 314, in parse_action
    return page.post(parsed)
  File "/usr/local/lib/python3.6/dist-packages/awxkit/cli/custom.py", line 137, in post
    ).results[0]
IndexError: list index out of range

```

Although the project gets created successfully.

**Comment by gamuniz** [comment]
closing due to lack of response
