### ISSUE TITLE
AWX Inventory sync from oVirt broken since 3.0.0.0

### ISSUE THREAD

**Issue by umataro** [ansible/awx#3131]
##### ISSUE TYPE
bug report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Inventory sync does not work anymore

##### ENVIRONMENT

* AWX version: 3.0.0.0
* AWX install method: docker (geerlingguy/ansible-role-awx update from awx 2.1.0 to 3.0.0.0)
* Ansible version: 2.7.6

##### STEPS TO REPRODUCE

Attempt to resync inventory using oVirt source (ovirt4.py)

##### EXPECTED RESULTS

successful sync (green cloud)

##### ACTUAL RESULTS

failed sync (red cloud)

##### ADDITIONAL INFORMATION

```
    1.571 INFO     Updating inventory 5: at_dc_ovirt_vm
    1.589 DEBUG    Using base command: /usr/bin/ansible-inventory -i /var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/plugins/inventory/ovirt4.py
    1.589 INFO     Reading Ansible inventory source: /var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/plugins/inventory/ovirt4.py
    1.590 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    1.590 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    1.590 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python2.7/site-packages:
  171.737 DEBUG    Finished loading from source: /var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/plugins/inventory/ovirt4.py
  171.737 INFO     Processing JSON output...
  171.737 DEBUG    Loaded group: all
  171.740 DEBUG    Loaded group: affinity_group_LB-10
  171.741 DEBUG    Adding child group affinity_group_LB-10 to parent all
  171.742 DEBUG    Loaded host: lb11
  171.743 DEBUG    Adding host lb11 to group affinity_group_LB-10
  171.745 DEBUG    Loaded host: lb12
  171.745 DEBUG    Adding host lb12 to group affinity_group_LB-10
  171.745 DEBUG    Adding child group affinity_group_LB-10 to parent all
  171.745 DEBUG    Loaded group: affinity_group_LB-20
  171.745 DEBUG    Adding child group affinity_group_LB-20 to parent all
  171.746 DEBUG    Loaded host: lb21
  171.746 DEBUG    Adding host lb21 to group affinity_group_LB-20
  171.746 DEBUG    Loaded host: lb22
  171.746 DEBUG    Adding host lb22 to group affinity_group_LB-20
  171.746 DEBUG    Adding child group affinity_group_LB-20 to parent all
  171.746 DEBUG    Loaded group: affinity_group_LB-30
  171.746 DEBUG    Adding child group affinity_group_LB-30 to parent all
  171.746 DEBUG    Loaded host: lb31
  
 ----snip snip-----
 
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==3.0.0.0', 'console_scripts', 'awx-manage')()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 150, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1030, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 975, in handle
    self.load_into_database()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 824, in load_into_database
    self._delete_hosts()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 413, in _delete_hosts
    instance_ids = all_instance_ids[offset:(offset + self._batch_size)]
TypeError: 'dict_keys' object is not subscriptable
```

**Comment by wenottingham** [comment]
This was fixed in https://github.com/ansible/awx/pull/3058, you'll need to build off of devel until a 3.0.1 or later is released.
