### ISSUE TITLE
No such file or directory error when running custom inventory

### ISSUE THREAD

**Issue by mgaruccio** [ansible/awx#3242]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
When attempting to run a custom inventory script the job fails with the error below, seeming to indicate that the script itself does not exist.
```
[WARNING]:  * Failed to parse /tmp/awx_8__1daembc/tmp1axy3nf6 with script
plugin: problem running /tmp/awx_8__1daembc/tmp1axy3nf6 --list ([Errno 2] No
such file or directory)
```

##### ENVIRONMENT
* AWX version: 3.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.6
* Operating System: Ubuntu
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Create any custom inventory script
2. Add script as a source for an inventory
3. Attempt to sync inventory

##### EXPECTED RESULTS

Expected an inventory to be returned

##### ACTUAL RESULTS

```
 1.735 INFO     Updating inventory 2: vCloud
    1.745 INFO     Reading Ansible inventory source: /tmp/awx_8__1daembc/tmp1axy3nf6
    1.747 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    1.747 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    1.747 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python2.7/site-packages:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==3.0.0.0', 'console_scripts', 'awx-manage')()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 150, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1030, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 930, in handle
    data = AnsibleInventoryLoader(source=source, is_custom=self.is_custom, venv_path=venv_path).load()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 176, in load
    return self.command_to_json(base_args + ['--list'])
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 159, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
 [WARNING]:  * Failed to parse /tmp/awx_8__1daembc/tmp1axy3nf6 with script
plugin: problem running /tmp/awx_8__1daembc/tmp1axy3nf6 --list ([Errno 2] No
such file or directory)
 [WARNING]: Unable to parse /tmp/awx_8__1daembc/tmp1axy3nf6 as an inventory
source
ERROR! No inventory was parsed, please check your configuration and options.
```
##### ADDITIONAL INFORMATION

Attempted to run this with both a real custom script and a script that returns a faked JSON object with same result on both attempts.

**Comment by mgaruccio** [comment]
annd never mind, I had an invalid hashbang, sorry for the clutter
