### ISSUE TITLE
Can not login in AWX web UI with french browser

### ISSUE THREAD

**Issue by fredgate** [ansible/awx#3407]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Error to login in AWX web UI.

##### ENVIRONMENT
* AWX version: 3.0.1.0
* AWX install method: docker on linux
* Ansible version:  2.7.7
* Operating System: Debian 9
* Web Browser: Firefox, Chrome

##### STEPS TO REPRODUCE
Install AWX with Docker on Linux using playbook from git repository. All is fine. Configuration was successfully with awx-cli (organization, projects, inventories, job templates...).
Open awx web in a browser and enter credentials for the admin user.

##### EXPECTED RESULTS
I can login in AWX web application and see dashboard.

##### ACTUAL RESULTS

I can not login. The web application returns that credentials are invalid.
The following error appear in the logs of the `awx_web` container :

> Traceback (most recent call last):
>   File "/usr/lib64/python3.6/logging/__init__.py", line 995, in emit
>     stream.write(msg)
> UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 879: ordinal not in range(128)
> 
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
>     response = get_response(request)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/wsgi.py", line 71, in _legacy_get_response
>     return super(AWXWSGIHandler, self)._legacy_get_response(request)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
>     response = self._get_response(request)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
>     return func(*args, **kwds)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/views/generic/base.py", line 68, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
>     return bound_func(*args, **kwargs)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
>     return view(request, *args, **kwargs)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
>     return func.__get__(self, type(self))(*args2, **kwargs2)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
>     return bound_func(*args, **kwargs)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
>     response = view_func(request, *args, **kwargs)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
>     return func.__get__(self, type(self))(*args2, **kwargs2)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
>     return bound_func(*args, **kwargs)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
>     response = view_func(request, *args, **kwargs)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
>     return func.__get__(self, type(self))(*args2, **kwargs2)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/auth/views.py", line 90, in dispatch
>     return super(LoginView, self).dispatch(request, *args, **kwargs)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
>     return handler(request, *args, **kwargs)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/api/generics.py", line 83, in post
>     ret = super(LoggedLoginView, self).post(request, *args, **kwargs)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/views/generic/edit.py", line 182, in post
>     if form.is_valid():
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/forms/forms.py", line 183, in is_valid
>     return self.is_bound and not self.errors
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/forms/forms.py", line 175, in errors
>     self.full_clean()
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/forms/forms.py", line 385, in full_clean
>     self._clean_form()
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/forms/forms.py", line 412, in _clean_form
>     cleaned_data = self.clean()
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/auth/forms.py", line 187, in clean
>     self.user_cache = authenticate(self.request, username=username, password=password)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/auth/__init__.py", line 70, in authenticate
>     user = _authenticate_with_backend(backend, backend_path, request, credentials)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/auth/__init__.py", line 116, in _authenticate_with_backend
>     return backend.authenticate(*args, **credentials)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/sso/backends.py", line 88, in authenticate
>     if self.settings.START_TLS and ldap.OPT_X_TLS_REQUIRE_CERT in self.settings.CONNECTION_OPTIONS:
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/sso/backends.py", line 79, in _get_settings
>     self._settings = LDAPSettings(self.settings_prefix)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/sso/backends.py", line 49, in __init__
>     super(LDAPSettings, self).__init__(prefix, defaults)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 994, in __init__
>     value = getattr(django.conf.settings, prefix + name, default)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/conf/settings.py", line 542, in __getattr_without_cache__
>     return getattr(self._wrapped, name)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/conf/settings.py", line 446, in __getattr__
>     value = self._get_local(name)
>   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/conf/settings.py", line 432, in _get_local
>     value, name, exc_info=True)
>   File "/usr/lib64/python3.6/logging/__init__.py", line 1319, in warning
>     self._log(WARNING, msg, args, **kwargs)
>   File "/usr/lib64/python3.6/logging/__init__.py", line 1443, in _log
>     self.handle(record)
>   File "/usr/lib64/python3.6/logging/__init__.py", line 1453, in handle
>     self.callHandlers(record)
>   File "/usr/lib64/python3.6/logging/__init__.py", line 1515, in callHandlers
>     hdlr.handle(record)
>   File "/usr/lib64/python3.6/logging/__init__.py", line 864, in handle
>     self.emit(record)
>   File "/usr/lib64/python3.6/logging/__init__.py", line 999, in emit
>     self.handleError(record)
>   File "/usr/lib64/python3.6/logging/__init__.py", line 917, in handleError
>     traceback.print_exception(t, v, tb, None, sys.stderr)
>   File "/usr/lib64/python3.6/traceback.py", line 101, in print_exception
>     print(line, file=file, end="")
> UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 47: ordinal not in range(128)
> 

##### ADDITIONAL INFORMATION
After multiple tries, I found the problem origin. It occurs for browser configured with preferred display language defined to French (fr-FR). An error occurs when this header is present on the request :
`Accept-Language | fr-FR,en-US;q=0.7,en;q=0.3`
All is fine if browser is configured for english language (en-US) and this header is present on the request :
`Accept-Language | en-US,en;q=0.7,fr-FR;q=0.3`

**Comment by ryanpetrello** [comment]
@fredgate any chance your username has any non-ASCII characters?  Trying to replicate this myself, and that might help.

**Comment by ryanpetrello** [comment]
Also, it looks like you might be using LDAP.  Any chance you could share your (sanitized) LDAP configuration?

**Comment by fredgate** [comment]
Hi.
My username has only ASCII characters : I use the local account `admin`. I do not use a LDAP account.
But effectively I have configured a LDAP provider. Here is my configuration obtained from API endpoint :
```json
{
    "AUTH_LDAP_SERVER_URI": "ldaps://ldap.mydomain:1636",
    "AUTH_LDAP_BIND_DN": "",
    "AUTH_LDAP_BIND_PASSWORD": "",
    "AUTH_LDAP_START_TLS": false,
    "AUTH_LDAP_CONNECTION_OPTIONS": {
        "OPT_REFERRALS": 0,
        "OPT_NETWORK_TIMEOUT": 30
    },
    "AUTH_LDAP_USER_SEARCH": [
        "ou=people,ou=corporate,dc=mydomain,dc=com",
        "SCOPE_SUBTREE",
        "(&(objectClass=posixAccount)(uid=%(user)s))"
    ],
    "AUTH_LDAP_USER_DN_TEMPLATE": null,
    "AUTH_LDAP_USER_ATTR_MAP": {
        "first_name": "givenName",
        "last_name": "sn",
        "email": "mail"
    },
    "AUTH_LDAP_GROUP_SEARCH": [
        "ou=groups,ou=corporate,dc=mydomain,dc=com",
        "SCOPE_SUBTREE",
        "(memberUid=*)"
    ],
    "AUTH_LDAP_GROUP_TYPE": "PosixGroupType",
    "AUTH_LDAP_GROUP_TYPE_PARAMS": {
        "name_attr": "cn",
        "member_attr": "member"
    },
    "AUTH_LDAP_REQUIRE_GROUP": null,
    "AUTH_LDAP_DENY_GROUP": null,
    "AUTH_LDAP_USER_FLAGS_BY_GROUP": {
        "is_superuser": [
            "cn=tower-administrators,ou=groups,ou=corporate,dc=mydomain,dc=com"
        ]
    },
    "AUTH_LDAP_ORGANIZATION_MAP": {
        "My": {
            "admins": "cn=tower-administrators,ou=groups,ou=corporate,dc=mydomain,dc=com",
            "remove_admins": true,
            "users": true,
            "remove_users": true
        }
    },
    "AUTH_LDAP_TEAM_MAP": {
        "Dev": {
            "organization": "My",
            "users": "cn=devteam,ou=groups,ou=corporate,dc=mydomain,dc=com",
            "remove": true
        },
        "Ops": {
            "organization": "My",
            "users": "cn=opsteam,ou=groups,ou=corporate,dc=mydomain,dc=com",
            "remove": true
        }
    },
    "AUTH_LDAP_1_SERVER_URI": "",
    "AUTH_LDAP_1_BIND_DN": "",
    "AUTH_LDAP_1_BIND_PASSWORD": "",
    "AUTH_LDAP_1_START_TLS": false,
    "AUTH_LDAP_1_CONNECTION_OPTIONS": {
        "OPT_REFERRALS": 0,
        "OPT_NETWORK_TIMEOUT": 30
    },
    "AUTH_LDAP_1_USER_SEARCH": [],
    "AUTH_LDAP_1_USER_DN_TEMPLATE": null,
    "AUTH_LDAP_1_USER_ATTR_MAP": {},
    "AUTH_LDAP_1_GROUP_SEARCH": [],
    "AUTH_LDAP_1_GROUP_TYPE": "MemberDNGroupType",
    "AUTH_LDAP_1_GROUP_TYPE_PARAMS": {
        "member_attr": "member",
        "name_attr": "cn"
    },
    "AUTH_LDAP_1_REQUIRE_GROUP": null,
    "AUTH_LDAP_1_DENY_GROUP": null,
    "AUTH_LDAP_1_USER_FLAGS_BY_GROUP": {},
    "AUTH_LDAP_1_ORGANIZATION_MAP": {},
    "AUTH_LDAP_1_TEAM_MAP": {},
    "AUTH_LDAP_2_SERVER_URI": "",
    "AUTH_LDAP_2_BIND_DN": "",
    "AUTH_LDAP_2_BIND_PASSWORD": "",
    "AUTH_LDAP_2_START_TLS": false,
    "AUTH_LDAP_2_CONNECTION_OPTIONS": {
        "OPT_REFERRALS": 0,
        "OPT_NETWORK_TIMEOUT": 30
    },
    "AUTH_LDAP_2_USER_SEARCH": [],
    "AUTH_LDAP_2_USER_DN_TEMPLATE": null,
    "AUTH_LDAP_2_USER_ATTR_MAP": {},
    "AUTH_LDAP_2_GROUP_SEARCH": [],
    "AUTH_LDAP_2_GROUP_TYPE": "MemberDNGroupType",
    "AUTH_LDAP_2_GROUP_TYPE_PARAMS": {
        "member_attr": "member",
        "name_attr": "cn"
    },
    "AUTH_LDAP_2_REQUIRE_GROUP": null,
    "AUTH_LDAP_2_DENY_GROUP": null,
    "AUTH_LDAP_2_USER_FLAGS_BY_GROUP": {},
    "AUTH_LDAP_2_ORGANIZATION_MAP": {},
    "AUTH_LDAP_2_TEAM_MAP": {},
    "AUTH_LDAP_3_SERVER_URI": "",
    "AUTH_LDAP_3_BIND_DN": "",
    "AUTH_LDAP_3_BIND_PASSWORD": "",
    "AUTH_LDAP_3_START_TLS": false,
    "AUTH_LDAP_3_CONNECTION_OPTIONS": {
        "OPT_REFERRALS": 0,
        "OPT_NETWORK_TIMEOUT": 30
    },
    "AUTH_LDAP_3_USER_SEARCH": [],
    "AUTH_LDAP_3_USER_DN_TEMPLATE": null,
    "AUTH_LDAP_3_USER_ATTR_MAP": {},
    "AUTH_LDAP_3_GROUP_SEARCH": [],
    "AUTH_LDAP_3_GROUP_TYPE": "MemberDNGroupType",
    "AUTH_LDAP_3_GROUP_TYPE_PARAMS": {
        "member_attr": "member",
        "name_attr": "cn"
    },
    "AUTH_LDAP_3_REQUIRE_GROUP": null,
    "AUTH_LDAP_3_DENY_GROUP": null,
    "AUTH_LDAP_3_USER_FLAGS_BY_GROUP": {},
    "AUTH_LDAP_3_ORGANIZATION_MAP": {},
    "AUTH_LDAP_3_TEAM_MAP": {},
    "AUTH_LDAP_4_SERVER_URI": "",
    "AUTH_LDAP_4_BIND_DN": "",
    "AUTH_LDAP_4_BIND_PASSWORD": "",
    "AUTH_LDAP_4_START_TLS": false,
    "AUTH_LDAP_4_CONNECTION_OPTIONS": {
        "OPT_REFERRALS": 0,
        "OPT_NETWORK_TIMEOUT": 30
    },
    "AUTH_LDAP_4_USER_SEARCH": [],
    "AUTH_LDAP_4_USER_DN_TEMPLATE": null,
    "AUTH_LDAP_4_USER_ATTR_MAP": {},
    "AUTH_LDAP_4_GROUP_SEARCH": [],
    "AUTH_LDAP_4_GROUP_TYPE": "MemberDNGroupType",
    "AUTH_LDAP_4_GROUP_TYPE_PARAMS": {
        "member_attr": "member",
        "name_attr": "cn"
    },
    "AUTH_LDAP_4_REQUIRE_GROUP": null,
    "AUTH_LDAP_4_DENY_GROUP": null,
    "AUTH_LDAP_4_USER_FLAGS_BY_GROUP": {},
    "AUTH_LDAP_4_ORGANIZATION_MAP": {},
    "AUTH_LDAP_4_TEAM_MAP": {},
    "AUTH_LDAP_5_SERVER_URI": "",
    "AUTH_LDAP_5_BIND_DN": "",
    "AUTH_LDAP_5_BIND_PASSWORD": "",
    "AUTH_LDAP_5_START_TLS": false,
    "AUTH_LDAP_5_CONNECTION_OPTIONS": {
        "OPT_REFERRALS": 0,
        "OPT_NETWORK_TIMEOUT": 30
    },
    "AUTH_LDAP_5_USER_SEARCH": [],
    "AUTH_LDAP_5_USER_DN_TEMPLATE": null,
    "AUTH_LDAP_5_USER_ATTR_MAP": {},
    "AUTH_LDAP_5_GROUP_SEARCH": [],
    "AUTH_LDAP_5_GROUP_TYPE": "MemberDNGroupType",
    "AUTH_LDAP_5_GROUP_TYPE_PARAMS": {
        "member_attr": "member",
        "name_attr": "cn"
    },
    "AUTH_LDAP_5_REQUIRE_GROUP": null,
    "AUTH_LDAP_5_DENY_GROUP": null,
    "AUTH_LDAP_5_USER_FLAGS_BY_GROUP": {},
    "AUTH_LDAP_5_ORGANIZATION_MAP": {},
    "AUTH_LDAP_5_TEAM_MAP": {}
}
```

**Comment by fredgate** [comment]
I found the problem.
It occurs when `AUTH_LDAP_GROUP_TYPE` is set to `PosixGroupType` and `AUTH_LDAP_GROUP_TYPE_PARAMS` is not set so initialized by AWX to default value `{"name_attr": "cn", "member_attr": "member"}` which is not valid for this type.
AWX want to prepare a message that it can not format when locale is french.
Since I explicitly set the `AUTH_LDAP_GROUP_TYPE_PARAMS` to `{"name_attr": "cn"}` wich is valid for `PosixGroupType`, I have no problem and I can now log in AWX.

May be that AWX should not set this default value (that is the only LDAP property that is set by default).

**Comment by ryanpetrello** [comment]
@fredgate,

I'm struggling to explain why your French locale would matter, as the line where the error occurs isn't a string that we translate:

```python
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/conf/settings.py", line 446, in getattr
value = self._get_local(name)
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/conf/settings.py", line 432, in _get_local
value, name, exc_info=True)
```

https://github.com/ansible/awx/blob/3d9a47f0d90f57e0bf2cafdd1bc421d423e655f3/awx/conf/settings.py#L430-L432

**Comment by TheRealHaoLiu** [comment]
closing due to inactivity
