### ISSUE TITLE
AWX doesn't run scheduled job

### ISSUE THREAD

**Issue by fedelemantuano** [ansible/awx#3467]
##### ISSUE TYPE
I can't understand why AWX doesn't start all scheduled jobs.

##### COMPONENT NAME
 - awx.main.tasks

##### SUMMARY
AWX works well, start all job template but sometimes happens that it doesn't spawns jobs from a scheduling.
I don't see errors logs or othor errors around scheduling time.
I can't reproduce the error, but after docker container restart, the scheduling works.

##### ENVIRONMENT
* AWX version: 1.0.7.2
* AWX install method: docker
* Ansible version:  2.6.2
* Operating System: Red Had
* Web Browser: Chrome

##### STEPS TO REPRODUCE

I can't reproduce the errors. It happens randomly.

##### EXPECTED RESULTS

Spawn a job template.

##### ACTUAL RESULTS

If I don't restart docker it doesn't start the job

**Comment by fedelemantuano** [comment]
Hi,

I checked the error in docker logs and I can attach:

```
['File "/var/lib/awx/venv/awx/bin/celery", line 11, in <module>\n    sys.exit(main())\n', '  File "/var/
lib/awx/venv/awx/lib/python2.7/site-packages/celery/__main__.py", line 30, in main\n    main()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/
bin/celery.py", line 81, in main\n    cmd.execute_from_commandline(argv)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/celery.py", line 7
93, in execute_from_commandline\n    super(CeleryCommand, self).execute_from_commandline(argv)))\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celer
y/bin/base.py", line 311, in execute_from_commandline\n    return self.handle_argv(self.prog_name, argv[1:])\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-pa
ckages/celery/bin/celery.py", line 785, in handle_argv\n    return self.execute(command, argv)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/
bin/celery.py", line 717, in execute\n    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/c
elery/bin/worker.py", line 179, in run_from_argv\n    return self(*args, **options)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/base.py
", line 274, in __call__\n    ret = self.run(*args, **kwargs)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run\
n    state_db=self.node_format(state_db, hostname), **kwargs\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in
start\n    self.blueprint.start(self)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start\n    step.start(parent)
\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start\n    return self.obj.start()\n', '  File "/var/lib/awx/venv/
awx/lib/python2.7/site-packages/billiard/process.py", line 137, in start\n    self._popen = Popen(self)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-package
s/billiard/forking.py", line 105, in __init__\n    code = process_obj._bootstrap()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/billiard/process.py
", line 292, in _bootstrap\n    self.run()\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 553, in run\n    self.service.start(e
mbedded_process=True)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 479, in start\n    interval = self.scheduler.tick()\n', '
 File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 221, in tick\n    next_time_to_run = self.maybe_due(entry, self.publisher)\n', '  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 207, in maybe_due\n    exc, traceback.format_stack(), exc_info=True)\n']



Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 204, in maybe_due
    result = self.apply_async(entry, publisher=publisher)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 260, in apply_async
    entry, exc=exc)), sys.exc_info()[2])
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/beat.py", line 252, in apply_async
    **entry.options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/task.py", line 573, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/base.py", line 345, in send_task
    options = router.route(options, name, args, kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/routes.py", line 50, in route
    route = self.lookup_route(task, args, kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/routes.py", line 78, in lookup_route
    return _first_route(self.routes, task, args, kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/utils/functional.py", line 233, in _matcher
    answer = getattr(maybe_evaluate(obj), method)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/utils/ha.py", line 11, in route_for_task
    (changed, instance) = Instance.objects.get_or_register()
  File "/usr/lib/python2.7/site-packages/awx/main/managers.py", line 106, in get_or_register
    return (False, self.me())
  File "/usr/lib/python2.7/site-packages/awx/main/managers.py", line 86, in me
    if node.exists():
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 670, in exists
    return self.query.has_results(using=self.db)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/query.py", line 517, in has_results
    return compiler.has_results()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 858, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
SchedulingError: Couldn't apply scheduled task tower_scheduler: could not receive data from server: Bad file descriptor
```

**Comment by ryanpetrello** [comment]
Looks like this might be some version of https://github.com/celery/celery/issues/3409

**Comment by ryanpetrello** [comment]
@fedelemantuano have you tried this on a more modern version of AWX?  We've since removed a *lot* of our usage of celery (due to problematic bugs like this one).

**Comment by fedelemantuano** [comment]
No, I didn't. Do you have best pratice to upgrade to new version without issues?
I know that it's almost impossibile.

**Comment by fedelemantuano** [comment]
I upgraded in stage environment from `1.0.7.2` to `3.0.1.0`, without issues. So we can close this issue for now.
If I'll have another error I'll open a new issue.
