### ISSUE TITLE
Inventory update errors duplicated in stdout

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#3493]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Inventory update standard out has duplicated content

##### ENVIRONMENT
* AWX version: right after ansible-runner merge
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Create an inventory with an ec2 inventory source that has invalid aws credentials applied to it.

##### EXPECTED RESULTS

failure

##### ACTUAL RESULTS

failure with this

```
    3.522 INFO     Updating inventory 2245: bad ec2
    3.538 INFO     Reading Ansible inventory source: /awx_devel/awx/plugins/inventory/ec2.py
    3.540 INFO     Using VIRTUAL_ENV: /venv/ansible
    3.540 INFO     Using PATH: /venv/ansible/bin:/venv/awx/bin:/venv/awx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    3.540 INFO     Using PYTHONPATH: /venv/ansible/lib/python2.7/site-packages:
    6.071 ERROR    ansible-inventory failed (rc=1) with stdout:

stderr:
 [WARNING]:  * Failed to parse /awx_devel/awx/plugins/inventory/ec2.py with
script plugin: Inventory script (/awx_devel/awx/plugins/inventory/ec2.py) had
an execution error: ERROR: "Authentication error retrieving ec2 inventory.  -
AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment vars found but may not
be correct  - No Boto config found at any expected location '/etc/boto.cfg,
~/.boto, ~/.aws/credentials'", while: getting EC2 instances

 [WARNING]: Unable to parse /awx_devel/awx/plugins/inventory/ec2.py as an
inventory source

ERROR! No inventory was parsed, please check your configuration and options.

Traceback (most recent call last):
  File "/usr/local/bin/awx-manage", line 9, in <module>
    load_entry_point('awx', 'console_scripts', 'awx-manage')()
  File "/awx_devel/awx/__init__.py", line 140, in manage
    execute_from_command_line(sys.argv)
  File "/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/awx_devel/awx/main/management/commands/inventory_import.py", line 1111, in handle
    raise exc
  File "/awx_devel/awx/main/management/commands/inventory_import.py", line 1003, in handle
    data = AnsibleInventoryLoader(source=source, is_custom=self.is_custom, venv_path=venv_path).load()
  File "/awx_devel/awx/main/management/commands/inventory_import.py", line 195, in load
    return self.command_to_json(base_args + ['--list'])
  File "/awx_devel/awx/main/management/commands/inventory_import.py", line 178, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:

stderr:
 [WARNING]:  * Failed to parse /awx_devel/awx/plugins/inventory/ec2.py with
script plugin: Inventory script (/awx_devel/awx/plugins/inventory/ec2.py) had
an execution error: ERROR: "Authentication error retrieving ec2 inventory.  -
AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment vars found but may not
be correct  - No Boto config found at any expected location '/etc/boto.cfg,
~/.boto, ~/.aws/credentials'", while: getting EC2 instances

 [WARNING]: Unable to parse /awx_devel/awx/plugins/inventory/ec2.py as an
inventory source

ERROR! No inventory was parsed, please check your configuration and options.
```

##### ADDITIONAL INFORMATION

duplicated error

**Comment by AlanCoding** [comment]
Resolved by @jbradberry in https://github.com/ansible/awx/pull/3174/commits/046385d72ebd0050d0cdffa38099dfca6e53e363 and ansible/awx#3532
