### ISSUE TITLE
Inventory Source using script in Source From Project not working

### ISSUE THREAD

**Issue by ryan012880** [ansible/awx#3537]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI
 - Installer

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.9
* Operating System: RHEL7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Fresh install AWX 4.0.0 (pull official container from docker hub)
2. Configure an inventory using inventory source and source from project with script
3. Execute sync

##### EXPECTED RESULTS

Sync should not fail

##### ACTUAL RESULTS

<img width="1222" alt="Screen Shot 2019-03-29 at 12 08 04 AM" src="https://user-images.githubusercontent.com/10410660/55173562-dcb11000-51b6-11e9-82bd-5272abfad99a.png">

##### ADDITIONAL INFORMATION

Same error when executing the command awx-manage inside the container itself.

```
[root@awxweb awx]# awx-manage --help
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==4.0.0.0', 'console_scripts', 'awx-manage')()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 124, in manage
    prepare_env()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 89, in prepare_env
    if not settings.DEBUG: # pragma: no cover
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/settings/production.py", line 85, in <module>
    include(settings_file, optional(settings_files), scope=locals())
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/split_settings/tools.py", line 102, in include
    exec(compile(to_compile.read(), included_file, 'exec'), scope)
ValueError: source code string cannot contain null bytes
```

**Comment by ryan012880** [comment]
I did a container rebuild and all is good, not sure what is the issue on the official container in docker hub though.
