### ISSUE TITLE
Import Inventory failed trough Github File. Local CLI works

### ISSUE THREAD

**Issue by BramFr** [ansible/awx#3568]
##### ISSUE TYPE
- Import from github file failed

##### COMPONENT NAME
 - Github
 - UI

##### ENVIRONMENT
* AWX version: 2.1.2.0
* AWX install method: docker on linux (ansible/awx_task:2.1.2 Image: sha256:5e3665e23839a90dff9e14eca38eb60fb7e599c81984f846e565d22687eedf87)
* Ansible version:  2.7.4
* Operating System: Linux Debian 10

##### STEPS TO REPRODUCE
Create a file on github and try to update ore create your inventory.

##### EXPECTED RESULTS
Update/Create Invenotry with hosts and Groups

##### ACTUAL RESULTS
Job give me a failed:

```
2019-04-01 09:07:29,519 DEBUG    awx.main.models.inventory Going to update inventory computed fields
2019-04-01 09:07:29,530 DEBUG    awx.main.models.inventory Finished updating inventory computed fields
2019-04-01 09:07:29,532 ERROR    awx.main.tasks inventory_update 52 (running) Exception occurred while running task
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 928, in run
    self.pre_run_hook(instance, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 2174, in pre_run_hook
    project_update_task().run(local_project_sync.id)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 619, in _wrapped
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 1072, in run
    raise AwxTaskError.TaskError(instance, rc)
Exception: project_update 53 (failed) encountered an error (rc=2), please see task stdout for details.
2019-04-01 09:07:29,532 INFO     awx.main.tasks inventory_update 52 (running) finished running, producing 0 events.
2019-04-01 09:07:29,570 DEBUG    awx.main.models.inventory Going to update inventory computed fields
2019-04-01 09:07:29,581 DEBUG    awx.main.models.inventory Finished updating inventory computed fields
2019-04-01 09:07:29,589 WARNING  awx.main.dispatch inventory_update 52 (error) encountered an error (rc=None), please see task stdout for details.
2019-04-01 09:07:29,590 DEBUG    awx.main.dispatch task 705a79ac-bbf3-4072-b394-273ae99aa8cd starting awx.main.tasks.handle_work_error(*[u'705a79ac-bbf3-4072-b394-273ae99aa8cd'])
2019-04-01 09:07:29,591 DEBUG    awx.main.tasks Executing error task id 705a79ac-bbf3-4072-b394-273ae99aa8cd, subtasks: [{u'type': u'inventory_update', u'id': 52}]
```

##### ADDITIONAL INFORMATION

When i try local with the same inventory file everythinks works:

Trough CLI:
```
awx-manage inventory_import --inventory-name Github-Inventory --source ./inventory.yml 
    1.572 INFO     Updating inventory 3: Github-Inventory
    1.627 INFO     Reading Ansible inventory source: /var/lib/awx/projects/_6__anisble/inventory/inventory.yml
    2.371 INFO     Processing JSON output...
    2.372 INFO     Loaded 6 groups, 106 hosts
2019-04-01 09:18:59,110 DEBUG    awx.main.models.inventory Going to update inventory computed fields
2019-04-01 09:18:59,177 DEBUG    awx.main.models.inventory Finished updating inventory computed fields
    2.524 INFO     Inventory import completed for  (Github-Inventory - 11) in 1.0s
```

**Comment by BramFr** [comment]
typo within requirements.yml file. 
```
TASK [fetch galaxy roles from requirements.yml] ********************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["ansible-galaxy", "install", "-r", "requirements.yml", "-p", "/var/lib/awx/projects/_6__anisble/roles/"], "delta": "0:00:02.387701", "end": "2019-04-01 07:37:54.036872", "msg": "non-zero return code", "rc": 1, "start": "2019-04-01 07:37:51.649171", "stderr": "\u001b[1;35m [WARNING]: - ansible-network was NOT installed successfully: this role does\u001b[0m\n\u001b[1;35mnot appear to have a meta/main.yml file.\u001b[0m\n\u001b[1;35m\u001b[0m\n\u001b[0;31mERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.\u001b[0m", "stderr_lines": ["\u001b[1;35m [WARNING]: - ansible-network was NOT installed successfully: this role does\u001b[0m", "\u001b[1;35mnot appear to have a meta/main.yml file.\u001b[0m", "\u001b[1;35m\u001b[0m", "\u001b[0;31mERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.\u001b[0m"], "stdout": "", "stdout_lines": []}
```
