### ISSUE TITLE
ModuleNotFoundError: No module named 'corsheaders'

### ISSUE THREAD

**Issue by ghost** [ansible/awx#3588]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Receiving tracebacks within the awx_task container's awx venv regarding corsheaders missing. forcing `django-cors-headers` into the requirements files for the venv do not resolve the issue

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker on nomad
* Ansible version:  2.6.11
* Operating System: linux
* Web Browser: chrome

##### STEPS TO REPRODUCE

deploy official images as nomad job

##### EXPECTED RESULTS

no errors in the stderr 

##### ACTUAL RESULTS

errors produced (provided below)

##### ADDITIONAL INFORMATION

```
Traceback (most recent call last):
  File "/usr/local/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==3.0.1', 'console_scripts', 'awx-manage')()
  File "/usr/local/lib/python3.6/site-packages/awx/__init__.py", line 140, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'corsheaders'
```

**Comment by ryanpetrello** [comment]
Are you still encountering this on the latest version of awx (4.0.0)?

**Comment by michalss** [comment]
yes im getting this error as well :(

**Comment by awithrow9** [comment]
Please try this again with the latest.
