### ISSUE TITLE
minishift MAC based install fails - password authentication failed for user "awx"

### ISSUE THREAD

**Issue by ffirg** [ansible/awx#368]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
awx pod logs show 'password authentication failed for user "awx"' and GUI is not available (internal server error) when hitting route

##### ENVIRONMENT
* AWX version: origin/devel
* AWX install method: minishift
* Ansible version:  2.4.0.0
* Operating System: macOS Sierra 10.12.6
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Followed install instructions for minishift

```
$ grep -Ev '^$|#' inventory
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"
[all:vars]
dockerhub_base=ansible
dockerhub_version=latest
awx_secret_key=awxsecret
openshift_host=192.168.99.100:8443
awx_openshift_project=awx
openshift_user=developer
awx_node_port=30083
postgres_data_dir=/tmp/pgdocker
host_port=80
docker_registry=172.30.1.1:5000
docker_registry_repository=awx
docker_registry_username=developer
pg_username=awx
pg_password=awxpass
pg_database=awx
pg_port=5432
```

##### EXPECTED RESULTS

Access to containerised GUI

##### ACTUAL RESULTS

awx pod logs repeatedly show:

```
2017-10-05 09:28:18,560 INFO exited: daphne (exit status 1; not expected)
--
  | 2017-10-05 09:28:19,564 INFO spawned: 'daphne' with pid 784
  | 2017-10-05 09:28:20,570 INFO success: daphne entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
  | Traceback (most recent call last):
  | File "/var/lib/awx/venv/awx/bin/daphne", line 11, in <module>
  | sys.exit(CommandLineInterface.entrypoint())
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/daphne/cli.py", line 105, in entrypoint
  | cls().run(sys.argv[1:])
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/daphne/cli.py", line 135, in run
  | channel_layer = importlib.import_module(module_path)
  | File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
  | __import__(name)
  | File "/usr/lib/python2.7/site-packages/awx/asgi.py", line 37, in <module>
  | channel_layer = get_channel_layer()
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/channels/asgi.py", line 100, in get_channel_layer
  | django.setup()
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
  | apps.populate(settings.INSTALLED_APPS)
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
  | app_config.ready()
  | File "/usr/lib/python2.7/site-packages/awx/conf/apps.py", line 18, in ready
  | configure_external_logger(settings)
  | File "/usr/lib/python2.7/site-packages/awx/main/utils/handlers.py", line 342, in configure_external_logger
  | is_enabled = settings_module.LOG_AGGREGATOR_ENABLED
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in __getattr__
  | return getattr(self._wrapped, name)
  | File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 386, in __getattr__
  | value = self._get_local(name)
  | File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
  | self.gen.throw(type, value, traceback)
  | File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 64, in _log_database_error
  | if get_tower_migration_version() < '310':
  | File "/usr/lib/python2.7/site-packages/awx/main/utils/db.py", line 13, in get_tower_migration_version
  | loader = MigrationLoader(connection, ignore_no_migrations=True)
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
  | self.build_graph()
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/loader.py", line 191, in build_graph
  | self.applied_migrations = recorder.applied_migrations()
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
  | self.ensure_schema()
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
  | if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 164, in cursor
  | cursor = self.make_cursor(self._cursor())
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 135, in _cursor
  | self.ensure_connection()
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
  | self.connect()
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
  | six.reraise(dj_exc_type, dj_exc_value, traceback)
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
  | self.connect()
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/transaction_hooks/mixin.py", line 75, in connect
  | super(TransactionHooksDatabaseWrapperMixin, self).connect(*a, **kw)
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py", line 119, in connect
  | self.connection = self.get_new_connection(conn_params)
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in get_new_connection
  | connection = Database.connect(**conn_params)
  | File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
  | conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  | django.db.utils.OperationalError: FATAL:  password authentication failed for user "awx"
```

**Comment by matburt** [comment]
It does look like you are defining some of the vars that aren't used by openshift `postgres_data_dir=/tmp/pgdocker` for example.

It seems like something must have gone wrong generating the postgres service itself in minishift.

Can you:
* Show me the playbook log where the postgres pod was created
* Is the postgres pod running?
* Was it available and ready to accept connections when the awx container came up? Did you try re-launching the containers?
* Can you try to connect to the postgres service that was created via the credentials supplied in the playbook?

**Comment by ffirg** [comment]
Just tried again, same error. 
Also upgraded to minishift v1.6.0+7a71565
Also tried new deployments.

Playbook logs: https://pastebin.com/n9Abkck7

$ grep pg_ inventory
\# Set pg_hostname if you have an external postgres server, otherwise
\# pg_hostname=postgresql
pg_username=awx
pg_password=redhat
pg_database=awx
pg_port=5432

$ grep pg_username openshift/tasks/main.yml
  shell: "oc new-app --template=postgresql-persistent -e MEMORY_LIMIT={{ pg_memory_limit|default('512') }}Mi -e NAMESPACE=openshift -e DATABASE_SERVICE_NAME=postgresql  -e POSTGRESQL_USER={{ pg_username }} -e POSTGRESQL_PASSWORD={{ pg_password }} -e POSTGRESQL_DATABASE={{ pg_database }} -e VOLUME_CAPACITY={{ pg_volume_capacity|default('5')}}Gi -e POSTGRESQL_VERSION=9.5 -n {{ awx_openshift_project }}"

$ oc get pods -o wide
NAME                   READY     STATUS    RESTARTS   AGE       IP           NODE
awx-2602614252-217zz   4/4       Running   0          30m       172.17.0.3   localhost
postgresql-2-k18vr     1/1       Running   0          15m       172.17.0.4   localhost

Using the terminal inside the awx pod:
sh-4.2$ psql -h 172.17.0.4 -U awx                                                                                                                                                           
Password for user awx:                                                                                                                                                                      
psql: FATAL:  password authentication failed for user "awx" 

Inside the postgred pod terminal:
sh-4.2$ psql                                                                                                                                                                                
psql (9.5.7)                                                                                                                                                                                
Type "help" for help.                                                                                                                                                                       
                                                                                                                                                                                            
postgres=# \du                                                                                                                                                                              
                                   List of roles                                                                                                                                            
 Role name |                         Attributes                         | Member of                                                                                                         
-----------+------------------------------------------------------------+-----------                                                                                                        
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}                                                                                                                
 userKDL   |                                                            | {}  
^^^^^^^^^
This is the postgres secrets, so no awx user has been created?

**Comment by ffirg** [comment]
So got it working by creating an 'awx' user in postgres directly, then creating the awx database owned by awx. Restarted the awx pod and it's now up and running.

So for some reason the installer isn't creating the awx database and user???

This is the inventory file I used - am I doing something wrong here?
```
$ cat inventory
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"

[all:vars]

# Remove these lines if you want to run a local image build
# Otherwise the setup playbook will install the official Ansible images. Versions may
# be selected based on: latest, 1, 1.0, 1.0.0, 1.0.0.123
# by default the base will be used to search for ansible/awx_web and ansible/awx_task
dockerhub_base=ansible
dockerhub_version=latest

# This will create or update a default admin (superuser) account in AWX, if not provided
# then these default values are used
default_admin_user=admin
default_admin_password=redhat

# AWX Secret key
# It's *very* important that this stay the same between upgrades or you will lose the ability to decrypt
# your credentials
awx_secret_key=awxsecret

# Openshift Install
# Will need to set -e openshift_password=developer -e docker_registry_password=$(oc whoami -t)
openshift_host=192.168.99.100:8443
awx_openshift_project=awx
openshift_user=developer
awx_node_port=30083

# Standalone Docker Install
#postgres_data_dir=/tmp/pgdocker
#host_port=80

# Required for Openshift when building the image on your own
# Optional for Openshift if using Dockerhub or another prebuilt registry
# Required for Standalone Docker Install if building the image on your own
# Optional for Standalone Docker Install if using Dockerhub or another prebuilt registry
# Define if you want the image pushed to a registry. The container definition will also use these images
#docker_registry=172.30.1.1:5000
#docker_registry_repository=awx
#docker_registry_username=developer

# Set pg_hostname if you have an external postgres server, otherwise
# a new postgres service will be created
# pg_hostname=postgresql
pg_username=awx
pg_password=redhat
pg_database=awx
pg_port=5432

# Use a local distribution build container image for building the AWX package
# This is helpful if you don't want to bother installing the build-time dependencies as
# it is taken care of already.
# NOTE: IMPORTANT: If you are running a mininshift install, using this container might not work
#                  if you are using certain drivers like KVM where the source tree can't be mapped
#                  into the build container.
#                  Thus this setting must be set to False which will trigger a local build. To view the
#                  typical dependencies that you might need to install see:
#                  installer/image_build/files/Dockerfile.sdist
# use_container_for_build=true

# Build AWX with official logos
# Requires cloning awx-logos repo into the project root.
# Review the trademark guidelines at https://github.com/ansible/awx-logos/blob/master/TRADEMARKS.md
# awx_official=false

# Proxy
#http_proxy=http://proxy:3128
#https_proxy=http://proxy:3128
#no_proxy=mycorp.org
```

**Comment by matburt** [comment]
Not sure why that's the case, we rely on the oc postgresql-persistent app from openshift... could you look at the logs for that pod to see if it had trouble?

**Comment by ffirg** [comment]
So it's got to be this bit in awx/installer/openshift/tasks/main.yml which isn't working properly:
```
- name: Deploy and Activate Postgres
  shell: "oc new-app --template=postgresql-persistent -e MEMORY_LIMIT={{ pg_memory_limit|default('512') }}Mi -e NAMESPACE=openshift -e DATABASE_SERVICE_NAME=postgresql  -e POSTGRESQL_USER={{ pg_username }} -e POSTGRESQL_PASSWORD={{ pg_password }} -e POSTGRESQL_DATABASE={{ pg_database }} -e VOLUME_CAPACITY={{ pg_volume_capacity|default('5')}}Gi -e POSTGRESQL_VERSION=9.5 -n {{ awx_openshift_project }}"
  when: (pg_hostname is not defined or pg_hostname == '') and (postgres_svc_details is defined and postgres_svc_details.rc != 0)
  register: openshift_pg_activate
```

My install certainly tried to do it:
< TASK [openshift : Deploy and Activate Postgres] >
 -------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [localhost]

Where is postgres_svc_details set???

My logs have gone, I'll need to destroy and rebuild.

**Comment by matburt** [comment]
You can get a lot of the details from minishift's oc tools as well as the minishift ui also.

**Comment by ffirg** [comment]
Deleted project and tried again with -vvv

So the variables are being substituted in, but then the template uses something else???

```
 _________________________________________________
< TASK [openshift : Deploy and Activate Postgres] >
 -------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /Users/pgriffit/awx/installer/openshift/tasks/main.yml:88
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/commands/command.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: pgriffit
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/pgriffit/.ansible/tmp/ansible-tmp-1507568920.3-159604225618374 `" && echo ansible-tmp-1507568920.3-159604225618374="` echo /Users/pgriffit/.ansible/tmp/ansible-tmp-1507568920.3-159604225618374 `" ) && sleep 0'
<localhost> PUT /var/folders/gs/1m2ppsbd1j3_rs9k46x995zw0000gn/T/tmpenXNWh TO /Users/pgriffit/.ansible/tmp/ansible-tmp-1507568920.3-159604225618374/command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/pgriffit/.ansible/tmp/ansible-tmp-1507568920.3-159604225618374/ /Users/pgriffit/.ansible/tmp/ansible-tmp-1507568920.3-159604225618374/command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/env python /Users/pgriffit/.ansible/tmp/ansible-tmp-1507568920.3-159604225618374/command.py; rm -rf "/Users/pgriffit/.ansible/tmp/ansible-tmp-1507568920.3-159604225618374/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true,
    "cmd": "oc new-app --template=postgresql-persistent -e MEMORY_LIMIT=512Mi -e NAMESPACE=openshift -e DATABASE_SERVICE_NAME=postgresql -e POSTGRESQL_USER=awx -e POSTGRESQL_PASSWORD=redhat -e POSTGRESQL_DATABASE=awx -e VOLUME_CAPACITY=5Gi -e POSTGRESQL_VERSION=9.5 -n awx",
    "delta": "0:00:00.373472",
    "end": "2017-10-09 18:08:41.510105",
    "failed": false,
    "invocation": {
        "module_args": {
            "_raw_params": "oc new-app --template=postgresql-persistent -e MEMORY_LIMIT=512Mi -e NAMESPACE=openshift -e DATABASE_SERVICE_NAME=postgresql -e POSTGRESQL_USER=awx -e POSTGRESQL_PASSWORD=redhat -e POSTGRESQL_DATABASE=awx -e VOLUME_CAPACITY=5Gi -e POSTGRESQL_VERSION=9.5 -n awx",
            "_uses_shell": true,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "warn": true
        }
    },
    "rc": 0,
"start": "2017-10-09 18:08:41.136633",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "--> Deploying template \"openshift/postgresql-persistent\" to project awx\n\n     PostgreSQL (Persistent)\n     ---------\n     PostgreSQL database service, with persistent storage. For more information about using this template, including OpenShift considerations, see https://github.com/sclorg/postgresql-container/blob/master/9.5.\n\nNOTE: Scaling to more than one replica is not supported. You must have persistent volumes available in your cluster to use this template.\n\n     The following service(s) have been created in your project: postgresql.\n\n       Username: user472\n       Password: UQXoP2w6wqkiERMa\n  Database Name: sampledb\n Connection URL: postgresql://postgresql:5432/\n\nFor more information about using this template, including OpenShift considerations, see https://github.com/sclorg/postgresql-container/blob/master/9.5.\n\n     * With parameters:\n        * Memory Limit=512Mi\n        * Namespace=openshift\n        * Database Service Name=postgresql\n        * PostgreSQL Connection Username=user472 # generated\n        * PostgreSQL Connection Password=UQXoP2w6wqkiERMa # generated\n        * PostgreSQL Database Name=sampledb\n        * Volume Capacity=1Gi\n        * Version of PostgreSQL Image=9.5\n\n--> Creating resources ...\n    secret \"postgresql\" created\n    service \"postgresql\" created\n    persistentvolumeclaim \"postgresql\" created\n    deploymentconfig \"postgresql\" created\n--> Success\n    Run 'oc status' to view your app.",
    "stdout_lines": [
        "--> Deploying template \"openshift/postgresql-persistent\" to project awx",
        "",
        "     PostgreSQL (Persistent)",
        "     ---------",
        "     PostgreSQL database service, with persistent storage. For more information about using this template, including OpenShift considerations, see https://github.com/sclorg/postgresql-container/blob/master/9.5.",
        "",
        "NOTE: Scaling to more than one replica is not supported. You must have persistent volumes available in your cluster to use this template.",
        "",
        "     The following service(s) have been created in your project: postgresql.",
        "",
        "       Username: user472",
        "       Password: UQXoP2w6wqkiERMa",
        "  Database Name: sampledb",
        " Connection URL: postgresql://postgresql:5432/",
        "",
        "For more information about using this template, including OpenShift considerations, see https://github.com/sclorg/postgresql-container/blob/master/9.5.",
        "",
        "     * With parameters:",
        "        * Memory Limit=512Mi",
        "        * Namespace=openshift",
        "        * Database Service Name=postgresql",
        "        * PostgreSQL Connection Username=user472 # generated",
        "        * PostgreSQL Connection Password=UQXoP2w6wqkiERMa # generated",
        "        * PostgreSQL Database Name=sampledb",
        "        * Volume Capacity=1Gi",
        "        * Version of PostgreSQL Image=9.5",
        "",
        "--> Creating resources ...",
        "    secret \"postgresql\" created",
        "    service \"postgresql\" created",
        "    persistentvolumeclaim \"postgresql\" created",
        "    deploymentconfig \"postgresql\" created",
        "--> Success",
```

**Comment by matburt** [comment]
I've noticed this issue lately after having upgraded to ansible 2.4. I think I've got this taken care of in this branch:  https://github.com/ansible/awx/tree/scalable_clustering

Specifically with these changes to the startup task launcher:

https://github.com/ansible/awx/blob/scalable_clustering/installer/image_build/files/launch_awx_task.sh#L7-L9

Which should properly wait for the container to be available

This branch should merge within the next couple of weeks.

**Comment by ffirg** [comment]
Hi Matt

This doesn’t seem to work for me
I git cloned scalable_clustering and tried that. Doesn’t create the awx database and therefore front end fails (internal server error)

**Comment by matburt** [comment]
How did you install that branch? Remember you can't have it pull the dockerhub images because those images are built against the `devel` branch.
