### ISSUE TITLE
Cleanup Job Days cannot be changed from 30

### ISSUE THREAD

**Issue by giordyb** [ansible/awx#369]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When running a clean up job the UI prompts for the number of days with a default of 30, if I change the number of days to anything else the job still runs with "days: 30" in the Extra Variables
##### STEPS TO REPRODUCE

* go into management jobs and run cleanup activity stream or cleanup job details
* change the number of days to anything from 30 

##### EXPECTED RESULTS

job keeps the last N days 

##### ACTUAL RESULTS

Job keeps the last 30 days

**Comment by jaredevantabor** [comment]
this console error is almost certainly related to this issue: 
![image](https://user-images.githubusercontent.com/7010629/31278083-ad4ed2cc-aa71-11e7-9cce-01ddc8704355.png)

```
angular.js:12808 TypeError: Cannot read property '$setPristine' of undefined
    at onOpen (http://localhost:3000/static/js/app.js:90814:44)
    at HTMLDivElement.open (http://localhost:3000/static/js/app.js:71245:21)
    at $.(anonymous function).(anonymous function)._trigger (http://localhost:3000/static/js/vendor.js:56886:13)
    at $.(anonymous function).(anonymous function).open (http://localhost:3000/static/js/vendor.js:65951:8)
    at $.(anonymous function).(anonymous function).open (http://localhost:3000/static/js/vendor.js:56502:25)
    at HTMLDivElement.<anonymous> (http://localhost:3000/static/js/vendor.js:56594:39)
    at Function.each (http://localhost:3000/static/js/vendor.js:15961:19)
    at jQuery.fn.init.each (http://localhost:3000/static/js/vendor.js:15733:17)
    at jQuery.fn.init.$.fn.(anonymous function) [as dialog] (http://localhost:3000/static/js/vendor.js:56584:9)
    at http://localhost:3000/static/js/app.js:90855:35
```

**Comment by mabashian** [comment]
I was definitely able to reproduce this but the fix wasn't as forthcoming as I hoped it'd be.  I'm going to have to put this down for the time being.  There's something odd going on with the `scope` of the modal.  `prompt_for_days_form` is expected to be on scope but currently is not which is leading to the error.  I'm not sure if this has something to do with the re-work of `index.html` or the layout changes (?).  More investigation may be needed.  It's also possible that the easiest way to fix this might not be to keep the previous pattern intact but to insert/open the modal another way.

**Comment by one1zero1one** [comment]
For those ending up here without UI skills but in need for a quick cleanup run (with less than 30 days - e.g. 10), 

```
export AWXHOST=localhost
curl  -f -k -H 'Content-Type: application/json' -XPOST \
    --user admin:password \
    --data '{"extra_vars":"{\"days\":10}"}' \
    https://$AWXHOST/api/v2/system_job_templates/1/launch/
```

**Comment by jaredevantabor** [comment]
this is fixed in devel now.
