### ISSUE TITLE
Microsoft Azure Resource Manager - Inventory bug

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#3690]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Microsoft Azure Resource Manager inventory source cannot sync. 
This has worked recently.

##### ENVIRONMENT
* Ansible version:  2.7.10
* Operating System: CentOS

##### STEPS TO REPRODUCE

Create Microsoft Azure Resource Manager credential.
Fill out subscription ID, username and password.
Create Microsoft Azure Resource Manager inventory source.
Select previous created credential. Start sync process.

##### EXPECTED RESULTS

 Microsoft Azure Resource Manager inventory should sync.

##### ACTUAL RESULTS

`
    3.193 INFO     Updating inventory 8: Azure Test Inventory
    3.222 DEBUG    Using system install of ansible-inventory CLI: /usr/bin/ansible-inventory
    3.222 INFO     Reading Ansible inventory source: /usr/lib/python2.7/site-packages/awx/plugins/inventory/azure_rm.py
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==2.1.0', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 150, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 994, in handle
    self.is_custom)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 245, in load_inventory_source
    is_custom=is_custom).load()
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 180, in load
    data = self.command_to_json(base_args + ['--list'])
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 163, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:

stderr:
 [WARNING]:  * Failed to parse /usr/lib/python2.7/site-
packages/awx/plugins/inventory/azure_rm.py with script plugin: Inventory script
(/usr/lib/python2.7/site-packages/awx/plugins/inventory/azure_rm.py) had an
execution error: No handlers could be found for logger
"msrestazure.azure_active_directory" Traceback (most recent call last):   File
"/usr/lib/python2.7/site-packages/awx/plugins/inventory/azure_rm.py", line 973,
in <module>     main()   File "/usr/lib/python2.7/site-
packages/awx/plugins/inventory/azure_rm.py", line 969, in main
AzureInventory()   File "/usr/lib/python2.7/site-
packages/awx/plugins/inventory/azure_rm.py", line 603, in __init__
self.get_inventory()   File "/usr/lib/python2.7/site-
packages/awx/plugins/inventory/azure_rm.py", line 669, in get_inventory
self._load_machines(selected_machines)   File "/usr/lib/python2.7/site-
packages/awx/plugins/inventory/azure_rm.py", line 744, in _load_machines
interface_reference['networkInterfaces'])   File
"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/mgmt/network/v2017
_06_01/operations/network_interfaces_operations.py", line 166, in get
response = self._client.send(request, header_parameters, **operation_config)
File "/var/lib/awx/venv/ansible/lib/python2.7/site-
packages/msrest/service_client.py", line 290, in send
raise_with_traceback(ClientRequestError, msg, err)   File
"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/msrest/exceptions.py",
line 48, in raise_with_traceback     raise error
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError:
HTTPSConnectionPool(host='management.azure.com', port=443): Max retries
exceeded with url: /subscriptions/HIDE_SUBSCRIPTION_ID/resourceGroups/test-linux-
master/providers/Microsoft.Network/networkInterfaces/test-linux-master01?api-
version=2017-06-01 (Caused by ResponseError('too many 500 error responses',))

 [WARNING]: Unable to parse /usr/lib/python2.7/site-
packages/awx/plugins/inventory/azure_rm.py as an inventory source

ERROR! No inventory was parsed, please check your configuration and options.
`

##### ADDITIONAL INFORMATION

I've reset the used azure credential password.
I've changed the user. Both users are owners.
I've tried with different subscriptions.
Upgraded from ansible version 2.7.4 to 2.7.10 but error persists.

**Comment by nicolaibaralmueller** [comment]
This was fixed by updating ansible[azure] on the web task node in docker.
