### ISSUE TITLE
AWX 3.0.1 stopped showing job outputs

### ISSUE THREAD

**Issue by larrybg** [ansible/awx#3761]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

We have AWX 3.0.1 running in the Docker containers. The database is installed on a separate server. Everything worked just fine for a month or so. Starting a few days ago I've noticed job outputs are missing and when I download output, files are 0 bytes.

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker on linux
* Ansible version:  2.7.7
* Operating System: Mac
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Execute the job.

##### EXPECTED RESULTS
Running job produces an output that should be shown in the UI output window

##### ACTUAL RESULTS
Nothing shown

##### ADDITIONAL INFORMATION
<img width="1136" alt="Screen Shot 2019-04-24 at 11 11 41 AM" src="https://user-images.githubusercontent.com/20246246/56671015-d876f600-6681-11e9-8a5c-d38dbf4e3947.png">

**Comment by ryanpetrello** [comment]
Hey @larrybg,

Please give this a try on the latest version of awx (4.0.0) and reopen this if you're still encountering it - we've fixed a number of issues related to this in the past few months.  I suspect you might be running into this one:

https://github.com/ansible/awx/pull/3424

**Comment by extjperttula** [comment]
Facing exactly the same issue. Started immediately after the date change from 21st May to 22nd May. Re-installation surely would fix this but  something else would be nice to try first in live system.

**Comment by MathijsVanWilligen** [comment]
Same issue here with awx 4.0.0 on kubernetes, not showing job output and no ouput in https://awx/api/v2/jobs/{ job_id }/job_events/.
Also a reboot or re-installation won't fix this.

**Comment by ryanpetrello** [comment]
@MathijsVanWilligen @extjperttula generally if there's *no* output and *no* events, it suggests that the callback receiver process isn't running, or is encountering errors.  Do you see any errors or tracebacks in your container logs?

**Comment by sdktr** [comment]
@ryanpetrello we (@MathijsVanWilligen and I) noticed that the events are shown eventually, after about 36 hours. Analysing the database top queries reveales what seems like a background proces that your're referring to as well that moves logs from some queue to 'main_jobevent' psql table.

Can you point us in the right direction to understand this proces? We seem to have some kind of performance issue in this log handler proces? See DB stats:
![image](https://user-images.githubusercontent.com/19833687/58285323-d2715380-7dac-11e9-884f-e7acb4f0e642.png)

**Comment by sdktr** [comment]
Additionally: we encountered this since using AWX 4.0.0. We've not upgraded, but only migrated the config of the old 2.1.0 based installation so we didn't carry over the old job logs.
We have however increased the amount of tasks that run periodically so sizing (of the DB/k8s env) could be off. Some help into understanding how events _should_ be handled/archived is still appreciated though. 

Loginfo from Celery container below; besides these logs the regular stdout from the ansible runs is displayed in the celery container as well.

`2019-05-23 22:05:46,296 DEBUG    awx.main.tasks Starting periodic scheduler
2019-05-23 22:05:46,302 DEBUG    awx.main.tasks Last scheduler run was: 2019-05-23 22:05:16.442189+00:00
2019-05-23 22:05:46,347 DEBUG    awx.main.dispatch task b7cfbe82-5a91-4ab0-8d65-a8f2971d0201 is finished
2019-05-23 22:05:49,156 WARNING  awx.main.commands.run_callback_receiver could not write to queue 2
2019-05-23 22:05:49,156 WARNING  awx.main.commands.run_callback_receiver could not write to queue 2
2019-05-23 22:05:49,156 WARNING  awx.main.commands.run_callback_receiver detail: Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/pool.py", line 263, in write
    self.workers[queue_actual].put(body)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/pool.py", line 81, in put
    self.calculate_managed_tasks()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/pool.py", line 127, in calculate_managed_tasks
    del self.managed_tasks[uuid]
KeyError: '0a590273-7433-4713-b51e-b612499c6f2e'
 2019-05-23 22:05:49,156 WARNING  awx.main.commands.run_callback_receiver detail: Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/pool.py", line 263, in write
    self.workers[queue_actual].put(body)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/pool.py", line 81, in put
    self.calculate_managed_tasks()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/pool.py", line 127, in calculate_managed_tasks
    del self.managed_tasks[uuid]
KeyError: '0a590273-7433-4713-b51e-b612499c6f2e'
 2019-05-23 22:05:55,546 DEBUG    awx.main.dispatch publish awx.main.scheduler.tasks.run_task_manager(10d1d172-da07-4d31-a2fc-2d5392a6ffe2, queue=awx_private_queue)
[2019-05-23 22:05:55,546: DEBUG/Process-1] publish awx.main.scheduler.tasks.run_task_manager(10d1d172-da07-4d31-a2fc-2d5392a6ffe2, queue=awx_private_queue)
2019-05-23 22:05:55,567 DEBUG    awx.main.dispatch delivered 10d1d172-da07-4d31-a2fc-2d5392a6ffe2 to worker[7032] qsize 0
2019-05-23 22:05:55,569 DEBUG    awx.main.dispatch task 10d1d172-da07-4d31-a2fc-2d5392a6ffe2 starting awx.main.scheduler.tasks.run_task_manager(*[])
2019-05-23 22:05:55,569 DEBUG    awx.main.scheduler Running Tower task manager.
2019-05-23 22:05:56,147 DEBUG    awx.main.scheduler Starting Scheduler
2019-05-23 22:05:56,230 DEBUG    awx.main.dispatch task 10d1d172-da07-4d31-a2fc-2d5392a6ffe2 is finished
RESULT 2
OKREADY
2019-05-23 22:06:09,341 WARNING  awx.main.commands.run_callback_receiver could not write to queue 2
2019-05-23 22:06:09,341 WARNING  awx.main.commands.run_callback_receiver could not write to queue 2
2019-05-23 22:06:09,341 WARNING  awx.main.commands.run_callback_receiver detail: Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/pool.py", line 263, in write
    self.workers[queue_actual].put(body)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/pool.py", line 81, in put
    self.calculate_managed_tasks()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/pool.py", line 127, in calculate_managed_tasks
    del self.managed_tasks[uuid]
KeyError: 'be59548e-db50-45f9-2109-000000000082'
 2019-05-23 22:06:09,341 WARNING  awx.main.commands.run_callback_receiver detail: Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/pool.py", line 263, in write
    self.workers[queue_actual].put(body)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/pool.py", line 81, in put
    self.calculate_managed_tasks()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/pool.py", line 127, in calculate_managed_tasks
    del self.managed_tasks[uuid]
KeyError: 'be59548e-db50-45f9-2109-000000000082'`

**Comment by larrybg** [comment]
Hi @ryanpetrello !
And here we go again... Version 4.0.0.0 running about a month or so and quitting to show jobs outputs. Looks like this bug wasn't fixed. I'm opening new issue...
<img width="1215" alt="Screen Shot 2019-05-24 at 12 42 12 PM" src="https://user-images.githubusercontent.com/20246246/58343703-b6f46000-7e21-11e9-83f3-66cdf782d87e.png">
