### ISSUE TITLE
Upgrade-in-progress middleware stopped working

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#3821]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The page saying that AWX is upgrading is not showing when AWX is not upgrade. 500 error instead.

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  N/A
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

```
awx-manage migrate main <current migration number minus 1>
```

This assumes that the last migration is reversible.

Then visit some page.

##### EXPECTED RESULTS

A fancy page telling me that AWX is migrating

##### ACTUAL RESULTS

server error

```
awx_1        | 13:53:33 uwsgi.1      | 2019-05-03 13:53:33,348 ERROR    django.request Internal Server Error: /favicon.ico/
awx_1        | 13:53:33 uwsgi.1      | Traceback (most recent call last):
awx_1        | 13:53:33 uwsgi.1      |   File "/venv/awx/lib64/python3.6/site-packages/django/core/handlers/base.py", line 131, in get_response
awx_1        | 13:53:33 uwsgi.1      |     response = middleware_method(request, response)
awx_1        | 13:53:33 uwsgi.1      |   File "./awx/main/middleware.py", line 130, in process_response
awx_1        | 13:53:33 uwsgi.1      |     if request.session and not request.session.is_empty() and not should_skip:
awx_1        | 13:53:33 uwsgi.1      | AttributeError: 'WSGIRequest' object has no attribute 'session'

```

**Comment by AlanCoding** [comment]
Link https://github.com/ansible/awx/pull/3510
