### ISSUE TITLE
Random failuer with k8s_facts module when job template includes inventory with multiple hosts

### ISSUE THREAD

**Issue by geauxvirtual** [ansible/awx#3834]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When a job template has an inventory with multiple servers, a task using the k8s_facts can fail with error message saying `ValueError: Unterminated string`

##### ENVIRONMENT
* AWX version: 3.0.0
* AWX install method: kubernetes
* Ansible version:  2.7.6

##### STEPS TO REPRODUCE

Playbook that contains a task using the k8s_facts module

```
- name: Get Vault URL
  k8s_facts:
    api_version: v1
    kind: Service
    namespace: default
    label_selectors:
      - app = vault
  register: vault_svc
```

An inventory with more than one server.
Job slicing set to 1.

##### EXPECTED RESULTS

Successful execution of the task.

##### ACTUAL RESULTS

```
TASK [common/vault : Get Vault URL] ********************************************
ok: [6TV9CM2]
ok: [6TW1XM2]
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: Unterminated string starting at: line 1 column 28665 (char 28664)
fatal: [13Y8XM2]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1556919469.94-43869933857434/AnsiballZ_k8s_facts.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1556919469.94-43869933857434/AnsiballZ_k8s_facts.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1556919469.94-43869933857434/AnsiballZ_k8s_facts.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_k8s_facts_payload_KYCj__/__main__.py\", line 176, in <module>\n  File \"/tmp/ansible_k8s_facts_payload_KYCj__/__main__.py\", line 172, in main\n  File \"/tmp/ansible_k8s_facts_payload_KYCj__/__main__.p…
ok: [13Y9XM2]
```

##### ADDITIONAL INFORMATION

I have created a simple playbook in the awx-task container, along with an inventory of 4 hosts. Running the playbook on the cli of the task container, I've yet to see the same failure as I see occur in AWX frequently.

When I split the job using job slicing to match the number of hosts, I do not see the same issue.

**Comment by AlanCoding** [comment]
Could you click on the event and get the full details in the fatal task?

**Comment by geauxvirtual** [comment]
```json
{
	"_ansible_parsed": false,
	"exception": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1556919469.94-43869933857434/AnsiballZ_k8s_facts.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1556919469.94-43869933857434/AnsiballZ_k8s_facts.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1556919469.94-43869933857434/AnsiballZ_k8s_facts.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_k8s_facts_payload_KYCj__/__main__.py\", line 176, in <module>\n  File \"/tmp/ansible_k8s_facts_payload_KYCj__/__main__.py\", line 172, in main\n  File \"/tmp/ansible_k8s_facts_payload_KYCj__/__main__.py\", line 145, in execute_module\n  File \"/tmp/ansible_k8s_facts_payload_KYCj__/ansible_k8s_facts_payload.zip/ansible/module_utils/k8s/common.py\", line 174, in get_api_client\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 103, in __init__\n    self.__init_cache()\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 111, in __init_cache\n    self.__cache = json.load(f, cls=cache_decoder(self))\n  File \"/usr/lib64/python2.7/json/__init__.py\", line 290, in load\n    **kw)\n  File \"/usr/lib64/python2.7/json/__init__.py\", line 351, in loads\n    return cls(encoding=encoding, **kw).decode(s)\n  File \"/usr/lib64/python2.7/json/decoder.py\", line 366, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib64/python2.7/json/decoder.py\", line 382, in raw_decode\n    obj, end = self.scan_once(s, idx)\nValueError: Unterminated string starting at: line 1 column 28665 (char 28664)\n",
	"_ansible_no_log": false,
	"module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1556919469.94-43869933857434/AnsiballZ_k8s_facts.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1556919469.94-43869933857434/AnsiballZ_k8s_facts.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1556919469.94-43869933857434/AnsiballZ_k8s_facts.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_k8s_facts_payload_KYCj__/__main__.py\", line 176, in <module>\n  File \"/tmp/ansible_k8s_facts_payload_KYCj__/__main__.py\", line 172, in main\n  File \"/tmp/ansible_k8s_facts_payload_KYCj__/__main__.py\", line 145, in execute_module\n  File \"/tmp/ansible_k8s_facts_payload_KYCj__/ansible_k8s_facts_payload.zip/ansible/module_utils/k8s/common.py\", line 174, in get_api_client\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 103, in __init__\n    self.__init_cache()\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 111, in __init_cache\n    self.__cache = json.load(f, cls=cache_decoder(self))\n  File \"/usr/lib64/python2.7/json/__init__.py\", line 290, in load\n    **kw)\n  File \"/usr/lib64/python2.7/json/__init__.py\", line 351, in loads\n    return cls(encoding=encoding, **kw).decode(s)\n  File \"/usr/lib64/python2.7/json/decoder.py\", line 366, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib64/python2.7/json/decoder.py\", line 382, in raw_decode\n    obj, end = self.scan_once(s, idx)\nValueError: Unterminated string starting at: line 1 column 28665 (char 28664)\n",
	"changed": false,
	"module_stdout": "",
	"rc": 1,
	"msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
}
```

**Comment by AlanCoding** [comment]
This might be a valid issue to file for

https://github.com/ansible/ansible/issues

or

https://github.com/openshift/openshift-restclient-python/issues

Unless you know of something that clearly sets apart successful CLI use from use in AWX.

**Comment by ryanpetrello** [comment]
Agreed, this looks to me like an issue in the openshift client library being used by Ansible, not AWX:

```python
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1556919469.94-43869933857434/AnsiballZ_k8s_facts.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1556919469.94-43869933857434/AnsiballZ_k8s_facts.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1556919469.94-43869933857434/AnsiballZ_k8s_facts.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_k8s_facts_payload_KYCj__/__main__.py", line 176, in <module>
  File "/tmp/ansible_k8s_facts_payload_KYCj__/__main__.py", line 172, in main
  File "/tmp/ansible_k8s_facts_payload_KYCj__/__main__.py", line 145, in execute_module
  File "/tmp/ansible_k8s_facts_payload_KYCj__/ansible_k8s_facts_payload.zip/ansible/module_utils/k8s/common.py", line 174, in get_api_client
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/openshift/dynamic/client.py", line 103, in __init__
    self.__init_cache()
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/openshift/dynamic/client.py", line 111, in __init_cache
    self.__cache = json.load(f, cls=cache_decoder(self))
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 28665 (char 28664)
```

**Comment by geauxvirtual** [comment]
Again, I can run this same module from Ansible on the CLI of the AWX task container, and it does not fail. I ONLY see this error when running this module in AWX.

If I could duplicate this error outside of AWX, I would open the issue with ansible or openshift, but so far, the issue is only seen within AWX.

**Comment by geauxvirtual** [comment]
> Unless you know of something that clearly sets apart successful CLI use from use in AWX.

What sets apart operation in AWX from the cli? 
Why would this fail in AWX but succeed on the CLI? 
Why does the issue not occur when job slicing matches the number of hosts in the inventory?

**Comment by AlanCoding** [comment]
From what you're saying about the job slicing, I get that it works with 1 host, doesn't work with more hosts.

I am curious if your job template has the fact cache turned on. That's only of the only connections I could draw to the host count here.

The only surface area is the content being fed in the library's `configuration` (aside from non-obvious places it might look). If you could hack far enough to find out what is coming in for those values, that might give a final triage to your problem.

https://github.com/ansible/ansible/blob/v2.7.6/lib/ansible/module_utils/k8s/common.py#L174

**Comment by geauxvirtual** [comment]
Correct. If I run the job with one job slice and 3 hosts, the job fails. When I run the job with 3 job slices and 3 hosts, the job succeeds.

Fact cache is not enabled on the job templates.

**Comment by AlanCoding** [comment]
So I thought I would try to poke at the client library to see where these guys come up:

```
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/openshift/dynamic/client.py", line 103, in __init__
    self.__init_cache()
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/openshift/dynamic/client.py", line 111, in __init_cache
    self.__cache = json.load(f, cls=cache_decoder(self))
```

It seems I found it here:

https://github.com/openshift/openshift-restclient-python/blob/v0.8.4/openshift/dynamic/client.py#L111

Release 0.8.4 is from Jan 11. Not that long ago, but if you scroll through all subsequent versions, all the code around this cache processing experiences a huge amount of churn, which is kind of a big red flag right there.

I would firstly try upgrading to 0.8.8. If that doesn't work, then I would try upgrading Ansible, because the way the module utils gathers parameters in these cloud modules can also undergo churn.
