### ISSUE TITLE
LDAP - Unable to  write ldap filter or  bind DN  with not english names.

### ISSUE THREAD

**Issue by iyurev** [ansible/awx#391]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Unable to  write ldap filter or  bind DN  with not english names, for example:
CN=BindLdapUser,OU=AWXAdmins,OU=**Администраторы**,DC=somecompany,DC=com

##### ENVIRONMENT

* AWX version: 1.0.0.553
* AWX install method:  docker on linux
* Ansible version:  2.3.2.0

##### STEPS TO REPRODUCE

1. In UI open:  **Settings** -> **AUTHENTICATION** -> select **LDAP**
2. Insert in the field LDAP BIND DN or LDAP REQUIRE GROUP something like this:
    `CN=BindLdapUser,OU=AWXAdmins,OU=Администраторы,DC=somecompany,DC=com`
3.  Try click **SAVE** button.

##### EXPECTED RESULTS
Saved settings and worked LDAP authentication.

##### ACTUAL RESULTS
Error in message box:
`Failed to save settings. Returned status: undefined . A server error has occurred`

##### ADDITIONAL INFORMATION
If DN or LDAP  composed  only from english letters settings normally save.

Below piece  log of java console from my browser:

```
vendor.a4f215857035eea92e41.js:29 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ vendor.a4f215857035eea92e41.js:29
vendor.a4f215857035eea92e41.js:436 TypeError: document.on is not a function
    at atSideNavLink (http://some_awx_inst/static/js/app.4099ea5a2541e18632df.js:403:1526394)
    at http://some_awx_inst/static/js/vendor.a4f215857035eea92e41.js:436:70281
    at invokeLinkFn (http://some_awx_inst/static/js/vendor.a4f215857035eea92e41.js:436:70399)
    at nodeLinkFn (http://some_awx_inst/static/js/vendor.a4f215857035eea92e41.js:436:55720)
    at http://some_awx_inst/static/js/vendor.a4f215857035eea92e41.js:436:65511
    at processQueue (http://some_awx_inst/static/js/vendor.a4f215857035eea92e41.js:436:117543)
    at http://some_awx_inst/static/js/vendor.a4f215857035eea92e41.js:436:117810
    at Scope.$eval (http://some_awx_inst/static/js/vendor.a4f215857035eea92e41.js:436:130738)
    at Scope.$digest (http://some_awx_inst/static/js/vendor.a5f215857035eea92e41.js:436:128538)
    at Scope.$apply (http://some_awx_inst/static/js/vendor.a4f215857035eea92e41.js:436:131164) <div class="at-Layout-side ng-isolate-scope" ng-class="{'at-Layout-side--expanded': vm.isExpanded &amp;&amp; layoutVm.isLoggedIn}" ng-show="layoutVm.isLoggedIn &amp;&amp; !layoutVm.licenseIsMissing">
(anonymous) @ vendor.a4f215857035eea92e41.js:436
/static/languages/ru_RU.json Failed to load resource: the server responded with a status of 404 (Not Found)
vendor.a4f215857035eea92e41.js:436 TypeError: Cannot set property 'loggedIn' of undefined
    at app.4099ea5a2541e18632df.js:403
    at processQueue (vendor.a4f215857035eea92e41.js:436)
    at vendor.a4f215857035eea92e41.js:436
    at Scope.$eval (vendor.a4f215857035eea92e41.js:436)
    at Scope.$digest (vendor.a4f215857035eea92e41.js:436)
    at Scope.$apply (vendor.a4f215857035eea92e41.js:436)
    at done (vendor.a4f215857035eea92e41.js:436)
    at completeRequest (vendor.a4f215857035eea92e41.js:436)
    at XMLHttpRequest.xhr.onload (vendor.a4f215857035eea92e41.js:436)
(anonymous) @ vendor.a4f215857035eea92e41.js:436
/#/login:1 This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
app.4099ea5a2541e18632df.js:403 promise resolved, and readyState: undefined
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 Socket deleted: undefined
app.4099ea5a2541e18632df.js:403 promise resolved, and readyState: undefined
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
app.4099ea5a2541e18632df.js:403 socket readyState at emit: 1
/api/v2/settings/all/ Failed to load resource: the server responded with a status of 400 (BAD REQUEST)
/api/v2/settings/all/ Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
vendor.a4f215857035eea92e41.js:436 PATCH http://some_awx_inst/api/v2/settings/all/ 500 (INTERNAL SERVER ERROR)
(anonymous) @ vendor.a4f215857035eea92e41.js:436
sendReq @ vendor.a4f215857035eea92e41.js:436
serverRequest @ vendor.a4f215857035eea92e41.js:436
processQueue @ vendor.a4f215857035eea92e41.js:436
(anonymous) @ vendor.a4f215857035eea92e41.js:436
$eval @ vendor.a4f215857035eea92e41.js:436
$digest @ vendor.a4f215857035eea92e41.js:436
$apply @ vendor.a4f215857035eea92e41.js:436
(anonymous) @ vendor.a4f215857035eea92e41.js:436
dispatch @ vendor.a4f215857035eea92e41.js:29
elemData.handle @ vendor.a4f215857035eea92e41.js:29

```

**Comment by matburt** [comment]
`A server error has occurred` `INTERNAL SERVER ERROR`

Please provide the AWX error emitted in the docker service logs when this occurs.

**Comment by iyurev** [comment]
This is output **awx_web** container   when I click save button in UI:

```
10.7.99.133 - - [11/Oct/2017:08:12:30 +0000] "GET /static/images/ui-bg_flat_50_ffffff_40x100.png HTTP/1.1" 304 0 "http://some_awx_inst/static/css/vendor.a4f215857035eea92e41.css" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "-"
[pid: 27|app: 0|req: 208/1687] 10.7.99.133 () {46 vars in 2095 bytes} [Wed Oct 11 08:12:32 2017] GET /api/v2/settings/all/ => generated 12641 bytes in 150 msecs (HTTP/1.1 200) 7 headers in 222 bytes (1 switches on core 0)
10.7.99.133 - - [11/Oct/2017:08:12:32 +0000] "GET /api/v2/settings/all/ HTTP/1.1" 200 12669 "http://some_awx_inst/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "-"
2017-10-11 08:14:04,826 ERROR    django.request Internal Server Error: /api/v2/settings/all/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 246, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 262, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 675, in partial_update
    return super(RetrieveUpdateAPIView, self).partial_update(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/mixins.py", line 78, in partial_update
    return self.update(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 671, in update
    return super(RetrieveUpdateAPIView, self).update(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/mixins.py", line 69, in update
    serializer.is_valid(raise_exception=True)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/serializers.py", line 213, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/serializers.py", line 407, in run_validation
    value = self.to_internal_value(data)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/serializers.py", line 437, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/fields.py", line 696, in run_validation
    return super(CharField, self).run_validation(data)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/fields.py", line 483, in run_validation
    self.run_validators(value)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/fields.py", line 497, in run_validators
    validator(value)
  File "/usr/lib/python2.7/site-packages/awx/sso/validators.py", line 37, in validate_ldap_bind_dn
    validate_ldap_dn(value)
  File "/usr/lib/python2.7/site-packages/awx/sso/validators.py", line 25, in validate_ldap_dn
    ldap.dn.str2dn(dn_value)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/ldap/dn.py", line 53, in str2dn
    return ldap.functions._ldap_function_call(None,_ldap.str2dn,dn,flags)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/ldap/functions.py", line 66, in _ldap_function_call
    result = func(*args,**kwargs)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 35-43: ordinal not in range(128)
[pid: 29|app: 0|req: 682/1688] 10.7.99.133 () {52 vars in 2240 bytes} [Wed Oct 11 08:14:04 2017] PATCH /api/v2/settings/all/ => generated 41 bytes in 194 msecs (HTTP/1.1 500) 4 headers in 157 bytes (1 switches on core 0)
10.7.99.133 - - [11/Oct/2017:08:14:04 +0000] "PATCH /api/v2/settings/all/ HTTP/1.1" 500 52 "http://some_awx_inst/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "-"

```

 Looks like unicode truble??
`UnicodeEncodeError: 'ascii' codec can't encode characters in position 35-43: ordinal not in range(128)`

**Comment by matburt** [comment]
This looks like an issue with python-ldap parsing your string. It's possible we could work around this by forcing an encoding. Someone will need to dig into that more.
