### ISSUE TITLE
Failed to parse dynamic inventory script

### ISSUE THREAD

**Issue by gforster** [ansible/awx#3964]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Failed to parse a dynamic inventory script. Script works fine in Ansible Engine/CLI. l

##### ENVIRONMENT
* AWX version: Tower 3.4.3
* AWX install method: tower install
* Ansible version:  2.7.9
* Operating System: RHEL 7
* Web Browser: firefox

##### STEPS TO REPRODUCE

Adding inventory to point to custom dynamic script. I have installed subprocess via pip per https://docs.ansible.com/ansible-tower/latest/html/upgrade-migration-guide/virtualenv.html 

##### EXPECTED RESULTS

inventory parsed and added

##### ACTUAL RESULTS

failure

##### ADDITIONAL INFORMATION
```
    1.471 INFO     Updating inventory 22: my inventory
    1.490 INFO     Reading Ansible inventory source: /var/lib/awx/projects/_66__my_playbooks/ansible-inventory/my-inventory.py
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==3.4.3', 'console_scripts', 'awx-manage')()
  File "/lib/python2.7/site-packages/awx/__init__.py", line 150, in manage
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 1024, in handle
  File "/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 245, in load_inventory_source
  File "/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 180, in load
  File "/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 163, in command_to_json
RuntimeError: ansible-inventory failed (rc=1) with stdout:

stderr:
 [WARNING]:  * Failed to parse /var/lib/awx/projects/_66__my_playbooks
/ansible-inventory/my-inventory.py with script plugin: Inventory script
(/var/lib/awx/projects/_66__my_playbooks/ansible-inventory/my-inventory.py)
had an execution error: Traceback (most recent call last):   File
"/var/lib/awx/projects/_66__my_playbooks/ansible-inventory/my-inventory.py",
line 126, in <module>     stderr=subprocess.STDOUT, shell=False)   File
"/usr/lib64/python2.7/subprocess.py", line 568, in check_output     process =
Popen(stdout=PIPE, *popenargs, **kwargs)   File
"/usr/lib64/python2.7/subprocess.py", line 711, in __init__     errread,
errwrite)   File "/usr/lib64/python2.7/subprocess.py", line 1327, in
_execute_child     raise child_exception OSError: [Errno 2] No such file or
directory

 [WARNING]:  * Failed to parse /var/lib/awx/projects/_66__my_playbooks
/ansible-inventory/my-inventory.py with ini plugin:
/var/lib/awx/projects/_66__my_playbooks/ansible-inventory/my-inventory.py:3:
Error parsing host definition 'DOCUMENTATION = '''': No closing quotation

 [WARNING]: Unable to parse /var/lib/awx/projects/_66__my_playbooks/ansible-
inventory/my-inventory.py as an inventory source

ERROR! No inventory was parsed, please check your configuration and options.
```
**The custom script:**
```python
#!/usr/bin/env python

import os
import json
import argparse
import subprocess

comment_char = '#'
server_char = ':'
project_root = os.path.dirname(os.path.abspath(__file__))

parser = argparse.ArgumentParser(
  description='Produce an Ansible Dynamic Inventory file based on nodes.stz'
)
parser.add_argument(
  '--list',
  action='store_true',
  help='Get all Ansible inventory variables about all servers',
)
parser.add_argument(
  '--host',
  action='store',
  help='Get all Ansible inventory variables about a specific server',
)
args = parser.parse_args()

if "MY_ARGS" in os.environ:
    MY_ARGS = os.environ['MY_ARGS']

stderr = ''
try:
    MY_ARGS
except:
    output = subprocess.check_output(
            ["asset_list", "-A"],
            stderr=subprocess.STDOUT, shell=False)
else:
    output = subprocess.check_output(
            ["asset_list", "-a"] + str(MY_ARGS).split(),
            stderr=subprocess.STDOUT, shell=False)
 
result = {
  'all': {
    'children': [
      'ungrouped'
    ],
    'hosts': [],
    'vars': {},
   },
  'ungrouped': {
    'children': [
    ]
  },
  '_meta': {
    'hostvars': {}
   }
}
server = ''
for raw_line in output.split('\n'):
    line = raw_line.strip()
    if len(line) > 0 and not line.startswith(comment_char):
        if line.endswith(server_char):
            server = line[:-1]
            result['all']['hosts'].append(server)
            result['_meta']['hostvars'][server] = {}
        else:
            raw_key, raw_value = line.split('=', 1)
            key = raw_key.strip()
            value = raw_value.strip()
            result['_meta']['hostvars'][server][key] = value
            if key == 'ansible_groups':
                for group in value.split(","):
                    if group not in result.keys():
                        result[group] = {'hosts': [], 'vars': {}}
                    result[group]['hosts'].append(server)
            if key == 'bucket':
                for group in value.split(","):
                    group = 'bucket_' + group.lower().replace(" ", "_")
                    if group not in result.keys():
                        result[group] = {'hosts': [], 'vars': {}}
                    result[group]['hosts'].append(server)
            if key == 'classification':
                for group in value.split(","):
                    group = 'ni_classification_' + group.lower().replace(" ", "_")
                    if group not in result.keys():
                        result[group] = {'hosts': [], 'vars': {}}
                    result[group]['hosts'].append(server)
            if key == 'tier':
                for group in value.split(","):
                    group = 'tier_' + group.lower().replace(" ", "_")
                    if group not in result.keys():
                        result[group] = {'hosts': [], 'vars': {}}
                    result[group]['hosts'].append(server)
            if key == 'platform':
                for group in value.split(","):
                    group = 'platform_' + group.lower().replace(" ", "_")
                    if group not in result.keys():
                        result[group] = {'hosts': [], 'vars': {}}
                    result[group]['hosts'].append(server)
            if key == 'production':
                for group in value.split(","):
                    group = 'production_' + group.lower().replace(" ", "_")
                    if group not in result.keys():
                        result[group] = {'hosts': [], 'vars': {}}
                    result[group]['hosts'].append(server)
            if key == 'remedy_os':
                for group in value.split(","):
                    group = 'remedy_os_' + group.lower().replace(" ", "_")
                    if group not in result.keys():
                        result[group] = {'hosts': [], 'vars': {}}
                    result[group]['hosts'].append(server)
            if key == 'app_owner':
                for group in value.split(","):
                    group = 'app_owner_' + group.lower().replace(" ", "_")
                    if group not in result.keys():
                        result[group] = {'hosts': [], 'vars': {}}
                    result[group]['hosts'].append(server)
            if key == 'os':
                for group in value.split(","):
                    group = 'os_' + group.lower().replace(" ", "_")
                    if group not in result.keys():
                        result[group] = {'hosts': [], 'vars': {}}
                    result[group]['hosts'].append(server)
            if key == 'remedy_os':
                for group in value.split(","):
                    group = 'remedy_os_' + group.lower().replace(" ", "_")
                    if group not in result.keys():
                        result[group] = {'hosts': [], 'vars': {}}
            if key == 'remedy_ostype':
                for group in value.split(","):
                    group = 'remedy_ostype_' + group.lower().replace(" ", "_")
                    if group not in result.keys():
                        result[group] = {'hosts': [], 'vars': {}}
                    result[group]['hosts'].append(server)
                    result[group]['hosts'].append(server)
            if key == 'status':
                for group in value.split(","):
                    group = 'status_' + group.lower().replace(" ", "_")
                    if group not in result.keys():
                        result[group] = {'hosts': [], 'vars': {}}
                    result[group]['hosts'].append(server)
                    result[group]['hosts'].append(server)

if args.host is None:
    args.list = True


if args.list:
    print(json.dumps(result))
else:
    server = result['_meta']['hostvars'].get(args.host)
    if server is None:
        print('No such server')
    else:
        server_data = {
            'server': server,
        }
        print(json.dumps(server_data))
```

**Comment by lijok** [comment]
In the traceback it says "OSError: [Errno 2] No such file or directory"
Do you have "asset_list" executable in wherever awx is running? If you installed awx on docker by following the installation guide, i believe that will be the awx_task container

**Comment by gforster** [comment]
Yes, it is executable and working via cli as the awx user. There are no issues whatsoever running anything (playbooks, dynamic inventory, etc.) from the command line, which is what is so confusing.

**Comment by ryanpetrello** [comment]
What @lijok said - the container which is running this inventory script isn't able to find `asset_list` on the `PATH`.  What is the absolute path to `asset_list`?  Does the executable exist somewhere that's whitelisted by bubblewrap?  You might consider setting `AWX_PROOT_ENABLED = False` at `/api/v2/settings/jobs/` and trying with that.

**Comment by gforster** [comment]
I have ensured that `/custom/common/bin` (where asset_list is) is in `$PATH` and `AWX_PROOT_ENABLED = False`. The results are the same. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ryanpetrello** [comment]
Is it a matter of the user executing the playbook having an incorrect `PATH`?  What happens if you update your inventory script's `check_output()` invocation to explicitly run `/custom/common/bin/asset_list`?

**Comment by gforster** [comment]
Unfortunately, I get

`Traceback (most recent call last): File "/lib/python2.7/site-packages/awx/main/tasks.py", line 934, in run File "/lib/python2.7/site-packages/awx/main/tasks.py", line 2180, in pre_run_hook File "/lib/python2.7/site-packages/awx/main/tasks.py", line 625, in _wrapped File "/lib/python2.7/site-packages/awx/main/tasks.py", line 1078, in run Exception: project_update 1293 (error) encountered an error (rc=None), please see task stdout for details. `

And nothing in the task stdout to check on details. Same in the logs on the server.

**Comment by ryanpetrello** [comment]
@gforster I'm not certain of the exact cause, but this very much seems like a situation where the binary in question `asset_list` can't be found on the `PATH` in the container where the playbook is running.

Given that you've reported:

> AWX version: Tower 3.4.3

You may want to consider reaching out to Red Hat for official support.
