### ISSUE TITLE
Create Schedule page templates are broken

### ISSUE THREAD

**Issue by alexander-bauer** [ansible/awx#401]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
I am unable to create schedules for running jobs, because the schedule creation page has unrendered templates which break page functionality. I've attached a screenshot. I can fill out some of the fields, but clicking on the date picker under "Start Date" reloads the page. The local timezone and repeat frequency dropdowns are also empty.

![screen shot 2017-10-11 at 11 25 32 am](https://user-images.githubusercontent.com/1558334/31450252-f3b7512c-ae76-11e7-8a9b-345c280143a5.png)

##### ENVIRONMENT
* AWX version: 1.0.0.524
* AWX install method: docker on linux
* Ansible version: 2.3.1.0
* Operating System: CentOS Linux 7
* Web Browser: Mozilla Firefox 52.1.0

##### STEPS TO REPRODUCE

1. Create a job to run a playbook.
1. Click on Edit Templates
1. Click on the calendar button on the right side of the new job row
1. Add a new schedule
1. See broken page

##### EXPECTED RESULTS

I expected the new schedule page to render without issue, have a functional date picker, local timezone dropdown, repeat frequency dropdown, etc.

##### ACTUAL RESULTS

Schedule page has many `{{ }}`-style Jinja template directives which have not been rendered. Some page elements are nonfunctional.

**Comment by wenottingham** [comment]
Can you pull up any errors from the browser console?

**Comment by alexander-bauer** [comment]
Here's the console output upon loading the page.

```
promise resolved, and readyState: undefined  app.aac55c247dbd70cf730c.js:403:295766
socket readyState at emit: 1 app.aac55c247dbd70cf730c.js:403:298326
Socket deleted: undefined  app.aac55c247dbd70cf730c.js:403:297040
promise resolved, and readyState: undefined  app.aac55c247dbd70cf730c.js:403:295766
socket readyState at emit: 1 app.aac55c247dbd70cf730c.js:403:298326
Socket deleted: undefined  app.aac55c247dbd70cf730c.js:403:297040
promise resolved, and readyState: undefined  app.aac55c247dbd70cf730c.js:403:295766
socket readyState at emit: 1 app.aac55c247dbd70cf730c.js:403:298326
Socket deleted: undefined  app.aac55c247dbd70cf730c.js:403:297040
promise resolved, and readyState: undefined  app.aac55c247dbd70cf730c.js:403:295766
socket readyState at emit: 1 app.aac55c247dbd70cf730c.js:403:298326
Empty string passed to getElementById(). vendor.aac55c247dbd70cf730c.js:398:32327
Empty string passed to getElementById(). vendor.aac55c247dbd70cf730c.js:398:32322
socket readyState at emit: 1  app.aac55c247dbd70cf730c.js:403:298326
Empty string passed to getElementById().  vendor.aac55c247dbd70cf730c.js:398:32322
Error: $.fn.select2 is undefined
exports.default</<@https://awx1.mydomain/static/js/app.aac55c247dbd70cf730c.js:403:422342
exports.default</callSelect2@https://awx1.mydomain/static/js/app.aac55c247dbd70cf730c.js:403:91600
exports.default<@https://awx1.mydomain/static/js/app.aac55c247dbd70cf730c.js:403:91716
invoke@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:30009
instantiate@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:30174
$ControllerProvider/this.$get</<@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:78540
$ViewDirectiveFill/<.compile/<@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:143878
invokeLinkFn@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:70399
nodeLinkFn@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:55720
compositeLinkFn@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:45981
compile/<@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:44694
updateView@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:148476
configUpdatedCallback@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:147685
ViewService/this.sync/configureUIView@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:93417
ViewService/this.sync@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:93451
activateViews@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:88055
TransitionHook</TransitionHook.prototype.invokeHook@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:35056
TransitionHook</TransitionHook.runSynchronousHooks@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:36253
Transition</Transition.prototype.run/transitionSuccess@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:26644
processQueue@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:117543
scheduleProcessQueue/<@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:117810
$RootScopeProvider/this.$get</Scope.prototype.$eval@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:130726
$RootScopeProvider/this.$get</Scope.prototype.$digest@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:128522
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:131153
done@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:85804
completeRequest@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:89746
createHttpBackend/</xhr.onload@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:90678
 <div ui-view="form" class="ng-scope">  vendor.aac55c247dbd70cf730c.js:436:104482
Error: $(...).tooltip is not a function
exports.default</<.link/</stateChangeWatcher<@https://awx1.mydomain/static/js/app.aac55c247dbd70cf730c.js:403:398313
$RootScopeProvider/this.$get</Scope.prototype.$broadcast@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:133018
stateChangeStartHandler@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:474:1402
TransitionHook</TransitionHook.prototype.invokeHook@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:35056
TransitionHook</TransitionHook.runSynchronousHooks@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:36253
Transition</Transition.prototype.run@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:26004
StateService</StateService.prototype.transitionTo@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:116055
StateQueueManager</StateQueueManager.prototype.attachRoute/<@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:109171
invoke@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:30009
handleIfMatch@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:79506
UrlRouterProvider</UrlRouterProvider.prototype.when/strategies.matcher/<@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:81741
check@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:79901
update@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:80104
UrlRouter</UrlRouter.prototype.listen/this.listener<@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:83169
$get/</<@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:122546
$get/<@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:468:122505
$RootScopeProvider/this.$get</Scope.prototype.$broadcast@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:133018
afterLocationChange@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:100709
$LocationProvider/this.$get</</<@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:103746
$RootScopeProvider/this.$get</Scope.prototype.$eval@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:130726
$RootScopeProvider/this.$get</Scope.prototype.$digest@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:128522
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:131153
done@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:85804
completeRequest@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:89746
createHttpBackend/</xhr.onload@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:90678
  vendor.aac55c247dbd70cf730c.js:436:104482
Error: this.scope.scheduler_form is undefined
this.isValid@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:449:52716
@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:449:54306
$RootScopeProvider/this.$get</Scope.prototype.$broadcast@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:133018
exports.default</</<@https://awx1.mydomain/static/js/app.aac55c247dbd70cf730c.js:403:89698
$RootScopeProvider/this.$get</Scope.prototype.$emit@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:132328
exports.default</</<@https://awx1.mydomain/static/js/app.aac55c247dbd70cf730c.js:403:90309
$RootScopeProvider/this.$get</Scope.prototype.$digest@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:129068
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:131153
done@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:85804
completeRequest@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:89746
createHttpBackend/</xhr.onload@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:90678
  vendor.aac55c247dbd70cf730c.js:436:104482
Error: this.scope.scheduler_form is undefined
this.isValid@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:449:52716
@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:449:54306
$RootScopeProvider/this.$get</Scope.prototype.$broadcast@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:133018
exports.default</</<@https://awx1.mydomain/static/js/app.aac55c247dbd70cf730c.js:403:89698
$RootScopeProvider/this.$get</Scope.prototype.$emit@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:132328
exports.default</</<@https://awx1.mydomain/static/js/app.aac55c247dbd70cf730c.js:403:90240
watchGroupAction@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:125301
$RootScopeProvider/this.$get</Scope.prototype.$eval@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:130726
$RootScopeProvider/this.$get</Scope.prototype.$digest@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:128522
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:131153
done@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:85804
completeRequest@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:89746
createHttpBackend/</xhr.onload@https://awx1.mydomain/static/js/vendor.aac55c247dbd70cf730c.js:436:90678
  vendor.aac55c247dbd70cf730c.js:436:104482
Empty string passed to getElementById().  vendor.aac55c247dbd70cf730c.js:398:32327  
```

Another maybe-crucial piece of information is that **there is no Internet access** from this site. Thinking this might be an issue for externally-loaded Javascript, I looked at the Network tab, but I'm not seeing any errors there.

**Comment by alexander-bauer** [comment]
@wenottingham is there any more information I can give you that will help in diagnosing this?

**Comment by wenottingham** [comment]
We did note a build issue in our published containers... can you try with 1.0.1.12?

**Comment by alexander-bauer** [comment]
I upgraded to the 1.0.1 tagged version, and this is no longer an issue for me. Thanks!

**Comment by arnarg** [comment]
Am I missing something here? I've tried tags `1.0.1.12`, `1` and `latest` as well as building it myself from devel branch but I still get this bug in chrome, firefox and safari.

The inventory file is:
```
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"

[all:vars]

dockerhub_base=ansible
dockerhub_version=1

awx_secret_key=<redacted>

postgres_data_dir=/tmp/pgdocker
host_port=80

pg_username=awx
pg_password=<redacted>
pg_database=awx
pg_port=5432
```

Console errors are:
```
TypeError: Cannot read property 'replace' of undefined
    at resolve (vendor.4c1b9c3….js:449)
    at Object.getLocal (vendor.4c1b9c3….js:449)
    at ChildScope.scope.setDefaults (vendor.4c1b9c3….js:449)
    at vendor.4c1b9c3….js:449
    at ChildScope.$emit (vendor.4c1b9c3….js:436)
    at Object.getZoneList (vendor.4c1b9c3….js:449)
    at vendor.4c1b9c3….js:449
    at app.cf519dd….js:403
    at new exports.default (app.cf519dd….js:403)
    at Object.instantiate (vendor.4c1b9c3….js:436)
(anonymous) @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:436
$emit @ vendor.4c1b9c3….js:436
getZoneList @ vendor.4c1b9c3….js:449
(anonymous) @ vendor.4c1b9c3….js:449
(anonymous) @ app.cf519dd….js:403
exports.default @ app.cf519dd….js:403
instantiate @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:469
(anonymous) @ vendor.4c1b9c3….js:436
invokeLinkFn @ vendor.4c1b9c3….js:436
nodeLinkFn @ vendor.4c1b9c3….js:436
compositeLinkFn @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:436
updateView @ vendor.4c1b9c3….js:469
configUpdatedCallback @ vendor.4c1b9c3….js:469
configureUIView @ vendor.4c1b9c3….js:431
ViewService.sync @ vendor.4c1b9c3….js:431
activateViews @ vendor.4c1b9c3….js:469
(anonymous) @ vendor.4c1b9c3….js:398
TransitionHook.invokeHook @ vendor.4c1b9c3….js:398
(anonymous) @ vendor.4c1b9c3….js:398
TransitionHook.runAllHooks @ vendor.4c1b9c3….js:398
transitionSuccess @ vendor.4c1b9c3….js:398
processQueue @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:436
$digest @ vendor.4c1b9c3….js:436
$apply @ vendor.4c1b9c3….js:436
done @ vendor.4c1b9c3….js:436
completeRequest @ vendor.4c1b9c3….js:436
xhr.onload @ vendor.4c1b9c3….js:436

TypeError: Cannot read property 'replace' of undefined
    at resolve (vendor.4c1b9c3….js:449)
    at Object.getLocal (vendor.4c1b9c3….js:449)
    at ChildScope.scope.setDefaults (vendor.4c1b9c3….js:449)
    at Object.clear (vendor.4c1b9c3….js:449)
    at app.cf519dd….js:403
    at new exports.default (app.cf519dd….js:403)
    at Object.instantiate (vendor.4c1b9c3….js:436)
    at vendor.4c1b9c3….js:436
    at Object.<anonymous> (vendor.4c1b9c3….js:469)
    at vendor.4c1b9c3….js:436 "<div ui-view="form" class="ng-scope">"
(anonymous) @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:436
invokeLinkFn @ vendor.4c1b9c3….js:436
nodeLinkFn @ vendor.4c1b9c3….js:436
compositeLinkFn @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:436
updateView @ vendor.4c1b9c3….js:469
configUpdatedCallback @ vendor.4c1b9c3….js:469
configureUIView @ vendor.4c1b9c3….js:431
ViewService.sync @ vendor.4c1b9c3….js:431
activateViews @ vendor.4c1b9c3….js:469
(anonymous) @ vendor.4c1b9c3….js:398
TransitionHook.invokeHook @ vendor.4c1b9c3….js:398
(anonymous) @ vendor.4c1b9c3….js:398
TransitionHook.runAllHooks @ vendor.4c1b9c3….js:398
transitionSuccess @ vendor.4c1b9c3….js:398
processQueue @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:436
$digest @ vendor.4c1b9c3….js:436
$apply @ vendor.4c1b9c3….js:436
done @ vendor.4c1b9c3….js:436
completeRequest @ vendor.4c1b9c3….js:436
xhr.onload @ vendor.4c1b9c3….js:436
```

**Comment by ykisialevich** [comment]
I had similar issue (Schedule page was broken), but it my case this fix helped me:
1. set SELINUX=disabled in /etc/selinux/config
2. setenforce 0
3. reboot
