### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/var/lib/awx/.azure/azureProfile.json'

### ISSUE THREAD

**Issue by jhonjcastroh** [ansible/awx#4055]
When run this command it works:
`sudo ansible-playbook -i hosts create-vm-azure.yml --extra-vars "vm_name=test flavor=Standard_D2s_v3 resource_group=nebula user_vm=nebula pass_vm=Password" -vvvv`

But whit run the job at AWX doesn´t works....

**Output:
ansible-playbook 2.7.7
config file = /var/lib/awx/projects/_6__github_jhon/ansible.cfg
configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python2.7/site-packages/ansible
executable location = /usr/bin/ansible-playbook
python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /var/lib/awx/projects/_6__github_jhon/ansible.cfg as config file

{
"_ansible_parsed": false,
"vm_name": "j",
"exception": "Traceback (most recent call last):\n File "/root/.ansible/tmp/ansible-tmp-1560352088.55-6858242544000/AnsiballZ_azure_rm_virtualmachine.py", line 113, in \n _ansiballz_main()\n File "/root/.ansible/tmp/ansible-tmp-1560352088.55-6858242544000/AnsiballZ_azure_rm_virtualmachine.py", line 105, in _ansiballz_main\n invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n File "/root/.ansible/tmp/ansible-tmp-1560352088.55-6858242544000/AnsiballZ_azure_rm_virtualmachine.py", line 48, in invoke_module\n imp.load_module('main', mod, module, MOD_DESC)\n File "/tmp/ansible_azure_rm_virtualmachine_payload_Sjg_wZ/main.py", line 1795, in \n File "/tmp/ansible_azure_rm_virtualmachine_payload_Sjg_wZ/main.py", line 1791, in main\n File "/tmp/ansible_azure_rm_virtualmachine_payload_Sjg_wZ/main.py", line 771, in init\n File "/tmp/ansible_azure_rm_virtualmachine_payload_Sjg_wZ/ansible_azure_rm_virtualmachine_payload.zip/ansible/module_utils/azure_rm_common.py", line 301, in init\n File "/tmp/ansible_azure_rm_virtualmachine_payload_Sjg_wZ/ansible_azure_rm_virtualmachine_payload.zip/ansible/module_utils/azure_rm_common.py", line 956, in init\n File "/tmp/ansible_azure_rm_virtualmachine_payload_Sjg_wZ/ansible_azure_rm_virtualmachine_payload.zip/ansible/module_utils/azure_rm_common.py", line 1142, in _get_credentials\n File "/tmp/ansible_azure_rm_virtualmachine_payload_Sjg_wZ/ansible_azure_rm_virtualmachine_payload.zip/ansible/module_utils/azure_rm_common.py", line 1096, in _get_azure_cli_credentials\n File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/common/credentials.py", line 46, in get_azure_cli_credentials\n profile = get_cli_profile()\n File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/common/credentials.py", line 28, in get_cli_profile\n ACCOUNT.load(os.path.join(azure_folder, 'azureProfile.json'))\n File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/cli/core/_session.py", line 42, in load\n self.save()\n File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/cli/core/_session.py", line 46, in save\n with codecs_open(self.filename, 'w', encoding=self._encoding) as f:\n File "/usr/lib64/python2.7/codecs.py", line 881, in open\n file = builtin.open(filename, mode, buffering)\nIOError: [Errno 2] No such file or directory: '/var/lib/awx/.azure/azureProfile.json'\n",
"changed": false,
"_ansible_item_label": "j",
"_ansible_delegated_vars": {
"ansible_delegated_host": "localhost",
"ansible_host": "localhost"
},
"module_stderr": "Traceback (most recent call last):\n File "/root/.ansible/tmp/ansible-tmp-1560352088.55-6858242544000/AnsiballZ_azure_rm_virtualmachine.py", line 113, in \n _ansiballz_main()\n File "/root/.ansible/tmp/ansible-tmp-1560352088.55-6858242544000/AnsiballZ_azure_rm_virtualmachine.py", line 105, in _ansiballz_main\n invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n File "/root/.ansible/tmp/ansible-tmp-1560352088.55-6858242544000/AnsiballZ_azure_rm_virtualmachine.py", line 48, in invoke_module\n imp.load_module('main', mod, module, MOD_DESC)\n File "/tmp/ansible_azure_rm_virtualmachine_payload_Sjg_wZ/main.py", line 1795, in \n File "/tmp/ansible_azure_rm_virtualmachine_payload_Sjg_wZ/main.py", line 1791, in main\n File "/tmp/ansible_azure_rm_virtualmachine_payload_Sjg_wZ/main.py", line 771, in init\n File "/tmp/ansible_azure_rm_virtualmachine_payload_Sjg_wZ/ansible_azure_rm_virtualmachine_payload.zip/ansible/module_utils/azure_rm_common.py", line 301, in init\n File "/tmp/ansible_azure_rm_virtualmachine_payload_Sjg_wZ/ansible_azure_rm_virtualmachine_payload.zip/ansible/module_utils/azure_rm_common.py", line 956, in init\n File "/tmp/ansible_azure_rm_virtualmachine_payload_Sjg_wZ/ansible_azure_rm_virtualmachine_payload.zip/ansible/module_utils/azure_rm_common.py", line 1142, in _get_credentials\n File "/tmp/ansible_azure_rm_virtualmachine_payload_Sjg_wZ/ansible_azure_rm_virtualmachine_payload.zip/ansible/module_utils/azure_rm_common.py", line 1096, in _get_azure_cli_credentials\n File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/common/credentials.py", line 46, in get_azure_cli_credentials\n profile = get_cli_profile()\n File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/common/credentials.py", line 28, in get_cli_profile\n ACCOUNT.load(os.path.join(azure_folder, 'azureProfile.json'))\n File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/cli/core/_session.py", line 42, in load\n self.save()\n File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/cli/core/_session.py", line 46, in save\n with codecs_open(self.filename, 'w', encoding=self._encoding) as f:\n File "/usr/lib64/python2.7/codecs.py", line 881, in open\n file = builtin.open(filename, mode, buffering)\nIOError: [Errno 2] No such file or directory: '/var/lib/awx/.azure/azureProfile.json'\n",
"_ansible_item_result": true,
"module_stdout": "",
"rc": 1,
"msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
"_ansible_ignore_errors": null,
"_ansible_no_log": false
}

FILE EXIST:
ansibleadmin@Ansible-Server:~$ cat /var/lib/awx/.azure/azureProfile.json
{
"cloudName": "AzureCloud",
"id": "ID",
"isDefault": true,
"name": "Pago por uso",
"state": "Enabled",
"tenantId": "TENANTID",
"client": "CLIENT",
"secret": "SERCRET",
"user": {
"name": "USER@outlook.com",
"type": "user"
}
}

PLAYBOOK

    name: Creando una VM en Azure componentes por defecto
    hosts: all
    tasks:
        name: Create VM with defaults
        azure_rm_virtualmachine:
          auth_source: cli
          resource_group: "{{ resource_group }}"
          admin_username: "{{ user_vm }}"
          admin_password: "{{ pass_vm }}"
          name: "{{ vm_name }}"
          vm_size: "{{ flavor }}"
          managed_disk_type: Standard_LRS
          open_ports: 8443
          image:
            offer: CentOS
            publisher: OpenLogic
            sku: '7.6'
            version: latest
        loop: "{{ vm_name_list }}"
        loop_control:
          loop_var: vm_name
        delegate_to: localhost

    Feature Request:

In host:
ansible 2.8.1
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/ansibleadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
executable location = /usr/local/bin/ansible
python version = 3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609]

When set ansible_python_interpreter=/usr/bin/python3 get the follow error:

    An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'enum' has no attribute 'IntFlag'

**Comment by falcon78921** [comment]
@jhonjcastroh out of curiosity, did you create a **Microsoft Azure Resource Manager** credential in AWX and tie it to the job template?

**Comment by jhonjcastroh** [comment]
@falcon78921 no, in the job template I added the credencials of machine where I have installed the CLI Azure.

**Comment by falcon78921** [comment]
@jhonjcastroh I highly recommend creating a Microsoft Azure Resource Manager credential instead of explicitly defining `/var/lib/awx/.azure/azureProfile.json`. You shouldn't have to do this in AWX. Creating a manual `credentials` or `azureProfile.json` (Azure CLI) file is only for running Azure playbooks in ad-hoc.

See: https://docs.ansible.com/ansible/latest/scenario_guides/guide_azure.html
