### ISSUE TITLE
Analytics collections throws errors in log when no insights-client present

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#4170]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Looking through logs to debug another problem, I found a weird traceback.

##### ENVIRONMENT
* AWX version: devel
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

When `insights-client` is not installed on a machine, awx still tries to do things to communicate with it and ends up throwing tracebacks in the logs.

##### EXPECTED RESULTS

No insights-client, no reporting metrics, no tracebacks

##### ACTUAL RESULTS

in `/var/log/tower.log`
```
2019-06-25 00:24:00,434 ERROR    awx.main.analytics Could not generate metric instance_info.json
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/analytics/core.py", line 94, in gather
    json.dump(func(last_run), f)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable
2019-06-25 00:24:00,469 ERROR    awx.main.analytics could not find insights-client on PATH
```

##### ADDITIONAL INFORMATION

@rooftopcellist mentioned:
https://github.com/ansible/awx/blob/devel/awx/main/analytics/core.py#L139
awx/main/analytics/core.py:139

and that he thought `CalledProcessError` _would_ have caught that..

...looks like is not quite enough for this situation

**Comment by ryanpetrello** [comment]
cc @rooftopcellist we should fix this

**Comment by ryanpetrello** [comment]
@kdelee I think the fact that `insights-agent` is missing is a red herring.  This JSON serialization error looks like something else to me.

**Comment by rooftopcellist** [comment]
@ryanpetrello here is some more information:

this is how it shows up when I run it as an awx-manage command:

```
bash-4.2$ awx-manage gather_analytics --ship
2019-06-26 18:47:14,187 DEBUG    awx.main.analytics Last analytics run was: 2019-06-26 18:46:34.389683+00:00
/tmp/00000000-0000-0000-0000-000000000000_2019-06-26-184714+0000.tar.gz
could not find insights-client on PATH
``` 
I agree that the datetime TypeError is separate, and probably an actual bug.  @kdelee saw this on a cluster install (I am guessing with an isolated node configured).  

I suspect that the `last_isolated_check` just needs to be forced to be a string. testing now.

```
            'last_isolated_check': instance['last_isolated_check'],
```

**Comment by Spredzy** [comment]
verified
