### ISSUE TITLE
500 error when user is removed from an active session

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#4334]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
1. log in as a user
2. remove the user via the API
3. reload

```
awx_1        | 2019-07-16 21:07:30,594 ERROR    django.request Internal Server Error: /
awx_1        | Traceback (most recent call last):
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 240, in _commit
awx_1        |     return self.connection.commit()
awx_1        | psycopg2.IntegrityError: insert or update on table "main_usersessionmembership" violates foreign key constraint "main_usersessionmembership_user_id_fe163c98_fk_auth_user_id"
awx_1        | DETAIL:  Key (user_id)=(2) is not present in table "auth_user".
awx_1        | 
awx_1        | 
awx_1        | The above exception was the direct cause of the following exception:
awx_1        | 
awx_1        | Traceback (most recent call last):
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
awx_1        |     response = get_response(request)
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/django/utils/deprecation.py", line 96, in __call__
awx_1        |     response = self.process_response(request, response)
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/django/contrib/sessions/middleware.py", line 58, in process_response
awx_1        |     request.session.save()
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 87, in save
awx_1        |     obj.save(force_insert=must_create, force_update=not must_create, using=using)
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/django/db/transaction.py", line 240, in __exit__
awx_1        |     connection.commit()
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 262, in commit
awx_1        |     self._commit()
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 240, in _commit
awx_1        |     return self.connection.commit()
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
awx_1        |     raise dj_exc_value.with_traceback(traceback) from exc_value
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 240, in _commit
awx_1        |     return self.connection.commit()
awx_1        | django.db.utils.IntegrityError: insert or update on table "main_usersessionmembership" violates foreign key constraint "main_usersessionmembership_user_id_fe163c98_fk_auth_user_id"
awx_1        | DETAIL:  Key (user_id)=(2) is not present in table "auth_user".
```

##### ENVIRONMENT
* AWX version: curret devel head
* AWX install method: docker-compose

##### ADDITIONAL INFORMATION

Also happens with older releases. In that case, the traceback is:
```
2019-07-16 19:25:44,119 ERROR    django.request Internal Server Error: /
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/handlers/base.py", line 131, in get_response
    response = middleware_method(request, response)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/sessions/middleware.py", line 58, in process_response
    request.session.save()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 87, in save
    obj.save(force_insert=must_create, force_update=not must_create, using=using)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/base.py", line 848, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/signals.py", line 658, in save_user_session_membership
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
```

**Comment by elyezer** [comment]
Did the following to verify:

1) Create an user and logged into the UI with it
2) Deleted the user over the API
3) Tried to navigate on the UI and I was brought to the loging page 
4) Tried to loging with the deleted user and, as expected, was not able.

While doing all the steps above I was watching the logs and no stacktrace was shown. With that said we can close this one.
