### ISSUE TITLE
Job Fails right away throwing Traceback errors.

### ISSUE THREAD

**Issue by naren-ambati** [ansible/awx#4406]
### SUMMARY
JOB fails throwing exception python errors. 

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: docker on linux
* Operating System: Oracle Linux
* External Rabbitmq
* External memcached

##### EXPECTED RESULTS
- Trying to ping my server. Should get pong.

##### ACTUAL RESULTS
`
Traceback (most recent call last): File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/cryptography/fernet.py", line 104, in _verify_signature h.verify(data[-32:]) File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/cryptography/hazmat/primitives/hmac.py", line 67, in verify ctx.verify(signature) File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 75, in verify raise InvalidSignature("Signature did not match digest.") cryptography.exceptions.InvalidSignature: Signature did not match digest. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 1176, in run private_data_files = self.build_private_data_files(self.instance, private_data_dir) File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 794, in build_private_data_files private_data = self.build_private_data(instance, private_data_dir) File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 2215, in build_private_data private_data['credentials'][creds] = creds.get_input('ssh_key_data', default='') File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/models/credential/__init__.py", line 277, in get_input return decrypt_field(self, field_name) File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/utils/encryption.py", line 121, in decrypt_field return smart_str(decrypt_value(key, value)) File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/utils/encryption.py", line 98, in decrypt_value value = f.decrypt(encrypted) File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/cryptography/fernet.py", line 75, in decrypt return self._decrypt_data(data, timestamp, ttl) File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/cryptography/fernet.py", line 117, in _decrypt_data self._verify_signature(data) File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/cryptography/fernet.py", line 106, in _verify_signature raise InvalidToken cryptography.fernet.InvalidToken
`
## awx_task logs:
`
2019-07-31 21:32:26,640 DEBUG    awx.main.dispatch task 9be7c9aa-e1df-441f-8e9f-b458cd6a99bd is finished
2019-07-31 21:32:28,249 WARNING  django.security.SuspiciousSession Session data corrupted
2019-07-31 21:32:28,256 ERROR    awx.main.consumers Request user is not authenticated to use websocket.
2019-07-31 21:32:31,404 WARNING  django.security.SuspiciousSession Session data corrupted
2019-07-31 21:32:31,411 ERROR    awx.main.consumers Request user is not authenticated to use websocket.
2019-07-31 21:32:34,561 WARNING  django.security.SuspiciousSession Session data corrupted
2019-07-31 21:32:34,568 ERROR    awx.main.consumers Request user is not authenticated to use websocket.
`
## 
<img width="1449" alt="Screen Shot 2019-07-31 at 4 37 50 PM" src="https://user-images.githubusercontent.com/32987080/62250063-944a6e80-b3b1-11e9-94da-fd4dda5bdbf9.png">
awx_web logs:

`
2019/07/31 21:32:58 [error] 151#0: *274 recv() failed (104: Connection reset by peer) while proxying upgraded connection, client: 17.168.54.160, server: server1, request: "GET /websocket/ HTTP/1.1", upstream: "http://127.0.0.1:8051/websocket/", host: "server1"
`

**Comment by ryanpetrello** [comment]
@naren-ambati 

It this a fresh install, or did you restore/backup/migrate from some other installation?  This error is usually a sign that you migrated data between installs incorrectly.

**Comment by naren-ambati** [comment]
I took copy of existing AWX container and enabled ssl and changes things for external dependencies. Do you think that messed things up?

**Comment by ryanpetrello** [comment]
In order for secrets (like SSH keys you entered into the database) to be decrypted properly, you'll need to persist the original `SECRET_KEY` value across deployments:

https://github.com/ansible/awx/blob/devel/installer/roles/local_docker/tasks/compose.yml#L18

**Comment by naren-ambati** [comment]
/etc/tower/settings.py takes care of that right
```
def get_secret():
    if os.path.exists("/etc/tower/SECRET_KEY"):
        return open('/etc/tower/SECRET_KEY', 'rb').read().strip()
    return os.getenv("SECRET_KEY", "privateawx")
```

**Comment by cloneluke** [comment]
[install-copy-openedge-certs](https://github.com/ansible/awx/issues/10799#issuecomment-1690485902)
