### ISSUE TITLE
AWX 1.0.6.15 : Permanent Error in awx_task

### ISSUE THREAD

**Issue by zdriic** [ansible/awx#4408]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
When I check docker logs with the command "docker logs -f awx_task", I still get the error message below every 30 seconds approximately.
In my opinion, this is a bug of the version from at least version 1.0.6.15 to 1.0.6.41 (or more).
Have you ever seen this error before?

> I know I have a very old version but we try to implement AWX in a large company and in higher versions there is always something that does not work or cannot be upgraded with existing data...

##### ENVIRONMENT
* AWX version: 1.0.6.15 (and 1.0.6.41 too)
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.8.3 (same error with 2.7.10)
* Operating System: Ubuntu 16.04
* Web Browser: Firefox

##### STEPS TO REPRODUCE

I can just see this error with "docker logs -f awx_task" command but AWX seems to work correctly despite this error.

##### ACTUAL RESULTS

[2019-08-01 13:31:59,251: DEBUG/Worker-25] Open OK!
[2019-08-01 13:31:59,252: DEBUG/Worker-25] using channel_id: 1
[2019-08-01 13:31:59,253: DEBUG/Worker-25] Channel open
[2019-08-01 13:31:59,264: DEBUG/Worker-25] Closed channel #1
[2019-08-01 13:31:59,324: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7f5531c70320> (args:(u'awx.main.tasks.awx_periodic_scheduler', u'1f2c0975-9fb0-4ca9-84af-374d35290102', [], {}, {u'utc': True, u'is_eager': False, u'chord': None, u'group': None, u'args': [], u'retries': 0, u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'awx_private_queue', u'exchange': u'awx_private_queue'}, u'expires': u'2019-08-01T13:32:19.120317+00:00', u'hostname': 'celery@awx', u'task': u'awx.main.tasks.awx_periodic_scheduler', u'callbacks': None, u'correlation_id': u'1f2c0975-9fb0-4ca9-84af-374d35290102', u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'reply_to': u'01ab76e6-d837-3400-adf7-015eadab2e95', u'id': u'1f2c0975-9fb0-4ca9-84af-374d35290102', u'headers': {}}) kwargs:{})
[2019-08-01 13:31:59,326: DEBUG/MainProcess] basic.qos: prefetch_count->264
[2019-08-01 13:31:59,329: INFO/MainProcess] Received task: awx.main.tasks.handle_ha_toplogy_changes[7dfb59c0-f67a-45ef-84f6-9c14001bcb87]
[2019-08-01 13:31:59,329: INFO/MainProcess] Scaling up 1 processes.
[2019-08-01 13:31:59,537: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7f5531c70320> (args:(u'awx.main.tasks.handle_ha_toplogy_changes', u'7dfb59c0-f67a-45ef-84f6-9c14001bcb87', [], {}, {u'utc': True, u'is_eager': False, u'chord': None, u'group': None, u'args': [], u'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': False, u'routing_key': u'awx_private_queue', u'exchange': u'tower_broadcast_all'}, u'expires': None, u'hostname': 'celery@awx', u'task': u'awx.main.tasks.handle_ha_toplogy_changes', u'callbacks': None, u'correlation_id': u'7dfb59c0-f67a-45ef-84f6-9c14001bcb87', u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'reply_to': u'631cba5e-ae4c-39a1-81cc-e5959f2fb3b6', u'id': u'7dfb59c0-f67a-45ef-84f6-9c14001bcb87', u'headers': {}}) kwargs:{})
[2019-08-01 13:31:59,539: INFO/MainProcess] Task awx.main.tasks.cluster_node_heartbeat[d407aa2c-bff9-457c-81c3-7ba30e8af698] succeeded in 0.430306020018s: None
[2019-08-01 13:31:59,540: DEBUG/MainProcess] basic.qos: prefetch_count->268
[2019-08-01 13:31:59,542: DEBUG/MainProcess] Task accepted: awx.main.tasks.awx_periodic_scheduler[1f2c0975-9fb0-4ca9-84af-374d35290102] pid:476
[2019-08-01 13:31:59,545: DEBUG/MainProcess] Task accepted: awx.main.tasks.handle_ha_toplogy_changes[7dfb59c0-f67a-45ef-84f6-9c14001bcb87] pid:475
2019-08-01 13:31:59,588 DEBUG    awx.main.tasks Reconfigure celeryd queues task on host celery@awx
2019-08-01 13:31:59,599 ERROR    awx.main.tasks Task awx.main.tasks.awx_periodic_scheduler encountered exception.
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 395, in awx_periodic_scheduler
    state = TowerScheduleState.get_solo()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/solo/models.py", line 54, in get_solo
    obj, created = cls.objects.get_or_create(pk=cls.singleton_instance_id)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 384, in get
    (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one TowerScheduleState -- it returned 3!
[2019-08-01 13:31:59,638: ERROR/MainProcess] Task awx.main.tasks.awx_periodic_scheduler[1f2c0975-9fb0-4ca9-84af-374d35290102] raised unexpected: MultipleObjectsReturned('get() returned more than one TowerScheduleState -- it returned 3!',)
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 395, in awx_periodic_scheduler
    state = TowerScheduleState.get_solo()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/solo/models.py", line 54, in get_solo
    obj, created = cls.objects.get_or_create(pk=cls.singleton_instance_id)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 384, in get
    (self.model._meta.object_name, num)
Exception: get() returned more than one TowerScheduleState -- it returned 3!
[2019-08-01 13:31:59,644: DEBUG/Worker-25] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2018 Pivotal Software, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'connection.blocked': True, u'authentication_failure_close': True, u'direct_reply_to': True, u'basic.nack': True, u'per_consumer_qos': True, u'consumer_priorities': True, u'consumer_cancel_notify': True, u'publisher_confirms': True}, u'cluster_name': u'rabbit@255a30cd5c99', u'platform': u'Erlang/OTP 20.1.7', u'version': u'3.7.4'}, mechanisms: [u'AMQPLAIN', u'PLAIN'], locales: [u'en_US']

Thanks in advance for your help

**Comment by wenottingham** [comment]
Hi -

I understand you may be stuck on the older versoin, but we are not maintaining or providing fixes for that. For bug reporting, you will need to be a on a current version (6.1.0 is the current release).
