### ISSUE TITLE
Scheduler job not work

### ISSUE THREAD

**Issue by GoodHaHa** [ansible/awx#4419]
##### ISSUE TYPE
scheduler job not work

##### SUMMARY
scheduler job not work

##### ENVIRONMENT
* AWX version: 6.1.0 and 6.0.0
* AWX install method: docker on centos
* Ansible version:  2.5.8
* Operating System: centos 7.4
* Web Browser: chrome

##### STEPS TO REPRODUCE

scheduler job not work

##### ADDITIONAL INFORMATION

~~~
2019-08-05 10:11:42,327 DEBUG    awx.main.dispatch task 26431618-8ee6-4b63-982e-98d5c22f1351 starting awx.main.tasks.awx_periodic_scheduler(*[])
2019-08-05 10:11:42,334 DEBUG    awx.main.tasks Starting periodic scheduler
2019-08-05 10:11:42,337 ERROR    awx.main.dispatch Worker failed to run task awx.main.tasks.awx_periodic_scheduler(*[], **{}
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/worker/task.py", line 85, in perform_work
    result = self.run_callable(body)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/worker/task.py", line 61, in run_callable
    return _call(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 483, in awx_periodic_scheduler
    state = TowerScheduleState.get_solo()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/solo/models.py", line 54, in get_solo
    obj, created = cls.objects.get_or_create(pk=cls.singleton_instance_id)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 412, in get
    (self.model._meta.object_name, num)
awx.main.models.ha.TowerScheduleState.MultipleObjectsReturned: get() returned more than one TowerScheduleState -- it returned 2!
2019-08-05 10:11:42,339 DEBUG    awx.main.dispatch task 26431618-8ee6-4b63-982e-98d5c22f1351 is finished
~~~

**Comment by GoodHaHa** [comment]
duplicate key

![image](https://user-images.githubusercontent.com/7147143/62508915-dd7c4180-b83b-11e9-87c2-d2660622258f.png)
