### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by infosecwatchman** [ansible/awx#4456]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Somewhere while AWX is setting up the database after the ansible-playbook finishes and in the `docker logs -f awx_task` I'm seeing it cannot finish because of a python file. 
This is what I'm getting:
```
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/settings/production.py", line 106, in <module>
    raise ImproperlyConfigured(msg)
django.core.exceptions.ImproperlyConfigured: No AWX configuration found at /etc/tower/settings.py.
Define the AWX_SETTINGS_FILE environment variable to specify an alternate path.
2019-08-09 18:40:04,723 INFO spawned: 'channels-worker' with pid 4831
2019-08-09 18:40:04,980 INFO exited: callback-receiver (exit status 1; not expected)
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/settings/production.py", line 84, in <module>
    include(settings_file, optional(settings_files), scope=locals())
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/split_settings/tools.py", line 102, in include
    exec(compile(to_compile.read(), included_file, 'exec'), scope)
  File "/etc/tower/settings.py", line 19, in <module>
    SECRET_KEY = get_secret()
  File "/etc/tower/settings.py", line 8, in get_secret
    return open('/etc/tower/SECRET_KEY', 'rb').read().strip()
IsADirectoryError: [Errno 21] Is a directory: '/etc/tower/SECRET_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==6.1.0.0', 'console_scripts', 'awx-manage')()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 126, in manage
    prepare_env()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 91, in prepare_env
    if not settings.DEBUG: # pragma: no cover
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/settings/production.py", line 106, in <module>
    raise ImproperlyConfigured(msg)
django.core.exceptions.ImproperlyConfigured: No AWX configuration found at /etc/tower/settings.py.
Define the AWX_SETTINGS_FILE environment variable to specify an alternate path.
2019-08-09 18:40:05,675 INFO spawned: 'callback-receiver' with pid 4836
2019-08-09 18:40:05,675 INFO success: dispatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-08-09 18:40:06,074 INFO success: channels-worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-08-09 18:40:06,081 INFO exited: dispatcher (exit status 1; not expected)
```

**Comment by ryanpetrello** [comment]
Hey @GregorioSecurity,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by Obsecurus** [comment]
Sorry to comment on a closed issue but I feel like this one is affecting others. For me `/tmp/awxcompose/SECRET_KEY` existed but `/etc/tower/SECRET_KEY` in both awx_task and awx_web were empty directories instead of the file containing the key
