### ISSUE TITLE
awx 7.0.0 fresh install on kubernetes fails on Check for tower user and create django super user tasks

### ISSUE THREAD

**Issue by alancivita** [ansible/awx#4668]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY

Installed brand new awx 7.0.0 deployment on kubernetes (on the same env 6.0.0 works fine)
##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: kubernetes
* Ansible version:  2.8.4
* Operating System: Mac OS Mojave
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Install from scratch on kubernetes

##### ACTUAL RESULTS
Installation fails on 
TASK [kubernetes : Check for Tower Super users]
and
TASK [kubernetes : create django super user if it does not exist]

i had to remove the no_log form the playbook.

##### ADDITIONAL INFORMATION

Attached the full error 
[awx-700-error.log](https://github.com/ansible/awx/files/3579797/awx-700-error.log)

**Comment by ryanpetrello** [comment]
```python
Traceback (most recent call last):
File "/usr/bin/awx-manage", line 11, in <module>     load_entry_point('awx==7.0.0.0', 'console_scripts', 'awx-manage')()
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 142, in manage     execute_from_command_line(sys.argv)
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line     utility.execute()
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute     self.fetch_command(subcommand).run_from_argv(self.argv)
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv     self.execute(*args, **cmd_options)
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute     output = self.handle(*args, **options)
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/commands/shell.py", line 92, in handle     exec(sys.stdin.read())
File "<string>", line 1, in <module>
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/auth/models.py", line 162, in create_superuser     return self._create_user(username, email, password, **extra_fields)   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/auth/models.py", line 145, in _create_user     user.save(using=self._db
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/auth/base_user.py", line 66, in save     super().save(*args, **kwargs)
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/base.py", line 741, in save     force_update=force_update, update_fields=update_fields)
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/base.py", line 779, in save_base     force_update, using, update_fields,
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/base.py", line 870, in _save_table     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/base.py", line 908, in _do_insert     using=using, raw=raw)
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method     return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert     return query.get_compiler(using=using).execute_sql(return_id)
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql     cursor.execute(sql, params)
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers     return executor(sql, params, many, context)   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute     return self.cursor.execute(sql, params)
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__     raise dj_exc_value.with_traceback(traceback) from exc_value
File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute     return self.cursor.execute(sql, params) django.db.utils.IntegrityError: null value in column "last_login" violates not-null constraint DETAIL:  Failing row contains (1, <redacted>..., null, t, admin, , , root@localhost, t, t, 2019-09-05 14:25:39.785032+00)
```

**Comment by ryanpetrello** [comment]
@jrb could this be related to more recent Django updates?

**Comment by ryanpetrello** [comment]
Hrm, this suggests that your database schema for `auth_user` has `last_login` as `NOT NULL`...

![image](https://user-images.githubusercontent.com/214912/64355092-97e39d80-cfce-11e9-8db4-5b137ea94b23.png)

**Comment by alancivita** [comment]
Hi thanks, for getting back
attached is what i have:
![Screenshot 2019-09-05 at 17 21 27](https://user-images.githubusercontent.com/23634711/64355563-b911b180-d001-11e9-9a86-0ca1bbe8b174.png)

**Comment by matburt** [comment]
This works fine for me on a kubernetes install with 7.0

![image](https://user-images.githubusercontent.com/89544/64362092-e186b500-cfdb-11e9-8e71-f411c3e5e867.png)

**Comment by shanemcd** [comment]
I have tested a 5.0.0 -> 7.0.0 upgrade and a fresh install. Both work fine for me. I'm going to close this. If you need help troubleshooting your environment join us on [IRC](http://webchat.freenode.net/?channels=ansible-awx) or our [Google Group](https://groups.google.com/forum/#!forum/awx-project).

**Comment by alancivita** [comment]
So, only because it works for you it's not a bug? seriously?
as i said a fresh 6.0.0 works, 7.0.0 no.
Thanks anyway

**Comment by matburt** [comment]
What we're saying is that two different people haven't been able to reproduce it. You're going to have to give us more information or perform some more troubleshooting on your own to help us find the problem.

**Comment by alancivita** [comment]
FYI the problem resides with python version installed on the worker nodes in kubernetes.
Mine were running python 3.5, so tried to upgrade to python 3.6 and magically everything started working.
But i'm wondering why awx containers do care about the python version installed on the workers.

**Comment by SmartassSkeleton** [comment]
@alancivita 
I am facing the same problem, can you please share what did you do in order to fix this?

**Comment by alancivita** [comment]
@SmartassSkeleton i've updated python from 3.5 to 3.6 on all the kube nodes (very likely you have to do it only on the worker ones):
so connect to each node and :( i'm using ubuntu):
sudo add-apt-repository ppa:jonathonf/python-3.6
sudo apt-get update
sudo apt-get install python3.6
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 2
sudo update-alternatives --config python3

the default selection should be ok - make sure that python 3.6 is the default for the system
after that i've redeployed and it worked
