### ISSUE TITLE
XML module can't add element with namespaced attribute

### ISSUE THREAD

**Issue by icb-** [ansible/awx#469]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - XML module

##### SUMMARY
With the new XML module in 2.4, I get a traceback if I try to add namespaced attributes at the same time as I add the element.

##### ENVIRONMENT
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

##### STEPS TO REPRODUCE

Given this XML file:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<AttributeFilterPolicyGroup xmlns="urn:mace:shibboleth:2.0:afp"
                            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                            id="ShibbolethFilterPolicy"
                            xsi:schemaLocation="urn:mace:shibboleth:2.0:afp http://shibboleth.net/schema/idp/shibboleth-afp.xsd">
  <AttributeFilterPolicy id="UnverifiedRPs" />
</AttributeFilterPolicyGroup>
```

And this play:
```yaml
---
- hosts: test
  tasks:
  - name: Attribute filter Unverified RPs
    xml:
      path: /tmp/test.xml
      namespaces: &namespaces
        x: "urn:mace:shibboleth:2.0:afp"
        xsi: "http://www.w3.org/2001/XMLSchema-instance"
      xpath: '/x:AttributeFilterPolicyGroup/x:AttributeFilterPolicy[@id = "UnverifiedRPs"]'
      pretty_print: yes
      set_children:
        - PolicyRequirementRule:
            "xsi:type": ANY
        - AttributeRule:
            attributeID: eduPersonPrincipalName
        - AttributeRule:
            attributeID: uid
  - name: Attribute filter Unverified RPs
    xml:
      path: /tmp/test.xml
      namespaces: *namespaces
      xpath: '/x:AttributeFilterPolicyGroup/x:AttributeFilterPolicy[@id = "UnverifiedRPs"]/x:AttributeRule[@attributeID="{{item}}"]'
      pretty_print: yes
      set_children:
        - PermitValueRule:
            "xsi:type": ANY
    with_items:
      - eduPersonPrincipalName
      - uid
```

##### EXPECTED RESULTS

Should create elements with namespaced attributes.

##### ACTUAL RESULTS

Failes with a Python traceback
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_XTN7oc/ansible_module_xml.py", line 853, in <module>
    main()
  File "/tmp/ansible_XTN7oc/ansible_module_xml.py", line 829, in main
    set_target_children(module, doc, xpath, namespaces, set_children, input_type)
  File "/tmp/ansible_XTN7oc/ansible_module_xml.py", line 402, in set_target_children
    changed = set_target_children_inner(module, tree, xpath, namespaces, children, in_type)
  File "/tmp/ansible_XTN7oc/ansible_module_xml.py", line 380, in set_target_children_inner
    children = children_to_nodes(module, children, in_type)
  File "/tmp/ansible_XTN7oc/ansible_module_xml.py", line 644, in children_to_nodes
    return [child_to_element(module, child, type) for child in children]
  File "/tmp/ansible_XTN7oc/ansible_module_xml.py", line 624, in child_to_element
    node = etree.Element(key, value)
  File "lxml.etree.pyx", line 2808, in lxml.etree.Element (src/lxml/lxml.etree.c:61236)
  File "apihelpers.pxi", line 123, in lxml.etree._makeElement (src/lxml/lxml.etree.c:13819)
  File "apihelpers.pxi", line 111, in lxml.etree._makeElement (src/lxml/lxml.etree.c:13693)
  File "apihelpers.pxi", line 263, in lxml.etree._initNodeAttributes (src/lxml/lxml.etree.c:15339)
  File "apihelpers.pxi", line 1529, in lxml.etree._attributeValidOrRaise (src/lxml/lxml.etree.c:26818)
ValueError: Invalid attribute name u'xsi:type'
```

##### ADDITIONAL INFORMATION

I can work around this by creating the elements without the namespaced attributes and running another task to add the attributes, but that ends up being a lot of extra tasks, and is much more confusing.

```yaml
  - name: Attribute filter Unverified RPs
    xml:
      path: /tmp/test.xml
      namespaces: *namespaces
      xpath: '/x:AttributeFilterPolicyGroup/x:AttributeFilterPolicy[@id = "UnverifiedRPs"]/x:PolicyRequirementRule'
      pretty_print: yes
      attribute: "xsi:type"
      value: "ANY"
```

**Comment by ryanpetrello** [comment]
Hey @icb-,

This looks like it could be an issue in ansible *itself*, not the awx project.  Would you reopen this at:

https://github.com/ansible/ansible/issues/new

Thanks!
