### ISSUE TITLE
"%" in credential password causes Python parsing exception

### ISSUE THREAD

**Issue by 01000101** [ansible/awx#484]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When using credentials (specifically tested with Cloudforms credentials), a password with a string interpolation special character ("%") causes the parser to raise an exception. This can be fixed by "escaping" the character in the password with "%%". So, a password that's "hello%world" could be input as "hello%%world" and it will work (no exception and successful password string). 

##### ENVIRONMENT
* AWX version: ansible-tower 3.1.5 (1.el7)
* AWX install method: ansible-tower-setup-3.1.5.tar.gz + install.sh
* Ansible version:  2.3.2.0 (2.el7)
* Operating System: Red Hat Enterprise Linux Server release 7.4 (Maipo)
* Web Browser: Chrome 61.0.3163.100 (Windows 10)

##### STEPS TO REPRODUCE

Add a new Cloudforms credential with a password containing a "%" symbol. Use that credential in a dynamic inventory source (also to Cloudforms). 

##### EXPECTED RESULTS

Password is accepted and sent as seen in the text box input. 

##### ACTUAL RESULTS

Inventory sync failed because of a string interpolation failure (parsing the password). 

##### ADDITIONAL INFORMATION

Exception log:

```
  1.339 INFO     Updating inventory 3: Cloudforms Dynamic
    1.358 INFO     Reading executable JSON source: /var/lib/awx/venv/tower/lib/python2.7/site-packages/awx/plugins/inventory/cloudforms.py
    1.474 ERROR    Failed to load JSON from: 
Traceback (most recent call last):
  File "/usr/bin/tower-manage", line 9, in <module>
    load_entry_point('ansible-tower==3.1.5', 'console_scripts', 'tower-manage')()
  File "/lib/python2.7/site-packages/awx/__init__.py", line 105, in manage
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/core/management/base.py", line 661, in handle
    return self.handle_noargs(**options)
  File "/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 1290, in handle_noargs
  File "/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 503, in load_inventory_source
  File "/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 392, in load
  File "/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 380, in command_to_json
RuntimeError: ['/var/lib/awx/venv/tower/lib/python2.7/site-packages/awx/plugins/inventory/cloudforms.py', '--list'] failed (rc=1) with output: Traceback (most recent call last):
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/awx/plugins/inventory/cloudforms.py", line 464, in <module>
    CloudFormsInventory()
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/awx/plugins/inventory/cloudforms.py", line 51, in __init__
    self.read_settings()
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/awx/plugins/inventory/cloudforms.py", line 140, in read_settings
    self.cloudforms_pw = config.get('cloudforms', 'password')
  File "/usr/lib64/python2.7/ConfigParser.py", line 623, in get
    return self._interpolate(section, option, value, d)
  File "/usr/lib64/python2.7/ConfigParser.py", line 691, in _interpolate
    self._interpolate_some(option, L, rawval, section, vars, 1)
  File "/usr/lib64/python2.7/ConfigParser.py", line 732, in _interpolate_some
    "'%%' must be followed by '%%' or '(', found: %r" % (rest,))
ConfigParser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%7K'
```

**Comment by matburt** [comment]
Honestly this looks like an Ansible cloudforms inventory script issue... can you try using this password with core ansible pointed at this inventory script and see if it has the same issue?  If so then we'll need to file a bug against upstream ansible.

**Comment by matburt** [comment]
Let us know if you can provide the requested info and we can re-open this one.
