### ISSUE TITLE
Unable to run 'awx-manage' after upgrade to awx 7.0.0

### ISSUE THREAD

**Issue by colinengland** [ansible/awx#4860]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After upgrade from 6.1.0.246 to unable to run awx-manage as not all the rh-python36 packages got installed.

##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: yum
* Ansible version:  2.8.4
* Operating System: Red Hat Enterprise Linux Server release 7.7
* Web Browser: N/A

##### STEPS TO REPRODUCE

Upgrade using steps on awx.wiki.

##### EXPECTED RESULTS

Upgraded successfully and working.

##### ACTUAL RESULTS

awx-manage was not able to run due to the following message:

# sudo -u awx scl enable rh-postgresql10 rh-python36 rh-git29 "GIT_PYTHON_REFRESH=quiet awx-manage makemigrations"
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==7.0.0', 'console_scripts', 'awx-manage')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 126, in manage
    prepare_env()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/__init__.py", line 91, in prepare_env
    if not settings.DEBUG: # pragma: no cover
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/settings/production.py", line 17, in <module>
    from .defaults import *  # NOQA
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/settings/defaults.py", line 8, in <module>
    from celery.schedules import crontab
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/schedules.py", line 13, in <module>
    from . import current_app
ImportError: cannot import name 'current_app'

##### ADDITIONAL INFORMATION

Was able to fix by re-running the yum install line for rh-python36* and single quoting the glob:
yum -y install --disablerepo='*' --enablerepo='copr:copr.fedorainfracloud.org:mrmeee:ansible-awx, rhel-7-server-rpms' -x '*-debuginfo' 'rh-python36*'

Might be worth updating the guide?

**Comment by ryanpetrello** [comment]
@colinengland not sure what's up here - sounds like you're using https://awx.wiki/installation?

You might want to reach out to folks maintaining that here: https://github.com/MrMEEE/awx-build/issues
