### ISSUE TITLE
Relation "django_session" does not exist

### ISSUE THREAD

**Issue by yasahmed** [ansible/awx#4894]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

when i try to start  ansible/awx_web container i got this error on log : 

```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/middleware/locale.py", line 21, in process_request
    language = translation.get_language_from_request(request, check_path=i18n_patterns_used)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/utils/translation/__init__.py", line 236, in get_language_from_request
    return _trans.get_language_from_request(request, check_path)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/utils/translation/trans_real.py", line 463, in get_language_from_request
    lang_code = request.session.get(LANGUAGE_SESSION_KEY)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 65, in get
    return self._session.get(key, default)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 194, in _get_session
    self._session_cache = self.load()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...

```
##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: docker for mac
* Ansible version:  2.8.4
* Operating System:Mac os
* Web Browser: chrome

##### STEPS TO REPRODUCE
` ansible-playbook -i inventory install.yml`

##### ACTUAL RESULTS
i got an error : `django.db.utils.ProgrammingError: relation "django_session" does not exist`

**Comment by ryanpetrello** [comment]
Hey @yasahmed,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC room:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by holdmypotion** [comment]
Hey, I'll be honest. I don't know about the specific type of bug/error you are getting. But I solved something similar, which I had on connecting an RDS(PostgreSQL) instance with a Django app, by migrating the class model migrations
```
python manage.py migrate
```
Hope it might help!
