### ISSUE TITLE
ipv6 hosts not working with AWX Ansible container solution 

### ISSUE THREAD

**Issue by achhabr1** [ansible/awx#5041]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by achhabr1** [comment]
ansible-playbook 2.8.4
2
  config file = /etc/ansible/ansible.cfg
3
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
4
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
5
  executable location = /usr/bin/ansible-playbook
6
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
7
Using /etc/ansible/ansible.cfg as config file
8
setting up inventory plugins
9
host_list declined parsing /tmp/awx_11_1eo5a1_2/tmp2pz7y79j as it did not pass it's verify_file() method
10
Parsed /tmp/awx_11_1eo5a1_2/tmp2pz7y79j inventory source with script plugin
11
Loading callback plugin awx_display of type stdout, v2.0 from /var/lib/awx/venv/awx/lib/python3.6/site-packages/ansible_runner/callbacks/awx_display.pyc
12
13
PLAYBOOK: vyatta_backup.yml ****************************************************
14
Positional arguments: ansible_development/vyatta/vyatta_backup.yml
15
remote_user: root
16
become_method: sudo
17
inventory: (u'/tmp/awx_11_1eo5a1_2/tmp2pz7y79j',)
18
forks: 5
19
tags: (u'all',)
20
extra_vars: (u'@/tmp/awx_11_1eo5a1_2/env/extravars',)
21
verbosity: 4
22
connection: smart
23
timeout: 10
24
1 plays in ansible_development/vyatta/vyatta_backup.yml
25
26
PLAY [Backup vyatta configurations] ********************************************
14:10:22
27
META: ran handlers
28
29
TASK [backup vyatta device configuration] **************************************
14:10:22
30
task path: /tmp/awx_11_1eo5a1_2/project/ansible_development/vyatta/vyatta_backup.yml:13
31
<fd:192:168:64:0:6:1062:1> attempting to start connection
32
<fd:192:168:64:0:6:1062:1> using connection plugin network_cli
33
<fd:192:168:64:0:6:1057:1> attempting to start connection
34
<fd:192:168:64:0:6:1057:1> using connection plugin network_cli
35
<fd:192:168:64:0:6:1062:1> local domain socket does not exist, starting it
36
<fd:192:168:64:0:6:1062:1> control socket path is /var/lib/awx/.ansible/pc/4b382fc7ad
37
<fd:192:168:64:0:6:1062:1> loaded cliconf plugin for network_os vyos
38
<fd:192:168:64:0:6:1062:1> 
39
The full traceback is:
40
Traceback (most recent call last):
41
  File "/usr/bin/ansible-connection", line 104, in start
42
    self.connection._connect()
43
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/network_cli.py", line 327, in _connect
44
    ssh = self.paramiko_conn._connect()
45
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 245, in _connect
46
    self.ssh = SSH_CONNECTION_CACHE[cache_key] = self._connect_uncached()
47
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 368, in _connect_uncached
48
    raise AnsibleConnectionFailure(msg)
49
AnsibleConnectionFailure: [Errno 99] Cannot assign requested address
50
51
<fd:192:168:64:0:6:1057:1> local domain socket does not exist, starting it
52
<fd:192:168:64:0:6:1057:1> control socket path is /var/lib/awx/.ansible/pc/b70cabf996
53
fatal: [fd:192:168:64:0:6:1062:1]: FAILED! => {
54
    "msg": "[Errno 99] Cannot assign requested address"
55
}
56
<fd:192:168:64:0:6:1057:1> loaded cliconf plugin for network_os vyos
57
<fd:192:168:64:0:6:1057:1> 
58
The full traceback is:
59
Traceback (most recent call last):
60
  File "/usr/bin/ansible-connection", line 104, in start
61
    self.connection._connect()
62
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/network_cli.py", line 327, in _connect
63
    ssh = self.paramiko_conn._connect()
64
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 245, in _connect
65
    self.ssh = SSH_CONNECTION_CACHE[cache_key] = self._connect_uncached()
66
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 368, in _connect_uncached
67
    raise AnsibleConnectionFailure(msg)
68
AnsibleConnectionFailure: [Errno 99] Cannot assign requested address
69
70
fatal: [fd:192:168:64:0:6:1057:1]: FAILED! => {
71
    "msg": "[Errno 99] Cannot assign requested address"
72
}
73
74
PLAY RECAP *********************************************************************
14:10:23
75
fd:192:168:64:0:6:1057:1   : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
76
fd:192:168:64:0:6:1062:1   : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by achhabr1** [comment]
AWX version: AWX 7.0.0.0
AWX install method: docker on linux
Ansible version: 2.8.4
Operating System: MacOS
Web Browser: Safari
