### ISSUE TITLE
Change secret_key and re-encrypt credentials

### ISSUE THREAD

**Issue by LucaBernstein** [ansible/awx#5079]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Currently it seems not possible to change the awx **secret_key** (from installer/inventory) to be able to change the credential encryption key - or is it possible?

Will this be supported in the future?

**Comment by ryanpetrello** [comment]
Hey @LucaBernstein,

It's possible to _change_ the key, but AWX doesn't currently have any tooling to decrypt and re-encrypt your secrets for you.  It's possible we might add functionality to support something like this in the future.

**Comment by ryanpetrello** [comment]
Hey @LucaBernstein I've opened a PR to add a new command for generating a new `SECRET_KEY` (if you're interested in trying it out):

https://github.com/ansible/awx/pull/5493

The intended usage here is to:

1.  Stop all running services.
2.  _Run_ the new command `awx-manage regenerate_secret_key` from *one* database-connected node.  The new key is printed, and can be replaced in your inventory.
3.  Start all services again.

**Comment by kdelee** [comment]
@elyezer is out on PTO for a while, but 90% sure this is ready to close

**Comment by kdelee** [comment]
Going to close as I reviewed his work and indeed while we can do some more work on running his automation on a regular basis and reporting it somewhere, we can test on demand and its working.

**Comment by hseitz-unwired** [comment]
Forgot to change awx_secret_key on deployment - found this and works like a charm 👍 thanks!

**Comment by haydenseitz** [comment]
Forgot to change awx_secret_key on deployment - found this and works like a charm 👍 thanks!

**Comment by bumpy44** [comment]
I've attempted this a few times now and what appears to happen is that it does indeed re-key the database secrets but fails to provide the new key and instead errors.  This is from AWX 17.1 on docker.

`bash-4.4# awx-manage regenerate_secret_key
2021-12-08 04:37:29,898 ERROR    awx.main.utils.encryption Failed to decrypt `Setting(pk=22).value`; if you've recently restored from a database backup or are running in a clustered environment, check that your `SECRET_KEY` value is correct
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/fernet.py", line 104, in _verify_signature
    h.verify(data[-32:])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/hazmat/primitives/hmac.py", line 66, in verify
    ctx.verify(signature)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/utils/encryption.py", line 170, in decrypt_field
    return smart_str(decrypt_value(key, value))
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/utils/encryption.py", line 143, in decrypt_value
    value = f.decrypt(encrypted)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/fernet.py", line 75, in decrypt
    return self._decrypt_data(data, timestamp, ttl)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/fernet.py", line 117, in _decrypt_data
    self._verify_signature(data)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/fernet.py", line 106, in _verify_signature
    raise InvalidToken
cryptography.fernet.InvalidToken
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/fernet.py", line 104, in _verify_signature
    h.verify(data[-32:])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/hazmat/primitives/hmac.py", line 66, in verify
    ctx.verify(signature)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 154, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/regenerate_secret_key.py", line 37, in handle
    self._survey_passwords()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/regenerate_secret_key.py", line 129, in _survey_passwords
    job.save(update_fields=["extra_vars"])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/unified_jobs.py", line 872, in save
    result = super(UnifiedJob, self).save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/polymorphic/models.py", line 93, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/base.py", line 199, in save
    super(PasswordFieldsModel, self).save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/base.py", line 320, in save
    super(PrimordialModel, self).save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/base.py", line 165, in save
    super(CreatedModifiedModel, self).save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/base.py", line 744, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/base.py", line 769, in save_base
    update_fields=update_fields,
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/signals.py", line 445, in activity_stream_update
    if not activity_stream_enabled:
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/signals.py", line 319, in __bool__
    return bool(self.enabled and getattr(settings, 'ACTIVITY_STREAM_ENABLED', True))
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/conf/settings.py", line 528, in __getattr_without_cache__
    return getattr(self._wrapped, name)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cachetools/decorators.py", line 22, in wrapper
    v = func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/conf/settings.py", line 441, in __getattr__
    value = self._get_local(name)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/conf/settings.py", line 356, in _get_local
    self._preload_cache()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/conf/settings.py", line 323, in _preload_cache
    value = decrypt_field(setting, 'value')
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/utils/encryption.py", line 170, in decrypt_field
    return smart_str(decrypt_value(key, value))
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/utils/encryption.py", line 143, in decrypt_value
    value = f.decrypt(encrypted)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/fernet.py", line 75, in decrypt
    return self._decrypt_data(data, timestamp, ttl)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/fernet.py", line 117, in _decrypt_data
    self._verify_signature(data)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/cryptography/fernet.py", line 106, in _verify_signature
    raise InvalidToken
cryptography.fernet.InvalidToken
`
