### ISSUE TITLE
AWX python error after Ansible run success

### ISSUE THREAD

**Issue by ansibleguy13** [ansible/awx#5111]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I am trying to run an AWX workflow template made up of 3 simple templates.  The first template completes with "Success" and the workflow moves on to the second template.  The second template completes with "Success", briefly, then throws the following error in the job pane on the left:

Error
STARTED
10/25/2019 9:25:44 AM
FINISHED
10/25/2019 9:29:40 AM
ERROR DETAILS
Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_9_a_i576bf' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_9_a_i576bf' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_9_a_i576bf' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_9_a_i576bf' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_9_a_i576bf' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_9_a_i576bf' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_9_a_i576bf' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_9_a_i576bf' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_9_a_i576bf' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_9_a_i576bf' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_9_a_i576bf' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_9_a_i576bf' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_9_a_i576bf' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_9_a_i576bf' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_9_a_i576bf' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/awx/main/tasks.py", line 1346, in run res = ansible_runner.interface.run(**params) File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/interface.py", line 178, in run r.run() File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 262, in run _delete() File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 258, in _delete res = _delete(retries=retries - 1) File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 258, in _delete res = _delete(retries=retries - 1) File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 258, in _delete res = _delete(retries=retries - 1) [Previous line repeated 11 more times] File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible_runner/runner.py", line 253, in _delete shutil.rmtree(self.config.process_isolation_path_actual) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 480, in rmtree _rmtree_safe_fd(fd, path, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd _rmtree_safe_fd(dirfd, fullname, onerror) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 422, in _rmtree_safe_fd onerror(os.rmdir, fullname, sys.exc_info()) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/shutil.py", line 420, in _rmtree_safe_fd os.rmdir(name, dir_fd=topfd) OSError: [Errno 16] Device or resource busy: 'awx_9_a_i576bf'

##### ENVIRONMENT
* AWX version: 7.0.0.599-1
* AWX install method: AWX rpm
* Ansible version:  2.8.5
* Operating System: CentOS 7.5
* Web Browser:

##### STEPS TO REPRODUCE

Create a workflow with multiple templates connected by success relationships and run

##### EXPECTED RESULTS

After seeing the ansible run succeed, I would expect the workflow to move on the next template instead of throwing an error

##### ACTUAL RESULTS

Ansible run succeeds, then workflow errors out

**Comment by ansibleguy13** [comment]
I initially thought this was a workflow issue, but then realized it happens when I run some templates, and not others.  The one that is working is not a simple ansible job, but one of the ones that is failing, all I did was print out a debug message for testing.  It fails consistently though, and the other succeeds consistently.  Any help is greatly appreciated.

**Comment by ryanpetrello** [comment]
This is a bug in `ansible-runner` itself, which we're currently working on addressing:

https://github.com/ansible/ansible-runner/issues/374

**Comment by 6sossomons** [comment]
Newest version fixes it for a few of us already..

**Comment by ryanpetrello** [comment]
Yep, we're working on a new release of `ansible-runner` shortly to address this.

**Comment by ryanpetrello** [comment]
This should be resolved for new installs once https://github.com/ansible/awx/pull/5117 is merged.

**Comment by ansibleguy13** [comment]
will there be a new AWX rpm released, or do I just have to grab the ansible-runner from somewhere?  Thanks!

**Comment by ryanpetrello** [comment]
Hey @ansibleguy13,

We don't build or publish RPMs for AWX.  In the coming weeks, we'll likely release another version of AWX that pins to the latest version of runner.

In the meantime, you can do so yourself via something like `/var/lib/awx/venv/awx/bin/pip install -U ansible-runner`.

**Comment by 6sossomons** [comment]
> will there be a new AWX rpm released, or do I just have to grab the ansible-runner from somewhere? Thanks!

MrMeee has already updated to the newest version of the RPMs using the newest runner.

**Comment by ansibleguy13** [comment]
Thank you all so much for your help.  It is very much appreciated.
