### ISSUE TITLE
Implement import/export functionality

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#5146]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

tower-cli has send/receive, for exporting subsets of AWX assets for import into another AWX instance. This is commonly used as a mechanism of "promoting" automation from a dev instance to a production instance.

It dumps full json structure, including dereferincing linked inventories/projects/etc by name, instead of ID, for portability.

We should figure out a way to handle this natively in AWX and/or its CLI.

**Comment by sumkincpp** [comment]
:+1: for that, also would be great to cover in identical way for awxkit and awx (i.e. through tower_send module). In awx this might be a management playbook, which internally uses tower_* modules.

> The AWX CLI doesn't currently have official support for backing up and restoring resources (similar to tower-cli send and tower-cli receive).
> 
> If you rely on this functionality, you should continue to use tower-cli at this time.

https://github.com/ansible/awx/blob/devel/awxkit/awxkit/cli/docs/source/examples.rst#backuprestore

**Comment by kdelee** [comment]
additional requirement:

need to update
```
awx_collection/plugins/modules/tower_receive.py
awx_collection/plugins/modules/tower_send.py
```
to use the awx cli based import/export

**Comment by jbradberry** [comment]
@kdelee no, those are being deprecated and new ones based around import/export are going to be written.

**Comment by elyezer** [comment]
This has been verified and it doing what is supposed to. There are couple more entities that I will be verifying but overall I have not found anything that would block getting this verified.

**Comment by adpavlov** [comment]
there is also workflow schema key, but it still not recognizes workflow_approval node:

```
 awx-cli workflow schema awx_pipeline_ACTIVITY_Full
Traceback (most recent call last):
  File "/bin/awx-cli", line 11, in <module>
    load_entry_point('ansible-tower-cli==3.3.4', 'console_scripts', 'awx-cli')()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tower_cli/conf.py", line 371, in method_with_context_managed
    method(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tower_cli/cli/resource.py", line 107, in func
    result = method(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tower_cli/resources/workflow.py", line 286, in schema
    existing_network = self._get_schema(wfjt)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tower_cli/resources/workflow.py", line 261, in _get_schema
    return self._workflow_node_structure(node_results)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tower_cli/resources/workflow.py", line 250, in _workflow_node_structure
    schema_dict.append(branch_schema(root_node_id))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tower_cli/resources/workflow.py", line 245, in branch_schema
    branch_schema(sub_node_id))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tower_cli/resources/workflow.py", line 233, in branch_schema
    ujt_key = JOB_TYPES[job_type]
KeyError: 'workflow_approval'
```
