### ISSUE TITLE
Fix intermittent failing test in JobTemplateForm.test.jsx

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#5234]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Seen this error on several PR builds now:

```
FAIL src/screens/Template/shared/JobTemplateForm.test.jsx (36.288s)
  ● <JobTemplateForm /> › should update form values on input changes

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: 

      108 |   });
      109 | 
    > 110 |   test('should update form values on input changes', async () => {
          |   ^
      111 |     let wrapper;
      112 |     await act(async () => {
      113 |       wrapper = mountWithContexts(

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.test (src/screens/Template/shared/JobTemplateForm.test.jsx:110:3)
      at Object.describe (src/screens/Template/shared/JobTemplateForm.test.jsx:10:1)
```

I tested this out locally and wasn't able to reproduce.

**Comment by jakemcdermott** [comment]
https://github.com/ansible/awx/pull/5250
