### ISSUE TITLE
force_boot rabbitmq if mnesia database exists

### ISSUE THREAD

**Issue by grahamn-gr** [ansible/awx#5314]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
We have PVCs attached to our rabbitMQ containers in Kubernetes for the mnesia database.
We ran in to this issue https://github.com/helm/charts/issues/13485 (with the provided AWX RabbitMQ 3.7.15 image).
Fix is to force_boot rabbitMQ if a PVC is already present

##### ENVIRONMENT
* AWX version: 8.0.0
* AWX install method: openshift
* Ansible version:  2.9.0
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Hard to replicate, but we had a storage issue and had to scale our pods to zero and back up again, when doing so the healthcheck failed:

```
Traceback (most recent call last):
  File "/usr/local/bin/healthchecks/rabbit_health_node.py", line 11, in <module>
    conn.request('GET', '/api/healthchecks/node', headers={'Authorization': 'Basic %s' % authsecret})
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 99] Address not available
```

This was due to rabbit not starting and it waiting for the mnesia tables:

```
2019-11-13 15:57:56.031 [info] <0.260.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
2019-11-13 15:58:26.032 [warning] <0.260.0> Error while waiting for Mnesia tables: {timeout_waiting_for_tables,[rabbit_user,rabbit_user_permission,rabbit_topic_permission,rabbit_vhost,rabbit_durable_route,rabbit_durable_exchange,rabbit_runtime_parameters,rabbit_durable_queue]}
2019-11-13 15:58:26.032 [info] <0.260.0> Waiting for Mnesia tables for 30000 ms, 8 retries left 
```

I had to remove the PVC for it to start correctly.

##### EXPECTED RESULTS

Rabbitmq starts

##### ACTUAL RESULTS

RabbitMQ goes in to a crashloop

##### ADDITIONAL INFORMATION

Adding the following to the sts allows for a force_boot if the database already exists. 

```
          command:
           - bash
           - -ec
           - |
             [[ -n "$DEBUG" ]] && set -x
             set -e

              if [ `id -u` -ge 500 ]; then
                 echo "rabbitmq:x:`id -u`:`id -g`:,,,:${HOME}:/bin/ash" >> /tmp/passwd
                 cat /tmp/passwd > /etc/passwd
                 rm /tmp/passwd
             fi

              echo "$RABBITMQ_ERLANG_COOKIE" > $HOME/.erlang.cookie
             chmod 0600 $HOME/.erlang.cookie
             if [ -d "/var/lib/rabbitmq/mnesia/${RABBITMQ_NODENAME}" ]; then rabbitmqctl force_boot; fi
             exec rabbitmq-server
```

This basically uses https://github.com/ansible/awx-rabbitmq/blob/master/launch.sh but adds the `if [ -d "/var/lib/rabbitmq/mnesia/${RABBITMQ_NODENAME}" ]; then rabbitmqctl force_boot; fi` line before starting rabbitmq-server. Rather than building a new container image, I override the starting command used.

**Comment by wenottingham** [comment]
Closing per https://github.com/ansible/awx-rabbitmq/pull/13
