### ISSUE TITLE
Container group execution throws an exception certificate authority data is omitted.

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#5326]
<img width="931" alt="image" src="https://user-images.githubusercontent.com/214912/68881287-dd150180-06da-11ea-9a14-fdef299b8906.png">

```python
Traceback (most recent call last):
  File "/awx_devel/awx/main/scheduler/kubernetes.py", line 55, in list_active_jobs
    for pod in pm.kube_api.list_namespaced_pod(
  File "/venv/awx/lib64/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/awx_devel/awx/main/scheduler/kubernetes.py", line 91, in kube_api
    config_dict=self.kube_config
  File "/venv/awx/lib64/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/awx_devel/awx/main/scheduler/kubernetes.py", line 83, in kube_config
    return generate_tmp_kube_config(self.credential, self.namespace)
  File "/awx_devel/awx/main/scheduler/kubernetes.py", line 178, in generate_tmp_kube_config
    credential.get_input('ssl_ca_cert').encode() # encode to bytes
  File "/awx_devel/awx/main/models/credential/__init__.py", line 288, in get_input
    raise AttributeError
AttributeError
```

**Comment by kdelee** [comment]
Confirmed this back in 3.6.1 times, just forgot to close this
