### ISSUE TITLE
Error if i try to install AWX with Docker

### ISSUE THREAD

**Issue by vampywiz17** [ansible/awx#5399]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Try to install AWX witch Docker

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: docker on linux,
* Ansible version:  2.9.1
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

sudo ansible-playbook -vvv -i inventory install.yml

##### EXPECTED RESULTS

Start Docker Container

##### ACTUAL RESULTS

```
TASK [local_docker : Start the containers] *****************************************************************************************************************************
task path: /home/vamp/awx-9.0.1/installer/roles/local_docker/tasks/compose.yml:26
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1574759693.33-267648285616553 `" && echo ansible-tmp-1574759693.33-267648285616553="` echo /root/.ansible/tmp/ansible-tmp-1574759693.33-267648285616553 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/docker/_docker_service.py
<localhost> PUT /root/.ansible/tmp/ansible-local-64224nD4cYc/tmpsts9qZ TO /root/.ansible/tmp/ansible-tmp-1574759693.33-267648285616553/AnsiballZ__docker_service.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1574759693.33-267648285616553/ /root/.ansible/tmp/ansible-tmp-1574759693.33-267648285616553/AnsiballZ__docker_service.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/env python /root/.ansible/tmp/ansible-tmp-1574759693.33-267648285616553/AnsiballZ__docker_service.py && sleep 0'

<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1574759693.33-267648285616553/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1574759693.33-267648285616553/AnsiballZ__docker_service.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1574759693.33-267648285616553/AnsiballZ__docker_service.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1574759693.33-267648285616553/AnsiballZ__docker_service.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.cloud.docker._docker_service', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_docker_service_payload_CMaDVf/ansible_docker_service_payload.zip/ansible/modules/cloud/docker/_docker_service.py", line 483, in <module>
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 12, in <module>
    from .. import config
  File "/usr/lib/python2.7/site-packages/compose/config/__init__.py", line 6, in <module>
    from .config import ConfigurationError
  File "/usr/lib/python2.7/site-packages/compose/config/config.py", line 50, in <module>
    from .validation import match_named_volumes
  File "/usr/lib/python2.7/site-packages/compose/config/validation.py", line 12, in <module>
    from jsonschema import Draft4Validator
  File "/usr/lib/python2.7/site-packages/jsonschema/__init__.py", line 33, in <module>
    import importlib_metadata as metadata
  File "/usr/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
  File "/usr/lib/python2.7/site-packages/zipp.py", line 12, in <module>
    import more_itertools
  File "/usr/lib/python2.7/site-packages/more_itertools/__init__.py", line 1, in <module>
    from more_itertools.more import *  # noqa
  File "/usr/lib/python2.7/site-packages/more_itertools/more.py", line 340
    def _collate(*iterables, key=lambda a: a, reverse=False):
                               ^
SyntaxError: invalid syntax

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1574759693.33-267648285616553/AnsiballZ__docker_service.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1574759693.33-267648285616553/AnsiballZ__docker_service.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1574759693.33-267648285616553/AnsiballZ__docker_service.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.docker._docker_service', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_docker_service_payload_CMaDVf/ansible_docker_service_payload.zip/ansible/modules/cloud/docker/_docker_service.py\", line 483, in <module>\n  File \"/usr/lib/python2.7/site-packages/compose/cli/command.py\", line 12, in <module>\n    from .. import config\n  File \"/usr/lib/python2.7/site-packages/compose/config/__init__.py\", line 6, in <module>\n    from .config import ConfigurationError\n  File \"/usr/lib/python2.7/site-packages/compose/config/config.py\", line 50, in <module>\n    from .validation import match_named_volumes\n  File \"/usr/lib/python2.7/site-packages/compose/config/validation.py\", line 12, in <module>\n    from jsonschema import Draft4Validator\n  File \"/usr/lib/python2.7/site-packages/jsonschema/__init__.py\", line 33, in <module>\n    import importlib_metadata as metadata\n  File \"/usr/lib/python2.7/site-packages/importlib_metadata/__init__.py\", line 9, in <module>\n    import zipp\n  File \"/usr/lib/python2.7/site-packages/zipp.py\", line 12, in <module>\n    import more_itertools\n  File \"/usr/lib/python2.7/site-packages/more_itertools/__init__.py\", line 1, in <module>\n    from more_itertools.more import *  # noqa\n  File \"/usr/lib/python2.7/site-packages/more_itertools/more.py\", line 340\n    def _collate(*iterables, key=lambda a: a, reverse=False):\n                               ^\nSyntaxError: invalid syntax\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

**Comment by ryanpetrello** [comment]
@vampywiz17 it looks like you're running this under python2; you'll need to use an `ansible-playbook` and `docker-compose` using python3.
