### ISSUE TITLE
ImportError: No module named concurrent.futures

### ISSUE THREAD

**Issue by anxstj** [ansible/awx#5462]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Running a task with *aws_s3* and python3 in a virtualenv results in *ImportError: No module named concurrent.futures*

##### ENVIRONMENT
* AWX version: 9.0.1 (or 9.2.0)
* AWX install method: docker
* Ansible version:  2.8.5 (or 2.9.2)
* Operating System: CentOS 8 (on Debian 9)
* Web Browser: Firefox 69

##### STEPS TO REPRODUCE

Use the following playbook:

```
---
- name: Deploy setup scripts to S3
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Upload setup.sh to S3
      aws_s3:
        bucket: mybuccker
        object: /setup.sh
        mode: put
        s3_url: https://s3.example.com
        src: ./setup.sh
        overwrite: different
```
In the Job Template choose *Ansible Environment*  = **/var/lib/awx/venv/ansible** or **Use default Environment**.

Create an inventory with localhost as only host. (`ansible_connection: local` does not matter)

```
{
    "id": 9,
    "type": "inventory",
    "name": "Localhost",
    "description": "Localhost-only",
    "organization": 7,
    "kind": "",
    "host_filter": null,
    "variables": "---\nansible_connection: local",
    "has_active_failures": true,
    "total_hosts": 1,
    "hosts_with_active_failures": 1,
    "total_groups": 0,
    "groups_with_active_failures": 0,
    "has_inventory_sources": false,
    "total_inventory_sources": 0,
    "inventory_sources_with_failures": 0,
    "insights_credential": null,
    "pending_deletion": false
```
With one host:

```
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 79,
            "name": "localhost",
            "description": "",
            "inventory": 9,
            "enabled": true,
            "instance_id": "",
            "variables": "",
            "has_active_failures": true,
            "has_inventory_sources": false,
            "last_job": 26136,
            "last_job_host_summary": 57121,
            "insights_system_id": null,
            "ansible_facts_modified": null
        }
    ]
}
```

##### EXPECTED RESULTS

```
TASK [Upload setup.sh to S3] ***********************************************
ok: [localhost]
```

##### ACTUAL RESULTS

```
TASK [Upload setup.sh to S3] ***********************************************
task path: /tmp/awx_15895_7ubsjj3y/project/deploy.yml:7
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1575625727.9322572-17569923605198 `" && echo ansible-tmp-1575625727.9322572-17569923605198="` echo /root/.ansible/tmp/ansible-tmp-1575625727.9322572-17569923605198 `" ) && sleep 0'
<localhost> EXEC /bin/sh -c 'test -e ./anx_setup.sh && sleep 0'
<localhost> Attempting python interpreter discovery
<localhost> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/cloud/amazon/aws_s3.py
<localhost> PUT /var/lib/awx/.ansible/tmp/ansible-local-27217am9moc_n/tmpoi6us8i4 TO /root/.ansible/tmp/ansible-tmp-1575625727.9322572-17569923605198/AnsiballZ_aws_s3.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1575625727.9322572-17569923605198/ /root/.ansible/tmp/ansible-tmp-1575625727.9322572-17569923605198/AnsiballZ_aws_s3.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1575625727.9322572-17569923605198/AnsiballZ_aws_s3.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1575625727.9322572-17569923605198/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1575625727.9322572-17569923605198/AnsiballZ_aws_s3.py", line 114, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1575625727.9322572-17569923605198/AnsiballZ_aws_s3.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1575625727.9322572-17569923605198/AnsiballZ_aws_s3.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_aws_s3_payload_kv_bhL/__main__.py", line 915, in <module>
  File "/tmp/ansible_aws_s3_payload_kv_bhL/__main__.py", line 760, in main
  File "/tmp/ansible_aws_s3_payload_kv_bhL/__main__.py", line 651, in get_s3_connection
  File "/tmp/ansible_aws_s3_payload_kv_bhL/ansible_aws_s3_payload.zip/ansible/module_utils/ec2.py", line 117, in boto3_conn
  File "/tmp/ansible_aws_s3_payload_kv_bhL/ansible_aws_s3_payload.zip/ansible/module_utils/ec2.py", line 151, in _boto3_conn
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/session.py", line 839, in create_client
    client_config=config, api_version=api_version)
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/client.py", line 80, in create_client
    cls = self._create_client_class(service_name, service_model)
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/client.py", line 110, in _create_client_class
    base_classes=bases)
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/boto3/utils.py", line 61, in _handler
    module = import_module(module)
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/boto3/utils.py", line 52, in import_module
    __import__(name)
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/boto3/s3/inject.py", line 15, in <module>
    from boto3.s3.transfer import create_transfer_manager
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/boto3/s3/transfer.py", line 127, in <module>
    from s3transfer.exceptions import RetriesExceededError as \\
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/s3transfer/__init__.py", line 134, in <module>
    import concurrent.futures
ImportError: No module named concurrent.futures
```

##### ADDITIONAL INFORMATION

```
bash-4.4# . /var/lib/awx/venv/ansible/bin/activate
(ansible) bash-4.4# pip freeze | grep s3
s3transfer==0.2.1
deactivate
bash-4.4# pip3 freeze | grep s3
bash-4.4# 
```
It seams that ansible uses `/usr/bin/python` instead of `/var/lib/awx/venv/ansible/bin/python`.

**Comment by anxstj** [comment]
This was a problem with the inventory. localhost must not be listed as "127.0.0.1".

localhost is always present, no need to define it. If it must be defined additionally, then the following should be used:

```
ansible_connection: local
ansible_python_interpreter: '{{ ansible_playbook_python }}'
```
