### ISSUE TITLE
can't play insights-client role

### ISSUE THREAD

**Issue by matt8754** [ansible/awx#5484]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When playing insights-client role in a tower, I hit this error
Traceback (most recent call last): File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 1255, in run self.pre_run_hook(self.instance, private_data_dir) File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 1846, in pre_run_hook job.project.scm_type, job_revision File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 2246, in make_local_copy copy_tree(project_path, destination_folder) 
File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dir_util.py", line 159, in copy_tree verbose=verbose, dry_run=dry_run)) 
File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dir_util.py", line 159, in copy_tree verbose=verbose, dry_run=dry_run)) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dir_util.py", line 159, in copy_tree verbose=verbose, dry_run=dry_run)) [Previous line repeated 121 more times] File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/dir_util.py", line 163, in copy_tree dry_run=dry_run) File "/opt/rh/rh-python36/root/usr/lib64/python3.6/distutils/file_util.py", line 105, in copy_file "can't copy '%s': doesn't exist or not a regular file" % src) distutils.errors.DistutilsFileError: can't copy '/var/lib/awx/projects/linux/manual/roles/redhatinsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/roles/RedHatInsights.insights-client/tests/example-insights-client-playbook.yml': doesn't exist or not a regular file

##### ENVIRONMENT
* AWX version: Tower 3.6
* Operating System: Linux

##### STEPS TO REPRODUCE
Install the insights-client role on the tower and run a job to play it.

##### EXPECTED RESULTS

The role can be played.

##### ACTUAL RESULTS

The role can't be played.

##### ADDITIONAL INFORMATION

The issue is caused by a symlink on this file.

https://github.com/RedHatInsights/insights-client-role/blob/master/tests/roles/RedHatInsights.insights-client

I think the issue is caused by this line.

https://github.com/ansible/awx/blob/devel/awx/main/tasks.py#L2218
It should call copy_tree like this:
copy_tree(project_path, destination_folder, preserve_symlinks=1)

**Comment by elyezer** [comment]
I was able that the reported issue is now fixed. Did the following to verify it:

1) Created a Project that synced https://github.com/RedHatInsights/insights-client-role.git
2) Created a JT that was linked to the project created on 1 and specified `tests/example-insights-client-playbook.yml` as the playbook to run
3) Launched the job and the role was properly run. The job has failed since the user running it doesn't have sudo permission but the "can't copy file" is not raised anymore.

![Screenshot from 2020-05-05 18-08-59](https://user-images.githubusercontent.com/48132/81120886-9a025100-8efb-11ea-94d7-7d79fe54107a.png)

With all that said we can consider this as being verified.
