### ISSUE TITLE
AWX 9.0.1 Not able to create OpenStack dynamic inventory when sourced from GIT

### ISSUE THREAD

**Issue by artuja** [ansible/awx#5535]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

I want to create a dynamic openstack inventory. When I use a custom script as an inventory source it works as expected. But when the same script is sourced from GIT as a project, the following error occurs

    2.578 INFO     Updating inventory 9: CNI-UNDERCLOUD
    3.096 DEBUG    Using base command: python /usr/bin/ansible-inventory -i /tmp/awx_158_36ca2aqh/project/openstack.py --playbook-dir /tmp/awx_158_36ca2aqh/project -vvvvv
    3.096 INFO     Reading Ansible inventory source: /tmp/awx_158_36ca2aqh/project/openstack.py
    3.098 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    3.098 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    3.098 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==9.0.1.0', 'console_scripts', 'awx-manage')()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 158, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1153, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1043, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 214, in load
    return self.command_to_json(base_args + ['--list'])
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 197, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Oct  7 2019, 17:58:22) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /tmp/awx_158_36ca2aqh/project/openstack.py as it did not pass it's verify_file() method
auto declined parsing /tmp/awx_158_36ca2aqh/project/openstack.py as it did not pass it's verify_file() method
yaml declined parsing /tmp/awx_158_36ca2aqh/project/openstack.py as it did not pass it's verify_file() method
toml declined parsing /tmp/awx_158_36ca2aqh/project/openstack.py as it did not pass it's verify_file() method
 [WARNING]:  * Failed to parse /tmp/awx_158_36ca2aqh/project/openstack.py with
script plugin: Inventory script (/tmp/awx_158_36ca2aqh/project/openstack.py)
had an execution error: Traceback (most recent call last):   File
"/tmp/awx_158_36ca2aqh/project/openstack.py", line 64, in <module>     import
openstack as sdk   File "/tmp/awx_158_36ca2aqh/project/openstack.py", line 65,
in <module>     from openstack.cloud import inventory as sdk_inventory
ModuleNotFoundError: No module named 'openstack.cloud'; 'openstack' is not a
package
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 268, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/script.py", line 161, in parse
    raise AnsibleParserError(to_native(e))
 [WARNING]:  * Failed to parse /tmp/awx_158_36ca2aqh/project/openstack.py with
ini plugin: /tmp/awx_158_36ca2aqh/project/openstack.py:54: Expected key=value
host variable assignment, got: argparse
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 268, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/ini.py", line 138, in parse
    raise AnsibleParserError(e)
 [WARNING]: Unable to parse /tmp/awx_158_36ca2aqh/project/openstack.py as an
inventory source
ERROR! No inventory was parsed, please check your configuration and options.

**Comment by ryanpetrello** [comment]
@AlanCoding any ideas here?

**Comment by AlanCoding** [comment]
There are a lot of layers to this. I did previously double-check this against the version of the openstack script that the built-in source is using, and the imports match. So the Ansible venv should have the necessary requirements. Moving on from that, I am _relatively_ sure that we all share the expectation that SCM inventory updates have the Ansible venv python libraries made available, and obviously have the system site packages accessible as well (this is where Ansible typically resides, but not always).

So this could be expressing that the default Ansible venv libraries are, unexpectedly, not available for SCM inventory sources. But that requires some additional verification. If it does boil down to that, then I would love to develop a simplified test case for it. There are multiple ways that this bug could be introduced (management command logic, bubblewrap, etc.).

But I don't know that is what we're dealing with.

It would really help this issue if we could get a public github repo to test with. So you could paste your existing repo, or create a new one with the same openstack.py in it and verify that you still hit the issue with that?

**Comment by artuja** [comment]
I'm using the inventory script available here https://github.com/artuja/openstack-repository.git

**Comment by AlanCoding** [comment]
I am able to successfully run an openstack inventory update using that script.

here are some relevant parts of my job environment if you want to compare

```json
    "job_env": {
        "OS": " Operating System: Docker Desktop",
        "LC_ALL": "en_US.UTF-8",
        "RABBITMQ_VHOST": "/",
        "LANG": "\"en-us\"",
        "HOSTNAME": "awx",
        "OLDPWD": "/awx_devel",
        "RABBITMQ_USER": "guest",
        "VIRTUAL_ENV": "/venv/awx",
        "MFLAGS": "-w",
        "RABBITMQ_PASS": "**********",
        "RABBITMQ_HOST": "rabbitmq",
        "PWD": "/awx_devel",
        "HOME": "/var/lib/awx",
        "SUPERVISOR_PROCESS_NAME": "awx-dispatcher",
        "SDB_HOST": "0.0.0.0",
        "SUPERVISOR_ENABLED": "1",
        "SDB_PORT": "7899",
        "MAKELEVEL": "2",
        "SHLVL": "2",
        "LANGUAGE": "en_US:en",
        "SUPERVISOR_GROUP_NAME": "tower-processes",
        "AWX_GROUP_QUEUES": "tower",
        "CURRENT_UID": "501",
        "PATH": "/venv/awx/bin:/venv/awx/bin:/venv/awx/bin:/usr/local/n/versions/node/10.15.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "PS1": "(awx) ",
        "SUPERVISOR_SERVER_URL": "unix:///tmp/supervisor.sock",
        "MAKEFLAGS": "w",
        "_": "/venv/awx/bin/python3",
        "DJANGO_SETTINGS_MODULE": "awx.settings.development",
        "DJANGO_LIVE_TEST_SERVER_ADDRESS": "localhost:9013-9199",
        "SDB_NOTIFY_HOST": "docker.for.mac.host.internal",
        "TZ": "UTC",
        "ANSIBLE_FORCE_COLOR": "True",
        "ANSIBLE_HOST_KEY_CHECKING": "False",
        "ANSIBLE_INVENTORY_UNPARSED_FAILED": "True",
        "ANSIBLE_PARAMIKO_RECORD_HOST_KEYS": "False",
        "ANSIBLE_VENV_PATH": "/venv/ansible",
        "AWX_PRIVATE_DATA_DIR": "/tmp/awx_11_fjdcpti3",
        "INVENTORY_SOURCE_ID": "14",
        "INVENTORY_UPDATE_ID": "11",
        "ANSIBLE_INVENTORY_EXPORT": "True",
        "ANSIBLE_VERBOSE_TO_STDERR": "True",
        "ANSIBLE_COLLECTIONS_PATHS": "/tmp/awx_11_fjdcpti3/requirements_collections:~/.ansible/collections:/usr/share/ansible/collections",
        "OS_CLIENT_CONFIG_FILE": "/tmp/awx_11_fjdcpti3/tmpd6mvei3j",
        "ANSIBLE_CALLBACK_PLUGINS": "/venv/awx/lib/python3.6/site-packages/ansible_runner/callbacks",
        "ANSIBLE_STDOUT_CALLBACK": "awx_display",
        "ANSIBLE_RETRY_FILES_ENABLED": "False",
        "AWX_ISOLATED_DATA_DIR": "/tmp/awx_11_fjdcpti3/artifacts/11",
        "PYTHONPATH": "/venv/awx/lib/python3.6/site-packages/ansible_runner/callbacks",
        "RUNNER_OMIT_EVENTS": "False",
        "RUNNER_ONLY_FAILED_EVENTS": "False"
    },
```
