### ISSUE TITLE
docker_compose error

### ISSUE THREAD

**Issue by rovshango** [ansible/awx#5576]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Installer

##### SUMMARY
Facing errors at docker_compose step

##### ENVIRONMENT
* AWX version: 9.1.0
* AWX install method: docker in linux
* Ansible version:  2.9.1
* Operating System: CentOS Linux release 7.7.1908 (Core)
* Web Browser:

##### STEPS TO REPRODUCE

I have installed docker, docker module and docker-compose with pip and pulled awx repo

##### EXPECTED RESULTS

AWX installation as expected

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1577733859.32-87533721083053/AnsiballZ_docker_compose.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1577733859.32-87533721083053/AnsiballZ_docker_compose.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1577733859.32-87533721083053/AnsiballZ_docker_compose.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.cloud.docker.docker_compose', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_docker_compose_payload_OKzNba/ansible_docker_compose_payload.zip/ansible/modules/cloud/docker/docker_compose.py", line 483, in <module>
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 12, in <module>
    from .. import config
  File "/usr/lib/python2.7/site-packages/compose/config/__init__.py", line 6, in <module>
    from .config import ConfigurationError
  File "/usr/lib/python2.7/site-packages/compose/config/config.py", line 50, in <module>
    from .validation import match_named_volumes
  File "/usr/lib/python2.7/site-packages/compose/config/validation.py", line 12, in <module>
    from jsonschema import Draft4Validator
  File "/usr/lib/python2.7/site-packages/jsonschema/__init__.py", line 33, in <module>
    import importlib_metadata as metadata
  File "/usr/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
  File "/usr/lib/python2.7/site-packages/zipp.py", line 12, in <module>
    import more_itertools
  File "/usr/lib/python2.7/site-packages/more_itertools/__init__.py", line 1, in <module>
    from .more import *  # noqa
  File "/usr/lib/python2.7/site-packages/more_itertools/more.py", line 460
    yield from iterable
             ^
SyntaxError: invalid syntax

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1577733859.32-87533721083053/AnsiballZ_docker_compose.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1577733859.32-87533721083053/AnsiballZ_docker_compose.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1577733859.32-87533721083053/AnsiballZ_docker_compose.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.docker.docker_compose', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_docker_compose_payload_OKzNba/ansible_docker_compose_payload.zip/ansible/modules/cloud/docker/docker_compose.py\", line 483, in <module>\n  File \"/usr/lib/python2.7/site-packages/compose/cli/command.py\", line 12, in <module>\n    from .. import config\n  File \"/usr/lib/python2.7/site-packages/compose/config/__init__.py\", line 6, in <module>\n    from .config import ConfigurationError\n  File \"/usr/lib/python2.7/site-packages/compose/config/config.py\", line 50, in <module>\n    from .validation import match_named_volumes\n  File \"/usr/lib/python2.7/site-packages/compose/config/validation.py\", line 12, in <module>\n    from jsonschema import Draft4Validator\n  File \"/usr/lib/python2.7/site-packages/jsonschema/__init__.py\", line 33, in <module>\n    import importlib_metadata as metadata\n  File \"/usr/lib/python2.7/site-packages/importlib_metadata/__init__.py\", line 9, in <module>\n    import zipp\n  File \"/usr/lib/python2.7/site-packages/zipp.py\", line 12, in <module>\n    import more_itertools\n  File \"/usr/lib/python2.7/site-packages/more_itertools/__init__.py\", line 1, in <module>\n    from .more import *  # noqa\n  File \"/usr/lib/python2.7/site-packages/more_itertools/more.py\", line 460\n    yield from iterable\n             ^\nSyntaxError: invalid syntax\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
```

**Comment by rovshango** [comment]
Hello,
After following install (downgrade actually) AWX installation went as expected
`pip install more-itertools==5.0.0`
