### ISSUE TITLE
Stuck in "working" before launching a system job

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#558]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When I go to launch a system job, the UI gets stuck with the "working" message in the lower corner.

##### ENVIRONMENT
* AWX version: 0579db1162146d65a8cc3aed19da76e81b149ae6
* Operating System: Mac
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Click on the launch button for a system job. Close the window with the prompts.

##### EXPECTED RESULTS

Not stuck

##### ACTUAL RESULTS

```
angular.js:14700 TypeError: Cannot read property '$setPristine' of undefined
    at onOpen (http://localhost:8013/static/js/app.feb8ec489925d2c4c2f0.js:80966:44)
    at HTMLDivElement.open (http://localhost:8013/static/js/app.feb8ec489925d2c4c2f0.js:61233:21)
    at $.(anonymous function).(anonymous function)._trigger (http://localhost:8013/static/js/vendor.4c1b9c38e5c8ab72ad49.js:51424:13)
    at $.(anonymous function).(anonymous function).open (http://localhost:8013/static/js/vendor.4c1b9c38e5c8ab72ad49.js:60489:8)
    at $.(anonymous function).(anonymous function).open (http://localhost:8013/static/js/vendor.4c1b9c38e5c8ab72ad49.js:51040:25)
    at HTMLDivElement.<anonymous> (http://localhost:8013/static/js/vendor.4c1b9c38e5c8ab72ad49.js:51132:39)
    at Function.each (http://localhost:8013/static/js/vendor.4c1b9c38e5c8ab72ad49.js:14403:19)
    at jQuery.fn.init.each (http://localhost:8013/static/js/vendor.4c1b9c38e5c8ab72ad49.js:14175:17)
    at jQuery.fn.init.$.fn.(anonymous function) [as dialog] (http://localhost:8013/static/js/vendor.4c1b9c38e5c8ab72ad49.js:51122:9)
    at http://localhost:8013/static/js/app.feb8ec489925d2c4c2f0.js:81012:35
```

##### ADDITIONAL INFORMATION

This only happens with the job for
 - Cleanup Activity Stream
 - Cleanup Job Details

It is not triggered by going to launch Cleanup Fact Details.

If I click the launch button on cleanup fact details, I get

```
Uncaught TypeError: Cannot read property 'value' of undefined
    at HTMLDivElement.onClick (card.controller.js:123)
    at HTMLButtonElement.props.click (jquery-ui.js:10036)
    at HTMLButtonElement.dispatch (jquery.js:4737)
    at HTMLButtonElement.elemData.handle (jquery.js:4549)
```

**Comment by AlanCoding** [comment]
I am still able to reproduce this.

**Comment by jaredevantabor** [comment]
This is fixed in devel now.
