### ISSUE TITLE
GCP Inventory sync failed 

### ISSUE THREAD

**Issue by 1it** [ansible/awx#559]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
GCP Inventory sync failed 

##### ENVIRONMENT
* AWX version: 1.0.1.137
* AWX install method: docker on linux
* Ansible version:  2.4.1.0 
* Operating System: Ubuntu Xenial
* Web Browser: Google Chrome 61.0.3163.100

##### STEPS TO REPRODUCE
Create GCP service account, add credentials to AWX
Create new inventory, add source Google Compute Engine. Click "Sync All"

##### EXPECTED RESULTS

Inventory synced, new hosts added to inventory.

##### ACTUAL RESULTS

```
2017-11-02 12:14:49,687 INFO     awx.main.commands.inventory_import Updating inventory 2: Default
2017-11-02 12:14:49,695 INFO     awx.main.commands.inventory_import Reading Ansible inventory source: /usr/lib/python2.7/site-packages/awx/plugins/inventory/gce.py
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==1.0.1.137', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 107, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 661, in handle
    return self.handle_noargs(**options)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 1000, in handle_noargs
    self.is_custom)
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 243, in load_inventory_source
    is_custom=is_custom).load()
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 179, in load
    data = self.command_to_json(base_args + ['--list'])
  File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 163, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=4) with stdout:

stderr:
ERROR! Could not parse inventory source /usr/lib/python2.7/site-packages/awx/plugins/inventory/gce.py with available plugins:
Plugin script failed: Inventory script (/usr/lib/python2.7/site-packages/awx/plugins/inventory/gce.py) had an execution error: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awx/plugins/inventory/gce.py", line 78, in <module>
    import pkg_resources
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3037, in <module>
    @_call_aside
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3021, in _call_aside
    f(*args, **kwargs)
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3050, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pkg_resources/__init__.py", line 969, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pkg_resources/__init__.py", line 855, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycrypto>=2.6' distribution was not found and is required by the application

 
Plugin ini failed: /usr/lib/python2.7/site-packages/awx/plugins/inventory/gce.py:19: Error parsing host definition ''''': No closing quotation
```

##### ADDITIONAL INFORMATION
<img width="1397" alt="2017-11-02 15 38 36" src="https://user-images.githubusercontent.com/7093190/32326460-f7825940-bfe3-11e7-9756-6b007e5097a0.png">

**Comment by matburt** [comment]
I think this should fix it up for you: https://github.com/ansible/awx/commit/74c9b9cf6aef09a60e19cff60eff3cbbbcbf1abf

You can either build the image yourself manually to test it out or wait for the nightly official images to build.
