### ISSUE TITLE
Failed to read /api. GET status: 500 A server error has occured

### ISSUE THREAD

**Issue by icepilot** [ansible/awx#5595]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I have tried deploying AWX following the install notes from (https://github.com/ansible/awx/blob/devel/INSTALL.md) severl times now, on multiple platforms (Ubuntu 16.04, Ubuntu 18.04, and CentOS 7). All attempts have resulted in this same error when attempting to login through the web page.

##### ENVIRONMENT
* AWX version: 9.1.0
* AWX install method: docker on linux
* Ansible version:  2.9.2
* Operating System: Ubuntu 16.04 Desktop
* Web Browser: Firefox 71.0

##### STEPS TO REPRODUCE

From a clean install of Ubuntu 16.04:
- apt update && apt upgrade -y
- Clone the repo
    - https://github.com/ansible/awx
    - https://github.com/ansible/awx-logos

- Install Ansible
    - sudo apt-add-repository --yes --update ppa:ansible/ansible
    - apt update
    - sudo apt install ansible
        - Ansible version: 2.9.2

- Install Docker
    - sudo apt install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt update
    - sudo apt install -y docker-ce docker-ce-cli containerd.io
    - sudo docker run hello-world
        - hello-world ran as expected
    - sudo systemctl enable docker
    - sudo systemctl start docker
    - Added user to the docker group

- Install docker-compose
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - docker-compose --version
        - 1.25.0, build b42d419

- Install/Update pip
    - sudo apt install -y python-pip python3-pip
    - sudo python3 -m pip install pip --upgrade --force
    - sudo python -m pip install pip --upgrade --force

- Installed the Docker SDK for python module:
    - pip install docker
    - pip3 install docker

- Installed the docker-compose python module:
    - pip install docker-compose
    - pip3 install docker-compose

- Installed Node/NPM
    - curl -k -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
    - chmod +x nodesource_setup.sh
    - ./nodesource_setup.sh
    - sudo apt update
    - sudo apt install -y nodejs
        - node -v: 10.18.0
        - npm -v: 6.13.4

- Make changes to the installer/inventory file:
    - Since this is my 5th time trying to deploy this, I left everything as default config with the exception of "awx_official=true"

- Run the Installer:
    - ansible-playbook -i inventory install.yml
        - Everything appears to have successfully run...
![playbook](https://user-images.githubusercontent.com/35821934/71786278-e6c63180-2fc6-11ea-9fbf-9a7dc7e66bca.PNG)
    - docker ps
![docker_ps](https://user-images.githubusercontent.com/35821934/71786304-36a4f880-2fc7-11ea-82a6-4312b675e09e.PNG)

##### EXPECTED RESULTS

Due to not seeing any issues through the build process, and the expected containers being deployed, I though everything would work as intended...

##### ACTUAL RESULTS

- When I attempt to navigate to the site (http://localhost) on Firefox 71.0, I get the error message:
Failed to read /api. GET status: 500 A server error has occured
![Error](https://user-images.githubusercontent.com/35821934/71786382-132e7d80-2fc8-11ea-844f-ac514062dff8.PNG)

- I attempted to ignore the message, and try logging in using the default credentials (as I did not modify these in the installer/inventory file).
![Ignore](https://user-images.githubusercontent.com/35821934/71786414-4b35c080-2fc8-11ea-9d1d-e9db04d39f7f.PNG)

##### ADDITIONAL INFORMATION

Looking at the logs:
- docker logs -f awx_task

Using /etc/ansible/ansible.cfg as config file
127.0.0.1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "elapsed": 0,
    "match_groupdict": {},
    "match_groups": [],
    "path": null,
    "port": 5432,
    "search_regex": null,
    "state": "started"
}
Using /etc/ansible/ansible.cfg as config file
127.0.0.1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "elapsed": 0,
    "match_groupdict": {},
    "match_groups": [],
    "path": null,
    "port": 11211,
    "search_regex": null,
    "state": "started"
}
Using /etc/ansible/ansible.cfg as config file
127.0.0.1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "elapsed": 18,
    "match_groupdict": {},
    "match_groups": [],
    "path": null,
    "port": 5672,
    "search_regex": null,
    "state": "started"
}
Using /etc/ansible/ansible.cfg as config file
127.0.0.1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "db": "awx"
}
2020-01-05 20:10:34,056 DEBUG    awx.main.dispatch publish awx.main.tasks.set_migration_flag(0758a23f-05e2-42cf-89ab-19eb95d79351, queue=tower_broadcast_all)
Operations to perform:
  Apply all migrations: auth, conf, contenttypes, main, oauth2_provider, sessions, sites, social_django, sso, taggit
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/kombu/utils/functional.py", line 42, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==9.1.0.0', 'console_scripts', 'awx-manage')()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 165, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/commands/migrate.py", line 193, in handle
    self.verbosity, self.interactive, connection.alias, apps=pre_migrate_apps, plan=plan,
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/sql.py", line 34, in emit_pre_migrate_signal
    **kwargs
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/apps.py", line 8, in raise_migration_flag
    set_migration_flag.delay()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/publish.py", line 67, in delay
    return cls.apply_async(args, kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/publish.py", line 103, in apply_async
    routing_key=queue)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/kombu/messaging.py", line 187, in _publish
    channel = self.channel
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/kombu/messaging.py", line 209, in _get_channel
    channel = self._channel = channel()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/kombu/utils/functional.py", line 44, in __call__
    value = self.__value__ = self.__contract__()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/kombu/messaging.py", line 224, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/kombu/connection.py", line 852, in default_channel
    self.ensure_connection(**conn_opts)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/kombu/connection.py", line 422, in ensure_connection
    callback, timeout=timeout)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/kombu/utils/functional.py", line 341, in retry_over_time
    return fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/kombu/connection.py", line 275, in connect
    return self.connection
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/kombu/connection.py", line 823, in connection
    self._connection = self._establish_connection()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/kombu/connection.py", line 778, in _establish_connection
    conn = self.transport.establish_connection()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/amqp/connection.py", line 313, in connect
    self.drain_events(timeout=self.connect_timeout)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/amqp/connection.py", line 500, in drain_events
    while not self.blocking_read(timeout):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/amqp/connection.py", line 506, in blocking_read
    return self.on_inbound_frame(frame)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/amqp/connection.py", line 510, in on_inbound_method
    method_sig, payload, content,
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/amqp/abstract_channel.py", line 126, in dispatch_method
    listener(*args)
  **File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/amqp/connection.py", line 639, in _on_close
    (class_id, method_id), ConnectionError)
amqp.exceptions.AccessRefused: (0, 0): (403) ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.**
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "auth_user" does not exist
LINE 1: INSERT INTO "auth_user" ("password", "last_login", "is_super...
                    ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==9.1.0.0', 'console_scripts', 'awx-manage')()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 165, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/commands/shell.py", line 92, in handle
    exec(sys.stdin.read())
  File "<string>", line 1, in <module>
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/auth/models.py", line 162, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/auth/models.py", line 145, in _create_user
    user.save(using=self._db)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/contrib/auth/base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "auth_user" does not exist
LINE 1: INSERT INTO "auth_user" ("password", "last_login", "is_super...
                    ^

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "main_instance" does not exist
LINE 1: SELECT (1) AS "a" FROM "main_instance" WHERE "main_instance"...
                               ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django_pglocks/__init__.py", line 74, in advisory_lock
    yield acquired
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/utils/pglock.py", line 14, in advisory_lock
    yield internal_lock
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/managers.py", line 125, in register
    if instance.exists():
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 766, in exists
    return self.query.has_results(using=self.db)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 522, in has_results
    return compiler.has_results()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1070, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "main_instance" does not exist
LINE 1: SELECT (1) AS "a" FROM "main_instance" WHERE "main_instance"...
                               ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

**Comment by wenottingham** [comment]
@shanemcd is this the migration issue we are looking at a new release for?

**Comment by wenottingham** [comment]
Please try with the latest release - we believe it will resolve this.
