### ISSUE TITLE
500 server error on token delete

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/awx#5640]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
500 server error when deleting token. First observed when QE test `tests.api.auth.test_application_tokens.TestApplicationTokens.test_delete_token[True]` failed. From the stack trace; this is the problem area https://github.com/ansible/awx/blob/devel/awx/main/models/oauth.py#L124

I'm not sure why there is an exists check right before the save(). If it's to prevent a race condition, it only narrows the window. A delete can still happen between the exists and the save.

##### ADDITIONAL INFORMATION

tower.log
```
2020-01-10 16:51:08,402 ERROR    django.request Internal Server Error: /api/v2/tokens/5/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/transaction.py", line 284, in __exit__
    connection.set_autocommit(True)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 410, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 636, in run_and_clear_commit_hooks
    func()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/models/oauth.py", line 124, in <lambda>
    connection.on_commit(lambda: self.save(update_fields=['last_used']))
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/models/oauth.py", line 134, in save
    super(OAuth2AccessToken, self).save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/base.py", line 855, in _save_table
    raise DatabaseError("Save with update_fields did not affect any rows.")
django.db.utils.DatabaseError: Save with update_fields did not affect any rows.
```

**Comment by kdelee** [comment]
@chrismeyersfsu have you rebased? This is a bug that just got fixed/test that just got added.

https://github.com/ansible/awx/issues/5478

**Comment by chrismeyersfsu** [comment]
I rebased this morning and in re-running the tests, it's now passing.
