### ISSUE TITLE
VMware dynamic inventory fails in awx 9.1.0 with py env 3

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#5648]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Not able to update vmware inventory. 

I tried the approach tried here: [https://github.com/ansible/awx/issues/4156](url) but did not resolve the issue.

##### ENVIRONMENT
* AWX version: 9.1.0
* AWX install method: docker on linux
* Ansible version:  2.9,2

##### STEPS TO REPRODUCE

AWX 9.1.0 installed and setup a "VMware vCenter" inventory. 
This worked in AWX 6.1.0 with ansible 2.8.6.

##### EXPECTED RESULTS

Update of inventory.

##### ACTUAL RESULTS

```
    4.545 INFO     Updating inventory 28: VCENTER_INVENTORY
    5.489 INFO     Reading Ansible inventory source: /var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py
    5.495 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    5.495 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/var/lib/awx/venv/awx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    5.496 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 11, in <module>
    load_entry_point('awx==9.1.0', 'console_scripts', 'awx-manage')()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 165, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1158, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1048, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 215, in load
    return self.command_to_json(base_args + ['--list'])
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 198, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.6.8 (default, Oct  7 2019, 17:58:22) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]
Using /etc/ansible/ansible.cfg as config file
[WARNING]:  * Failed to parse /var/lib/awx/venv/awx/lib64/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py with script plugin:
Inventory script (/var/lib/awx/venv/awx/lib64/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py) had an execution error:
Traceback (most recent call last):   File
"/var/lib/awx/venv/awx/lib64/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 792, in <module>
print(VMWareInventory().show())   File
"/var/lib/awx/venv/awx/lib64/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 146, in __init__
self.do_api_calls_update_cache()   File
"/var/lib/awx/venv/awx/lib64/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 185, in
do_api_calls_update_cache     self.inventory =
self.instances_to_inventory(self.get_instances())   File
"/var/lib/awx/venv/awx/lib64/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 364, in get_instances
return self._get_instances(kwargs)   File
"/var/lib/awx/venv/awx/lib64/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py", line 381, in
_get_instances     if not si: UnboundLocalError: local variable 'si' referenced
before assignment

  File "/usr/local/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/local/lib/python3.6/site-packages/ansible/plugins/inventory/script.py", line 161, in parse
    raise AnsibleParserError(to_native(e))

[WARNING]: Unable to parse /var/lib/awx/venv/awx/lib64/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py as an inventory source

ERROR! No inventory was parsed, please check your configuration and options.
```

**Comment by ryanpetrello** [comment]
@nicolaibaralmueller,

This looks like a bug in the VMWare inventory plugin code itself:

https://github.com/ansible/ansible/blob/devel/contrib/inventory/vmware_inventory.py#L366-L383

Based on my reading of this code, it looks to me like you're entering this code block:

https://github.com/ansible/ansible/blame/devel/contrib/inventory/vmware_inventory.py#L372

...meaning some form of `ssl.SSLError` is being thrown.

**Comment by jladdjr** [comment]
@nicolaibaralmueller - agree w/ @ryanpetrello; looks like you're hitting an ssl exception. Posted a fix for undefined var. That should at least give the ssl exception a chance to surface correctly.

Fwiw, we're currently working on migrating awx from the vmware inventory script to the [new plugin system](https://github.com/ansible/ansible/blob/stable-2.9/lib/ansible/plugins/inventory/vmware_vm_inventory.py).

**Comment by jladdjr** [comment]
@nicolaibaralmueller - going to mark this as resolved. If you hit any further issues here, feel free to re-open.

**Comment by nicolaibaralmueller** [comment]
@ryanpetrello @jladdjr Great but how do I resolve the issue right now?!

**Comment by ryanpetrello** [comment]
@nicolaibaralmueller,

AWX is an open source project that we make available free of charge. While we do our best to address reported issues in a timely manner, it’s simply impossible for us to provide immediate hands-on support for every issue.

In this case, the actual bug is in an inventory script included with Ansible, not AWX.  @jladdjr went out of his way to open a pull request against Ansible that should address your issue (https://github.com/ansible/ansible/pull/66482) and it was merged yesterday.

We'll pull this change into the next release of AWX (as we have time), but until then, you'll just have to come up with a workaround on your own.

**Comment by nicolaibaralmueller** [comment]
@ryanpetrello Yes I realize that. Just seems like a vmware inventory bug would be a high priority. 

I replaced the existing vmware_inventory.py with the latest from devel but a new error appeared. Opening a ansible git issue for that.
