### ISSUE TITLE
AWX Inventory - Satellite 6

### ISSUE THREAD

**Issue by Caidran** [ansible/awx#57]
### Summary

Unable to import inventory from Satellite 6

### Environment

* AWX version: devel
* Ansible version:  2.3.1
* Operating System: RHEL 7.3

### Steps To Reproduce:

Attempt to add a Satellite 6 inventory source.

### Expected Results:

AWX should import hosts from Satellite. 

### Actual Results:

2017-09-08 09:30:12,250 INFO     awx.main.commands.inventory_import Updating inventory 2: UNIX
2017-09-08 09:30:12,265 INFO     awx.main.commands.inventory_import Reading Ansible inventory source: /usr/lib/python2.7/site-packages/awx/plugins/inventory/foreman.py

The task hangs at this stage, previously I had a bunch of stuff in here about investigating this on the host however I wasn't doing so within the docker container so all of my investigation was useless. :)

That being said, the satellite import still hangs however I'll continue investigating from within the container after the weekend and hopefully get to the bottom of it.

**Comment by matburt** [comment]
Were you ever able to get any more information about this?

**Comment by matburt** [comment]
This seems to be working fine in our tests, since you haven't provided any more information I'm going to close this. Comment if you have more details

**Comment by ish-xyz** [comment]
With Satellite 6.2 I get this error:

AWX is trying to get the ID 496 that does not exist in the Satellite appliance.

ERROR! Could not parse inventory source /usr/lib/python2.7/site-packages/awx/plugins/inventory/foreman.py with available plugins:
Plugin script failed: Inventory script (/usr/lib/python2.7/site-packages/awx/plugins/inventory/foreman.py) had an execution error: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awx/plugins/inventory/foreman.py", line 379, in <module>
    sys.exit(not ForemanInventory().run())
  File "/usr/lib/python2.7/site-packages/awx/plugins/inventory/foreman.py", line 374, in run
    self.get_inventory()
  File "/usr/lib/python2.7/site-packages/awx/plugins/inventory/foreman.py", line 327, in get_inventory
    self.update_cache()
  File "/usr/lib/python2.7/site-packages/awx/plugins/inventory/foreman.py", line 259, in update_cache
    params = self._resolve_params(host)
  File "/usr/lib/python2.7/site-packages/awx/plugins/inventory/foreman.py", line 183, in _resolve_params
    for param in self._get_all_params_by_id(host['id']):
  File "/usr/lib/python2.7/site-packages/awx/plugins/inventory/foreman.py", line 174, in _get_all_params_by_id
    ret = self._get_json(url, [404])
  File "/usr/lib/python2.7/site-packages/awx/plugins/inventory/foreman.py", line 149, in _get_json
    ret.raise_for_status()
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://xxxxx.xxxx.net/api/v2/hosts/496?per_page=250&page=1

**Comment by wenottingham** [comment]
That error comes from the satellite server - it would need to be handled in the inventory script. File a bug upstream at https://github.com/ansible/ansible/issues if it's repeatable.

**Comment by dLobatog** [comment]
@ish-xyz Do you still get that error? If so, what's on /var/log/foreman/production.log? Particularly curious about the 500 server error

**Comment by dLobatog** [comment]
@ish-xyz Do you still get that error? If so, what's on /var/log/foreman/production.log? Particularly curious about the 500 server error
