### ISSUE TITLE
upgrade to AWX 9.1.1 Openstack inventories and modules start to fail

### ISSUE THREAD

**Issue by dvntstph** [ansible/awx#5821]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Upgraded AWX from 7.0.0 to 9.1.1. 
On previous release I was able to manage Openstack environment using AWX.
In 9.1.1 inventories in AWX using Openstack as inventory source fails to enumerate/parse.
Also observed other Openstack specific problems: ansible module os_server behaviour is no longer idempotent - fails in a playbook run if server already exists.

##### ENVIRONMENT
* AWX 9.1.1
* AWX install method: docker on linux 
* Ansible version: 2.8.5
* Operating System: Ubuntu 18.04
* Web Browser: Chrome Version 79.0.3945.130

##### STEPS TO REPRODUCE

Provisioned fresh host for AWX install.
Downloaded and Installed AWX 7.0.0 from source https://github.com/ansible/awx/archive/7.0.0.zip
`ansible-playbook -i inventory install.yml`

Added valid Openstack credential.
Created new inventory with source type set to Openstack. Used created credential.
Inventory is imported as expected from Openstack

Upgrade to AWX 9.1.1

```
docker rm -f awx_task
docker rm -f awx_web
docker rm -f awx_rabbitmq
docker rm -f awx_memcached
git clone https://github.com/ansible/awx.git
cd awx/installer
ansible-playbook -i inventory install.yml
```
Repeat steps to add inventory 
Add valid Openstack credential.
Create new inventory with source type set to Openstack. Used created credential.
Inventory fails to import.

##### EXPECTED RESULTS

Expected same behaviour as with previous versions of AWX

##### ACTUAL RESULTS

Openstack Inventories fail to import in AWX 9.1.1
Openstack Ansible module _os_server_ behaviour is no longer idempotent. If server exists, _os_server_ task in playbook fails instead of returning OK

##### ADDITIONAL INFORMATION

**Output of inventory import job from AWX** 

```
    4.133 INFO     Updating inventory 2: devzero.edu-openstack-inventory
    5.050 INFO     Reading Ansible inventory source: /tmp/awx_1_xcdosmqu/openstack.yml
    5.057 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    5.057 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    5.057 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1158, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1048, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 215, in load
    return self.command_to_json(base_args + ['--list'])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 198, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Oct  7 2019, 17:58:22) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]
Using /etc/ansible/ansible.cfg as config file
 [WARNING]:  * Failed to parse /tmp/awx_1_xcdosmqu/openstack.yml with auto
plugin: 'id'
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 268, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/auto.py", line 58, in parse
    plugin.parse(inventory, loader, path, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/openstack.py", line 207, in parse
    expand=expand_hostvars, fail_on_cloud_config=fail_on_errors)
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/openstack/cloud/inventory.py", line 68, in list_hosts
    all_projects=all_projects):
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/openstack/cloud/_compute.py", line 346, in list_servers
    bare=bare)
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/openstack/cloud/_compute.py", line 367, in _list_servers
    for server in servers
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/openstack/cloud/_compute.py", line 367, in <listcomp>
    for server in servers
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/openstack/cloud/_compute.py", line 570, in _expand_server
    return meta.get_hostvars_from_server(self, server)
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/openstack/cloud/meta.py", line 487, in get_hostvars_from_server
    flavor_id = server['flavor']['id']
 [WARNING]: Unable to parse /tmp/awx_1_xcdosmqu/openstack.yml as an inventory
source
ERROR! No inventory was parsed, please check your configuration and options.
```
**Output of os_server playbook** 

```
{
    "module_stdout": "",
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1580866261.3807242-193074254864696/AnsiballZ_os_server.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1580866261.3807242-193074254864696/AnsiballZ_os_server.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1580866261.3807242-193074254864696/AnsiballZ_os_server.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/lib64/python3.6/imp.py\", line 235, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib64/python3.6/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 618, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_os_server_payload_o8lamfm8/__main__.py\", line 753, in <module>\n  File \"/tmp/ansible_os_server_payload_o8lamfm8/__main__.py\", line 743, in main\n  File \"/tmp/ansible_os_server_payload_o8lamfm8/__main__.py\", line 669, in _get_server_state\n  File \"/tmp/ansible_os_server_payload_o8lamfm8/__main__.py\", line 417, in _exit_hostvars\n  File \"/var/lib/awx/venv/ansible/lib/python3.6/site-packages/openstack/cloud/_compute.py\", line 1889, in get_openstack_vars\n    return meta.get_hostvars_from_server(self, server)\n  File \"/var/lib/awx/venv/ansible/lib/python3.6/site-packages/openstack/cloud/meta.py\", line 487, in get_hostvars_from_server\n    flavor_id = server['flavor']['id']\nKeyError: 'id'\n",
    "exception": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1580866261.3807242-193074254864696/AnsiballZ_os_server.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1580866261.3807242-193074254864696/AnsiballZ_os_server.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1580866261.3807242-193074254864696/AnsiballZ_os_server.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/lib64/python3.6/imp.py\", line 235, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib64/python3.6/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 618, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_os_server_payload_o8lamfm8/__main__.py\", line 753, in <module>\n  File \"/tmp/ansible_os_server_payload_o8lamfm8/__main__.py\", line 743, in main\n  File \"/tmp/ansible_os_server_payload_o8lamfm8/__main__.py\", line 669, in _get_server_state\n  File \"/tmp/ansible_os_server_payload_o8lamfm8/__main__.py\", line 417, in _exit_hostvars\n  File \"/var/lib/awx/venv/ansible/lib/python3.6/site-packages/openstack/cloud/_compute.py\", line 1889, in get_openstack_vars\n    return meta.get_hostvars_from_server(self, server)\n  File \"/var/lib/awx/venv/ansible/lib/python3.6/site-packages/openstack/cloud/meta.py\", line 487, in get_hostvars_from_server\n    flavor_id = server['flavor']['id']\nKeyError: 'id'\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1,
    "_ansible_no_log": false,
    "changed": false
}

```

**Comment by ryanpetrello** [comment]
looks related: https://github.com/ansible/ansible/issues/63894

**Comment by ryanpetrello** [comment]
related: https://github.com/openstack/openstacksdk/commit/9874fa81d7227b9ab41a5448bca55d1ac265f3e7

**Comment by ryanpetrello** [comment]
It looks like this was fixed in a newer version of `openstacksdk`.  I'm guessing the issue would go away if we updated:

https://github.com/ansible/awx/blob/devel/requirements/requirements_ansible.in#L64

to:

https://github.com/openstack/openstacksdk/releases/tag/0.37.0

**Comment by ryanpetrello** [comment]
@AlanCoding can you take a peek at this one as part of our recent dependency upgrades?

**Comment by AlanCoding** [comment]
This looks like a _super_ simple request, but just need to get a grasp on all the changes we're getting.

version was released Oct 24, 2019. Prior one was June 13, 2019.

https://github.com/openstack/openstacksdk/commits/0.37.0/releasenotes/notes

These look pretty bug-related

**Comment by kdelee** [comment]
Running inventory updates against a devstack that we use for testing, this works.

Going to close, please try this out @dvntstph and ping me if you have any trouble
