### ISSUE TITLE
Can't start AWX web, connection rabbitmq, postgres timeout

### ISSUE THREAD

**Issue by tatdatpham** [ansible/awx#5833]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 9.1.1
* AWX install method: docker on centos8
* Ansible version:  2.9.3
* Operating System: Centos 8
* Web Browser: Chrome latest

##### STEPS TO REPRODUCE

Install awx follow command
```
ansible-playbook -i inventory install.yml
```

All container is up
```
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                                 NAMES
756ed3d8a7e2        ansible/awx_task:9.1.1       "/tini -- /bin/sh -c…"   About an hour ago   Up About an hour    8052/tcp                                              awx_task
ffb7cfb55ba5        ansible/awx_web:9.1.1        "/tini -- /bin/sh -c…"   About an hour ago   Up About an hour    0.0.0.0:80->8052/tcp                                  awx_web
a3a1f2724640        postgres:10                  "docker-entrypoint.s…"   About an hour ago   Up About an hour    5432/tcp                                              awx_postgres
ff2a5734c174        memcached:alpine             "docker-entrypoint.s…"   About an hour ago   Up About an hour    11211/tcp                                             awx_memcached
54685e6e1512        ansible/awx_rabbitmq:3.7.4   "docker-entrypoint.s…"   About an hour ago   Up About an hour    4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp   awx_rabbitmq

```

Docker network information
```
[root@Ansible ~]# docker network ls
NETWORK ID          NAME                  DRIVER              SCOPE
f618ce3566df        bridge                bridge              local
f390a293d3cb        docker_data_default   bridge              local
18bedebad701        host                  host                local
778c0b26d644        none                  null                local

```

```
[root@Ansible ~]# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' awx_postgres awx_task awx_memcached awx_web awx_rabbitmq
172.23.0.4
172.23.0.5
172.23.0.2
172.23.0.6
172.23.0.3
```
AWX_POSTGRES 
```
PostgreSQL init process complete; ready for start up.

2020-02-06 06:42:26.453 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-02-06 06:42:26.453 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2020-02-06 06:42:26.456 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-02-06 06:42:26.468 UTC [65] LOG:  database system was shut down at 2020-02-06 06:42:26 UTC
2020-02-06 06:42:26.472 UTC [1] LOG:  database system is ready to accept connections

PostgreSQL Database directory appears to contain a database; Skipping initialization

2020-02-06 06:42:36.881 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-02-06 06:42:36.881 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2020-02-06 06:42:36.883 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-02-06 06:42:36.893 UTC [26] LOG:  database system was interrupted; last known up at 2020-02-06 06:42:26 UTC
2020-02-06 06:42:36.904 UTC [26] LOG:  database system was not properly shut down; automatic recovery in progress
2020-02-06 06:42:36.905 UTC [26] LOG:  invalid record length at 0/16360D0: wanted 24, got 0
2020-02-06 06:42:36.905 UTC [26] LOG:  redo is not required
2020-02-06 06:42:36.912 UTC [1] LOG:  database system is ready to accept connections
```

AWX_RABBITMQ
```
2020-02-06 06:42:42.666 [info] <0.278.0>
 Starting RabbitMQ 3.7.4 on Erlang 20.1.7
 Copyright (C) 2007-2018 Pivotal Software, Inc.
 Licensed under the MPL.  See http://www.rabbitmq.com/
2020-02-06 06:42:42.667 [info] <0.278.0>
 node           : rabbit@54685e6e1512
 home dir       : /var/lib/rabbitmq
 config file(s) : /etc/rabbitmq/rabbitmq.conf
 cookie hash    : at619UOZzsenF44tSK3ulA==
 log(s)         : <stdout>
 database dir   : /var/lib/rabbitmq/mnesia/rabbit@54685e6e1512
2020-02-06 06:42:42.891 [info] <0.284.0> Memory high watermark set to 3125 MiB (3276904857 bytes) of 7812 MiB (8192262144 bytes) total
2020-02-06 06:42:42.894 [info] <0.286.0> Enabling free disk space monitoring
2020-02-06 06:42:42.894 [info] <0.286.0> Disk free limit set to 50MB
2020-02-06 06:42:42.896 [info] <0.288.0> Limiting to approx 1048476 file handles (943626 sockets)
2020-02-06 06:42:42.896 [info] <0.289.0> FHC read buffering:  OFF
2020-02-06 06:42:42.896 [info] <0.289.0> FHC write buffering: ON
2020-02-06 06:42:42.898 [info] <0.278.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
2020-02-06 06:42:42.929 [info] <0.278.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
2020-02-06 06:42:42.929 [info] <0.278.0> Peer discovery backend rabbit_peer_discovery_classic_config does not support registration, skipping registration.
2020-02-06 06:42:42.930 [info] <0.278.0> Priority queues enabled, real BQ is rabbit_variable_queue
2020-02-06 06:42:42.933 [info] <0.317.0> Starting rabbit_node_monitor
2020-02-06 06:42:42.961 [info] <0.278.0> Management plugin: using rates mode 'basic'
2020-02-06 06:42:42.962 [info] <0.343.0> Making sure data directory '/var/lib/rabbitmq/mnesia/rabbit@54685e6e1512/msg_stores/vhosts/5A7PFSQL4N28PQOL0INDFDDLU' for vhost 'awx' exists
2020-02-06 06:42:42.964 [info] <0.343.0> Starting message stores for vhost 'awx'
2020-02-06 06:42:42.964 [info] <0.347.0> Message store "5A7PFSQL4N28PQOL0INDFDDLU/msg_store_transient": using rabbit_msg_store_ets_index to provide index
2020-02-06 06:42:42.965 [info] <0.343.0> Started message store of type transient for vhost 'awx'
2020-02-06 06:42:42.966 [info] <0.350.0> Message store "5A7PFSQL4N28PQOL0INDFDDLU/msg_store_persistent": using rabbit_msg_store_ets_index to provide index
2020-02-06 06:42:42.966 [warning] <0.350.0> Message store "5A7PFSQL4N28PQOL0INDFDDLU/msg_store_persistent": rebuilding indices from scratch
2020-02-06 06:42:42.967 [info] <0.343.0> Started message store of type persistent for vhost 'awx'
2020-02-06 06:42:42.970 [info] <0.385.0> started TCP Listener on [::]:5672
2020-02-06 06:42:42.970 [info] <0.278.0> Setting up a table for connection tracking on this node: tracked_connection_on_node_rabbit@54685e6e1512
2020-02-06 06:42:42.970 [info] <0.278.0> Setting up a table for per-vhost connection counting on this node: tracked_connection_per_vhost_on_node_rabbit@54685e6e1512
2020-02-06 06:42:42.971 [info] <0.33.0> Application rabbit started on node rabbit@54685e6e1512
2020-02-06 06:42:42.973 [info] <0.33.0> Application rabbitmq_management_agent started on node rabbit@54685e6e1512
2020-02-06 06:42:42.973 [info] <0.33.0> Application rabbitmq_web_dispatch started on node rabbit@54685e6e1512
2020-02-06 06:42:43.002 [info] <0.436.0> Management plugin started. Port: 15672
2020-02-06 06:42:43.002 [info] <0.542.0> Statistics database started.
2020-02-06 06:42:43.003 [info] <0.33.0> Application rabbitmq_management started on node rabbit@54685e6e1512
 completed with 3 plugins.
2020-02-06 06:42:43.155 [info] <0.5.0> Server startup complete; 3 plugins started.
 * rabbitmq_management
 * rabbitmq_web_dispatch
 * rabbitmq_management_agent
```

##### EXPECTED RESULTS
AWX is running successful
##### ACTUAL RESULTS

I cant access to AWX via browser. When i checked log on awx_task. i got error:
```
2020-02-06 07:57:42,241 INFO exited: dispatcher (exit status 1; not expected)
2020-02-06 07:57:43,247 INFO spawned: 'dispatcher' with pid 473
2020-02-06 07:57:44,250 INFO success: dispatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-02-06 07:57:59,330 WARNING  kombu.mixins Broker connection error, trying again in 32.0 seconds: timeout('timed out',).
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/transport.py", line 137, in _connect
    host, port, family, socket.SOCK_STREAM, SOL_TCP)
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/utils/functional.py", line 344, in retry_over_time
    return fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/connection.py", line 283, in connect
    return self.connection
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/connection.py", line 839, in connection
    self._connection = self._establish_connection()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/connection.py", line 794, in _establish_connection
    conn = self.transport.establish_connection()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/connection.py", line 311, in connect
    self.transport.connect()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/transport.py", line 77, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/transport.py", line 148, in _connect
    "failed to resolve broker hostname"))
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/transport.py", line 161, in _connect
    self.sock.connect(sa)
socket.timeout: timed out
RESULT 2
OKREADY
2020-02-06 07:58:36,378 WARNING  kombu.mixins Broker connection error, trying again in 32.0 seconds: timeout('timed out',).
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/transport.py", line 137, in _connect
    host, port, family, socket.SOCK_STREAM, SOL_TCP)
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/utils/functional.py", line 344, in retry_over_time
    return fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/connection.py", line 283, in connect
    return self.connection
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/connection.py", line 839, in connection
    self._connection = self._establish_connection()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/connection.py", line 794, in _establish_connection
    conn = self.transport.establish_connection()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/connection.py", line 311, in connect
    self.transport.connect()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/transport.py", line 77, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/transport.py", line 148, in _connect
    "failed to resolve broker hostname"))
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/transport.py", line 161, in _connect
    self.sock.connect(sa)
socket.timeout: timed out

```

**Comment by ryanpetrello** [comment]
Hey @tatdatpham,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
