### ISSUE TITLE
Add Approval-Node-Handling to workflow.py

### ISSUE THREAD

**Issue by moonrail** [ansible/awx#5878]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
As approval nodes are a welcome addition to workflows in AWX they should be usable via awx-cli and Ansible module tower_workflow_template.

Currently awx-cli generates this output on getting a schema with at least one Approval-Node:

```bash
$ awx-cli workflow schema 67
*** DETAILS: Getting records. *************************************************
GET https://<host>/api/v2/workflow_job_template_nodes/
Params: [('workflow_job_template', 67)]

Traceback (most recent call last):
  File "/home/<user>/.local/bin/awx-cli", line 11, in <module>
    load_entry_point('ansible-tower-cli==3.3.7', 'console_scripts', 'awx-cli')()
  File "/home/<user>/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/<user>/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/<user>/.local/lib/python2.7/site-packages/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/home/<user>/.local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/<user>/.local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/<user>/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/<user>/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/<user>/.local/lib/python2.7/site-packages/tower_cli/conf.py", line 373, in method_with_context_managed
    method(*args, **kwargs)
  File "/home/<user>/.local/lib/python2.7/site-packages/tower_cli/cli/resource.py", line 107, in func
    result = method(*args, **kwargs)
  File "/home/<user>/.local/lib/python2.7/site-packages/tower_cli/resources/workflow.py", line 286, in schema
    existing_network = self._get_schema(wfjt)
  File "/home/<user>/.local/lib/python2.7/site-packages/tower_cli/resources/workflow.py", line 261, in _get_schema
    return self._workflow_node_structure(node_results)
  File "/home/<user>/.local/lib/python2.7/site-packages/tower_cli/resources/workflow.py", line 250, in _workflow_node_structure
    schema_dict.append(branch_schema(root_node_id))
  File "/home/<user>/.local/lib/python2.7/site-packages/tower_cli/resources/workflow.py", line 245, in branch_schema
    branch_schema(sub_node_id))
  File "/home/<user>/.local/lib/python2.7/site-packages/tower_cli/resources/workflow.py", line 233, in branch_schema
    ujt_key = JOB_TYPES[job_type]
KeyError: u'workflow_approval'
```

**Comment by ryanpetrello** [comment]
Hey @moonrail,

This is a bug in the deprecated `tower-cli` tool:  https://github.com/ansible/tower-cli

We're unlikely to address this - you might want to consider moving to the new official AWX CLI:

https://groups.google.com/d/msg/awx-project/ZAlhpLMBzVw/TLvSW5cDBAAJ

**Comment by moonrail** [comment]
Hi @ryanpetrello,

please note, that I do use the awx-cli, as visible in posted output.

Additionally I just upgraded to the current version of awx-cli and am still experiencing this issue:
```
$ pip3 install --user "https://github.com/ansible/awx/archive/9.1.1.tar.gz#egg=awxkit&subdirectory=awxkit"
(...)
Successfully built awxkit
Installing collected packages: awxkit
Successfully installed awxkit-9.1.1
$ awx-cli --version
Tower CLI 3.3.7
$ awx-cli workflow schema 67
*** DETAILS: Getting records. *************************************************
GET https://<host>/api/v2/workflow_job_template_nodes/
Params: [('workflow_job_template', 67)]

Traceback (most recent call last):
  File "/home/jg/.local/bin/awx-cli", line 11, in <module>
    load_entry_point('ansible-tower-cli==3.3.7', 'console_scripts', 'awx-cli')()
  File "/home/jg/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jg/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jg/.local/lib/python2.7/site-packages/tower_cli/cli/base.py", line 129, in invoke
    return super(TowerCLI, self).invoke(ctx)
  File "/home/jg/.local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jg/.local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jg/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jg/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jg/.local/lib/python2.7/site-packages/tower_cli/conf.py", line 373, in method_with_context_managed
    method(*args, **kwargs)
  File "/home/jg/.local/lib/python2.7/site-packages/tower_cli/cli/resource.py", line 107, in func
    result = method(*args, **kwargs)
  File "/home/jg/.local/lib/python2.7/site-packages/tower_cli/resources/workflow.py", line 286, in schema
    existing_network = self._get_schema(wfjt)
  File "/home/jg/.local/lib/python2.7/site-packages/tower_cli/resources/workflow.py", line 261, in _get_schema
    return self._workflow_node_structure(node_results)
  File "/home/jg/.local/lib/python2.7/site-packages/tower_cli/resources/workflow.py", line 250, in _workflow_node_structure
    schema_dict.append(branch_schema(root_node_id))
  File "/home/jg/.local/lib/python2.7/site-packages/tower_cli/resources/workflow.py", line 245, in branch_schema
    branch_schema(sub_node_id))
  File "/home/jg/.local/lib/python2.7/site-packages/tower_cli/resources/workflow.py", line 233, in branch_schema
    ujt_key = JOB_TYPES[job_type]
KeyError: u'workflow_approval'
```

So if this is related to old tower-cli, what am I doing wrong?


Edit:
If you mean, I should be using `awx` instead of `awx-cli`; what is the way to go to define Workflow-Schemata? In old `tower-cli` and `awx-cli` one can define a scheme in convenient syntax - is this now deprecated?

**Comment by ryanpetrello** [comment]
@moonrail,

You're using https://github.com/ansible/tower-cli.  The code in the traceback you provided is from that Python package:

https://github.com/ansible/tower-cli/blob/master/tower_cli/resources/workflow.py#L233

The official AWX CLI doesn't have support for exporting and importing a workflow schema - that work is being tracked here:

https://github.com/ansible/awx/issues/5146
