### ISSUE TITLE
AWX 9.2 vmware_inventory.py TLS v1 not supported

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#6138]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

It is not possible to connect to vmware vsphere (TLSv1) since at least AWX version 8.

TLSv1 needs to be enabled/supported!

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.5

##### ACTUAL RESULTS

Output when synching with vsphere:

(It complains about username or password but that is a wrong error message. I can connect no problem with the account and the error message when using vmware_guest is different.)

```
    3.375 INFO     Updating inventory 28: Vcenter Inventory
    4.108 INFO     Reading Ansible inventory source: /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/plugins/inventory/vmware_inventory.py
    4.112 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    4.113 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    4.113 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1157, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1047, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 215, in load
    return self.command_to_json(base_args + ['--list'])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 198, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.9.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
Using /etc/ansible/ansible.cfg as config file
[WARNING]:  * Failed to parse /var/lib/awx/venv/awx/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py with script plugin:
Inventory script (/var/lib/awx/venv/awx/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py) had an execution error:
Could not connect to the specified host using specified username and password

  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/script.py", line 161, in parse
    raise AnsibleParserError(to_native(e))

[WARNING]: Unable to parse /var/lib/awx/venv/awx/lib/python3.6/site-
packages/awx/plugins/inventory/vmware_inventory.py as an inventory source

ERROR! No inventory was parsed, please check your configuration and options.
```

Output when using vmware_guest to build a new VM:

```
Unable to connect to vCenter or ESXi API at virtualcenter.local on TCP/443: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:897)
```

I tried adding support for TLSv1 by adding the below lines inside vmware_inventory.py but the installed openssl does not know the TLSVersion parameter: 

```
context.options &= ~ssl.OP_NO_TLSv1_3 & ~ssl.OP_NO_TLSv1_2 & ~ssl.OP_NO_TLSv1_1
context.minimum_version = ssl.TLSVersion.TLSv1
```

```
def get_instances(self):
        ''' Get a list of vm instances with pyvmomi '''
        kwargs = {'host': self.server,
                  'user': self.username,
                  'pwd': self.password,
                  'port': int(self.port)}

        if self.validate_certs and hasattr(ssl, 'SSLContext'):
            context = ssl.SSLContext(ssl.PROTOCOL_TLS)
            context.options &= ~ssl.OP_NO_TLSv1_3 & ~ssl.OP_NO_TLSv1_2 & ~ssl.OP_NO_TLSv1_1
            context.minimum_version = ssl.TLSVersion.TLSv1
            context.verify_mode = ssl.CERT_REQUIRED
            context.check_hostname = True
            kwargs['sslContext'] = context
        elif self.validate_certs and not hasattr(ssl, 'SSLContext'):
            sys.exit('pyVim does not support changing verification mode with python < 2.7.9. Either update '
                     'python or use validate_certs=false.')
        elif not self.validate_certs and hasattr(ssl, 'SSLContext'):
            context = ssl.SSLContext(ssl.PROTOCOL_TLS)
            context.options &= ~ssl.OP_NO_TLSv1_3 & ~ssl.OP_NO_TLSv1_2 & ~ssl.OP_NO_TLSv1_1
            context.minimum_version = ssl.TLSVersion.TLSv1
            context.verify_mode = ssl.CERT_NONE
            context.check_hostname = False
            kwargs['sslContext'] = context
        elif not self.validate_certs and not hasattr(ssl, 'SSLContext'):
            # Python 2.7.9 < or RHEL/CentOS 7.4 <
            pass

        return self._get_instances(kwargs)

```
```AttributeError:` module 'ssl' has no attribute 'TLSVersion```

**Comment by wenottingham** [comment]
You'd likely need to set a crypto profile on the container image; you'd need to rebuild the image.

See https://github.com/ansible/awx/issues/6039 for a similar case.

**Comment by nicolaibaralmueller** [comment]
> You'd likely need to set a crypto profile on the container image; you'd need to rebuild the image.
> 
> See #6039 for a similar case.

Thanks. That solved the issue. I hope there will be an inventory setting for this in future releases.
