### ISSUE TITLE
App doesn't start after fresh install to docker on RHEL7

### ISSUE THREAD

**Issue by hiddenicon** [ansible/awx#623]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Fresh install to docker on RHEL from git repo using the ansible playbook. Application does not come up at all after install. 
 This has been running on this host before, did removal of containers to install fresh again from the github repo.

Seeing the following log messages from each container below:

```
awx_task:
2017-11-13 21:03:38,868 INFO spawned: 'channels-worker' with pid 6570
SystemCheckError: System check identified some issues:
ERRORS:
main.JobTemplate.project: (models.E006) The field 'project' clashes with the field 'project' from model 'main.unifiedjobtemplate'.
2017-11-13 21:03:39,057 INFO exited: awx-celeryd-beat (exit status 1; not expected)
2017-11-13 21:03:39,139 INFO spawned: 'awx-celeryd-beat' with pid 6573
2017-11-13 21:03:39,140 INFO exited: callback-receiver (exit status 1; not expected)
2017-11-13 21:03:40,147 INFO success: channels-worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-11-13 21:03:40,148 INFO spawned: 'callback-receiver' with pid 6590
2017-11-13 21:03:40,149 INFO success: awx-celeryd-beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-11-13 21:03:41,149 INFO success: callback-receiver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Unknown command: 'celery'
Type 'awx-manage help' for usage.
2017-11-13 21:03:41,833 INFO exited: celery (exit status 1; not expected)
2017-11-13 21:03:42,837 INFO spawned: 'celery' with pid 6605
```

```
awx_web:
2017-11-13 21:08:02,030 INFO exited: daphne (exit status 1; not expected)
2017-11-13 21:08:03,034 INFO spawned: 'daphne' with pid 2931
2017-11-13 21:08:04,041 INFO success: daphne entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/daphne", line 11, in <module>
    sys.exit(CommandLineInterface.entrypoint())
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/daphne/cli.py", line 144, in entrypoint
    cls().run(sys.argv[1:])
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/daphne/cli.py", line 174, in run
    channel_layer = importlib.import_module(module_path)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/awx/asgi.py", line 37, in <module>
    channel_layer = get_channel_layer()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/channels/asgi.py", line 118, in get_channel_layer
    return channel_layers[alias].channel_layer
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/channels/asgi.py", line 70, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/channels/asgi.py", line 33, in make_backend
    return self._make_backend(name, config)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/channels/asgi.py", line 53, in _make_backend
    "Cannot import BACKEND %r specified for %s" % (self.configs[name]['BACKEND'], name)
channels.asgi.InvalidChannelLayerError: Cannot import BACKEND 'asgi_amqp.AMQPChannelLayer' specified for default

postgres:
ERROR:  relation "conf_setting" does not exist at character 158
STATEMENT:  SELECT "conf_setting"."id", "conf_setting"."created", "conf_setting"."modified", "conf_setting"."key", "conf_setting"."value", "conf_setting"."user_id" FROM "conf_setting" WHERE ("conf_setting"."user_id" IS NULL AND "conf_setting"."key" IN ('SOCIAL_AUTH_GOOGLE_OAUTH2_ORGANIZATION_MAP', 'LICENSE', 'SOCIAL_AUTH_GITHUB_TEAM_MAP', 'SOCIAL_AUTH_GITHUB_ORG_NAME', 'AWX_PROOT_SHOW_PATHS', 'LOG_AGGREGATOR_LOGGERS', 'SOCIAL_AUTH_SAML_ORGANIZATION_MAP', 'LOG_AGGREGATOR_PROTOCOL', 'ORG_ADMINS_CAN_SEE_ALL_USERS', 'AUTH_BASIC_ENABLED', 'SOCIAL_AUTH_GITHUB_TEAM_ORGANIZATION_MAP', 'TOWER_URL_BASE', 'SOCIAL_AUTH_SAML_SP_ENTITY_ID', 'SOCIAL_AUTH_AZUREAD_OAUTH2_ORGANIZATION_MAP', 'SOCIAL_AUTH_ORGANIZATION_MAP', 'EVENT_STDOUT_MAX_BYTES_DISPLAY', 'ACTIVITY_STREAM_ENABLED_FOR_INVENTORY_SYNC', 'SOCIAL_AUTH_SAML_SP_PUBLIC_CERT', 'SOCIAL_AUTH_SAML_ENABLED_IDPS', 'SOCIAL_AUTH_GITHUB_ORG_SECRET', 'AWX_ISOLATED_CONNECTION_TIMEOUT', 'LOG_AGGREGATOR_HOST', 'TACACSPLUS_HOST', 'RADIUS_PORT', 'SOCIAL_AUTH_SAML_SP_PRIVATE_KEY', 'AWX_ISOLATED_KEY_GENERATION', 'TACACSPLUS_SESSION_TIMEOUT', 'AUTH_TOKEN_EXPIRATION', 'AWX_ISOLATED_PRIVATE_KEY', 'SOCIAL_AUTH_TEAM_MAP', 'SOCIAL_AUTH_GITHUB_SECRET', 'LOG_AGGREGATOR_INDIVIDUAL_FACTS', 'SOCIAL_AUTH_GOOGLE_OAUTH2_TEAM_MAP', 'SOCIAL_AUTH_SAML_SUPPORT_CONTACT', 'AUTH_LDAP_GROUP_TYPE', 'SOCIAL_AUTH_GITHUB_TEAM_KEY', 'SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET', 'SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS', 'SOCIAL_AUTH_SAML_ORG_INFO', 'REMOTE_HOST_HEADERS', 'LOG_AGGREGATOR_PORT', 'LOG_AGGREGATOR_TCP_TIMEOUT', 'TACACSPLUS_PORT', 'SOCIAL_AUTH_GOOGLE_OAUTH2_KEY', 'PROXY_IP_WHITELIST', 'AUTH_LDAP_BIND_DN', 'SOCIAL_AUTH_GITHUB_TEAM_ID', 'LOG_AGGREGATOR_LEVEL', 'PENDO_TRACKING_STATE', 'DEFAULT_PROJECT_UPDATE_TIMEOUT', 'AUTH_LDAP_USER_FLAGS_BY_GROUP', 'SOCIAL_AUTH_USER_FIELDS', 'SOCIAL_AUTH_GITHUB_ORGANIZATION_MAP', 'TACACSPLUS_SECRET', 'SOCIAL_AUTH_GITHUB_ORG_TEAM_MAP', 'LOG_AGGREGATOR_ENABLED', 'TACACSPLUS_AUTH_PROTOCOL', 'SOCIAL_AUTH_SAML_TECHNICAL_CONTACT', 'AUTH_LDAP_GROUP_SEARCH', 'AWX_ISOLATED_PUBLIC_KEY', 'LOG_AGGREGATOR_TOWER_UUID', 'AWX_ISOLATED_CHECK_INTERVAL', 'SOCIAL_AUTH_SAML_TEAM_MAP', 'AUTH_LDAP_USER_DN_TEMPLATE', 'AUTH_LDAP_ORGANIZATION_MAP', 'AUTH_TOKEN_PER_USER', 'CUSTOM_LOGIN_INFO', 'AWX_PROOT_BASE_PATH', 'TOWER_ADMIN_ALERTS', 'LOG_AGGREGATOR_PASSWORD', 'SOCIAL_AUTH_GITHUB_TEAM_SECRET', 'STDOUT_MAX_BYTES_DISPLAY', 'AUTH_LDAP_CONNECTION_OPTIONS', 'AUTH_LDAP_TEAM_MAP', 'LOG_AGGREGATOR_VERIFY_CERT', 'SCHEDULE_MAX_JOBS', 'AUTH_LDAP_BIND_PASSWORD', 'AUTH_LDAP_USER_ATTR_MAP', 'CUSTOM_LOGO', 'SOCIAL_AUTH_AZUREAD_OAUTH2_TEAM_MAP', 'LOG_AGGREGATOR_USERNAME', 'AUTH_LDAP_DENY_GROUP', 'SOCIAL_AUTH_GITHUB_KEY', 'SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS', 'SOCIAL_AUTH_GITHUB_ORG_ORGANIZATION_MAP', 'AUTH_LDAP_REQUIRE_GROUP', 'AWX_ISOLATED_LAUNCH_TIMEOUT', 'DEFAULT_JOB_TIMEOUT', 'AD_HOC_COMMANDS', 'AUTH_LDAP_USER_SEARCH', 'RADIUS_SECRET', 'RADIUS_SERVER', 'AUTH_LDAP_SERVER_URI', 'SOCIAL_AUTH_AZUREAD_OAUTH2_KEY', 'AWX_PROOT_HIDE_PATHS', 'SOCIAL_AUTH_GITHUB_ORG_KEY', 'ACTIVITY_STREAM_ENABLED', 'AWX_ANSIBLE_CALLBACK_PLUGINS', 'SOCIAL_AUTH_GITHUB_TEAM_TEAM_MAP', 'ANSIBLE_FACT_CACHE_TIMEOUT', 'DEFAULT_INVENTORY_UPDATE_TIMEOUT', 'AUTH_LDAP_START_TLS', 'SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET', 'LOG_AGGREGATOR_TYPE')) ORDER BY "conf_setting"."id" ASC
```

##### ENVIRONMENT
* AWX version: latest, just clone down from repo
* AWX install method: docker on linux
* Ansible version:  2.4.2
* Operating System: REHL7
* Web Browser: Chrome

##### STEPS TO REPRODUCE
Just do install from install playbook. Happens on a fresh install.

**Comment by bunicb** [comment]
I had the same issue today, using Ansible version 2.4.0 and CentOS 7.4.

**Comment by matburt** [comment]
We're in the process of merging some feature branches so there's going to be some churn on our development branch.  If you need to deploy awx in the meantime you can select version 1.0.1.167

**Comment by bunicb** [comment]
I tried installing using the zip of 1.0.1 from releases, as well as checking out the 1.0.1 tag. Got the same errors when installing.

**Comment by JurgenVM** [comment]
I can confirm changing the following line in the inventory works.

dockerhub_version=1.0.1.167

**Comment by MrMEEE** [comment]
I still have this issue on my RPM builds... have tried both build 323 and 314.. Can anyone explain what the problem was???

**Comment by AndreasDickow** [comment]
getting the same issue in django

**Comment by behconsci** [comment]
any updates?

**Comment by mirakl577** [comment]
just curious, have someone completed setup on devel branch. i've got the same errors in container logs
