### ISSUE TITLE
in ansible tower ,File Exists Error on Jobs

### ISSUE THREAD

**Issue by nonomato** [ansible/awx#6339]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
File Exists Error on  Jobs

##### ENVIRONMENT
* Ansible Tower version: 3.2.7
* Ansible version:  2.6.4
* Operating System: CentOS Linux release 7.5.1804
* Web Browser: chrome

##### EXPECTED RESULTS

Task run successfully

##### ACTUAL RESULTS

Bug appears randomly

In Ansible Tower Web UI:
Identity added: /tmp/awx_56471__MqKDI/credential_6 (/tmp/awx_56471__MqKDI/credential_6)
ERROR! Unexpected Exception, this is probably a bug: [Errno 17] File exists
to see the full traceback, use -vvv

In Ansible Log File:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/lib/python2.7/site-packages/awx/main/tasks.py", line 477, in _wrapped
  File "/lib/python2.7/site-packages/awx/main/tasks.py", line 952, in run
Exception: job 56471 (failed) encountered an error (rc=250), please see task stdout for details.

**Comment by ryanpetrello** [comment]
@nonomato 

This bug tracker is for reporting issues in the open source AWX project, not Red Hat Ansible Tower.  If you need help troubleshooting Ansible Tower, please reach out to Red Hat support.
