### ISSUE TITLE
project update error: invalid syntax (uuid.py, line 138)

### ISSUE THREAD

**Issue by gstorme** [ansible/awx#6372]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Upgraded from 7.0.0 to 9.3.0.
Running a project update fails with this error:

> Identity added: /tmp/awx_4397_ylni359w/artifacts/4397/ssh_key_data (/tmp/awx_4397_ylni359w/artifacts/4397/ssh_key_data)
ERROR! Unexpected Exception, this is probably a bug: invalid syntax (uuid.py, line 138)
the full traceback was:
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 92, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/lib/python3.6/site-packages/ansible/cli/__init__.py", line 22, in <module>
    from ansible.inventory.manager import InventoryManager
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 34, in <module>
    from ansible.inventory.data import InventoryData
  File "/usr/lib/python3.6/site-packages/ansible/inventory/data.py", line 26, in <module>
    from ansible.inventory.group import Group
  File "/usr/lib/python3.6/site-packages/ansible/inventory/group.py", line 27, in <module>
    from ansible.utils.vars import combine_vars
  File "/usr/lib/python3.6/site-packages/ansible/utils/vars.py", line 24, in <module>
    import uuid
  File "/var/lib/awx/venv/ansible/lib/python3.6/site-packages/uuid.py", line 138
    if not 0 <= time_low < 1<<32L:
                                ^
SyntaxError: invalid syntax

Problem occurs on 9.2.0 and 9.3.0, not on 7.0.0.

##### ENVIRONMENT
* AWX version: 9.3.0
* AWX install method: docker on linux
* Ansible version:  2.9.5
* Operating System: Debian 9.12

##### STEPS TO REPRODUCE

Create a project with scm type git, run project update.

##### EXPECTED RESULTS

Project update runs fine, just as on version 7.0.0.

##### ACTUAL RESULTS

See error in summary above.

##### ADDITIONAL INFORMATION

GET /api/v2/project_updates/4397/
```
HTTP 200 OK
Allow: GET, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
X-API-Node: awx
X-API-Time: 0.032s

{
    "id": 4397,
    "type": "project_update",
    "url": "/api/v2/project_updates/4397/",
    "related": {
        "credential": "/api/v2/credentials/3/",
        "unified_job_template": "/api/v2/projects/33/",
        "stdout": "/api/v2/project_updates/4397/stdout/",
        "project": "/api/v2/projects/33/",
        "cancel": "/api/v2/project_updates/4397/cancel/",
        "scm_inventory_updates": "/api/v2/project_updates/4397/scm_inventory_updates/",
        "notifications": "/api/v2/project_updates/4397/notifications/",
        "events": "/api/v2/project_updates/4397/events/"
    },
    "summary_fields": {
        "project": {
            "id": 33,
            "name": "playbooks-windows",
            "description": "",
            "status": "failed",
            "scm_type": "git"
        },
        "credential": {
            "id": 3,
            "name": "Gitlab",
            "description": "",
            "kind": "scm",
            "cloud": false,
            "kubernetes": false,
            "credential_type_id": 2
        },
        "unified_job_template": {
            "id": 33,
            "name": "playbooks-windows",
            "description": "",
            "unified_job_type": "project_update"
        },
        "instance_group": {
            "id": 1,
            "name": "tower",
            "is_containerized": false
        },
        "user_capabilities": {
            "delete": true,
            "start": true
        }
    },
    "created": "2020-03-21T19:31:22.651898Z",
    "modified": "2020-03-21T19:31:24.325720Z",
    "name": "playbooks-windows",
    "description": "",
    "local_path": "_33__playbooks_windows",
    "scm_type": "git",
    "scm_url": "git@git.xxx.net:awx/playbooks-windows.git",
    "scm_branch": "develop",
    "scm_refspec": "",
    "scm_clean": false,
    "scm_delete_on_update": false,
    "credential": 3,
    "timeout": 0,
    "scm_revision": "",
    "unified_job_template": 33,
    "launch_type": "dependency",
    "status": "failed",
    "failed": true,
    "started": "2020-03-21T19:31:24.392872Z",
    "finished": "2020-03-21T19:31:25.857507Z",
    "canceled_on": null,
    "elapsed": 1.465,
    "job_args": "[\"ssh-agent\", \"sh\", \"-c\", \"ssh-add /tmp/awx_4397_ylni359w/artifacts/4397/ssh_key_data && rm -f /tmp/awx_4397_ylni359w/artifacts/4397/ssh_key_data && ansible-playbook -t update_git -i /tmp/awx_4397_ylni359w/inventory/hosts -e @/tmp/awx_4397_ylni359w/env/extravars project_update.yml\"]",
    "job_cwd": "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/playbooks",
    "job_env": {
        "LC_ALL": "en_US.UTF-8",
        "LANG": "en_US.UTF-8",
        "HOSTNAME": "awx",
        "PWD": "/home/awx",
        "HOME": "/home/awx",
        "SHLVL": "2",
        "LANGUAGE": "en_US.UTF-8",
        "PATH": "/var/lib/awx/venv/ansible/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "_": "/usr/local/bin/supervisord",
        "SUPERVISOR_ENABLED": "1",
        "SUPERVISOR_SERVER_URL": "unix:///tmp/supervisor.sock",
        "SUPERVISOR_PROCESS_NAME": "dispatcher",
        "SUPERVISOR_GROUP_NAME": "tower-processes",
        "LC_CTYPE": "en_US.UTF-8",
        "DJANGO_SETTINGS_MODULE": "awx.settings.production",
        "DJANGO_LIVE_TEST_SERVER_ADDRESS": "localhost:9013-9199",
        "TZ": "UTC",
        "ANSIBLE_FACT_CACHE_TIMEOUT": "0",
        "ANSIBLE_FORCE_COLOR": "True",
        "ANSIBLE_HOST_KEY_CHECKING": "False",
        "ANSIBLE_INVENTORY_UNPARSED_FAILED": "True",
        "ANSIBLE_PARAMIKO_RECORD_HOST_KEYS": "False",
        "ANSIBLE_VENV_PATH": "/var/lib/awx/venv/ansible",
        "ANSIBLE_TIMEOUT": "120",
        "AWX_PRIVATE_DATA_DIR": "/tmp/awx_4397_ylni359w",
        "VIRTUAL_ENV": "/var/lib/awx/venv/ansible",
        "PYTHONPATH": "/var/lib/awx/venv/ansible/lib/python3.6/site-packages:",
        "ANSIBLE_RETRY_FILES_ENABLED": "False",
        "ANSIBLE_ASK_PASS": "False",
        "ANSIBLE_BECOME_ASK_PASS": "False",
        "DISPLAY": "",
        "TMP": "/tmp",
        "PROJECT_UPDATE_ID": "4397",
        "ANSIBLE_CALLBACK_PLUGINS": "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/plugins/callback",
        "ANSIBLE_GALAXY_SERVER_GALAXY_URL": "https://galaxy.ansible.com",
        "ANSIBLE_GALAXY_SERVER_LIST": "galaxy",
        "ANSIBLE_STDOUT_CALLBACK": "awx_display",
        "AWX_ISOLATED_DATA_DIR": "/tmp/awx_4397_ylni359w/artifacts/4397",
        "RUNNER_OMIT_EVENTS": "False",
        "RUNNER_ONLY_FAILED_EVENTS": "False"
    },
    "job_explanation": "",
    "execution_node": "awx",
    "result_traceback": "",
    "event_processing_finished": true,
    "project": 33,
    "job_type": "check",
    "job_tags": "update_git",
    "host_status_counts": {},
    "playbook_counts": {
        "play_count": 0,
        "task_count": 0
    }
}
```

**Comment by ryanpetrello** [comment]
@gstorme,

It looks like your ansible virtualenv has a package installed that doesn't work in python3, and is interfering with the built-in `uuid` library in modern Python versions (newer versions of AWX ship use python3 only, as python2 is now out of support).

https://pypi.org/project/uuid/#history

I'm not really certain what the point of this package is, or how it got installed on your system; it seems very old now (last release was 14 years ago).  I suspect it was some python2-era polyfill that's no longer necessary in modern Pythons?

```python
~ python3
>>> if not 0 <= 1 < 1<<32L: pass
  File "<stdin>", line 1
    if not 0 <= 1 < 1<<32L: pass
                         ^
SyntaxError: invalid syntax
```

```
~ python2
>>> if not 0 <= 1 < 1<<32L: pass
...
>>>
```

I'm not sure how it _got there_, but you might try doing something like:
```
~ /var/lib/awx/venv/ansible/bin/python3 -m pip uninstall uuid

**Comment by gstorme** [comment]
My bad, we install a custom pip package which has uuid as a dependency and also got installed.
Should have checked that, we'll fix our package/code to be compatible with python3.
Thanks
