### ISSUE TITLE
No instance groups after install

### ISSUE THREAD

**Issue by Bobbobboe** [ansible/awx#6376]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After installing AWX using docker-compose and the provided installer there is no instance group tower in the webinterface.

##### ENVIRONMENT
* AWX version: 9.3.0
* AWX install method: docker on linux
* Ansible version:  2.9.6
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Install AWX using installer
2. Login to Webinterface
3. Click Instance Groups

##### EXPECTED RESULTS

Instance group tower is present

##### ACTUAL RESULTS

No Instance Groups in the list

##### ADDITIONAL INFORMATION

Logs awx-task:
```
Default organization added.
Demo Credential, Inventory, and Job Template added.
(changed: True)
2020-03-23 11:02:05,885 DEBUG    awx.main.dispatch publish awx.main.tasks.apply_cluster_membership_policies(63ff1169-0704-41db-9e56-b1b49a1cca42, queue=awx_private_queue)

```

**Comment by Bobbobboe** [comment]
When I start a job it creates the tower Instance Group but without any Instances

**Comment by Bobbobboe** [comment]
After manually adding the AWX instance to the Instance Group and rebooting I get the following error:
```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/utils/functional.py", line 344, in retry_over_time
    return fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/connection.py", line 283, in connect
    return self.connection
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/connection.py", line 839, in connection
    self._connection = self._establish_connection()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/connection.py", line 794, in _establish_connection
    conn = self.transport.establish_connection()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/connection.py", line 311, in connect
    self.transport.connect()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/transport.py", line 77, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/transport.py", line 148, in _connect
    "failed to resolve broker hostname"))
OSError: failed to resolve broker hostname
```

**Comment by ryanpetrello** [comment]
> OSError: failed to resolve broker hostname

This sounds to me like your RabbitMQ node(s) is/are not up or are unreachable.

This issue tracker is for tracking feature enhancements and bugs to AWX itself.  If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by Bobbobboe** [comment]
I thought it was a RabbitMQ problem but when I asked on IRC they told me RabbitMQ was no longer a dependency. So just to confirm RabbitMQ is still needed?

**Comment by ryanpetrello** [comment]
Hey @Bobbobboe,

We are in fact removing RabbitMQ in the next major version of AWX (which is not _yet_ released, but likely will be in the coming week or so).

These issues you're encountering troubleshooting RabbitMQ are a good example of why we intend to move away from it :)

More details at: https://github.com/ansible/awx/issues/5443
