### ISSUE TITLE
Websocket can't connect after upgrading to 9.3

### ISSUE THREAD

**Issue by JGRFenix** [ansible/awx#6392]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Recently we ecountered an issue where the logs for the container awx_web was reporting a permission denied when ever we submitted an API request. I fixed this by upgrading to the latest version of AWX (https://github.com/ansible/awx/blob/devel/INSTALL.md#upgrading-from-previous-versions) since doing this upgrade we get this error in both Firefox and Chrome 
```The connection to wss://<domain>/websocket/ was interrupted while the page was loading.```

and from awx_web logs container:  
```
2020/03/24 12:03:39 [error] 133#0: *48 upstream timed out (110: Connection timed out) while reading response header from upstream, client: <IP>, server: _, request: "GET /websocket/ HTTP/1.0", upstream: "http://127.0.0.1:8051/websocket/", host: "<domain>"
<Proxy IP> - - [24/Mar/2020:12:03:55 +0000] "GET /websocket/ HTTP/1.0" 504 176 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0" "<Actual IP>"
```

And we can't schedule any jobs

```
Tue Mar 24 12:05:07 2020 - *** HARAKIRI ON WORKER 4 (pid: 137, try: 1) ***
Tue Mar 24 12:05:07 2020 - HARAKIRI !!! worker 4 status !!!
Tue Mar 24 12:05:07 2020 - HARAKIRI [core 0] 172.23.170.15 - POST /api/v2/jobs/1923/relaunch/ since 1585051386
Tue Mar 24 12:05:07 2020 - HARAKIRI !!! end of worker 4 status !!!
DAMN ! worker 4 (pid: 137) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 4 (new pid: 172)
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0xdaf4e0 pid: 172 (default app)
```
and from the awx_task container logs:
```
2020-03-24 12:06:42,878 WARNING  kombu.mixins Broker connection error, trying again in 32.0 seconds: OSError('failed to resolve broker hostname',).
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/transport.py", line 137, in _connect
    host, port, family, socket.SOCK_STREAM, SOL_TCP)
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```
##### ENVIRONMENT
* AWX version: 9.3
* AWX install method: docker on linux
* Ansible version:  2.8.5
* Operating System: Centos 7
* Web Browser: Firefox

##### STEPS TO REPRODUCE
stop and delete containers:
```ansible-playbook -i inventory install.yml -e @vars.yml```
check for error and its there

##### EXPECTED RESULTS

awx_task to not show that error as we haven't seen it before
websocket to connect fine

##### ACTUAL RESULTS

awx_tasks shows the above error
websocket refuses to connect

**Comment by thibveni** [comment]
i have the same issue, on the same environment

here is the error on the container

```
2020-03-25 09:02:11,930 WARNING  kombu.mixins Broker connection error, trying again in 28.0 seconds: OSError('failed to resolve broker hostname',).
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/transport.py", line 137, in _connect
    host, port, family, socket.SOCK_STREAM, SOL_TCP)
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/utils/functional.py", line 344, in retry_over_time
    return fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/connection.py", line 283, in connect
    return self.connection
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/connection.py", line 839, in connection
    self._connection = self._establish_connection()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/connection.py", line 794, in _establish_connection
    conn = self.transport.establish_connection()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/connection.py", line 311, in connect
    self.transport.connect()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/transport.py", line 77, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/amqp/transport.py", line 148, in _connect
    "failed to resolve broker hostname"))
OSError: failed to resolve broker hostname
```

**Comment by JGRFenix** [comment]
Hi,

I've managed to fix this issue on my enviroment I miss read the upgrade guide and was pulling from git rather than https://github.com/ansible/awx/releases

using the latest release works fine now, 

Thanks,

JR
