### ISSUE TITLE
Some ui_next test making network calls

### ISSUE THREAD

**Issue by keithjgrant** [ansible/awx#6507]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Some tests are making network calls. These should be stubbed out to increase test speed and reliability.

##### STEPS TO REPRODUCE

Stop all development servers and run ui_next test suite. ECONNREFUSED errors will appear for failed network requests.

![Screen Shot 2020-03-31 at 10 33 58 AM](https://user-images.githubusercontent.com/410794/78057389-803d7f00-733b-11ea-828c-a4cdf7190d96.png)

**Comment by jakemcdermott** [comment]
![wtf](https://user-images.githubusercontent.com/9753817/78064651-12f01500-7360-11ea-9cf4-8415444c8442.gif)

**Comment by jlmitch5** [comment]
I've been noticing random failures when I run all the tests as `npm run test-watch`.  These clear up when I subsequently run in "failed-only" mode.  They sometimes have different error notes, but a lot of times I see this (on different tests):

```
 FAIL  src/screens/Inventory/InventoryGroup/InventoryGroup.test.jsx
  ● <InventoryGroup /> › renders successfully
    The `document` global was defined when React was initialized, but is not defined anymore. This can happen in a test environment if a component schedules an update from an asynchronous callback, but the test has already finished running. To solve this, you can either unmount the component at the end of your test (and ensure that any asynchronous operations get canceled in `componentWillUnmount`), or you can change the test itself to be asynchronous.
      170 |                 },
      171 |               ]}
    > 172 |               toolbarSortColumns={[
          |            ^
      173 |                 {
      174 |                   name: i18n._(t`Username`),
      175 |                   key: 'username',
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:150:17)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:292:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:22510:9)
      at unstable_runWithPriority (node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11061:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22412:3)
      at finishSyncRender (node_modules/react-dom/cjs/react-dom.development.js:21838:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21824:7)
      at node_modules/react-dom/cjs/react-dom.development.js:11111:24
      at unstable_runWithPriority (node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11061:10)
      at flushSyncCallbackQueueImpl (node_modules/react-dom/cjs/react-dom.development.js:11106:7)
      at flushSyncCallbackQueue (node_modules/react-dom/cjs/react-dom.development.js:11094:3)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21230:9)
      at Object.enqueueSetState (node_modules/react-dom/cjs/react-dom.development.js:12661:5)
      at UsersList.Object.<anonymous>.Component.setState (node_modules/react/cjs/react.development.js:471:16)
      at UsersList.loadUsers (src/screens/User/UserList/UserList.jsx:172:12)
```

a different run

```
 FAIL  src/screens/Host/HostGroups/HostGroupsList.test.jsx (10.241s)
  ● <HostGroupsList /> › should fetch groups from api and render them in the list
    The `document` global was defined when React was initialized, but is not defined anymore. This can happen in a test environment if a component schedules an update from an asynchronous callback, but the test has already finished running. To solve this, you can either unmount the component at the end of your test (and ensure that any asynchronous operations get canceled in `componentWillUnmount`), or you can change the test itself to be asynchronous.
      74 |       if (err && err.response && err.response.status === 401) {
      75 |         this.setState({ hasValidationError: true });
    > 76 |       } else {
         |            ^
      77 |         this.setState({ hasAuthError: true });
      78 |       }
      79 |     } finally {
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:150:17)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:292:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:22510:9)
      at unstable_runWithPriority (node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11061:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22412:3)
      at finishSyncRender (node_modules/react-dom/cjs/react-dom.development.js:21838:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21824:7)
      at node_modules/react-dom/cjs/react-dom.development.js:11111:24
      at unstable_runWithPriority (node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11061:10)
      at flushSyncCallbackQueueImpl (node_modules/react-dom/cjs/react-dom.development.js:11106:7)
      at flushSyncCallbackQueue (node_modules/react-dom/cjs/react-dom.development.js:11094:3)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21230:9)
      at Object.enqueueSetState (node_modules/react-dom/cjs/react-dom.development.js:12661:5)
      at AWXLogin.Object.<anonymous>.Component.setState (node_modules/react/cjs/react.development.js:471:16)
      at AWXLogin.loadCustomLoginInfo (src/screens/Login/Login.jsx:76:12)
  ● <HostGroupsList /> › should fetch groups from api and render them in the list
    expect(received).toBe(expected) // Object.is equality
    Expected: 3
    Received: 0
      115 |   test('should fetch groups from api and render them in the list', async () => {
      116 |     expect(HostsAPI.readAllGroups).toHaveBeenCalled();
    > 117 |     expect(wrapper.find('HostGroupItem').length).toBe(3);
          |                                                  ^
      118 |   });
      119 |
      120 |   test('should check and uncheck the row item', async () => {
      at Object.test (src/screens/Host/HostGroups/HostGroupsList.test.jsx:117:50)
 FAIL  src/screens/Organization/OrganizationAdd/OrganizationAdd.test.jsx
  ● <OrganizationAdd /> › onSubmit should post to api
    The `document` global was defined when React was initialized, but is not defined anymore. This can happen in a test environment if a component schedules an update from an asynchronous callback, but the test has already finished running. To solve this, you can either unmount the component at the end of your test (and ensure that any asynchronous operations get canceled in `componentWillUnmount`), or you can change the test itself to be asynchronous.
      170 |                 },
      171 |               ]}
    > 172 |               toolbarSortColumns={[
          |            ^
      173 |                 {
      174 |                   name: i18n._(t`Username`),
      175 |                   key: 'username',
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:150:17)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:292:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:22510:9)
      at unstable_runWithPriority (node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11061:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22412:3)
      at finishSyncRender (node_modules/react-dom/cjs/react-dom.development.js:21838:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21824:7)
      at node_modules/react-dom/cjs/react-dom.development.js:11111:24
      at unstable_runWithPriority (node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11061:10)
      at flushSyncCallbackQueueImpl (node_modules/react-dom/cjs/react-dom.development.js:11106:7)
      at flushSyncCallbackQueue (node_modules/react-dom/cjs/react-dom.development.js:11094:3)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21230:9)
      at Object.enqueueSetState (node_modules/react-dom/cjs/react-dom.development.js:12661:5)
      at UsersList.Object.<anonymous>.Component.setState (node_modules/react/cjs/react.development.js:471:16)
      at UsersList.loadUsers (src/screens/User/UserList/UserList.jsx:172:12)
```

**Comment by unlikelyzero** [comment]
@keithjgrant is this still happening?

**Comment by mabashian** [comment]
We can close this
