### ISSUE TITLE
AWX is Upgrading..... Issue

### ISSUE THREAD

**Issue by codesupremo** [ansible/awx#6539]
##### ISSUE TYPE
 - AWX is Upgrading... (from Browser)

##### SUMMARY

AWX is Upgrading... and it is taking a very long time, for more than a day now and still not finished.

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: docker
* Ansible version:  2.9.3
* Operating System: CentOS7
* Web Browser: Firefox in Ubuntu 18.4

##### STEPS TO REPRODUCE

When Accessing the AWX GUI — It’s stuck in AWX is Upgrading state. I’m not sure when it will be completely upgraded, It’s been a day now.

##### EXPECTED RESULTS

AWX GUI Login Prompt

##### ACTUAL RESULTS

Stuck in “AWX is Upgrading”

Unable to Login to AWX GUI because it is stuck in AWX is Upgrading state

**Comment by chrismeyersfsu** [comment]
@codesupremo can you supply the docker logs i.e. `docker logs -f awx_task` `docker logs -f awx_web`

**Comment by ghost** [comment]
I can confirm that error as well in a docker-compose setup and external postgresql instance.
In my case, it seems like the database was not migrated, as AWX was complaining in the logs about some tables missing.

I solved by manually perform the migration with:
```bash
$ awx-manage migrate --noinput
```

from the awx-web container.

**Comment by way31415926** [comment]
@ldepandis @chrismeyersfsu 
I encountered the same problem, and execute the command 'awx-manage migrate --noinput'.
Then,I could not login in the system.And there is no data in the database.
![image](https://user-images.githubusercontent.com/31196437/79563602-ad31b600-80df-11ea-8563-2b2a2fc195a9.png)
![image](https://user-images.githubusercontent.com/31196437/79563632-bc186880-80df-11ea-908e-a7ec6bb8c4f6.png)

**Comment by ghost** [comment]
@way31415926 yes, that's right, because this is not a part of the database migration process.

In the awx-web container run
```awx-manage createsuperuser --username admin```

Insert the email and password and you're good to go.

Also, if you want the Demo Inventory or the other demo resources, just run
```awx-manage create_preload_data```

**Comment by way31415926** [comment]
@ldepandis You are right , thanks a lot.

**Comment by jibbajabber** [comment]
I can reliable reproduce this symptom for docker compose install method for all releases I've tried (`11.0.0`, `12.0.0`, `13.0.0` and `14.0.0`)
What is odd, is that I was happy deploying `11.0.0` for the past week without issues, however now despite restoring my environment to a clean fresh CentOS 7 install with a snapshot, the installer hangs waiting for migrations that never happen.

This is resolved for me by running the migrations manually inside `awx_web` container as mentioned but I don't know why this is now broken (for me) for so many releases.

My environment:
* `ansible 2.9.0`
* `python 3.6.5`

My pyenv python packages:
```
ansible==2.9.0
ansible-tower-cli==3.3.9
certifi==2020.6.20
cffi==1.14.1
chardet==3.0.4
click==6.7
colorama==0.4.3
cryptography==3.0
idna==2.10
Jinja2==2.11.2
MarkupSafe==1.1.1
pycparser==2.20
PyYAML==5.3.1
requests==2.24.0
six==1.15.0
urllib3==1.25.10
```

`awx_web` container `13.0.0` output:
```
020-08-13 10:59:37,099 ERROR    awx.main.wsbroadcast AWX is currently installing/upgrading.  Trying again in 5s...
2020-08-13 10:59:43,566 INFO exited: wsbroadcast (exit status 0; expected)
2020-08-13 10:59:43,566 INFO exited: wsbroadcast (exit status 0; expected)
2020-08-13 10:59:44,573 INFO spawned: 'wsbroadcast' with pid 507
2020-08-13 10:59:44,573 INFO spawned: 'wsbroadcast' with pid 507
2020-08-13 10:59:45,584 INFO success: wsbroadcast entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-13 10:59:45,584 INFO success: wsbroadcast entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[pid: 78|app: 0|req: 12/189] x.x.x.x () {54 vars in 2608 bytes} [Thu Aug 13 10:59:45 2020] GET / => generated 0 bytes in 27 msecs (HTTP/1.1 302) 3 headers in 119 bytes (1 switches on core 0)
x.x.x.x - - [13/Aug/2020:10:59:46 +0000] "GET / HTTP/1.1" 302 5 "https://dv-awx001.oursite.com/migrations_notran/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" "-"
[pid: 78|app: 0|req: 13/190] x.x.x.x () {54 vars in 2707 bytes} [Thu Aug 13 10:59:46 2020] GET /migrations_notran/ => generated 1589 bytes in 29 msecs (HTTP/1.1 200) 5 headers in 171 bytes (1 switches on core 0)
x.x.x.x - - [13/Aug/2020:10:59:46 +0000] "GET /migrations_notran/ HTTP/1.1" 200 1589 "https://dv-awx001.oursite.com/migrations_notran/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" "-"
x.x.x.x - - [13/Aug/2020:10:59:46 +0000] "POST /csp-violation/ HTTP/1.1" 302 5 "https://dv-awx001.oursite.com/migrations_notran/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" "-"
[pid: 79|app: 0|req: 100/191] x.x.x.x () {58 vars in 2622 bytes} [Thu Aug 13 10:59:46 2020] POST /csp-violation/ => generated 0 bytes in 31 msecs (HTTP/1.1 302) 3 headers in 119 bytes (1 switches on core 0)
[pid: 81|app: 0|req: 52/192] x.x.x.x () {54 vars in 2492 bytes} [Thu Aug 13 10:59:46 2020] GET /api/ => generated 0 bytes in 28 msecs (HTTP/1.1 302) 3 headers in 119 bytes (1 switches on core 0)
x.x.x.x - - [13/Aug/2020:10:59:46 +0000] "GET /api/ HTTP/1.1" 302 5 "https://dv-awx001.oursite.com/migrations_notran/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" "-"
[pid: 79|app: 0|req: 101/193] x.x.x.x () {54 vars in 2583 bytes} [Thu Aug 13 10:59:46 2020] GET /migrations_notran/ => generated 1589 bytes in 32 msecs (HTTP/1.1 200) 5 headers in 171 bytes (1 switches on core 0)
x.x.x.x - - [13/Aug/2020:10:59:46 +0000] "GET /migrations_notran/ HTTP/1.1" 200 1589 "https://dv-awx001.oursite.com/migrations_notran/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" "-"
x.x.x.x - - [13/Aug/2020:10:59:46 +0000] "GET /api/ HTTP/1.1" 302 5 "https://dv-awx001.oursite.com/migrations_notran/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" "-"
[pid: 81|app: 0|req: 53/194] x.x.x.x () {56 vars in 2544 bytes} [Thu Aug 13 10:59:46 2020] GET /api/ => generated 0 bytes in 32 msecs (HTTP/1.1 302) 3 headers in 119 bytes (1 switches on core 0)
[pid: 79|app: 0|req: 102/195] x.x.x.x () {56 vars in 2635 bytes} [Thu Aug 13 10:59:46 2020] GET /migrations_notran/ => generated 1589 bytes in 32 msecs (HTTP/1.1 200) 5 headers in 171 bytes (1 switches on core 0)
x.x.x.x - - [13/Aug/2020:10:59:46 +0000] "GET /migrations_notran/ HTTP/1.1" 200 1589 "https://dv-awx001.oursite.com/migrations_notran/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" "-"
2020-08-13 10:59:47,141 ERROR    awx.main.wsbroadcast AWX is currently installing/upgrading.  Trying again in 5s...
```

I forget which release but I've also seen this `awx_web` output (where `main_instance` doesn't appear to be created):
```
2020-08-05 10:16:25,097 INFO exited: dispatcher (exit status 1; not expected)
2020-08-05 10:16:25,097 INFO exited: dispatcher (exit status 1; not expected)
2020-08-05 10:16:26,103 INFO spawned: 'dispatcher' with pid 2484
2020-08-05 10:16:26,103 INFO spawned: 'dispatcher' with pid 2484
2020-08-05 10:16:27,106 INFO success: dispatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-05 10:16:27,106 INFO success: dispatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-05 10:16:30,257 WARNING  awx.main.dispatch.periodic periodic beat started
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "main_instance" does not exist
LINE 1: SELECT (1) AS "a" FROM "main_instance" WHERE "main_instance"...

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 154, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/run_dispatcher.py", line 55, in handle
    reaper.reap()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/dispatch/reaper.py", line 38, in reap
    (changed, me) = Instance.objects.get_or_register()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/managers.py", line 144, in get_or_register
    return (False, self.me())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/managers.py", line 100, in me
    if node.exists():
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 766, in exists
    return self.query.has_results(using=self.db)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/sql/query.py", line 522, in has_results
    return compiler.has_results()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1110, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "main_instance" does not exist
LINE 1: SELECT (1) AS "a" FROM "main_instance" WHERE "main_instance"...
```

Since I'm close to completion for an ansible role for creating our entire AWX instance (credentials, projects, inventories, job templates, users etc etc), I will add this workaround when waiting for the installer to complete, if relevant search terms found within the `awx_web` container log, or within a reasonable time reached for the REST API to be available. 
I need our deployment to be completely automated, so a workaround is mandatory for us (I'd rather not _have_ to do this though 😃 if we could get this addressed)

Happy to share more info, capture more logs etc if it helps 👍 

## My ansible for this workaround (two role task files):
`wait_for_install_to_complete.yml` (runs after installer finishes and waits for REST to be ready):
```
---
- name: Wait for AWX to be ready to work
  uri:
    url: "{{ item.url }}"
    user: "{{ item.user | default(omit) }}"
    password: "{{ item.pass | default(omit) }}"
    return_content: yes
    validate_certs: no
    force_basic_auth: "{{ item.basic_auth | default(omit) }}"
  until: awx_ready.status == 200
  retries: 10
  delay: 30
  register: awx_ready
  changed_when: false
  with_items: "{{ awx_ready_urls }}"
  ignore_errors: yes
...
```

`awx_ready_urls` used:
```
awx_ready_urls:
  - { url: "https://{{ inventory_hostname }}/api/v2" }
```

`rescue.yml` (tries the migration workaround, waits for all migrations to be applied then tries one more time to wait for REST):
```
---
- name: Attempt rescue of bad install
  block:
    - name: Kick migration in case of failure
      command: docker exec -it awx_web bash -c "awx-manage migrate"
      register: migration_status
      retries: 3
      delay: 5
      until: "'No migrations to apply' in migration_status.stdout"
      changed_when: no

    - name: Restart all containers
      docker_compose:
        project_src: "{{ awx_docker_compose_dir }}"
        restarted: yes

    - name: Wait for AWX to be ready
      include: wait_for_install_to_complete.yml
  when: install_status !=200
...
```

**Comment by juanjo-vlc** [comment]
I had the same issue installing 17.1.0 and solved it using awx-manage commands suggested by a ghost.
I got a failure on the playbook task "Run migrations in task container", and the log showed a lot of django related traces.
Maybe the postgres container was not ready when the migration tasks were triggered.

**Comment by sfhl** [comment]
Hi there,
i have got a similar issue running awx 17.0.1 on kubernetes with external psql database.
AWX is running fine, tasks are executed, the web ui is accessible, but the log permanently says:
```
2021-04-26 09:44:07,594 INFO exited: wsbroadcast (exit status 0; expected)
2021-04-26 09:44:07,594 INFO exited: wsbroadcast (exit status 0; expected)
2021-04-26 09:44:08,597 INFO spawned: 'wsbroadcast' with pid 234
2021-04-26 09:44:08,597 INFO spawned: 'wsbroadcast' with pid 234
2021-04-26 09:44:09,598 INFO success: wsbroadcast entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-26 09:44:09,598 INFO success: wsbroadcast entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-26 09:44:11,094 ERROR    awx.main.wsbroadcast AWX is currently installing/upgrading.  Trying again in 5s...
2021-04-26 09:44:16,529 INFO exited: wsbroadcast (exit status 0; expected)
2021-04-26 09:44:16,529 INFO exited: wsbroadcast (exit status 0; expected)
2021-04-26 09:44:17,532 INFO spawned: 'wsbroadcast' with pid 240
2021-04-26 09:44:17,532 INFO spawned: 'wsbroadcast' with pid 240
2021-04-26 09:44:18,534 INFO success: wsbroadcast entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-26 09:44:18,534 INFO success: wsbroadcast entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-26 09:44:19,905 ERROR    awx.main.wsbroadcast AWX is currently installing/upgrading.  Trying again in 5s...
2021-04-26 09:44:26,300 INFO exited: wsbroadcast (exit status 0; expected)
2021-04-26 09:44:26,300 INFO exited: wsbroadcast (exit status 0; expected)
2021-04-26 09:44:27,303 INFO spawned: 'wsbroadcast' with pid 246
2021-04-26 09:44:27,303 INFO spawned: 'wsbroadcast' with pid 246
2021-04-26 09:44:28,304 INFO success: wsbroadcast entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-26 09:44:28,304 INFO success: wsbroadcast entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-26 09:44:30,368 ERROR    awx.main.wsbroadcast AWX is currently installing/upgrading.  Trying again in 5s...
2021-04-26 09:44:35,748 INFO exited: wsbroadcast (exit status 0; expected)
2021-04-26 09:44:35,748 INFO exited: wsbroadcast (exit status 0; expected)
2021-04-26 09:44:36,752 INFO spawned: 'wsbroadcast' with pid 252
2021-04-26 09:44:36,752 INFO spawned: 'wsbroadcast' with pid 252
2021-04-26 09:44:37,754 INFO success: wsbroadcast entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-26 09:44:37,754 INFO success: wsbroadcast entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-26 09:44:39,394 ERROR    awx.main.wsbroadcast AWX is currently installing/upgrading.  Trying again in 5s...
2021-04-26 09:44:44,794 INFO exited: wsbroadcast (exit status 0; expected)
2021-04-26 09:44:44,794 INFO exited: wsbroadcast (exit status 0; expected)
2021-04-26 09:44:45,797 INFO spawned: 'wsbroadcast' with pid 258
2021-04-26 09:44:45,797 INFO spawned: 'wsbroadcast' with pid 258
2021-04-26 09:44:46,798 INFO success: wsbroadcast entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-26 09:44:46,798 INFO success: wsbroadcast entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-26 09:44:48,173 ERROR    awx.main.wsbroadcast AWX is currently installing/upgrading.  Trying again in 5s...
2021-04-26 09:44:53,669 INFO exited: wsbroadcast (exit status 0; expected)
2021-04-26 09:44:53,669 INFO exited: wsbroadcast (exit status 0; expected)
2021-04-26 09:44:54,675 INFO spawned: 'wsbroadcast' with pid 264
2021-04-26 09:44:54,675 INFO spawned: 'wsbroadcast' with pid 264
2021-04-26 09:44:55,676 INFO success: wsbroadcast entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-26 09:44:55,676 INFO success: wsbroadcast entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-04-26 09:44:56,980 ERROR    awx.main.wsbroadcast AWX is currently installing/upgrading.  Trying again in 5s...
...
```

I have already tried to "force" migrations, but nothing is executed.
```
awx-manage migrate --noinput
Operations to perform:
  Apply all migrations: auth, conf, contenttypes, main, oauth2_provider, sessions, sites, social_django, sso, taggit
Running migrations:
  No migrations to apply.
```

My goal is to upgrade to the latest version (19.0.0) but there i get `KeyError: 'guid'`, so i want to clean up previous errors first.

Any help is highly appreciated.
Thanks in advance!

**Comment by symplialex** [comment]
Hello @sfhl , did you get a work around for the KeyError: 'guid' on 19.0.0?
Am facing the same situation as you did.

thanks

**Comment by sfhl** [comment]
@symplialex as far as i remember, even if it seems wrong, i was able to fix it using `awx-manage create_preload_data` on the awx-web (container).
Gladly that does not seem to imapct the existing data.

**Comment by jeffpascal** [comment]
Try this:

docker exec awx_web '/usr/bin/update-ca-trust'
docker exec awx_task '/usr/bin/update-ca-trust'

Worked for me.

**Comment by Iabdullahmaqsoodcodedistrict** [comment]
I want to build awx docker container but issue is with this docker-compose.yaml awx container successfully runing but following error logs throwing:
version: '3'
services:
  awx:
    image: ghcr.io/ansible/awx:21.10.2
    container_name: ansible_awx_container
    depends_on:
      - postgres
      - redis
    ports:
      - "80:8052"  # Mapping port 8052 inside the container to port 80 on the host machine
    environment:
      SECRET_KEY: 54SqkwPnO0sShGxh-6_3sg5F8qosdg-fZD073KHk_Cuw8Q0JQDDLWmUPRXlSUd7Pyb8
      BROADCAST_WEBSOCKET_SECRET: PK35aJsF7939ygfIwxTXYMzoutbPCfi-9jOuG3rPAShhZ_lfoe9IAf4biu_XzCtr4qU
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: awx
      DATABASE_PASSWORD: awx
      DATABASE_NAME: awx
    volumes:
      - awx_data:/var/lib/awx

  postgres:
    image: postgres:10
    container_name: postgres_container
    environment:
      POSTGRES_USER: awxuser
      POSTGRES_PASSWORD: awx
      POSTGRES_DB: awx
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis_container

volumes:
  awx_data:
  postgres_data:

Erro Logs:
2024-08-26 15:24:04 [wait-for-migrations] Waiting for database migrations...
2024-08-26 15:24:04 [wait-for-migrations] Attempt 1 of 30
2024-08-26 15:24:05 [wait-for-migrations] Waiting 0.5 seconds before next attempt
2024-08-26 15:24:06 [wait-for-migrations] Attempt 2 of 30
2024-08-26 15:24:07 [wait-for-migrations] Waiting 1 seconds before next attempt
2024-08-26 15:24:08 [wait-for-migrations] Attempt 3 of 30
2024-08-26 15:24:09 [wait-for-migrations] Waiting 2 seconds before next attempt
2024-08-26 15:24:11 [wait-for-migrations] Attempt 4 of 30
2024-08-26 15:24:11 [wait-for-migrations] Waiting 4 seconds before next attempt
2024-08-26 15:24:15 [wait-for-migrations] Attempt 5 of 30
2024-08-26 15:24:16 [wait-for-migrations] Waiting 8 seconds before next attempt
2024-08-26 15:24:24 [wait-for-migrations] Attempt 6 of 30
2024-08-26 15:24:25 [wait-for-migrations] Waiting 16 seconds before next attempt
2024-08-26 15:24:41 [wait-for-migrations] Attempt 7 of 30
2024-08-26 15:24:42 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:25:12 [wait-for-migrations] Attempt 8 of 30
2024-08-26 15:25:13 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:25:43 [wait-for-migrations] Attempt 9 of 30
2024-08-26 15:25:45 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:26:15 [wait-for-migrations] Attempt 10 of 30
2024-08-26 15:26:16 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:26:46 [wait-for-migrations] Attempt 11 of 30
2024-08-26 15:26:47 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:27:17 [wait-for-migrations] Attempt 12 of 30
2024-08-26 15:27:18 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:27:48 [wait-for-migrations] Attempt 13 of 30
2024-08-26 15:27:49 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:28:19 [wait-for-migrations] Attempt 14 of 30
2024-08-26 15:28:20 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:28:50 [wait-for-migrations] Attempt 15 of 30
2024-08-26 15:28:50 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:29:20 [wait-for-migrations] Attempt 16 of 30
2024-08-26 15:29:21 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:29:51 [wait-for-migrations] Attempt 17 of 30
2024-08-26 15:29:52 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:30:22 [wait-for-migrations] Attempt 18 of 30
2024-08-26 15:30:23 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:30:53 [wait-for-migrations] Attempt 19 of 30
2024-08-26 15:30:53 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:31:23 [wait-for-migrations] Attempt 20 of 30
2024-08-26 15:31:25 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:31:55 [wait-for-migrations] Attempt 21 of 30
2024-08-26 15:31:55 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:32:25 [wait-for-migrations] Attempt 22 of 30
2024-08-26 15:32:26 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:32:56 [wait-for-migrations] Attempt 23 of 30
2024-08-26 15:32:57 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:33:27 [wait-for-migrations] Attempt 24 of 30
2024-08-26 15:33:28 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:33:58 [wait-for-migrations] Attempt 25 of 30
2024-08-26 15:33:59 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:34:29 [wait-for-migrations] Attempt 26 of 30
2024-08-26 15:34:29 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:34:59 [wait-for-migrations] Attempt 27 of 30
2024-08-26 15:35:00 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:35:30 [wait-for-migrations] Attempt 28 of 30
2024-08-26 15:35:31 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:36:01 [wait-for-migrations] Attempt 29 of 30
2024-08-26 15:36:02 [wait-for-migrations] Waiting 30 seconds before next attempt
2024-08-26 15:36:32 [wait-for-migrations] Attempt 30 of 30
2024-08-26 15:36:32 [wait-for-migrations] ERROR: Database migrations not applied

**Comment by ppodgorsek** [comment]
@Iabdullahmaqsoodcodedistrict If you had read the second reply at the top of this thread, you would have seen the answer you're looking for...

**Comment by Iabdullahmaqsoodcodedistrict** [comment]
@ppodgorsek Issue resolved Thanks
