### ISSUE TITLE
AWX version 10 Crashes with 12 or more pods running 

### ISSUE THREAD

**Issue by wbieniek** [ansible/awx#6543]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Initially scale OpenShift AWX cluster to 12 pods without any issue, then try to add one more pods, which started successfully, but AWX GUI stop responding with the following error:

Server Error
A server error has occurred.

#### ENVIRONMENT
* AWX version: 10
* AWX install method: openshift
* Ansible version:  2.9.5
* Operating System:
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Start 12 pods in openshift then try to add additional pods
Reducing number of pods to 12 restored GUI and normal operations
##### ACTUAL RESULTS

Cluster stop responding 

##### ADDITIONAL INFORMATION
WEB log:
2020-04-02 14:59:55,405 WARNING  awx.main.wsbroadcast awx-0 going to add {'awx-11'} to the websocket broadcast list
2020-04-02 14:59:55,406 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 0 to awx-11
2020-04-02 14:59:55,420 WARNING  awx.main.wsbroadcast Failed to connect to awx-11: 'Cannot connect to host awx-11:8052 ssl:False [Name or service not known]'. Reconnecting ...
2020-04-02 14:59:55,421 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 1 to awx-11
2020-04-02 14:59:57,861 INFO     awx.main.consumers Broadcast client connected.
2020-04-02 14:59:57,861 INFO     Broadcast client connected.
2020-04-02 15:00:00,444 WARNING  awx.main.wsbroadcast Failed to connect to awx-11: 'Cannot connect to host awx-11:8052 ssl:False [Name or service not known]'. Reconnecting ...
2020-04-02 15:00:00,445 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 2 to awx-11
RESULT 2
OKREADY
2020-04-02 15:00:05,414 WARNING  awx.main.wsbroadcast awx-0 going to remove {'awx-11'} from the websocket broadcast list
2020-04-02 15:00:05,414 WARNING  awx.main.wsbroadcast awx-0 going to add {'172.20.218.191'} to the websocket broadcast list
2020-04-02 15:00:05,415 WARNING  awx.main.wsbroadcast awx-0 connection to awx-11 cancelled
2020-04-02 15:00:05,415 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 0 to 172.20.218.191
RESULT 2
OKREADY
RESULT 2
OKREADY
2020-04-02 15:02:05,512 WARNING  awx.main.wsbroadcast awx-0 going to add {'awx-12'} to the websocket broadcast list
2020-04-02 15:02:05,513 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 0 to awx-12
2020-04-02 15:02:05,526 WARNING  awx.main.wsbroadcast Failed to connect to awx-12: 'Cannot connect to host awx-12:8052 ssl:False [Name or service not known]'. Reconnecting ...
2020-04-02 15:02:05,527 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 1 to awx-12
2020-04-02 15:02:09,724 INFO     awx.main.consumers Broadcast client connected.
2020-04-02 15:02:09,724 INFO     Broadcast client connected.
2020-04-02 15:02:10,539 WARNING  awx.main.wsbroadcast Failed to connect to awx-12: 'Cannot connect to host awx-12:8052 ssl:False [Name or service not known]'. Reconnecting ...
2020-04-02 15:02:10,540 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 2 to awx-12
2020-04-02 15:02:15,555 WARNING  awx.main.wsbroadcast Failed to connect to awx-12: 'Cannot connect to host awx-12:8052 ssl:False [Name or service not known]'. Reconnecting ...
2020-04-02 15:02:15,556 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 3 to awx-12
2020-04-02 15:02:20,571 WARNING  awx.main.wsbroadcast Failed to connect to awx-12: 'Cannot connect to host awx-12:8052 ssl:False [Name or service not known]'. Reconnecting ...
2020-04-02 15:02:20,572 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 4 to awx-12
2020-04-02 15:02:25,593 WARNING  awx.main.wsbroadcast Failed to connect to awx-12: 'Cannot connect to host awx-12:8052 ssl:False [Name or service not known]'. Reconnecting ...
2020-04-02 15:02:25,594 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 5 to awx-12
2020-04-02 15:02:30,658 WARNING  awx.main.wsbroadcast Failed to connect to awx-12: 'Cannot connect to host awx-12:8052 ssl:False [Name or service not known]'. Reconnecting ...
2020-04-02 15:02:30,659 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 6 to awx-12
2020-04-02 15:02:35,704 WARNING  awx.main.wsbroadcast Failed to connect to awx-12: 'Cannot connect to host awx-12:8052 ssl:False [Name or service not known]'. Reconnecting ...
2020-04-02 15:02:35,706 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 7 to awx-12
2020-04-02 15:02:40,722 WARNING  awx.main.wsbroadcast Failed to connect to awx-12: 'Cannot connect to host awx-12:8052 ssl:False [Name or service not known]'. Reconnecting ...
2020-04-02 15:02:40,722 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 8 to awx-12
2020-04-02 15:02:45,771 WARNING  awx.main.wsbroadcast Failed to connect to awx-12: 'Cannot connect to host awx-12:8052 ssl:False [Name or service not known]'. Reconnecting ...
2020-04-02 15:02:45,771 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 9 to awx-12
2020-04-02 15:02:50,782 WARNING  awx.main.wsbroadcast Failed to connect to awx-12: 'Cannot connect to host awx-12:8052 ssl:False [Name or service not known]'. Reconnecting ...
2020-04-02 15:02:50,783 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 10 to awx-12
2020-04-02 15:02:55,800 WARNING  awx.main.wsbroadcast Failed to connect to awx-12: 'Cannot connect to host awx-12:8052 ssl:False [Name or service not known]'. Reconnecting ...
2020-04-02 15:02:55,800 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 11 to awx-12
2020-04-02 15:03:00,825 WARNING  awx.main.wsbroadcast Failed to connect to awx-12: 'Cannot connect to host awx-12:8052 ssl:False [Name or service not known]'. Reconnecting ...
RESULT 2
OKREADY
2020-04-02 15:03:00,826 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 12 to awx-12
2020-04-02 15:03:05,839 WARNING  awx.main.wsbroadcast Failed to connect to awx-12: 'Cannot connect to host awx-12:8052 ssl:False [Name or service not known]'. Reconnecting ...
2020-04-02 15:03:05,914 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 13 to awx-12
2020-04-02 15:03:10,927 WARNING  awx.main.wsbroadcast Failed to connect to awx-12: 'Cannot connect to host awx-12:8052 ssl:False [Name or service not known]'. Reconnecting ...
2020-04-02 15:03:10,928 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 14 to awx-12
2020-04-02 15:03:15,941 WARNING  awx.main.wsbroadcast Failed to connect to awx-12: 'Cannot connect to host awx-12:8052 ssl:False [Name or service not known]'. Reconnecting ...
2020-04-02 15:03:15,942 DEBUG    awx.main.wsbroadcast awx-0 connect attempt 15 to awx-12

TASK log:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  remaining connection slots are reserved for non-replication superuser connections

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/conf/settings.py", line 76, in _ctit_db_wrapper
    yield
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/conf/settings.py", line 404, in __getattr__
    value = self._get_local(name)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/conf/settings.py", line 347, in _get_local
    setting = Setting.objects.filter(key=name, user__isnull=True).order_by('pk').first()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 653, in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1138, in execute_sql
    cursor = self.connection.cursor()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  remaining connection slots are reserved for non-replication superuser connections

**Comment by ryanpetrello** [comment]
> django.db.utils.OperationalError: FATAL: remaining connection slots are reserved for non-replication superuser connections

Looks to me like your postgres is running out of connections cc @chrismeyersfsu @elyezer

**Comment by wbieniek** [comment]
Increasing postgres connections solved this issue  
thank you

**Comment by ryanpetrello** [comment]
@wbieniek 

Do you know what the connection threshold was set to before and after your change?  Just curious if what you're encountering is more of an anomaly.  It's true that 10.0.x _will_ require more active connections because the dispatchers now use postgres as a sort of distributed queue (instead of RabbitMQ).

**Comment by wbieniek** [comment]
it was set to 100. I increased to 500.
current connection with 14 pods
postgres=# select max_conn,used,res_for_super,max_conn-used-res_for_super res_for_normal
from
  (select count(*) used from pg_stat_activity) t1,
  (select setting::int res_for_super from pg_settings where name=$$superuser_reserved_connections$$) t2,
  (select setting::int max_conn from pg_settings where name=$$max_connections$$) t3;
 max_conn | used | res_for_super | res_for_normal
----------+------+---------------+----------------
      500 |  103 |             3 |            394
(1 row)

postgres=#

**Comment by wbieniek** [comment]
postgres=# SELECT
now() - query_start as "ELAPSED_TIME",
usename as "USERNAME",
datname as "DBNAME",
wait_event as "EVENT",
substR(query, 1,34) as "SQL_Text"
FROM
pg_stat_activity
WHERE
state != 'idle'
ORDER BY 1 DESC limit 20;
 ELAPSED_TIME | USERNAME |  DBNAME  | EVENT |          SQL_Text
--------------+----------+----------+-------+-----------------------------
 00:00:00     | postgres | postgres |       | SELECT                     +
              |          |          |       | now() - query_start as "ELA
(1 row)

postgres=#

**Comment by ryanpetrello** [comment]
Yea, for a cluster this size, 100 connections is probably just too few.  Even though they're pooled, there _are_ a number of persistent services running on each node - servicing HTTP requests, the dispatcher workers that run playbooks, the callback receivers that persist stdout into the database.  Multiply those `x14` and it's easy to see how you could break 100.  This is especially true if you're running playbooks in parallel and causing the dispatcher worker pool to autoscale up (more actively running playbooks == more active database connections to persist the results).

One thing I'd appreciate - if you notice the number *growing* over time (without adding cluster capacity), and not going down, please reopen this issue with some details.

**Comment by wbieniek** [comment]
will do, thank you
