### ISSUE TITLE
Fail to send Grafana notification

### ISSUE THREAD

**Issue by ghost** [ansible/awx#6580]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When I try to send a notification to Grafana, AWX returns an error.

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: Kubernetes 1.18.0
* Ansible version:  2.9.5
* Operating System: macOS Catalina
* Web Browser: Mozilla Firefox 74.0

##### STEPS TO REPRODUCE
1. Configure Grafana notification
2. Click on "Test notification"

##### EXPECTED RESULTS
Notification sent successfully.

##### ACTUAL RESULTS
From awx_tasks log:
```
2020-04-04 23:37:53,653 DEBUG    awx.main.dispatch task 7bc53b9c-c78c-4f96-91e6-08dd52eb9285 starting awx.main.tasks.send_notifications(*[[8]])
2020-04-04 23:37:53,717 ERROR    awx.main.notifications.grafana_backend Error sending notification grafana: [{"classification":"DeserializationError","message":"json: cannot unmarshal string into Go struct field PostAnnotationsCmd.tags of type []string"}]
2020-04-04 23:37:53,719 ERROR    awx.main.tasks Send Notification Failed Error sending notification grafana: [{"classification":"DeserializationError","message":"json: cannot unmarshal string into Go struct field PostAnnotationsCmd.tags of type []string"}]
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 330, in send_notifications
    sent = notification.notification_template.send(notification.subject, notification.body)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/notifications.py", line 196, in send
    return backend_obj.send_messages([notification_obj])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/notifications/grafana_backend.py", line 103, in send_messages
    raise Exception(smart_text(_("Error sending notification grafana: {}").format(r.text)))
Exception: Error sending notification grafana: [{"classification":"DeserializationError","message":"json: cannot unmarshal string into Go struct field PostAnnotationsCmd.tags of type []string"}]
```

##### ADDITIONAL INFORMATION
Both AWX and Grafana are deployed in the same Kubernetes cluster.

**Comment by ryanpetrello** [comment]
I'm able to reproduce this:

![image](https://user-images.githubusercontent.com/214912/78590101-4a067080-780f-11ea-9214-a63a726f388c.png)

...but only when I fail to put in valid tags in the notification configuration:

![image](https://user-images.githubusercontent.com/214912/78590173-6a362f80-780f-11ea-853e-2d17bf47a3d2.png)

If I specify one or more tags, it works fine:

![image](https://user-images.githubusercontent.com/214912/78590155-60acc780-780f-11ea-93f7-2d0ee436e71d.png)

**Comment by ryanpetrello** [comment]
@ldepandis want to give this change a whirl?

https://github.com/ansible/awx/pull/6607

**Comment by ghost** [comment]
@ryanpetrello Thank your for your support!
I just noticed another thing.
If you add a tag, save the configuration and then remove it before sending a notification it just works. Are you able to confirm this behavior in your environment?
Also, this bug seems happening only the first time you're configuring the notification.
After that time, even if you remove every tag, it just works properly.

About your change, sure thing. I will check it right now.

**Comment by ghost** [comment]
@ryanpetrello I can confirm that with your branch everything is working properly.
Here the notification sent to Grafana right after I created the notification resource.

<img width="388" alt="image" src="https://user-images.githubusercontent.com/13005894/78608919-fa04c980-7861-11ea-938d-7996d0cd7eaf.png">


Thank you for your support!

**Comment by ryanpetrello** [comment]
Thanks for confirming, @ldepandis - I'll get the PR merged and released in the next version of AWX.

**Comment by one-t** [comment]
Tested on devel using Grafana deployed on GKE, this is working as expected
