### ISSUE TITLE
500 on project edit/update (channels)

### ISSUE THREAD

**Issue by wilkis3** [ansible/awx#6598]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
If I create a new project or used an existing project (I deleted all of them :grimacing:) I got an error message and I can't do anything.

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: docker
* Ansible version: 2.9.5
* Operating System: Ubuntu 18.04.4
* Web Browser: Firefox, Chromium

##### STEPS TO REPRODUCE

1. Added credentials
2. Setup an new project (select name, scm type(git), scm url, scm credentials)
2.1. Clicked Save
2.2. In-windows popup message notified: 
```
ERROR!
Failed to create new project. POST returned status: 500 A server error has occurred.
```
3. Job to update project starts automatically
3.1. Update job failed, without any message, only with the following explanation:
```
Task was marked as running in Tower but was not present in the job queue, so it has been marked as failed. 
```

##### EXPECTED RESULTS

SCM update works, without any interrupts.

##### ACTUAL RESULTS

I can't update or create a new project.

##### ADDITIONAL INFORMATION

* awx-web log:
```
2020-04-06 17:34:25,271 WARNING  awx.main.analytics.broadcast_websocket ('Unsupported URI scheme', 'amqp')
2020-04-06 17:34:25,423 ERROR    django.request Internal Server Error: /api/v2/projects/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/transaction.py", line 284, in __exit__
    connection.set_autocommit(True)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 410, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 636, in run_and_clear_commit_hooks
    func()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/unified_jobs.py", line 1255, in <lambda>
    connection.on_commit(lambda: self._websocket_emit_status(status))
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/unified_jobs.py", line 1245, in _websocket_emit_status
    emit_channel_notification('jobs-status_changed', status_data)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/consumers.py", line 248, in emit_channel_notification
    channel_layer = get_channel_layer()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/channels/layers.py", line 363, in get_channel_layer
    return channel_layers[alias]
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/channels/layers.py", line 80, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/channels/layers.py", line 46, in make_backend
    return self._make_backend(name, config)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/channels/layers.py", line 63, in _make_backend
    % name
channels.exceptions.InvalidChannelLayerError: ROUTING key found for default - this is no longer needed in Channels 2.
2020-04-06 17:34:25,423 ERROR    django.request Internal Server Error: /api/v2/projects/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/transaction.py", line 284, in __exit__
    connection.set_autocommit(True)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 410, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 636, in run_and_clear_commit_hooks
    func()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/unified_jobs.py", line 1255, in <lambda>
    connection.on_commit(lambda: self._websocket_emit_status(status))
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/unified_jobs.py", line 1245, in _websocket_emit_status
    emit_channel_notification('jobs-status_changed', status_data)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/consumers.py", line 248, in emit_channel_notification
    channel_layer = get_channel_layer()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/channels/layers.py", line 363, in get_channel_layer
    return channel_layers[alias]
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/channels/layers.py", line 80, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/channels/layers.py", line 46, in make_backend
    return self._make_backend(name, config)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/channels/layers.py", line 63, in _make_backend
    % name
channels.exceptions.InvalidChannelLayerError: ROUTING key found for default - this is no longer needed in Channels 2.
172.18.0.7 - - [06/Apr/2020:17:34:25 +0200] "POST /api/v2/projects/ HTTP/1.1" 500 41 "https://awx.COMPANY.TLD/" "Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" "XXX.XXX.XXX.XXX"
[pid: 102|app: 0|req: 283/751] 172.18.0.7 () {68 vars in 2832 bytes} [Mon Apr  6 17:34:25 2020] POST /api/v2/projects/ => generated 41 bytes in 411 msecs (HTTP/1.1 500) 5 headers in 185 bytes (1 switches on core 0)
```

Screenshot: in-windows popup message
![scrn-2020-04-06-17-49-02](https://user-images.githubusercontent.com/36081959/78578961-8a2a1b00-7830-11ea-948c-8d065eab6fe0.png)

**Comment by ryanpetrello** [comment]
@chrismeyersfsu you have any idea what's up here?

**Comment by wilkis3** [comment]
We have restored a backup from AWX 9.3.0 from last Friday. It sould be a problem with AWX 10.0.0.

**Comment by Cartman25** [comment]
Hello, exactly the same here. I thought it was the lack of python in /usr/bin but still the same problem.

**Comment by chrismeyersfsu** [comment]
@Cartman25 @wilkis3 Check to see if there is a `credentials.py` file hanging around from previous awx installs in `~/.awx/awxcompose/`. If so, delete it.

**Comment by Cartman25** [comment]
Hey sorry for he delay.

I try to play with this new version in my Dev environment.

/!\ i just read that RabbitMQ is no more in AWX, i'll upgrade my AWX with REDIS
--> [https://groups.google.com/forum/#!topic/awx-project/lRnm2vB1oEQ](url)

I run AWX with docker and i checked with both awx_web & awx_task containers. I have no awxcompose folder anywhere.

The only file i see is in my custom **awx_config** in my docker host

```
- name: Create Docker Compose Configuration
  template:
    src: "{{ item }}.j2"
    dest: "{{ awx_config_dir }}/{{ item }}"
    mode: 0600
    owner: 1001
  with_items:
    - environment.sh
    - credentials.py
    - nginx.conf
  register: awx_config
```

and my **credentials.py** template :

```
DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': "{{ pg_database }}",
        'USER': "{{ pg_username }}",
        'PASSWORD': "{{ pg_password }}",
        'HOST': "{{ pg_hostname|default('postgres') }}",
        'PORT': "{{ pg_port }}",
    }
}
BROKER_URL = 'amqp://{}:{}@{}:{}/{}'.format(
    "{{ rabbitmq_user }}",
    "{{ rabbitmq_password }}",
    "rabbitmq",
    "5672",
    "awx")

CHANNEL_LAYERS = {
    'default': {'BACKEND': 'asgi_amqp.AMQPChannelLayer',
                'ROUTING': 'awx.main.routing.channel_routing',
                'CONFIG': {'url': BROKER_URL}}
}
```
I also added `BROADCAST_WEBSOCKET_SECRET = "{{ broadcast_websocket_secret | b64encode }}"` in **credentials.py** but i have the same box error when i try to update a project or run a template in the web interface.

Has something changed ?

**Comment by wilkis3** [comment]
@chrismeyersfsu @Cartman25 
We didn't find any awxcompose directory. And we're also use RabbitMQ currently.
An AWX upgrade to the version 10.0.0, 11.0.0 or 11.2.0 won't solved the problem.

**Comment by Cartman25** [comment]
@wilkis3 

/!\ RabbitMQ is no more in AWX, i made the upgrade to AWX with REDIS and it worked well 
--> https://groups.google.com/forum/#!topic/awx-project/lRnm2vB1oEQ

**Comment by wilkis3** [comment]
@Cartman25 @chrismeyersfsu 
Yes, we have used RabbitMQ and not Redis, that was the problem. Now it works with Redis.
