### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by cmdrrobin** [ansible/awx#661]
##### ISSUE TYPE
 - Bug Report
 
##### COMPONENT NAME
 - TASK

##### SUMMARY
```
[2017-11-15 19:46:40,056: ERROR/MainProcess] Control command error: error(104, 'Connection reset by peer')
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/worker/pidbox.py", line 42, in on_message
    self.node.handle_message(body, message)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/pidbox.py", line 129, in handle_message
    return self.dispatch(**body)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/pidbox.py", line 112, in dispatch
    ticket=ticket)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/pidbox.py", line 135, in reply
    serializer=self.mailbox.serializer)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/pidbox.py", line 265, in _publish_reply
    **opts
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/messaging.py", line 194, in _publish
    [maybe_declare(entity) for entity in declare]
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/messaging.py", line 102, in maybe_declare
    return maybe_declare(entity, self.channel, retry, **retry_policy)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/common.py", line 129, in maybe_declare
    return _maybe_declare(entity, declared, ident, channel, orig)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/common.py", line 135, in _maybe_declare
    entity.declare(channel=channel)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/kombu/entity.py", line 185, in declare
    nowait=nowait, passive=passive,
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/channel.py", line 616, in exchange_declare
    wait=None if nowait else spec.Exchange.DeclareOk,
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/abstract_channel.py", line 50, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/method_framing.py", line 166, in write_frame
    write(view[:offset])
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/amqp/transport.py", line 258, in write
    self._write(s)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer
```

##### ENVIRONMENT
* AWX version: 1.0.1
* AWX install method: Kubernetes
* Ansible version:  <<DONT KNOW WHICH VERSION IT USES>>
* Operating System: Rancher OS
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Running the following deployment:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: awx-task
  namespace: services
  labels:
    app: awx
    role: task
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: awx
        role: task
    spec:
      hostname: "awx"
      containers:
      - name: awx-task
        image: ansible/awx_task:1.0.1
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: awx-task-secrets
              key: secret_key
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: awx-task-secrets
              key: db_username
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: awx-task-secrets
              key: db
        - name: DATABASE_HOST
          value: awx-db.backend
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: awx-task-secrets
              key: db_password
        - name: DATABASE_PORT
          value: "5432"
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        - name: RABBITMQ_HOST
          value: "awx-queue.backend"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_VHOST
          value: "awx"
        - name: MEMCACHED_HOST
          value: "awx-cache.backend"
        - name: MEMCACHED_PORT
          value: "11211"
        - name: AWX_ADMIN_USER
          value: "admin"
        - name: AWX_ADMIN_PASSWORD
          value: "ansible"

```

##### EXPECTED RESULTS
When I use version `1.0.1.176` it works fine.

##### ACTUAL RESULTS
I'm wonder what version of `ansible/awx_task` should be stable?

**Comment by cmdrrobin** [comment]
Ment to say version `1.0.1.167`. (not `1.0.1.176`)

**Comment by matburt** [comment]
This doesn't look like our deployment yml... did you move the rabbitmq service out of the pod?

You are kind-of on your own if you do that, we specifically keep that together with other pod services to reduce this kind of disconnection.

There will be several other places in the code you'll probably need to change to make this work.

**Comment by cmdrrobin** [comment]
@matburt what is the point of setting `RABBITMQ_HOST` variable if it's being used...
Also the message states `error: [Errno 104] Connection reset by peer` which is not refused, but rather reset by some issue.
Anyway, version `1.0.1.167` works fine for testing. Will keep testing this.

Maybe an idea to add a tag `stable` to the Docker image release which is stable for using/testing.

**Comment by matburt** [comment]
At the moment the `devel` branch is under heavy development for new features. We can't ever really guarantee anything is *stable* per-se :)
