### ISSUE TITLE
git inventory sync stuck after upgrade from 10 to 11

### ISSUE THREAD

**Issue by zilkanir** [ansible/awx#6770]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
after inventory file changes , inventory sync jobs are stuck with awx 11 (it was working on awx 10).

##### ENVIRONMENT
* AWX version: 11.0.0
* AWX install method: docker on linux
* Ansible version: 2.9.5
* Operating System: CentOS 7.5 (docker)
* Web Browser: chrome

##### STEPS TO REPRODUCE

log from job (and the job keep running forever, and i need to manually cancel):

    6.200 INFO     Updating inventory 2: Linux
    7.081 INFO     Reading Ansible inventory source: /tmp/awx_10158_58549ekn/project/hosts
    7.085 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    7.085 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    7.085 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
    8.049 ERROR    ansible-inventory 2.9.5
    8.049 ERROR      config file = /etc/ansible/ansible.cfg
    8.049 ERROR      configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
    8.050 ERROR      ansible python module location = /usr/lib/python3.6/site-packages/ansible
    8.050 ERROR      executable location = /usr/bin/ansible-inventory
    8.050 ERROR      python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
    8.050 ERROR    Using /etc/ansible/ansible.cfg as config file
    8.050 ERROR    host_list declined parsing /tmp/awx_10158_58549ekn/project/hosts as it did not pass its verify_file() method
    8.050 ERROR    script declined parsing /tmp/awx_10158_58549ekn/project/hosts as it did not pass its verify_file() method
    8.050 ERROR    auto declined parsing /tmp/awx_10158_58549ekn/project/hosts as it did not pass its verify_file() method
    8.050 ERROR    Parsed /tmp/awx_10158_58549ekn/project/hosts inventory source with ini plugin
    8.050 ERROR    
    8.050 INFO     Processing JSON output...
    8.058 INFO     Loaded 27 groups, 476 hosts

##### EXPECTED RESULTS

the job should sync quickly the inventory from remote git file

##### ACTUAL RESULTS

job stuck

**Comment by zilkanir** [comment]
the job finished eventually after 20 minutes (5 minutes after the other running jobs completed. the inventory is with overwrite on)

**Comment by zilkanir** [comment]
Now another inventory file changes to remote git (remove hosts - ini file) cause inventory sync to fail. something wrong with the git inventory sync, here is the failed job log:

    7.097 INFO     Updating inventory 2: Linux
    7.777 INFO     Reading Ansible inventory source: /tmp/awx_10917_9x16ocdv/project/hosts
    7.780 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    7.781 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    7.781 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
    8.660 ERROR    ansible-inventory 2.9.5
    8.660 ERROR      config file = /etc/ansible/ansible.cfg
    8.661 ERROR      configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
    8.661 ERROR      ansible python module location = /usr/lib/python3.6/site-packages/ansible
    8.661 ERROR      executable location = /usr/bin/ansible-inventory
    8.661 ERROR      python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
    8.661 ERROR    Using /etc/ansible/ansible.cfg as config file
    8.661 ERROR    host_list declined parsing /tmp/awx_10917_9x16ocdv/project/hosts as it did not pass its verify_file() method
    8.661 ERROR    script declined parsing /tmp/awx_10917_9x16ocdv/project/hosts as it did not pass its verify_file() method
    8.661 ERROR    auto declined parsing /tmp/awx_10917_9x16ocdv/project/hosts as it did not pass its verify_file() method
    8.661 ERROR    Parsed /tmp/awx_10917_9x16ocdv/project/hosts inventory source with ini plugin
    8.661 ERROR    
    8.662 INFO     Processing JSON output...
    8.671 INFO     Loaded 27 groups, 474 hosts
2020-04-22 20:50:22,511 DEBUG    awx.main.models.inventory Going to update inventory computed fields, pk=2
2020-04-22 20:50:22,554 DEBUG    awx.main.models.inventory Finished updating inventory computed fields, pk=2, in 0.042 seconds
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 240, in _commit
    return self.connection.commit()
psycopg2.errors.ForeignKeyViolation: update or delete on table "main_host" violates foreign key constraint "main_jobhostsummary_host_id_7d9f6bf9_fk_main_host_id" on table "main_jobhostsummary"
DETAIL:  Key (id)=(457) is still referenced from table "main_jobhostsummary".
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1139, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1090, in handle
    self.check_org_host_limit()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/transaction.py", line 240, in __exit__
    connection.commit()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 262, in commit
    self._commit()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 240, in _commit
    return self.connection.commit()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 240, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: update or delete on table "main_host" violates foreign key constraint "main_jobhostsummary_host_id_7d9f6bf9_fk_main_host_id" on table "main_jobhostsummary"
DETAIL:  Key (id)=(457) is still referenced from table "main_jobhostsummary".

**Comment by zilkanir** [comment]
I disabled all schedules , and after 1-2 hours i ran again the inventory sync and it succeeded (after ~30min)

    8.787 INFO     Updating inventory 2: Linux
    9.231 INFO     Reading Ansible inventory source: /tmp/awx_11232_vnc7rw7u/project/hosts
    9.235 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    9.235 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    9.235 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
   10.186 ERROR    ansible-inventory 2.9.5
   10.186 ERROR      config file = /etc/ansible/ansible.cfg
   10.186 ERROR      configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
   10.186 ERROR      ansible python module location = /usr/lib/python3.6/site-packages/ansible
   10.186 ERROR      executable location = /usr/bin/ansible-inventory
   10.186 ERROR      python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
   10.187 ERROR    Using /etc/ansible/ansible.cfg as config file
   10.187 ERROR    host_list declined parsing /tmp/awx_11232_vnc7rw7u/project/hosts as it did not pass its verify_file() method
   10.187 ERROR    script declined parsing /tmp/awx_11232_vnc7rw7u/project/hosts as it did not pass its verify_file() method
   10.187 ERROR    auto declined parsing /tmp/awx_11232_vnc7rw7u/project/hosts as it did not pass its verify_file() method
   10.187 ERROR    Parsed /tmp/awx_11232_vnc7rw7u/project/hosts inventory source with ini plugin
   10.187 ERROR    
   10.187 INFO     Processing JSON output...
   10.197 INFO     Loaded 27 groups, 474 hosts
2020-04-23 13:00:31,561 DEBUG    awx.main.models.inventory Going to update inventory computed fields, pk=2
2020-04-23 13:00:31,625 DEBUG    awx.main.models.inventory Finished updating inventory computed fields, pk=2, in 0.062 seconds
 1600.032 INFO     Inventory import completed for git inventory in 1591.3s

**Comment by zilkanir** [comment]
Hi,

I've upgraded to 12.0 and now when i'm removing hosts from git ansible ini file and commit , this is the results of awx inventory sync:

    5.838 INFO     Updating inventory 2: Linux
    7.248 INFO     Reading Ansible inventory source: /tmp/awx_40439_ischcd_k/project/hosts
    7.255 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    7.255 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    7.255 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
    8.672 ERROR    ansible-inventory 2.9.9
    8.672 ERROR      config file = /etc/ansible/ansible.cfg
    8.674 ERROR      configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
    8.674 ERROR      ansible python module location = /usr/lib/python3.6/site-packages/ansible
    8.674 ERROR      executable location = /usr/bin/ansible-inventory
    8.674 ERROR      python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
    8.675 ERROR    Using /etc/ansible/ansible.cfg as config file
    8.675 ERROR    host_list declined parsing /tmp/awx_40439_ischcd_k/project/hosts as it did not pass its verify_file() method
    8.675 ERROR    script declined parsing /tmp/awx_40439_ischcd_k/project/hosts as it did not pass its verify_file() method
    8.675 ERROR    auto declined parsing /tmp/awx_40439_ischcd_k/project/hosts as it did not pass its verify_file() method
    8.675 ERROR    Parsed /tmp/awx_40439_ischcd_k/project/hosts inventory source with ini plugin
    8.675 INFO     Processing JSON output...
    8.682 INFO     Loaded 24 groups, 473 hosts
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DeadlockDetected: deadlock detected
DETAIL:  Process 18699 waits for ShareLock on transaction 52550177; blocked by process 20490.
Process 20490 waits for ShareLock on transaction 52548518; blocked by process 18699.
HINT:  See server log for query details.
CONTEXT:  while deleting tuple (2,8) in relation "main_host"
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django_pglocks/__init__.py", line 74, in advisory_lock
    yield acquired
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/utils/pglock.py", line 14, in advisory_lock
    yield internal_lock
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 883, in load_into_database
    self._delete_hosts()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 475, in _delete_hosts
    host.delete()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/inventory.py", line 602, in delete
    super(Host, self).delete(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/base.py", line 919, in delete
    return collector.delete()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/deletion.py", line 312, in delete
    count = query.delete_batch(pk_list, self.using)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/sql/subqueries.py", line 41, in delete_batch
    num_deleted += self.do_query(self.get_meta().db_table, self.where, using=using)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/sql/subqueries.py", line 24, in do_query
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: deadlock detected
DETAIL:  Process 18699 waits for ShareLock on transaction 52550177; blocked by process 20490.
Process 20490 waits for ShareLock on transaction 52548518; blocked by process 18699.
HINT:  See server log for query details.
CONTEXT:  while deleting tuple (2,8) in relation "main_host"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 154, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1141, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1076, in handle
    self.load_into_database()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 890, in load_into_database
    self._create_update_group_hosts()
  File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/utils/pglock.py", line 14, in advisory_lock
    yield internal_lock
  File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django_pglocks/__init__.py", line 80, in advisory_lock
    cursor.execute(command)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in _execute
    self.db.validate_no_broken_transaction()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 438, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

Thanks,
Nir.

**Comment by shanemcd** [comment]
Hello, does this still happen on latest AWX?

**Comment by zilkanir** [comment]
No, you can close the issue.
Thanks
