### ISSUE TITLE
firehose.py fails with: UnboundLocalError: local variable 'indexes' referenced before assignment

### ISSUE THREAD

**Issue by jhutar** [ansible/awx#6902]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
firehose.py fails with: `UnboundLocalError: local variable 'indexes' referenced before assignment`

##### ENVIRONMENT
firehose.py from recent checkout running on ansible-tower-3.6.4-1.el8at.x86_64

```
# git log tools/scripts/firehose.py | head -n 5
commit 59477aa22165f0c54d624f91bf7e742a7b41477d
Author: Mat Wilson <mawilson@redhat.com>
Date:   Mon Apr 6 10:54:08 2020 -0700

    update firehose script for bigint migration
```

##### STEPS TO REPRODUCE
```
# awx/tools/scripts/firehose.py --jobs 100 --events 100000
2020-04-30T20:58:53.691463
inserting 100 job(s)
running batch 1, runtime 5.245208740234375e-06
took 0.15918254852294922
removing indexes and constraints
2020-04-30T20:58:55.729901
restoring indexes and constraints (this may take awhile)
Traceback (most recent call last):
  File "awx/tools/scripts/firehose.py", line 197, in generate_events
    cursor.execute('ALTER TABLE main_jobevent SET UNLOGGED')
psycopg2.errors.InvalidTableDefinition: could not change table "main_jobevent" to unlogged because it references logged table "main_jobevent_hosts"


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "awx/tools/scripts/firehose.py", line 296, in <module>
    generate_events(events, str(created.pk))
  File "awx/tools/scripts/firehose.py", line 255, in generate_events
    for indexname, indexdef in indexes:
UnboundLocalError: local variable 'indexes' referenced before assignment
```

##### EXPECTED RESULTS
Should work

##### ACTUAL RESULTS
Traceback

##### ADDITIONAL INFORMATION
None

**Comment by wenottingham** [comment]
firehose.py talks to the raw database, and is therefore tied to the version of AWX it comes from. It is not intended to be a standalone tool used on arbitrary versions.
