### ISSUE TITLE
AWX not working in Openshift after install - 502 Bad Gateway nginx

### ISSUE THREAD

**Issue by parasharsingh8086** [ansible/awx#6904]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: openshift
* Ansible version: 2.6.19
* Operating System: Red Hat Enterprise Linux 7.7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

<!
Installation has no error msg reported:

TASK [local_docker : Update CA trust in awx_task container] *************************************************************************************************************************************
skipping: [localhost]

PLAY RECAP **************************************************************************************************************************************************************************************
localhost                  : ok=47   changed=20   unreachable=0    failed=0

[root@uswix532 awx]# oc get pod
NAME                   READY     STATUS    RESTARTS   AGE
awx-85575c8fbd-l9mf9   4/4       Running   0          7m
postgresql-1-ttjqb     1/1       Running   0          11m
[root@uswix532 awx]#
[root@uswix532 awx]# oc get route
NAME          HOST/PORT                                 PATH      SERVICES      PORT      TERMINATION     WILDCARD
awx-web       awx-web.tapps.oc.kohlerco.com                       awx-web-svc   http                      None
awx-web-svc   awx-web-svc-awx-1.tapps.oc.kohlerco.com             awx-web-svc   http      edge/Redirect   None
[root@uswix532 awx]# curl http://awx-web.tapps.oc.kohlerco.com
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
[root@uswix532 awx]#

I look into awx pod logs, and saw this:

335 static files copied to '/var/lib/awx/public/static'.
2020-04-30 19:03:43,330 INFO RPC interface 'supervisor' initialized
2020-04-30 19:03:43,330 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-04-30 19:03:43,330 INFO supervisord started with pid 72
2020-04-30 19:03:44,333 INFO spawned: 'awx-config-watcher' with pid 75
2020-04-30 19:03:44,337 INFO spawned: 'nginx' with pid 76
2020-04-30 19:03:44,338 INFO spawnerr: can't find command 'scl'
2020-04-30 19:03:44,339 INFO spawnerr: can't find command 'scl'
2020-04-30 19:03:44,341 INFO spawned: 'wsbroadcast' with pid 77
2020-04-30 19:03:44,343 INFO spawnerr: can't find command 'rsyslogd'
READY
2020-04-30 19:03:45,483 INFO success: awx-config-watcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-30 19:03:45,484 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-30 19:03:45,485 INFO spawnerr: can't find command 'scl'
2020-04-30 19:03:45,486 INFO spawnerr: can't find command 'scl'
2020-04-30 19:03:45,486 INFO success: wsbroadcast entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-30 19:03:45,487 INFO spawnerr: can't find command 'rsyslogd'
2020-04-30 19:03:47,498 INFO spawnerr: can't find command 'scl'
2020-04-30 19:03:47,498 INFO spawnerr: can't find command 'scl'
2020-04-30 19:03:47,499 INFO spawnerr: can't find command 'rsyslogd'
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/run_wsbroadcast.py", line 19, in handle
    broadcast_websocket_mgr = BroadcastWebsocketManager()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/wsbroadcast.py", line 154, in __init__
    self.local_hostname = get_local_host()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/wsbroadcast.py", line 45, in get_local_host
    return Instance.objects.me().hostname
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/managers.py", line 116, in me
    raise RuntimeError("No instance found with the current cluster host id")
RuntimeError: No instance found with the current cluster host id
2020-04-30 19:03:48,225 INFO exited: wsbroadcast (exit status 1; not expected)
2020-04-30 19:03:49,228 INFO spawned: 'wsbroadcast' with pid 84
2020-04-30 19:03:50,233 INFO success: wsbroadcast entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-30 19:03:51,234 INFO spawnerr: can't find command 'scl'
2020-04-30 19:03:51,234 INFO gave up: uwsgi entered FATAL state, too many start retries too quickly
2020-04-30 19:03:51,235 INFO spawnerr: can't find command 'scl'
2020-04-30 19:03:51,235 INFO gave up: daphne entered FATAL state, too many start retries too quickly
2020-04-30 19:03:51,235 INFO spawnerr: can't find command 'rsyslogd'
2020-04-30 19:03:51,235 INFO gave up: awx-rsyslogd entered FATAL state, too many start retries too quickly
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/run_wsbroadcast.py", line 19, in handle
    broadcast_websocket_mgr = BroadcastWebsocketManager()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/wsbroadcast.py", line 154, in __init__
    self.local_hostname = get_local_host()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/wsbroadcast.py", line 45, in get_local_host
    return Instance.objects.me().hostname
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/managers.py", line 116, in me
    raise RuntimeError("No instance found with the current cluster host id")
RuntimeError: No instance found with the current cluster host id
2020-04-30 19:03:53,162 INFO exited: wsbroadcast (exit status 1; not expected)
2020-04-30 19:03:54,165 INFO spawned: 'wsbroadcast' with pid 90
2020-04-30 19:03:55,168 INFO success: wsbroadcast entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-30 19:03:57,701 WARNING  awx.main.wsbroadcast awx-85575c8fbd-vk4m8 going to add {'10.130.1.13'} to the websocket broadcast list
2020-04-30 19:03:57,706 DEBUG    awx.main.wsbroadcast awx-85575c8fbd-vk4m8 connect attempt 0 to 10.130.1.13
2020-04-30 19:04:00,725 WARNING  awx.main.wsbroadcast Failed to connect to 10.130.1.13: 'Cannot connect to host 10.130.1.13:8052 ssl:False [Connect call failed ('10.130.1.13', 8052)]'. Reconnecting ...
RESULT 2
OKREADY
2020-04-30 19:04:00,734 DEBUG    awx.main.wsbroadcast awx-85575c8fbd-vk4m8 connect attempt 1 to 10.130.1.13
2020-04-30 19:04:08,749 WARNING  awx.main.wsbroadcast Failed to connect to 10.130.1.13: 'Cannot connect to host 10.130.1.13:8052 ssl:False [Connect call failed ('10.130.1.13', 8052)]'. Reconnecting ...
2020-04-30 19:04:08,752 DEBUG    awx.main.wsbroadcast awx-85575c8fbd-vk4m8 connect attempt 2 to 10.130.1.13
2020-04-30 19:04:16,765 WARNING  awx.main.wsbroadcast Failed to connect to 10.130.1.13: 'Cannot connect to host 10.130.1.13:8052 ssl:False [Connect call failed ('10.130.1.13', 8052)]'. Reconnecting ...
2020-04-30 19:04:16,768 DEBUG    awx.main.wsbroadcast awx-85575c8fbd-vk4m8 connect attempt 3 to 10.130.1.13
2020-04-30 19:04:24,783 WARNING  awx.main.wsbroadcast Failed to connect to 10.130.1.13: 'Cannot connect to host 10.130.1.13:8052 ssl:False [Connect call failed ('10.130.1.13', 8052)]'. Reconnecting ...
2020-04-30 19:04:24,787 DEBUG    awx.main.wsbroadcast awx-85575c8fbd-vk4m8 connect attempt 4 to 10.130.1.13
2020-04-30 19:04:32,799 WARNING  awx.main.wsbroadcast Failed to connect to 10.130.1.13: 'Cannot connect to host 10.130.1.13:8052 ssl:False [Connect call failed ('10.130.1.13', 8052)]'. Reconnecting ...
2020-04-30 19:04:32,803 DEBUG    awx.main.wsbroadcast awx-85575c8fbd-vk4m8 connect attempt 5 to 10.130.1.13
2020-04-30 19:04:40,815 WARNING  awx.main.wsbroadcast Failed to connect to 10.130.1.13: 'Cannot connect to host 10.130.1.13:8052 ssl:False [Connect call failed ('10.130.1.13', 8052)]'. Reconnecting ...
2020-04-30 19:04:40,818 DEBUG    awx.main.wsbroadcast awx-85575c8fbd-vk4m8 connect attempt 6 to 10.130.1.13
2020-04-30 19:04:48,829 WARNING  awx.main.wsbroadcast Failed to connect to 10.130.1.13: 'Cannot connect to host 10.130.1.13:8052 ssl:False [Connect call failed ('10.130.1.13', 8052)]'. Reconnecting ...
2020-04-30 19:04:48,832 DEBUG    awx.main.wsbroadcast awx-85575c8fbd-vk4m8 connect attempt 7 to 10.130.1.13
2020-04-30 19:04:56,843 WARNING  awx.main.wsbroadcast Failed to connect to 10.130.1.13: 'Cannot connect to host 10.130.1.13:8052 ssl:False [Connect call failed ('10.130.1.13', 8052)]'. Reconnecting ...
2020-04-30 19:04:56,846 DEBUG    awx.main.wsbroadcast awx-85575c8fbd-vk4m8 connect attempt 8 to 10.130.1.13
RESULT 2
OKREADY
2020-04-30 19:05:04,861 WARNING  awx.main.wsbroadcast Failed to connect to 10.130.1.13: 'Cannot connect to host 10.130.1.13:8052 ssl:False [Connect call failed ('10.130.1.13', 8052)]'. Reconnecting ...
2020-04-30 19:05:04,945 DEBUG    awx.main.wsbroadcast awx-85575c8fbd-vk4m8 connect attempt 9 to 10.130.1.13
2020-04-30 19:05:07,767 WARNING  awx.main.wsbroadcast awx-85575c8fbd-vk4m8 going to remove {'10.130.1.13'} from the websocket broadcast list
2020-04-30 19:05:07,769 WARNING  awx.main.wsbroadcast awx-85575c8fbd-vk4m8 connection to 10.130.1.13 cancelled

2020-04-30 19:05:04,861 WARNING  awx.main.wsbroadcast Failed to connect to 10.130.1.13: 'Cannot connect to host 10.130.1.13:8052 ssl:False [Connect call failed ('10.130.1.13', 8052)]'. Reconnecting ...
2020-04-30 19:05:04,945 DEBUG    awx.main.wsbroadcast awx-85575c8fbd-vk4m8 connect attempt 9 to 10.130.1.13
2020-04-30 19:05:07,767 WARNING  awx.main.wsbroadcast awx-85575c8fbd-vk4m8 going to remove {'10.130.1.13'} from the websocket broadcast list
2020-04-30 19:05:07,769 WARNING  awx.main.wsbroadcast awx-85575c8fbd-vk4m8 connection to 10.130.1.13 cancelled
2020/04/30 19:05:45 [error] 78#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.129.0.1, server: _, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8050", host: "awx-web-svc-awx.tapps.oc.kohlerco.com", referrer: "https://uswix532.kohlerco.com:8443/ "
10.129.0.1 - - [30/Apr/2020:19:05:45 +0000] "GET / HTTP/1.1" 502 568 "https://uswix532.kohlerco.com:8443/ " "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36" "10.20.5.218"
RESULT 2
OKREADY
2020/04/30 19:06:41 [error] 78#0: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 10.129.0.1, server: _, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8050", host: "awx-web-svc-awx.tapps.oc.kohlerco.com", referrer: "https://uswix532.kohlerco.com:8443/ "
10.129.0.1 - - [30/Apr/2020:19:06:41 +0000] "GET / HTTP/1.1" 502 568 "https://uswix532.kohlerco.com:8443/ " "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36" "10.20.5.218"
RESULT 2

>

**Comment by wenottingham** [comment]
Your installer doesn't match your container versions.

Please see https://github.com/ansible/awx/blob/devel/INSTALL.md#clone-the-repo and follow the instructions there.
