### ISSUE TITLE
AWX cannot send mail to smtp office 365

### ISSUE THREAD

**Issue by lerminou** [ansible/awx#6947]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker
* Ansible version:  2.9
* Operating System: Centos 8
* Web Browser: any

##### STEPS TO REPRODUCE

Create a new mail notification
 check the option TLS
fill smtp.office365.com port 587 and set a username and password
   anonymous login is forbidden
try testing it

##### EXPECTED RESULTS

mail sent

##### ACTUAL RESULTS

exception in awx_task logs

##### ADDITIONAL INFORMATION

```
2020-05-06 14:21:57,746 DEBUG    awx.main.dispatch task f7190f15-aac7-4ca3-8f3b-c885f8e9a248 starting awx.main.tasks.send_notifications(*[[19]])
2020-05-06 14:21:58,019 ERROR    awx.main.tasks Send Notification Failed SMTP AUTH extension not supported by server.
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 324, in send_notifications
    sent = notification.notification_template.send(notification.subject, notification.body)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/notifications.py", line 196, in send
    return backend_obj.send_messages([notification_obj])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 70, in open
    self.connection.login(self.username, self.password)
  File "/usr/lib64/python3.6/smtplib.py", line 697, in login
    "SMTP AUTH extension not supported by server.")
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
RESULT 2
```

**Comment by beeankha** [comment]
Hi @lerminou.  Using a different SMTP server (we do not have a `smtp.office365.com` account), I could not recreate this issue.  Here are the configurations I used:
![Screenshot from 2020-05-12 13-54-03](https://user-images.githubusercontent.com/28930622/81730648-d8e45980-945b-11ea-880b-c33a7f15b96a.png)

Test notification showing as successful:
![Screen Shot 2020-05-12 at 2 03 16 PM](https://user-images.githubusercontent.com/28930622/81731038-6627ae00-945c-11ea-9750-d6b8d3bf6a48.png)

Email received:
<img width="917" alt="Screen Shot 2020-05-12 at 2 03 00 PM" src="https://user-images.githubusercontent.com/28930622/81731057-6cb62580-945c-11ea-9093-9a4a91553076.png">

AWX log output:
```
2020-05-12 17:59:35,169 DEBUG    awx.main.dispatch task 73d1352d-eb16-4eac-960b-8620d5b14184 starting awx.main.tasks.send_notifications(*[[1]])
172.18.0.1 POST /api/v2/notification_templates/31/test/ - HTTP/1.1 202
```

What _might_ be going on is that the [authenticated client SMTP submission on your Office 365 account is disabled](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission).  It is usually set to `enabled` by default, but this is worth double-checking to see if that's what is causing this particular issue, since the authentication seems to be working when I test it.

**Comment by lerminou** [comment]
thanks for you answer, unfortunately, I don't have access to my office organization parameters.
But i tried with this simple script using the same login in AWX and it works:
https://stackoverflow.com/a/56181943/4667411

**Comment by ryanpetrello** [comment]
Hey @lerminou,

We don't have an Office 365 account available to test this.  If you find any other clues or have some idea of a workaround, pull requests are welcome!
