### ISSUE TITLE
Operational Error: Deadlock detected

### ISSUE THREAD

**Issue by awithrow9** [ansible/awx#695]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
This is an old issue, ~Tower 3.0, moving this to AWX. 

##### STEPS TO REPRODUCE

Run the following integration test ...

```
tests/api/test_jobs.py::Test_Update_On_Launch::test_inventory[aws] PASSED
tests/api/test_jobs.py::Test_Update_On_Launch::test_inventory[aws] ERROR
__________________________________________________________ ERROR at teardown of Test_Update_On_Launch.test_inventory[aws] ___________________________________________________________
Traceback (most recent call last):
  File "/Users/jlaska/Projects/tower-qa.git/tests/lib/common/api/pages/base.py", line 162, in delete
    return self.handle_request(r)
  File "/Users/jlaska/Projects/tower-qa.git/tests/lib/common/api/pages/base.py", line 132, in handle_request
    raise common.exceptions.InternalServerError_Exception(exc_str, data)
InternalServerError_Exception: ('Internal Server Error (500) received', {})
```

##### ACTUAL RESULTS

```
2015-06-20 13:54:42,853 ERROR    django.request Internal Server Error: /api/v1/groups/3631/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/lib/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python2.7/site-packages/awx/lib/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/lib/site-packages/rest_framework/generics.py", line 497, in delete
    return self.destroy(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/views.py", line 1399, in destroy
  File "/usr/lib64/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/models/inventory.py", line 593, in mark_inactive_recursive
  File "/usr/lib/python2.7/site-packages/awx/main/models/inventory.py", line 586, in mark_actual
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 493, in update
    rows = query.get_compiler(self.db).execute_sql(None)
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 980, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib64/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib64/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib64/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
OperationalError: deadlock detected
DETAIL:  Process 24823 waits for ShareLock on transaction 46387; blocked by process 29587.
Process 29587 waits for ShareLock on transaction 46453; blocked by process 24823.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (305,4) in relation "main_host"
```

##### ADDITIONAL INFORMATION

Postgres log:

```
< 2015-06-20 17:54:42.851 UTC >ERROR:  deadlock detected
< 2015-06-20 17:54:42.851 UTC >DETAIL:  Process 24823 waits for ShareLock on transaction 46387; blocked by process 29587.
        Process 29587 waits for ShareLock on transaction 46453; blocked by process 24823.
        Process 24823: UPDATE "main_host" SET "active" = false WHERE "main_host"."id" IN (4554, 4546, 4544, 4541, 4540, 4532, 4527, 4519, 4503, 4502, 4501, 4556, 4531, 4548, 4536, 4530, 4537, 4542, 4529, 4525, 4552, 4533, 4555, 4553, 4551, 4550, 4549, 4547, 4545, 4538, 4535, 4528, 4526, 4524, 4523, 4522, 4521, 4520, 4517, 4513, 4512, 4511, 4510, 4509, 4508, 4507, 4506, 4505, 4504, 4539, 4518, 4534, 4514, 4543, 4516, 4515)
        Process 29587: UPDATE "main_group" SET "modified" = '2015-06-20 17:54:41.875553+00:00', "modified_by_id" = NULL, "has_active_failures" = true, "hosts_with_active_failures" = 4 WHERE "main_group"."id" = 3632
< 2015-06-20 17:54:42.851 UTC >HINT:  See server log for query details.
< 2015-06-20 17:54:42.851 UTC >CONTEXT:  while updating tuple (305,4) in relation "main_host"
< 2015-06-20 17:54:42.851 UTC >STATEMENT:  UPDATE "main_host" SET "active" = false WHERE "main_host"."id" IN (4554, 4546, 4544, 4541, 4540, 4532, 4527, 4519, 4503, 4502, 4501, 4556, 4531, 4548, 4536, 4530, 4537, 4542, 4529, 4525, 4552, 4533, 4555, 4553, 4551, 4550, 4549, 4547, 4545, 4538, 4535, 4528, 4526, 4524, 4523, 4522, 4521, 4520, 4517, 4513, 4512, 4511, 4510, 4509, 4508, 4507, 4506, 4505, 4504, 4539, 4518, 4534, 4514, 4543, 4516, 4515)
```

"Assuming I'm understanding correctly, this error happens because a DELETE request is issued while asynchronous work (calculated fields or cascade deletion)? Is there a way I can instrument integration to detect and wait for any asynchronous processing to complete?"

**Comment by AlanCoding** [comment]
I would wager that this was resolved by https://github.com/ansible/awx/pull/3529

**Comment by ryanpetrello** [comment]
Agreed.  Closing this unless we see reports of it again.
