### ISSUE TITLE
UI - 500 error on Recent Job Runs

### ISSUE THREAD

**Issue by YakShavingCatHerder** [ansible/awx#6982]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Clicking on any job from `Recent Job Runs` returns a 500 

##### ENVIRONMENT
* AWX version: `10.0.0`, `11.0.0`, `11.1.0`, `11.2.0`
* AWX install method: `docker on linux`
* Ansible version:  `2.9.7`
* Operating System: `Ubuntu 18.04`
* Web Browser: `Chrome 81.0.4044.138 (Official Build) (64-bit)`

##### STEPS TO REPRODUCE
- Fresh install via README method
- Connect to server via UI
- Run Demo template
- Return to Dashboard
- Click on any run lister under `Recent Run Jobs`

##### EXPECTED RESULTS
Loopback to Run output

##### ACTUAL RESULTS
500 pop-up error, show below
<img width="1792" alt="Screen Shot 2020-05-11 at 12 35 49 AM" src="https://user-images.githubusercontent.com/30486892/81524486-60787e00-931f-11ea-9ad3-c65db16e329c.png">

##### ADDITIONAL INFORMATION
`docker logs -f {{ awx_web }}`:
```173.42.42.42 - - [11/May/2020:04:25:22 +0000] "OPTIONS /api/v2/unified_jobs/ HTTP/1.1" 200 10718 "http://18.218.149.92/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "-"
[pid: 91|app: 0|req: 9/29] 173.42.42.42 () {48 vars in 2365 bytes} [Mon May 11 04:25:22 2020] OPTIONS /api/v2/unified_jobs/ => generated 10718 bytes in 86 msecs (HTTP/1.1 200) 12 headers in 454 bytes (1 switches on core 0)
[pid: 90|app: 0|req: 7/30] 173.42.42.42 () {48 vars in 2464 bytes} [Mon May 11 04:25:22 2020] GET /api/v2/unified_jobs/?page_size=20&order_by=-finished&not__launch_type=sync => generated 13685 bytes in 195 msecs (HTTP/1.1 200) 10 headers in 289 bytes (1 switches on core 0)
173.42.42.42 - - [11/May/2020:04:25:23 +0000] "GET /api/v2/unified_jobs/?page_size=20&order_by=-finished&not__launch_type=sync HTTP/1.1" 200 13685 "http://18.218.149.92/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "-"
2020-05-11 04:25:23,354 ERROR    django.request Internal Server Error: /api/v2/jobs/7/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/generics.py", line 304, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/generics.py", line 208, in get
    return self.retrieve(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/serializers.py", line 562, in data
    ret = super().data
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/serializers.py", line 3013, in to_representation
    ret = super(JobSerializer, self).to_representation(obj)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/serializers.py", line 802, in to_representation
    ret = super(UnifiedJobSerializer, self).to_representation(obj)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/serializers.py", line 2774, in to_representation
    ret = super(JobOptionsSerializer, self).to_representation(obj)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/serializers.py", line 529, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/fields.py", line 1905, in to_representation
    return method(value)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/serializers.py", line 3069, in get_host_status_counts
    counts = obj.job_events.only('event_data').get(event='playbook_on_stats').get_host_status_counts()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 412, in get
    (self.model._meta.object_name, num)
awx.main.models.events.JobEvent.MultipleObjectsReturned: get() returned more than one JobEvent -- it returned 3!
2020-05-11 04:25:23,354 ERROR    django.request Internal Server Error: /api/v2/jobs/7/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/generics.py", line 304, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/generics.py", line 208, in get
    return self.retrieve(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/serializers.py", line 562, in data
    ret = super().data
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/serializers.py", line 3013, in to_representation
    ret = super(JobSerializer, self).to_representation(obj)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/serializers.py", line 802, in to_representation
    ret = super(UnifiedJobSerializer, self).to_representation(obj)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/serializers.py", line 2774, in to_representation
    ret = super(JobOptionsSerializer, self).to_representation(obj)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/serializers.py", line 529, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/fields.py", line 1905, in to_representation
    return method(value)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/serializers.py", line 3069, in get_host_status_counts
    counts = obj.job_events.only('event_data').get(event='playbook_on_stats').get_host_status_counts()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 412, in get
    (self.model._meta.object_name, num)
awx.main.models.events.JobEvent.MultipleObjectsReturned: get() returned more than one JobEvent -- it returned 3!
[pid: 91|app: 0|req: 10/31] 173.42.42.42 () {46 vars in 2314 bytes} [Mon May 11 04:25:23 2020] GET /api/v2/jobs/7/ => generated 41 bytes in 160 msecs (HTTP/1.1 500) 6 headers in 208 bytes (1 switches on core 0)
173.42.42.42 - - [11/May/2020:04:25:23 +0000] "GET /api/v2/jobs/7/ HTTP/1.1" 500 41 "http://18.218.149.92/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "-"
[pid: 92|app: 0|req: 7/32] 173.42.42.42 () {46 vars in 2417 bytes} [Mon May 11 04:25:23 2020] GET /api/v2/jobs/7/job_events/?order_by=-start_line&page=1&page_size=50 => generated 77314 bytes in 163 msecs (HTTP/1.1 200) 13 headers in 477 bytes (1 switches on core 0)
173.42.42.42 - - [11/May/2020:04:25:23 +0000] "GET /api/v2/jobs/7/job_events/?order_by=-start_line&page=1&page_size=50 HTTP/1.1" 200 77314 "http://18.218.149.92/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "-"
173.42.42.42 - - [11/May/2020:04:25:23 +0000] "OPTIONS /api/v2/jobs/7/ HTTP/1.1" 200 11857 "http://18.218.149.92/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "-"
[pid: 88|app: 0|req: 5/33] 173.42.42.42 () {48 vars in 2353 bytes} [Mon May 11 04:25:23 2020] OPTIONS /api/v2/jobs/7/ => generated 11857 bytes in 183 msecs (HTTP/1.1 200) 12 headers in 462 bytes (1 switches on core 0)
[pid: 90|app: 0|req: 8/34] 173.42.42.42 () {48 vars in 2426 bytes} [Mon May 11 04:25:23 2020] GET /api/v2/dashboard/graphs/jobs/?period=month&job_type=all => generated 1090 bytes in 61 msecs (HTTP/1.1 200) 10 headers in 288 bytes (1 switches on core 0)
173.42.42.42 - - [11/May/2020:04:25:23 +0000] "GET /api/v2/dashboard/graphs/jobs/?period=month&job_type=all HTTP/1.1" 200 1090 "http://18.218.149.92/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "-"
[pid: 89|app: 0|req: 5/35] 173.42.42.42 () {48 vars in 2578 bytes} [Mon May 11 04:25:23 2020] GET /api/v2/unified_job_templates/?order_by=-last_job_run&page_size=5&last_job_run__isnull=false&type=workflow_job_template,job_template => generated 52 bytes in 113 msecs (HTTP/1.1 200) 10 headers in 286 bytes (1 switches on core 0)
173.42.42.42 - - [11/May/2020:04:25:23 +0000] "GET /api/v2/unified_job_templates/?order_by=-last_job_run&page_size=5&last_job_run__isnull=false&type=workflow_job_template,job_template HTTP/1.1" 200 52 "http://18.218.149.92/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "-"
[pid: 91|app: 0|req: 11/36] 173.42.42.42 () {48 vars in 2351 bytes} [Mon May 11 04:25:23 2020] GET /api/v2/dashboard/ => generated 1408 bytes in 141 msecs (HTTP/1.1 200) 11 headers in 383 bytes (1 switches on core 0)
173.42.42.42 - - [11/May/2020:04:25:23 +0000] "GET /api/v2/dashboard/ HTTP/1.1" 200 1408 "http://18.218.149.92/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "-"
173.42.42.42 - - [11/May/2020:04:25:23 +0000] "GET /api/v2/unified_jobs/?order_by=-finished&page_size=5&finished__isnull=false&type=workflow_job,job&count_disabled=1 HTTP/1.1" 200 6018 "http://18.218.149.92/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "-"
[pid: 88|app: 0|req: 6/37] 173.42.42.42 () {48 vars in 2542 bytes} [Mon May 11 04:25:23 2020] GET /api/v2/unified_jobs/?order_by=-finished&page_size=5&finished__isnull=false&type=workflow_job,job&count_disabled=1 => generated 6018 bytes in 185 msecs (HTTP/1.1 200) 10 headers in 288 bytes (1 switches on core 0)
[pid: 92|app: 0|req: 8/38] 173.42.42.42 () {54 vars in 2492 bytes} [Mon May 11 04:25:23 2020] OPTIONS /api/v2/job_templates/ => generated 23317 bytes in 184 msecs (HTTP/1.1 200) 10 headers in 295 bytes (1 switches on core 0)
173.42.42.42 - - [11/May/2020:04:25:23 +0000] "OPTIONS /api/v2/job_templates/ HTTP/1.1" 200 23317 "http://18.218.149.92/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "-"
[pid: 91|app: 0|req: 12/39] 10.0.11.140 () {36 vars in 425 bytes} [Mon May 11 04:25:35 2020] GET / => generated 11460 bytes in 75 msecs (HTTP/1.1 200) 5 headers in 169 bytes (1 switches on core 0)
10.0.11.140 - - [11/May/2020:04:25:36 +0000] "GET / HTTP/1.1" 200 11460 "-" "ELB-HealthChecker/2.0" "-"
[pid: 92|app: 0|req: 9/40] 10.0.10.204 () {36 vars in 425 bytes} [Mon May 11 04:25:36 2020] GET / => generated 11460 bytes in 38 msecs (HTTP/1.1 200) 5 headers in 169 bytes (1 switches on core 0)
10.0.10.204 - - [11/May/2020:04:25:36 +0000] "GET / HTTP/1.1" 200 11460 "-" "ELB-HealthChecker/2.0" "-"```

**Comment by andy812** [comment]
I've got the same error. I think, i found some problems in database. My job id is 145:
`select * from main_jobevent where job_id=145 and event='playbook_on_start';`
2 records in result.  Is it ok? I don't think so. 1 job = 1 start event.
In this table we can see the column "playbook".
`select * from main_jobtemplate;`
I've got 2 resords with the same playbook (because i use 2 inventories). Maybe that’s the reason.

@YakShavingCatHerder could you show the results of queries above?

**Comment by ryanpetrello** [comment]
`select * from main_jobevent where job_id=145 and event='playbook_on_start';`

I'm not sure what would cause you to have _duplicate_ `playbook_on_start` events here, but the reason you're encountering 500 errors is because you've got bad data (and will have to clean it up).

**Comment by YakShavingCatHerder** [comment]
Confirmed this was bad data; thanks for the help guys!

**Comment by therealrobopablo** [comment]
Hi I just ran into this issue, seeing to stem from API calls. How did you clean the data?

**Comment by therealrobopablo** [comment]
> Confirmed this was bad data; thanks for the help guys!

How did you clean up the data?

**Comment by ryanpetrello** [comment]
If anyone else here is still encountering this, we're tracking this in one place to avoid duplicates (and I'm looking for volunteers to help me figure out what's up):

#7253
