### ISSUE TITLE
Errors due to having % characters in password in config file

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#7002]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Some config files seems to cause the tower modules to error. Exact details still not completely uncelar.

##### STEPS TO REPRODUCE

Seems to be specific to installing Ansible in a python3 / RHEL8 environment from pip. It looks like it happens when using the config file without the `[general]` header.

##### EXPECTED RESULTS

Parses config file.

##### ACTUAL RESULTS

get traceback

```
Traceback (most recent call last):
  File "/tmp/ansible_tower_organization_payload_3v6k9sri/ansible_tower_organization_payload.zip/ansible_collections/awx/awx/plugins/module_utils/tower_api.py", line 147, in load_config
  File "/var/lib/awx/venv/python3_tower_modules/lib/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/var/lib/awx/venv/python3_tower_modules/lib/python3.6/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/var/lib/awx/venv/python3_tower_modules/lib/python3.6/site-packages/yaml/composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/var/lib/awx/venv/python3_tower_modules/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/var/lib/awx/venv/python3_tower_modules/lib/python3.6/site-packages/yaml/parser.py", line 174, in parse_document_start
    self.peek_token().start_mark)
yaml.parser.ParserError: expected '<document start>', but found '<scalar>'
  in "<unicode string>", line 2, column 1:
    host = https://ec2-18-206-224-12 ... 
    ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ansible_tower_organization_payload_3v6k9sri/ansible_tower_organization_payload.zip/ansible_collections/awx/awx/plugins/module_utils/tower_api.py", line 172, in load_config
  File "/usr/lib64/python3.6/configparser.py", line 800, in get
    d)
  File "/usr/lib64/python3.6/configparser.py", line 394, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib64/python3.6/configparser.py", line 444, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '<redacted, password with % in it>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ansible_tower_organization_payload_3v6k9sri/ansible_tower_organization_payload.zip/ansible_collections/awx/awx/plugins/module_utils/tower_api.py", line 111, in load_config_files
  File "/tmp/ansible_tower_organization_payload_3v6k9sri/ansible_tower_organization_payload.zip/ansible_collections/awx/awx/plugins/module_utils/tower_api.py", line 177, in load_config
ansible_collections.awx.awx.plugins.module_utils.tower_api.ConfigFileException: An unknown exception occured trying to ini load config file: '%' must be followed by '%' or '(', found: '%viG5v#MS]<r2HQ'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1589300028.911883-31299-24841853381059/AnsiballZ_tower_organization.py", line 116, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1589300028.911883-31299-24841853381059/AnsiballZ_tower_organization.py", line 108, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1589300028.911883-31299-24841853381059/AnsiballZ_tower_organization.py", line 54, in invoke_module
    runpy.run_module(mod_name='ansible_collections.awx.awx.plugins.modules.tower_organization', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_tower_organization_payload_3v6k9sri/ansible_tower_organization_payload.zip/ansible_collections/awx/awx/plugins/modules/tower_organization.py", line 129, in <module>
  File "/tmp/ansible_tower_organization_payload_3v6k9sri/ansible_tower_organization_payload.zip/ansible_collections/awx/awx/plugins/modules/tower_organization.py", line 94, in main
  File "/tmp/ansible_tower_organization_payload_3v6k9sri/ansible_tower_organization_payload.zip/ansible_collections/awx/awx/plugins/module_utils/tower_api.py", line 65, in __init__
  File "/tmp/ansible_tower_organization_payload_3v6k9sri/ansible_tower_organization_payload.zip/ansible_collections/awx/awx/plugins/module_utils/tower_api.py", line 113, in load_config_files
TypeError: fail_json() takes 1 positional argument but 2 were given
```

##### ADDITIONAL INFORMATION

Looks like the call pattern is incorrect here:

https://github.com/ansible/awx/blob/c3afe3f815b4be870ac71cea4bbb45cb01c11401/awx_collection/plugins/module_utils/tower_api.py#L113

That's not the _only_ problem here.

This is related to https://github.com/ansible/awx/issues/6983 in some ways, but not completely the same.

Also note:

```
>>> isinstance(yaml.parser.ParserError, yaml.YAMLError)
False
```

So where we catch the yaml error (which is already problematic), we don't catch all yaml errors.

**Comment by AlanCoding** [comment]
I don't seem to be able to replicate this anymore, but need to give it a better shot

**Comment by AlanCoding** [comment]
Could be that we need a `raw=True` option when it's loaded

https://github.com/ansible/awx/blob/5445a3b5673b3c5bce005ae91c0b6ca2f60963c1/awx_collection/plugins/module_utils/tower_api.py#L213
