### ISSUE TITLE
CloudForms inventory import fails with django.core.exceptions.ValidationError

### ISSUE THREAD

**Issue by rbywater** [ansible/awx#705]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

CloudForms inventory import fails with django.core.exceptions.ValidationError. Have tried with both a "normal" Cloudforms user credential and an "admin" one but same result both times.

##### ENVIRONMENT
* AWX version: 1.0.1.225 
* AWX install method: docker for mac
* Ansible version:  2.4.1
* Operating System: MacOS 10.12.6
* Web Browser: Chrome 62
* Cloudforms: 4.2 (Management engine Version 5.7.3.2.20170621144854_6c833cc)

##### STEPS TO REPRODUCE

1. Create new inventory source with source type of Red Hat Cloudforms
2. Run sync

##### EXPECTED RESULTS

* Inventory import successfully completes.

##### ACTUAL RESULTS

* Inventory import fails with "django.core.exceptions.ValidationError: [u\"'<object object at 0x7830fe0>' value must be either True or False.\"]" error

##### ADDITIONAL INFORMATION

Log file:
```
2017-11-23 01:44:04,433 INFO     awx.main.commands.inventory_import Updating inventory 2: CF
2017-11-23 01:44:04,472 INFO     awx.main.commands.inventory_import Reading Ansible inventory source: /usr/lib/python2.7/site-packages/awx/plugins/inventory/cloudforms.py
2017-11-23 01:44:34,698 INFO     awx.main.commands.inventory_import Processing JSON output...
2017-11-23 01:44:34,720 INFO     awx.main.commands.inventory_import Loaded 322 groups, 266 hosts
...
2017-11-23 01:44:34,739 WARNING  awx.main.commands.inventory_import Host \"<redacted1>\" has no \"id\" variable
2017-11-23 01:44:34,739 WARNING  awx.main.commands.inventory_import Host \"<redacted2>\" has no \"id\" variable
2017-11-23 01:44:34,739 WARNING  awx.main.commands.inventory_import Host \"<redacted3>\" has no \"id\" variable
...
2017-11-23 01:44:38,254 INFO     awx.main.commands.inventory_import Group \"<redacted4>_ovf\" added
2017-11-23 01:44:38,261 INFO     awx.main.commands.inventory_import Group \"<redacted5>_ovf\" added
2017-11-23 01:44:38,269 INFO     awx.main.commands.inventory_import Group \"location\" added
2017-11-23 01:44:38,276 INFO     awx.main.commands.inventory_import Group \"redhat\" added
2017-11-23 01:44:38,283 INFO     awx.main.commands.inventory_import Group \"tags\" added
2017-11-23 01:44:38,290 INFO     awx.main.commands.inventory_import Group \"type\" added
2017-11-23 01:44:38,298 INFO     awx.main.commands.inventory_import Group \"vendor\" added
Traceback (most recent call last):
  File \"/usr/bin/awx-manage\", line 9, in <module>
    load_entry_point('awx==1.0.1.225', 'console_scripts', 'awx-manage')()
  File \"/usr/lib/python2.7/site-packages/awx/__init__.py\", line 109, in manage
    execute_from_command_line(sys.argv)
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py\", line 364, in execute_from_command_line
    utility.execute()
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py\", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py\", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py\", line 330, in execute
    output = self.handle(*args, **options)
  File \"/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py\", line 1020, in handle
    self.load_into_database()
  File \"/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py\", line 892, in load_into_database
    self._create_update_hosts()
  File \"/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py\", line 798, in _create_update_hosts
    db_host = self.inventory.hosts.update_or_create(name=mem_host_name, defaults=host_attrs)[0]
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py\", line 665, in update_or_create
    return super(RelatedManager, self.db_manager(db)).update_or_create(**kwargs)
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/manager.py\", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py\", line 482, in update_or_create
    obj, created = self._create_object_from_params(lookup, params)
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py\", line 498, in _create_object_from_params
    obj = self.create(**params)
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py\", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File \"/usr/lib/python2.7/site-packages/awx/main/models/inventory.py\", line 665, in save
    super(Host, self).save(*args, **kwargs)
  File \"/usr/lib/python2.7/site-packages/awx/main/models/base.py\", line 264, in save
    super(PrimordialModel, self).save(*args, **kwargs)
  File \"/usr/lib/python2.7/site-packages/awx/main/models/base.py\", line 159, in save
    super(CreatedModifiedModel, self).save(*args, **kwargs)
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/base.py\", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/base.py\", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/base.py\", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/base.py\", line 963, in _do_insert
    using=using, raw=raw)
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/manager.py\", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py\", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py\", line 1106, in execute_sql
    for sql, params in self.as_sql():
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py\", line 1059, in as_sql
    for obj in self.query.objs
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py\", line 998, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/fields/__init__.py\", line 770, in get_db_prep_save
    prepared=False)
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/fields/__init__.py\", line 762, in get_db_prep_value
    value = self.get_prep_value(value)
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/fields/__init__.py\", line 1043, in get_prep_value
    return self.to_python(value)
  File \"/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/fields/__init__.py\", line 1036, in to_python
    params={'value': value},
django.core.exceptions.ValidationError: [u\"'<object object at 0x6aa0f40>' value must be either True or False.\"]
```

**Comment by imoes** [comment]
it seems that it is a performance problem with the database (Timeout).
For a local SSD, it looks like to work. In an external database, it works only partially.

**Comment by imoes** [comment]
same issue with OpenStack.py:
Traceback (most recent call last): File "/usr/bin/awx-manage", line 9, in <module> load_entry_point('awx==1.0.1.229', 'console_scripts', 'awx-manage')() File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage execute_from_command_line(sys.argv) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line utility.execute() File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute self.fetch_command(subcommand).run_from_argv(self.argv) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv self.execute(*args, **cmd_options) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute output = self.handle(*args, **options) File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 1020, in handle self.load_into_database() File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 892, in load_into_database self._create_update_hosts() File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 798, in _create_update_hosts db_host = self.inventory.hosts.update_or_create(name=mem_host_name, defaults=host_attrs)[0] File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 665, in update_or_create return super(RelatedManager, self.db_manager(db)).update_or_create(**kwargs) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method return getattr(self.get_queryset(), name)(*args, **kwargs) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 482, in update_or_create obj, created = self._create_object_from_params(lookup, params) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 498, in _create_object_from_params obj = self.create(**params) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 394, in create obj.save(force_insert=True, using=self.db) File "/usr/lib/python2.7/site-packages/awx/main/models/inventory.py", line 665, in save super(Host, self).save(*args, **kwargs) File "/usr/lib/python2.7/site-packages/awx/main/models/base.py", line 264, in save super(PrimordialModel, self).save(*args, **kwargs) File "/usr/lib/python2.7/site-packages/awx/main/models/base.py", line 159, in save super(CreatedModifiedModel, self).save(*args, **kwargs) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save force_update=force_update, update_fields=update_fields) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/base.py", line 924, in _save_table result = self._do_insert(cls._base_manager, using, fields, update_pk, raw) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/base.py", line 963, in _do_insert using=using, raw=raw) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method return getattr(self.get_queryset(), name)(*args, **kwargs) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 1076, in _insert return query.get_compiler(using=using).execute_sql(return_id) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1106, in execute_sql for sql, params in self.as_sql(): File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1059, in as_sql for obj in self.query.objs File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 998, in prepare_value value = field.get_db_prep_save(value, connection=self.connection) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 770, in get_db_prep_save prepared=False) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 762, in get_db_prep_value value = self.get_prep_value(value) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1043, in get_prep_value return self.to_python(value) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1036, in to_python params={'value': value}, django.core.exceptions.ValidationError: [u"'<object object at 0x5fbce40>' value must be either True or False."]

**Comment by AlanCoding** [comment]
https://github.com/django/django/blob/stable/1.11.x/django/db/models/fields/__init__.py#L1036

My first glance at this would suggest to me that we just put a value in `params` for a boolean field that was really an object. (problem is, I don't know which field yet)

Is there any good reason to suspect this is related to the drive performance? I can't see how this would be connected to timing issues.

**Comment by AlanCoding** [comment]
Speculatively, I can make a good guess as to where this came from.

first call: https://github.com/ansible/awx/blob/33ff10728dbe5c2ddfac8dcc62bd07566acd9b00/awx/main/management/commands/inventory_import.py#L798

but this is where I suspect the trouble might be caused:

https://github.com/ansible/awx/blob/33ff10728dbe5c2ddfac8dcc62bd07566acd9b00/awx/main/management/commands/inventory_import.py#L337-L341

`_get_enabled` looks like it can return `object()`. This will be passed as the value for the `enabled` field. That matches with the Django error given.

**Comment by rbywater** [comment]
That seems to fit with what I'm seeing. @AlanCoding is there any workaround in the config that could potentially make it work or am I pretty much stuck until a code change can be identified and released?

**Comment by AlanCoding** [comment]
You might be able to workaround this by nulling-out or deleting the *_ENABLED_VAR in settings for the particular inventory source your using. For cloudforms:

https://github.com/ansible/awx/blob/33ff10728dbe5c2ddfac8dcc62bd07566acd9b00/awx/settings/defaults.py#L837

If there's nothing in that variable, then it shouldn't do anything in the loop which problematically sets `enabled` to an object.

But of course AWX should get a fix in code soon. I'm chewing on how difficult it would be to replicate the bug in a unit test.

**Comment by switchboardOp** [comment]
Having the same issue using these versions:

    AWX version: 1.0.1.231
    AWX install method: docker for CentOS
    Ansible version: 2.4.1
    Cloudforms: 4.5 (Management engine Version 5.8.0.17.20170525183055_6317a22)

The changes to inventory_import.py in #731 fixed the issue for me.

**Comment by rbywater** [comment]
I made a temporary change to the code to match what was in the PR and this made it stop falling over but the default (False in the case of the current PR) was always used rather than the value coming out of Cloudforms. 

Investigating further it appears that the underlying cause of this issue is actually that the CLOUDFORMS_ENABLED_VAR and CLOUDFORMS_INSTANCE_ID_VAR are wrong and should be `cloudforms.power_state` and `cloudforms.id`. 

https://github.com/ansible/awx/blob/33ff10728dbe5c2ddfac8dcc62bd07566acd9b00/awx/settings/defaults.py#L837-L842

I've changed them locally and enable/disabled appears to be coming through properly now. Can this be fixed as part of this issue or does it need to be a separate one?

**Comment by AlanCoding** [comment]
> Investigating further it appears that the underlying cause of this issue is actually that the CLOUDFORMS_ENABLED_VAR and CLOUDFORMS_INSTANCE_ID_VAR are wrong and should be `cloudforms.power_state` and `cloudforms.id`.

Sounds like a good find there. Best approach is to make a PR with that change and link to this issue.

I tried to verify this change by looking at the dynamic inventory script for cloudforms:

https://github.com/ansible/ansible/blob/devel/contrib/inventory/cloudforms.py

But it looks like that won't have the answer. `_get_hosts` works by doing a request to the cloudforms server, so the data structure is dictated by what it gives.

It is concerning however, that the script, itself, seems to make the wrong assumption about power_state in `if host['power_state'] != 'on':`. It could be that the script there needs updating too.

**Comment by AlanCoding** [comment]
Notes for verification:

Two distinct things went wrong here that should both need to be checked.

 - the enabled_var was not working with the dot notation (like `cloudforms.power_state`)
 - cloudforms changed its enabled variable
