### ISSUE TITLE
Deploying multiple instances of AWX

### ISSUE THREAD

**Issue by idH64** [ansible/awx#7054]
##### ISSUE TYPE

 - Bug Report/Assistance

##### COMPONENT NAME

 - Installer

##### SUMMARY

Hello, I'm trying to set up a multi instance deployment of AWX. I've got two Centos8 hosts for AWX (I know the recommendation is 3 boxes) and a pair of Centos 8 boxes running Postgres12 in streaming replication.

The two AWX boxes have all the required software and modules installed and if I deploy them as stand alone deployments with all the defaults they just work as expected, however when I attempt to deploy them as connected instances I get into all sorts of trouble.

Deploying to the external database was easy and works (even with them running as stand alone boxes). The problem comes down to the AWX boxes. My assumption would be that they need to be distinct from one another so I change the following fields in the inventory file

```
awx_task_hostname
awx_web_hostname
```

The installer runs without issues and deploys the containers as expected, the web interface works, I can see the new instance in the instance group and everything appears to be fine, however the dispatcher doesn't fire, so for example if I attempt to delete the default inventory it gets stuck pending deletion (note that this also happens on a local sql deployment as well), looking at the debug logs I can see the following:

```
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/run_dispatcher.py", line 55, in handle
    reaper.reap()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/dispatch/reaper.py", line 38, in reap
    (changed, me) = Instance.objects.get_or_register()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/managers.py", line 155, in get_or_register
    return (False, self.me())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/managers.py", line 116, in me
    raise RuntimeError("No instance found with the current cluster host id")
RuntimeError: No instance found with the current cluster host id
```

When I go into the task container and inspect /etc/tower/settings.py I can see that CLUSTER_HOST_ID is set to AWX, so presumably this is hard coded into the docker container (If so, why offer the functionality to change the task name in the inventory file).

If I manually change this and then restart the container, the run time error goes away but the dispatcher still fails to run. I've had a very good Google and haven't been able to find anything helpful, so was just looking for a bit of assistance please.

##### ENVIRONMENT
* AWX version: 11.2
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: Centos8
* Web Browser: Chromium

##### STEPS TO REPRODUCE

1. Rename awx_task_hostname and awx_web_hostname in the inventory file
2. Run the installer

##### EXPECTED RESULTS

A new delpoyment with a unique name

##### ACTUAL RESULTS

RuntimeError: No instance found with the current cluster host id

**Comment by wenottingham** [comment]
What you're suggesting won't work. The only way to scale containerized AWX is in a container platform such as Kubernetes or OpenShift... you can't just deploy local docker on multiple hosts.

This repo is for bugs in AWX itself; for things like this you're best off asking on the mailing list or IRC channel: https://github.com/ansible/awx#get-involved
