### ISSUE TITLE
Better inventory errors

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#7067]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
See an example in #7052 
An inventory update failed, producing the following output:
```
Traceback (most recent call last):
File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in
sys.exit(manage())
File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/init.py", line 152, in manage
execute_from_command_line(sys.argv)
File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/init.py", line 381, in execute_from_command_line
utility.execute()
File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/init.py", line 375, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
self.execute(*args, **cmd_options)
File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
output = self.handle(*args, **options)
File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1139, in handle
raise exc
File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1029, in handle
venv_path=venv_path, verbosity=self.verbosity).load()
File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 215, in load
return self.command_to_json(base_args + ['--list'])
File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 198, in command_to_json
self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.9.7
config file = /etc/ansible/ansible.cfg
configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.6/site-packages/ansible
executable location = /usr/bin/ansible-inventory
python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
Using /etc/ansible/ansible.cfg as config file
[WARNING]: * Failed to parse /tmp/awx_1072_i0i4h5_1/vmware_vm_inventory.yml
with auto plugin: Invalid empty host name provided: None
File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
plugin.parse(self._inventory, self._loader, source, cache=cache)
File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/auto.py", line 58, in parse
plugin.parse(inventory, loader, path, cache=cache)
File "/var/lib/awx/vendor/inventory_collections/ansible_collections/community/vmware/plugins/inventory/vmware_vm_inventory.py", line 606, in parse
cacheable_results = self._populate_from_source()
File "/var/lib/awx/vendor/inventory_collections/ansible_collections/community/vmware/plugins/inventory/vmware_vm_inventory.py", line 689, in _populate_from_source
self._populate_host_properties(host_properties, host)
File "/var/lib/awx/vendor/inventory_collections/ansible_collections/community/vmware/plugins/inventory/vmware_vm_inventory.py", line 720, in _populate_host_properties
self.inventory.add_host(host)
File "/usr/lib/python3.6/site-packages/ansible/inventory/data.py", line 230, in add_host
raise AnsibleError("Invalid empty host name provided: %s" % host)
[WARNING]: Unable to parse /tmp/awx_1072_i0i4h5_1/vmware_vm_inventory.yml as an
inventory source
ERROR! No inventory was parsed, please check your configuration and options.
```

Every part of that error before:
```
[WARNING]: * Failed to parse /tmp/awx_1072_i0i4h5_1/vmware_vm_inventory.yml
with auto plugin: Invalid empty host name provided: None
```

could be elided without losing context.

This may require ansible changes.

**Comment by AlanCoding** [comment]
What if you reduce the verbosity on the inventory source?

**Comment by lgrullon-gilead** [comment]
> What if you reduce the verbosity on the inventory source?

Hi AlanCoding,
This one is impacting many of us trying to sync the vcenter inventory...I know wenottingham mentioned the vmware script is out the window and the plugin system is more supported on this scope. If possible, can you please provide guidance on how to get the inventory sync from vcenter.

I have opened this issue in the following thread: https://github.com/ansible/awx/issues/7052

**Comment by coreydeli** [comment]
Issue persists in 19.5.0

**Comment by AlanCoding** [comment]
FWIW, recent changes did make the inventory errors _more_ brief. We have gotten rid of the "/var/lib/awx/venv/awx/bin/awx-manage" related traceback.

To reduce the rest of the errors, we could 

1. narrow down the plugins used or
2. just have some general Ansible core improvement

The option (1) requires changing the plugins which are enabled. We do this when we can, but otherwise, the user has to somehow do that because we can not decipher intention. The server can't know if a yaml file is Ansible yaml inventory or something for the "auto" inventory plugin. The (2) option means we can just close this and file it in the Ansible core issue tracker.
