### ISSUE TITLE
Job events gone after upgrade to 11.2.0

### ISSUE THREAD

**Issue by anxstj** [ansible/awx#7095]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

After upgrade from 9.3.0 to 11.2.0, all job events are deleted. The jobs itself are listed, but there is no output shown.

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: docker
* Ansible version:  2.9.7
* Operating System: Debian 9
* Web Browser: Firefox 76

##### STEPS TO REPRODUCE

* Have a running 9.3.0 AWX running
* `git fetch`
* `git merge 11.2.0`
* `ansible-playbook -i inventory install.yml`

##### EXPECTED RESULTS

The events of jobs created with 9.3.0 should still be visible in the UI

##### ACTUAL RESULTS

The jobs created with 9.3.0 show an empty event list.

##### ADDITIONAL INFORMATION

GET /api/v2/jobs/43440/stdout/
```
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: text/plain ;utf-8
Vary: Accept
X-API-Node: awx
X-API-Product-Name: AWX
X-API-Product-Version: 11.2.0
X-API-Time: 0.284s

```

GET /api/v2/jobs/43440/job_events/
```
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
X-API-Node: awx
X-API-Product-Name: AWX
X-API-Product-Version: 11.2.0
X-API-Time: 0.394s
X-UI-Max-Events: 4000

{
    "count": 0,
    "next": null,
    "previous": null,
    "results": []
}

```

I also took a look into the database and a `select * from main_jobevent where job_id = 43440;` was empty, too.

Then I checked the cleanup job inside AWX and it is configured to purge jobs after 120 days and, according to its job output, it only removed jobs from January. So, the cleanup job wasn't the culprit.

**Comment by ryanpetrello** [comment]
Hey @anxstj,

A recent change we made to AWX was to move the events table to a _new_ table that has a `bigint` as its primary key, because users with billions of events were overflowing the old 4-byte integer primary key:

https://github.com/ansible/awx/issues/6010
https://github.com/ansible/awx/pull/6032

As part of this migration we:

1.  Rename the *old* table (which has all your events)
2. Create a *new* table with the new `bigint` primary key
3. Run a background task post-install that moves the events from the old table into the new.
4.  Remove the (now empty) old table when migration is finished

I suspect something is up with step #3 in your setup.

Can you exec into your `awx_task` container and run a few commands for me and share the output here?

```shell
awx-manage run_dispatcher --status
```

```shell
awx-manage shell_plus
```

...then, at the psql prompt...

```sql
SELECT COUNT(*) FROM _old_main_jobevent;
```

**Comment by anxstj** [comment]
Hi @ryanpetrello,

thank you for your fast reply.

```
# docker exec -it awx_task bash
bash-4.4# awx-manage run_dispatcher --status
2020-05-20 13:35:23,815 WARNING  awx.main.dispatch checking dispatcher status for awx
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/handlers.py", line 936, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/handlers.py", line 857, in _connect_unixsocket
    self.socket.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/handlers.py", line 939, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib64/python3.6/logging/handlers.py", line 868, in _connect_unixsocket
    self.socket.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
Call stack:
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/run_dispatcher.py", line 37, in handle
    print(Control('dispatcher').status())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/dispatch/control.py", line 24, in status
    return self.control_with_reply('status', *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/dispatch/control.py", line 34, in control_with_reply
    logger.warn('checking {} {} for {}'.format(self.service, command, self.queuename))
  File "/usr/lib64/python3.6/logging/__init__.py", line 1325, in warn
    self.warning(msg, *args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1320, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/utils/handlers.py", line 22, in emit
    return super(RSysLogHandler, self).emit(msg)
Message: 'checking dispatcher status for awx'
Arguments: ()
listening on ['tower_broadcast_all', 'awx']
awx[pid:105] workers total=4 min=4 max=160 
.  worker[pid:15750] sent=4 finished=3 qsize=1 rss=132.148MB
     - running 1c6add9f-c4b0-4bc5-a721-15417b4e67d2 RunProjectUpdate(*[45675])
.  worker[pid:24593] sent=5 finished=5 qsize=0 rss=122.059MB [IDLE]
.  worker[pid:24596] sent=3 finished=3 qsize=0 rss=122.059MB [IDLE]
.  worker[pid:24599] sent=1 finished=1 qsize=0 rss=121.992MB [IDLE]
```

```
bash-4.4# awx-manage shell_plus
# Shell Plus Model Imports
from awx.conf.models import Setting
from awx.main.models.activity_stream import ActivityStream
from awx.main.models.ad_hoc_commands import AdHocCommand
from awx.main.models.credential import Credential, CredentialInputSource, CredentialType
from awx.main.models.events import AdHocCommandEvent, InventoryUpdateEvent, JobEvent, ProjectUpdateEvent, SystemJobEvent
from awx.main.models.ha import Instance, InstanceGroup, InventoryInstanceGroupMembership, OrganizationInstanceGroupMembership, TowerAnalyticsState, TowerScheduleState, UnifiedJobTemplateInstanceGroupMembership
from awx.main.models.inventory import CustomInventoryScript, Host, Inventory, InventorySource, InventoryUpdate, SmartInventoryMembership
from django.contrib.auth.models import Group, Permission, User
from awx.main.models.jobs import Job, JobHostSummary, JobLaunchConfig, JobTemplate, SystemJob, SystemJobTemplate
from awx.main.models.label import Label
from awx.main.models.notifications import Notification, NotificationTemplate
from awx.main.models.oauth import OAuth2AccessToken, OAuth2Application
from awx.main.models.organization import Organization, Profile, Team, UserSessionMembership
from awx.main.models.projects import Project, ProjectUpdate
from awx.main.models.rbac import Role, RoleAncestorEntry
from awx.main.models.schedules import Schedule
from awx.main.models.unified_jobs import UnifiedJob, UnifiedJobDeprecatedStdout, UnifiedJobTemplate
from awx.main.models.workflow import WorkflowApproval, WorkflowApprovalTemplate, WorkflowJob, WorkflowJobNode, WorkflowJobTemplate, WorkflowJobTemplateNode
from awx.sso.models import UserEnterpriseAuth
from django.contrib.contenttypes.models import ContentType
from django.contrib.sessions.models import Session
from django.contrib.sites.models import Site
from oauth2_provider.models import Grant, RefreshToken
from social_django.models import Association, Code, Nonce, Partial, UserSocialAuth
from taggit.models import Tag, TaggedItem
# Shell Plus Django Imports
from django.core.cache import cache
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import transaction
from django.db.models import Avg, Case, Count, F, Max, Min, Prefetch, Q, Sum, When, Exists, OuterRef, Subquery
from django.utils import timezone
from django.urls import reverse
Python 3.6.8 (default, Nov 21 2019, 19:31:34) 
[GCC 8.3.1 20190507 (Red Hat 8.3.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>>
```

```
awx=# SELECT COUNT(*) FROM _old_main_jobevent;
  count  
---------
 7727159
(1 row)
```

**Comment by ryanpetrello** [comment]
Yep, your data is there, it just wasn't migrated (I'm unclear why, though your logs may provide some hints):

```sql
awx=# SELECT COUNT(*) FROM _old_main_jobevent;
  count  
---------
 7727159
(1 row)
```

If you want to kick off the migration process again, try something like this in the `awx_task` container:

```shell
supervisorctl -c /supervisor_task.conf restart tower-processes:dispatcher
```

**Comment by anxstj** [comment]
So starting the dispatcher seems to work:

```
bash-4.4# supervisorctl -c /supervisor_task.conf restart tower-processes:dispatcher
tower-processes:dispatcher: stopped
tower-processes:dispatcher: started
bash-4.4# ps faux | grep dispatcher
root     26944  0.0  0.0  12104  1080 pts/0    S+   14:26   0:00  \_ grep dispatcher
root     26931 72.5  0.3 303504 131252 ?       S    14:26   0:02      \_ /var/lib/awx/venv/awx/bin/python3 /usr/bin/awx-manage run_dispatcher
root     26937  0.0  0.3 302208 117652 ?       S    14:26   0:00          \_ /var/lib/awx/venv/awx/bin/python3 /usr/bin/awx-manage run_dispatcher
root     26938  0.0  0.3 302380 116668 ?       S    14:26   0:00          \_ /var/lib/awx/venv/awx/bin/python3 /usr/bin/awx-manage run_dispatcher
root     26939  0.0  0.3 302660 117144 ?       S    14:26   0:00          \_ /var/lib/awx/venv/awx/bin/python3 /usr/bin/awx-manage run_dispatcher
root     26940  0.0  0.3 302684 117148 ?       S    14:26   0:00          \_ /var/lib/awx/venv/awx/bin/python3 /usr/bin/awx-manage run_dispatcher
root     26941  0.0  0.3 302708 117192 ?       S    14:26   0:00          \_ /var/lib/awx/venv/awx/bin/python3 /usr/bin/awx-manage run_dispatcher
```
But I still get the logging error:

```
2020-05-20 14:27:37,435 WARNING  awx.main.dispatch checking dispatcher status for awx
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/handlers.py", line 936, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/handlers.py", line 857, in _connect_unixsocket
    self.socket.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/handlers.py", line 939, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib64/python3.6/logging/handlers.py", line 868, in _connect_unixsocket
    self.socket.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
Call stack:
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 152, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/run_dispatcher.py", line 37, in handle
    print(Control('dispatcher').status())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/dispatch/control.py", line 24, in status
    return self.control_with_reply('status', *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/dispatch/control.py", line 34, in control_with_reply
    logger.warn('checking {} {} for {}'.format(self.service, command, self.queuename))
  File "/usr/lib64/python3.6/logging/__init__.py", line 1325, in warn
    self.warning(msg, *args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1320, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/utils/handlers.py", line 22, in emit
    return super(RSysLogHandler, self).emit(msg)
Message: 'checking dispatcher status for awx'
Arguments: ()
listening on ['tower_broadcast_all', 'awx']
awx[pid:26931] workers total=4 min=4 max=160 
.  worker[pid:26938] sent=3 finished=3 qsize=0 rss=129.914MB [IDLE]
.  worker[pid:26939] sent=1 finished=1 qsize=0 rss=119.371MB [IDLE]
.  worker[pid:26940] sent=3 finished=3 qsize=0 rss=128.922MB [IDLE]
.  worker[pid:26941] sent=1 finished=0 qsize=1 rss=132.910MB
     - running b4861e26-24c6-40de-a81f-fb282313c8a6 RunJob(*[45771])

```
And that's all I see in the container logs. But I updated AWX over a week ago and the relevant logs have been rotated away. I recognized the missing data just today.

And the old events are still missing.

**Comment by ryanpetrello** [comment]
@rooftopcellist @wenottingham is the above traceback ^ a symptom of https://github.com/ansible/awx/pull/7088 ?

**Comment by ryanpetrello** [comment]
Reading back over your instructions:

`git merge 11.2.0`

Er, this probably is *not* what you want.

Can you:

`git fetch && git reset --hard origin/11.2.0`

Also, can you share the output of `docker image ls` ?

**Comment by anxstj** [comment]
I use some custom environments and build the containers myself. The changes are kept in the git repo and that's why the merge is necessary.
Except from the custom environments this is a default AWX with an external Postgresql 9.6 database.

```
git.example.com:4567/awx/ansible-awx/awx_task   11.2.0              2491ba548c25        8 days ago          5.39GB
git.example.com:4567/awx/ansible-awx/awx_web    11.2.0              0eccf450d5f7        8 days ago          5.35GB
git.example.com:4567/awx/ansible-awx/awx_task   <none>              9241851a3313        8 days ago          5.01GB
git.example.com:4567/awx/ansible-awx/awx_web    <none>              9c922738e747        8 days ago          4.97GB
git.example.com:4567/awx/ansible-awx/awx_task   9.3.0               0b4855fe9692        2 months ago        4.5GB
git.example.com:4567/awx/ansible-awx/awx_web    9.3.0               6fe48e17fdd2        2 months ago        4.46GB
redis                                           latest              f9b990972689        2 weeks ago         104MB
centos                                          8                   0f3e07c0138f        7 months ago        220MB
memcached                                       alpine              1b52b65cdde8        15 months ago       10.2MB
ansible/awx_rabbitmq                            3.7.4               e08fe791079e        2 years ago         85.6MB
```

**Comment by wenottingham** [comment]
> @rooftopcellist @wenottingham is the above traceback ^ a symptom of #7088 ?

I don't thik so, that manifests more as a rsyslog error before you get anywhere (and is dev env only).

**Comment by ryanpetrello** [comment]
@anxstj 

Aside from the noisy logs you've mentioned, did your events get processed after restarting the dispatcher process?

**Comment by anxstj** [comment]
New events get processed and show up in the job view. But the old events are still not migrated.

**Comment by anxstj** [comment]
I just checked a local test environment that uses the same container images, but also a postgresql container instead of a dedicated postgresql node. The test environment has all job events, including all the ones before the update. The awx database doesn't have a table _old_main_jobevent. This seems to indicate that the jobevent table migration was successful.

And the logs show:
```
Running migrations:
  Applying main.0109_v370_job_template_organization_field... OK
  Applying main.0110_v370_instance_ip_address... OK
  Applying main.0111_v370_delete_channelgroup... OK
  Applying main.0112_v370_workflow_node_identifier... OK
  Applying main.0113_v370_event_bigint... OK
  Applying main.0114_v370_remove_deprecated_manual_inventory_sources... OK
```
Is it possible that this problem is related to the dedicated postgresql database? (e.g. pg_hostname is defined)?

The `OSError: [Errno 9] Bad file descriptor` doesn't show up in the test environment, either.

The container images are the same.
```
$ docker image ls | grep awx 
git.example.com:4567/awx/ansible-awx/awx_task   11.2.0           2491ba548c25        2 weeks ago         5.39GB
git.example.com:4567/awx/ansible-awx/awx_web    11.2.0           0eccf450d5f7        2 weeks ago         5.35GB
ansible/awx_rabbitmq                             3.7.4           e08fe791079e        2 years ago         85.6MB
```

**Comment by ryanpetrello** [comment]
@anxstj,

Try running this in the `awx_task` container:

`~ awx-manage shell_plus`

...then, at the Python prompt:

```python
from awx.main.models import enforce_bigint_pk_migration
enforce_bigint_pk_migration()
```

**Comment by anxstj** [comment]
Running `enforce_bigint_pk_migration()` exits immediately. But the container logs the following:

```
2020-05-26 19:18:11,800 DEBUG    awx.main.dispatch task 0899f8b0-5c00-471b-b7c2-b6c19ccb5a5e starting awx.main.tasks.migrate_legacy_event_data(*['main_jobevent'])
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/handlers.py", line 936, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor
....
2020-05-26 19:18:27,898 DEBUG    awx.main.dispatch task a061075e-d0af-4c15-80f5-462e452b0b4a starting awx.main.tasks.awx_periodic_scheduler(*[])
2020-05-26 19:18:27,903 WARNING  awx.main.dispatch scaling up worker pid:12621
2020-05-26 19:18:27,912 DEBUG    awx.main.dispatch task 19c830c7-b834-4b69-a51d-093f4233c5c2 starting awx.main.scheduler.tasks.run_task_manager(*[])
2020-05-26 19:18:27,913 DEBUG    awx.main.scheduler Running Tower task manager.
2020-05-26 19:18:27,919 DEBUG    awx.main.tasks Starting periodic scheduler
2020-05-26 19:18:27,926 DEBUG    awx.main.tasks Last scheduler run was: 2020-05-26 19:17:57.379308+00:00
2020-05-26 19:18:27,933 DEBUG    awx.main.scheduler Starting Scheduler
...
2020-05-26 19:23:00,656 WARNING  awx.main.tasks migrated int -> bigint rows to main_jobevent from _old_main_jobevent; # (11301759 rows remaining)
```

What does the last message mean? Has the job finished or is it still running?

I run the `enforce_bigint_pk_migration()` command a second time, and got this output:
```
2020-05-26 19:38:30,254 DEBUG    awx.main.dispatch task 78dde9db-a9ac-4f17-88a8-9d1252d9b1bb starting awx.main.tasks.migrate_legacy_event_data(*['main_jobevent'])
...
2020-05-26 19:46:40,857 WARNING  awx.main.tasks migrated int -> bigint rows to main_jobevent from _old_main_jobevent; # (10301759 rows remaining)
```
The row count is the same.

**Comment by ryanpetrello** [comment]
> 2020-05-26 19:23:00,656 WARNING  awx.main.tasks migrated int -> bigint rows to main_jobevent from _old_main_jobevent; # (11301759 rows remaining)

It means it's migrating them in the background, and you'll need to wait while it does so (it may take a minute to migrate your 10M rows to the new table) 😄 

```2020-05-26 19:18:11,800 DEBUG    awx.main.dispatch task 0899f8b0-5c00-471b-b7c2-b6c19ccb5a5e starting awx.main.tasks.migrate_legacy_event_data(*['main_jobevent'])
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/handlers.py", line 936, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor
```

I'm not really sure why this is happening - maybe it's an underlying permissions issue with the socket for rsyslogd?  What happens if you run this in the task container:

```shell
ls -la /var/run/awx-rsyslog/rsyslog.sock
```

Also, if you run:

```shell
awx-manage shell_plus
```

...and run this at the Python prompt, can you share the output?

```python
In [4]: settings.LOGGING['handlers']['external_logger']
Out[4]:
{'address': '/var/run/awx-rsyslog/rsyslog.sock',
 'class': 'awx.main.utils.handlers.RSysLogHandler',
 'filters': ['external_log_enabled', 'dynamic_level_filter'],
 'formatter': 'json'}
```

**Comment by anxstj** [comment]
> It means it's migrating them in the background, and you'll need to wait while it does so (it may take a minute to migrate your 10M rows to the new table)

It worked! The _old_main_jobevent table is gone and the old events show up again in the job view. 

For the sake of completeness:
```
2020-05-26 19:46:40,857 WARNING  awx.main.tasks migrated int -> bigint rows to main_jobevent from _old_main_jobevent; # (10301759 rows remaining)
2020-05-26 20:03:32,986 WARNING  awx.main.tasks migrated int -> bigint rows to main_jobevent from _old_main_jobevent; # (9301759 rows remaining)
2020-05-26 20:17:22,750 WARNING  awx.main.tasks migrated int -> bigint rows to main_jobevent from _old_main_jobevent; # (8301759 rows remaining)
2020-05-26 20:25:58,794 WARNING  awx.main.tasks migrated int -> bigint rows to main_jobevent from _old_main_jobevent; # (7301759 rows remaining)
2020-05-26 20:26:23,827 WARNING  awx.main.tasks main_jobevent primary key migration to bigint has finished
```
So this took approx. 40 minutes to migrate.

And here's the output of the requested commands:
```
bash-4.4# ls -la /var/run/awx-rsyslog/rsyslog.sock
srw-rw-rw- 1 root root 0 May 16 21:15 /var/run/awx-rsyslog/rsyslog.sock
```
```
>>> settings.LOGGING['handlers']['external_logger']
{'class': 'awx.main.utils.handlers.RSysLogHandler', 'formatter': 'json', 'address': '/var/run/awx-rsyslog/rsyslog.sock', 'filters': ['external_log_enabled', 'dynamic_level_filter']}
````

Thank you a lot for your ongoing help.

**Comment by anxstj** [comment]
I guess I found the logging problem. 

I have external logging configured:

https://awx.example.com/api/v2/settings/logging/
```
{
    "LOG_AGGREGATOR_HOST": "host.example.com",
    "LOG_AGGREGATOR_PORT": 1470,
    "LOG_AGGREGATOR_TYPE": "other",
    "LOG_AGGREGATOR_USERNAME": "",
    "LOG_AGGREGATOR_PASSWORD": "$encrypted$",
    "LOG_AGGREGATOR_LOGGERS": [
        "awx",
        "activity_stream",
        "job_events",
        "system_tracking"
    ],
    "LOG_AGGREGATOR_INDIVIDUAL_FACTS": false,
    "LOG_AGGREGATOR_ENABLED": true,
    "LOG_AGGREGATOR_TOWER_UUID": "",
    "LOG_AGGREGATOR_PROTOCOL": "tcp",
    "LOG_AGGREGATOR_TCP_TIMEOUT": 5,
    "LOG_AGGREGATOR_VERIFY_CERT": true,
    "LOG_AGGREGATOR_LEVEL": "INFO",
    "LOG_AGGREGATOR_AUDIT": false,
    "LOG_AGGREGATOR_MAX_DISK_USAGE_GB": 1,
    "LOG_AGGREGATOR_MAX_DISK_USAGE_PATH": "/var/lib/awx",
    "LOG_AGGREGATOR_RSYSLOGD_DEBUG": false
}
```

After disabling the logging, I got the following logs:
```
2020-05-27 15:10:50,361 INFO spawned: 'awx-rsyslogd' with pid 1072
rsyslogd: pidfile '/var/run/awx-rsyslog/rsyslog.pid' and pid 1072 already exist.
If you want to run multiple instances of rsyslog, you need to specify
different pid files for them (-i option).
rsyslogd: run failed with error -3000 (see rsyslog.h or try https://www.rsyslog.com/e/3000 to learn what that number means)
2020-05-27 15:10:50,374 INFO exited: awx-rsyslogd (exit status 1; not expected)
```

pid 1072 didn't exist?! Executing `rm /var/run/awx-rsyslog/rsyslog.pid` inside the awx_web container and enabling the external logging (or running `supervisorctl restart awx-rsyslogd`) again fixed the logging error messages. Now rsyslogd is running inside awx_task and awx_web.

**Comment by gstorme** [comment]
Same upgrade path here on 2 separate AWX instances.
Both report `Applying main.0113_v370_event_bigint... OK` in the logs, but it only really succeeded on 1 out of 2.
The one where it succeeded has 13k rows in the jobevent table, the one where it failed has 14 million rows.

It's migrating the rows now at about 1 million per 5 minutes, after triggering the provided `enforce_bigint_pk_migration()`
