### ISSUE TITLE
SAML auth: Missing backend "saml" entry

### ISSUE THREAD

**Issue by xokamix** [ansible/awx#715]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

After SAML configured, got 502 from django on metadata page.
Seems like it cant find saml backend.

##### ENVIRONMENT
* AWX version: AWX 1.0.1.229
* AWX install method: docker for linux
* Ansible version: 2.4.1.0
* Operating System: centos7-core 3.10.0-327.22.2.el7.x86_64
* Web Browser: Firefox 56.0 / Chromium 62.0 (Linux Mint)

##### STEPS TO REPRODUCE

Clean install, with only saml auth configured.

##### EXPECTED RESULTS

Correct metadata.xml file

##### ACTUAL RESULTS

502 bad gateway, 
in awx_web logs:
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_core/backends/utils.py", line 57, in get_backend
    raise MissingBackend(name)
MissingBackend: Missing backend "saml" entry

##### ADDITIONAL INFORMATION
I've done 2 setups, first was with reverse proxy for https and ssl termination, the second one (after 1st try with saml failed) was clean install, with just SAML auth configured, but result was the same, even with empty config.

**Comment by matburt** [comment]
Can you show us a saml config put into AWX that can recreate t his scenario?

**Comment by iyurev** [comment]
Good day!
 I'am was try configured SAML with ADFS and got same error.

**AWX 1.0.1.268**

**Comment by iyurev** [comment]
My AWX  worked in docker containers, and HTTPS configured on separate container with nginx which do reverce proxy on awx_web http://:8052.  
This is json from my ENABLED IDENTITY PROVAIDER section, may be this will helpful:

{
"saml_ms_adfs":{
    "entity_id": "http://somedomain.foo/adfs/services/trust",
	"url": "https://somedomain.foo/adfs/ls",
    "x509cert": "some_certificate_in_one_string",
    "attr_user_permanent_id": "SamAccountName",
    "attr_first_name": "GivenName",
    "attr_last_name": "RuSurname",
    "attr_username": "SamAccountName",
    "attr_email": "Email"
    }
}

**Comment by matburt** [comment]
Thanks @badeveloper 

Given that this seems to work for others I'm going to close this one out. If you can provide more detail we can take another look.

**Comment by xokamix** [comment]
Sorry for delay,
 @matburt what details do you need?

I've looked into auth setting via API and seems that there are no SAML backend.
Reinstalled AWX, now it's **1.0.1.290**


```
/api/v2/settings/authentication/

 "AUTHENTICATION_BACKENDS": [
        "awx.sso.backends.LDAPBackend",
        "awx.sso.backends.TACACSPlusBackend",
        "social_core.backends.google.GoogleOAuth2",
        "social_core.backends.github.GithubOAuth2",
        "social_core.backends.github.GithubOrganizationOAuth2",
        "social_core.backends.github.GithubTeamOAuth2",
        "social_core.backends.azuread.AzureADOAuth2",
        "django.contrib.auth.backends.ModelBackend"
    ],
```

Thats what i got there.


As for SAML settings:

```
{
    "SOCIAL_AUTH_SAML_CALLBACK_URL": "http://tower.foo.bar/sso/complete/saml/",
    "SOCIAL_AUTH_SAML_METADATA_URL": "http://tower.foo.bar/sso/metadata/saml/",
    "SOCIAL_AUTH_SAML_SP_ENTITY_ID": "http://tower.foo.bar/",
    "SOCIAL_AUTH_SAML_SP_PUBLIC_CERT": "",
    "SOCIAL_AUTH_SAML_SP_PRIVATE_KEY": "",
    "SOCIAL_AUTH_SAML_ORG_INFO": {
        "en-US": {
            "url": "http://www.example.com",
            "displayname": "Example",
            "name": "example"
        }
    },
    "SOCIAL_AUTH_SAML_TECHNICAL_CONTACT": {
        "givenName": "Some User",
        "emailAddress": "suser@example.com"
    },
    "SOCIAL_AUTH_SAML_SUPPORT_CONTACT": {
        "givenName": "Some User",
        "emailAddress": "suser@example.com"
    },
    "SOCIAL_AUTH_SAML_ENABLED_IDPS": {
        "saml_ms_adfs": {
            "attr_last_name": "Surname",
            "attr_username": "SamAccountName",
            "entity_id": "http://adfs.foo.bar/adfs/services/trust",
            "attr_user_permanent_id": "SamAccountName",
            "url": "https://adfs.foo.bar/adfs/ls",
            "attr_email": "Email",
            "x509cert": "some_cert",
            "attr_first_name": "GivenName"
        }
    },
```

**Comment by iyurev** [comment]
Today I try update awx_web image to **1.0.1.307**, and get same error .  In container log sees  explicit error related with missing salm backend:

`Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/sso/views.py", line 87, in get
    redirect_uri=complete_url,
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/utils.py", line 27, in load_backend
    Backend = get_backend(BACKENDS, name)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_core/backends/utils.py", line 57, in get_backend
    raise MissingBackend(name)
MissingBackend: Missing backend "saml" entry
2017-12-11 11:33:01,337 ERROR    django.request Internal Server Error: /sso/metadata/saml/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/sso/views.py", line 87, in get
    redirect_uri=complete_url,
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/utils.py", line 27, in load_backend
    Backend = get_backend(BACKENDS, name)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_core/backends/utils.py", line 57, in get_backend
    raise MissingBackend(name)
MissingBackend: Missing backend "saml" entry
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 143, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/usr/lib/python2.7/site-packages/awx/main/views.py", line 88, in handle_500
`

**Comment by xokamix** [comment]
Error seems to be there on images builded localy too.

**Comment by batemanst** [comment]
I'm seeing the same thing, fwiw.

Image: 1.0.1.323

Enabled backends:

```
{
    "AUTH_TOKEN_EXPIRATION": 1800,
    "AUTH_TOKEN_PER_USER": -1,
    "AUTH_BASIC_ENABLED": true,
    "AUTHENTICATION_BACKENDS": [
        "awx.sso.backends.TACACSPlusBackend",
        "social_core.backends.google.GoogleOAuth2",
        "social_core.backends.github.GithubOAuth2",
        "social_core.backends.github.GithubOrganizationOAuth2",
        "social_core.backends.github.GithubTeamOAuth2",
        "social_core.backends.azuread.AzureADOAuth2",
        "django.contrib.auth.backends.ModelBackend"
    ],
    "SOCIAL_AUTH_ORGANIZATION_MAP": null,
    "SOCIAL_AUTH_TEAM_MAP": null,
    "SOCIAL_AUTH_USER_FIELDS": null
}
```

Traceback when hitting `/sso/metadata/saml` and returns `502`:

```

2017-12-13 03:07:18,522 ERROR    django.request Internal Server Error: /sso/metadata/saml/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/sso/views.py", line 87, in get
    redirect_uri=complete_url,
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_django/utils.py", line 27, in load_backend
    Backend = get_backend(BACKENDS, name)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/social_core/backends/utils.py", line 57, in get_backend
    raise MissingBackend(name)
MissingBackend: Missing backend "saml" entry

```

**Comment by xokamix** [comment]
@matburt Hello,
 could you please reopen this issues,a as it seems it bothering not me alone.

**Comment by oscartcy** [comment]
Hi,

Same issue here after configuring SAML settings through AWX UI and access /sso/metadata/saml/, it returns 502 bad gateway.

AWX 1.0.1.316

**Comment by iyurev** [comment]
From  /api/v2/settings/all/ :

   ```"AUTHENTICATION_BACKENDS": [
        "awx.sso.backends.TACACSPlusBackend",
        "social_core.backends.google.GoogleOAuth2",
        "social_core.backends.github.GithubOAuth2",
        "social_core.backends.github.GithubOrganizationOAuth2",
        "social_core.backends.github.GithubTeamOAuth2",
        "social_core.backends.azuread.AzureADOAuth2",
        "django.contrib.auth.backends.ModelBackend"
    ]
``` 

   SAML backends hasn't in  this list...

   Some one can explain saml backend must be there by default  after run container  or it  be enabled     only after correct setting through web interface???

**Comment by matburt** [comment]
Thanks for the details, we'll open this back up to take a look.

**Comment by batemanst** [comment]
My issue ended up being a missing field in the SAML config, didn't have the cert and private key configured. The Tower documentation was unclear about whether that was required when already doing SSL termination at the load balancer.

After all of the fields are populated, including an X509 cert and private key, then the SAML backend is activated.

**Comment by iyurev** [comment]
Yes, Backend activated after I added cert and private key from nginx that do HTTPS . @batemanst

**Comment by iyurev** [comment]
@matburt   So, I think it more  flaw of documentation that code.

**Comment by matburt** [comment]
Sounds good. We definitely do accept PRs
