### ISSUE TITLE
Deadlock on /inventory_sources/pk/hosts deletion

### ISSUE THREAD

**Issue by awithrow9** [ansible/awx#716]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
While  deleting an ec2 inventory source the following was observed:

```
awx_1        | 19:02:17 uwsgi.1     | 2017-11-14 19:02:17,163 ERROR    django.request Internal Server Error: /api/v2/inventory_sources/22/hosts/
awx_1        | 19:02:17 uwsgi.1     | Traceback (most recent call last):
awx_1        | 19:02:17 uwsgi.1     |   File "/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
awx_1        | 19:02:17 uwsgi.1     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
awx_1        | 19:02:17 uwsgi.1     |   File "/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
awx_1        | 19:02:17 uwsgi.1     |     return func(*args, **kwargs)
awx_1        | 19:02:17 uwsgi.1     |   File "/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
awx_1        | 19:02:17 uwsgi.1     |     return view_func(*args, **kwargs)
awx_1        | 19:02:17 uwsgi.1     |   File "/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
awx_1        | 19:02:17 uwsgi.1     |     return self.dispatch(request, *args, **kwargs)
awx_1        | 19:02:17 uwsgi.1     |   File "./awx/api/generics.py", line 246, in dispatch
awx_1        | 19:02:17 uwsgi.1     |     return super(APIView, self).dispatch(request, *args, **kwargs)
awx_1        | 19:02:17 uwsgi.1     |   File "/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
awx_1        | 19:02:17 uwsgi.1     |     response = self.handle_exception(exc)
awx_1        | 19:02:17 uwsgi.1     |   File "/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
awx_1        | 19:02:17 uwsgi.1     |     response = handler(request, *args, **kwargs)
awx_1        | 19:02:17 uwsgi.1     |   File "/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 220, in delete
awx_1        | 19:02:17 uwsgi.1     |     return self.destroy(request, *args, **kwargs)
awx_1        | 19:02:17 uwsgi.1     |   File "./awx/api/generics.py", line 466, in destroy
awx_1        | 19:02:17 uwsgi.1     |     self.perform_list_destroy(instance_list)
awx_1        | 19:02:17 uwsgi.1     |   File "./awx/api/generics.py", line 476, in perform_list_destroy
awx_1        | 19:02:17 uwsgi.1     |     self.perform_destroy(instance, check_permission=False)
awx_1        | 19:02:17 uwsgi.1     |   File "./awx/api/generics.py", line 452, in perform_destroy
awx_1        | 19:02:17 uwsgi.1     |     super(DestroyAPIView, self).perform_destroy(instance)
awx_1        | 19:02:17 uwsgi.1     |   File "/venv/awx/lib/python2.7/site-packages/rest_framework/mixins.py", line 91, in perform_destroy
awx_1        | 19:02:17 uwsgi.1     |     instance.delete()
awx_1        | 19:02:17 uwsgi.1     |   File "./awx/main/models/inventory.py", line 604, in delete
awx_1        | 19:02:17 uwsgi.1     |     super(Host, self).delete(*args, **kwargs)
awx_1        | 19:02:17 uwsgi.1     |   File "/venv/awx/lib/python2.7/site-packages/django/db/models/base.py", line 896, in delete
awx_1        | 19:02:17 uwsgi.1     |     collector.delete()
awx_1        | 19:02:17 uwsgi.1     |   File "/venv/awx/lib/python2.7/site-packages/django/db/models/deletion.py", line 309, in delete
awx_1        | 19:02:17 uwsgi.1     |     query.delete_batch(pk_list, self.using)
awx_1        | 19:02:17 uwsgi.1     |   File "/venv/awx/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 41, in delete_batch
awx_1        | 19:02:17 uwsgi.1     |     self.do_query(self.get_meta().db_table, self.where, using=using)
awx_1        | 19:02:17 uwsgi.1     |   File "/venv/awx/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 26, in do_query
awx_1        | 19:02:17 uwsgi.1     |     self.get_compiler(using).execute_sql(NO_RESULTS)
awx_1        | 19:02:17 uwsgi.1     |   File "/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
awx_1        | 19:02:17 uwsgi.1     |     cursor.execute(sql, params)
awx_1        | 19:02:17 uwsgi.1     |   File "/venv/awx/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
awx_1        | 19:02:17 uwsgi.1     |     return super(CursorDebugWrapper, self).execute(sql, params)
awx_1        | 19:02:17 uwsgi.1     |   File "/venv/awx/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
awx_1        | 19:02:17 uwsgi.1     |     return self.cursor.execute(sql, params)
awx_1        | 19:02:17 uwsgi.1     |   File "/venv/awx/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
awx_1        | 19:02:17 uwsgi.1     |     six.reraise(dj_exc_type, dj_exc_value, traceback)
awx_1        | 19:02:17 uwsgi.1     |   File "/venv/awx/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
awx_1        | 19:02:17 uwsgi.1     |     return self.cursor.execute(sql, params)
awx_1        | 19:02:17 uwsgi.1     | OperationalError: deadlock detected
awx_1        | 19:02:17 uwsgi.1     | DETAIL:  Process 2534 waits for ShareLock on transaction 24363; blocked by process 2535.
awx_1        | 19:02:17 uwsgi.1     | Process 2535 waits for ShareLock on transaction 24358; blocked by process 2534.
awx_1        | 19:02:17 uwsgi.1     | HINT:  See server log for query details.
awx_1        | 19:02:17 uwsgi.1     | CONTEXT:  while deleting tuple (0,74) in relation "main_group_hosts"
```

##### ENVIRONMENT
* AWX version: 3.2.2

##### STEPS TO REPRODUCE

1) Create and sync an ec2 inventory source
2) Send delete requests to the inventory source's related hosts and groups endpoints.

##### EXPECTED RESULTS

Successful, performant deletion.

##### ACTUAL RESULTS

500 error and no hosts deleted.

**Comment by ryanpetrello** [comment]
Closing due to age.
