### ISSUE TITLE
1/1000 login attempts from the ui_next server returns HTTP 400 from /api/login

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#7165]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

1/1000 Login attempts fails on the ui_next dev server. The /api/login/ returns HTTP 400 The error from our testrunner is included under ADDITIONAL INFORMATION.

##### ENVIRONMENT
* AWX version: 10+
* AWX install method: docker on linux, ui_next dev server

##### STEPS TO REPRODUCE

Our UI Tests fail to log in 1/1000 attempts. We finally implemented logging to capture this failed login attempt.

I honestly don't have a good way to reproduce. So I'll include the error as thrown from the test runner and also the sosreport.

##### ADDITIONAL INFORMATION

```
CypressError: cy.request() failed on:

https://ui-next:3001/api/login/

The response we received from your web server was:

> 400: Bad Request

This was considered a failure because the status code was not '2xx' or '3xx'.

If you do not want status codes to cause failures pass the option: 'failOnStatusCode: false'

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: https://ui-next:3001/api/login/
Headers: {
"Connection": "keep-alive",
"referer": "https://ui-next:3001/api/login/",
"x-csrftoken": "H7vtWbsxhFeIEPBTKADe46l86MWP9yIBTJFk8zovaK2GBJOw4oFviRkWH1Gc6X66",
"user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 KHTML, like Gecko Chrome/79.0.3945.130 Safari/537.36",
"accept": "*/*",
"cookie": "sessionid=a2tdbz2di457la37vfirh34cptd44o6x; csrftoken=H7vtWbsxhFeIEPBTKADe46l86MWP9yIBTJFk8zovaK2GBJOw4oFviRkWH1Gc6X66",
"content-type": "application/x-www-form-urlencoded",
"accept-encoding": "gzip, deflate",
"content-length": 155
}
Body: username=admin&password=afXy%40tF%5Dl%2Cz%26%3EF%3F%3FH&next=%2Fapi%2F&csrfmiddlewaretoken=H7vtWbsxhFeIEPBTKADe46l86MWP9yIBTJFk8zovaK2GBJOw4oFviRkWH1Gc6X66

-----------------------------------------------------------

The response we got was:

Status: 400 - Bad Request
Headers: {
"x-powered-by": "Express",
"server": "nginx",
"date": "Tue, 26 May 2020 15:08:34 GMT",
"content-type": "application/json",
"transfer-encoding": "chunked",
"connection": "close",
"vary": "Accept, Accept-Encoding",
"x-api-total-time": "0.184s",
"content-encoding": "gzip"
}
Body: {
"detail": "The request could not be understood by the server."
}


Because this error occurred during a 'before each' hook we are skipping all of the remaining tests.
at Object.cypressErr (https://ui-next:3001/__cypress/runner/cypress_runner.js:86207:11)
at Object.throwErr (https://ui-next:3001/__cypress/runner/cypress_runner.js:86162:18)
at Object.throwErrByPath (https://ui-next:3001/__cypress/runner/cypress_runner.js:86194:17)
at https://ui-next:3001/__cypress/runner/cypress_runner.js:72496:18
at tryCatcher (https://ui-next:3001/__cypress/runner/cypress_runner.js:120203:23)
at Promise._settlePromiseFromHandler (https://ui-next:3001/__cypress/runner/cypress_runner.js:118139:31)
at Promise._settlePromise (https://ui-next:3001/__cypress/runner/cypress_runner.js:118196:18)
at Promise._settlePromise0 (https://ui-next:3001/__cypress/runner/cypress_runner.js:118241:10)
at Promise._settlePromises (https://ui-next:3001/__cypress/runner/cypress_runner.js:118320:18)
at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (https://ui-next:3001/__cypress/runner/cypress_runner.js:114928:16)
at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://ui-next:3001/__cypress/runner/cypress_runner.js:114938:10)
at Async.drainQueues (https://ui-next:3001/__cypress/runner/cypress_runner.js:114812:14)
```
[all_tower_sos_reports (3).tar.gz](https://github.com/ansible/awx/files/4689021/all_tower_sos_reports.3.tar.gz)

**Comment by unlikelyzero** [comment]
closing as it has not been reproduced
