### ISSUE TITLE
Internal Server Error 500 on requesting inventory sync status under user other then global system administrator.

### ISSUE THREAD

**Issue by iserov** [ansible/awx#726]
![awx_tower_error](https://user-images.githubusercontent.com/34062219/33321663-8443713e-d457-11e7-9e44-4e63609ebcd3.png)
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Getting HTTP code 500 error when trying to get inventory source sync status while logged in as any user other then global system administartor (default admin)

##### ENVIRONMENT
* AWX version: 1.0.1.225
* AWX install method: docker on linux
* Ansible version:  2.4.1.0-1.el7
* Operating System: Red Hat Enterprise Linux Server release 7.4 (Maipo)
* Web Browser: Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

1. Create a user and give him admin privileges on projects and inventory, organisation and all other elements. The user MUST not have a "system administrator" role.
2. Log in as any user without system administrator privileges.
3. Create a git project and an inventory sourced from that project and syncronize that source using "2 round arrows" from a toolbox to the right.
4. Give the user all privileges on the project and inventory.
5. After all press "green cloud" in front of inventory source object and request the URL  /#/inventory_sync/1219

Observe the error message similar to one from a picture attached to this issue.

##### EXPECTED RESULTS

Expected that a screen with syncronization job status in a left part of the screen and ansible output in a right part of the screen should appear as it do when the user has system administrator privileges (default admin)

##### ADDITIONAL INFORMATION

In the same time we have the following error in awx_web docker container log:

HOSTIP - - [28/Nov/2017:13:08:21 +0000] "GET /api/v2/config/ HTTP/1.1" 200 506 "http://HOSTNAME:PORT/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36" "-"
2017-11-28 13:08:22,116 ERROR    django.request Internal Server Error: /api/v2/inventory_updates/1219/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 248, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 210, in get
    return self.retrieve(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/mixins.py", line 56, in retrieve
    instance = self.get_object()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 101, in get_object
    self.check_object_permissions(self.request, obj)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 339, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
  File "/usr/lib/python2.7/site-packages/awx/api/permissions.py", line 137, in has_object_permission
    return self.has_permission(request, view, obj)
  File "/usr/lib/python2.7/site-packages/awx/api/permissions.py", line 128, in has_permission
    response = self.check_permissions(request, view, obj)
  File "/usr/lib/python2.7/site-packages/awx/api/permissions.py", line 117, in check_permissions
    result = check_method and check_method(request, view, obj)
  File "/usr/lib/python2.7/site-packages/awx/api/permissions.py", line 43, in check_get_permissions
    return check_user_access(request.user, view.model, 'read', obj)
  File "/usr/lib/python2.7/site-packages/awx/main/access.py", line 116, in check_user_access
    result = access_method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/access.py", line 216, in can_read
    return bool(obj and self.get_queryset().filter(pk=obj.pk).exists())
  File "/usr/lib/python2.7/site-packages/awx/main/access.py", line 200, in get_queryset
    qs = self.filtered_queryset()
  File "/usr/lib/python2.7/site-packages/awx/main/access.py", line 886, in filtered_queryset
    return qs.filter(inventory_source__inventory__in=Inventory.accessible_pk_qs(self.user, 'read_role'))
NameError: global name 'qs' is not defined
2017-11-28 13:08:22,116 ERROR    django.request Internal Server Error: /api/v2/inventory_updates/1219/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 248, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 210, in get
    return self.retrieve(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/mixins.py", line 56, in retrieve
    instance = self.get_object()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 101, in get_object
    self.check_object_permissions(self.request, obj)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 339, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
  File "/usr/lib/python2.7/site-packages/awx/api/permissions.py", line 137, in has_object_permission
    return self.has_permission(request, view, obj)
  File "/usr/lib/python2.7/site-packages/awx/api/permissions.py", line 128, in has_permission
    response = self.check_permissions(request, view, obj)
  File "/usr/lib/python2.7/site-packages/awx/api/permissions.py", line 117, in check_permissions
    result = check_method and check_method(request, view, obj)
  File "/usr/lib/python2.7/site-packages/awx/api/permissions.py", line 43, in check_get_permissions
    return check_user_access(request.user, view.model, 'read', obj)
  File "/usr/lib/python2.7/site-packages/awx/main/access.py", line 116, in check_user_access
    result = access_method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/access.py", line 216, in can_read
    return bool(obj and self.get_queryset().filter(pk=obj.pk).exists())
  File "/usr/lib/python2.7/site-packages/awx/main/access.py", line 200, in get_queryset
    qs = self.filtered_queryset()
  File "/usr/lib/python2.7/site-packages/awx/main/access.py", line 886, in filtered_queryset
    return qs.filter(inventory_source__inventory__in=Inventory.accessible_pk_qs(self.user, 'read_role'))
NameError: global name 'qs' is not defined
[pid: 29|app: 0|req: 16/37] HOSTIP () {46 vars in 2488 bytes} [Tue Nov 28 13:08:22 2017] GET /api/v2/inventory_updates/1219/ => generated 41 bytes in 49 msecs (HTTP/1.1 500) 5 headers in 177 bytes (1 switches on core 0)
HOSTIP - - [28/Nov/2017:13:08:22 +0000] "GET /api/v2/inventory_updates/1219/ HTTP/1.1" 500 41 "http://HOSTNAME:PORT/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36" "-"

**Comment by AlanCoding** [comment]
Thanks for the report.
