### ISSUE TITLE
ansible-inventory crashes out-of-memory for large inventories

### ISSUE THREAD

**Issue by benapetr** [ansible/awx#727]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- ansible-inventory

##### SUMMARY
Importing 3500 servers causes ansible-inventory to allocate over 2GB of ram in 10 minutes and then crash:

Plugin script failed: problem running /tmp/awx_inventory_Q31G4Q/tmpSb_Zdb --host de02-pdccz1.cz.prod ([Errno 12] Cannot allocate memory)

##### ENVIRONMENT
* AWX version: 1.0.1.231
* AWX install method: docker on linux
* Ansible version:  2.4.1
* Operating System: RedHat 7.3
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Launch import of very large inventory

##### EXPECTED RESULTS

ansible-inventory should be written in a better way so that it doesn't need to allocate so much of operating memory to do something so simple

##### ACTUAL RESULTS

ansible-inventory crashed

**Comment by benapetr** [comment]
Another bug I probably found, copy paste from output window give 1 line of text only, download fails with "not found."

```
2017-11-28 14:03:29,094 INFO awx.main.commands.inventory_import Updating inventory 2: Server list 2017-11-28 14:03:29,118 INFO awx.main.commands.inventory_import Reading Ansible inventory source: /tmp/awx_inventory_Q31G4Q/tmpSb_Zdb Traceback (most recent call last): File "/usr/bin/awx-manage", line 9, in <module> load_entry_point('awx==1.0.1.231', 'console_scripts', 'awx-manage')() File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage execute_from_command_line(sys.argv) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line utility.execute() File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute self.fetch_command(subcommand).run_from_argv(self.argv) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv self.execute(*args, **cmd_options) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute output = self.handle(*args, **options) File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 995, in handle self.is_custom) File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 242, in load_inventory_source is_custom=is_custom).load() File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 178, in load data = self.command_to_json(base_args + ['--list']) File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 162, in command_to_json self.method, proc.returncode, stdout, stderr)) RuntimeError: ansible-inventory failed (rc=4) with stdout: stderr: ERROR! Could not parse inventory source /tmp/awx_inventory_Q31G4Q/tmpSb_Zdb with available plugins: Plugin script failed: problem running /tmp/awx_inventory_Q31G4Q/tmpSb_Zdb --host de02-pdccz1.cz.prod ([Errno 12] Cannot allocate memory) Plugin yaml failed: YAML inventory has invalid structure, it should be a dictionary, got: <class 'ansible.parsing.yaml.objects.AnsibleUnicode'> Plugin ini failed: /tmp/awx_inventory_Q31G4Q/tmpSb_Zdb:2: Expected key=value host variable assignment, got: http://run-tools.homecredit.net/sl/api/ansible-inventory/run-tools.homecredit.net
```

**Comment by benapetr** [comment]
I can confirm that with smaller inventory (each less than 400 servers) using same inventory script import succeeds with no issues.

The JSON of 3000+ servers inventory is valid and can be imported using much older RHEL supported Ansible Tower, but trying the same on AWX, which is newer, doesn't work and crashes with the unexpected error, possibly bug error

**Comment by matburt** [comment]
Get more memory ;)

ansible-inventory comes from the ansible core project: https://github.com/ansible/ansible

**Comment by benapetr** [comment]
@matburt you don't understand, I already tried to add more memory, then the script crashes with some python exception without even utilizing all of available memory. It's a bug in code. Closing the issue won't fix it. Try to import 3000+ servers from json dynamic inventory yourself and you will see.

**Comment by benapetr** [comment]
This is the log I am getting from job including exception, the fact that it's on 1 line is also a bug in AWX:

```
2017-11-29 11:39:43,751 INFO awx.main.commands.inventory_import Updating inventory 2: Server list 2017-11-29 11:39:43,765 INFO awx.main.commands.inventory_import Reading Ansible inventory source: /tmp/awx_inventory_4DYrGm/tmpWfLF6O Traceback (most recent call last): File "/usr/bin/awx-manage", line 9, in <module> load_entry_point('awx==1.0.1.231', 'console_scripts', 'awx-manage')() File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage execute_from_command_line(sys.argv) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line utility.execute() File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute self.fetch_command(subcommand).run_from_argv(self.argv) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv self.execute(*args, **cmd_options) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute output = self.handle(*args, **options) File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 995, in handle self.is_custom) File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 242, in load_inventory_source is_custom=is_custom).load() File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 178, in load data = self.command_to_json(base_args + ['--list']) File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 162, in command_to_json self.method, proc.returncode, stdout, stderr)) RuntimeError: ansible-inventory failed (rc=250) with stdout: to see the full traceback, use -vvv stderr: ERROR! Unexpected Exception, this is probably a bug: 
```

**Comment by benapetr** [comment]
Using download button gives me this: {"detail":"Not found."}

**Comment by matburt** [comment]
You said you gave 2G of RAM... this is *way* to little memory. Our install docs list a minimum of 4G... how much have you given it where you still see it crash?

**Comment by benapetr** [comment]
8GB of RAM in second run

**Comment by benapetr** [comment]
I tried it multiple times, with 8GB, according to htop the ram was used max from 60% when it crashed. The crash reason while having more RAM was different:

```
RuntimeError: ansible-inventory failed (rc=250) with stdout: to see the full traceback, use -vvv stderr: ERROR! Unexpected Exception, this is probably a bug:
```
