### ISSUE TITLE
Cryptic error message when ansible-galaxy cannot install roles

### ISSUE THREAD

**Issue by mivanov-its** [ansible/awx#7363]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX produces a cryptic error message when ansible-galaxy cannot install a role.

##### ENVIRONMENT
* AWX version: AWX 7.0.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.4
* Operating System: Linux, SLES 12P4
* Web Browser: Mozilla Firefox

##### STEPS TO REPRODUCE

Create a role without the meta/main.yml file. Import the role in the playbook via the requirements.yml file.

##### EXPECTED RESULTS

This should either work or produce an error message from ansible-galaxy. Ansible-galaxy produces the following output when run manually:

```
[WARNING]: - createServerCert was NOT installed successfully: this role does not appear to have a
meta/main.yml file.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

It produces a warning and threats this as an error. AWX fails then.

##### ACTUAL RESULTS

Error message in AWX:

```
Traceback (most recent call last): File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 1174, in run self.pre_run_hook(self.instance, private_data_dir) File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 1681, in pre_run_hook sync_task.run(local_project_sync.id) File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 685, in _wrapped return f(self, *args, **kwargs) File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 1330, in run raise AwxTaskError.TaskError(self.instance, rc) Exception: project_update 52869 (failed) encountered an error (rc=2), please see task stdout for details. 
```

**Comment by AlanCoding** [comment]
should be sufficiently resolved by @wenottingham's https://github.com/ansible/awx/pull/7194
