### ISSUE TITLE
Remove activity stream entries older than a certain number of days fails

### ISSUE THREAD

**Issue by ssaammoo** [ansible/awx#7403]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Remove activity stream entries older than a certain number of days fails with an error

##### ENVIRONMENT
* AWX version: 12.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.9
* Operating System: CentOS
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Run management job to remove activity stream entries older than a certain number of days 

##### EXPECTED RESULTS

old activity stream entries older than a certain number of days removed

##### ACTUAL RESULTS

` 
```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DiskFull: could not write to tuplestore temporary file: No space left on device
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: could not write to tuplestore temporary file: No space left on device
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 154, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/cleanup_activitystream.py", line 70, in handle
    self.cleanup_activitystream()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/cleanup_activitystream.py", line 44, in cleanup_activitystream
    for asobj in ActivityStream.objects.iterator():
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 341, in _iterator
    yield from self._iterable_class(self, chunked_fetch=use_chunked_fetch, chunk_size=chunk_size)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1143, in execute_sql
    cursor.close()
psycopg2.errors.InvalidCursorName: cursor "_django_curs_140645989772160_1" does not exist

```
 `

##### ADDITIONAL INFORMATION

It is not a disk space issue:

```
# df -kh | grep ansible

/dev/mapper/vg_system-lv_ansible      45G   36G  7.0G  84% /ansible

# cd /ansible/pgdocker/
# du . -sh
23G     .
```

**Comment by ssaammoo** [comment]
I noticed the job would work but it consumes huge disk space and not sure if this is a bug

The size before running the job:

```
# du . -sh
23G
```

The size during running the job:

```
# du . -sh
41G     .
```


Then size is back to original size.

**Comment by wenottingham** [comment]
How many entries do you have in the activity stream?

**Comment by ryanpetrello** [comment]
Hey @ssaammoo,

Do you have any updates on this?  How many entries do you have in the activity stream when you encounter this issue?

**Comment by wenottingham** [comment]
Closing, you can reopen when you have the requested details. To a certain extent, this is how transactional database deletes work, it will consume more space before the transaction finishes.

**Comment by samalv** [comment]
so sorry guys ... I have just missed to reply, I don't know how many entries I have in my activity stream but the last job number I have  is 67988

**Comment by samalv** [comment]
I have 31,849 job :-)
