### ISSUE TITLE
open_fifo_write os.mkfifo  FileExistsError in UI when launching a job

### ISSUE THREAD

**Issue by jijojv** [ansible/awx#7608]
##### ISSUE TYPE
bug

##### SUMMARY
Launching a job in the UI shows the following 
ERROR DETAILS
Traceback (most recent call last): File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1381, in run private_data_files = self.build_private_data_files(self.instance, private_data_dir) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 921, in build_private_data_files ansible_runner.utils.open_fifo_write(path, data.encode()) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/ansible_runner/utils.py", line 362, in open_fifo_write os.mkfifo(path, stat.S_IRUSR | stat.S_IWUSR) FileExistsError: [Errno 17] File exists

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: docker

##### STEPS TO REPRODUCE
launch job template

What's weird is - this is affecting all jobs in one project. Another project's jobs which are coming from the same git repo works fine.

**Comment by jijojv** [comment]
This was an upgrade from a much older AWX and this template had a Source Control type credential associated with it which would be invalid.  Removing that seems to fix this error

**Comment by jakemcdermott** [comment]
Hmm. Yeah. Generally we'd expect no-longer-valid db relationships to resolve on upgrade but they can break from time to time on devel.

It sounds like deleting the credential and/or credential relationship resolved the problem for you so I'm going to close this issue as resolved. Thanks for letting us know.
