### ISSUE TITLE
[ui_next] npm install has to be run twice in certain scenarios

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#7820]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
On my machine, I regularly have to run `npm install` twice to get around an error thrown on the first `npm install`. Note: a second npm install will properly install the dev environment

##### ENVIRONMENT
* AWX version: ui_next
* AWX install method: dev local?
* Ansible version:  2.9
* Operating System: MacOS 10.15.5 (19F101)
* NVM: v10.22.0

##### STEPS TO REPRODUCE
1. `rm -rf node_modules/`
2. `npm install`

##### EXPECTED RESULTS
Install to complete per normal.

##### ACTUAL RESULTS

error shown below

##### ADDITIONAL INFORMATION

```
> fsevents@1.2.13 install /Users/johnhill/github/awx/awx/ui_next/node_modules/webpack-dev-server/node_modules/fsevents
> node install.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:122:20)
    at Object.runInThisContext (vm.js:329:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at evalScript (internal/bootstrap/node.js:590:27)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/johnhill/.nvm/versions/node/v10.22.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Users/johnhill/.nvm/versions/node/v10.22.0/bin/node" "/Users/johnhill/.nvm/versions/node/v10.22.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/johnhill/github/awx/awx/ui_next/node_modules/webpack-dev-server/node_modules/fsevents
gyp ERR! node -v v10.22.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

**Comment by unlikelyzero** [comment]
Have not seen in a long time. Closing
