### ISSUE TITLE
LDAP authentication error

### ISSUE THREAD

**Issue by bit4man** [ansible/awx#7868]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When authenticating against FreeIPA/LDAP the debug log shows it finds the user record, but this is followed by a dump that ends up with: ```TypeError: not all arguments converted during string formatting```

##### ENVIRONMENT
* AWX version: 3.7.0.4
* AWX install method: ansible (setup.sh)
* Ansible version:  2.9.7
* Operating System: RHEL8
* Web Browser: n/a

##### STEPS TO REPRODUCE

After installation, go to the system settings and under LDAP enter URI and other core settings as documented here: https://docs.ansible.com/ansible-tower/latest/html/administration/ldap_auth.html

Log out as admin, and attempt to login with a user from the LDAP source.

Using ldapsearch on the tower host works - can authenticate user and retrieve data from the LDAP registry.

##### EXPECTED RESULTS

Login succeeds.

##### ACTUAL RESULTS

Login fails .... instead a stack-dump is found in the tower.log file.

##### ADDITIONAL INFORMATION

```2020-08-11 04:41:14,206 WARNING  django_auth_ldap not all arguments converted during string formatting while authenticating testuser
2020-08-11 04:41:14,206 ERROR    awx.sso.backends Encountered an error authenticating to LDAP
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/sso/backends.py", line 128, in authenticate
    return super(LDAPBackend, self).authenticate(request, username, password)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 151, in authenticate
    user = self.authenticate_ldap_user(ldap_user, password)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 209, in authenticate_ldap_user
    return ldap_user.authenticate(password)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 353, in authenticate
    self._get_or_create_user()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 622, in _get_or_create_user
    self._populate_user()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 642, in _populate_user
    self._populate_user_from_group_memberships()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 668, in _populate_user_from_group_memberships
    value = query.resolve(self)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django_auth_ldap/config.py", line 671, in resolve
    result = self.aggregator(self._resolve_children(ldap_user, groups))
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django_auth_ldap/config.py", line 699, in _resolve_children
    yield groups.is_member_of(child)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 934, in is_member_of
    is_member = self._group_type.is_member(self._ldap_user, group_dn)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django_auth_ldap/config.py", line 481, in is_member
    group_dn, self.member_attr, ldap_user.dn.encode()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/ldap/ldapobject.py", line 536, in compare_s
    return self.compare_ext_s(dn,attr,value,None,None)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/ldap/ldapobject.py", line 529, in compare_ext_s
    'Compare operation returned wrong result: %r' % (ldap_res)
TypeError: not all arguments converted during string formatting
2020-08-11 04:41:14,300 WARNING  awx.api.generics Login failed for user peter from 192.168.12.15
2020-08-11 04:41:14,307 WARNING  django.request Unauthorized: /api/login/
```

**Comment by ryanpetrello** [comment]
This is a bug in the `python-ldap` library that AWX relies on:

https://github.com/python-ldap/python-ldap/issues/270

**Comment by ryanpetrello** [comment]
Hey @bit4man,

This bug in `python-ldap` will be addressed in the next released version of Ansible AWX.

I suspect that the bug is *actually* disguising a legitimate LDAP configuration issue that you have, but it's hard to say for sure what that might be without functional error messaging.
