### ISSUE TITLE
Migration failure after upgrading image version

### ISSUE THREAD

**Issue by DBLaci** [ansible/awx#800]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - Installer

##### ENVIRONMENT
* AWX version: 1.0.1.316
* AWX install method: docker swarm
* Ansible version:  2.4.x
* Operating System: 
* Web Browser: Chromium

##### STEPS TO REPRODUCE

Changed image version for both awx_web and awx_tasks from 1.0.1.307 to 1.0.1.316

##### EXPECTED RESULTS

Web to work

##### ACTUAL RESULTS

On web got error: migration in progress - wait, and now "working..." only.

##### ADDITIONAL INFORMATION

awx_tasks container starts with this:

```
Using /etc/ansible/ansible.cfg as config file
[DEPRECATION WARNING]: The sudo command line option has been deprecated in 
favor of the "become" command line arguments. This feature will be removed in 
version 2.6. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
127.0.0.1 | SUCCESS => {
    "changed": false, 
    "db": "awx"
}
Operations to perform:
  Apply all migrations: auth, conf, contenttypes, django_celery_results, main, sessions, sites, social_django, sso, taggit
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==1.0.1.316', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/commands/shell.py", line 101, in handle
    exec(sys.stdin.read())
  File "<string>", line 1, in <module>
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/contrib/auth/models.py", line 170, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/contrib/auth/models.py", line 153, in _create_user
    user.save(using=self._db)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 80, in save
    super(AbstractBaseUser, self).save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "auth_user_username_key"
DETAIL:  Key (username)=(admin) already exists.

Instance already registered awx
Instance Group already registered tower
Instance already registered awx
...
```

This is not the first run tough sorry. I checked awx.auth_user table contains only one admin user.

Downgrade to 1.0.1.307 did not solve the problem for me so I am desperate. :)

**Comment by DBLaci** [comment]
I "solved" the problem by entering in the postgres container with

```
$ docker exec -it 123idofpostgres
# sudo - postgres
$ psql
$ \c awx
awx=# update auth_user set username='admin' where username='admin1';
```

At this point I restarted the awx_tasks container and now it is running without the key constraint error.

After this (in the postgres container continuing the above:)
```
update auth_user set username='adminwhy' where username='admin';
update auth_user set username='admin' where username='admin1';
```
And now I can login and everything seems to be fine. I have an additional admin I will delete in the future.

I hope this helps someone. I don't know why a new admin is inserted in the migrate between these versions, I think this is a bug.

**Comment by matburt** [comment]
fwiw this error is innocuous and doesn't cause issues... at some point we probably should silence it, though.
