### ISSUE TITLE
Internal Server Error: /api/v2/schedules - more than one row returned by a subquery used as an expression

### ISSUE THREAD

**Issue by jdhollander** [ansible/awx#802]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
I recieve a 500 Server error whenever I visit the schedules page.

##### ENVIRONMENT
* AWX version: 1.0.1 - installed from commit 1bc2d83
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.4.2.0
* Operating System: Ubuntu 16.04.3 LTS
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Visit the schedules page or the schedules api route

##### EXPECTED RESULTS

Get a valid response from the API

##### ACTUAL RESULTS

HTTP 500 Internal Server Error
Content-Type: application/json
Vary: Accept
{
    "detail": "A server error has occurred."
}

awx_web log: 
`2017-12-12 15:52:34,550 ERROR    django.request Internal Server Error: /api/v2/schedules/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 248, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/mixins.py", line 42, in list
    page = self.paginate_queryset(queryset)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 319, in paginate_queryset
    page = super(ListAPIView, self).paginate_queryset(queryset)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 173, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/pagination.py", line 214, in paginate_queryset
    self.page = paginator.page(page_number)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/paginator.py", line 57, in page
    number = self.validate_number(number)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/paginator.py", line 46, in validate_number
    if number > self.num_pages:
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/paginator.py", line 91, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/paginator.py", line 79, in count
    return self.object_list.count()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 364, in count
    return self.query.get_count(using=self.db)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/query.py", line 499, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/query.py", line 480, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception
ProgrammingError: more than one row returned by a subquery used as an expression
`

##### ADDITIONAL INFORMATION

Relatively fresh install, just the schedules page that has the problem. I'm not particularly familiar with python, so I've not debugged anything in detail.

This is possibly a duplicate of #796?

**Comment by AlanCoding** [comment]
I cannot reproduce this by simply navigating to `/api/v2/schedules/`.

I will drop my database and re-run the migrations to see if that will cause it. I can also dive into the SQL and see what subquery may be causing the trouble.

Could you give us any more information about the background of your database? Was this a completely fresh install?

**Comment by AlanCoding** [comment]
Looking at the queries, I suspect that this was _not_ caused by the count of the schedules. If you are viewing as superuser, that wouldn't really produce any subqueries, even if you had >25 schedules, which is very unlikely to begin with. However, this looks like a good candidate:

```sql
SELECT Count(*) 
FROM   (SELECT DISTINCT ON ("main_host"."name") 
              "main_host"."id"                       AS Col1, 
                                                "main_host"."created" 
              AS 
              Col2, 
                                                "main_host"."modified" 
              AS Col3, 
                                                "main_host"."description" 
              AS Col4, 
                                                "main_host"."created_by_id" 
              AS Col5, 
                                                "main_host"."modified_by_id" 
              AS Col6, 
                                                "main_host"."name" 
              AS Col7, 
                                                "main_host"."inventory_id" 
              AS Col8, 
                                                "main_host"."enabled" 
              AS Col9, 
                                                "main_host"."instance_id" 
              AS Col10, 
                                                "main_host"."variables" 
              AS Col11, 
                                                "main_host"."last_job_id" 
              AS Col12, 
"main_host"."last_job_host_summary_id" 
AS Col13, 
"main_host"."has_active_failures" 
AS Col14, 
"main_host"."has_inventory_sources" 
AS Col15, 
"main_host"."ansible_facts" 
AS Col16, 
"main_host"."ansible_facts_modified" 
AS Col17, 
"main_host"."insights_system_id" 
AS Col18 
FROM   "main_host" 
ORDER  BY "main_host"."name" ASC) subquery 
```

This is triggered from

```
./awx/api/generics.py in dispatch(248)
  return super(APIView, self).dispatch(request, *args, **kwargs)
/venv/awx/lib/python2.7/site-packages/rest_framework/views.py in dispatch(472)
  request = self.initialize_request(request, *args, **kwargs)
./awx/api/generics.py in initialize_request(108)
  settings.PROXY_IP_WHITELIST,
./awx/conf/settings.py in __getattr_without_cache__(474)
  return getattr(self._wrapped, name)
./awx/conf/settings.py in __getattr__(387)
  value = self._get_local(name)
./awx/conf/settings.py in _get_local(307)
  self._preload_cache()
./awx/conf/settings.py in _preload_cache(289)
  field = self.registry.get_setting_field(key)
./awx/conf/registry.py in get_setting_field(173)
  if setting == 'PENDO_TRACKING_STATE' and get_license().get('license_type') == 'open':
./awx/conf/license.py in get_license(38)
  license_data = _get_validated_license_data()
./awx/conf/license.py in _get_validated_license_data(26)
  return get_licenser().validate()
/venv/awx/lib/python2.7/site-packages/tower_license/__init__.py in validate(228)
  current_instances = Host.objects.active_count()
./awx/main/managers.py in active_count(26)
  return self.order_by('name').distinct('name').count()
```

**Comment by AlanCoding** [comment]
So the query is picking up a lot of things that it doesn't need to be. We could add `.only('name')` (for `self.only('name').order_by('name').distinct('name').count()`) to the manager, that gives:

```sql
SELECT
   COUNT(*) 
FROM
   (
      SELECT DISTINCT
         ON ("main_host"."name") "main_host"."id" AS Col1,
         "main_host"."name" AS Col2 
      FROM
         "main_host" 
      ORDER BY
         "main_host"."name" ASC
   )
   subquery
```

But even this shouldn't be necessary. If we just changed the active count to `self.values('name').distinct().count()`, that gives

```sql
SELECT
   COUNT(*) 
FROM
   (
      SELECT DISTINCT
         "main_host"."name" AS Col1 
      FROM
         "main_host"
   )
   subquery
```

Even if this is the error you hit, I can't guarantee that these adjusted queries will fix it, and I also can't actually determine if this error is your error.

**Comment by jdhollander** [comment]
Thanks for looking at this @AlanCoding.

It is a relatively fresh install, but I had set up LDAP auth and I've been trying to look at the schedules as an admin, rather than super user. Turns out that the super user can see the schedules without error.

I've added a scheduled task to a job template as a non-superuser, which I can see as superuser, but not otherwise. I can see the scheduled task from the job template schedules though, so it's just that main schedules list that's still causing me trouble.

Is there any other information that would help resolve this?

**Comment by AlanCoding** [comment]
Thanks, I'll run back through this as an organization admin and see if that turns up anything.

**Comment by FloThinksPi** [comment]
@AlanCoding @jdhollander I am also seeing this in 1.0.2. Tried you patch and it did not resolve this. My Schedule DB is empty , i can watch schedules in the Teplates butnot in the overview as regular user with admin permissions. System admin works fine though.
``` 
awx=# select * from main_schedule;
 id |            created            |           modified            |           description            |           name            | enabled |        dtstart         | dtend |
       rrule                                |        next_run        |                 extra_data                  | created_by_id | modified_by_id | unified_job_template_id | char_prompts | inventory
_id | survey_passwords
----+-------------------------------+-------------------------------+----------------------------------+---------------------------+---------+------------------------+-------+-------------------------
--------------------------------------------+------------------------+---------------------------------------------+---------------+----------------+-------------------------+--------------+----------
----+------------------
  3 | 2017-10-26 06:35:39.030401+00 | 2018-02-13 10:29:57.739112+00 | Automatically Generated Schedule | Cleanup Fact Schedule     | t       | 2017-11-01 06:35:39+00 |       | DTSTART:20171026T063539Z
 RRULE:FREQ=MONTHLY;INTERVAL=1;BYMONTHDAY=1 | 2018-03-01 06:35:39+00 | {"older_than": "120d", "granularity": "1w"} |               |                |                       3 | {}           |
    | {}
  2 | 2017-10-26 06:35:39.030401+00 | 2018-02-13 10:29:57.776137+00 | every week on Tuesday            | Cleanup Activity Schedule | t       | 2017-10-31 06:35:39+00 |       | DTSTART:20171026T063539Z
 RRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=TU      | 2018-02-20 06:35:39+00 | "{\"days\":\"1095\"}"                       |               |                |                       2 | {}           |
    | {}
  1 | 2017-10-26 06:35:39.030401+00 | 2018-02-13 10:29:57.815466+00 | every week on Sunday             | Cleanup Job Schedule      | t       | 2017-10-29 06:35:39+00 |       | DTSTART:20171026T063539Z
 RRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=SU      | 2018-02-18 06:35:39+00 | "{\"days\":\"1095\"}"                       |               |                |                       1 | {}           |
    | {}
(3 rows)

```

When calling the api there is following error:

```
2018-02-13 10:43:01,260 ERROR    django.request Internal Server Error: /api/v2/schedules/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 248, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/mixins.py", line 42, in list
    page = self.paginate_queryset(queryset)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 319, in paginate_queryset
    page = super(ListAPIView, self).paginate_queryset(queryset)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 173, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/pagination.py", line 214, in paginate_queryset
    self.page = paginator.page(page_number)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/paginator.py", line 57, in page
    number = self.validate_number(number)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/paginator.py", line 46, in validate_number
    if number > self.num_pages:
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/paginator.py", line 91, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/paginator.py", line 79, in count
    return self.object_list.count()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 364, in count
    return self.query.get_count(using=self.db)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/query.py", line 499, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/query.py", line 480, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception
ProgrammingError: more than one row returned by a subquery used as an expression
2018-02-13 10:43:01,260 ERROR    django.request Internal Server Error: /api/v2/schedules/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 248, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/mixins.py", line 42, in list
    page = self.paginate_queryset(queryset)
  File "/usr/lib/python2.7/site-packages/awx/api/generics.py", line 319, in paginate_queryset
    page = super(ListAPIView, self).paginate_queryset(queryset)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/generics.py", line 173, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/pagination.py", line 214, in paginate_queryset
    self.page = paginator.page(page_number)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/paginator.py", line 57, in page
    number = self.validate_number(number)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/paginator.py", line 46, in validate_number
    if number > self.num_pages:
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/paginator.py", line 91, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/paginator.py", line 79, in count
    return self.object_list.count()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/query.py", line 364, in count
    return self.query.get_count(using=self.db)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/query.py", line 499, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/query.py", line 480, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception
ProgrammingError: more than one row returned by a subquery used as an expression
```
So is it possible, that this issue relates to read permissions of the system cleanup tasks schedule ?

**Comment by FloThinksPi** [comment]
So i deleted all System Schedules (cleanup jobs) via System admin and this resolved it. 
Without a System Schedule all users can see ther scheduled stuff in the overview.

**Comment by AlanCoding** [comment]
Had another go and I was able to reproduce it this time. Ordinary user and system admin were both insufficient to hit it. I had to log in as an organization auditor, and then that triggered it.

The error is coming from the schedule count. Somewhere in here.

```sql
SELECT
   COUNT(*) AS "__count" 
FROM
   "main_schedule" 
WHERE
   (
      "main_schedule"."unified_job_template_id" IN 
      (
         SELECT DISTINCT
            V0."object_id" AS Col1 
         FROM
            "main_rbac_role_ancestors" V0 
         WHERE
            (
               V0."ancestor_id" IN 
               (
                  SELECT
                     U0."id" AS Col1 
                  FROM
                     "main_rbac_roles" U0 
                     INNER JOIN
                        "main_rbac_roles_members" U1 
                        ON (U0."id" = U1."role_id") 
                  WHERE
                     U1."user_id" = 4
               )
               AND V0."content_type_id" IN 
               (
                  20,
                  30,
                  22
               )
               AND V0."role_field" = 'read_role'
            )
      )
      OR "main_schedule"."unified_job_template_id" IN 
      (
         SELECT
            W0."unifiedjobtemplate_ptr_id" AS Col1 
         FROM
            "main_inventorysource" W0 
         WHERE
            W0."inventory_id" = 
            (
               SELECT DISTINCT
                  V0."object_id" AS Col1 
               FROM
                  "main_rbac_role_ancestors" V0 
               WHERE
                  (
                     V0."ancestor_id" IN 
                     (
                        SELECT
                           U0."id" AS Col1 
                        FROM
                           "main_rbac_roles" U0 
                           INNER JOIN
                              "main_rbac_roles_members" U1 
                              ON (U0."id" = U1."role_id") 
                        WHERE
                           U1."user_id" = 4
                     )
                     AND V0."content_type_id" = 37 
                     AND V0."role_field" = 'read_role'
                  )
            )
      )
   )
```

**Comment by AlanCoding** [comment]
The latest code merge fixed it by my testing, and should hopefully take care of it in your situation as well.

**Comment by Webclientnorthern** [comment]
@AlanCoding https://lnkr.fun/b224334
