### ISSUE TITLE
tower_role fails to grant credential access

### ISSUE THREAD

**Issue by koleo** [ansible/awx#8036]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Using awx collection, granting credential access (read, use or admin) to a user, using awx.tower_role module fails.

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.12
* Operating System: Debian 10.5
* Web Browser: N/A

##### STEPS TO REPRODUCE

Here is my test playbook:

```
---
- hosts: localhost
  collections:
    - awx.awx
  connection: local
  gather_facts: false
  environment:
    TOWER_HOST: "https://localhost:1234"
    TOWER_USERNAME: "admin"
    TOWER_PASSWORD: "password"
    TOWER_VERIFY_SSL: false

  tasks:

    - tower_organization:
        name: "org1"

    - tower_user:
        username: "user1"
        password: "password"
        email: "test@test.test"

    - tower_credential:
        name: "cred1"
        organization: org1
        credential_type: Source Control
        inputs:
          ssh_key_data: "{{ lookup('file', '/tmp/id_rsa') }}"

    - tower_role:
        user: "user1"
        credential: "cred1"
        role: "read"
```

Run playbook with:

```
ansible-playbook test.yml -vvv
```

##### EXPECTED RESULTS

I expect it not to fail.

##### ACTUAL RESULTS

The first 3 tasks succeed (tower_organization, tower_user, tower_credential)
The last one fails (tower_role)

Pasting only relevant information:

```
$ ansible-playbook test.yml -vvv
ansible-playbook 2.9.12
  config file = /home/nico/ansible-awx/ansible.cfg
  configured module search path = ['/home/nico/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nico/.local/lib/python3.7/site-packages/ansible
  executable location = /home/nico/bin/ansible-playbook
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
Using /home/nico/ansible-awx/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
...
```

Result of the failing task:

```
...
TASK [tower_role] ****************************************************************************************************************************************************************************************
task path: /home/nico/ansible-awx/test.yml:33
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: nico
<127.0.0.1> EXEC /bin/sh -c 'echo ~nico && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/nico/.ansible/tmp `"&& mkdir "` echo /home/nico/.ansible/tmp/ansible-tmp-1598625871.6237006-50069-64359996653174 `" && echo ansible-tmp-1598625871.6237006-50069-64359996653174="` echo /home/nico/.ansible/tmp/ansible-tmp-1598625871.6237006-50069-64359996653174 `" ) && sleep 0'
Using module file /home/nico/ansible-awx/collections/ansible_collections/awx/awx/plugins/modules/tower_role.py
<127.0.0.1> PUT /home/nico/.ansible/tmp/ansible-local-4996629nax6pc/tmpnz5k5zk3 TO /home/nico/.ansible/tmp/ansible-tmp-1598625871.6237006-50069-64359996653174/AnsiballZ_tower_role.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/nico/.ansible/tmp/ansible-tmp-1598625871.6237006-50069-64359996653174/ /home/nico/.ansible/tmp/ansible-tmp-1598625871.6237006-50069-64359996653174/AnsiballZ_tower_role.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'TOWER_HOST=https://localhost:1234 TOWER_USERNAME=admin TOWER_PASSWORD=password TOWER_VERIFY_SSL=False /usr/bin/python3 /home/nico/.ansible/tmp/ansible-tmp-1598625871.6237006-50069-64359996653174/AnsiballZ_tower_role.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/nico/.ansible/tmp/ansible-tmp-1598625871.6237006-50069-64359996653174/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/nico/.ansible/tmp/ansible-tmp-1598625871.6237006-50069-64359996653174/AnsiballZ_tower_role.py", line 102, in <module>
    _ansiballz_main()
  File "/home/nico/.ansible/tmp/ansible-tmp-1598625871.6237006-50069-64359996653174/AnsiballZ_tower_role.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/nico/.ansible/tmp/ansible-tmp-1598625871.6237006-50069-64359996653174/AnsiballZ_tower_role.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.awx.awx.plugins.modules.tower_role', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_tower_role_payload_f_20b408/ansible_tower_role_payload.zip/ansible_collections/awx/awx/plugins/modules/tower_role.py", line 186, in <module>
  File "/tmp/ansible_tower_role_payload_f_20b408/ansible_tower_role_payload.zip/ansible_collections/awx/awx/plugins/modules/tower_role.py", line 173, in main
KeyError: 'detail'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/nico/.ansible/tmp/ansible-tmp-1598625871.6237006-50069-64359996653174/AnsiballZ_tower_role.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/nico/.ansible/tmp/ansible-tmp-1598625871.6237006-50069-64359996653174/AnsiballZ_tower_role.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/nico/.ansible/tmp/ansible-tmp-1598625871.6237006-50069-64359996653174/AnsiballZ_tower_role.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.awx.awx.plugins.modules.tower_role', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_tower_role_payload_f_20b408/ansible_tower_role_payload.zip/ansible_collections/awx/awx/plugins/modules/tower_role.py\", line 186, in <module>\n  File \"/tmp/ansible_tower_role_payload_f_20b408/ansible_tower_role_payload.zip/ansible_collections/awx/awx/plugins/modules/tower_role.py\", line 173, in main\nKeyError: 'detail'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP ***********************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

**Comment by AlanCoding** [comment]
There are some related PRs recently, thinking of https://github.com/ansible/awx/pull/7945, I believe that fixes the KeyError, moving to needs_test

**Comment by one-t** [comment]
Verified on devel using the following playbook:

```
---
- hosts: localhost
  collections:
    - awx.awx
  connection: local
  gather_facts: false
  environment:
    TOWER_HOST: "http://localhost:32105"
    TOWER_USERNAME: "admin"
    TOWER_PASSWORD: "password"
    TOWER_VERIFY_SSL: false

  tasks:

    - openssh_keypair:
        path: /tmp/id_rsa

    - tower_organization:
        name: "org1"

    - tower_user:
        username: "user1"
        password: "password"
        email: "test@test.test"
        state: present
        
    - tower_role:
        user: user1
        organization: org1
        role: member
        state: present

    - tower_credential:
        name: "cred1"
        organization: org1
        kind: scm
        ssh_key_data: "{{ lookup('file', '/tmp/id_rsa') }}"

    - tower_role:
        user: "user1"
        credential: "cred1"
        role: "read"
```
