### ISSUE TITLE
Jobs fail to run with 400 error in kubernetes

### ISSUE THREAD

**Issue by Vamxi** [ansible/awx#8214]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
UI has started to bug out and launching a job in the job sections fails with the error provided .
Call to /api/v2/jobs/15148/relaunch/ failed. returned status: 400.
"awx.main.models.ha.MultipleObjectsReturned: get() returned more than one TowerScheduleState -- it returned 2!"
Opening Credentials sections throws a 500 error.

##### ENVIRONMENT
* AWX version: 5.0.0
* AWX install method: helm, kubernetes
* Ansible version:  2.8.1
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Run a job in the job section

##### EXPECTED RESULTS

Job needs to run

##### ACTUAL RESULTS
Logs from awx-task

`2020-09-23 12:38:36,955 DEBUG    awx.main.tasks Starting periodic scheduler
2020-09-23 12:38:36,958 ERROR    awx.main.dispatch Worker failed to run task awx.main.tasks.awx_periodic_scheduler(*[], **{}
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/worker/task.py", line 85, in perform_work
    result = self.run_callable(body)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/dispatch/worker/task.py", line 61, in run_callable
    return _call(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/tasks.py", line 483, in awx_periodic_scheduler
    state = TowerScheduleState.get_solo()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/solo/models.py", line 54, in get_solo
    obj, created = cls.objects.get_or_create(pk=cls.singleton_instance_id)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/query.py", line 384, in get
    (self.model._meta.object_name, num)
awx.main.models.ha.MultipleObjectsReturned: get() returned more than one TowerScheduleState -- it returned 2!`

Jobs fails to run . Also opening credentials in the UI gives a 500 error

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/28507843/94013640-fd681f00-fdc7-11ea-9109-e9c97d16c508.png)

**Comment by ryanpetrello** [comment]
Hey @Vamxi,

This is a fairly old version of AWX, and a _lot_ has changed - I'd recommend upgrading and reporting back if you still continue to see this issue.

Here's a similar older issue that looks like a duplicate - whatever's going on here, it looks like it can be resolved by cleaning up the duplicate row in the table:

https://github.com/ansible/awx/issues/4419#issuecomment-518481399
