### ISSUE TITLE
Task containers no buffer space and all container groups crash afterwards

### ISSUE THREAD

**Issue by ilijamt** [ansible/awx#8327]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When running a playbook that creates jobs that do configure EC2 machines. 

##### ENVIRONMENT
* AWX version: 15.0.0
* AWX install method: k8s (EKS)
* Ansible version:  ansible-runner with Ansible 2.9.13
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

EKS Cluster has: 
* 7 machines (t3.2xlarge)

Playbooks that configure EC2 instances ~100 of them (all of them spin up in a separate container), average runtime per playbook is ~15-20 minutes. 

Task controller

##### EXPECTED RESULTS

All jobs to finish but all jobs running after resources get freed up. 

##### ACTUAL RESULTS

All jobs fail after the error bellow 

```
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/dispatch/worker/callback.py", line 192, in perform_work
    self.flush(force=flush)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/dispatch/worker/callback.py", line 133, in flush
    emit_event_detail(e)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/events.py", line 111, in emit_event_detail
    'task': getattr(event, 'task', ''),
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/consumers.py", line 244, in emit_channel_notification
    "text": wrap_broadcast_msg(group, payload_dumped),
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/consumers.py", line 211, in run_sync
    event_loop.run_until_complete(func)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/channels_redis/core.py", line 707, in group_send
    group_send_lua, keys=channel_redis_keys, args=args
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/aioredis/connection.py", line 186, in _read_data
    obj = await self._reader.readobj()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/aioredis/stream.py", line 102, in readobj
    await self._wait_for_data('readobj')
  File "/usr/lib64/python3.6/asyncio/streams.py", line 464, in _wait_for_data
    yield from self._waiter
  File "/usr/lib64/python3.6/asyncio/selector_events.py", line 752, in write
    n = self._sock.send(data)
OSError: [Errno 105] No buffer space available
```

and then there are a lot of errors of the following.

```
2020-10-06 14:05:29,997 ERROR    awx.main.tasks Failed to delete orphaned pod job 337715 (error) from ansible-2.7-5
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 513, in awx_k8s_reaper
    PodManager(job).delete()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/scheduler/kubernetes.py", line 71, in delete
    _request_timeout=settings.AWX_CONTAINER_GROUP_K8S_API_TIMEOUT)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kubernetes/client/api/core_v1_api.py", line 10173, in delete_namespaced_pod
    (data) = self.delete_namespaced_pod_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kubernetes/client/api/core_v1_api.py", line 10273, in delete_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 345, in call_api
    _preload_content, _request_timeout)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 176, in __call_api
    _request_timeout=_request_timeout)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 411, in request
    body=body)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kubernetes/client/rest.py", line 268, in DELETE
    body=body)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'b50e558c-4c9a-4df6-a6bf-8e46ddee4c49', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 06 Oct 2020 14:05:29 GMT', 'Content-Length': '196'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"awx-job-337715\" not found","reason":"NotFound","details":{"name":"awx-job-337715","kind":"pods"},"code":404}
```

After this all the pending and running jobs are being canceled with the error

```
Task was marked as running in Tower but was not present in the job queue, so it has been marked as failed.
```

##### ADDITIONAL INFORMATION

We use our own custom ansible-runner docker image with some extra libraries installed internally. 
```
selinux~=0.2.1
ansible-tower-cli~=3.3.4
python-memcached~=1.59
psutil~=5.6.3
passlib~=1.7.1
pypsrp~=0.3.1
jmespath~=0.9.4
hvac~=0.9.3
packaging~=18.0
psycopg2~=2.8.3
pykerberos~=1.2.1
requests-kerberos~=0.12.0
datadog~=0.29.3
boto~=2.49.0
boto3~=1.9.186
winrmmanager~=1.1.0
openstacksdk~=0.31.1
kubernetes~=9.0.0
openshift~=0.9.0
```

All jobs run in a separate namespace: 

```
apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limit-range
  namespace: awx-cg
spec:
  limits:
  - default:
      cpu: 2000m
      memory: 4Gi
    defaultRequest:
      cpu: 1500m
      memory: 2Gi
    type: Container
```

A container group runner is 

```
apiVersion: v1
kind: Pod
metadata:
  namespace: awx-cg
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
spec:
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: failure-domain.beta.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
  containers:
    - image: registry/runners:2.10-latest
      tty: true
      stdin: true
      imagePullPolicy: Always
      args:
        - sleep
        - infinity
  imagePullSecrets:
  - name: docker-cfg
```

Container limits:

AWX Web:
```
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
```

AWX Task:
```
          resources:
            requests:
              memory: "4Gi"
              cpu: "3000m"
            limits:
              memory: "6Gi"
              cpu: "5000m"
```

AWX Redis:
```
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "1500m"
```

K8s version
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ilijamt** [comment]
This does not happen if Redis is extracted outside the deployment.
```
OSError: [Errno 105] No buffer space available
```
