### ISSUE TITLE
Python3.6 issue when running job template using AWX-13.0.0

### ISSUE THREAD

**Issue by kt-pham** [ansible/awx#8432]
##### ISSUE TYPE
Job Template fails/not executed due to "project_update failed for production"

##### SUMMARY
Error Message is as follows: 
Traceback (most recent call last): File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1354, in run self.pre_run_hook(self.instance, private_data_dir) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1936, in pre_run_hook sync_task.run(local_project_sync.id) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 779, in _wrapped return f(self, *args, **kwargs) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1518, in run raise AwxTaskError.TaskError(self.instance, rc) Exception: project_update 3230 (failed) encountered an error (rc=2), please see task stdout for details.

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: Ansible for K8s deployment
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE
Deployed into K8s cluster using provided ansible playbook. The job template using slicing (by 5) & forking (by 50), using a template with approximately 125 hosts. I've scaled the instance to 7 pods, since I thought this issue was due to jobs failing when K8s using the HPA feature. 

##### EXPECTED RESULTS

5/5 jobs should be executed and running.

##### ACTUAL RESULTS

There are only 5 jobs (because of the slice), and about 4/5 seem to be on hold (no pending state). These 4 then fail with the above error message, while the other 1 job runs just fine.

**Comment by shanemcd** [comment]
Due to the age of this issue and lack of discussion here, going to assume this is no longer a problem.
