### ISSUE TITLE
Lock cannot be obtained

### ISSUE THREAD

**Issue by Besstheone** [ansible/awx#8448]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
File lock error 

##### ENVIRONMENT
* AWX version: 15.0.0
* AWX install method: docker
* Ansible version:  2.9.13
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

We executed 4632 jobs and there is one that failed with lock file

##### EXPECTED RESULTS

Normal result ( fail or success)

##### ACTUAL RESULTS
```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/gitdb/util.py", line 323, in open
    fd = os.open(self._lockfilepath(), lockmode, int("600", 8))
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/awx/projects/_32__vmware/.git/refs/heads/awx_internal/674a814d-d754-4961-af8d-12103ecc4126.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1376, in run
    self.pre_run_hook(self.instance, private_data_dir)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1948, in pre_run_hook
    RunProjectUpdate.make_local_copy(job.project, private_data_dir, scm_revision=job_revision)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 2362, in make_local_copy
    source_branch = git_repo.create_head(tmp_branch_name, p.scm_revision)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/git/repo/base.py", line 386, in create_head
    return Head.create(self, path, commit, force, logmsg)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/git/refs/symbolic.py", line 543, in create
    return cls._create(repo, path, cls._resolve_ref_on_create, reference, force, logmsg)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/git/refs/symbolic.py", line 510, in _create
    ref.set_reference(target, logmsg)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/git/refs/symbolic.py", line 329, in set_reference
    fd = lfd.open(write=True, stream=True)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/gitdb/util.py", line 330, in open
    raise IOError("Lock at %r could not be obtained" % self._lockfilepath())
OSError: Lock at '/var/lib/awx/projects/_32__vmware/.git/refs/heads/awx_internal/674a814d-d754-4961-af8d-12103ecc4126.lock' could not be obtained
```

##### ADDITIONAL INFORMATION

This job template has been executed at least 600 times,
We got also this error on standalone job template ( not part of a workflow)
This flake can be related to #6119

**Comment by AlanCoding** [comment]
The linked fix made it in 14.1.0, so sounds like you should have that in your environment.

In these cases, when we run `make_local_copy`, we don't hold the exclusive local lock for that project, and if I were to guess from the current information, I would bet that could address this. I have hesitated re-organization to do that, because of the churn it would cause.

I take it that the JT fails, right? If that's the thing we want to address, then a simple retry sounds like the easiest option.

**Comment by woodbb** [comment]
We also just saw the same thing on 15.0.0:

Traceback (most recent call last): File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/gitdb/util.py", line 323, in open fd = os.open(self._lockfilepath(), lockmode, int("600", 8)) FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/awx/projects/_30__awx_project/.git/refs/heads/awx_internal/673e844e-3af0-4508-b815-577ebb9d8838.lock' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1376, in run self.pre_run_hook(self.instance, private_data_dir) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1948, in pre_run_hook RunProjectUpdate.make_local_copy(job.project, private_data_dir, scm_revision=job_revision) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 2362, in make_local_copy source_branch = git_repo.create_head(tmp_branch_name, p.scm_revision) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/git/repo/base.py", line 386, in create_head return Head.create(self, path, commit, force, logmsg) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/git/refs/symbolic.py", line 543, in create return cls._create(repo, path, cls._resolve_ref_on_create, reference, force, logmsg) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/git/refs/symbolic.py", line 510, in _create ref.set_reference(target, logmsg) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/git/refs/symbolic.py", line 329, in set_reference fd = lfd.open(write=True, stream=True) File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/gitdb/util.py", line 330, in open raise IOError("Lock at %r could not be obtained" % self._lockfilepath()) OSError: Lock at '/var/lib/awx/projects/_30__awx_project/.git/refs/heads/awx_internal/673e844e-3af0-4508-b815-577ebb9d8838.lock' could not be obtained

yes, this is on 1 job in a larger workflow.  Relaunching works successfully, btw - but we'd prefer no manual intervention.

**Comment by hsy-go** [comment]
Have you solved it? I also encountered this problem and am looking for a solution
