### ISSUE TITLE
Unable to save a Project

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8470]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Unable to save a Project. Offending commit https://github.com/ansible/awx/commit/5a67aa7fffd063b46cd94b166194413174a5f16c

##### ENVIRONMENT
* AWX version: 5a67aa7fffd063b46cd94b166194413174a5f16c

##### STEPS TO REPRODUCE
1. Try to create a basic Project

##### EXPECTED RESULTS
Save, 200

##### ACTUAL RESULTS
Error, 500

##### ADDITIONAL INFORMATION
https://dashboard.cypress.io/projects/ui2mq7/runs/3135/failures

**Comment by tiagodread** [comment]
Traceback:

```
awx_1       | 2020-10-27 19:38:18,154 ERROR    django.request Internal Server Error: /api/v2/projects/
awx_1       | Traceback (most recent call last):
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
awx_1       |     response = get_response(request)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
awx_1       |     response = self.process_exception_by_middleware(e, request)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
awx_1       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
awx_1       |   File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
awx_1       |     return func(*args, **kwds)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
awx_1       |     return view_func(*args, **kwargs)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
awx_1       |     return self.dispatch(request, *args, **kwargs)
awx_1       |   File "./awx/api/generics.py", line 328, in dispatch
awx_1       |     return super(APIView, self).dispatch(request, *args, **kwargs)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
awx_1       |     response = self.handle_exception(exc)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
awx_1       |     self.raise_uncaught_exception(exc)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
awx_1       |     raise exc
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
awx_1       |     response = handler(request, *args, **kwargs)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/generics.py", line 242, in post
awx_1       |     return self.create(request, *args, **kwargs)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/mixins.py", line 18, in create
awx_1       |     serializer.is_valid(raise_exception=True)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/serializers.py", line 234, in is_valid
awx_1       |     self._validated_data = self.run_validation(self.initial_data)
awx_1       |   File "./awx/api/serializers.py", line 564, in run_validation
awx_1       |     return super(BaseSerializer, self).run_validation(data)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/serializers.py", line 436, in run_validation
awx_1       |     value = self.validate(value)
awx_1       |   File "./awx/api/serializers.py", line 1430, in validate
awx_1       |     return super(ProjectSerializer, self).validate(attrs)
awx_1       |   File "./awx/api/serializers.py", line 1336, in validate
awx_1       |     if scm_type and "local_path" in attrs and self.instance.local_path != attrs['local_path']:
awx_1       | AttributeError: 'NoneType' object has no attribute 'local_path'
awx_1       | 2020-10-27 19:38:18,154 ERROR    django.request Internal Server Error: /api/v2/projects/
awx_1       | Traceback (most recent call last):
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
awx_1       |     response = get_response(request)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
awx_1       |     response = self.process_exception_by_middleware(e, request)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
awx_1       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
awx_1       |   File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
awx_1       |     return func(*args, **kwds)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
awx_1       |     return view_func(*args, **kwargs)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
awx_1       |     return self.dispatch(request, *args, **kwargs)
awx_1       |   File "./awx/api/generics.py", line 328, in dispatch
awx_1       |     return super(APIView, self).dispatch(request, *args, **kwargs)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
awx_1       |     response = self.handle_exception(exc)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
awx_1       |     self.raise_uncaught_exception(exc)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
awx_1       |     raise exc
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
awx_1       |     response = handler(request, *args, **kwargs)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/generics.py", line 242, in post
awx_1       |     return self.create(request, *args, **kwargs)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/mixins.py", line 18, in create
awx_1       |     serializer.is_valid(raise_exception=True)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/serializers.py", line 234, in is_valid
awx_1       |     self._validated_data = self.run_validation(self.initial_data)
awx_1       |   File "./awx/api/serializers.py", line 564, in run_validation
awx_1       |     return super(BaseSerializer, self).run_validation(data)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/serializers.py", line 436, in run_validation
awx_1       |     value = self.validate(value)
awx_1       |   File "./awx/api/serializers.py", line 1430, in validate
awx_1       |     return super(ProjectSerializer, self).validate(attrs)
awx_1       |   File "./awx/api/serializers.py", line 1336, in validate
awx_1       |     if scm_type and "local_path" in attrs and self.instance.local_path != attrs['local_path']:
awx_1       | AttributeError: 'NoneType' object has no attribute 'local_path'
```

**Comment by ryanpetrello** [comment]
Fix: https://github.com/ansible/awx/pull/8471

**Comment by unlikelyzero** [comment]
Covered by project-crud.spec.js
