### ISSUE TITLE
Azure Resource Manager Plugin unknown

### ISSUE THREAD

**Issue by u849296** [ansible/awx#8500]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using the Azure Resource Manager plugin I am getting plugin unknown:

File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/auto.py", line 53, in parse
    raise AnsibleParserError("inventory config '{0}' specifies unknown plugin '{1}'".format(path, plugin_name))

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: openshift
* Ansible version:  1.9.14
* Operating System: Openshift
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Rerun azure resource manager job
##### EXPECTED RESULTS

parse our inventory in azure without plugin errors
##### ACTUAL RESULTS
Job output:
 2.254 INFO     Updating inventory 3: Azure SS
    2.269 INFO     Reading Ansible inventory source: /tmp/awx_8_0dsaftb5/azure_rm.yml
    2.271 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    2.271 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    2.271 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 154, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1142, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1032, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 208, in load
    return self.command_to_json(base_args + ['--list'])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 191, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.9.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Using /etc/ansible/ansible.cfg as config file
[WARNING]:  * Failed to parse /tmp/awx_8_0dsaftb5/azure_rm.yml with auto
plugin: inventory config '/tmp/awx_8_0dsaftb5/azure_rm.yml' specifies unknown
plugin 'azure.azcollection.azure_rm'
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/auto.py", line 53, in parse
    raise AnsibleParserError("inventory config '{0}' specifies unknown plugin '{1}'".format(path, plugin_name))
[WARNING]: Unable to parse /tmp/awx_8_0dsaftb5/azure_rm.yml as an inventory
source
ERROR! No inventory was parsed, please check your configuration and options.

**Comment by wenottingham** [comment]
Did you install using the AWX operator?

**Comment by u849296** [comment]
Yes I did.

**Comment by wenottingham** [comment]
-> https://github.com/ansible/awx-operator/issues/36
