### ISSUE TITLE
Attempting to delete a workflow approval template results in 500 error

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#8501]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
<img width="1148" alt="Screen Shot 2020-10-30 at 11 16 35 AM" src="https://user-images.githubusercontent.com/9889020/97722929-94985480-1aa1-11eb-9f42-21eac7c2003f.png">

See the bottom of the issue for full traceback.

##### STEPS TO REPRODUCE
1. Create a workflow
2. Create a workflow approval node
3. Save workflow
4. Attempt to delete the created workflow approval template via the API browser

##### EXPECTED RESULTS
Successful delete (?)

##### ACTUAL RESULTS
Error

##### ADDITIONAL INFORMATION
Full error:

```
awx_1       | 2020-10-30 15:16:33,114 ERROR    django.request Internal Server Error: /api/v2/workflow_approval_templates/16/
awx_1       | Traceback (most recent call last):
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
awx_1       |     response = get_response(request)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
awx_1       |     response = self.process_exception_by_middleware(e, request)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
awx_1       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
awx_1       |   File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
awx_1       |     return func(*args, **kwds)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
awx_1       |     return view_func(*args, **kwargs)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
awx_1       |     return self.dispatch(request, *args, **kwargs)
awx_1       |   File "./awx/api/generics.py", line 328, in dispatch
awx_1       |     return super(APIView, self).dispatch(request, *args, **kwargs)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
awx_1       |     response = self.handle_exception(exc)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
awx_1       |     self.raise_uncaught_exception(exc)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
awx_1       |     raise exc
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
awx_1       |     response = handler(request, *args, **kwargs)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/generics.py", line 217, in delete
awx_1       |     return self.destroy(request, *args, **kwargs)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/mixins.py", line 91, in destroy
awx_1       |     self.perform_destroy(instance)
awx_1       |   File "./awx/api/views/mixin.py", line 141, in perform_destroy
awx_1       |     self.check_related_active_jobs(obj)
awx_1       |   File "./awx/api/views/mixin.py", line 145, in check_related_active_jobs
awx_1       |     active_jobs = obj.get_active_jobs()
awx_1       | AttributeError: 'WorkflowApprovalTemplate' object has no attribute 'get_active_jobs'
awx_1       | 2020-10-30 15:16:33,114 ERROR    django.request Internal Server Error: /api/v2/workflow_approval_templates/16/
awx_1       | Traceback (most recent call last):
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
awx_1       |     response = get_response(request)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
awx_1       |     response = self.process_exception_by_middleware(e, request)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
awx_1       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
awx_1       |   File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
awx_1       |     return func(*args, **kwds)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
awx_1       |     return view_func(*args, **kwargs)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
awx_1       |     return self.dispatch(request, *args, **kwargs)
awx_1       |   File "./awx/api/generics.py", line 328, in dispatch
awx_1       |     return super(APIView, self).dispatch(request, *args, **kwargs)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
awx_1       |     response = self.handle_exception(exc)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
awx_1       |     self.raise_uncaught_exception(exc)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
awx_1       |     raise exc
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
awx_1       |     response = handler(request, *args, **kwargs)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/generics.py", line 217, in delete
awx_1       |     return self.destroy(request, *args, **kwargs)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/mixins.py", line 91, in destroy
awx_1       |     self.perform_destroy(instance)
awx_1       |   File "./awx/api/views/mixin.py", line 141, in perform_destroy
awx_1       |     self.check_related_active_jobs(obj)
awx_1       |   File "./awx/api/views/mixin.py", line 145, in check_related_active_jobs
awx_1       |     active_jobs = obj.get_active_jobs()
awx_1       | AttributeError: 'WorkflowApprovalTemplate' object has no attribute 'get_active_jobs'
awx_1       | 172.18.0.1 DELETE /api/v2/workflow_approval_templates/16/ - HTTP/1.1 500
```

**Comment by akus062381** [comment]
I verified that this has been fixed.
