### ISSUE TITLE
AWX 15.0.1 - custom-venv with ansible 2.10 is not working

### ISSUE THREAD

**Issue by MarcusCaepio** [ansible/awx#8543]
Hi all,
Since 2 days I am trying to install ansible 2.10.2 as custom-venv in AWX on a fresh Ubuntu 20.04.1 for a local docker installation, to start migrating my playbooks to the FQCNs based on the docs at 
https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md 
The custom-venv is mounted into the awx container, but executing ansible in the container leads to

```
Traceback (most recent call last):
  File "/opt/my-envs/custom-venv/bin/ansible", line 34, in <module>
    from ansible import context
ModuleNotFoundError: No module named 'ansible'
```
Here are the steps to reproduce.
OS: Ubuntu 20.04.1 

- Install ansible via pip3, as there are is no ppa for ubuntu 20 atm. with pip install, there is no ansible.cfg and I created one, because it seems to be necessary for AWX to work correctly in finding inventories, roles, etc.
```
root@ansible:~# ansible --version
ansible 2.10.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

- create a virtual env, like it is described in the docs:
```
root@ansible:~# mkdir /opt/my-envs
root@ansible:~# chmod 0755 /opt/my-envs/
root@ansible:~# python3 -m venv /opt/my-envs/custom-venv
root@ansible:~# /opt/my-envs/custom-venv/bin/pip install psutil
Processing ./.cache/pip/wheels/f6/59/c2/38111ef4c354088a156bc95fbeb5396c0cac91a0f62f7158b9/psutil-5.7.3-cp38-cp38-linux_x86_64.whl
Installing collected packages: psutil
Successfully installed psutil-5.7.3
root@ansible:~# /opt/my-envs/custom-venv/bin/pip install -U "ansible == 2.10.2"
Processing ./.cache/pip/wheels/50/25/f3/6e20493741ea59a7ba96169202aba6824689e8f34576de3aaa/ansible-2.10.2-py3-none-any.whl
Processing ./.cache/pip/wheels/cb/f5/61/a226fbdb73687e5e8988c7485cc004e557e6b881565060ba62/ansible_base-2.10.3-py3-none-any.whl
Processing ./.cache/pip/wheels/13/90/db/290ab3a34f2ef0b5a0f89235dc2d40fea83e77de84ed2dc05c/PyYAML-5.3.1-cp38-cp38-linux_x86_64.whl
Collecting jinja2
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting packaging
  Using cached packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting cryptography
  Using cached cryptography-3.2.1-cp35-abi3-manylinux2010_x86_64.whl (2.6 MB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl (32 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting cffi!=1.11.3,>=1.8
  Using cached cffi-1.14.3-cp38-cp38-manylinux1_x86_64.whl (410 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Installing collected packages: PyYAML, MarkupSafe, jinja2, six, pyparsing, packaging, pycparser, cffi, cryptography, ansible-base, ansible
Successfully installed MarkupSafe-1.1.1 PyYAML-5.3.1 ansible-2.10.2 ansible-base-2.10.3 cffi-1.14.3 cryptography-3.2.1 jinja2-2.11.2 packaging-20.4 pycparser-2.20 pyparsing-2.4.7 six-1.15.0
```
Running ansible in the custom-venv looks good:
```
root@ansible:~# /opt/my-envs/custom-venv/bin/ansible --version
ansible 2.10.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/my-envs/custom-venv/lib/python3.8/site-packages/ansible
  executable location = /opt/my-envs/custom-venv/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```
Edit the awx-15.0.1/installer/inventory file to mount the custom-venv
`custom_venv_dir=/opt/my-envs/`

Build the container:
`root@ansible:~/awx-15.0.1/installer# ansible-playbook -i inventory install.ym`l
[...]
```
PLAY RECAP ********************************************************************************************************************************************************************************************
localhost                  : ok=40   changed=20   unreachable=0    failed=0    skipped=66   rescued=0    ignored=0
root@ansible:~/awx-15.0.1/installer# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                         NAMES
b00ff7b0589f        awx:15.0.1          "/usr/bin/tini -- /u…"   3 minutes ago       Up 3 minutes        8052/tcp                                      awx_task
f4128f9b8810        awx:15.0.1          "/usr/bin/tini -- /b…"   3 minutes ago       Up 3 minutes        0.0.0.0:80->8052/tcp, 0.0.0.0:443->8053/tcp   awx_web
3c24b1a9535d        redis               "docker-entrypoint.s…"   2 hours ago         Up 3 minutes        6379/tcp                                      awx_redis
adb6ef5a25cf        postgres:10         "docker-entrypoint.s…"   2 hours ago         Up 3 minutes        5432/tcp                                      awx_postgres

```
jump into e.g. awx_task and try to run ansible in the venv
```
root@ansible:~/awx-15.0.1/installer# docker exec -it awx_task /bin/bash
bash-4.4# /opt/my-envs/custom-venv/bin/ansible --version
Traceback (most recent call last):
  File "/opt/my-envs/custom-venv/bin/ansible", line 34, in <module>
    from ansible import context
ModuleNotFoundError: No module named 'ansible'

```

The only working dirty workaround is, to delete and re-install the venv in both awx_web and awx_task
```
bash-4.4# rm -r /opt/my-envs/custom-venv
bash-4.4# python3 -m venv /opt/my-envs/custom-venv
bash-4.4# yum install gcc
CentOS-8 - AppStream                                                                                                                                                    11 MB/s | 5.8 MB     00:00
CentOS-8 - Base                                                                                                                                                        2.8 MB/s | 2.2 MB     00:00
CentOS-8 - Extras                                                                                                                                                       92 kB/s | 8.1 kB     00:00
CentOS-8 - PowerTools                                                                                                                                                   12 MB/s | 1.9 MB     00:00
Extra Packages for Enterprise Linux Modular 8 - x86_64                                                                                                                 187 kB/s |  97 kB     00:00
Extra Packages for Enterprise Linux 8 - x86_64                                                                                                                          21 MB/s | 8.3 MB     00:00
Dependencies resolved.
=======================================================================================================================================================================================================
 Package                                           Architecture                             Version                                                  Repository                                   Size
=======================================================================================================================================================================================================
Installing:
 gcc                                               x86_64                                   8.3.1-5.el8.0.2                                          AppStream                                    23 M
Installing dependencies:
 cpp                                               x86_64                                   8.3.1-5.el8.0.2                                          AppStream                                    10 M
 glibc-devel                                       x86_64                                   2.28-101.el8                                             BaseOS                                      1.0 M
 glibc-headers                                     x86_64                                   2.28-101.el8                                             BaseOS                                      473 k
 isl                                               x86_64                                   0.16.1-6.el8                                             AppStream                                   841 k
 kernel-headers                                    x86_64                                   4.18.0-193.28.1.el8_2                                    BaseOS                                      4.0 M
 libgomp                                           x86_64                                   8.3.1-5.el8.0.2                                          BaseOS                                      203 k
 libmpc                                            x86_64                                   1.0.2-9.el8                                              AppStream                                    59 k
 libxcrypt-devel                                   x86_64                                   4.1.1-4.el8                                              BaseOS                                       25 k

Transaction Summary
=======================================================================================================================================================================================================
Install  9 Packages

Total download size: 40 M
Installed size: 99 M
Is this ok [y/N]: y
Downloading Packages:
(1/9): isl-0.16.1-6.el8.x86_64.rpm                                                                                                                                     6.6 MB/s | 841 kB     00:00
(2/9): libmpc-1.0.2-9.el8.x86_64.rpm                                                                                                                                   3.3 MB/s |  59 kB     00:00
(3/9): glibc-devel-2.28-101.el8.x86_64.rpm                                                                                                                             7.8 MB/s | 1.0 MB     00:00
(4/9): cpp-8.3.1-5.el8.0.2.x86_64.rpm                                                                                                                                   33 MB/s |  10 MB     00:00
(5/9): glibc-headers-2.28-101.el8.x86_64.rpm                                                                                                                           3.7 MB/s | 473 kB     00:00
(6/9): libgomp-8.3.1-5.el8.0.2.x86_64.rpm                                                                                                                              3.5 MB/s | 203 kB     00:00
(7/9): libxcrypt-devel-4.1.1-4.el8.x86_64.rpm                                                                                                                          551 kB/s |  25 kB     00:00
(8/9): kernel-headers-4.18.0-193.28.1.el8_2.x86_64.rpm                                                                                                                  16 MB/s | 4.0 MB     00:00
(9/9): gcc-8.3.1-5.el8.0.2.x86_64.rpm                                                                                                                                   27 MB/s |  23 MB     00:00
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                   35 MB/s |  40 MB     00:01
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                               1/1
  Installing       : libmpc-1.0.2-9.el8.x86_64                                                                                                                                                     1/9
  Running scriptlet: libmpc-1.0.2-9.el8.x86_64                                                                                                                                                     1/9
  Installing       : cpp-8.3.1-5.el8.0.2.x86_64                                                                                                                                                    2/9
  Running scriptlet: cpp-8.3.1-5.el8.0.2.x86_64                                                                                                                                                    2/9
  Installing       : libgomp-8.3.1-5.el8.0.2.x86_64                                                                                                                                                3/9
  Running scriptlet: libgomp-8.3.1-5.el8.0.2.x86_64                                                                                                                                                3/9
  Installing       : kernel-headers-4.18.0-193.28.1.el8_2.x86_64                                                                                                                                   4/9
  Running scriptlet: glibc-headers-2.28-101.el8.x86_64                                                                                                                                             5/9
  Installing       : glibc-headers-2.28-101.el8.x86_64                                                                                                                                             5/9
  Installing       : libxcrypt-devel-4.1.1-4.el8.x86_64                                                                                                                                            6/9
  Installing       : glibc-devel-2.28-101.el8.x86_64                                                                                                                                               7/9
  Running scriptlet: glibc-devel-2.28-101.el8.x86_64                                                                                                                                               7/9
  Installing       : isl-0.16.1-6.el8.x86_64                                                                                                                                                       8/9
  Running scriptlet: isl-0.16.1-6.el8.x86_64                                                                                                                                                       8/9
  Installing       : gcc-8.3.1-5.el8.0.2.x86_64                                                                                                                                                    9/9
  Running scriptlet: gcc-8.3.1-5.el8.0.2.x86_64                                                                                                                                                    9/9
  Verifying        : cpp-8.3.1-5.el8.0.2.x86_64                                                                                                                                                    1/9
  Verifying        : gcc-8.3.1-5.el8.0.2.x86_64                                                                                                                                                    2/9
  Verifying        : isl-0.16.1-6.el8.x86_64                                                                                                                                                       3/9
  Verifying        : libmpc-1.0.2-9.el8.x86_64                                                                                                                                                     4/9
  Verifying        : glibc-devel-2.28-101.el8.x86_64                                                                                                                                               5/9
  Verifying        : glibc-headers-2.28-101.el8.x86_64                                                                                                                                             6/9
  Verifying        : kernel-headers-4.18.0-193.28.1.el8_2.x86_64                                                                                                                                   7/9
  Verifying        : libgomp-8.3.1-5.el8.0.2.x86_64                                                                                                                                                8/9
  Verifying        : libxcrypt-devel-4.1.1-4.el8.x86_64                                                                                                                                            9/9

Installed:
  cpp-8.3.1-5.el8.0.2.x86_64     gcc-8.3.1-5.el8.0.2.x86_64 glibc-devel-2.28-101.el8.x86_64    glibc-headers-2.28-101.el8.x86_64 isl-0.16.1-6.el8.x86_64 kernel-headers-4.18.0-193.28.1.el8_2.x86_64
  libgomp-8.3.1-5.el8.0.2.x86_64 libmpc-1.0.2-9.el8.x86_64  libxcrypt-devel-4.1.1-4.el8.x86_64

Complete!
bash-4.4# /opt/my-envs/custom-venv/bin/pip install psutil
Collecting psutil
  Using cached https://files.pythonhosted.org/packages/33/e0/82d459af36bda999f82c7ea86c67610591cf5556168f48fd6509e5fa154d/psutil-5.7.3.tar.gz
Installing collected packages: psutil
  Running setup.py install for psutil ... done
Successfully installed psutil-5.7.3
You are using pip version 9.0.3, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
bash-4.4# /opt/my-envs/custom-venv/bin/pip install ansible
Collecting ansible
  Downloading https://files.pythonhosted.org/packages/f2/8f/09054d2e2bf4eaa1754956e08b5fae1b0e51089e620e50438e501d83eda1/ansible-2.10.2.tar.gz (40.6MB)
    100% |████████████████████████████████| 40.6MB 30kB/s
Collecting ansible-base<2.11,>=2.10.3 (from ansible)
  Downloading https://files.pythonhosted.org/packages/2e/d1/92422f8f53ae2d4e75ebdc2be2186a9ca2796b5d9679f20ed0239e86d8cf/ansible-base-2.10.3.tar.gz (5.8MB)
    100% |████████████████████████████████| 5.8MB 214kB/s
Collecting jinja2 (from ansible-base<2.11,>=2.10.3->ansible)
  Downloading https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl (125kB)
    100% |████████████████████████████████| 133kB 7.4MB/s
Collecting PyYAML (from ansible-base<2.11,>=2.10.3->ansible)
  Downloading https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz (269kB)
    100% |████████████████████████████████| 276kB 3.9MB/s
Collecting cryptography (from ansible-base<2.11,>=2.10.3->ansible)
  Downloading https://files.pythonhosted.org/packages/08/31/c43f1e45b4a5ebac13ff038a3f167ba3c7432f6dc8683ea504f5af9265eb/cryptography-3.2.1-cp35-abi3-manylinux1_x86_64.whl (2.6MB)
    100% |████████████████████████████████| 2.7MB 453kB/s
Collecting packaging (from ansible-base<2.11,>=2.10.3->ansible)
  Downloading https://files.pythonhosted.org/packages/46/19/c5ab91b1b05cfe63cccd5cfc971db9214c6dd6ced54e33c30d5af1d2bc43/packaging-20.4-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from jinja2->ansible-base<2.11,>=2.10.3->ansible)
  Downloading https://files.pythonhosted.org/packages/b2/5f/23e0023be6bb885d00ffbefad2942bc51a620328ee910f64abe5a8d18dd1/MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography->ansible-base<2.11,>=2.10.3->ansible)
  Downloading https://files.pythonhosted.org/packages/50/ca/bbca0fd95b24a1d4f0d2e016f09f35ae68d4fe72bf34cc538d0a0d2d3e10/cffi-1.14.3-cp36-cp36m-manylinux1_x86_64.whl (400kB)
    100% |████████████████████████████████| 409kB 3.0MB/s
Collecting six>=1.4.1 (from cryptography->ansible-base<2.11,>=2.10.3->ansible)
  Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging->ansible-base<2.11,>=2.10.3->ansible)
  Downloading https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl (67kB)
    100% |████████████████████████████████| 71kB 9.1MB/s
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography->ansible-base<2.11,>=2.10.3->ansible)
  Downloading https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl (112kB)
    100% |████████████████████████████████| 112kB 8.5MB/s
Installing collected packages: MarkupSafe, jinja2, PyYAML, pycparser, cffi, six, cryptography, pyparsing, packaging, ansible-base, ansible
  Running setup.py install for PyYAML ... done
  Running setup.py install for ansible-base ... done
  Running setup.py install for ansible ... done
Successfully installed MarkupSafe-1.1.1 PyYAML-5.3.1 ansible-2.10.2 ansible-base-2.10.3 cffi-1.14.3 cryptography-3.2.1 jinja2-2.11.2 packaging-20.4 pycparser-2.20 pyparsing-2.4.7 six-1.15.0
You are using pip version 9.0.3, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
bash-4.4# /opt/my-envs/custom-venv/bin/ansible --version
ansible 2.10.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/my-envs/custom-venv/lib64/python3.6/site-packages/ansible
  executable location = /opt/my-envs/custom-venv/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```
I also tried to edit the Makefile and the /installer/roles/image_build/templates/Dockerfile.j2 as decribed in the docs.
The COPY part in the Dockerfile.j2 lead to a build crash, the Makefile addition does nothing in the container.

Either I am doing sth. wrong, the docs are not correct or the build is not working correctly atm. 
Kindly asking for help here, as rebuild the virtual-env in the container after every awx update is not really satisfying. 

Thanks in advance!
Cheers,
Marcus

**Comment by blomquisg** [comment]
@MarcusCaepio Please take this to the AWX mailing list https://groups.google.com/g/awx-project.
