### ISSUE TITLE
Error "credential types request failed" when editing template

### ISSUE THREAD

**Issue by mensler** [ansible/awx#8578]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When opening a template edit page I get the error message "credential types request failed. GET returned status: 500 A server error has occurred." in a popup:
![screenshot-awx nonprod eu2 sofort klarna net-2020 11 12-16_37_29](https://user-images.githubusercontent.com/6129516/98961034-684ef000-2505-11eb-8480-05907a9a8f2f.png)

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version: 2.9.15
* Operating System: CentOS 7 (server), Ubuntu 20.04 (client)
* Web Browser: Chromium 86.0.4240.183

##### STEPS TO REPRODUCE

Not reproducable in a fresh installation, so I guess it might be an upgrade problem (last upgraded from 15.0.0, I'm not sure since when the problem exists in both our installations).
The error occurs directly after the template edit page loaded

##### EXPECTED RESULTS

Click on the link to a job template, the edit page opens, no error, credentials are shown in the "Credentials" field.

##### ACTUAL RESULTS

The error message pops up, the "Credentials" field is empty, no credentials dialog opens when the "Credentials" magnifier is clicked.

##### ADDITIONAL INFORMATION

The URL returning the 500 internal server error is: .../api/v2/credential_types/?page_size=200

Logs of the awx_web Docker container show the following exceptions:

```
2020-11-12 15:33:03,631 ERROR    django.request Internal Server Error: /api/v2/credential_types/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/generics.py", line 328, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/pagination.py", line 62, in paginate_queryset
    return super(Pagination, self).paginate_queryset(queryset, request, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/pagination.py", line 218, in paginate_queryset
    return list(self.page)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/paginator.py", line 150, in __len__
    return len(self.object_list)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 73, in __iter__
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/credential/__init__.py", line 372, in from_db
    native = ManagedCredentialType.registry[instance.namespace]
KeyError: 'cloudforms'
2020-11-12 15:33:03,631 ERROR    django.request Internal Server Error: /api/v2/credential_types/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/generics.py", line 328, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/pagination.py", line 62, in paginate_queryset
    return super(Pagination, self).paginate_queryset(queryset, request, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/pagination.py", line 218, in paginate_queryset
    return list(self.page)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/paginator.py", line 150, in __len__
    return len(self.object_list)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 73, in __iter__
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/credential/__init__.py", line 372, in from_db
    native = ManagedCredentialType.registry[instance.namespace]
KeyError: 'cloudforms'
10.236.21.83 - - [12/Nov/2020:15:33:03 +0000] "GET /api/v2/credential_types/?page_size=200 HTTP/1.1" 500 41 ...
```

**Comment by wenottingham** [comment]
You need https://github.com/ansible/awx/pull/8567
