### ISSUE TITLE
AWX Crashes when it encounters a 404

### ISSUE THREAD

**Issue by LavaToaster** [ansible/awx#862]
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
AWX Crashes when it encounters a 404.

##### ENVIRONMENT
* AWX version: 1.0.2 (also tested on latest devel)
* AWX install method: docker on linux
* Ansible version:  Unsure, not really relevant though.
* Operating System: Linux
* Web Browser: Not relevant as long as it can send a HTTP request.

##### STEPS TO REPRODUCE

Go to any invalid url like /404

##### EXPECTED RESULTS

It should give me a 404 page

##### ACTUAL RESULTS

It actually crashes.

##### ADDITIONAL INFORMATION

```
2017-12-19 11:30:12,216 ERROR    django.request Internal Server Error: /crash
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 116, in get_exception_response
    response = callback(request, **param_dict)
  File "/usr/lib/python2.7/site-packages/awx/main/views.py", line 80, in handle_404
    return handle_error(request, 404, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/views.py", line 56, in handle_error
    return render(request, 'error.html', kwargs, status=status)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/defaulttags.py", line 40, in render
    output = self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/defaulttags.py", line 166, in render
    values = self.sequence.resolve(context, True)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 736, in resolve
    new_obj = func(obj, *arg_vals)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/templatetags/rest_framework.py", line 244, in items
    return value.items()
AttributeError: 'NoneType' object has no attribute 'items'
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 53, in response_for_exception
    response = get_exception_response(request, get_resolver(get_urlconf()), 404, exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 119, in get_exception_response
    response = handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 143, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/usr/lib/python2.7/site-packages/awx/main/views.py", line 88, in handle_500
    return handle_error(request, 500, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/views.py", line 56, in handle_error
    return render(request, 'error.html', kwargs, status=status)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
2017/12/19 11:30:12 [error] 24#0: *37717 upstream prematurely closed connection while reading response header from upstream, client: 172.16.34.20, server: _, request: "GET /crash HTTP/1.1", upstream: "uwsgi://127.0.0.1:8050", host: "therewasahostherebutiremovedit.com"
```

**Comment by AlanCoding** [comment]
I can't directly reproduce this. I just get `2017-12-19 14:21:34,400 WARNING  django.request Not Found: /crash/`

**Comment by LavaToaster** [comment]
@AlanCoding Alrighty, I just did the following test as I had posted this issue from seeing it on our server here and after confirming if someone else saw it in IRC.

To reproduce on my "local" machine - I did the following: 
- Full AWX setup in Vagrant via: https://github.com/geerlingguy/ansible-vagrant-examples/tree/master/awx
- Waited for AWX to finish setting up.
- Whilst this was going on I went on it to confirm what version I was using, by `vagrant ssh`'ing into the box, and doing `sudo -s`, `cd /root/awx`, `git log` and saw that the latest commit was https://github.com/ansible/awx/commit/f7259a1e784bee2ebbd5c92a13a1623fb6ef2769 on `devel` branch.
- Once login page is shown, open a new tab and go to`/crash` or `/anypathyouwant`. You should get a 502 bad gateway back immediately, and refreshing the login page will also return a 502 bad gateway. 

Note: AWX starts back up after this type of crash within 10 seconds.

**Comment by LavaToaster** [comment]
Hey @AlanCoding, is there any more information you need from me? 

This bug causes our AWX server to go down daily due to an internal automated security (via AL Cloud Insight) scan which tries out unknown paths.

**Comment by matburt** [comment]
The vagrant install is not officially supported by the AWX team. We'd need to see a reproducer on our standalone install and like @AlanCoding I'm also not able to reproduce it there.

**Comment by LavaToaster** [comment]
I used vagrant as an example of being able reproduce it, I wasn't asking for support on it, it happens on our AWS server which runs AWX, and provisioned using the docker on linux that is provided here.

How would be the best way to get a reproducer for you?

**Comment by Abukamel** [comment]
I have the same problem on a server deployed using docker.
```bash
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 53, in response_for_exception
    response = get_exception_response(request, get_resolver(get_urlconf()), 404, exc)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 119, in get_exception_response
    response = handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/handlers/exception.py", line 143, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/usr/lib/python2.7/site-packages/awx/main/views.py", line 88, in handle_500
    return handle_error(request, 500, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/views.py", line 56, in handle_error
    return render(request, 'error.html', kwargs, status=status)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/defaulttags.py", line 40, in render
    output = self.nodelist.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/defaulttags.py", line 166, in render
    values = self.sequence.resolve(context, True)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/template/base.py", line 736, in resolve
    new_obj = func(obj, *arg_vals)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/templatetags/rest_framework.py", line 244, in items
    return value.items()
AttributeError: 'NoneType' object has no attribute 'items'
2018/01/14 07:07:57 [error] 26#0: *140 upstream prematurely closed connection while reading response header from upstream, client: 172.17.0.1, server: _, request: "GET /robots.txt HTTP/1.1", upstream: "uwsgi://127.0.0.1:8050", host: ""
2018/01/14 07:07:57 [warn] 26#0: *140 upstream server temporarily disabled while reading response header from upstream, client: 172.17.0.1, server: _, request: "GET /robots.txt HTTP/1.1", upstream: "uwsgi://127.0.0.1:8050", host: ""
```

![error screen shot](http://storage4.static.itmages.com/i/18/0114/h_1515913876_6774264_2839c9b02a.jpeg)

**Comment by davidflam** [comment]
Hi,

Same problem here, AWX is crashing when encountering 404. AWX is installed on a physical Ubuntu 16.04 LTS server with Docker 1.12.6. 

We have a monitoring agent that queries http://<server>:8052/nginx_status. Since nginx_status is not enabled in the default AWX docker install, nginx will return 404 and will crash AWX web ui. Solved by enabling nginx_status (see https://easyengine.io/tutorials/nginx/status-page/) or disabling monitoring agent.

**Comment by Cryptophobia** [comment]
I am having the same error appear on a K8s deployment using the latest image.
