### ISSUE TITLE
playbook could not be found with workflow and scm

### ISSUE THREAD

**Issue by chris93111** [ansible/awx#8755]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
sometime at start workflow job failed immediately with playbook could not be found
next try the same job run perfectly

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker
* Ansible version:  2.8.7
* Operating System: redhat
* Web Browser: chrome

##### STEPS TO REPRODUCE

workflow with multiple jobs same stage

##### EXPECTED RESULTS

work perfectly

##### ACTUAL RESULTS

many job fail at start

##### ADDITIONAL INFORMATION

job as scm configured
in workflow screen 2 failed job with playbook could not be found

![image](https://user-images.githubusercontent.com/27526373/101196095-976a0480-3660-11eb-93c8-577c4b6b4c1c.png)

**Comment by chris93111** [comment]
i found this in task 

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1523, in run
    self.post_run_hook(self.instance, status)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 2422, in post_run_hook
    self.make_local_copy(instance, self.job_private_data_dir)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 2367, in make_local_copy
    depth=1, single_branch=True,  # shallow, do not copy full history
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/git/repo/base.py", line 1019, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/git/repo/base.py", line 960, in _clone
    finalize_process(proc, stderr=stderr)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/git/util.py", line 328, in finalize_process
    proc.wait(**kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/git/cmd.py", line 408, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --branch=awx_internal/c75e02c7-ca92-4758-b06d-909c65e42ab2 --depth=1 --single-branch -v file:///var/lib/awx/projects/_76__iac /tmp/awx_69619_92py3ond/project
  stderr: 'Cloning into '/tmp/awx_69619_92py3ond/project'...
error: --shallow-file died of signal 9
error: git upload-pack: git-pack-objects died with error.
fatal: git upload-pack: aborting due to possible repository corruption on the remote side.
remote: aborting due to possible repository corruption on the remote side.
fatal: early EOF
fatal: index-pack failed

in kernel 

Dec  4 18:29:27 vldvaawx04-web kernel: Task in /system.slice/docker-3373896696bd2444084d18f2b5521e22302c067042d2b95edec4a20fa3928f36.scope killed as a result of limit of /system.slice/docker-3373896696bd2444084d18f2b5521e22302c067042d2b95edec4a20fa3928f36.scope
Dec  4 18:29:27 vldvaawx04-web kernel: memory: usage 2046992kB, limit 2048000kB, failcnt 61614
Dec  4 18:29:27 vldvaawx04-web kernel: memory+swap: usage 2048000kB, limit 2048000kB, failcnt 3955736
Dec  4 18:29:27 vldvaawx04-web kernel: kmem: usage 0kB, limit 9007199254740988kB, failcnt 0
Dec  4 18:29:27 vldvaawx04-web kernel: Memory cgroup stats for /system.slice/docker-3373896696bd2444084d18f2b5521e22302c067042d2b95edec4a20fa3928f36.scope: cache:216KB rss:2046776KB rss_huge:0KB mapped_file:96KB swap:1008KB inactive_anon:822616KB active_anon:1224312KB inactive_file:0KB active_file:0KB unevictable:0KB
Dec  4 18:29:27 vldvaawx04-web kernel: [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
Dec  4 18:29:27 vldvaawx04-web kernel: [48810]  1000 48810     1082       84       8       14             0 tini
Dec  4 18:29:27 vldvaawx04-web kernel: [48850]  1000 48850     9463      500      24       72             0 bash
Dec  4 18:29:27 vldvaawx04-web kernel: [50276]  1000 50276    26568     5031      57      191             0 supervisord
Dec  4 18:29:27 vldvaawx04-web kernel: [50322]  1000 50322    20792     3480      44        0             0 python3
Dec  4 18:29:27 vldvaawx04-web kernel: [50323]  1000 50323   264501    34646     189        0             0 awx-manage
Dec  4 18:29:27 vldvaawx04-web kernel: [50324]  1000 50324    77199    30872     154        0             0 awx-manage
Dec  4 18:29:27 vldvaawx04-web kernel: [50416]  1000 50416    86264    33135     171        0             0 awx-manage
Dec  4 18:29:27 vldvaawx04-web kernel: [50417]  1000 50417    86365    33236     169        0             0 awx-manage
Dec  4 18:29:27 vldvaawx04-web kernel: [50418]  1000 50418    86214    33078     169        0             0 awx-manage
Dec  4 18:29:27 vldvaawx04-web kernel: [50419]  1000 50419    86273    33128     170        0             0 awx-manage
Dec  4 18:29:27 vldvaawx04-web kernel: [50421]  1000 50421    76964    29076     144        0             0 awx-manage
Dec  4 18:29:27 vldvaawx04-web kernel: [122092]  1000 122092   262041    34836     187        0             0 awx-manage
Dec  4 18:29:27 vldvaawx04-web kernel: [ 4202]  1000  4202   261857    34513     185        0             0 awx-manage
Dec  4 18:29:27 vldvaawx04-web kernel: [54824]  1000 54824   265208    33671     187        0             0 awx-manage
Dec  4 18:29:27 vldvaawx04-web kernel: [58604]  1000 58604   265431    33791     187        0             0 awx-manage
Dec  4 18:29:27 vldvaawx04-web kernel: [19154]  1000 19154     5821      492      17        0             0 git
Dec  4 18:29:27 vldvaawx04-web kernel: [19694]  1000 19694     5833      492      16        0             0 git
Dec  4 18:29:27 vldvaawx04-web kernel: [19695]  1000 19695     7814      563      17        0             0 git
Dec  4 18:29:27 vldvaawx04-web kernel: [19696]  1000 19696     6476      567      17        0             0 git-upload-pack
Dec  4 18:29:27 vldvaawx04-web kernel: [19697]  1000 19697     6289      532      18        0             0 git
Dec  4 18:29:27 vldvaawx04-web kernel: [19699]  1000 19699   418252   164371     469        0             0 git
Dec  4 18:29:27 vldvaawx04-web kernel: [19700]  1000 19700     5765      429      15        0             0 git
Dec  4 18:29:27 vldvaawx04-web kernel: [19701]  1000 19701     7814      564      16        0             0 git
Dec  4 18:29:27 vldvaawx04-web kernel: [19702]  1000 19702    22098      543      16        0             0 git-upload-pack
Dec  4 18:29:27 vldvaawx04-web kernel: [19703]  1000 19703   375821   149298     444        0             0 git
Dec  4 18:29:27 vldvaawx04-web kernel: [19705]  1000 19705     5765      430      15        0             0 git
Dec  4 18:29:27 vldvaawx04-web kernel: Memory cgroup out of memory: Kill process 19720 (git) score 321 or sacrifice child
Dec  4 18:29:27 vldvaawx04-web kernel: Killed process 19699 (git) total-vm:1673008kB, anon-rss:655556kB, file-rss:1928kB, shmem-rss:0kB

**Comment by chris93111** [comment]
it's ok , the problem is in nomad with limitation memory for docker
