### ISSUE TITLE
Missing basic installation instructions

### ISSUE THREAD

**Issue by jlagermann** [ansible/awx#8895]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The README.md says to review the Install guide.  In the Install guide, the first step of the Getting started instructions is to Clone the repo.  The last part of that step says to, 

> "_Once you have a local copy, run commands within the root of the project tree._ "[https://github.com/ansible/awx/blob/devel/INSTALL.md#getting-started](url)

However, the root of the project tree does not contain any commands.
```
/awx$ ls -la
total 252
drwxrwxr-x 12 root root  4096 Dec 14 13:45 .
drwxr-xr-x 10 root root  4096 Dec 14 14:32 ..
-rw-rw-r--  1 root root   602 Dec 14 13:45 .coveragerc
-rw-rw-r--  1 root root    25 Dec 14 13:45 .dockerignore
-rw-rw-r--  1 root root    50 Dec 14 13:45 .env
drwxrwxr-x  8 root root  4096 Dec 14 13:45 .git
drwxrwxr-x  3 root root  4096 Dec 14 13:45 .github
-rw-rw-r--  1 root root  2042 Dec 14 13:45 .gitignore
-rw-rw-r--  1 root root   230 Dec 14 13:45 .yamllint
-rw-rw-r--  1 root root  2566 Dec 14 13:45 API_STANDARDS.md
-rw-rw-r--  1 root root 38155 Dec 14 13:45 CHANGELOG.md
-rw-rw-r--  1 root root 18083 Dec 14 13:45 CONTRIBUTING.md
-rw-rw-r--  1 root root   385 Dec 14 13:45 DATA_MIGRATION.md
-rw-rw-r--  1 root root  1620 Dec 14 13:45 DCO_1_1.md
-rw-rw-r--  1 root root 31577 Dec 14 13:45 INSTALL.md
-rw-rw-r--  1 root root  5138 Dec 14 13:45 ISSUES.md
-rw-rw-r--  1 root root  9304 Dec 14 13:45 LICENSE.md
-rw-rw-r--  1 root root  1097 Dec 14 13:45 MANIFEST.in
-rw-rw-r--  1 root root 22865 Dec 14 13:45 Makefile
-rw-rw-r--  1 root root  2683 Dec 14 13:45 README.md
-rw-rw-r--  1 root root     7 Dec 14 13:45 VERSION
drwxrwxr-x 14 root root  4096 Dec 14 13:45 awx
drwxrwxr-x  8 root root  4096 Dec 14 13:45 awx_collection
drwxrwxr-x  4 root root  4096 Dec 14 13:45 awxkit
drwxrwxr-x  2 root root  4096 Dec 14 13:45 config
drwxrwxr-x  8 root root  4096 Dec 14 13:45 docs
drwxrwxr-x  3 root root  4096 Dec 14 13:45 installer
-rwxrwxr-x  1 root root   149 Dec 14 13:45 manage.py
-rw-rw-r--  1 root root   497 Dec 14 13:45 pytest.ini
drwxrwxr-x  2 root root  4096 Dec 14 13:45 requirements
-rwxrwxr-x  1 root root  1223 Dec 14 13:45 setup.cfg
-rwxrwxr-x  1 root root  5382 Dec 14 13:45 setup.py
drwxrwxr-x 12 root root  4096 Dec 14 13:45 tools
-rw-rw-r--  1 root root   120 Dec 14 13:45 tox.ini
```

The three files with executable permissions do not do anything on their own.

```
/awx$ ./manage.py
Traceback (most recent call last):
  File "./manage.py", line 7, in <module>
    from awx import manage
  File "/etc/corelight-env/awx/awx/__init__.py", line 11, in <module>
    __version__ = get_distribution('awx').version
  File "/etc/corelight-env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 465, in get_distribution
    dist = get_provider(dist)
  File "/etc/corelight-env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 341, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/etc/corelight-env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/etc/corelight-env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'awx' distribution was not found and is required by the application

/awx$ ./setup.cfg
./setup.cfg: line 1: [pep8]: command not found
./setup.cfg: line 18: [flake8]: command not found
./setup.cfg: line 19: max-line-length=160: command not found

/awx$ ./setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```
##### ENVIRONMENT
All of the prerequisites listed in the INSTALL.md have been met with the following commands:

```
git clone -b 16.0.0 https://github.com/ansible/awx.git
git clone https://github.com/ansible/awx-logos.git

sudo apt-get update
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io

python3 -m pip install --upgrade docker

ansible-galaxy collection install community.general

curl http://ftp.gnu.org/gnu/make/make-4.3.tar.gz -o make-4.3.tar.gz
sudo tar -zxf make-4.3.tar.gz
cd make-4.3
configure
build.sh
```

**Comment by wenottingham** [comment]
I think you're misreading that. "run commands within the root of the project tree" means "run all the commands mentioned in the following sections from the root of your checkout tree". As an example, the commands mentioned in https://github.com/ansible/awx/blob/devel/INSTALL.md#run-the-installer-2

**Comment by jlagermann** [comment]
That makes a lot more sense.  It sounds like an easy documentation fix.  I would suggest the docs be updated with "run all the commands mentioned in the following sections from the root of your project/checkout tree".

**Comment by jakemcdermott** [comment]
https://github.com/ansible/awx/pull/8900

**Comment by jakemcdermott** [comment]
:wave: This is now addressed by https://github.com/ansible/awx/pull/8900. The doc updates are on the devel branch now and they'll be included with the next awx release.
