### ISSUE TITLE
Issue on a scheduled job - Error spawning scheduled job.

### ISSUE THREAD

**Issue by zdriic** [ansible/awx#9029]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Job remains pending with the status "NEW"

##### ENVIRONMENT
* AWX version: 9.3.0
* AWX install method: docker on linux
* Ansible version:  2.9.5
* Operating System: Ubuntu
* Web Browser: Firefox

**External DB on SLES12 and DBaaS**

##### STEPS TO REPRODUCE

From AWX, I scheduled a job to update an inventory (dynamic via python script) but this job sometimes remains pending with the status NEW and nothing happens until I restart the job manually.

Job scheduled every day at 02:00am

Have you ever had this case or do you have an idea how to fix it?

##### EXPECTED RESULTS

Inventory updated through the job scheduler

##### ACTUAL RESULTS

Job remains pending with the status "NEW"

- Log in awx_task : 

OKREADY
2021-01-07 01:00:02,121 DEBUG    awx.main.dispatch publish awx.main.tasks.awx_periodic_scheduler(40f82900-0dd4-471c-8223-99c10193d5bf, queue=awx_private_queue)
2021-01-07 01:00:02,141 DEBUG    awx.main.dispatch task 40f82900-0dd4-471c-8223-99c10193d5bf starting awx.main.tasks.awx_periodic_scheduler(*[])
2021-01-07 01:00:02,160 DEBUG    awx.main.tasks Starting periodic scheduler
**2021-01-07 01:00:02,169 DEBUG    awx.main.tasks Last scheduler run was: 2021-01-07 00:59:32.067443+00:00
2021-01-07 01:00:02,339 ERROR    awx.main.tasks Error spawning scheduled job.**
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 529, in awx_periodic_scheduler
    new_unified_job = schedule.unified_job_template.create_unified_job(**job_kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/inventory.py", line 1374, in create_unified_job
    return super(InventorySource, self).create_unified_job(**kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/unified_jobs.py", line 389, in create_unified_job
    unified_job.save()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/unified_jobs.py", line 856, in save
    result = super(UnifiedJob, self).save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/polymorphic/models.py", line 93, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/base.py", line 213, in save
    self.save(update_fields=update_fields)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/unified_jobs.py", line 805, in save
    self_before = self.__class__.objects.get(pk=self.pk)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
**awx.main.models.inventory.InventoryUpdate.DoesNotExist: InventoryUpdate matching query does not exist.**
2021-01-07 01:00:12,147 DEBUG    awx.main.dispatch publish awx.main.scheduler.tasks.run_task_manager(62cb89e4-2146-41cf-9ab8-1d74c51b6c75, queue=awx_private_queue)
2021-01-07 01:00:12,163 DEBUG    awx.main.dispatch task 62cb89e4-2146-41cf-9ab8-1d74c51b6c75 starting awx.main.scheduler.tasks.run_task_manager(*[])
2021-01-07 01:00:12,165 DEBUG    awx.main.scheduler Running Tower task manager.
2021-01-07 01:00:12,185 DEBUG    awx.main.scheduler Starting Scheduler
2021-01-07 01:00:32,185 DEBUG    awx.main.dispatch publish awx.main.tasks.cluster_node_heartbeat(0f332f03-b58d-45b5-9af1-2d9f1b40fd33, queue=awx)
2021-01-07 01:00:32,377 DEBUG    awx.main.dispatch publish awx.main.tasks.awx_k8s_reaper(d00e94a8-cd56-499b-8451-44502fc3e42b, queue=awx)
2021-01-07 01:00:32,388 DEBUG    awx.main.dispatch task 0f332f03-b58d-45b5-9af1-2d9f1b40fd33 starting awx.main.tasks.cluster_node_heartbeat(*[])
2021-01-07 01:00:32,390 DEBUG    awx.main.tasks Cluster node heartbeat task.
2021-01-07 01:00:32,393 DEBUG    awx.main.dispatch publish awx.main.tasks.awx_periodic_scheduler(8aef3f5c-b07a-4baf-a973-c617dea854d8, queue=awx_private_queue)
2021-01-07 01:00:32,393 DEBUG    awx.main.dispatch task d00e94a8-cd56-499b-8451-44502fc3e42b starting awx.main.tasks.awx_k8s_reaper(*[])
2021-01-07 01:00:32,407 DEBUG    awx.main.dispatch publish awx.main.scheduler.tasks.run_task_manager(8fd5284a-13b7-4196-9c10-ecec61a848fa, queue=awx_private_queue)
2021-01-07 01:00:32,407 DEBUG    awx.main.dispatch task 8aef3f5c-b07a-4baf-a973-c617dea854d8 starting awx.main.tasks.awx_periodic_scheduler(*[])
2021-01-07 01:00:32,420 DEBUG    awx.main.dispatch task 8fd5284a-13b7-4196-9c10-ecec61a848fa starting awx.main.scheduler.tasks.run_task_manager(*[])
2021-01-07 01:00:32,421 DEBUG    awx.main.scheduler Running Tower task manager.
2021-01-07 01:00:32,434 DEBUG    awx.main.tasks Starting periodic scheduler
2021-01-07 01:00:32,438 DEBUG    awx.main.scheduler Starting Scheduler
2021-01-07 01:00:32,447 DEBUG    awx.main.tasks Last scheduler run was: 2021-01-07 01:00:02.160924+00:00
2021-01-07 01:00:52,432 DEBUG    awx.main.dispatch publish awx.main.scheduler.tasks.run_task_manager(d3ec2511-b180-46a2-bae5-e6b4dcb27b7b, queue=awx_private_queue)
2021-01-07 01:00:52,448 DEBUG    awx.main.dispatch task d3ec2511-b180-46a2-bae5-e6b4dcb27b7b starting awx.main.scheduler.tasks.run_task_manager(*[])
2021-01-07 01:00:52,449 DEBUG    awx.main.scheduler Running Tower task manager.
2021-01-07 01:00:52,473 DEBUG    awx.main.scheduler Starting Scheduler
RESULT 2
OKREADY

**Comment by wenottingham** [comment]
Apologies, but AWX 9.x is very old, and we do not fix issues with older releases. Can you reproduce this behavior on AWX 16?

**Comment by zdriic** [comment]
I'm still using the latest version of AWX 9.3.0 with rabbitmq because as soon as we tested AWX with reddis and an external DBaaS, we had problems running the jobs (see 7253 ) but I don't think this job scheduling issue is due to the rabbitmq (maybe I'm wrong ! :-) )

**Comment by ryanpetrello** [comment]
What @wenottingham said - give this a whirl on a newer version and let us know if you still encounter issues - thanks!
