### ISSUE TITLE
AWX fails to sync Projects and Job output is unavailable.

### ISSUE THREAD

**Issue by kannurkars** [ansible/awx#9117]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Everything works well except the cloning/Syncing project from git.
When I execute this from UI PROJECT the **Job-status fails with "No Route to host error"**,but **I see all my playbooks/roles and collections are available/getting updated in /var/lib/awx/project/_15__git_projects directory.**

Even I can see Playbooks in templates but sync status shows as failed.
This is what I get in Job-status. because of this, I am unable to trigger my Job templates even though Playbooks are available.

```
> TASK [update project using git] ***************************************
> [fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin 'https://$encrypted$:$encrypted$@<URL>' /var/lib/awx/projects/_15__git_projects", "msg": "Cloning into '/var/lib/awx/projects/_15__git_projects'...\nfatal: unable to access 'https://<URL>': **Failed to connect to <URL> port 443: No route to host", "rc": 128, "stderr":** "Cloning into '/var/lib/awx/projects/_15__git_projects'...\nfatal: unable to access '<URL>': Failed to connect to <URL> port 443: **No route to host**\n", "stderr_lines": ["Cloning into '/var/lib/awx/projects/_15__git_projects'...", "fatal: unable to access 'h<URL>': Failed to connect to <URL> port 443: **No route to host"**], "stdout": "", "stdout_lines": []}
```

to confirm this I tried cloning from docker instance as well and connectivity to my git is fine.

```

# docker exec -it awx_web bash

bash-4.4# /usr/bin/git clone --origin origin '<URL>'
Cloning into 'awx_roles'...
Username for '': s.a.awxro.user01
Password for ''':
remote: Enumerating objects: 217, done.
remote: Counting objects: 100% (217/217), done.
remote: Compressing objects: 100% (124/124), done.
remote: Total 217 (delta 33), reused 195 (delta 26), pack-reused 0
Receiving objects: 100% (217/217), 49.24 KiB | 1.37 MiB/s, done.
Resolving deltas: 100% (33/33), done.
```

I don't have any more hair to rip out over this.

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux, External PG database version 10.
* Ansible version:  2.9.15
* Proxy: Tested with Proxy and without proxy. 
* Web Browser: Chrome / Firefox

##### EXPECTED RESULTS
Project Sync job should be successful. and we should see job output in api/v2/project_updates/110/
##### ACTUAL RESULTS
Job-status shows Failed and api/v2/project_updates/110/ shows 
```
HTTP 500 Internal Server Error
Content-Type: application/json
Vary: Accept

{
    "detail": "A server error has occurred."
}
```
but api/v2/project_updates/110/stdout/  show availble output. (attached in screeenshot as well)

```
PLAY [Update source tree if necessary] *****************************************

PLAY [Update source tree if necessary] *****************************************

TASK [update project using git] ************************************************

TASK [update project using git] ************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin 'https://$encrypted$:$encrypted$@<URL>/infraops/awx_roles.git' /var/lib/awx/projects/_17__git_projects", "msg": "Cloning into '/var/lib/awx/projects/_17__git_projects'...\\nfatal: unable to access 'https://<URL>/infraops/awx_roles.git/': Failed to connect to <URL> port 443: No route to host", "rc": 128, "stderr": "Cloning into '/var/lib/awx/projects/_17__git_projects'...\\nfatal: unable to access 'https://<URL>/infraops/awx_roles.git/': Failed to connect to <URL> port 443: No route to host\\n", "stderr_lines": ["Cloning into '/var/lib/awx/projects/_17__git_projects'...", "fatal: unable to access 'https://<URL>/infraops/awx_roles.git/': Failed to connect to <URL> port 443: No route to host"], "stdout": "", "stdout_lines": []}
changed: [localhost]

TASK [Set the git repository version] ******************************************

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

ok: [localhost]

TASK [Repository Version] ******************************************************
ok: [localhost] => {
    "msg": "Repository Version 448d1b40d2431cbdb7ba318c11f98b32ea32c20c"
}

PLAY [Install content with ansible-galaxy command if necessary] ****************

TASK [detect roles/requirements.(yml/yaml)] ************************************
skipping: [localhost] => (item={'ext': '.yml'}) 
skipping: [localhost] => (item={'ext': '.yaml'}) 

TASK [fetch galaxy roles from requirements.(yml/yaml)] *************************
skipping: [localhost] => (item={'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False', 'item': {'ext': '.yml'}, 'ansible_loop_var': 'item'}) 
skipping: [localhost] => (item={'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False', 'item': {'ext': '.yaml'}, 'ansible_loop_var': 'item'}) 

TASK [detect collections/requirements.(yml/yaml)] ******************************
skipping: [localhost] => (item={'ext': '.yml'}) 
skipping: [localhost] => (item={'ext': '.yaml'}) 

TASK [fetch galaxy collections from collections/requirements.(yml/yaml)] *******
skipping: [localhost] => (item={'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False', 'item': {'ext': '.yml'}, 'ansible_loop_var': 'item'}) 
skipping: [localhost] => (item={'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False', 'item': {'ext': '.yaml'}, 'ansible_loop_var': 'item'}) 

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0  
```

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/48320754/105531658-ab042400-5d0f-11eb-893c-43e919051031.png)

![image](https://user-images.githubusercontent.com/48320754/105531677-b35c5f00-5d0f-11eb-87f1-9e974ffafd66.png)

**Comment by wenottingham** [comment]
Do you have the actual traceback from the 500 in the logs?

**Comment by kannurkars** [comment]
> Do you have the actual traceback from the 500 in the logs?

can you please guide me, which logs will be helpful?

**Comment by wenottingham** [comment]
It would be in the container logs themselves

**Comment by kannurkars** [comment]
> It would be in the container logs themselves

not sure if I am posting the correct logs here; please guide me what exactly can help? as i see everything empty 
nothing in /var/log/messages /var/log/tower or nginx.
This is what I get from docker logs -f awx_task
```
2021-01-22 19:40:27,951 DEBUG    awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-01-22 19:40:27,951 DEBUG    awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-01-22 19:40:27,955 DEBUG    awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-01-22 19:40:27,955 DEBUG    awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-01-22 19:40:28,199 DEBUG    awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(2)
2021-01-22 19:40:28,199 DEBUG    awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(2)
2021-01-22 19:40:28,206 DEBUG    awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-01-22 19:40:28,206 DEBUG    awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-01-22 19:40:28,209 DEBUG    awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-01-22 19:40:28,209 DEBUG    awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-01-22 19:40:28,213 DEBUG    awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-01-22 19:40:28,213 DEBUG    awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-01-22 19:40:28,419 INFO     awx.main.commands.run_callback_receiver Event processing is finished for Job 121, sending notifications
2021-01-22 19:40:28,419 INFO     awx.main.commands.run_callback_receiver Event processing is finished for Job 121, sending notifications
2021-01-22 19:40:28,420 DEBUG    awx.main.tasks project_update 121 (failed) finished running, producing 33 events.
2021-01-22 19:40:28,439 DEBUG    awx.main.dispatch task e8fc717a-2b37-4d8a-93a2-defd5ab90143 starting awx.main.tasks.handle_success_and_failure_notifications(*[121])
2021-01-22 19:40:28,465 DEBUG    awx.main.commands.run_callback_receiver 119 is alive
2021-01-22 19:40:28,465 DEBUG    awx.main.commands.run_callback_receiver 119 is alive
2021-01-22 19:40:30,109 DEBUG    awx.main.tasks project_update 121 (failed) wrote to cache at /var/lib/awx/projects/.__awx_cache/_17__git_projects/121
2021-01-22 19:40:30,204 DEBUG    awx.main.dispatch task a3f77297-95c4-41af-90e8-571bcb126d67 starting awx.main.tasks.handle_work_success(*[])
2021-01-22 19:40:30,213 DEBUG    awx.main.dispatch task 46b86931-e573-4e72-a948-0e76d35fb6f6 starting awx.main.scheduler.tasks.run_task_manager(*[])
```

**Comment by wenottingham** [comment]
That is not far enough back. You'd want the logs from awx_web from when you get the 500 accessing the project_update.

**Comment by kannurkars** [comment]
> That is not far enough back. You'd want the logs from awx_web from when you get the 500 accessing the project_update.

Here we go:
```
`2021-01-22 20:30:57,949 ERROR    django.request Internal Server Error: /api/v2/project_updates/121/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/generics.py", line 328, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/generics.py", line 208, in get
    return self.retrieve(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/serializers.py", line 799, in to_representation
    ret = super(UnifiedJobSerializer, self).to_representation(obj)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/fields.py", line 1870, in to_representation
     return method(value)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/serializers.py", line 1519, in get_host_status_counts
    counts = obj.project_update_events.only('event_data').get(event='playbook_on_stats').get_host_status_counts()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 412, in get
    (self.model._meta.object_name, num)
awx.main.models.events.ProjectUpdateEvent.MultipleObjectsReturned: get() returned more than one ProjectUpdateEvent -- it returned 2!
2021-01-22 20:30:57,949 ERROR    django.request Internal Server Error: /api/v2/project_updates/121/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/generics.py", line 328, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/generics.py", line 208, in get
    return self.retrieve(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/serializers.py", line 799, in to_representation
    ret = super(UnifiedJobSerializer, self).to_representation(obj)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/fields.py", line 1870, in to_representation
    return method(value)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/serializers.py", line 1519, in get_host_status_counts
    counts = obj.project_update_events.only('event_data').get(event='playbook_on_stats').get_host_status_counts()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 412, in get
    (self.model._meta.object_name, num)
awx.main.models.events.ProjectUpdateEvent.MultipleObjectsReturned: get() returned more than one ProjectUpdateEvent -- it returned 2!
ERROR:django.request:Internal Server Error: /api/v2/project_updates/121/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/generics.py", line 328, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/generics.py", line 208, in get
    return self.retrieve(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/serializers.py", line 799, in to_representation
    ret = super(UnifiedJobSerializer, self).to_representation(obj)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/rest_framework/fields.py", line 1870, in to_representation
    return method(value)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/serializers.py", line 1519, in get_host_status_counts
    counts = obj.project_update_events.only('event_data').get(event='playbook_on_stats').get_host_status_counts()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 412, in get
    (self.model._meta.object_name, num)
awx.main.models.events.ProjectUpdateEvent.MultipleObjectsReturned: get() returned more than one ProjectUpdateEvent -- it returned 2!
[pid: 93|app: 0|req: 124/303] 10.184.250.29 () {46 vars in 2301 bytes} [Fri Jan 22 20:30:57 2021] GET /api/v2/project_updates/121/ => generated 12025 bytes in 86 msecs (HTTP/1.1 500) 7 headers in 330 bytes (1 switches on core 0)
10.184.250.29 - - [22/Jan/2021:20:30:57 +0000] "GET /api/v2/project_updates/121/ HTTP/1.1" 500 12025 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" "-"
2021/01/22 20:30:57 [error] 90#0: *2401 open() "/var/lib/awx/public/static/assets/logo-header.svg" failed (2: No such file or directory), client: 10.184.250.29, server: _, request: "GET /static/assets/logo-header.svg HTTP/1.1", host: "<URL>", referrer: "http://<URL>/api/v2/project_updates/121/"
10.184.250.29 - - [22/Jan/2021:20:30:57 +0000] "GET /static/assets/logo-header.svg HTTP/1.1" 404 564 "http://<URL>/api/v2/project_updates/121/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" "-"`
```

**Comment by kannurkars** [comment]
> That is not far enough back. You'd want the logs from awx_web from when you get the 500 accessing the project_update.

Anyways!! What about **No route to Host** Error? Why I am getting this even though contents are available? (screenshot added in original issue)

**Comment by wenottingham** [comment]
Unsure, presumably something off in the container networking. The odder thing is why the project update didn't fail overall.

**Comment by kannurkars** [comment]
> Unsure, presumably something off in the container networking. The odder thing is why the project update didn't fail overall.

I checked containers networking thoroughly, before bringing things here. Plus I am getting everything on the local disk; which means my instance is able to reach the repo, able to log in, and fetch the data (including revision update), and write it on the disk still the status says it's failed. 

TIA

**Comment by kannurkars** [comment]
after some more digging, it tuned out the culprit is  `get_host_status_counts()`. I had accidentally installed a second instance for the same DB. Thanks to #7253. lets see if this works for me.

**Comment by blomquisg** [comment]
Reopen if that didn't fix your issue.
