### ISSUE TITLE
Container Group Pods terminating - Exception occurred while running task

### ISSUE THREAD

**Issue by hurdigurdi** [ansible/awx#9404]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Container Group Pods terminating - Exception occurred while running task

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.17
* Operating System: MacOs (frontent)
* Web Browser: Chrome

##### STEPS TO REPRODUCE

* Define Container Groups in K8s
* schedule job with large inventory (~1000-2000 hosts)

##### EXPECTED RESULTS

Job should complete, showing success or error.

##### ACTUAL RESULTS

Job-Pod is terminated. 
Entry in awx-task container:
```
2021-02-24 09:38:57,500 ERROR    awx.main.tasks job 389 (running) Exception occurred while running task
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 1507, in run
    ident=str(self.instance.pk))
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/isolated/manager.py", line 424, in run
    status, rc = self.check()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/isolated/manager.py", line 261, in check
    rc = int(f.readline())
ValueError: invalid literal for int() with base 10: 'None'
2021-02-24 09:38:57,503 DEBUG    awx.main.tasks job 389 (running) finished running, producing 1238 events.
2021-02-24 09:38:57,567 DEBUG    awx.main.tasks Deleting pod awx-job-389
2021-02-24 09:38:57,607 DEBUG    awx.main.dispatch task 42f97dcd-86e4-49df-8918-68216924a5ec starting awx.main.tasks.update_inventory_computed_fields(*[3])
2021-02-24 09:38:57,622 DEBUG    awx.main.models.inventory Going to update inventory computed fields, pk=3
```

##### ADDITIONAL INFORMATION

Jobs run fine using same Container Group using smaller inventories or when limiting it.

**Comment by hurdigurdi** [comment]
Update to this issue:

it appears this is being caused by a resource bottleneck on the K8s Cluster, which leads to the rsyncs exceeding the AWX_ISOLATED_CHECK_INTERVAL.

We applied following changes:
* migrate K8s nodes running Container Groups to nodes with more available vCPUs
* extend AWX_ISOLATED_CHECK_INTERVAL to 60 seconds
* introduce CPU resource limits in Container Group Pod definition (limit 2 CPUs, requests 1 CPU)
* run 10 slices with 5 forks each for a set of 2000 VMs

Running 10 slices with 10 forks each still leads to such a high CPU load that 2 out of 10 slices terminated with above mentioned Exception.

**Comment by shanemcd** [comment]
This whole feature has been completely rewritten. Please open a new issue if you see this with Container Groups v2.
