### ISSUE TITLE
dispatcher (exit status 1; not expected) - returned more than one InstanceGroup -- it returned 2!

### ISSUE THREAD

**Issue by uvu9Ba** [ansible/awx#9430]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

After importing postgres dump task container reports following error:
```
awx.main.models.ha.MultipleObjectsReturned: get() returned more than one InstanceGroup -- it returned 2!
```

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: kubernetes
* Ansible version:  3.0.0
* Operating System: Fedora 33
* Web Browser: Vivaldi

##### STEPS TO REPRODUCE

```
cat postgres_dump.sql_2021-02-28 | kubectl exec -n awx-intern -i awx-postgresql-postgresql-0 -- psql --username awx --dbname awx
```
Then remove the double entry like in https://github.com/ansible/awx/issues/4419 explaied. This worked in the past but not now.

##### EXPECTED RESULTS

AWX is working with older DB snapshot

##### ACTUAL RESULTS

No Job is started because of the error

##### ADDITIONAL INFORMATION

Task container logs:
```
2021-03-01 13:33:07,391 WARNING  awx.main.dispatch.periodic periodic beat started
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 154, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/run_dispatcher.py", line 55, in handle
    reaper.reap()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/dispatch/reaper.py", line 38, in reap
    (changed, me) = Instance.objects.get_or_register()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/managers.py", line 147, in get_or_register
    RegisterQueue('tower', None, 100, 0, []).register()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/register_queue.py", line 87, in register
    (ig, created, changed1) = self.get_create_update_instance_group()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/register_queue.py", line 31, in get_create_update_instance_group
    (ig, created) = InstanceGroup.objects.get_or_create(name=self.queuename)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 412, in get
    (self.model._meta.object_name, num)
awx.main.models.ha.MultipleObjectsReturned: get() returned more than one InstanceGroup -- it returned 2!
```
```
awx=# select schedule_last_run from public.main_towerschedulestate;
       schedule_last_run       
-------------------------------
 2021-03-01 12:29:34.717148+00
(1 row)
```

**Comment by uvu9Ba** [comment]
I even try to delete the other entry as well - nothing changed :(
```
awx=# select * from public.main_towerschedulestate;
 id | schedule_last_run 
----+-------------------
(0 rows)
```

**Comment by uvu9Ba** [comment]
Repated the steps but this time I set the replicas to 0 before I imported the sql dump.
Then I removed the imported schedule_last_run. And then set the replicas back to 1.

Now it works
