### ISSUE TITLE
It is not possible to delete an execution_environment if the same ee have already used in a job_template

### ISSUE THREAD

**Issue by yagomarques** [ansible/awx#9556]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
- during an Explore Test session  @tiagodread and me, detected this problem around the scenario - `EE association between organization and execution environments trying to DELETE
`

##### STEPS TO REPRODUCE
1. Create an EE 
2. Create organization and associate with the EE created on step 1. 
3. Create a project using the organization created on step 2.
4. Create a job_template using the project created on step 3.
5. Launch the job_template
6. Try to delete the EE created on step 1.

##### EXPECTED RESULTS
- the execution_environment is deleted with successfully 

##### ACTUAL RESULTS
- we are receiving the error:
```
Traceback (most recent call last):
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
awx_1_1     |     response = get_response(request)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
awx_1_1     |     response = self.process_exception_by_middleware(e, request)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
awx_1_1     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
awx_1_1     |   File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
awx_1_1     |     return func(*args, **kwds)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/transaction.py", line 240, in __exit__
awx_1_1     |     connection.commit()
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 262, in commit
awx_1_1     |     self._commit()
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 240, in _commit
awx_1_1     |     return self.connection.commit()
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
awx_1_1     |     raise dj_exc_value.with_traceback(traceback) from exc_value
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 240, in _commit
awx_1_1     |     return self.connection.commit()
awx_1_1     | django.db.utils.IntegrityError: update or delete on table "main_executionenvironment" violates foreign key constraint "main_unifiedjob_execution_environmen_b2eaf9c0_fk_main_exec" on table "main_unifiedjob"
awx_1_1     | DETAIL:  Key (id)=(5) is still referenced from table "main_unifiedjob".
```
##### ADDITIONAL INFORMATION
- we will continue to exploring the permutations for this scenario with projects, inv source etc.

**Comment by jbradberry** [comment]
All of the reference fields to EEs (Org.default_environment, Project.default_environment, JT/WFJT/Job/WFJ.execution_environment) all have `on_delete=models.SET_NULL` set.  This is part of Django's machinery for dealing with this scenario, and it is somewhat surprising that it is failing in this manner.

**Comment by jbradberry** [comment]
... It has been brought to my attention that there is a separate `polymorphic.SET_NULL`.  My bad.

**Comment by yagomarques** [comment]
@jbradberry i did the same process, but this time i received other error.

**Comment by yagomarques** [comment]
@jbradberry i did the same steps, but this time i received other error. 
```
ERROR    [---] django.request Internal Server Error: /api/v2/execution_environments/8/
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/api/generics.py", line 328, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/rest_framework/generics.py", line 217, in delete
    return self.destroy(request, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/rest_framework/mixins.py", line 91, in destroy
    self.perform_destroy(instance)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/api/generics.py", line 541, in perform_destroy
    super(DestroyAPIView, self).perform_destroy(instance)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/rest_framework/mixins.py", line 95, in perform_destroy
    instance.delete()
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/base.py", line 921, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/db/models/deletion.py", line 224, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/main/utils/polymorphic.py", line 19, in SET_NULL
    return models.SET_NULL(collector, field, sub_objs.non_polymorphic(), using)
AttributeError: 'QuerySet' object has no attribute 'non_polymorphic'
```

I ran that directly on your branch(I build a machine pointing to its branch)

**Comment by yagomarques** [comment]
I did the same steps after the new PR and **it's working!**
```
2021-03-12 19:01:14,993 INFO     [----] awx.analytics.performance request: <:DELETE '/api/v2/execution_environments/47/'>, response_time: 0.136s
```
after, i did a get to check if the `execution_environments` was deleted. 
get_result:
```
{
    "count": 0,
    "next": null,
    "previous": null,
    "results": []
}
```
