### ISSUE TITLE
Projects Unable to Sync Properly

### ISSUE THREAD

**Issue by beeankha** [ansible/awx#9559]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When attempting to sync/update a Project, the following error is output in the logs:
```
awx_1_1     | 2021-03-11 14:17:18,927 ERROR    [b3409386] awx.main.dispatch Worker failed to run task awx.main.tasks.RunProjectUpdate(*[10], **{}
awx_1_1     | Traceback (most recent call last):
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 235, in _cursor
awx_1_1     |     return self._prepare_cursor(self.create_cursor(name))
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 223, in create_cursor
awx_1_1     |     cursor = self.connection.cursor()
awx_1_1     | psycopg2.InterfaceError: connection already closed
awx_1_1     | 
awx_1_1     | The above exception was the direct cause of the following exception:
awx_1_1     | 
awx_1_1     | Traceback (most recent call last):
awx_1_1     |   File "/awx_devel/awx/main/dispatch/worker/task.py", line 90, in perform_work
awx_1_1     |     result = self.run_callable(body)
awx_1_1     |   File "/awx_devel/awx/main/dispatch/worker/task.py", line 66, in run_callable
awx_1_1     |     return _call(*args, **kwargs)
awx_1_1     |   File "/awx_devel/awx/main/tasks.py", line 824, in _wrapped
awx_1_1     |     return f(self, *args, **kwargs)
awx_1_1     |   File "/awx_devel/awx/main/tasks.py", line 1340, in run
awx_1_1     |     start_args='')  # blank field to remove encrypted passwords
awx_1_1     |   File "/awx_devel/awx/main/tasks.py", line 868, in update_model
awx_1_1     |     instance.save(update_fields=update_fields)
awx_1_1     |   File "/awx_devel/awx/main/models/projects.py", line 655, in save
awx_1_1     |     return super(ProjectUpdate, self).save(*args, **kwargs)
awx_1_1     |   File "/awx_devel/awx/main/models/unified_jobs.py", line 890, in save
awx_1_1     |     self._update_parent_instance()
awx_1_1     |   File "/awx_devel/awx/main/models/projects.py", line 544, in _update_parent_instance
awx_1_1     |     return super(ProjectUpdate, self)._update_parent_instance()
awx_1_1     |   File "/awx_devel/awx/main/models/unified_jobs.py", line 813, in _update_parent_instance
awx_1_1     |     parent_instance.save(update_fields=update_fields)
awx_1_1     |   File "/awx_devel/awx/main/models/projects.py", line 371, in save
awx_1_1     |     super(Project, self).save(*args, **kwargs)
awx_1_1     |   File "/awx_devel/awx/main/models/unified_jobs.py", line 286, in save
awx_1_1     |     super(UnifiedJobTemplate, self).save(*args, **kwargs)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/polymorphic/models.py", line 93, in save
awx_1_1     |     return super(PolymorphicModel, self).save(*args, **kwargs)
awx_1_1     |   File "/awx_devel/awx/main/models/base.py", line 320, in save
awx_1_1     |     super(PrimordialModel, self).save(*args, **kwargs)
awx_1_1     |   File "/awx_devel/awx/main/models/base.py", line 165, in save
awx_1_1     |     super(CreatedModifiedModel, self).save(*args, **kwargs)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/base.py", line 744, in save
awx_1_1     |     force_update=force_update, update_fields=update_fields)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/base.py", line 769, in save_base
awx_1_1     |     update_fields=update_fields,
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
awx_1_1     |     for receiver in self._live_receivers(sender)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
awx_1_1     |     for receiver in self._live_receivers(sender)
awx_1_1     |   File "/awx_devel/awx/main/signals.py", line 449, in activity_stream_update
awx_1_1     |     old = sender.objects.get(id=instance.id)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
awx_1_1     |     return getattr(self.get_queryset(), name)(*args, **kwargs)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
awx_1_1     |     num = len(clone)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
awx_1_1     |     self._fetch_all()
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
awx_1_1     |     self._result_cache = list(self._iterable_class(self))
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/polymorphic/query.py", line 60, in _polymorphic_iterator
awx_1_1     |     o = next(base_iter)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
awx_1_1     |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
awx_1_1     |     cursor = self.connection.cursor()
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
awx_1_1     |     return self._cursor()
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 235, in _cursor
awx_1_1     |     return self._prepare_cursor(self.create_cursor(name))
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
awx_1_1     |     raise dj_exc_value.with_traceback(traceback) from exc_value
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 235, in _cursor
awx_1_1     |     return self._prepare_cursor(self.create_cursor(name))
awx_1_1     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 223, in create_cursor
awx_1_1     |     cursor = self.connection.cursor()
awx_1_1     | django.db.utils.InterfaceError: connection already closed
awx_1_1     | 2021-03-11 14:18:29,060 ERROR    [1dbc5f38] awx.main.dispatch project_update 10 (failed) is no longer running; reaping
```

When I remove the changes that were made in [this PR](https://github.com/ansible/awx/pull/8580), Projects return to being able to get synced with no errors.

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker on linux
* Operating System: Fedora
* Web Browser: Chrome

**Comment by ryanpetrello** [comment]
😢 cc @gamuniz

**Comment by kdelee** [comment]
Closing this as stale, project updates are now working in general
