### ISSUE TITLE
Raising NotImplementedError while sending webhook

### ISSUE THREAD

**Issue by ElliotGo** [ansible/awx#964]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Failed to send webhook notification, raising NotImplementedError

##### ENVIRONMENT
* AWX version: 1.0.2.356
* AWX install method: docker
* Ansible version:  2.4.10
* Operating System: WIN 10
* Web Browser: Chrome 62.0.3202.94（64 bit）

##### STEPS TO REPRODUCE
1. add webhook notification template
2. enable "on success and on failure" notification in job template
3. run job template
4. Raising NotImplementedError while sending webhook

##### EXPECTED RESULTS

no exception while sending webhook

##### ACTUAL RESULTS

Raising NotImplementedError while sending webhook

##### ADDITIONAL INFORMATION
**Notification Template Config**
            "name": "ZOOM Webhook Notifications",
            "description": "",
            "organization": 1,
            "notification_type": "webhook",
            "notification_configuration": {
                "url": "https://addon.zoom.us/webhook/incoming/6af6dea8db0a4641ac16b66dd9319b8d",
                "headers": {
                    "X-Zoom-Token": "nuEI218PBtxRk15v",
                    "Content-Type": "application/json",
                    "Accept": "Application/json"
                },
                "use_tls": false,
                "use_ssl": false

**Exceptions**
```
2018-01-11 06:34:37,441 ERROR    awx.main.tasks Task awx.main.tasks.handle_work_success encountered exception.
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 357, in handle_work_success
    _send_notification_templates(instance, 'succeeded')
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 341, in _send_notification_templates
    raise NotImplementedError("build_notification_%s_message() does not exist" % status_str)
NotImplementedError: build_notification_succeeded_message() does not exist
2018-01-11 06:34:37,441 ERROR    awx.main.tasks Task awx.main.tasks.handle_work_success encountered exception.
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 357, in handle_work_success
    _send_notification_templates(instance, 'succeeded')
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 341, in _send_notification_templates
    raise NotImplementedError("build_notification_%s_message() does not exist" % status_str)
NotImplementedError: build_notification_succeeded_message() does not exist
[2018-01-11 06:34:37,441: ERROR/ForkPoolWorker-513] Task awx.main.tasks.handle_work_success encountered exception.
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 357, in handle_work_success
    _send_notification_templates(instance, 'succeeded')
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 341, in _send_notification_templates
    raise NotImplementedError("build_notification_%s_message() does not exist" % status_str)
NotImplementedError: build_notification_succeeded_message() does not exist
[2018-01-11 06:34:37,441: ERROR/ForkPoolWorker-513] Task awx.main.tasks.handle_work_success[15735be5-7f25-4340-ab3a-970831d0244e] raised unexpected: NotImplementedError('build_notification_succeeded_message() does not exist',)
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 357, in handle_work_success
    _send_notification_templates(instance, 'succeeded')
  File "/usr/lib/python2.7/site-packages/awx/main/tasks.py", line 341, in _send_notification_templates
    raise NotImplementedError("build_notification_%s_message() does not exist" % status_str)
NotImplementedError: build_notification_succeeded_message() does not exist
```

**Comment by gitevanx** [comment]
I am running into the same problem.
ENVIRONMENT
- AWX version: 1.0.2.327
- AWX install method: docker
- Ansible version: 2.4.2.0
- Operating System: CentOS Linux release 7.4.1708 
- Web Browser: Chrome 63.0.3239.132 (Official Build) (64-bit)

**Comment by wwitzel3** [comment]
Some changes were merged in that fixed some issues with notifications. Can you please confirm if you are still seeing this error with the latest devel branch?
