### ISSUE TITLE
AWX in K8s: Permission denied error when syncing inventory from project

### ISSUE THREAD

**Issue by shanemcd** [ansible/awx#9733]
I ran into this when debugging https://github.com/ansible/awx/issues/9704

```
Traceback (most recent call last):
  File "/awx_devel/awx/main/tasks.py", line 1476, in run
    self.post_run_hook(self.instance, status)
  File "/awx_devel/awx/main/tasks.py", line 2347, in post_run_hook
    self.make_local_copy(instance, self.job_private_data_dir)
  File "/awx_devel/awx/main/tasks.py", line 2282, in make_local_copy
    source_branch = git_repo.create_head(tmp_branch_name, p.scm_revision)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/git/repo/base.py", line 386, in create_head
    return Head.create(self, path, commit, force, logmsg)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/git/refs/symbolic.py", line 543, in create
    return cls._create(repo, path, cls._resolve_ref_on_create, reference, force, logmsg)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/git/refs/symbolic.py", line 510, in _create
    ref.set_reference(target, logmsg)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/git/refs/symbolic.py", line 326, in set_reference
    assure_directory_exists(fpath, is_file=True)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/git/util.py", line 177, in assure_directory_exists
    os.makedirs(path, exist_ok=True)
  File "/usr/lib64/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/lib/awx/projects/_8__httpsgithubcomansibletest_playbooksgit/.git/refs/heads/awx_internal'
```

**Comment by ashnehete** [comment]
I am still seeing this error on Kubernetes
```
awx-operator=0.9.0
awx-image=quay.io/ansible/awx:19.1.0
awx-ee=quay.io/ansible/awx-ee:0.2.0
```

Any possible solutions because I think I'm using the latest version for all.

**Comment by shenxg13** [comment]
hi, i got this issue in 19.4.0, do you have any solutions, thanks.

**Comment by maveleo** [comment]
@shenxg13  do you have a workaround ?

**Comment by andreasbourges** [comment]
any known solution to this problem ?

**Comment by maveleo** [comment]
> any known solution to this problem ?

Please, try adding the security_context 

```
security_context_settings:
  runAsUser: 1000
  runAsGroup: 0
```

**Comment by andreasbourges** [comment]
Hi,

 

.thanks for the suggestion! I modified my awx-deploy.yaml and deployed it
again, but:

 

Every 1.0s: kubectl get pods
net04-mgmt-vm: Thu Jul 28 08:51:50 2022

 

NAME                                               READY   STATUS
RESTARTS        AGE

awx-postgres-0                                     1/1     Running
2 (22h ago)     13d

awx-7dd9bf96c7-ml7zf                               4/4     Running
4 (22h ago)     5d16h

awx-operator-controller-manager-7594795b6b-d7kb9   2/2     Running
12 (22h ago)    35d

awx-ccb94c5bc-g5zlr                                0/4
Init:CrashLoopBackOff   6 (3m53s ago)   9m40s

 

 

I'm somewhat lost - any hint on how to troubleshoot this?

Could it be, that this is not supported on k3s ?
