### ISSUE TITLE
Management Job "Cleanup Job Details" fails

### ISSUE THREAD

**Issue by larrybg** [ansible/awx#9750]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Management Job "Cleanup Job Details" fails

##### ENVIRONMENT
* AWX version: 15.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.13
* Operating System: Mac
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Run maintenance job

##### EXPECTED RESULTS
Removes job's history and shrinks database size

##### ACTUAL RESULTS

Job is failing

##### ADDITIONAL INFORMATION
Job details:
`Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DataCorrupted: invalid page in block 16228707 of relation base/16385/21150
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 154, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/cleanup_jobs.py", line 254, in handle
    skipped, deleted = getattr(self, 'cleanup_%s' % m)()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/cleanup_jobs.py", line 81, in cleanup_jobs
    _, models_deleted = collector.delete()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/deletion.py", line 168, in delete
    count = qs._raw_delete(using=self.using)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 725, in _raw_delete
    return sql.DeleteQuery(self.model).delete_qs(self, using)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/sql/subqueries.py", line 75, in delete_qs
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.InternalError: invalid page in block 16228707 of relation base/16385/21150`

**Comment by ryanpetrello** [comment]
> django.db.utils.InternalError: invalid page in block 16228707 of relation base/16385/21150

Looks like your database has suffered some corruption (or there's potential disk corruption) 😢 

If you need help troubleshooting an AWX install or postgres setup, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
