### ISSUE TITLE
Job Fail sometimes - 19.0.0 - Openshift

### ISSUE THREAD

**Issue by dperez-sct** [ansible/awx#9860]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When execute a template job, it fails with (for us) useless info

##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: openshift 4
* Ansible version:  ???

##### STEPS TO REPRODUCE
Execute the template.

##### EXPECTED RESULTS
Job executes and work.

##### ACTUAL RESULTS
Job fail with this info:

```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1397, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2957, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3008, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Pod Running
```

##### ADDITIONAL INFORMATION

When execute the job, a pod deploy over openshift, show this info and go down/ fail the job
`/run.sh: line 3:      18 Killed                  ansible-runner worker --private-data-dir=/runner`

Sometimes (1 of 10) all work...

I don't know if this problem is only our problem or if it is a bug.
The awx it's deployed from scratch, following the manual step by step.

If anybody need more info, please tell me.

**Comment by dperez-sct** [comment]
Sorry, memory limit too low.

Fixed increasing the memory limits.
