### ISSUE TITLE
cannot build the UI 

### ISSUE THREAD

**Issue by sysnasri** [ansible/awx#9877]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY

While installing with docker containers in the following section "Clean and Build UI" , I encountered with the following errors. 

```
[root@ansible-awx ~]# docker exec tools_awx_1 make clean-ui
rm -rf node_modules
rm -rf awx/ui_next/node_modules
rm -rf awx/ui_next/build
rm -rf awx/ui_next/src/locales/_build
rm -rf awx/ui_next/.ui-built
[root@ansible-awx ~]# docker exec tools_awx_1 make ui-devel
npm --prefix awx/ui_next --loglevel warn --ignore-scripts install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2048 packages from 889 contributors and audited 2056 packages in 100.251s

108 packages are looking for funding
  run `npm fund` for details

found 5 vulnerabilities (4 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
make[1]: Entering directory '/awx_devel'
npm --prefix awx/ui_next --loglevel warn run compile-strings

> ui_next@0.1.0 compile-strings /awx_devel/awx/ui_next
> lingui compile

Compiling message catalogs…
Done!
npm --prefix awx/ui_next --loglevel warn run build

> ui_next@0.1.0 build /awx_devel/awx/ui_next
> INLINE_RUNTIME_CHUNK=false react-scripts build

Creating an optimized production build...
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:832:20)
    at ChildProcess.target.send (internal/child_process.js:703:19)
    at ChildProcessWorker.send (/awx_devel/awx/ui_next/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/ChildProcessWorker.js:291:17)
    at WorkerPool.send (/awx_devel/awx/ui_next/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/WorkerPool.js:32:34)
    at Farm._process (/awx_devel/awx/ui_next/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/Farm.js:129:10)
    at Farm._enqueue (/awx_devel/awx/ui_next/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/Farm.js:152:10)
    at Farm._push (/awx_devel/awx/ui_next/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/Farm.js:159:12)
    at /awx_devel/awx/ui_next/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/Farm.js:90:14
    at new Promise (<anonymous>)
    at Farm.doWork (/awx_devel/awx/ui_next/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/Farm.js:56:12)
    at JestWorker._callFunctionWithArgs (/awx_devel/awx/ui_next/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/index.js:143:23)
    at TaskRunner.runTask (/awx_devel/awx/ui_next/node_modules/terser-webpack-plugin/dist/TaskRunner.js:41:26)
    at enqueue (/awx_devel/awx/ui_next/node_modules/terser-webpack-plugin/dist/TaskRunner.js:89:35)
    at /awx_devel/awx/ui_next/node_modules/terser-webpack-plugin/dist/TaskRunner.js:113:86
Emitted 'error' event on ChildProcess instance at:
    at internal/child_process.js:836:39
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ui_next@0.1.0 build: `INLINE_RUNTIME_CHUNK=false react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ui_next@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/lib/awx/.npm/_logs/2021-04-10T14_19_53_955Z-debug.log
make[1]: *** [Makefile:398: awx/ui_next/.ui-built] Error 1
make[1]: Leaving directory '/awx_devel'
make: *** [Makefile:410: ui-devel] Error 2
```

##### ENVIRONMENT
* AWX version: latest
* AWX install method:  developer environment
* AWX deployment target: docker
* Operating System: centos7 
* Web Browser:

**Comment by shanemcd** [comment]
I am not able to produce this. I'm guessing either:

- Hiccup with NPM
- Your system ran out of memory. 

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by Craftoncu** [comment]
Got it reproduced. @shanemcd your guess wasn't wrong. 
Server must run out of memory.
Adding some swap solves the issue.

I decreased server RAM periodically from 10GiB to 4GiB. Onto 4 GiB the build process crashed.
Adding 1 GiB swap did the job.

**Finally we need 4GiB of RAM**

**Comment by sysnasri** [comment]
Yes probably it relates to swap , the server does not have swap space.

**Comment by Craftoncu** [comment]
U missunderstood.  The swap isn't the solution.
The swap is a dirty quick fix. 

I think you will need more RAM anyway

**Comment by sysnasri** [comment]
I know but the server has enough memory 4 Gig,  I have also increased it let me try I'll inform you.

**Comment by sysnasri** [comment]
I have installed it but the web UI is not accesible
https://IP :8043/#/home

![image](https://user-images.githubusercontent.com/73346319/115108079-c5067900-9f83-11eb-892c-9429a518c2bb.png)

**Comment by sysnasri** [comment]
Any idea about this?

**Comment by garba345** [comment]
any updates here?
