### ISSUE TITLE
Frequent Vault Lookup Errors

### ISSUE THREAD

**Issue by techBeck03** [ansible/awx#9915]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I'm using Vault lookups within my credentials tied to various playbooks and constantly get Errors related to these lookups within my jobs.  It happens every time if I try to relaunch a failed job that's using a credential with a Vault lookup.  It also happens frequently on newly launched jobs.

If I relaunch the Errored job again then it will work just fine.

##### ENVIRONMENT
* AWX version: `19.0.0`
* AWX install method: `awx-operator`
* Ansible version:  `2.11`
* Operating System: `MacOS`
* Web Browser: `Chrome`

##### STEPS TO REPRODUCE

Launch a job using a credential with Vault lookups

##### EXPECTED RESULTS

Job should launch without error

##### ACTUAL RESULTS

```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1332, in run
    passwords = self.build_passwords(self.instance, kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1495, in build_passwords
    value = runtime_passwords.get(field, cred.get_input('password' if field == 'ssh_password' else field, default=''))
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/models/credential/__init__.py", line 273, in get_input
    return self._get_dynamic_input(field_name)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/models/credential/__init__.py", line 301, in _get_dynamic_input
    return input_source.get_input_value()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/models/credential/__init__.py", line 1203, in get_input_value
    return backend(**backend_kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/credential_plugins/hashivault.py", line 223, in kv_backend
    raise_for_status(response)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/credential_plugins/plugin.py", line 12, in raise_for_status
    resp.raise_for_status()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://infra-vault.auslab.cisco.com/v1/infra/data/ad_bind_admin
```

##### ADDITIONAL INFORMATION

I did deploy my awx cluster with multiple `tower_replicas: 2` so I'm not sure if that's a factor.

**EDIT**:

I scaled my awx deployment replicas to `1` and still have this issue so that does not appear to be related to the problem.

**Comment by shanemcd** [comment]
Hello @techBeck03 - we haven't heard any other reports of this lately. It kind of feels like you might not have the config quite right. I don't think we could help without seeing more about what you're actually doing. This might be a good post either on IRC or our mailing list:

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project

**Comment by techBeck03** [comment]
The config is straight forward and it works some times but not others indicating that my config is valid enough to resolve credentials.  What additional info would you like to see?

As an overall observation, this issue sure was closed very quickly without any real investigation other than saying "we haven't heard any other reports of this lately"..... I guess if no one has complained about something before it must not be an issue 🤷‍♂️
