### ISSUE TITLE
emil notification problem  on ansible-awx

### ISSUE THREAD

**Issue by sina-admin** [ansible/awx#9939]
hello
can anyone help me?
I have faced a problem on ansible awx. when i set a email notification on ansible awx and test it, that  has been failed.
please help me... my error log is:

2021-04-18 23:29:33,537 DEBUG    awx.main.dispatch task c008decb-4eb4-43f9-9b2c-6a920fd375cd starting awx.main.tasks.send_notifications(*[[35]])
2021-04-18 23:29:38,765 ERROR    awx.main.tasks Send Notification Failed [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 342, in send_notifications
    sent = notification.notification_template.send(notification.subject, notification.body)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/notifications.py", line 194, in send
    return backend_obj.send_messages([notification_obj])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 63, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/lib64/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib64/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib64/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/lib64/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by shanemcd** [comment]
> `Name or service not known` <- Looks like AWX can't reach your SMTP server? 

This is an issue tracker for bugs in AWX itself. You may have better luck troubleshooting your environment on IRC or the mailing list.

http://webchat.freenode.net/?channels=ansible-awx
https://groups.google.com/forum/#!forum/awx-project
