### ISSUE TITLE
19.0.0 Docker install fails during Clean and Build UI

### ISSUE THREAD

**Issue by andresch26** [ansible/awx#9968]
ISSUE TYPE

    Bug Report

SUMMARY

Install fails during Clean and Build UI "docker exec tools_awx_1 make clean-ui ui-devel"
ENVIRONMENT

    AWX version: 19.0.0
    AWX install method: docker on linux
    Ansible version: 2.10.7
    Operating System: Centos Linux 7
    Web Browser: N/A

STEPS TO REPRODUCE

I followed the install steps on https://github.com/ansible/awx/blob/19.0.0/tools/docker-compose/README.md
  - Set tools/docker-compose/inventory variables for pg_password & secret_key
  - make docker-compose-build
  - make docker-compose
  - Correct for nginx user errors as per bug #9552
  - docker exec tools_awx_1 make clean-ui ui-devel

EXPECTED RESULTS

Build UI and login in to AWX

ACTUAL RESULTS

# docker exec tools_awx_1 make clean-ui ui-devel
  rm -rf node_modules
  rm -rf awx/ui_next/node_modules
  rm -rf awx/ui_next/build
  rm -rf awx/ui_next/src/locales/_build
  rm -rf awx/ui_next/.ui-built
  npm --prefix awx/ui_next --loglevel warn --ignore-scripts install
  npm ERR! cb() never called!
  
  npm ERR! This is an error with npm itself. Please report this error at:
  npm ERR!     <https://npm.community>
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /var/lib/awx/.npm/_logs/2021-04-21T12_07_15_898Z-debug.log
  make: *** [Makefile:395: awx/ui_next/node_modules] Error 1

ADDITIONAL INFORMATION
Last few lines in log file - /var/lib/awx/.npm/_logs/2021-04-21T12_07_15_898Z-debug.log
I've attempted this 3 different times, always failing at roughly the same point.
  27968 silly extract @patternfly/react-tokens@4.9.26 extracted to /awx_devel/awx/ui_next/node_modules/.staging/@patternfly/react-tokens-99450260 (19726ms)
  27969 timing npm Completed in 76260ms
  27970 error cb() never called!
  27971 error This is an error with npm itself. Please report this error at:
  27972 error <https://npm.community>

UI to https://<host_fqdn>:8043 displays:
  <% if (process.env.NODE_ENV === 'production') { %> <% } %> <% if (process.env.NODE_ENV === 'production') { %>
  <% } else { %>
  <% } %>

**Comment by shanemcd** [comment]
Looks similar to https://github.com/ansible/awx/issues/9877 - Try adding more memory.

**Comment by andresch26** [comment]
Thanks for the suggestion. I increased from 4GB to 16GB with the same result

# cat /proc/meminfo
MemTotal:       16266760 kB
MemFree:        10581692 kB
MemAvailable:   13179736 kB

checking htop during the install I can see swap isn't used, and mem stays below 2.7Gb

**Comment by shanemcd** [comment]
Dang. I'm out of ideas then. Leaving this open in case others run into this.

**Comment by andresch26** [comment]
Interestingly enough i re-ran `ui-devel` a second time, after it failed the first time, and found a bit more information about where it is failing........ or at least I think I have

```bash-4.4# make ui-devel
make[1]: Entering directory '/awx_devel'
npm --prefix awx/ui_next --loglevel warn run compile-strings

> ui_next@0.1.0 compile-strings /awx_devel/awx/ui_next
> lingui compile

sh: lingui: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! ui_next@0.1.0 compile-strings: `lingui compile`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ui_next@0.1.0 compile-strings script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/lib/awx/.npm/_logs/2021-04-22T05_35_29_398Z-debug.log
make[1]: *** [Makefile:398: awx/ui_next/.ui-built] Error 1
make[1]: Leaving directory '/awx_devel'
make: *** [Makefile:411: ui-devel] Error 2
```
--debug log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   '--prefix',
1 verbose cli   'awx/ui_next',
1 verbose cli   '--loglevel',
1 verbose cli   'warn',
1 verbose cli   'run',
1 verbose cli   'compile-strings'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.15.1
4 verbose run-script [ 'precompile-strings', 'compile-strings', 'postcompile-strings' ]
5 info lifecycle ui_next@0.1.0~precompile-strings: ui_next@0.1.0
6 info lifecycle ui_next@0.1.0~compile-strings: ui_next@0.1.0
7 verbose lifecycle ui_next@0.1.0~compile-strings: unsafe-perm in lifecycle true
8 verbose lifecycle ui_next@0.1.0~compile-strings: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/awx_devel/awx/ui_next/node_modules/.bin:/var/lib/awx/venv/awx/bin/:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle ui_next@0.1.0~compile-strings: CWD: /awx_devel/awx/ui_next
10 silly lifecycle ui_next@0.1.0~compile-strings: Args: [ '-c', 'lingui compile' ]
11 info lifecycle ui_next@0.1.0~compile-strings: Failed to exec compile-strings script
12 verbose stack Error: ui_next@0.1.0 compile-strings: `lingui compile`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:315:20)
12 verbose stack     at maybeClose (internal/child_process.js:1048:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
13 verbose pkgid ui_next@0.1.0
14 verbose cwd /awx_devel
15 verbose Linux 3.10.0-1160.24.1.el7.x86_64
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "--prefix" "awx/ui_next" "--loglevel" "warn" "run" "compile-strings"
17 verbose node v14.15.1
18 verbose npm  v6.14.8
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error ui_next@0.1.0 compile-strings: `lingui compile`
23 error spawn ENOENT
24 error Failed at the ui_next@0.1.0 compile-strings script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```


I will post anything I find here.

**Comment by shanemcd** [comment]
It'd be great if you could format your code with markdown https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by andresch26** [comment]
fair enough... corrected.. thanks for the reminder

**Comment by mabashian** [comment]
Node/NPM versions look good to me.

> sh: lingui: command not found

This odd and indicates that lingui hasn't properly installed when we get to this point in the build process.  Were there any errors in the log as a result of `npm install`?

**Comment by andresch26** [comment]
Appologises if I'm looking in the wrong area, but I do not see errors during the `npm install` in `/var/log/dnf.log`, or when the npm command is run part of the `ui-devel` command.  Please let me know if I've missed anything, or if there's anything I may do to help!  ~Thanks

dnf.log
```
2021-04-13T11:19:31Z DEBUG --> Finished dependency resolution
2021-04-13T11:19:31Z DDEBUG timer: depsolve: 1160 ms
2021-04-13T11:19:31Z INFO Dependencies resolved.
2021-04-13T11:19:31Z INFO =======================================================================================================
 Package                     Arch    Version                                           Repo        Size
=======================================================================================================
Installing:
........
 npm                         x86_64  1:6.14.11-1.10.24.0.1.module_el8.3.0+717+fa496f1d appstream  3.7 M
........
Installed:
npm-1:6.14.11-1.10.24.0.1.module_el8.3.0+717+fa496f1d.x86_64
........
2021-04-13T11:21:05Z DEBUG ---> Package npm.x86_64 1:6.14.11-1.10.24.0.1.module_el8.3.0+717+fa496f1d will be erased
2021-04-13T11:21:05Z DEBUG --> Finished dependency resolution
2021-04-13T11:21:05Z DDEBUG timer: depsolve: 37 ms
2021-04-13T11:21:05Z INFO Dependencies resolved.

```


ui-devel command:

```
bash-4.4# npm --prefix awx/ui_next --loglevel verbose --ignore-scripts install
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   '--prefix',
npm verb cli   'awx/ui_next',
npm verb cli   '--loglevel',
npm verb cli   'verbose',
npm verb cli   '--ignore-scripts',
npm verb cli   'install'
npm verb cli ]
npm info using npm@6.14.8
npm info using node@v14.15.1
npm verb npm-session f539b3c63539f24a
npm info lifecycle ui_next@0.1.0~preinstall: ui_next@0.1.0
npm timing stage:loadCurrentTree Completed in 27ms
```

**Comment by unixplex** [comment]
can you pls share the inventory file entry

**Comment by andresch26** [comment]
Sure... this is the sort of inventory file I am specifying:

```
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python3"

[all:vars]

# AWX-Managed Database Settings
# If left blank, these will be generated upon install.
# Values are written out to tools/docker-compose/_sources/secrets/
# pg_password=""
 broadcast_websocket_secret="nh3RrG46"
 secret_key="Lq9MALuT"

# External Database Settings
# pg_host=""
 pg_password="awxpassw0rd"
# pg_username=""
# pg_hostname=""

# awx_image="quay.io/awx/awx_devel"
# migrate_local_docker=false
```

**Comment by unixplex** [comment]
okay from where did you get the value of broadcast_websocket_secret ?

**Comment by andresch26** [comment]
To be honest, I don't remeber at this point. I've tried so many different ways. Is there a way you'd recommend?

**Comment by mrzogs** [comment]
Is there an update to this, I have the same issue?

**Comment by garba345** [comment]
any updates?
