### ISSUE TITLE
OSError: [Errno 40] Too many levels of symbolic links

### ISSUE THREAD

**Issue by breeze7086** [ansible/awx#9983]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Hi all,

I have installed the AWX by following the installation guide of this project.
When I launch a template with an inventory, I get error logs from the container of awx-task like

`2021-04-22 07:46:50,286 DEBUG    [3aa217cbe44c4aacb2e7ed70e603cf5f] awx.analytics.job_lifecycle job-64 preparing playbook
2021-04-22 07:46:50,418 DEBUG    [3aa217cbe44c4aacb2e7ed70e603cf5f] awx.analytics.job_lifecycle job-64 running playbook
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3018, in transmit
    ansible_runner.interface.run(streamer='transmit', _output=_socket.makefile('wb'), **self.runner_params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/ansible_runner/interface.py", line 243, in run
    r.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/ansible_runner/streaming.py", line 53, in run
    self._output.write(utils.stream_dir(self.private_data_dir))
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/ansible_runner/utils.py", line 95, in stream_dir
    archive.write(os.path.join(dirpath, fname), arcname=os.path.join(relpath, fname))
  File "/usr/lib64/python3.8/zipfile.py", line 1740, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/usr/lib64/python3.8/zipfile.py", line 522, in from_file
    st = os.stat(filename)
OSError: [Errno 40] Too many levels of symbolic links: '/tmp/pdd_wrapper_64_82dc9h9k/awx_64_ser8xcjz/project/modules/modules'
2021-04-22 07:46:56,428 DEBUG    [ffbbd9d21f2c42ecb1998f5c198f3d98] awx.main.dispatch task a59dcc5f-fb8a-4234-8899-c8bb4fa76ce6 starting awx.main.scheduler.tasks.run_task_manager(*[])
2021-04-22 07:46:56,430 DEBUG    [ffbbd9d21f2c42ecb1998f5c198f3d98] awx.main.scheduler Running Tower task manager.
2021-04-22 07:46:56,450 DEBUG    [ffbbd9d21f2c42ecb1998f5c198f3d98] awx.main.scheduler Starting Scheduler
Instance Group already registered tower
(changed: True)
2021-04-22 07:46:56,472 WARNING  [ffbbd9d21f2c42ecb1998f5c198f3d98] awx.main.dispatch scaling up worker pid:653
2021-04-22 07:46:56,478 DEBUG    [ffbbd9d21f2c42ecb1998f5c198f3d98] awx.main.dispatch task 0db6c385-976b-4ce4-afa1-b8d4e3ca7cc5 starting awx.main.analytics.analytics_tasks.send_subsystem_metrics(*[])
2021-04-22 07:46:56,506 DEBUG    [ffbbd9d21f2c42ecb1998f5c198f3d98] awx.main.scheduler Finishing Scheduler`

As a reference, I can run an ad-hoc module like a shell command towards inventory hosts.

##### ENVIRONMENT
* AWX version: <  AWX 19.0.0  >
* AWX install method: minikube
* Ansible version:  ansible 2.9.4
* Operating System: RHEL 7.9
* Web Browser: Edge

##### STEPS TO REPRODUCE

1, Install a cluster by following the installation guide
2, Create an inventory with hosts
3, Create a project with my Ansible repository
4, Create a template with the project of above
5, Launch the template with the inventory (Failed on this step)

##### EXPECTED RESULTS

The playbook can be executed successfully.

##### ACTUAL RESULTS

The Job keeps in running state without any output on the console.

**Comment by shanemcd** [comment]
Do you have a recursive symlink somewhere in your project?

**Comment by breeze7086** [comment]
Thank you for your hint! @shanemcd 
I finally found out the recursive symlink within my project, after deleting it, AWX works.
